### ISSUE TITLE
txt 未能成功加载

### ISSUE THREAD

**Issue by forrestneo** [chatchat-space/Langchain-Chatchat#103]
hinese. Creating a new one with MEAN pooling.
合并文本 - 副本.txt 未能成功加载
Traceback (most recent call last):
  File "/home/zsd/.local/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/zsd/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/home/zsd/.local/lib/python3.10/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/zsd/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zsd/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/zsd/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/zsd/langchain-ChatGLM/webui.py", line 31, in get_answer
    resp, history = kb.get_knowledge_based_answer(
  File "/home/zsd/langchain-ChatGLM/knowledge_based_chatglm.py", line 95, in get_knowledge_based_answer
    retriever=vector_store.as_retriever(search_kwargs={"k": VECTOR_SEARCH_TOP_K}),
AttributeError: 'NoneType' object has no attribute 'as_retriever'

**Comment by imClumsyPanda** [comment]
如果是ubuntu系统，建议检查文件中是否有特殊字符或编码不是utf8

**Comment by imClumsyPanda** [comment]
另外目前项目代码已更新，建议使用最新版代码测试

**Comment by suntea233** [comment]
我也遇到了，我上传的是txt文件，bug是
`TypeError: cannot unpack non-iterable NoneType object`
