### ISSUE TITLE
上传文档（txt、word）添加至向量库报错[BUG]

### ISSUE THREAD

**Issue by MOLIZHU2023** [chatchat-space/Langchain-Chatchat#1059]
本地部署，LLM模型正常启动，推理正常，知识库功能中，上传文档（txt、word）到知识库成功，点击添加到向量库报错，代码如下：

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback:
File "D:\your_path\env_name\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "D:\Langchain\langchain-ChatGLM\webui.py", line 92, in <module>
    pages[selected_page]["func"](api)
File "D:\Langchain\langchain-ChatGLM\webui_pages\knowledge_base\knowledge_base.py", line 201, in knowledge_base_page
    api.update_kb_doc(kb, row["file_name"])
File "D:\Langchain\langchain-ChatGLM\webui_pages\utils.py", line 535, in update_kb_doc
    return response.json()
File "D:\your_path\env_name\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
File "D:\your_path\env_name\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
File "D:\your_path\env_name\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "D:\your_path\env_name\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B 32K
- 使用的 Embedding 模型：M3E base
- 操作系统及版本 / Operating system and version:Win11

**Comment by sonicno1** [comment]
添加 pdf时报错  AttributeError: 'NoneType' object has no attribute 'json'

**Comment by Halflifefa** [comment]
+1

**Comment by leexk312** [comment]
+1 希望作者能回复

**Comment by liunux4odoo** [comment]
> 本地部署，LLM模型正常启动，推理正常，知识库功能中，上传文档（txt、word）到知识库成功，点击添加到向量库报错，代码如下：
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0) Traceback: File "D:\your_path\env_name\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script exec(code, module.**dict**) File "D:\Langchain\langchain-ChatGLM\webui.py", line 92, in pages[selected_page]["func"](api) File "D:\Langchain\langchain-ChatGLM\webui_pages\knowledge_base\knowledge_base.py", line 201, in knowledge_base_page api.update_kb_doc(kb, row["file_name"]) File "D:\Langchain\langchain-ChatGLM\webui_pages\utils.py", line 535, in update_kb_doc return response.json() File "D:\your_path\env_name\lib\site-packages\httpx_models.py", line 756, in json return jsonlib.loads(self.text, **kwargs) File "D:\your_path\env_name\lib\json__init__.py", line 357, in loads return _default_decoder.decode(s) File "D:\your_path\env_name\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "D:\your_path\env_name\lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None
> 
> * 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B 32K
> * 使用的 Embedding 模型：M3E base
> * 操作系统及版本 / Operating system and version:Win11

请确认api.py正常启动，并在其中测试一下接口是否正常返回：
![api docs](https://github.com/chatchat-space/Langchain-Chatchat/raw/master/img/fastapi_docs_020_0.png)

**Comment by liunux4odoo** [comment]
> 添加 pdf时报错 AttributeError: 'NoneType' object has no attribute 'json'

参见[项目依赖](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/INSTALL.md#%E9%A1%B9%E7%9B%AE%E4%BE%9D%E8%B5%96)

使用 langchain.document_loaders.UnstructuredFileLoader 进行 .docx 等格式非结构化文件接入时，可能需要依据文档进行其他依赖包的安装，请参考 [langchain 文档](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/unstructured_file.html)。

**Comment by sonicno1** [comment]
添加pdf文件向量时，报错
lib\site-packages\spacy\language.py", line 1110, in make_doc
    raise ValueError(
ValueError: [E088] Text of length 3019309 exceeds maximum of 1000000. The parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you can check whether your inputs are too long by checking `len(text)`.

前端：
lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by syusama** [comment]
+1，文件向量化的时候报错，也是json相关报错

**Comment by imClumsyPanda** [comment]
> 添加pdf文件向量时，报错 lib\site-packages\spacy\language.py", line 1110, in make_doc raise ValueError( ValueError: [E088] Text of length 3019309 exceeds maximum of 1000000. The parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you can check whether your inputs are too long by checking `len(text)`.
> 
> 前端： lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

看起来是分词过程单段过长的问题，项目中默认使用 [SpacyTextSplitter](https://api.python.langchain.com/en/latest/text_splitter/langchain.text_splitter.SpacyTextSplitter.html#langchain.text_splitter.SpacyTextSplitter)，在缺少相关依赖时，自动改用 [RecursiveCharacterTextSplitter](https://api.python.langchain.com/en/latest/text_splitter/langchain.text_splitter.RecursiveCharacterTextSplitter.html#langchain.text_splitter.RecursiveCharacterTextSplitter)。

如果 SpacyTextSplitter 的依赖未安装完整，建议执行以下命令后重试上传该 pdf 是否仍存在相同报错：
```shell
$ pip install spacy
$ python -m spacy download zh_core_web_sm
```

如果 SpacyTextSplitter 依赖已完整安装后仍存在该问题，请反馈一下，我看看是不是需要从文件中加载文本后先截断再运行 textsplitter。

**Comment by luning00** [comment]
UnstructuredFileLoader
INFO:     127.0.0.1:52444 - "POST /knowledge_base/upload_doc HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/airdoc-llm/server/knowledge_base/kb_doc_api.py", line 58, in upload_doc
    kb.add_doc(kb_file)
  File "/data/airdoc-llm/server/knowledge_base/kb_service/base.py", line 78, in add_doc
    docs = kb_file.file2text()
  File "/data/airdoc-llm/server/knowledge_base/utils.py", line 120, in file2text
    docs = loader.load_and_split(text_splitter)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/langchain/document_loaders/base.py", line 43, in load_and_split
    docs = self.load()
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/langchain/document_loaders/unstructured.py", line 86, in load
    elements = self._get_elements()
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/langchain/document_loaders/unstructured.py", line 171, in _get_elements
    return partition(filename=self.file_path, **self.unstructured_kwargs)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/unstructured/partition/auto.py", line 287, in partition
    elements = partition_csv(filename=filename, file=file, **kwargs)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/unstructured/documents/elements.py", line 237, in wrapper
    elements = func(*args, **kwargs)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/unstructured/file_utils/filetype.py", line 630, in wrapper
    elements = func(*args, **kwargs)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/unstructured/partition/csv.py", line 50, in partition_csv
    table = pd.read_csv(filename)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2029, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 19 fields in line 40, saw 24

前端报错
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback:
File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/data/airdoc-llm/webui.py", line 56, in <module>
    pages[selected_page]["func"](api)
File "/data/airdoc-llm/webui_pages/knowledge_base/knowledge_base.py", line 138, in knowledge_base_page
    ret = api.upload_kb_doc(f, kb)
File "/data/airdoc-llm/webui_pages/utils.py", line 490, in upload_kb_doc
    return response.json()
File "/root/anaconda3/envs/py3.8/lib/python3.8/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
File "/root/anaconda3/envs/py3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
File "/root/anaconda3/envs/py3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/root/anaconda3/envs/py3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

上传20.4k大小的 txt 文件报错 转成 json格式后还是报同样的错误

**Comment by zoepao** [comment]
同报错，请问解决了不

**Comment by yang384** [comment]
我doc pdf txt   都无法添加至向量库，报错：
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by danny-zhu** [comment]
> 添加pdf文件向量时，报错 lib\site-packages\spacy\language.py", line 1110, in make_doc raise ValueError( ValueError: [E088] Text of length 3019309 exceeds maximum of 1000000. The parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you can check whether your inputs are too long by checking `len(text)`.
> 
> 前端： lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
参考 https://github.com/chatchat-space/Langchain-Chatchat/issues/1287#issuecomment-1704758907
