### ISSUE TITLE
0.2的版本启动后  connect  refused 

### ISSUE THREAD

**Issue by shujun1992** [chatchat-space/Langchain-Chatchat#1064]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by jackaihfia2334** [comment]
+1

**Comment by shujun1992** [comment]
具体报错如下:

2023-08-14 11:19:19.971 Uncaught app exception
Traceback (most recent call last):
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 100, in connect_tcp
    sock = socket.create_connection(
  File "/root/anaconda3/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/root/anaconda3/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 92, in handle_request
    raise exc
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 69, in handle_request
    stream = self._connect(request)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 117, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 99, in connect_tcp
    with map_exceptions(exc_map):
  File "/root/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/opt/langchain-ChatGLM-V2.0/Langchain-Chatchat-master/webui.py", line 57, in <module>
    pages[selected_page]["func"](api)
  File "/opt/langchain-ChatGLM-V2.0/Langchain-Chatchat-master/webui_pages/dialogue/dialogue.py", line 101, in dialogue_page
    for t in r:
  File "/opt/langchain-ChatGLM-V2.0/Langchain-Chatchat-master/webui_pages/utils.py", line 212, in _httpx_stream2generator
    with response as r:
  File "/root/anaconda3/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_api.py", line 152, in stream
    with client.stream(
  File "/root/anaconda3/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_client.py", line 857, in stream
    response = self.send(
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/root/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/langchain-ChatGLM-V2.0/langchain/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused



在虚拟环境中运行，已修改配置和初始化向量库

**Comment by muximuxi** [comment]
遇到了同样的问题~

**Comment by a656418zz** [comment]
不止如此，我ctrl+c取消了stream进程之后，就一直在命令行里报channel 4/3: open failed: connect failed: Connection refused

**Comment by Halflifefa** [comment]
+1

**Comment by jackaihfia2334** [comment]
查看一下是否启动了llm_api和api服务

**Comment by shujun1992** [comment]
llm_api和api服务启动就可以了，谢谢

**Comment by muximuxi** [comment]
请问不使用openai 也需要api key 吗，为什么设置使用模型是chatglm2,也报错：
openai_api_key=llm_model_dict[LLM_MODEL]["api_key"],
KeyError: 'api_key'
然后strealit run webui.py报错：
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**Comment by liunux4odoo** [comment]
> 请问不使用openai 也需要api key 吗，为什么设置使用模型是chatglm2,也报错： openai_api_key=llm_model_dict[LLM_MODEL]["api_key"], KeyError: 'api_key'� 然后strealit run webui.py报错： raise mapped_exc(message) from exc httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

现在本地模型不需要api_key，但model_config.llm_model_dict里每个模型要有这个键，方便以后API_KEY起作用。

**Comment by LiKe-rm** [comment]
> llm_api和api服务启动就可以了，谢谢

怎么查看有没有启动，怎么启动这两个服务丫
