### ISSUE TITLE
容器版正常启动后，对话报错

### ISSUE THREAD

**Issue by zhubao315** [chatchat-space/Langchain-Chatchat#1070]
错误信息如下：

2023-08-14 06:23:14.093 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/langchain-ChatGLM-dev/webui.py", line 57, in <module>
    pages[selected_page]["func"](api)
  File "/langchain-ChatGLM-dev/webui_pages/dialogue/dialogue.py", line 104, in dialogue_page
    chat_box.update_msg(text, streaming=False)  # 更新最终的字符串，去除光标
  File "/usr/local/lib/python3.10/dist-packages/streamlit_chatbox/messages.py", line 191, in update_msg
    old_element = self.history[history_index]["elements"][element_index]
  File "/usr/local/lib/python3.10/dist-packages/streamlit_chatbox/messages.py", line 64, in history
    return st.session_state.get(self._session_key).get(self._chat_name)
AttributeError: 'NoneType' object has no attribute 'get'

启动过程如下：

bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
current llm: chatglm2-6b-32k
Init Database...
2023-08-14 06:28:01,137 - utils.py[line:148] - INFO: Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-08-14 06:28:01,137 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
2023-08-14 06:28:05,959 - text_splitter.py[line:176] - WARNING: Created a chunk of size 462, which is longer than the specified 420
2023-08-14 06:28:05,960 - text_splitter.py[line:176] - WARNING: Created a chunk of size 511, which is longer than the specified 420
2023-08-14 06:28:05,961 - text_splitter.py[line:176] - WARNING: Created a chunk of size 428, which is longer than the specified 420
2023-08-14 06:28:05,962 - text_splitter.py[line:176] - WARNING: Created a chunk of size 923, which is longer than the specified 420
2023-08-14 06:28:05,963 - text_splitter.py[line:176] - WARNING: Created a chunk of size 494, which is longer than the specified 420
2023-08-14 06:28:05,963 - text_splitter.py[line:176] - WARNING: Created a chunk of size 513, which is longer than the specified 420
2023-08-14 06:28:06,019 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /m3e-large
2023-08-14 06:28:06,019 - SentenceTransformer.py[line:805] - WARNING: No sentence-transformers model found with name /m3e-large. Creating a new one with MEAN pooling.
2023-08-14 06:28:06,060 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpw05nvsls
2023-08-14 06:28:06,060 - instantiator.py[line:76] - INFO: Writing /tmp/tmpw05nvsls/_remote_module_non_scriptable.py
database talbes created
recreating all vector stores
UnstructuredFileLoader
page_content='Under the Concealing Surface: Detecting and Understanding Live Webcams in the Wild\n\nJINKE SONG, Beijing Jiaotong University, China QIANG LI∗, Beijing Jiaotong University, China HAINING WANG, Virginia Tech, USA LIMIN SUN, Chinese Academy of Sciences, China\n\nGiven the central role of webcams in monitoring physical surroundings, it behooves the research community to understand the characteristics of webcams’ distribution and their privacy/security implications.' metadata={'source': '/langchain-ChatGLM-dev/knowledge_base/samples/content/[SIGMETRICS 2020]Under the Concealing Surface Detecting and Understanding Live Webcams in the Wild.pdf'}
Batches: 100%|██████████| 9/9 [00:01<00:00,  8.07it/s]
2023-08-14 06:28:09,143 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-08-14 06:28:09,151 - loader.py[line:56] - INFO: Successfully loaded faiss with AVX2 support.
2023-08-14 06:28:10,283 - text_splitter.py[line:176] - WARNING: Created a chunk of size 481, which is longer than the specified 420
UnstructuredFileLoader
page_content='ChatGPT是OpenAI开发的一个大型语言模型，可以提供各种主题的信息，\n\n\n\n# 如何向 ChatGPT 提问以获得高质量答案：提示技巧工程完全指南\n\n#\n\n# 介绍\n\n我很高兴欢迎您阅读我的最新书籍《The Art of Asking ChatGPT for High-Quality Answers: A complete Guide to Prompt Engineering Techniques》。\n\n本书是一本全面指南，介绍了各种提示技术，用于从ChatGPT中生成高质量的答案。\n\n\n\n我们将探讨如何使用不同的提示工程技术来实现不同的目标。\n\nChatGPT是一款最先进的语言模型，能够生成类似人类的文本。\n\n然而，理解如何正确地向ChatGPT提问以获得我们所需的高质量输出非常重要。\n\n而这正是本书的目的。' metadata={'source': '/langchain-ChatGLM-dev/knowledge_base/samples/content/The Art of Asking ChatGPT for High-Quality Answers: A complete Guide to Prompt Engineering Techniques.txt'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.30it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.82it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 85.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.42it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.90it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.13it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 85.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 85.66it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 85.98it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 85.30it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.71it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 83.84it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.84it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.89it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 83.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.76it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 85.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 83.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 83.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.96it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.75it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 188.27it/s]
Starting LLM API Service...
>> Waiting for LLM API Service to start up.
Starting Chatchat API Service...
>> Waiting for Chatchat API Service to start up.
Starting WebUI Service...

  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.6:8501
  External URL: http://111.207.114.219:8501

2023-08-14 06:29:31,269 - _client.py[line:1013] - INFO: HTTP Request: POST http://0.0.0.0:7861/chat/chat "HTTP/1.1 200 OK"

**Comment by inksong** [comment]
@imClumsyPanda dialogue.py, line 104  check plz

**Comment by liunux4odoo** [comment]
@zhubao315 能否贴一下webui的截图，是不是使用的多会话版本？

**Comment by VignetteApril** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/28882898/941469c1-53a3-46bf-ae90-6dc846f1b50a)
这是我的webui截图，我也是遇到的同样的问题。

**Comment by Insomnia-y** [comment]
同样用docker在linux部署，遇到了完全相同的问题。

docker命令：
`docker run -d --gpus all -p 80:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.3`

报错信息：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/60568578/8fea784d-3c2d-4273-87fd-3529257b6af3)

webui截图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/60568578/8563a152-f2e0-483d-a011-01517a34e0ac)

**Comment by VignetteApril** [comment]
我的问题找到了，是因为没有足够的显存启动模型。

**Comment by blueroutecn** [comment]
registry.cn-beijing.aliyuncs.com这个如何登陆pull呀。
