### ISSUE TITLE
使用qwen模型报错 ValueError: Loading /data/data/llm/model/Qwen-7b-chat requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

### ISSUE THREAD

**Issue by jackaihfia2334** [chatchat-space/Langchain-Chatchat#1075]
root@docker-desktop:/data/data/llm/code/Langchain-Chatchat# python server/llm_api.py
2023-08-14 07:04:46,406 - llm_api.py[line:196] - INFO: {'local_model_path': '/data/data/llm/model/Qwen-7b-chat', 'api_base_url': 'http://localhost:8888/v1', 'api_key': 'EMPTY'}
2023-08-14 07:04:46,406 - llm_api.py[line:199] - INFO: 如需查看 llm_api 日志，请前往 /data/data/llm/code/Langchain-Chatchat/logs
2023-08-14 07:04:46 | ERROR | stderr | INFO:     Started server process [11556]
2023-08-14 07:04:46 | ERROR | stderr | INFO:     Waiting for application startup.
2023-08-14 07:04:46 | ERROR | stderr | INFO:     Application startup complete.
2023-08-14 07:04:46 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20001 (Press CTRL+C to quit)
2023-08-14 07:04:53 | INFO | model_worker | Loading the model ['Qwen-7b'] on worker e976587b ...
INFO:     Started server process [11557]
INFO:     Waiting for application startup.
2023-08-14 07:04:54 | ERROR | stderr | Traceback (most recent call last):
2023-08-14 07:04:54 | ERROR | stderr |   File "/data/data/llm/code/Langchain-Chatchat/server/llm_api.py", line 230, in <module>
2023-08-14 07:04:54 | ERROR | stderr |     run_model_worker(queue)
2023-08-14 07:04:54 | ERROR | stderr |   File "/data/data/llm/code/Langchain-Chatchat/server/llm_api.py", line 161, in run_model_worker
2023-08-14 07:04:54 | ERROR | stderr |     app = create_model_worker_app(*args, **kwargs)
2023-08-14 07:04:54 | ERROR | stderr |   File "/data/data/llm/code/Langchain-Chatchat/server/llm_api.py", line 99, in create_model_worker_app
2023-08-14 07:04:54 | ERROR | stderr |     worker = ModelWorker(
2023-08-14 07:04:54 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 199, in __init__
2023-08-14 07:04:54 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-08-14 07:04:54 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 237, in load_model
2023-08-14 07:04:54 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-08-14 07:04:54 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 70, in load_model
2023-08-14 07:04:54 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2023-08-14 07:04:54 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
2023-08-14 07:04:54 | ERROR | stderr |     config, kwargs = AutoConfig.from_pretrained(
2023-08-14 07:04:54 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 919, in from_pretrained
2023-08-14 07:04:54 | ERROR | stderr |     raise ValueError(
2023-08-14 07:04:54 | ERROR | stderr | ValueError: Loading /data/data/llm/model/Qwen-7b-chat requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
2023-08-14 07:04:54 | ERROR | stderr | INFO:     Shutting down
2023-08-14 07:04:54 | ERROR | stderr | INFO:     Waiting for application shutdown.
2023-08-14 07:04:54 | ERROR | stderr | INFO:     Application shutdown complete.
2023-08-14 07:04:54 | ERROR | stderr | INFO:     Finished server process [11556]

**Comment by hvne4j** [comment]
你好，我也碰到这个问题，请教下如何解决的呢

**Comment by jackaihfia2334** [comment]
在Automodel和Autotokenizer里设置trust_remote_code=True即可

**Comment by jackaihfia2334** [comment]
> 在Automodel和Autotokenizer里设置trust_remote_code=True即可

在Automodel和Autotokenizer里设置trust_remote_code=True即可

**Comment by ccly1996** [comment]
> > 在Automodel和Autotokenizer里设置trust_remote_code=True即可
> 
> 在Automodel和Autotokenizer里设置trust_remote_code=True即可

这两个文件在哪啊

**Comment by jackaihfia2334** [comment]
> > > 在Automodel和Autotokenizer里设置trust_remote_code=True即可
> > 
> > 
> > 在Automodel和Autotokenizer里设置trust_remote_code=True即可
> 
> 这两个文件在哪啊

不是两个文件，是两个函数，具体在的文件看你自己的报错信息，我的是2023-08-14 07:04:54 | ERROR | stderr | File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 70, in load_model，你可以看看我前面的error对照一下

**Comment by ccly1996** [comment]
好的谢谢


---- 回复的原邮件 ----
| 发件人 | Mao ***@***.***> |
| 发送日期 | 2023年08月15日 17:25 |
| 收件人 | chatchat-space/Langchain-Chatchat ***@***.***> |
| 抄送人 | ccly1996 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [chatchat-space/Langchain-Chatchat] 使用qwen模型报错 ValueError: Loading /data/data/llm/model/Qwen-7b-chat requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to r |

在Automodel和Autotokenizer里设置trust_remote_code=True即可

在Automodel和Autotokenizer里设置trust_remote_code=True即可

这两个文件在哪啊

不是两个文件，是两个函数，具体在的文件看你自己的报错信息，我的是2023-08-14 07:04:54 | ERROR | stderr | File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 70, in load_model，你可以看看我前面的error对照一下

**Comment by energy888666** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44359146/1fd90a8f-3470-4943-8d76-2a4348514f99) 
 我这个咋还是不行呢 ??

> > > > 在Automodel和Autotokenizer里设置trust_remote_code=True即可
> > > 
> > > 
> > > 在Automodel和Autotokenizer里设置trust_remote_code=True即可
> > 
> > 
> > 这两个文件在哪啊
> 
> 不是两个文件，是两个函数，具体在文件中看你自己的报错信息，我是2023-08-14 07:04:54 | 错误 | 标准错误| 文件“/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py”，第70行，在load_model中，你可以看看我前面的错误对照一下
