### ISSUE TITLE
[BUG] v4版本，新建知识库报错AttributeError: 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by wwwhhh93** [chatchat-space/Langchain-Chatchat#1076]
使用的是autodl上的v4镜像，在webui界面单击新建知识库的新建按钮后报错：
Traceback (most recent call last):
  File "/root/pyenv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/root/langchain-ChatGLM/webui.py", line 71, in <module>
    pages[selected_page]["func"](api)
  File "/root/langchain-ChatGLM/webui_pages/knowledge_base/knowledge_base.py", line 96, in knowledge_base_page
    ret = api.create_knowledge_base(
  File "/root/langchain-ChatGLM/webui_pages/utils.py", line 392, in create_knowledge_base
    return response.json()
AttributeError: 'NoneType' object has no attribute 'json'
请问如何解决

**Comment by Halflifefa** [comment]
请问是怎么解决的?

**Comment by wwwhhh93** [comment]
把llm服务和api服务都打开就行了

**Comment by Halflifefa** [comment]
感谢,我将loader = DocumentLoader(self.filepath, autodetect_encoding=True)中的autodetect_encoding=True删掉后成功运行了
