### ISSUE TITLE
[BUG] llm对话正常，但知识库问答一问就报错

### ISSUE THREAD

**Issue by qihangf** [chatchat-space/Langchain-Chatchat#1106]
**问题描述 / Problem Description**
如题

**复现问题的步骤 / Steps to Reproduce**
以此启动  server/llm_api.py，server/api.py，webui.py

**实际结果 / Actual Result**
llm_api.py正常

server/api.py报错
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py",line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/applications.py", line 122,in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/middleware/errors.py", line184, in __call__
    raise exc
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/middleware/errors.py", line162, in __call__
    await self.app(scope, receive, _send)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/responses.py", line 277, in__call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/responses.py", line 273, inwrap
    await func()
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/starlette/responses.py", line 262, instream_response
    async for chunk in self.body_iterator:
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 56, in knowledge_base_chat_iterator
    docs = kb.search_docs(query, top_k)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 117, insearch_docs
    docs = self.do_search(query, top_k, embeddings)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 89, in do_search
    docs = search_index.similarity_search(query, k=top_k, score_threshold=SCORE_THRESHOLD)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 326, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 268, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 217, in similarity_search_with_score_by_vector
    _id = self.index_to_docstore_id[i]
KeyError: 26273

webui.py报错
File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/webui.py", line 56, in <module>
    pages[selected_page]["func"](api)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 111, in dialogue_page
    for d in api.knowledge_base_chat(prompt, selected_kb, kb_top_k, history):
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/webui_pages/utils.py", line 213, in _httpx_stream2generator
    for chunk in r.iter_text(None):
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/httpx/_models.py", line 844, in iter_text
    for byte_content in self.iter_bytes():
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/httpx/_models.py", line 823, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/httpx/_models.py", line 881, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/httpx/_client.py", line 123, in __iter__
    for chunk in self._stream:
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/httpx/_transports/default.py", line 105, in __iter__
    yield part
  File "/data/software/anaconda3/envs/new/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunkedread)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：2.0
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B-32k
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): m3e
- 操作系统及版本 / Operating system and version:乌班图
- Python 版本 / Python version:3.10

**Comment by liunux4odoo** [comment]
从报错信息可以看出是langchain进行faiss搜索的时候出错，你langchain版本是多少？

```shell
File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 56, in knowledge_base_chat_iterator
docs = kb.search_docs(query, top_k)
File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 117, insearch_docs
docs = self.do_search(query, top_k, embeddings)
File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 89, in do_search
docs = search_index.similarity_search(query, k=top_k, score_threshold=SCORE_THRESHOLD)
File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 326, in similarity_search
docs_and_scores = self.similarity_search_with_score(
File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 268, in similarity_search_with_score
docs = self.similarity_search_with_score_by_vector(
File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 217, in similarity_search_with_score_by_vector
_id = self.index_to_docstore_id[i]
KeyError: 26273
```

**Comment by maceygo** [comment]
> 从报错信息可以看出是langchain进行faiss搜索的时候出错，你langchain版本是多少？
> 
> ```shell
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 56, in knowledge_base_chat_iterator
> docs = kb.search_docs(query, top_k)
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 117, insearch_docs
> docs = self.do_search(query, top_k, embeddings)
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 89, in do_search
> docs = search_index.similarity_search(query, k=top_k, score_threshold=SCORE_THRESHOLD)
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 326, in similarity_search
> docs_and_scores = self.similarity_search_with_score(
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 268, in similarity_search_with_score
> docs = self.similarity_search_with_score_by_vector(
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 217, in similarity_search_with_score_by_vector
> _id = self.index_to_docstore_id[i]
> KeyError: 26273
> ```



> 从报错信息可以看出是langchain进行faiss搜索的时候出错，你langchain版本是多少？
> 
> ```shell
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 56, in knowledge_base_chat_iterator
> docs = kb.search_docs(query, top_k)
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 117, insearch_docs
> docs = self.do_search(query, top_k, embeddings)
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 89, in do_search
> docs = search_index.similarity_search(query, k=top_k, score_threshold=SCORE_THRESHOLD)
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 326, in similarity_search
> docs_and_scores = self.similarity_search_with_score(
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 268, in similarity_search_with_score
> docs = self.similarity_search_with_score_by_vector(
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 217, in similarity_search_with_score_by_vector
> _id = self.index_to_docstore_id[i]
> KeyError: 26273
> ```

@liunux4odoo 

你好，我也遇到了类似的错误，知识库加载成功但一提问就报错，这是我的报错信息， File "/usr/local/lib/python3.8/dist-packages/langchain/vectorstores/faiss.py", line 268, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(
TypeError: similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter' ，
好像是faiss搜索的时

**Comment by maceygo** [comment]
> 从报错信息可以看出是langchain进行faiss搜索的时候出错，你langchain版本是多少？
> 
> ```shell
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 56, in knowledge_base_chat_iterator
> docs = kb.search_docs(query, top_k)
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 117, insearch_docs
> docs = self.do_search(query, top_k, embeddings)
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 89, in do_search
> docs = search_index.similarity_search(query, k=top_k, score_threshold=SCORE_THRESHOLD)
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 326, in similarity_search
> docs_and_scores = self.similarity_search_with_score(
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 268, in similarity_search_with_score
> docs = self.similarity_search_with_score_by_vector(
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 217, in similarity_search_with_score_by_vector
> _id = self.index_to_docstore_id[i]
> KeyError: 26273
> ```

@liunux4odoo 
你好 我也遇到了类似的错误，知识库加载成功，但一提问就报错，这是我的后台输出信息，
 File "/usr/local/lib/python3.8/dist-packages/langchain/vectorstores/faiss.py", line 268, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(
TypeError: similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter' ，

好像是faiss搜索时传递了意外参数，我的版本是v0.1.17 ，请问你有遇到过这个错误吗，谢谢

**Comment by qihangf** [comment]
> 从报错信息可以看出是langchain进行faiss搜索的时候出错，你langchain版本是多少？
> 
> ```shell
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 56, in knowledge_base_chat_iterator
> docs = kb.search_docs(query, top_k)
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 117, insearch_docs
> docs = self.do_search(query, top_k, embeddings)
> File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 89, in do_search
> docs = search_index.similarity_search(query, k=top_k, score_threshold=SCORE_THRESHOLD)
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 326, in similarity_search
> docs_and_scores = self.similarity_search_with_score(
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 268, in similarity_search_with_score
> docs = self.similarity_search_with_score_by_vector(
> File "/data/software/anaconda3/envs/new/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 217, in similarity_search_with_score_by_vector
> _id = self.index_to_docstore_id[i]
> KeyError: 26273
> ```

是这个包的版本吗，是0.0.257

**Comment by imClumsyPanda** [comment]
该问题与langchain中faiss添加、删除文档实现方式代码有关，请将langchain版本更新至0.0.266后，重建向量库，并检查是否会复现该问题。
