### ISSUE TITLE
[BUG] LLM API访问正常，通过webui访问异常

### ISSUE THREAD

**Issue by RayYe586** [chatchat-space/Langchain-Chatchat#1109]
**问题描述 / Problem Description**
LLM API访问正常，通过webui访问异常 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 分别部署llmapi 和 api
2. streamlit run webui.py启动webui
3. 无论是llm问答或者是知识库操作都有问题

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：e3d968d04360add8699f8863c84ab1e592392658
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:ubuntu 22
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:
8卡p100环境
**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
webui报错：
2023-08-16 00:23:38,661 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
resp: <contextlib._GeneratorContextManager object at 0x7fdc65fdd0f0>
2023-08-16 00:23:38.662 Uncaught app exception
Traceback (most recent call last):
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 197, in _receive_event
    event = self._h11_state.next_event()
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/h11/_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 104, in __iter__
    for part in self._httpcore_stream:
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 347, in __iter__
    for part in self._stream:
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 325, in __iter__
    raise exc
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 317, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_body
    event = self._receive_event(timeout=timeout)
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 196, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/bso/src/srcllm/langchain-ChatGLM/webui.py", line 56, in <module>
    pages[selected_page]["func"](api)
  File "/home/bso/src/srcllm/langchain-ChatGLM/webui_pages/dialogue/dialogue.py", line 100, in dialogue_page
    for t in r:
  File "/home/bso/src/srcllm/langchain-ChatGLM/webui_pages/utils.py", line 214, in _httpx_stream2generator
    for chunk in r.iter_text(None):
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_models.py", line 844, in iter_text
    for byte_content in self.iter_bytes():
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_models.py", line 823, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_models.py", line 881, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_client.py", line 123, in __iter__
    for chunk in self._stream:
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 103, in __iter__
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

api.py报错：
    raise e
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/bso/src/srcllm/langchain-ChatGLM/server/chat/chat.py", line 40, in chat_iterator
    chat_prompt = ChatPromptTemplate.from_messages(
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/langchain/prompts/chat.py", line 192, in from_messages
    return cls(input_variables=list(input_vars), messages=messages)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 14 validation errors for ChatPromptTemplate
messages -> 0
  value is not a valid dict (type=type_error.dict)
messages -> 0
  value is not a valid dict (type=type_error.dict)
messages -> 1
  value is not a valid dict (type=type_error.dict)
messages -> 1
  value is not a valid dict (type=type_error.dict)
messages -> 2
  value is not a valid dict (type=type_error.dict)
messages -> 2
  value is not a valid dict (type=type_error.dict)
messages -> 3
  value is not a valid dict (type=type_error.dict)
messages -> 3
  value is not a valid dict (type=type_error.dict)
messages -> 4
  value is not a valid dict (type=type_error.dict)
messages -> 4
  value is not a valid dict (type=type_error.dict)
messages -> 5
  value is not a valid dict (type=type_error.dict)
messages -> 5
  value is not a valid dict (type=type_error.dict)
messages -> 6
  value is not a valid dict (type=type_error.dict)
messages -> 6
  value is not a valid dict (type=type_error.dict)

**Comment by liunux4odoo** [comment]
请问你langchain版本？

**Comment by RayYe586** [comment]
langchain                 0.0.257

**Comment by RayYe586** [comment]
重新检查了下依赖，搞定了

**Comment by WCwalker** [comment]
> 

大哥，你改了什么，我也遇到这个问题了，谢谢

**Comment by 330570902** [comment]
我也遇到相同的问题了，依赖改了什么吗？

**Comment by kyrie1123** [comment]
> 重新检查了下依赖，搞定了

一样的问题，请问怎么解决的呢？谢谢

**Comment by kevindany** [comment]
> > 重新检查了下依赖，搞定了
> 
> 一样的问题，请问怎么解决的呢？谢谢

同问。我的langchain 0.0.266

**Comment by IssacCzy** [comment]
> 重新检查了下依赖，搞定了
同样遇到这个问题，请问是如何解决的呢？

**Comment by IssacCzy** [comment]
> 重新检查了下依赖，搞定了


同样遇到这个问题，请问是如何解决的呢？
