### ISSUE TITLE
[BUG] RemoteProtocolError

### ISSUE THREAD

**Issue by aleimu** [chatchat-space/Langchain-Chatchat#1111]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/langchain-ChatGLM/webui.py", line 56, in <module>
    pages[selected_page]["func"](api)
  File "/langchain-ChatGLM/webui_pages/dialogue/dialogue.py", line 122, in dialogue_page
    for d in api.search_engine_chat(prompt, search_engine, se_top_k):
  File "/langchain-ChatGLM/webui_pages/utils.py", line 213, in _httpx_stream2generator
    for chunk in r.iter_text(None):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 844, in iter_text
    for byte_content in self.iter_bytes():
  File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 823, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 881, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 123, in __iter__
    for chunk in self._stream:
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 103, in __iter__
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

当前master分支中使用webui经常发生的报错

**Comment by liunux4odoo** [comment]
使用搜索引擎问答的话，bing搜索需要KEY，duckduckgo搜索需要能访问的网络。

**Comment by kyrie1123** [comment]
我在和本地知识库对话当中也经常发生这个报错，是什么原因呢？
