### ISSUE TITLE
[BUG] 上传的txt文档，如果扩展名是大写”TXT“，报错

### ISSUE THREAD

**Issue by RayYe586** [chatchat-space/Langchain-Chatchat#1121]
上传的txt文档，如果扩展名是大写”TXT“，报错：
Traceback (most recent call last):
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/bso/src/srcllm/langchain-ChatGLM/webui.py", line 56, in <module>
    pages[selected_page]["func"](api)
  File "/home/bso/src/srcllm/langchain-ChatGLM/webui_pages/knowledge_base/knowledge_base.py", line 138, in knowledge_base_page
    ret = api.upload_kb_doc(f, kb)
  File "/home/bso/src/srcllm/langchain-ChatGLM/webui_pages/utils.py", line 491, in upload_kb_doc
    return response.json()
  File "/home/bso/venv/chatglm2_6b_venv/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xain** [comment]
#1128 我提交了一个pr修正了这个问题。
