### ISSUE TITLE
[BUG] 启动LLM_api.py失败

### ISSUE THREAD

**Issue by GPTlei** [chatchat-space/Langchain-Chatchat#1124]
环境为win10 wsl2 ubuntu，全新安装的0.2，本地模型chatglm2-6b，运行python server/llm_api.py失败显示如下：

pico@DESKTOP-K24MTK4:~/langchain-ChatGLM$ python server/llm_api.py
2023-08-16 16:39:40,842 - llm_api.py[line:196] - INFO: {'local_model_path': '/home/pico/langchain-ChatGLM/model/chatglm2-6b', 'api_base_url': 'http://localhost:8888/v1', 'api_key': 'EMPTY'}
2023-08-16 16:39:40,842 - llm_api.py[line:199] - INFO: 如需查看 llm_api 日志，请前往 /home/pico/langchain-ChatGLM/logs
2023-08-16 16:39:41 | ERROR | stderr | INFO:     Started server process [4454]
2023-08-16 16:39:41 | ERROR | stderr | INFO:     Waiting for application startup.
2023-08-16 16:39:41 | ERROR | stderr | INFO:     Application startup complete.
2023-08-16 16:39:41 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20001 (Press CTRL+C to quit)
2023-08-16 16:39:41,344 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmprdl6kdvt
2023-08-16 16:39:41,345 - instantiator.py[line:76] - INFO: Writing /tmp/tmprdl6kdvt/_remote_module_non_scriptable.py
2023-08-16 16:39:41,415 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpco5t9m8i
2023-08-16 16:39:41,415 - instantiator.py[line:76] - INFO: Writing /tmp/tmpco5t9m8i/_remote_module_non_scriptable.py
2023-08-16 16:39:42 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 9bf1eece ...
2023-08-16 16:39:42 | ERROR | stderr | Traceback (most recent call last):
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/langchain-ChatGLM/server/llm_api.py", line 230, in <module>
2023-08-16 16:39:42 | ERROR | stderr |     run_model_worker(queue)
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/langchain-ChatGLM/server/llm_api.py", line 161, in run_model_worker
2023-08-16 16:39:42 | ERROR | stderr |     app = create_model_worker_app(*args, **kwargs)
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/langchain-ChatGLM/server/llm_api.py", line 99, in create_model_worker_app
2023-08-16 16:39:42 | ERROR | stderr |     worker = ModelWorker(
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/.local/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 199, in __init__
2023-08-16 16:39:42 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/.local/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 236, in load_model
2023-08-16 16:39:42 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/.local/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 614, in load_model
2023-08-16 16:39:42 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 642, in from_pretrained
2023-08-16 16:39:42 | ERROR | stderr |     tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 486, in get_tokenizer_config
2023-08-16 16:39:42 | ERROR | stderr |     resolved_config_file = cached_file(
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
2023-08-16 16:39:42 | ERROR | stderr |     resolved_file = hf_hub_download(
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
2023-08-16 16:39:42 | ERROR | stderr |     validate_repo_id(arg_value)
2023-08-16 16:39:42 | ERROR | stderr |   File "/home/pico/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
2023-08-16 16:39:42 | ERROR | stderr |     raise HFValidationError(
2023-08-16 16:39:42 | ERROR | stderr | huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/pico/langchain-ChatGLM/model/chatglm2-6b'. Use `repo_type` argument if needed.
2023-08-16 16:39:42 | ERROR | stderr | INFO:     Shutting down
2023-08-16 16:39:42 | ERROR | stderr | INFO:     Waiting for application shutdown.
2023-08-16 16:39:42 | ERROR | stderr | INFO:     Application shutdown complete.
2023-08-16 16:39:42 | ERROR | stderr | INFO:     Finished server process [4454]

**Comment by imClumsyPanda** [comment]
请问是否已经按照requirements.txt要求安装全部依赖包？

**Comment by weipeng008005** [comment]
我也出现了这个问题

**Comment by GPTlei** [comment]
已经按照requirements.txt安装全部依赖，依然不行。没办法又改直接在windows10的conda环境安装。
windows安装还是有一个之前版本的老问题，就是torch默认安装的是CPU版，需要卸载后pip安装GPU版本。目前已经跑通。
wsl2还没头绪
