### ISSUE TITLE
[BUG] 运行报错python webui_allinone.py

### ISSUE THREAD

**Issue by mybolide** [chatchat-space/Langchain-Chatchat#1146]
**问题描述 / Problem Description**
运行报错python webui_allinone.py
包括使用了：python webui_allinone.py --model-path-address=E:\\huggingface\\chatglm2-6b-32k

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python webui_allinone.py'
2. 问题出现 / Problem occurs

**实际结果 / Actual Result**
```
Starting webui_allineone.py, it would take a while, please be patient....
'while' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "D:\workspace\Langchain-Chatchat\webui_allinone.py", line 70, in <module>
    launch_all(args=args,controller_args=controller_args,worker_args=worker_args,server_args=server_args)
  File "D:\workspace\Langchain-Chatchat\server\llm_api_launch.py", line 237, in launch_all
    subprocess.run(controller_check_sh, shell=True, check=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'while [ `grep -c "Uvicorn running on" ./logs//controller.log` -eq '0' ];do
                        sleep 5s;
                        echo "wait controller running"
                done
                echo 'controller running' ' returned non-zero exit status 1.
```

**环境信息 / Environment Information**
最新分支
使用模型：ChatGLM-6B/chatglm2-6b-32k
- 操作系统及版本 / Operating system and version: windows11
- Python 版本 / Python version:3.10.6

**Comment by hzg0601** [comment]
目前webui_allinone.py不支持win平台，项目组正在测试适合全平台一键启动脚本分支dev_allinone，欢迎测试

**Comment by mybolide** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13502882/4c1f6e55-0417-4a1c-99b6-d9727c3129aa)
运行报错了
