### ISSUE TITLE
[BUG] 0.2.0bug 合集

### ISSUE THREAD

**Issue by ucas010** [chatchat-space/Langchain-Chatchat#1149]
bug1 ：
```
[SQL: SELECT knowledge_base.id AS knowledge_base_id, knowledge_base.kb_name AS knowledge_base_kb_name, knowledge_base.vs_type AS knowledge_base_vs_type, knowledge_base.embed_model AS knowledge_base_embed_model, knowledge_base.file_count AS knowledge_base_file_count, knowledge_base.create_time AS knowledge_base_create_time 
FROM knowledge_base 
WHERE knowledge_base.kb_name = ?
 LIMIT ? OFFSET ?]
[parameters: ('128', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO:     172.16.71.252:63301 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.16.71.252:63302 - "GET /swagger-ui.css HTTP/1.1" 304 Not Modified
INFO:     172.16.71.252:63301 - "GET /swagger-ui-bundle.js HTTP/1.1" 304 Not Modified
INFO:     172.16.71.252:63301 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.16.71.252:63308 - "POST /knowledge_base/upload_doc HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "//site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: knowledge_base

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "//site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "//site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/da9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/shon3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/dan3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/dathon3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/da/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/dat.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/da/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/dython3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/dat/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/data/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/don3.9/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
  File "/atchat/server/knowledge_base/kb_doc_api.py", line 35, in upload_doc
    kb = KBServiceFactory.get_service_by_name(knowledge_base_name)
  File "/dhat/server/knowledge_base/kb_service/base.py", line 216, in get_service_by_name
    _, vs_type, embed_model = load_kb_from_db(kb_name)
  File "/data/xuliatchat/server/db/session.py", line 25, in wrapper
    result = f(session, *args, **kwargs)
  File "/datachat/server/db/repository/knowledge_base_repository.py", line 34, in load_kb_from_db
    kb = session.query(KnowledgeBaseModel).filter_by(kb_name=kb_name).first()
  File "/da3.9/site-packages/sqlalchemy/orm/query.py", line 2747, in first
    return self.limit(1)._iter().first()  # type: ignore
  File "/daite-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/dat-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
  File "/data/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/dkages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/dckages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/dataackages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/data/9/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/data/3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/data/3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/datahon3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/data-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/datackages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: knowledge_base
[SQL: SELECT knowledge_base.id AS knowledge_base_id, knowledge_base.kb_name AS knowledge_base_kb_name, knowledge_base.vs_type AS knowledge_base_vs_type, knowledge_base.embed_model AS knowledge_base_embed_model, knowledge_base.file_count AS knowledge_base_file_count, knowledge_base.create_time AS knowledge_base_create_time 
FROM knowledge_base 
WHERE knowledge_base.kb_name = ?
 LIMIT ? OFFSET ?]
[parameters: ('128', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

执行代码：
```
nohup python server/llm_api_launch.py & 
nohup python server/api.py --port 7866 &
```

**Comment by liunux4odoo** [comment]
这不是bug，部署文档里说过了，需要先`python init_database.py --recreate-vs` 初始化数据库。

**Comment by ucas010** [comment]
bug2 :
{
    "code": 404,
    "msg": "未找到知识库 knowledge_base"
}

**Comment by ucas010** [comment]
bug 3: 
{
    "detail": [
        {
            "loc": [
                "body",
                "knowledge_base_name"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        },
        {
            "loc": [
                "body",
                "file_name"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}

**Comment by ucas010** [comment]
bug4 : 
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
