### ISSUE TITLE
[BUG]  ImportError: cannot import name 'AWQConfig' from 'fastchat.serve.model_worker' 

### ISSUE THREAD

**Issue by zhuhaifengaaa** [chatchat-space/Langchain-Chatchat#1152]
** ImportError导入报错**
一键启动python startup.py --all-webui，之后再log中看到报错.

具体报错如下：
2023-08-18 09:34:15 | ERROR | stderr | Process model_worker(88543):
2023-08-18 09:34:15 | ERROR | stderr | Traceback (most recent call last):
2023-08-18 09:34:15 | ERROR | stderr |   File "/home/zhuhaifeng/langchain-chatchat/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-08-18 09:34:15 | ERROR | stderr |     self.run()
2023-08-18 09:34:15 | ERROR | stderr |   File "/home/zhuhaifeng/langchain-chatchat/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-08-18 09:34:15 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-08-18 09:34:15 | ERROR | stderr |   File "/home/zhuhaifeng/project/langchain-ChatGLM2-2/startup.py", line 205, in run_model_worker
2023-08-18 09:34:15 | ERROR | stderr |     app = create_model_worker_app(**kwargs)
2023-08-18 09:34:15 | ERROR | stderr |   File "/home/zhuhaifeng/project/langchain-ChatGLM2-2/startup.py", line 45, in create_model_worker_app
2023-08-18 09:34:15 | ERROR | stderr |     from fastchat.serve.model_worker import app, GptqConfig, AWQConfig, ModelWorker, worker_id
2023-08-18 09:34:15 | ERROR | stderr | ImportError: cannot import name 'AWQConfig' from 'fastchat.serve.model_worker' (/home/zhuhaifeng/langchain-chatchat/lib/python3.10/site-packages/fastchat/serve/model_worker.py)

请问怎么处理啊

**Comment by CindyShenn** [comment]
我也遇到了，更新一下这两个包的版本就可以了：fschat==0.2.24，transformers>=4.31.0

**Comment by zhuhaifengaaa** [comment]
> 

谢谢，解决了
