### ISSUE TITLE
[BUG] 向samples知识库添加文件报错

### ISSUE THREAD

**Issue by taofendenanhai** [chatchat-space/Langchain-Chatchat#1154]
**问题描述 / Problem Description**
```
Exception in thread ScriptRunner.scriptThread:
Traceback (most recent call last):
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 316, in _run_script_thread
    widget_states = self._session_state.get_widget_states()
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/site-packages/streamlit/runtime/state/safe_session_state.py", line 90, in get_widget_states
    return self._state.get_widget_states()
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/site-packages/streamlit/runtime/state/session_state.py", line 563, in get_widget_states
    return self._new_widget_state.as_widget_states()
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/site-packages/streamlit/runtime/state/session_state.py", line 227, in as_widget_states
    states = [
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/site-packages/streamlit/runtime/state/session_state.py", line 230, in <listcomp>
    if self.get_serialized(widget_id)
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/site-packages/streamlit/runtime/state/session_state.py", line 210, in get_serialized
    serialized = metadata.serializer(item.value)
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/site-packages/streamlit/elements/selectbox.py", line 58, in serialize
    return index_(self.options, v)
  File "/home/whzhu_st/anaconda3/envs/chatglm_etuning/lib/python3.8/site-packages/streamlit/util.py", line 157, in index_
    raise ValueError("{} is not in iterable".format(str(x)))
ValueError: {'kb_name': 'samples', 'vs_type': 'faiss', 'embed_model': 'm3e-base', 'file_count': 1, 'create_time': datetime.datetime(2023, 8, 16, 15, 23, 25), 'in_folder': True, 'in_db': True, 'No': 1} is not in iterable

```

**复现问题的步骤 / Steps to Reproduce**
1. 执行 知识库管理
2. 点击 上传文件
3. 等待
4. 向模型提问，然后问题出现 

**实际结果 / Actual Result**
描添加完成知识库的时候发生以上错误，但是不影响langchain运行

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：m3e-base
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.8

**Comment by imClumsyPanda** [comment]
请问向量库类型是？

**Comment by taofendenanhai** [comment]
m3e-base

**Comment by lunalulu** [comment]
请问解决了吗？遇到了同样的问题
@taofendenanhai

**Comment by taofendenanhai** [comment]
> 请问解决了吗？遇到了同样的问题 @taofendenanhai

没 但还是可以跑起来，不影响正常工作

**Comment by imClumsyPanda** [comment]
建议更新至v0.2.2后重试
