### ISSUE TITLE
[BUG] 加载llama2-chinese-13b-chat模型出现AttributeError: 'BaseModelOutputWithPast' object has no attribute 'logits'

### ISSUE THREAD

**Issue by haof-github** [chatchat-space/Langchain-Chatchat#1155]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
加载llama2-chinese-13b-chat模型，在server/llm_api.py 那边出现出现AttributeError: 'BaseModelOutputWithPast' object has no attribute 'logits'，在api.py那边显示caught exception: response payload is not completed.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'server/llm_api.py' （加载的模型是llama2-chinese-13b-chat,\url{https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat}, embedding is m3e-large）
2. 执行 'server/api.py'
3. 执行 ”streamlit run webui.py“ 
4. 打开langchain-chatchat网址
5. 输入任意字符，比如”你好“
6. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.0
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：llama2-chinese-13b-chat
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）： moka-ai/m3e-large
- 操作系统及版本 / Operating system and version: Centos
- Python 版本 / Python version: 3.8.17
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
直接用fastchat调用该模型文件，可以正常运行。

**以下是llm.api.py报错的情况：**
2023-08-17 16:52:47 | ERROR | stderr | 
2023-08-17 16:53:05 | INFO | model_worker | Register to controller
2023-08-17 16:53:05 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m5856[0m]
2023-08-17 16:53:05 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2023-08-17 16:53:05 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2023-08-17 16:53:05 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:20002[0m (Press CTRL+C to quit)
2023-08-17 16:53:50 | INFO | model_worker | Send heart beat. Models: ['llama2-chinese-13b-chat']. Semaphore: None. call_ct: 0. worker_id: 4c435058. 
2023-08-17 16:54:35 | INFO | model_worker | Send heart beat. Models: ['llama2-chinese-13b-chat']. Semaphore: None. call_ct: 0. worker_id: 4c435058. 
2023-08-17 16:55:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34156 - "[1mPOST /worker_get_conv_template HTTP/1.1[0m" [32m200 OK[0m
2023-08-17 16:55:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34160 - "[1mPOST /model_details HTTP/1.1[0m" [32m200 OK[0m
2023-08-17 16:55:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34160 - "[1mPOST /count_token HTTP/1.1[0m" [32m200 OK[0m
2023-08-17 16:55:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34164 - "[1mPOST /worker_generate_stream HTTP/1.1[0m" [32m200 OK[0m
2023-08-17 16:55:07 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2023-08-17 16:55:07 | ERROR | stderr | Traceback (most recent call last):
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2023-08-17 16:55:07 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/fastapi/applications.py", line 290, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     raise exc
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     raise exc
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     raise e
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     await self.app(scope, receive, send)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
2023-08-17 16:55:07 | ERROR | stderr |     await self.app(scope, receive, send)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/routing.py", line 69, in app
2023-08-17 16:55:07 | ERROR | stderr |     await response(scope, receive, send)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/responses.py", line 277, in __call__
2023-08-17 16:55:07 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2023-08-17 16:55:07 | ERROR | stderr |     raise exceptions[0]
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/responses.py", line 273, in wrap
2023-08-17 16:55:07 | ERROR | stderr |     await func()
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/responses.py", line 262, in stream_response
2023-08-17 16:55:07 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
2023-08-17 16:55:07 | ERROR | stderr |     yield await anyio.to_thread.run_sync(_next, iterator)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
2023-08-17 16:55:07 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-08-17 16:55:07 | ERROR | stderr |     return await future
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-08-17 16:55:07 | ERROR | stderr |     result = context.run(func, *args)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/starlette/concurrency.py", line 53, in _next
2023-08-17 16:55:07 | ERROR | stderr |     return next(iterator)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/fastchat/serve/model_worker.py", line 222, in generate_stream_gate
2023-08-17 16:55:07 | ERROR | stderr |     for output in self.generate_stream_func(
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
2023-08-17 16:55:07 | ERROR | stderr |     response = gen.send(None)
2023-08-17 16:55:07 | ERROR | stderr |   File "/mnt/data06/user2345/miniconda3/envs/chat2/lib/python3.8/site-packages/fastchat/serve/inference.py", line 116, in generate_stream
2023-08-17 16:55:07 | ERROR | stderr |     logits = out.logits
2023-08-17 16:55:07 | ERROR | stderr | AttributeError: 'BaseModelOutputWithPast' object has no attribute 'logits'

**以下是api.py的报错情况：**
2023-08-17 16：21：47，960 - util.py[line:67] - INFO: message='OpenAI API response' path=http://localhost:8898/v1/chat/completions processing_ms=None request_id=None response_code=200**(这部分信息截图没截取到)** 
Caught exceptions: Response payload is not completed

**Comment by zoepao** [comment]
同样的问题，解决了吗

**Comment by haof-github** [comment]
> 同样的问题，解决了吗

目前还没有

**Comment by imClumsyPanda** [comment]
请问fschat版本是多少？项目代码更新至最新版后是否仍存在该问题？

**Comment by haof-github** [comment]
> 请问fschat版本是多少？项目代码更新至最新版后是否仍存在该问题？

0.2.20.  对，python环境以及代码都重新安装再运行也还是同样的错误

**Comment by imClumsyPanda** [comment]
建议更新到0.0.24版本后测试下是否仍存在该问题

**Comment by haof-github** [comment]
> 建议更新到0.0.24版本后测试下是否仍存在该问题

你是说fschat==0.2.24吧，刚刚已经更新了，测试了，还是一样的问题。另外我用fastchat直接跑这个模型是可以正常运行的。

**Comment by hzg0601** [comment]
请贴出详细的打印信心

**Comment by haof-github** [comment]
> 请贴出详细的打印信心

已经添加到附加信息里面去了

**Comment by hzg0601** [comment]
你的transformers版本和torch版本是多少？

**Comment by haof-github** [comment]
> 你的transformers版本和torch版本是多少？

sentence-transformers==2.2.2    torch==2.0.1    
Driver Version: 515.43.04    CUDA Version: 11.7

**Comment by hzg0601** [comment]
是transformers不是sentence-transformers，从报错信息看可能是transformers版本不对，确保transformers版本为
4.31.0

**Comment by haof-github** [comment]
> 是transformers不是sentence-transformers，从报错信息看可能是transformers版本不对，确保transformers版本为 4.31.0

刚刚检查了下，transformers是4.28的版本，然后更新到了4.32.0版本测试了一下，还是有问题

**Comment by hzg0601** [comment]
> 

还是一样的错误吗？

**Comment by haof-github** [comment]
> > 
> 
> 还是一样的错误吗？

对，一样的错误。之前用fastchat直接跑这个模型，可以正常运行

**Comment by zoepao** [comment]
邮件已收到，谢谢。

**Comment by GUI0609** [comment]
可以请问下现在解决了吗
