### ISSUE TITLE
[BUG] 部署peft-model失败

### ISSUE THREAD

**Issue by jackaihfia2334** [chatchat-space/Langchain-Chatchat#1164]
经实践，通过peft方式加载lora模型（而非加载合并后的模型）部署是成功的，但api和webui似乎存在适配上的问题。
我通过python3 -m fastchat.serve.cli --model-path /data2/project/peft-model，以命令行形式交互得到预期的结果。

而使用python3 -m fastchat.serve.model_worker --model-path /data2/project/peft-model启动LLM服务后，通过python server/api.py启动api服务，通过streamlit run webui.py启动webui服务，
在输入时 api服务报错如下（似乎是端口问题）
——————————————————————
root@docker-desktop:/data1/llm/code/Langchain-Chatchat# python server/api.py
2023-08-18 08:49:10,100 - utils.py[line:148] - INFO: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-08-18 08:49:10,100 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
INFO:     Started server process [32283]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
INFO:     127.0.0.1:46718 - "POST /chat/chat HTTP/1.1" 200 OK
2023-08-18 08:49:35,508 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-18 08:49:35,508 - manager.py[line:364] - WARNING: Error in AsyncIteratorCallbackHandler.on_retry callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:35,508 - manager.py[line:364] - WARNING: Error in StdOutCallbackHandler.on_retry callback: 'StdOutCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:39,512 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-18 08:49:39,513 - manager.py[line:364] - WARNING: Error in AsyncIteratorCallbackHandler.on_retry callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:39,513 - manager.py[line:364] - WARNING: Error in StdOutCallbackHandler.on_retry callback: 'StdOutCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:43,515 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-18 08:49:43,515 - manager.py[line:364] - WARNING: Error in AsyncIteratorCallbackHandler.on_retry callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:43,515 - manager.py[line:364] - WARNING: Error in StdOutCallbackHandler.on_retry callback: 'StdOutCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:47,522 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-18 08:49:47,523 - manager.py[line:364] - WARNING: Error in AsyncIteratorCallbackHandler.on_retry callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:47,523 - manager.py[line:364] - WARNING: Error in StdOutCallbackHandler.on_retry callback: 'StdOutCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:55,530 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-18 08:49:55,531 - manager.py[line:364] - WARNING: Error in AsyncIteratorCallbackHandler.on_retry callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_retry'
2023-08-18 08:49:55,531 - manager.py[line:364] - WARNING: Error in StdOutCallbackHandler.on_retry callback: 'StdOutCallbackHandler' object has no attribute 'on_retry'
Caught exception: Error communicating with OpenAI

此问题也在isssues1110中提出  https://github.com/chatchat-space/Langchain-Chatchat/issues/1110

**Comment by jackaihfia2334** [comment]
另外，我尝试使用fastchat原生的webui加载方式，报错如下，似乎是因为没有从本地加载adaper_config而是去huggingface下载，详见
https://github.com/lm-sys/FastChat/issues/2262

———————————————————————
root@docker-desktop:/# python3 -m fastchat.serve.gradio_web_server
2023-08-18 16:24:00 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, share=False, controller_url='http://localhost:21001', concurrency_count=10, model_list_mode='once', moderate=False, add_chatgpt=False, add_claude=False, add_palm=False, gradio_auth_path=None)
2023-08-18 16:24:00 | INFO | gradio_web_server | Models: ['peft-model']
2023-08-18 16:24:00 | INFO | stdout | Running on local URL:  http://0.0.0.0:7860
2023-08-18 16:24:00 | INFO | stdout | 
2023-08-18 16:24:00 | INFO | stdout | To create a public link, set `share=True` in `launch()`.
2023-08-18 16:24:05 | INFO | gradio_web_server | load_demo. ip: 127.0.0.1. params: {}
2023-08-18 16:24:05 | INFO | httpx | HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
2023-08-18 16:24:05 | INFO | httpx | HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
2023-08-18 16:24:10 | INFO | gradio_web_server | add_text. ip: 127.0.0.1. len: 2
2023-08-18 16:24:10 | INFO | stdout | peft-model
2023-08-18 16:24:10 | INFO | stdout | peft-model
2023-08-18 16:24:10 | INFO | stdout | peft-model
2023-08-18 16:24:10 | INFO | stdout | peft-model
2023-08-18 16:24:10 | INFO | stdout | find 'adapter_config.json' at 'peft-model'
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 6b2753fa-c523-43c3-80bf-70ebedbb1769)')' thrown while requesting HEAD https://huggingface.co/peft-model/resolve/main/adapter_config.json
2023-08-18 16:24:20 | WARNING | huggingface_hub.utils._http | '(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 6b2753fa-c523-43c3-80bf-70ebedbb1769)')' thrown while requesting HEAD https://huggingface.co/peft-model/resolve/main/adapter_config.json
2023-08-18 16:24:20 | ERROR | stderr | Traceback (most recent call last):
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/peft/utils/config.py", line 119, in from_pretrained
2023-08-18 16:24:20 | ERROR | stderr |     config_file = hf_hub_download(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2023-08-18 16:24:20 | ERROR | stderr |     return fn(*args, **kwargs)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
2023-08-18 16:24:20 | ERROR | stderr |     raise LocalEntryNotFoundError(
2023-08-18 16:24:20 | ERROR | stderr | huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.
2023-08-18 16:24:20 | ERROR | stderr | 
2023-08-18 16:24:20 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-08-18 16:24:20 | ERROR | stderr | 
2023-08-18 16:24:20 | ERROR | stderr | Traceback (most recent call last):
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 442, in run_predict
2023-08-18 16:24:20 | ERROR | stderr |     output = await app.get_blocks().process_api(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1392, in process_api
2023-08-18 16:24:20 | ERROR | stderr |     result = await self.call_function(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1097, in call_function
2023-08-18 16:24:20 | ERROR | stderr |     prediction = await anyio.to_thread.run_sync(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
2023-08-18 16:24:20 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-08-18 16:24:20 | ERROR | stderr |     return await future
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-08-18 16:24:20 | ERROR | stderr |     result = context.run(func, *args)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 703, in wrapper
2023-08-18 16:24:20 | ERROR | stderr |     response = f(*args, **kwargs)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/gradio_web_server.py", line 210, in add_text
2023-08-18 16:24:20 | ERROR | stderr |     state = State(model_selector)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/gradio_web_server.py", line 68, in __init__
2023-08-18 16:24:20 | ERROR | stderr |     self.conv = get_conversation_template(model_name)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 291, in get_conversation_template
2023-08-18 16:24:20 | ERROR | stderr |     return adapter.get_default_conv_template(model_path)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 498, in get_default_conv_template
2023-08-18 16:24:20 | ERROR | stderr |     config = PeftConfig.from_pretrained(model_path)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/peft/utils/config.py", line 123, in from_pretrained
2023-08-18 16:24:20 | ERROR | stderr |     raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
2023-08-18 16:24:20 | ERROR | stderr | ValueError: Can't find 'adapter_config.json' at 'peft-model'
2023-08-18 16:24:20 | INFO | httpx | HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-08-18 16:24:20 | INFO | httpx | HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
2023-08-18 16:24:20 | INFO | gradio_web_server | bot_response. ip: 127.0.0.1
2023-08-18 16:24:20 | ERROR | stderr | Traceback (most recent call last):
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 442, in run_predict
2023-08-18 16:24:20 | ERROR | stderr |     output = await app.get_blocks().process_api(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1392, in process_api
2023-08-18 16:24:20 | ERROR | stderr |     result = await self.call_function(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1111, in call_function
2023-08-18 16:24:20 | ERROR | stderr |     prediction = await utils.async_iteration(iterator)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 346, in async_iteration
2023-08-18 16:24:20 | ERROR | stderr |     return await iterator.__anext__()
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 339, in __anext__
2023-08-18 16:24:20 | ERROR | stderr |     return await anyio.to_thread.run_sync(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
2023-08-18 16:24:20 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-08-18 16:24:20 | ERROR | stderr |     return await future
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-08-18 16:24:20 | ERROR | stderr |     result = context.run(func, *args)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 322, in run_sync_iterator_async
2023-08-18 16:24:20 | ERROR | stderr |     return next(iterator)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 691, in gen_wrapper
2023-08-18 16:24:20 | ERROR | stderr |     yield from f(*args, **kwargs)
2023-08-18 16:24:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/gradio_web_server.py", line 300, in bot_response
2023-08-18 16:24:20 | ERROR | stderr |     if state.skip_next:
2023-08-18 16:24:20 | ERROR | stderr | AttributeError: 'NoneType' object has no attribute 'skip_next'
2023-08-18 16:24:20 | INFO | httpx | HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-08-18 16:24:20 | INFO | httpx | HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
