### ISSUE TITLE
启动llm_api.py报错

### ISSUE THREAD

**Issue by ihsin-yyx** [chatchat-space/Langchain-Chatchat#1166]
2023-08-19 23:06:22 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 6e56c560 ...
2023-08-19 23:06:23 | ERROR | stderr | 
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
2023-08-19 23:06:25 | ERROR | stderr | 
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:01<00:09,  1.67s/it]
2023-08-19 23:06:27 | ERROR | stderr | 
Loading checkpoint shards:  29%|████████████████▎                                        | 2/7 [00:03<00:08,  1.72s/it]
2023-08-19 23:06:28 | ERROR | stderr | 
Loading checkpoint shards:  43%|████████████████████████▍                                | 3/7 [00:05<00:07,  1.80s/it]
2023-08-19 23:06:30 | ERROR | stderr | 
Loading checkpoint shards:  57%|████████████████████████████████▌                        | 4/7 [00:07<00:05,  1.91s/it]
2023-08-19 23:06:33 | ERROR | stderr | 
Loading checkpoint shards:  71%|████████████████████████████████████████▋                | 5/7 [00:09<00:04,  2.07s/it]
2023-08-19 23:06:36 | ERROR | stderr | 
Loading checkpoint shards:  86%|████████████████████████████████████████████████▊        | 6/7 [00:12<00:02,  2.36s/it]
2023-08-19 23:06:38 | ERROR | stderr | 
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:15<00:00,  2.37s/it]
2023-08-19 23:06:38 | ERROR | stderr | 
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:15<00:00,  2.15s/it]
2023-08-19 23:06:38 | ERROR | stderr | 
2023-08-19 23:06:38 | INFO | model_worker | Register to controller
2023-08-19 23:06:38 | ERROR | stderr | Process model_worker(34884):
2023-08-19 23:06:38 | ERROR | stderr | Traceback (most recent call last):
2023-08-19 23:06:38 | ERROR | stderr |   File "C:\Users\ihsin\anaconda3\envs\chatchat\lib\multiprocessing\process.py", line 314, in _bootstrap
2023-08-19 23:06:39 | ERROR | stderr |     self.run()
2023-08-19 23:06:39 | ERROR | stderr |   File "C:\Users\ihsin\anaconda3\envs\chatchat\lib\multiprocessing\process.py", line 108, in run
2023-08-19 23:06:39 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-08-19 23:06:39 | ERROR | stderr |   File "C:\Users\ihsin\Langchain-Chatchat\Langchain-Chatchat-0.2.1\server\llm_api.py", line 193, in run_model_worker
2023-08-19 23:06:39 | ERROR | stderr |     app = create_model_worker_app(*args, **kwargs)
2023-08-19 23:06:39 | ERROR | stderr |   File "C:\Users\ihsin\Langchain-Chatchat\Langchain-Chatchat-0.2.1\server\llm_api.py", line 127, in create_model_worker_app
2023-08-19 23:06:39 | ERROR | stderr |     worker = ModelWorker(
2023-08-19 23:06:39 | ERROR | stderr |   File "C:\Users\ihsin\anaconda3\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 225, in __init__
2023-08-19 23:06:39 | ERROR | stderr |     self.init_heart_beat()
2023-08-19 23:06:39 | ERROR | stderr |   File "C:\Users\ihsin\Langchain-Chatchat\Langchain-Chatchat-0.2.1\server\llm_api.py", line 72, in _new_init_heart_beat
2023-08-19 23:06:39 | ERROR | stderr |     self.register_to_controller()
2023-08-19 23:06:39 | ERROR | stderr |   File "C:\Users\ihsin\anaconda3\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 109, in register_to_controller
2023-08-19 23:06:39 | ERROR | stderr |     assert r.status_code == 200
2023-08-19 23:06:39 | ERROR | stderr | AssertionError

**Comment by ihsin-yyx** [comment]
关闭科学上网后正常，还在排除问题

**Comment by soyisou** [comment]
> 关闭科学上网后正常，还在排除问题

找到问题了么？我这边关闭之后，还是出现这个AssertionError问题

**Comment by ihsin-yyx** [comment]
> > 关闭科学上网后正常，还在排除问题
> 
> 找到问题了么？我这边关闭之后，还是出现这个AssertionError问题
你去控制面板里面设置，打开所有的iis服务里面的子项，再关掉科学上网后试试。不行的话就把log日记扔给gpt或者Claude2排除问题

**Comment by ArlanCooper** [comment]
请问有人解决这个问题了吗？

**Comment by chujun-L** [comment]
我也遇到同样的问题

**Comment by xinzhu666** [comment]
一样的问题，Ubuntu22.04，没配置代理。新的虚拟机，端口也不存在占用的情况。丢到gpt4里面，返回`错误表明register_to_controller函数的HTTP响应状态码不是200。可能的原因是controller端未正确响应或地址错误。检查controller服务是否运行，地址是否正确。`

运行代码：
```shell
python server/llm_api_stale.py
```
报错信息：
```shell
2023-08-22 01:53:06 | INFO | model_worker | args: Namespace(host='localhost', port=20002, worker_address='http://localhost:20002', controller_address='http://localhost:21001', model_path='/home/ls/lab/models/chatglm2-6b', revision='main', device='cuda', gpus='0', num_gpus=1, max_gpu_memory='20GiB', load_8bit=False, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, model_names=None, conv_template=None, limit_worker_concurrency=5, stream_interval=2, no_register=False)
2023-08-22 01:53:06 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker e3847ee7 ...
2023-08-22 01:53:06 | ERROR | stderr |  ！这边空白的输出是哪里的问题？
Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]
2023-08-22 01:53:10 | ERROR | stderr | 
Loading checkpoint shards:  14%|█▍        | 1/7 [00:04<00:24,  4.07s/it]
2023-08-22 01:53:15 | ERROR | stderr | 
Loading checkpoint shards:  29%|██▊       | 2/7 [00:08<00:20,  4.13s/it]
2023-08-22 01:53:19 | ERROR | stderr | 
Loading checkpoint shards:  43%|████▎     | 3/7 [00:12<00:16,  4.17s/it]
2023-08-22 01:53:23 | ERROR | stderr | 
Loading checkpoint shards:  57%|█████▋    | 4/7 [00:16<00:12,  4.09s/it]
2023-08-22 01:53:27 | ERROR | stderr | 
Loading checkpoint shards:  71%|███████▏  | 5/7 [00:20<00:08,  4.02s/it]
2023-08-22 01:53:31 | ERROR | stderr | 
Loading checkpoint shards:  86%|████████▌ | 6/7 [00:24<00:04,  4.13s/it]
2023-08-22 01:53:34 | ERROR | stderr | 
Loading checkpoint shards: 100%|██████████| 7/7 [00:27<00:00,  3.59s/it]
2023-08-22 01:53:34 | ERROR | stderr | 
Loading checkpoint shards: 100%|██████████| 7/7 [00:27<00:00,  3.88s/it]
2023-08-22 01:53:34 | ERROR | stderr | 
2023-08-22 01:53:52 | INFO | model_worker | Register to controller
2023-08-22 01:53:52 | INFO | stdout | register_to_controller: http://localhost:21001/register_worker
2023-08-22 01:53:52 | ERROR | stderr | Traceback (most recent call last):
2023-08-22 01:53:52 | ERROR | stderr |   File "/home/ls/miniconda3/envs/Langchain/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-08-22 01:53:52 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-08-22 01:53:52 | ERROR | stderr |   File "/home/ls/miniconda3/envs/Langchain/lib/python3.10/runpy.py", line 86, in _run_code
2023-08-22 01:53:52 | ERROR | stderr |     exec(code, run_globals)
2023-08-22 01:53:52 | ERROR | stderr |   File "/home/ls/miniconda3/envs/Langchain/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 468, in <module>
2023-08-22 01:53:52 | ERROR | stderr |     worker = ModelWorker(
2023-08-22 01:53:52 | ERROR | stderr |   File "/home/ls/miniconda3/envs/Langchain/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 226, in __init__
2023-08-22 01:53:52 | ERROR | stderr |     self.init_heart_beat()
2023-08-22 01:53:52 | ERROR | stderr |   File "/home/ls/miniconda3/envs/Langchain/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 93, in init_heart_beat
2023-08-22 01:53:52 | ERROR | stderr |     self.register_to_controller()
2023-08-22 01:53:52 | ERROR | stderr |   File "/home/ls/miniconda3/envs/Langchain/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 110, in register_to_controller
2023-08-22 01:53:52 | ERROR | stderr |     assert r.status_code == 200
2023-08-22 01:53:52 | ERROR | stderr | AssertionError

```

**Comment by laosan2333** [comment]
俺也一样

**Comment by douyang8** [comment]
.bashrc里面加上这句
export no_proxy='$no_proxy,127.0.0.1'

**Comment by yycsu** [comment]
> .bashrc里面加上这句 export no_proxy='$no_proxy,127.0.0.1'

感谢老哥🙏，真的可以了！

**Comment by ArlanCooper** [comment]
> .bashrc里面加上这句 export no_proxy='$no_proxy,127.0.0.1'

优秀，我也可以了

**Comment by applepieiris** [comment]
> .bashrc里面加上这句 export no_proxy='$no_proxy,127.0.0.1'

有人遇到加了这一句之后streamlit界面报错：
`Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "$no_proxy", use "$no_proxy://"`
吗？

**Comment by ArlanCooper** [comment]
> > .bashrc里面加上这句 export no_proxy='$no_proxy,127.0.0.1'
> 
> 有人遇到加了这一句之后streamlit界面报错： `Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "$no_proxy", use "$no_proxy://"` 吗？

这个设置的是no_proxy参数，而不是proxy参数，可能你用错地方了吗？

**Comment by HaroldYoung** [comment]
> .bashrc里面加上这句 export no_proxy='$no_proxy,127.0.0.1'

请问这是哪个文件呢，我好像没有找到
