### ISSUE TITLE
多卡部署时遇到cuda不在同一设备上的问题

### ISSUE THREAD

**Issue by maceygo** [chatchat-space/Langchain-Chatchat#1187]
**问题描述 / Problem Description**

将模型部署在两个GPU设备上遇到报错

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'webui.py'
2.在对话框内输入内容
3.提交给问答模型
4. 问题出现 / Problem occurs

**实际结果 / Actual Result**
__call:hello
Traceback (most recent call last):
  File "/mnt/langchain-ChatGLM/models/base/base.py", line 114, in gen
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/mnt/langchain-ChatGLM/models/base/base.py", line 163, in generate_with_callback
    self._generate_answer(**kwargs)
  File "/mnt/langchain-ChatGLM/models/chatglm_llm.py", line 82, in _generate_answer
    for inum, (stream_resp, _) in enumerate(self.checkPoint.model.stream_chat(
  File "/root/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b-32k/modeling_chatglm.py", line 1072, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/root/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b-32k/modeling_chatglm.py", line 1157, in stream_generate
    outputs = self(
  File "/root/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b-32k/modeling_chatglm.py", line 946, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b-32k/modeling_chatglm.py", line 836, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b-32k/modeling_chatglm.py", line 655, in forward
    presents = torch.cat((presents, kv_cache), dim=0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.1.17
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2Vec
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:ubuntu16.04
- Python 版本 / Python version:3.8
- 其他相关环境信息 / Other relevant environment information:accelerate==0.18.0

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by hzg0601** [comment]
此为chatglm2-6b-32k的bug
