### ISSUE TITLE
默认配置启动，对话回复较慢，查看系统资源CPU负荷60%，GPU负荷没有

### ISSUE THREAD

**Issue by pessimo** [chatchat-space/Langchain-Chatchat#1189]
**问题描述 / Problem Description**
默认配置启动，对话回复较慢，查看系统资源CPU负荷60%，GPU负荷没有。怀疑是推理没有使用gpu？

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：拉的线上最新 c82134c07bb0e36cdd58e30511b8e7f93d89c034
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: win10
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information: 显卡是两张 4090 turbo，应该没有显存问题

**Comment by cwyalpha** [comment]
同样的问题，是在colab跑的chatglm-6b-int4，能跑通，但是GPU也没有在动，CPU比较慢

**Comment by pessimo** [comment]
检查后发现，是因为使用的 cuda12，和当前的 torch 不兼容。 升级torch 到nightly 版本即可

**Comment by CreamK** [comment]
请问你是怎么按转torch的，我使用https://pytorch.org/的方法pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121报错，报错如下：
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError

**Comment by pessimo** [comment]
我查了一下 你这个可能是 pip的错误
