### ISSUE TITLE
http://127.0.0.1:7861/chat/chat "HTTP/1.1 502 Bad Gateway"

### ISSUE THREAD

**Issue by liubixia55** [chatchat-space/Langchain-Chatchat#1207]
最新代码部署启动后，
 _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 502 Bad Gateway"

2023-08-23 14:05:18,130 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 502 Bad Gateway"
INFO:     127.0.0.1:62470 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\fastapi\applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\fastapi\routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\fastapi\routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\fastchat\serve\openai_api_server.py", line 340, in create_chat_completion
    error_check_ret = await check_model(request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\fastchat\serve\openai_api_server.py", line 118, in check_model
    models = models_ret.json()["models"]
             ^^^^^^^^^^^^^^^^^
  File "D:\bixia.liu\chatglm\Langchain-Chatchat\myenv\Lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidi\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidi\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidi\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：commit d79676c
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）： moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: windows11专业版21H2
- Python 版本 / Python version: 3.11.4
- 其他相关环境信息 / Other relevant environment information:

**Comment by liunux4odoo** [comment]
你是如何启动的？

**Comment by liubixia55** [comment]
一键启动也不行： python startup.py --all-webui

分步启动也不行： 
 python server/llm_api.py
 python server/api.py
 streamlit run webui.py




bealla
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] http://127.0.0.1:7861/chat/chat "HTTP/1.1 502 Bad Gateway" (Issue #1207)





 
你是如何启动的？

**Comment by liunux4odoo** [comment]
python startup.py --all-webui 终端log贴上来

**Comment by liubixia55** [comment]
(myenv) D:\bixia.liu\chatglm\Langchain-Chatchat&gt;python startup.py --all-webui
2023-08-23 15:00:03,846 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.






==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22000-SP0.
python版本：3.11.4 (tags/v3.11.4:d2340ef, Jun&nbsp; 7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
项目版本：v0.2.2-preview
langchain版本：0.0.266. fastchat版本：0.2.24




当前LLM模型：chatglm2-6b @ cuda
{'api_base_url': 'http://127.0.0.1:8888/v1',
&nbsp;'api_key': 'EMPTY',
&nbsp;'local_model_path': 'D:\\bixia.liu\\chatglm\\ChatGLM2-6B\\chatglm2-6b-int4'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================






2023-08-23 15:00:04,267 - startup.py[line:374] - INFO: 正在启动服务：
2023-08-23 15:00:04,267 - startup.py[line:375] - INFO: 如需查看 llm_api 日志，请前往 D:\bixia.liu\chatglm\Langchain-Chatchat\logs
2023-08-23 15:00:07 | ERROR | stderr | INFO:&nbsp; &nbsp; &nbsp;Started server process [20236]
2023-08-23 15:00:07 | ERROR | stderr | INFO:&nbsp; &nbsp; &nbsp;Waiting for application startup.
INFO:&nbsp; &nbsp; &nbsp;Started server process [17184]
INFO:&nbsp; &nbsp; &nbsp;Waiting for application startup.
2023-08-23 15:00:07 | ERROR | stderr | INFO:&nbsp; &nbsp; &nbsp;Application startup complete.
2023-08-23 15:00:07 | ERROR | stderr | INFO:&nbsp; &nbsp; &nbsp;Uvicorn running on http://127.0.0.1:20001 (Press CTRL+C to quit)
INFO:&nbsp; &nbsp; &nbsp;Application startup complete.
INFO:&nbsp; &nbsp; &nbsp;Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
2023-08-23 15:00:08 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 3767f7ba ...
2023-08-23 15:00:10,901 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
INFO:&nbsp; &nbsp; &nbsp;Started server process [25280]
INFO:&nbsp; &nbsp; &nbsp;Waiting for application startup.
2023-08-23 15:00:17 | INFO | model_worker | Register to controller
2023-08-23 15:00:17 | INFO | controller | Register a new worker: http://127.0.0.1:20002
2023-08-23 15:00:17 | INFO | controller | Register done: http://127.0.0.1:20002, {'model_names': ['chatglm2-6b'], 'speed': 1, 'queue_length': 0}
2023-08-23 15:00:17 | INFO | stdout | INFO:&nbsp; &nbsp; &nbsp;127.0.0.1:64727 - "POST /register_worker HTTP/1.1" 200 OK
2023-08-23 15:00:17 | ERROR | stderr | INFO:&nbsp; &nbsp; &nbsp;Started server process [4944]
2023-08-23 15:00:17 | ERROR | stderr | INFO:&nbsp; &nbsp; &nbsp;Waiting for application startup.
2023-08-23 15:00:18 | ERROR | stderr | INFO:&nbsp; &nbsp; &nbsp;Application startup complete.
INFO:&nbsp; &nbsp; &nbsp;Application startup complete.
2023-08-23 15:00:18 | ERROR | stderr | INFO:&nbsp; &nbsp; &nbsp;Uvicorn running on http://127.0.0.1:20002 (Press CTRL+C to quit)
INFO:&nbsp; &nbsp; &nbsp;Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)






==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22000-SP0.
python版本：3.11.4 (tags/v3.11.4:d2340ef, Jun&nbsp; 7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
项目版本：v0.2.2-preview
langchain版本：0.0.266. fastchat版本：0.2.24




当前LLM模型：chatglm2-6b @ cuda
{'api_base_url': 'http://127.0.0.1:8888/v1',
&nbsp;'api_key': 'EMPTY',
&nbsp;'local_model_path': 'D:\\bixia.liu\\chatglm\\ChatGLM2-6B\\chatglm2-6b-int4'}
当前Embbedings模型： m3e-base @ cuda




服务端运行信息：
&nbsp; &nbsp; OpenAI API Server: http://127.0.0.1:8888/v1
&nbsp; &nbsp; &nbsp;(请确认llm_model_dict中配置的api_base_url与上面地址一致。)
&nbsp; &nbsp; Chatchat&nbsp; API&nbsp; Server: http://127.0.0.1:7861
&nbsp; &nbsp; Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================








&nbsp; You can now view your Streamlit app in your browser.


&nbsp; URL: http://127.0.0.1:8501


2023-08-23 15:00:35,882 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 502 Bad Gateway"

2023-08-23 15:01:02 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: 3767f7ba.
2023-08-23 15:01:02 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-08-23 15:01:02 | INFO | stdout | INFO:&nbsp; &nbsp; &nbsp;127.0.0.1:64861 - "POST /receive_heart_beat HTTP/1.1" 200 OK



bealla
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] http://127.0.0.1:7861/chat/chat "HTTP/1.1 502 Bad Gateway" (Issue #1207)





 
python startup.py --all-webui 终端log贴上来

**Comment by liunux4odoo** [comment]
服务都正常启动了，应该没有问题。你有设置全局代理一类的吗？

**Comment by liubixia55** [comment]
真的是代理的问题，感谢感谢！


bealla
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] http://127.0.0.1:7861/chat/chat "HTTP/1.1 502 Bad Gateway" (Issue #1207)





 
服务都正常启动了，应该没有问题。你有设置全局代理一类的吗？

**Comment by Duyz232** [comment]
> 真的是代理的问题，感谢感谢！ bealla ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chatchat-space/Langchain-Chatchat" ***@***.***&gt;; 发送时间:&nbsp;2023年8月23日(星期三) 下午3:05 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] http://127.0.0.1:7861/chat/chat "HTTP/1.1 502 Bad Gateway" (Issue #1207) 服务都正常启动了，应该没有问题。你有设置全局代理一类的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您是如何解决的呢？？我也遇到这个问题。

**Comment by Amos20191021** [comment]
这个就是我们部署时候拉源使用了科学上网：我是Windows机器用梯子，然后Linux服务器全局代理向这台Windows。等到跑起来的时候，这个全局代理未取消，而导致，unset http_proxy
unset https_proxy
就可以了
