### ISSUE TITLE
[BUG] 执行python3 init_database.py --recreate-vs 初始化命令报错

### ISSUE THREAD

**Issue by py-carol** [chatchat-space/Langchain-Chatchat#1208]
**问题描述 / Problem Description**
执行python3 init_database.py --recreate-vs报错
database talbes created
filling kb infos to database
loading vector store in 'samples'.
2023-08-23 07:04:43,636 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /root/m3e-base
2023-08-23 07:04:43,678 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmplgvq6pu_
2023-08-23 07:04:43,678 - instantiator.py[line:76] - INFO: Writing /tmp/tmplgvq6pu_/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/root/dev/langchain-ChatGLM/init_database.py", line 37, in <module>
    folder2db(kb, "fill_info_only")
  File "/root/dev/langchain-ChatGLM/server/knowledge_base/migrate.py", line 36, in folder2db
    kb.create_kb()
  File "/root/dev/langchain-ChatGLM/server/knowledge_base/kb_service/base.py", line 53, in create_kb
    self.do_create_kb()
  File "/root/dev/langchain-ChatGLM/server/knowledge_base/kb_service/faiss_kb_service.py", line 94, in do_create_kb
    load_vector_store(self.kb_name)
  File "/root/dev/langchain-ChatGLM/server/knowledge_base/kb_service/faiss_kb_service.py", line 43, in load_vector_store
    embeddings = load_embeddings(embed_model, embed_device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/dev/langchain-ChatGLM/server/knowledge_base/utils.py", line 44, in load_embeddings
    embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict[model],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 65, in __init__
    self.client = sentence_transformers.SentenceTransformer(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2629, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/soft/python3.11.4/lib/python3.11/site-packages/transformers/modeling_utils.py", line 447, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28
- Python 版本 / Python version: 3.11.4 
- 其他相关环境信息 / Other relevant environment information: langchain版本：0.0.266. fastchat版本：0.2.24

**附加信息 / Additional Information**

**Comment by hundyoung** [comment]
I met the same issue. Then I fixed it by redownloading the model.

**Comment by py-carol** [comment]
> 

The updated version still has the same error. I would like to know if there are any other third-party libraries that need to be installed besides requirements. txt

**Comment by qiyer** [comment]
库的版本问题，之前也遇到了，把库都卸载了，重新安装就好了。
（通常是之前安装了Langchain-Chatchat 老版本，后来升级最新版本，因为有些库的依赖问题，导致某些必须库的版本没有升级上来，还是老版本，就会出现上述问题）

**Comment by py-carol** [comment]
谢谢！ 已经解决了，确实是因为模型问题导致的，我是使用git clone命令下载模型的，没报错就以为下载ok，后来才发现模型的size对不上，好像是没下载完整，一整个大乌龙，重新一个一个文件下载了，然后就OK了

**Comment by AiDaShi** [comment]
> 谢谢！ 已经解决了，确实是因为模型问题导致的，我是使用git clone命令下载模型的，没报错就以为下载ok，后来才发现模型的size对不上，好像是没下载完整，一整个大乌龙，重新一个一个文件下载了，然后就OK了

我目前也遇到这个问题请问是哪个模型呢？

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后重试
