### ISSUE TITLE
windows 私有模型部署出现异常 AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by zhangfangxing** [chatchat-space/Langchain-Chatchat#1215]
**问题描述 / Problem Description**
windows10系统部署该项目是没问题的，包括我加载知识库之类的测试也是没问题的。
后来我自己弄了个模型，用glm2-6b进行微调之后的，放在了server目录下，创建了个models文件夹，却始终没办法解决。报错问题。

**复现问题的步骤 / Steps to Reproduce**
执行 python server\llm_api.py时候出现的错误。

**实际结果 / Actual Result**
报错内容如下所示：
```
2023-08-23 18:36:48,178 - llm_api.py[line:231] - INFO: {'local_model_path': 'D:/myGLM-6B/Langchain-Chatchat-master/Langchain-Chatchat-master/server/models', 'api_base_url': 'http://localhost:8888/v1', 'api_key': 'EMPTY'}
2023-08-23 18:36:48,178 - llm_api.py[line:234] - INFO: 如需查看 llm_api 日志，请前往 D:\myGLM-6B\Langchain-Chatchat-master\Langchain-Chatchat-master\logs
2023-08-23 18:36:50 | ERROR | stderr | INFO:     Started server process [17692]
2023-08-23 18:36:50 | ERROR | stderr | INFO:     Waiting for application startup.
INFO:     Started server process [9312]
INFO:     Waiting for application startup.
2023-08-23 18:36:50 | ERROR | stderr | INFO:     Application startup complete.
2023-08-23 18:36:50 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20001 (Press CTRL+C to quit)
2023-08-23 18:36:50 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 2b65a77c ...
2023-08-23 18:36:50 | ERROR | stderr | Process model_worker(8756):
2023-08-23 18:36:50 | ERROR | stderr | Traceback (most recent call last):
2023-08-23 18:36:50 | ERROR | stderr |   File "C:\Users\jczd\.conda\envs\mytest4\lib\multiprocessing\process.py", line 315, in _bootstrap
2023-08-23 18:36:50 | ERROR | stderr |     self.run()
2023-08-23 18:36:50 | ERROR | stderr |   File "C:\Users\jczd\.conda\envs\mytest4\lib\multiprocessing\process.py", line 108, in run
2023-08-23 18:36:50 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-08-23 18:36:50 | ERROR | stderr |   File "D:\myGLM-6B\Langchain-Chatchat-master\Langchain-Chatchat-master\server\llm_api.py", line 194, in run_model_worker
2023-08-23 18:36:50 | ERROR | stderr |     app = create_model_worker_app(*args, **kwargs)
2023-08-23 18:36:50 | ERROR | stderr |   File "D:\myGLM-6B\Langchain-Chatchat-master\Langchain-Chatchat-master\server\llm_api.py", line 128, in create_model_worker_app
2023-08-23 18:36:50 | ERROR | stderr |     worker = ModelWorker(
2023-08-23 18:36:50 | ERROR | stderr |   File "C:\Users\jczd\.conda\envs\mytest4\lib\site-packages\fastchat\serve\model_worker.py", line 207, in __init__
2023-08-23 18:36:50 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-08-23 18:36:50 | ERROR | stderr |   File "C:\Users\jczd\.conda\envs\mytest4\lib\site-packages\fastchat\model\model_adapter.py", line 268, in load_model
2023-08-23 18:36:50 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-08-23 18:36:50 | ERROR | stderr |   File "C:\Users\jczd\.conda\envs\mytest4\lib\site-packages\fastchat\model\model_adapter.py", line 72, in load_model
2023-08-23 18:36:50 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2023-08-23 18:36:50 | ERROR | stderr |   File "C:\Users\jczd\.conda\envs\mytest4\lib\site-packages\transformers\models\auto\auto_factory.py", line 461, in from_pretrained
2023-08-23 18:36:50 | ERROR | stderr |     config, kwargs = AutoConfig.from_pretrained(
2023-08-23 18:36:50 | ERROR | stderr |   File "C:\Users\jczd\.conda\envs\mytest4\lib\site-packages\transformers\models\auto\configuration_auto.py", line 986, in from_pretrained
2023-08-23 18:36:50 | ERROR | stderr |     trust_remote_code = resolve_trust_remote_code(
2023-08-23 18:36:50 | ERROR | stderr |   File "C:\Users\jczd\.conda\envs\mytest4\lib\site-packages\transformers\dynamic_module_utils.py", line 535, in resolve_trust_remote_code
2023-08-23 18:36:50 | ERROR | stderr |     signal.signal(signal.SIGALRM, _raise_timeout_error)
2023-08-23 18:36:50 | ERROR | stderr | AttributeError: module 'signal' has no attribute 'SIGALRM'


```

**环境信息 / Environment Information**
python3.8
源码部署未使用docker
使用 我自己微调之后的chatglm2-6b模型。该模型经过测试，是可以正常运心的。不考虑这个模型的情况下，本项目运行无异常。

** model_config.py 内容**
```
import os
import logging
import torch
# 日志格式
LOG_FORMAT = "%(asctime)s - %(filename)s[line:%(lineno)d] - %(levelname)s: %(message)s"
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logging.basicConfig(format=LOG_FORMAT)


# 在以下字典中修改属性值，以指定本地embedding模型存储位置
# 如将 "text2vec": "GanymedeNil/text2vec-large-chinese" 修改为 "text2vec": "User/Downloads/text2vec-large-chinese"
# 此处请写绝对路径
embedding_model_dict = {
    "ernie-tiny": "nghuyong/ernie-3.0-nano-zh",
    "ernie-base": "nghuyong/ernie-3.0-base-zh",
    "text2vec-base": "shibing624/text2vec-base-chinese",
    "text2vec": "GanymedeNil/text2vec-large-chinese",
    "text2vec-paraphrase": "shibing624/text2vec-base-chinese-paraphrase",
    "text2vec-sentence": "shibing624/text2vec-base-chinese-sentence",
    "text2vec-multilingual": "shibing624/text2vec-base-multilingual",
    "m3e-small": "moka-ai/m3e-small",
    "m3e-base": "moka-ai/m3e-base",
    "m3e-large": "moka-ai/m3e-large",
    "bge-small-zh": "BAAI/bge-small-zh",
    "bge-base-zh": "BAAI/bge-base-zh",
    "bge-large-zh": "BAAI/bge-large-zh"
}

# 选用的 Embedding 名称
EMBEDDING_MODEL = "m3e-base"

# Embedding 模型运行设备
EMBEDDING_DEVICE = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"


llm_model_dict = {
    "chatglm-6b": {
        "local_model_path": "",
        "api_base_url": "http://localhost:8888/v1",  # "name"修改为fastchat服务中的"api_base_url"
        "api_key": "EMPTY"
    },

    "chatglm-6b-int4": {
        "local_model_path": "",
        "api_base_url": "http://localhost:8888/v1",  # "name"修改为fastchat服务中的"api_base_url"
        "api_key": "EMPTY"
    },

    "chatglm2-6b": {
        "local_model_path": "D:/myGLM-6B/Langchain-Chatchat-master/Langchain-Chatchat-master/server/models",
        "api_base_url": "http://localhost:8888/v1",  # URL需要与运行fastchat服务端的server_config.FSCHAT_OPENAI_API一致
        "api_key": "EMPTY"
    },

    "chatglm2-6b-32k": {
        "local_model_path": "",  # "THUDM/chatglm2-6b-32k",
        "api_base_url": "http://localhost:8888/v1",  # "URL需要与运行fastchat服务端的server_config.FSCHAT_OPENAI_API一致
        "api_key": "EMPTY"
    },

    "vicuna-13b-hf": {
        "local_model_path": "",
        "api_base_url": "http://localhost:8888/v1",  # "name"修改为fastchat服务中的"api_base_url"
        "api_key": "EMPTY"
    },

    # 调用chatgpt时如果报出： urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443):
    #  Max retries exceeded with url: /v1/chat/completions
    # 则需要将urllib3版本修改为1.25.11
    # 如果依然报urllib3.exceptions.MaxRetryError: HTTPSConnectionPool，则将https改为http
    # 参考https://zhuanlan.zhihu.com/p/350015032

    # 如果报出：raise NewConnectionError(
    # urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001FE4BDB85E0>:
    # Failed to establish a new connection: [WinError 10060]
    # 则是因为内地和香港的IP都被OPENAI封了，需要切换为日本、新加坡等地
    "gpt-3.5-turbo": {
        "local_model_path": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": os.environ.get("OPENAI_API_KEY")
    },
}


# LLM 名称
LLM_MODEL = "chatglm2-6b"

# LLM 运行设备
LLM_DEVICE = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"

# 日志存储路径
LOG_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "logs")
if not os.path.exists(LOG_PATH):
    os.mkdir(LOG_PATH)

# 知识库默认存储路径
KB_ROOT_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "knowledge_base")

# 数据库默认存储路径。
# 如果使用sqlite，可以直接修改DB_ROOT_PATH；如果使用其它数据库，请直接修改SQLALCHEMY_DATABASE_URI。
DB_ROOT_PATH = os.path.join(KB_ROOT_PATH, "info.db")
SQLALCHEMY_DATABASE_URI = f"sqlite:///{DB_ROOT_PATH}"

# 可选向量库类型及对应配置
kbs_config = {
    "faiss": {
    },
    "milvus": {
        "host": "127.0.0.1",
        "port": "19530",
        "user": "",
        "password": "",
        "secure": False,
    },
    "pg": {
        "connection_uri": "postgresql://postgres:postgres@127.0.0.1:5432/langchain_chatchat",
    }
}

# 默认向量库类型。可选：faiss, milvus, pg.
DEFAULT_VS_TYPE = "faiss"

# 缓存向量库数量
CACHED_VS_NUM = 1

# 知识库中单段文本长度
CHUNK_SIZE = 250

# 知识库中相邻文本重合长度
OVERLAP_SIZE = 50

# 知识库匹配向量数量
VECTOR_SEARCH_TOP_K = 5

# 知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右
SCORE_THRESHOLD = 1

# 搜索引擎匹配结题数量
SEARCH_ENGINE_TOP_K = 5

# nltk 模型存储路径
NLTK_DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "nltk_data")

# 基于本地知识问答的提示词模版
PROMPT_TEMPLATE = """【指令】根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，不允许在答案中添加编造成分，答案请使用中文。 

【已知信息】{context} 

【问题】{question}"""

# API 是否开启跨域，默认为False，如果需要开启，请设置为True
# is open cross domain
OPEN_CROSS_DOMAIN = False

# Bing 搜索必备变量
# 使用 Bing 搜索需要使用 Bing Subscription Key,需要在azure port中申请试用bing search
# 具体申请方式请见
# https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/create-bing-search-service-resource
# 使用python创建bing api 搜索实例详见:
# https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/quickstarts/rest/python
BING_SEARCH_URL = "https://api.bing.microsoft.com/v7.0/search"
# 注意不是bing Webmaster Tools的api key，

# 此外，如果是在服务器上，报Failed to establish a new connection: [Errno 110] Connection timed out
# 是因为服务器加了防火墙，需要联系管理员加白名单，如果公司的服务器的话，就别想了GG
BING_SUBSCRIPTION_KEY = ""

# 是否开启中文标题加强，以及标题增强的相关配置
# 通过增加标题判断，判断哪些文本为标题，并在metadata中进行标记；
# 然后将文本与往上一级的标题进行拼合，实现文本信息的增强。
ZH_TITLE_ENHANCE = False
```

**Comment by zhangfangxing** [comment]
换句话说这里本地模型应该怎么写= =

    "chatglm2-6b": {
        "local_model_path": "D:/myGLM-6B/Langchain-Chatchat-master/Langchain-Chatchat-master/server/models",
        "api_base_url": "http://localhost:8888/v1",  # URL需要与运行fastchat服务端的server_config.FSCHAT_OPENAI_API一致
        "api_key": "EMPTY"
    },

**Comment by imClumsyPanda** [comment]
建议参考这个网页中的回答 https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows

**Comment by zhangfangxing** [comment]
很难说这是一个有效的回答，我也查看了这部分代码，猜测是这个工具包的bug，而非这个项目的bug。

目前我通过替换缓存的方式运行起来了。但是感觉没有真正意义上解决问题。有空我会继续测试的。

感谢你的回复～

> 建议参考这个网页中的回答 https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows
