### ISSUE TITLE
如何设置 trust_remote_code=True ？我在加载XVERSE模型时，出现需要设置 trust_remote_code=True的提示

### ISSUE THREAD

**Issue by tms2003** [chatchat-space/Langchain-Chatchat#1216]
我直接加入XVERSE模型，结果出错了：

```

2023-08-23 13:13:41 | ERROR | stderr | Traceback (most recent call last):                                                    
2023-08-23 13:13:41 | ERROR | stderr |   File "/root/miniconda3/envs/glm/lib/python3.10/multiprocessing/process.py", line 315
, in _bootstrap                                                                                                              
2023-08-23 13:13:41 | ERROR | stderr |     self.run()                                                                        
2023-08-23 13:13:41 | ERROR | stderr |   File "/root/miniconda3/envs/glm/lib/python3.10/multiprocessing/process.py", line 108
, in run                                                                                                                     
2023-08-23 13:13:41 | ERROR | stderr |     self._target(*self._args, **self._kwargs)                                         
2023-08-23 13:13:41 | ERROR | stderr |   File "/tangcan/source/llm/Langchain-Chatchat/server/llm_api.py", line 195, in run_mo
del_worker                                                                                                                   
2023-08-23 13:13:41 | ERROR | stderr |     app = create_model_worker_app(*args, **kwargs)                                    
2023-08-23 13:13:41 | ERROR | stderr |   File "/tangcan/source/llm/Langchain-Chatchat/server/llm_api.py", line 128, in create
_model_worker_app                                                                                                            
2023-08-23 13:13:41 | ERROR | stderr |     worker = ModelWorker(                                                             
2023-08-23 13:13:41 | ERROR | stderr | TypeError: ModelWorker.__init__() got an unexpected keyword argument 'trust_remote_cod
e'
^C2023-08-23 13:14:39 | ERROR | stderr | INFO:     Shutting down


2023-08-23 13:20:21 | ERROR | stderr |     raise ValueError(
2023-08-23 13:20:21 | ERROR | stderr | ValueError: Loading this model requires you to execute execute some code in that repo on your local machine. Make sure you have read the code at https://hf.co//xxx/source/llm/XVERSE-13B/XVERSE-13B-Chat to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.



```
提示是需要进行

**Comment by aphrodite1028** [comment]
遇到同样的错误，没找到入口

**Comment by hzg0601** [comment]
fastchat默认为True,请检查fastchat的版本

**Comment by zhangzhibang** [comment]
> 遇到同样的错误，没找到入口

老哥这个问题解决了吗,我也遇到了

**Comment by yinhaoxs** [comment]
<img width="860" alt="截屏2023-10-31 11 30 23" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/45021245/1bbf7008-489e-4c89-b885-6c22744a2084">
加一下就可以了

**Comment by 1986smalltiger** [comment]
> <img alt="截屏2023-10-31 11 30 23" width="860" src="https://user-images.githubusercontent.com/45021245/279250857-1bbf7008-489e-4c89-b885-6c22744a2084.png"> 加一下就可以
这个文件在什么位置？
