### ISSUE TITLE
[BUG] KeyError: 'st.session_state has no key "messages". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'```

### ISSUE THREAD

**Issue by BEILOP** [chatchat-space/Langchain-Chatchat#1222]
**问题描述 / Problem Description**
KeyError: 'st.session_state has no key "messages". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

**复现问题的步骤 / Steps to Reproduce**
python webui.py

**预期的结果 / Expected Result**
打开web页面

**实际结果 / Actual Result**
```  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run webui.py [ARGUMENTS]
Traceback (most recent call last):
  File "/home/anaconda3/envs/aigc/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 378, in __getitem__
    return self._getitem(widget_id, key)
  File "/home/anaconda3/envs/aigc/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 423, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiaojiaxin/langchain-ChatGLM/webui.py", line 70, in <module>
    pages[selected_page]["func"](api)
  File "/home/jiaojiaxin/langchain-ChatGLM/webui_pages/dialogue/dialogue.py", line 40, in dialogue_page
    chat_box.init_session()
  File "/home/anaconda3/envs/aigc/lib/python3.10/site-packages/streamlit_chatbox/messages.py", line 33, in init_session
    self.reset_history("默认会话")
  File "/home/anaconda3/envs/aigc/lib/python3.10/site-packages/streamlit_chatbox/messages.py", line 37, in reset_history
    st.session_state[self._session_key].update({name: []})
  File "/home/anaconda3/envs/aigc/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
  File "/home/anaconda3/envs/aigc/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 113, in __getitem__
    return self._state[key]
  File "/home/anaconda3/envs/aigc/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 380, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "messages". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B -int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:ubuntu
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by BEILOP** [comment]
streamlit                 1.25.0
streamlit-aggrid          0.3.4.post3
streamlit-antd-components 0.1.16
streamlit-chatbox         1.1.6
streamlit-option-menu     0.3.6

**Comment by myron--0** [comment]
我也遇到了这个问题，你们问题都解决了吗

**Comment by imClumsyPanda** [comment]
打开webui应使用命令 streamlit run webui.py

按照报错信息，推测使用的是命令 python webui.py
