### ISSUE TITLE
Execute Command $ python init_database.py --recreate-vs Error occurred after

### ISSUE THREAD

**Issue by libing331** [chatchat-space/Langchain-Chatchat#1243]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Execute Command $ python init_database.py --recreate-vs Error occurred after

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / $ python init_database.py --recreate-vs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / D:\qlt\Langchain-Chatchat-master>python init_database.py --recreate-vs
2023-08-25 15:59:53,801 - utils.py[line:160] - INFO: NumExpr defaulting to 4 threads.

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19041-SP0.
python版本：3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)]
项目版本：v0.2.2-preview
langchain版本：0.0.248. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b @ cpu
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'D:\\qlt\\Langchain-Chatchat-master\\chatglm2-6b'}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

database talbes created
recreating all vector stores
loading vector store in 'samples'.
2023-08-25 15:59:55,962 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: D:\qlt\Langchain-Chatchat-master\m3e-base
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.87it/s]
2023-08-25 15:59:57,087 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-08-25 15:59:57,087 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-08-25 15:59:57,088 - loader.py[line:64] - INFO: Loading faiss.
2023-08-25 15:59:57,142 - loader.py[line:66] - INFO: Successfully loaded faiss.
Traceback (most recent call last):
  File "init_database.py", line 33, in <module>
    recreate_all_vs()
  File "D:\qlt\Langchain-Chatchat-master\server\knowledge_base\migrate.py", line 114, in recreate_all_vs
    folder2db(kb_name, "recreate_vs", vs_type, embed_mode, **kwargs)
  File "D:\qlt\Langchain-Chatchat-master\server\knowledge_base\migrate.py", line 36, in folder2db
    kb.create_kb()
  File "D:\qlt\Langchain-Chatchat-master\server\knowledge_base\kb_service\base.py", line 53, in create_kb
    self.do_create_kb()
  File "D:\qlt\Langchain-Chatchat-master\server\knowledge_base\kb_service\faiss_kb_service.py", line 94, in do_create_kb
    load_vector_store(self.kb_name)
  File "D:\qlt\Langchain-Chatchat-master\server\knowledge_base\kb_service\faiss_kb_service.py", line 55, in load_vector_store
    search_index.delete(ids)
  File "C:\Users\qlt\AppData\Local\Programs\Python\Python38\lib\site-packages\langchain\vectorstores\base.py", line 81, in delete
    raise NotImplementedError("delete method must be implemented by subclass.")
NotImplementedError: delete method must be implemented by subclass.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：no / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:windows10
- Python 版本 / Python version:v3.8.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imClumsyPanda** [comment]
langchain版本未按照requirements要求更新

**Comment by EhetshamNehal** [comment]
How did you solve this? I'm getting the same error.
