### ISSUE TITLE
llm api启动保持，依赖requirements都安装了，切换多个pyenv都一样的问题

### ISSUE THREAD

**Issue by joeiren** [chatchat-space/Langchain-Chatchat#1247]
root@autodl-:~/autodl-tmp/Langchain-Chatchat# python startup.py --llm-api

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-100-generic-x86_64-with-glibc2.17.
python版本：3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]
项目版本：v0.2.2
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b @ cuda
{'api_base_url': 'http://localhost:8889/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'THUDM/chatglm2-6b'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-08-25 18:22:28,797 - startup.py[line:382] - INFO: 正在启动服务：
2023-08-25 18:22:28,797 - startup.py[line:383] - INFO: 如需查看 llm_api 日志，请前往 /root/autodl-tmp/Langchain-Chatchat/logs
2023-08-25 18:22:30 | ERROR | stderr | INFO:     Started server process [2472]
2023-08-25 18:22:30 | ERROR | stderr | INFO:     Waiting for application startup.
2023-08-25 18:22:30 | ERROR | stderr | INFO:     Application startup complete.
2023-08-25 18:22:30 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20001 (Press CTRL+C to quit)
INFO:     Started server process [2473]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8889 (Press CTRL+C to quit)
Process model_worker(2439):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/autodl-tmp/Langchain-Chatchat/startup.py", line 213, in run_model_worker
    app = create_model_worker_app(**kwargs)
  File "/root/autodl-tmp/Langchain-Chatchat/startup.py", line 53, in create_model_worker_app
    from fastchat.serve.model_worker import app, GptqConfig, AWQConfig, ModelWorker, worker_id
  File "/root/miniconda3/lib/python3.8/site-packages/fastchat/serve/model_worker.py", line 39, in <module>
    from fastchat.model.model_adapter import (
  File "/root/miniconda3/lib/python3.8/site-packages/fastchat/model/__init__.py", line 1, in <module>
    from fastchat.model.model_adapter import (
  File "/root/miniconda3/lib/python3.8/site-packages/fastchat/model/model_adapter.py", line 14, in <module>
    import accelerate
ModuleNotFoundError: No module named 'accelerate'

**Comment by joeiren** [comment]
补充：logs目录下只有一个controller.log文件，但是无日志记录。

**Comment by imClumsyPanda** [comment]
请执行 pip install accelerate 并看下执行后是否还存在该问题
