### ISSUE TITLE
[BUG] mac m1 执行 pip3 install -r requirements.txt  报错

### ISSUE THREAD

**Issue by yudidi** [chatchat-space/Langchain-Chatchat#1268]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**

1. 执行 conda create -n chain python=3.10
2. conda activate chain
3. git clone https://github.com/chatchat-space/Langchain-Chatchat.git
4. cd Langchain-Chatchat/
5.  pip3 install -r requirements.txt -i https://pypi.Python.org/simple/
6. 问题出现

**预期的结果 / Expected Result**
应该安装完成。

**实际结果 / Actual Result**
```
Collecting wavedrom (from markdown2[all]->fschat==0.2.24->-r requirements.txt (line 4))
  Using cached wavedrom-2.0.3.post3.tar.gz (137 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      /Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
        ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/1d/66/8f42c941be949ef2b22fe905d850c794e7c170a526023612aad5f3a121ad/setuptools_scm-7.1.0-py3-none-any.whl#sha256=73988b6d848709e2af142aa48c986ea29592bbcfca5375678064708205253d8e (from https://pypi.tuna.tsinghua.edu.cn/simple/setuptools-scm/) (requires-python:>=3.7)
      ERROR: Could not install requirement setuptools_scm from https://pypi.tuna.tsinghua.edu.cn/packages/1d/66/8f42c941be949ef2b22fe905d850c794e7c170a526023612aad5f3a121ad/setuptools_scm-7.1.0-py3-none-any.whl#sha256=73988b6d848709e2af142aa48c986ea29592bbcfca5375678064708205253d8e because of HTTP error 403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/1d/66/8f42c941be949ef2b22fe905d850c794e7c170a526023612aad5f3a121ad/setuptools_scm-7.1.0-py3-none-any.whl for URL https://pypi.tuna.tsinghua.edu.cn/packages/1d/66/8f42c941be949ef2b22fe905d850c794e7c170a526023612aad5f3a121ad/setuptools_scm-7.1.0-py3-none-any.whl#sha256=73988b6d848709e2af142aa48c986ea29592bbcfca5375678064708205253d8e (from https://pypi.tuna.tsinghua.edu.cn/simple/setuptools-scm/) (requires-python:>=3.7)
      Traceback (most recent call last):
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/didiyu/ENTER/envs/chain/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/yd/mp5rd9bx1x3670cth1fp7n180000gn/T/tmpkl7z5ekl', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/yd/mp5rd9bx1x3670cth1fp7n180000gn/T/pip-install-5ycjd35i/wavedrom_5712b4c761c94f32ad89a8564e8619cd/setup.py", line 28, in <module>
          setup(
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/setuptools/dist.py", line 907, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
        File "/Users/didiyu/ENTER/envs/chain/lib/python3.10/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/didiyu/ENTER/envs/chain/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/yd/mp5rd9bx1x3670cth1fp7n180000gn/T/tmpkl7z5ekl', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：37985f29f01a7606081f8b8ce50a3fbd546743b5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：还没到这一步
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： 默认
- 操作系统及版本 / Operating system and version: mac m1, 16g,8cpu
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imClumsyPanda** [comment]
我这边是m1 max的macos开发环境，homebrew方式安装的conda，python 3.8的环境下，测试pip install -r requirements.txt没有问题。

**Comment by yudidi** [comment]
我后来单独安装了wheel，然后pip install -r requirements.txt也没问题了.

**Comment by GeoJX** [comment]
step1: pip install setuptools_scm
step 2: pip install wavedrom -i https://pypi.tuna.tsinghua.edu.cn/simple
It work!
