### ISSUE TITLE
KeyError: 'answer'

### ISSUE THREAD

**Issue by BoFan-tunning** [chatchat-space/Langchain-Chatchat#1276]
KeyError: 'answer'
2023-08-27 22:54:40,265 - utils.py[line:242] - ERROR: Unterminated string starting at: line 1 column 512 (char 511)
2023-08-27 22:54:40.266 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "D:\glm\Langchain-Chatchat\webui.py", line 70, in <module>
    pages[selected_page]["func"](api)
  File "D:\glm\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 122, in dialogue_page
    text += d["answer"]
KeyError: 'answer'
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/129488076/bd178369-825d-4a06-9e52-d8678f5499a7)
最新版本
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/129488076/42b3bed5-e9e0-4f55-959a-bcc7aad17f4d)

**Comment by dayphosphor** [comment]
同样遇到这样的问题

**Comment by weifan-zhao** [comment]
同样遇到这样的问题+1

**Comment by sanlanwa** [comment]
这个怎么解决？
