### ISSUE TITLE
[BUG] 本地部署断开网络连接无法对话

### ISSUE THREAD

**Issue by Andrewlilei** [chatchat-space/Langchain-Chatchat#1298]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

本地按README 默认部署，发现无法离线使用。Config enable 跨域True 也无法解决。

**复现问题的步骤 / Steps to Reproduce**
完全按照README中的本地默认配置进行

**预期的结果 / Expected Result**
下载所有模型，完全实现应该本地运行

**实际结果 / Actual Result**
1） 发现无法实现离线使用，一旦断开网络就不能对话。并且报错
![ee1c6c887d75e44f3e178fff29f1234](https://github.com/chatchat-space/Langchain-Chatchat/assets/132241862/e9825ca4-9838-4f50-a380-d1336dd9c430)
2）FastAPI doc 访问始终出错 Could not render
![f830c1df20d6ff21b7f7ce0357f240b](https://github.com/chatchat-space/Langchain-Chatchat/assets/132241862/953c2962-9df2-40ea-946c-7ff8db9d98c5)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.0.266.
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:  WIN10
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

操作系统：Windows-10-10.0.19045-SP0.
python版本：3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.2
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b @ cuda
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'f:/Huggingface/ChatGLM/LLM/ChatGLM2-6B-main'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-08-29 13:02:14,021 - startup.py[line:382] - INFO: 正在启动服务：
2023-08-29 13:02:14,021 - startup.py[line:383] - INFO: 如需查看 llm_api 日志，请前往 F:\Huggingface\ChatGLM\LLM\Langchain-Chatchat-master\logs
2023-08-29 13:02:17 | ERROR | stderr | INFO:     Started server process [20672]
2023-08-29 13:02:17 | ERROR | stderr | INFO:     Waiting for application startup.
INFO:     Started server process [21488]
INFO:     Waiting for application startup.
2023-08-29 13:02:17 | ERROR | stderr | INFO:     Application startup complete.
2023-08-29 13:02:17 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20001 (Press CTRL+C to quit)
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
2023-08-29 13:02:17 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker aec75a96 ...
Loading checkpoint shards:   0%|                                                                                                                | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|██████████████▊                                                                                         | 1/7 [00:01<00:08,  1.48s/it]
INFO:     Started server process [13664]
INFO:     Waiting for application startup.
Loading checkpoint shards:  29%|█████████████████████████████▋                                                                          | 2/7 [00:03<00:07,  1.58s/it]
Loading checkpoint shards:  43%|████████████████████████████████████████████▌                                                           | 3/7 [00:04<00:06,  1.55s/it]
Loading checkpoint shards:  57%|███████████████████████████████████████████████████████████▍                                            | 4/7 [00:06<00:04,  1.52s/it]
Loading checkpoint shards:  71%|██████████████████████████████████████████████████████████████████████████▎                             | 5/7 [00:07<00:03,  1.53s/it]
Loading checkpoint shards:  86%|█████████████████████████████████████████████████████████████████████████████████████████▏              | 6/7 [00:09<00:01,  1.54s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.33s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.45s/it]
2023-08-29 13:02:28 | ERROR | stderr |
2023-08-29 13:02:33 | INFO | model_worker | Register to controller
2023-08-29 13:02:33 | INFO | controller | Register a new worker: http://127.0.0.1:20002
2023-08-29 13:02:33 | INFO | controller | Register done: http://127.0.0.1:20002, {'model_names': ['chatglm2-6b'], 'speed': 1, 'queue_length': 0}
2023-08-29 13:02:33 | INFO | stdout | INFO:     127.0.0.1:53252 - "POST /register_worker HTTP/1.1" 200 OK
2023-08-29 13:02:33 | ERROR | stderr | INFO:     Started server process [11620]
2023-08-29 13:02:33 | ERROR | stderr | INFO:     Waiting for application startup.
2023-08-29 13:02:33 | ERROR | stderr | INFO:     Application startup complete.
INFO:     Application startup complete.
2023-08-29 13:02:33 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20002 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)

=========================此处是断开WIFI 网络====================================
INFO:     127.0.0.1:59786 - "POST /chat/chat HTTP/1.1" 200 OK
2023-08-29 13:02:49,319 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-08-29 13:02:49,407 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-29 13:02:53,408 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-29 13:02:57,398 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-29 13:03:01,420 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-29 13:03:09,406 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-29 13:03:18 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: aec75a96. 
2023-08-29 13:03:18 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-08-29 13:03:18 | INFO | stdout | INFO:     127.0.0.1:59787 - "POST /receive_heart_beat HTTP/1.1" 200 OK
Caught exception: Error communicating with OpenAI
2023-08-29 13:03:19.421 Uncaught app exception
Traceback (most recent call last):
  File "f:\Conda_env\chatchat\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "F:\Huggingface\ChatGLM\LLM\Langchain-Chatchat-master\webui.py", line 70, in <module>
    pages[selected_page]["func"](api)
  File "F:\Huggingface\ChatGLM\LLM\Langchain-Chatchat-master\webui_pages\dialogue\dialogue.py", line 111, in dialogue_page
    chat_box.update_msg(text, streaming=False)  # 更新最终的字符串，去除光标
  File "f:\Conda_env\chatchat\lib\site-packages\streamlit_chatbox\messages.py", line 191, in update_msg

=================以下为打开连接WIFI网络=================================
2023-08-29 13:07:03 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-08-29 13:07:03 | INFO | stdout | INFO:     127.0.0.1:59816 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-08-29 13:07:48 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: aec75a96.
2023-08-29 13:07:48 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-08-29 13:07:48 | INFO | stdout | INFO:     127.0.0.1:59817 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-08-29 13:08:33 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: aec75a96.
2023-08-29 13:08:33 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-08-29 13:08:33 | INFO | stdout | INFO:     127.0.0.1:59818 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-08-29 13:09:18 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: aec75a96.
2023-08-29 13:09:18 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-08-29 13:09:18 | INFO | stdout | INFO:     127.0.0.1:59819 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-08-29 13:10:03 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: aec75a96.
2023-08-29 13:10:03 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-08-29 13:10:03 | INFO | stdout | INFO:     127.0.0.1:59820 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-08-29 13:10:48 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: aec75a96.
2023-08-29 13:10:48 | INFO | controller | Receive heart beat. http://127.0.0.1:20002

**Comment by Andrewlilei** [comment]
仔细阅读 Model_config 里找到了说明，需要配置openai_proxy. 
但是不明白，为什么LLM 模型都在本地了还必须要上网才能用呢？

**Comment by Andrewlilei** [comment]
参考 #1197，问题解决
