### ISSUE TITLE
ConcisValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.e description of the issue

### ISSUE THREAD

**Issue by 1234yyy1234** [chatchat-space/Langchain-Chatchat#1326]
多卡加载baichuan-13B出现以下问题：
(chatglm2) F:\Langchain-Chatchat-master2.2>python server/llm_api.py
2023-08-31 15:10:42,128 - llm_api.py[line:231] - INFO: {'local_model_path': 'F:\\llm_model\\baichuan-13b-v2', 'api_base_url': 'http://localhost:8888/v1', 'api_key': 'EMPTY'}
2023-08-31 15:10:42,129 - llm_api.py[line:234] - INFO: 如需查看 llm_api 日志，请前往 F:\Langchain-Chatchat-master2.2\logs
2023-08-31 15:10:45 | ERROR | stderr | INFO:     Started server process [16648]
2023-08-31 15:10:45 | ERROR | stderr | INFO:     Waiting for application startup.
INFO:     Started server process [15388]
INFO:     Waiting for application startup.
2023-08-31 15:10:45 | ERROR | stderr | INFO:     Application startup complete.
2023-08-31 15:10:45 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20001 (Press CTRL+C to quit)
2023-08-31 15:10:48 | INFO | model_worker | Loading the model ['baichuan-13b-chat'] on worker d06aa21b ...
2023-08-31 15:10:48 | WARNING | accelerate.utils.modeling | The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-08-31 15:10:48 | ERROR | stderr | Process model_worker(11840):
2023-08-31 15:10:48 | ERROR | stderr | Traceback (most recent call last):
2023-08-31 15:10:48 | ERROR | stderr |   File "D:\Anaconda\envs\chatglm2\lib\multiprocessing\process.py", line 315, in _bootstrap
2023-08-31 15:10:48 | ERROR | stderr |     self.run()
2023-08-31 15:10:48 | ERROR | stderr |   File "D:\Anaconda\envs\chatglm2\lib\multiprocessing\process.py", line 108, in run
2023-08-31 15:10:48 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-08-31 15:10:48 | ERROR | stderr |   File "F:\Langchain-Chatchat-master2.2\server\llm_api.py", line 194, in run_model_worker
2023-08-31 15:10:48 | ERROR | stderr |     app = create_model_worker_app(*args, **kwargs)
2023-08-31 15:10:48 | ERROR | stderr |   File "F:\Langchain-Chatchat-master2.2\server\llm_api.py", line 128, in create_model_worker_app
2023-08-31 15:10:48 | ERROR | stderr |     worker = ModelWorker(
2023-08-31 15:10:48 | ERROR | stderr |   File "D:\Anaconda\envs\chatglm2\lib\site-packages\fastchat\serve\model_worker.py", line 207, in __init__
2023-08-31 15:10:48 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-08-31 15:10:48 | ERROR | stderr |   File "D:\Anaconda\envs\chatglm2\lib\site-packages\fastchat\model\model_adapter.py", line 268, in load_model
2023-08-31 15:10:48 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-08-31 15:10:48 | ERROR | stderr |   File "D:\Anaconda\envs\chatglm2\lib\site-packages\fastchat\model\model_adapter.py", line 1118, in load_model
2023-08-31 15:10:48 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2023-08-31 15:10:48 | ERROR | stderr |   File "D:\Anaconda\envs\chatglm2\lib\site-packages\transformers\models\auto\auto_factory.py", line 488, in from_pretrained
2023-08-31 15:10:48 | ERROR | stderr |     return model_class.from_pretrained(
2023-08-31 15:10:48 | ERROR | stderr |   File "D:\Anaconda\envs\chatglm2\lib\site-packages\transformers\modeling_utils.py", line 2903, in from_pretrained
2023-08-31 15:10:48 | ERROR | stderr |     ) = cls._load_pretrained_model(
2023-08-31 15:10:48 | ERROR | stderr |   File "D:\Anaconda\envs\chatglm2\lib\site-packages\transformers\modeling_utils.py", line 3002, in _load_pretrained_model
2023-08-31 15:10:48 | ERROR | stderr |     raise ValueError(
2023-08-31 15:10:48 | ERROR | stderr | ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

**Comment by 1234yyy1234** [comment]
是GPU或是CPU的内存不足

**Comment by ite-jin** [comment]
你好，这个问题是怎么解决的？我也碰到了相同的问题

**Comment by 1234yyy1234** [comment]
> 你好，这个问题是怎么解决的？我也碰到了相同的问题

提高gpu显存试一下
