### ISSUE TITLE
[BUG] safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by caijianying** [chatchat-space/Langchain-Chatchat#1332]
执行 `python3 init_database.py --recreate-vs` 命令报错！

>  下面是错误信息

2023-08-31 22:10:04,077 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.

==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-12.0.1-arm64-arm-64bit.
python版本：3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
项目版本：v0.2.2
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b @ cpu
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': '/Users/jianyingcai/dev/langchain-models/chatglm2-6b'}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

database talbes created
recreating all vector stores
loading vector store in 'samples'.
2023-08-31 22:10:04,827 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /Users/jianyingcai/dev/langchain-models/m3e-base
2023-08-31 22:10:04,994 - instantiator.py[line:21] - INFO: Created a temporary directory at /var/folders/8z/90zfbxg53lv7d0qgv1rq2l2w0000gn/T/tmpu5gc8zj0
2023-08-31 22:10:04,994 - instantiator.py[line:76] - INFO: Writing /var/folders/8z/90zfbxg53lv7d0qgv1rq2l2w0000gn/T/tmpu5gc8zj0/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/Users/jianyingcai/dev/Langchain-Chatchat/init_database.py", line 33, in <module>
    recreate_all_vs()
  File "/Users/jianyingcai/dev/Langchain-Chatchat/server/knowledge_base/migrate.py", line 114, in recreate_all_vs
    folder2db(kb_name, "recreate_vs", vs_type, embed_mode, **kwargs)
  File "/Users/jianyingcai/dev/Langchain-Chatchat/server/knowledge_base/migrate.py", line 36, in folder2db
    kb.create_kb()
  File "/Users/jianyingcai/dev/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 53, in create_kb
    self.do_create_kb()
  File "/Users/jianyingcai/dev/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 104, in do_create_kb
    load_vector_store(self.kb_name)
  File "/Users/jianyingcai/dev/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 53, in load_vector_store
    embeddings = load_embeddings(embed_model, embed_device)
  File "/Users/jianyingcai/dev/Langchain-Chatchat/server/knowledge_base/utils.py", line 55, in load_embeddings
    embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict[model], model_kwargs={'device': device})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 65, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 516, in from_pretrained
    return model_class.from_pretrained(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2805, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/modeling_utils.py", line 458, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by wangzuohao** [comment]
any feedback for this issue?

**Comment by gittjob** [comment]
> 对于这个问题有任何反馈吗？

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/82756842/b11a06ef-e215-41fb-ac62-b1bcc86b4ba4)
大佬，我应该怎么做？

**Comment by Eric-1208** [comment]
同问

**Comment by 332123342** [comment]
同问

**Comment by 332123342** [comment]
m3e-base 换 text2vec-base-chinese 就可以了
