### ISSUE TITLE
[BUG] 创建知识库-向量类型除了faiss都报错

### ISSUE THREAD

**Issue by zicheqingluo** [chatchat-space/Langchain-Chatchat#1336]
**问题描述 / Problem Description**
1.知识库管理-创建支持库，向量库类型只有faiss不报错，其他两种都报错。
2.知识库完全胡说八道，之前langchain-chatglm至少70%的准确度，faiss搭配text2vec基本啥都搜不到，要么就是自己编造

**复现问题的步骤 / Steps to Reproduce**
选择向量类型为pg或milvus，创建之后就报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：a5ee38511d9c2eaf1357d40bb2d15532401ac469 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：pg或milvus
- 操作系统及版本 / Operating system and version:CentOS Linux release 7.8.2003 (Core)
- Python 版本 / Python version:3.10.12

报错：023-09-01 15:11:30,679 - instantiator.py[line:76] - INFO: Writing /tmp/tmpzxrbqtg0/_remote_module_non_scriptable.py
INFO:     127.0.0.1:33484 - "POST /knowledge_base/create_knowledge_base HTTP/1.1" 500 Internal Server Error
2023-09-01 15:11:32,617 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/create_knowledge_base "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 113, in __init__
    from pymilvus import Collection, utility
ModuleNotFoundError: No module named 'pymilvus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/rd/llm/Langchain-Chatchat/server/knowledge_base/kb_api.py", line 29, in create_kb
    kb = KBServiceFactory.get_service(knowledge_base_name, vector_store_type, embed_model)
  File "/data/rd/llm/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 211, in get_service
    return MilvusKBService(kb_name, embed_model=embed_model) # other milvus parameters are set in model_config.kbs_config
  File "/data/rd/llm/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 42, in __init__
    self.do_init()
  File "/data/rd/llm/Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 43, in do_init
    self._load_milvus()
  File "/data/rd/llm/Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 39, in _load_milvus
    self.milvus = Milvus(embedding_function=embeddings,
  File "/data/rd/.pyenv/versions/langchain-chatchat/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 115, in __init__
    raise ValueError(
ValueError: Could not import pymilvus python package. Please install it with `pip install pymilvus`.
2023-09-01 15:11:32,618 - utils.py[line:396] - ERROR: Expecting value: line 1 column 1 (char 0)

**Comment by SwordHG** [comment]
我个人研究下来，0.2版本agent构造更适合openai的，假如你用chatglm的，效果会比之前差，然后匹配的阈值要调大，不然搜不到东西，这可能是0.2版本text_split和0.1版本不同的原因导致的，自己用，需要优化的点还是挺多的，prompt也要改

**Comment by Liu-kakuki** [comment]
兄弟，注意看这两行报错
ModuleNotFoundError: No module named 'pymilvus'
ValueError: Could not import pymilvus python package. Please install it with pip install pymilvus.
使用milvus的时候记得安装pymilvus依赖，另外还需要注意一下安装的milvus和pymilvus冲不冲突，建议两个版本保持一致

**Comment by zicheqingluo** [comment]
> 我个人研究下来，0.2版本agent构造更适合openai的，假如你用chatglm的，效果会比之前差，然后匹配的阈值要调大，不然搜不到东西，这可能是0.2版本text_split和0.1版本不同的原因导致的，自己用，需要优化的点还是挺多的，prompt也要改

怎么调都不行了，啥都查不到，也不报错

**Comment by zicheqingluo** [comment]
> > 我个人研究下来，0.2版本agent构造更适合openai的，假如你用chatglm的，效果会比之前差，然后匹配的阈值要调大，不然搜不到东西，这可能是0.2版本text_split和0.1版本不同的原因导致的，自己用，需要优化的点还是挺多的，prompt也要改
> 
> 怎么调都不行了，啥都查不到，也不报错

又重新换回了langchain-chatglm，虽说不那么精准，但其实还能用。

**Comment by zicheqingluo** [comment]
> 兄弟，注意看这两行报错 ModuleNotFoundError: No module named 'pymilvus' ValueError: Could not import pymilvus python package. Please install it with pip install pymilvus. 使用milvus的时候记得安装pymilvus依赖，另外还需要注意一下安装的milvus和pymilvus冲不冲突，建议两个版本保持一致

更新了代码，不安装也不会报错了。

**Comment by zixiaotan21** [comment]
> 我个人研究下来，0.2版本agent构造更适合openai的，假如你用chatglm的，效果会比之前差，然后匹配的阈值要调大，不然搜不到东西，这可能是0.2版本text_split和0.1版本不同的原因导致的，自己用，需要优化的点还是挺多的，prompt也要改

同样感觉0.2版本搜索效果不太好，想请教一下大佬，

除了：
1. 匹配的阈值要调大
2. prompt优化

还有哪些地方可以优化调整呀，确实搜索知识库的时候，经常搜不到东西~
