### ISSUE TITLE
分别启动LLM,API,WEIUI可以，一键启动就出现以下错误，请指教

### ISSUE THREAD

**Issue by fryeggs** [chatchat-space/Langchain-Chatchat#1346]
(langchat) D:\envs\langchat>python startup.py -a
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19044-SP0.
python版本：3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.2
langchain版本：0.0.266. fastchat版本：0.2.24
当前LLM模型：chatglm2-6b @ cpu
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': '888888',
 'local_model_path': 'D:\\envs\\models\\chatglm2-6b'}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2023-09-02 21:22:55,284 - startup.py[line:382] - INFO: 正在启动服务：
2023-09-02 21:22:55,284 - startup.py[line:383] - INFO: 如需查看 llm_api 日志，请前往 D:\envs\langchat\logs
2023-09-02 21:22:57 | ERROR | stderr | INFO:     Started server process [3120]
2023-09-02 21:22:57 | ERROR | stderr | INFO:     Waiting for application startup.
INFO:     Started server process [8896]
INFO:     Waiting for application startup.
2023-09-02 21:22:57 | ERROR | stderr | INFO:     Application startup complete.
2023-09-02 21:22:57 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20001 (Press CTRL+C to quit)
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
2023-09-02 21:22:57 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 3077497c ...
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:01<00:08,  1.49s/it]
INFO:     Started server process [8352]
INFO:     Waiting for application startup.
Loading checkpoint shards:  29%|████████████████▎                                        | 2/7 [00:03<00:07,  1.55s/it]
Loading checkpoint shards:  43%|████████████████████████▍                                | 3/7 [00:04<00:06,  1.59s/it]
Loading checkpoint shards:  57%|████████████████████████████████▌                        | 4/7 [00:06<00:04,  1.55s/it]
Loading checkpoint shards:  71%|████████████████████████████████████████▋                | 5/7 [00:08<00:03,  1.65s/it]
Loading checkpoint shards:  86%|████████████████████████████████████████████████▊        | 6/7 [00:09<00:01,  1.73s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.50s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.56s/it]
2023-09-02 21:23:09 | ERROR | stderr |
2023-09-02 21:23:09 | INFO | model_worker | Register to controller
2023-09-02 21:23:09 | ERROR | stderr | Process model_worker(3760):
2023-09-02 21:23:09 | ERROR | stderr | Traceback (most recent call last):
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
2023-09-02 21:23:09 | ERROR | stderr |     conn = connection.create_connection(
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
2023-09-02 21:23:09 | ERROR | stderr |     raise err
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
2023-09-02 21:23:09 | ERROR | stderr |     sock.connect(sa)
2023-09-02 21:23:09 | ERROR | stderr | OSError: [WinError 10049] 在其上下文中，该请求的地址无效。
2023-09-02 21:23:09 | ERROR | stderr |
2023-09-02 21:23:09 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-09-02 21:23:09 | ERROR | stderr |
2023-09-02 21:23:09 | ERROR | stderr | Traceback (most recent call last):
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
2023-09-02 21:23:09 | ERROR | stderr |     httplib_response = self._make_request(
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\connectionpool.py", line 415, in _make_request
2023-09-02 21:23:09 | ERROR | stderr |     conn.request(method, url, **httplib_request_kw)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\connection.py", line 244, in request
2023-09-02 21:23:09 | ERROR | stderr |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\http\client.py", line 1283, in request
2023-09-02 21:23:09 | ERROR | stderr |     self._send_request(method, url, body, headers, encode_chunked)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\http\client.py", line 1329, in _send_request
2023-09-02 21:23:09 | ERROR | stderr |     self.endheaders(body, encode_chunked=encode_chunked)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\http\client.py", line 1278, in endheaders
2023-09-02 21:23:09 | ERROR | stderr |     self._send_output(message_body, encode_chunked=encode_chunked)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\http\client.py", line 1038, in _send_output
2023-09-02 21:23:09 | ERROR | stderr |     self.send(msg)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\http\client.py", line 976, in send
2023-09-02 21:23:09 | ERROR | stderr |     self.connect()
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\connection.py", line 205, in connect
2023-09-02 21:23:09 | ERROR | stderr |     conn = self._new_conn()
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
2023-09-02 21:23:09 | ERROR | stderr |     raise NewConnectionError(
2023-09-02 21:23:09 | ERROR | stderr | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001FA53109300>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。
2023-09-02 21:23:09 | ERROR | stderr |
2023-09-02 21:23:09 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-09-02 21:23:09 | ERROR | stderr |
2023-09-02 21:23:09 | ERROR | stderr | Traceback (most recent call last):
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\requests\adapters.py", line 486, in send
2023-09-02 21:23:09 | ERROR | stderr |     resp = conn.urlopen(
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
2023-09-02 21:23:09 | ERROR | stderr |     retries = retries.increment(
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\urllib3\util\retry.py", line 592, in increment
2023-09-02 21:23:09 | ERROR | stderr |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-09-02 21:23:09 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA53109300>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))
2023-09-02 21:23:09 | ERROR | stderr |
2023-09-02 21:23:09 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-09-02 21:23:09 | ERROR | stderr |
2023-09-02 21:23:09 | ERROR | stderr | Traceback (most recent call last):
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\multiprocessing\process.py", line 314, in _bootstrap
2023-09-02 21:23:09 | ERROR | stderr |     self.run()
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\multiprocessing\process.py", line 108, in run
2023-09-02 21:23:09 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\startup.py", line 213, in run_model_worker
2023-09-02 21:23:09 | ERROR | stderr |     app = create_model_worker_app(**kwargs)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\startup.py", line 114, in create_model_worker_app
2023-09-02 21:23:09 | ERROR | stderr |     worker = ModelWorker(
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\fastchat\serve\model_worker.py", line 225, in __init__
2023-09-02 21:23:09 | ERROR | stderr |     self.init_heart_beat()
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\startup.py", line 61, in _new_init_heart_beat
2023-09-02 21:23:09 | ERROR | stderr |     self.register_to_controller()
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\fastchat\serve\model_worker.py", line 108, in register_to_controller
2023-09-02 21:23:09 | ERROR | stderr |     r = requests.post(url, json=data)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\requests\api.py", line 115, in post
2023-09-02 21:23:09 | ERROR | stderr |     return request("post", url, data=data, json=json, **kwargs)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\requests\api.py", line 59, in request
2023-09-02 21:23:09 | ERROR | stderr |     return session.request(method=method, url=url, **kwargs)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\requests\sessions.py", line 589, in request
2023-09-02 21:23:09 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\requests\sessions.py", line 703, in send
2023-09-02 21:23:09 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2023-09-02 21:23:09 | ERROR | stderr |   File "D:\envs\langchat\lib\site-packages\requests\adapters.py", line 519, in send
2023-09-02 21:23:09 | ERROR | stderr |     raise ConnectionError(e, request=request)
2023-09-02 21:23:09 | ERROR | stderr | requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA53109300>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))

**Comment by cayikubiatm** [comment]
你改东西咯 该回去喔

**Comment by swjtu510** [comment]
请问分布式启动怎么调试啊，我启动llm_api.py之后，四行报错不知道是为什么 
D:Lll Langchain-chatchat>pythonerver/11mapi.py
2023-09-15 15:16:31 INFO rootlocal model-path :D:/LLM/chatglm2-6b'api_base url: http://localhost:8888api key :EMPTY
2023-09-15 15:16:31如需查看 11m_api日志，请前往 D:INFOrootLLM Langchain-chatchat logs
2023-09-15 15:16:36INFOworker Loading the model'['chatmodelg1m2-6b'] on worker a5dc2086
2023-09-15 15:16:36ERRORstdeIAFOStarted server procss[5552]TIooo
2023-09-15 15:16:36ERRORINeO:stdeWaiting for applicaion startup.
2023-09-15 15:16:36ERRORstdeINFO:Application startupcomplete.
2023-09-15 15:16:36ERRORstdeINFo:Uvicorn running onttp://0.0.0.0:20001 (Pressto quit)CTRL
![微信图片_20230915154540](https://github.com/chatchat-space/Langchain-Chatchat/assets/128615702/9a9407ea-5563-4a96-9cba-29d7d2718667)
+C的F09927Started server processinFo:Waiting for applicationstartup.Loading checkpoint shards:14%Loading checkpoint shards:29%15，459.04s/it]
1/7[01:28<08:49，882/7 [13:28<38:
