### ISSUE TITLE
没有NVIDIA GPU, 用内存可以跑起来吗？

### ISSUE THREAD

**Issue by tancheng1988** [chatchat-space/Langchain-Chatchat#1348]
是内部OPENSTACK的SERVER, 显卡很弱，想用内存跑，可以吗

这是显卡信息
[root@peering ~]# lspci -vnn | grep VGA -A 12
00:02.0 VGA compatible controller [0300]: Cirrus Logic GD 5446 [1013:00b8] (prog-if 00 [VGA controller])
        Subsystem: Red Hat, Inc. QEMU Virtual Machine [1af4:1100]
        Flags: fast devsel
        Memory at fc000000 (32-bit, prefetchable) [size=32M]
        Memory at febd0000 (32-bit, non-prefetchable) [size=4K]
        Expansion ROM at 000c0000 [disabled] [size=128K]
        Kernel driver in use: cirrus
        Kernel modules: cirrus

提示没有Found no NVIDIA driver on your system.， 关闭了

root@db7d2225af60:/logs# cat llmapisrv.log
2023-09-01 14:45:19,679 - llm_api.py[line:196] - INFO: {'local_model_path': '/chatglm2-6b-32k/', 'api_base_url': 'http://localhost:8888/v1', 'api_key': 'EMPTY'}
2023-09-01 14:45:19,679 - llm_api.py[line:199] - INFO: 如需查看 llm_api 日志，请前往 /langchain-ChatGLM-dev/logs
2023-09-01 14:45:20,469 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpl3mthaeh
2023-09-01 14:45:20,469 - instantiator.py[line:76] - INFO: Writing /tmp/tmpl3mthaeh/_remote_module_non_scriptable.py
2023-09-01 14:45:20 | ERROR | stderr | INFO:     Started server process [195]
2023-09-01 14:45:20 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-01 14:45:21 | ERROR | stderr | INFO:     Application startup complete.
2023-09-01 14:45:21 | INFO | model_worker | Loading the model ['chatglm2-6b-32k'] on worker 5a488b63 ...
2023-09-01 14:45:21 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20001 (Press CTRL+C to quit)
2023-09-01 14:45:21,147 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpkrlvra8i
2023-09-01 14:45:21,148 - instantiator.py[line:76] - INFO: Writing /tmp/tmpkrlvra8i/_remote_module_non_scriptable.py
Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]
INFO:     Started server process [196]
INFO:     Waiting for application startup.
Loading checkpoint shards:  14%|█▍        | 1/7 [00:19<01:57, 19.52s/it]
Loading checkpoint shards:  29%|██▊       | 2/7 [00:40<01:41, 20.24s/it]
Loading checkpoint shards:  43%|████▎     | 3/7 [01:03<01:25, 21.45s/it]
Loading checkpoint shards:  57%|█████▋    | 4/7 [01:26<01:06, 22.00s/it]
Loading checkpoint shards:  71%|███████▏  | 5/7 [01:48<00:44, 22.29s/it]
Loading checkpoint shards:  86%|████████▌ | 6/7 [02:14<00:23, 23.49s/it]
Loading checkpoint shards: 100%|██████████| 7/7 [02:28<00:00, 20.29s/it]
Loading checkpoint shards: 100%|██████████| 7/7 [02:28<00:00, 21.19s/it]
2023-09-01 14:47:49 | ERROR | stderr |
2023-09-01 14:47:50 | ERROR | stderr | Traceback (most recent call last):
2023-09-01 14:47:50 | ERROR | stderr |   File "/langchain-ChatGLM-dev/server/llm_api.py", line 230, in <module>
2023-09-01 14:47:50 | ERROR | stderr |     run_model_worker(queue)
2023-09-01 14:47:50 | ERROR | stderr |   File "/langchain-ChatGLM-dev/server/llm_api.py", line 161, in run_model_worker
2023-09-01 14:47:50 | ERROR | stderr |     app = create_model_worker_app(*args, **kwargs)
2023-09-01 14:47:50 | ERROR | stderr |   File "/langchain-ChatGLM-dev/server/llm_api.py", line 99, in create_model_worker_app
2023-09-01 14:47:50 | ERROR | stderr |     worker = ModelWorker(
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 199, in __init__
2023-09-01 14:47:50 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 239, in load_model
2023-09-01 14:47:50 | ERROR | stderr |     model.to(device)
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 1896, in to
2023-09-01 14:47:50 | ERROR | stderr |     return super().to(*args, **kwargs)
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1145, in to
2023-09-01 14:47:50 | ERROR | stderr |     return self._apply(convert)
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 797, in _apply
2023-09-01 14:47:50 | ERROR | stderr |     module._apply(fn)
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 797, in _apply
2023-09-01 14:47:50 | ERROR | stderr |     module._apply(fn)
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 797, in _apply
2023-09-01 14:47:50 | ERROR | stderr |     module._apply(fn)
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 820, in _apply
2023-09-01 14:47:50 | ERROR | stderr |     param_applied = fn(param)
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1143, in convert
2023-09-01 14:47:50 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2023-09-01 14:47:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
2023-09-01 14:47:50 | ERROR | stderr |     torch._C._cuda_init()
2023-09-01 14:47:50 | ERROR | stderr | RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2023-09-01 14:47:50 | ERROR | stderr | INFO:     Shutting down
2023-09-01 14:47:50 | ERROR | stderr | INFO:     Waiting for application shutdown.
2023-09-01 14:47:50 | ERROR | stderr | INFO:     Application shutdown complete.
2023-09-01 14:47:50 | ERROR | stderr | INFO:     Finished server process [195]

**Comment by heatdrive** [comment]
试一下装cpu的torch
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

**Comment by imClumsyPanda** [comment]
可以，但是fastchat中量化要求机器中有gpu。
