### ISSUE TITLE
对话模式搜索引擎问答：匹配结果条数调大后提示错误

### ISSUE THREAD

**Issue by deepeye** [chatchat-space/Langchain-Chatchat#1353]
**问题描述**
对话模式搜索引擎问答：匹配结果条数调大后提示错误。

**复现问题的步骤**
模型配置如下（FastChat部署大模型）：
```
"Qwen-7B-Chat": {
        "name": "Qwen-7B-Chat",
        "local_model_path": None,
        "api_base_url": "http://{HOST}:8000/v1", 
        "api_key": "EMPTY"
    }
```
先启动api：python server/api.py
再启动webui：python webui.py
对话模式选择 “搜索引擎问答”
搜索引擎选择 “bing”
匹配搜索结果条数
**预期的结果**
正常返回归纳后的结果

**实际结果 / Actual Result**
```
2023-09-04 14:15:41,454 - _client.py[line:1013] - _client - httpx - /root/anaconda3/envs/langchain2/lib/python3.10/site-packages/httpx/_client.py - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/search_engine_chat "HTTP/1.1 200 OK"
2023-09-04 14:15:43.368 Uncaught app exception
Traceback (most recent call last):
  File "/data/chat/Langchain-Chatchat/webui_pages/utils.py", line 228, in _httpx_stream2generator
    yield json.loads(chunk)
  File "/root/anaconda3/envs/langchain2/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/langchain2/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/langchain2/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1945 (char 1944)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/langchain2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/data/chat/Langchain-Chatchat/webui.py", line 70, in <module>
    pages[selected_page]["func"](api)
  File "/data/chat/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 132, in dialogue_page
    for d in api.search_engine_chat(prompt, search_engine, se_top_k):
  File "/data/chat/Langchain-Chatchat/webui_pages/utils.py", line 242, in _httpx_stream2generator
    logger.error(e.with_traceback())
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)
```

**环境信息 / Environment Information**
- Langchain-Chatchat v0.2.2
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-7B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Centos7.9
- Python 版本 / Python version: python3.10.12

**Comment by deepeye** [comment]
补充：本地调试正常（Mac M2），部署服务器出现上述报错

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后修复了部分服务器配置问题，可以重新尝试一下
