### ISSUE TITLE
运行python server/llm_api.py出现问题，查看log内容如下

### ISSUE THREAD

**Issue by wsh228581** [chatchat-space/Langchain-Chatchat#1366]
**controller.log**

2023-09-04 21:45:42 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m3704741[0m]
2023-09-04 21:45:42 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2023-09-04 21:45:42 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2023-09-04 21:45:42 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://172.19.14.162:20001[0m (Press CTRL+C to quit)
2023-09-04 21:54:16 | ERROR | stderr | [32mINFO[0m:     Shutting down
2023-09-04 21:54:16 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2023-09-04 21:54:16 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2023-09-04 21:54:16 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m3704741[0m]
2023-09-04 21:54:17 | ERROR | stderr | Traceback (most recent call last):
2023-09-04 21:54:17 | ERROR | stderr |   File "<string>", line 1, in <module>
2023-09-04 21:54:17 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
2023-09-04 21:54:17 | ERROR | stderr |     exitcode = _main(fd, parent_sentinel)
2023-09-04 21:54:17 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
2023-09-04 21:54:17 | ERROR | stderr |     return self._bootstrap(parent_sentinel)
2023-09-04 21:54:17 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/multiprocessing/process.py", line 332, in _bootstrap
2023-09-04 21:54:17 | ERROR | stderr |     threading._shutdown()
2023-09-04 21:54:17 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/threading.py", line 1567, in _shutdown
2023-09-04 21:54:17 | ERROR | stderr |     lock.acquire()
2023-09-04 21:54:17 | ERROR | stderr | KeyboardInterrupt

**model_worker_5b336484.log**

2023-09-04 21:45:42 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 5b336484 ...
2023-09-04 21:45:42 | INFO | stdout | Loading /home/sun/data/weishihao/LangChain/model requires to execute some code in that repo, you can inspect the content of the repository at https://hf.co//home/sun/data/weishihao/LangChain/model. You can dismiss this prompt by passing `trust_remote_code=True`.
2023-09-04 21:45:42 | INFO | stdout | Do you accept? [y/N]
2023-09-04 21:45:42 | ERROR | stderr | Process model_worker(3704697):
2023-09-04 21:45:42 | ERROR | stderr | Traceback (most recent call last):
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-09-04 21:45:42 | ERROR | stderr |     self.run()
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-09-04 21:45:42 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/data/weishihao/LangChain/server/llm_api.py", line 194, in run_model_worker
2023-09-04 21:45:42 | ERROR | stderr |     app = create_model_worker_app(*args, **kwargs)
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/data/weishihao/LangChain/server/llm_api.py", line 128, in create_model_worker_app
2023-09-04 21:45:42 | ERROR | stderr |     worker = ModelWorker(
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 207, in __init__
2023-09-04 21:45:42 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 268, in load_model
2023-09-04 21:45:42 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 72, in load_model
2023-09-04 21:45:42 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 456, in from_pretrained
2023-09-04 21:45:42 | ERROR | stderr |     config, kwargs = AutoConfig.from_pretrained(
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 947, in from_pretrained
2023-09-04 21:45:42 | ERROR | stderr |     trust_remote_code = resolve_trust_remote_code(
2023-09-04 21:45:42 | ERROR | stderr |   File "/home/sun/anaconda3/envs/chatglm3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 538, in resolve_trust_remote_code
2023-09-04 21:45:42 | ERROR | stderr |     answer = input(
2023-09-04 21:45:42 | ERROR | stderr | EOFError: EOF when reading a line

**Comment by jason95054** [comment]
Have you installed git-lfs?
