### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Vin9196** [chatchat-space/Langchain-Chatchat#1377]
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22000-SP0.
python版本：3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.3
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：gpt-3.5-turbo @ cpu
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '.........',
 'openai_proxy': 'http://127.0.0.1:7890'}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2023-09-05 16:05:52 | INFO | root | 正在启动服务：
2023-09-05 16:05:52 | INFO | root | 如需查看 llm_api 日志，请前往 E:\langchain\Langchain-Chatchat\logs
INFO:     Started server process [23468]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22000-SP0.
python版本：3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.3
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：gpt-3.5-turbo @ cpu
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '...........',
 'openai_proxy': 'http://127.0.0.1:7890'}
当前Embbedings模型： m3e-base @ cpu

服务端运行信息：
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

2023-09-05 16:06:17 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_models "HTTP/1.1 502 Bad Gateway"
2023-09-05 16:06:17.806 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Vin\.conda\envs\langchain\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "E:\langchain\Langchain-Chatchat\webui.py", line 72, in <module>
    pages[selected_page]["func"](api)
  File "E:\langchain\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 75, in dialogue_page
    running_models = api.list_running_models()
  File "E:\langchain\Langchain-Chatchat\webui_pages\utils.py", line 663, in list_running_models
    return r.json().get("data", [])
  File "C:\Users\Vin\.conda\envs\langchain\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\Vin\.conda\envs\langchain\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Vin\.conda\envs\langchain\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Vin\.conda\envs\langchain\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-09-05 16:07:05 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_models "HTTP/1.1 502 Bad Gateway"

用chatgpt3.5报错，代理用的是全局模式设置都是按照步骤来的

**Comment by haof-github** [comment]
同样遇到这个问题，直接用api的形式调用chatgpt是可以调用的

**Comment by w-JiqQian** [comment]
好兄弟怎么解决的？

**Comment by 107350qin** [comment]
我也遇到了咋解决的？

**Comment by judgementc** [comment]
同问wenbui这个问题咋解决：
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback:
File "D:\anaconda\envs\env_name\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "D:\HighTech\Langchain-chat\Langchain-Chatchat\webui.py", line 72, in <module>
    pages[selected_page]["func"](api)
File "D:\HighTech\Langchain-chat\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 75, in dialogue_page
    running_models = api.list_running_models()
File "D:\HighTech\Langchain-chat\Langchain-Chatchat\webui_pages\utils.py", line 663, in list_running_models
    return r.json().get("data", [])
File "D:\anaconda\envs\env_name\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
File "D:\anaconda\envs\env_name\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
File "D:\anaconda\envs\env_name\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "D:\anaconda\envs\env_name\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by zyhui98** [comment]
关掉代理即可解决，这个原因是127.0.0.1，使用python客户端访问127.0.0.1经过一层代理就不行了，可以把代理关掉。
设置127.0.0.1/32 为Direct也能解决。

因为网络问题、代理问题、从业时间1%的时间都折腾在这了，也积累了很多经验，算是今天可以到头了。这几天解决好几个网络问题，一下通透了。

<img width="791" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/5568889/be79d444-17ea-4bd7-98d6-d69e0e4ffdba">

**Comment by ArronAI007** [comment]
我在上传PPT的时候，报错如下：
"HTTP/1.1 413 Request Entity Too Large"
HTTP Request: POST http://127.0.0.1:7861/knowledge_base/upload_docs "HTTP/1.1 500 Internal Server Error"
JSONDecodeError: API未能返回正确的JSON。Expecting value: line 1 column 1 (char 0)

我这边的解决是：把PPT最后的“谢谢”页删除了就可以了，真正的原因还没有找到

**Comment by Vin9196** [comment]
已收到，谢谢！
