### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by wangzaistone** [chatchat-space/Langchain-Chatchat#1387]
**问题描述 / Problem Description**
拉取最新的代码后，在执行完说明文档中的“python startup.py --all-webui” 再去启动webui的服务时报错，使用的命令为Readme中的” 
streamlit run webui.py“ 。 报错信息为：

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

Traceback (most recent call last):
  File "/home/anaconda3/envs/langchain/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/streamlit/web/cli.py", line 233, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/streamlit/web/cli.py", line 269, in _main_run
    bootstrap.run(file, command_line, args, flag_options)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/streamlit/web/bootstrap.py", line 411, in run
    _install_pages_watcher(main_script_path)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/streamlit/web/bootstrap.py", line 386, in _install_pages_watcher
    watch_dir(
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/streamlit/watcher/path_watcher.py", line 153, in watch_dir
    return _watch_path(
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/streamlit/watcher/path_watcher.py", line 128, in _watch_path
    watcher_class(
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/streamlit/watcher/event_based_path_watcher.py", line 92, in __init__
    path_watcher.watch_path(
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/streamlit/watcher/event_based_path_watcher.py", line 170, in watch_path
    folder_handler.watch = self._observer.schedule(
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/watchdog/observers/api.py", line 301, in schedule
    emitter.start()
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 92, in start
    self.on_thread_start()
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 179, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 395, in _add_dir_watch
    self._add_watch(path, mask)
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
    Inotify._raise_error()
  File "/home/anaconda3/envs/langchain/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 428, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
# 环境为linux， python 3.8 ，v100 32G

**Comment by imClumsyPanda** [comment]
```
python startup.py --all-webui
```
命令执行后已经包含执行webui启动过程，无需再执行 streamlit run
