### ISSUE TITLE
版本v0.2.3 加载Baichuan-13B-Chat尽然要150G显存炸了

### ISSUE THREAD

**Issue by SilenceWinter** [chatchat-space/Langchain-Chatchat#1388]
langchain-chatchat 版本v0.2.3， python3.9.17 
bc0a39ab8223a37f80df05cef9dd683e7c6aa655
显卡A6000，45G显存
不用langchain，单独直接运行baichuan官方项目代码，只需显存31G左右
但是，用了langchain-chatchat ，直接干到了150G显存需求
另外chatglm2-6b和qwen-7b-chat都能运行正常。

报错如下：
Process model_worker - baichuan-13b:
Traceback (most recent call last):
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xoxo/pyproj/Langchain-Chatchat/startup.py", line 319, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/xoxo/pyproj/Langchain-Chatchat/startup.py", line 133, in create_model_worker_app
    worker = ModelWorker(
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 207, in __init__
    self.model, self.tokenizer = load_model(
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 274, in load_model
    model.to(device)
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2014, in to
    return super().to(*args, **kwargs)
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 150.00 MiB 

model_config.py中配置
    "baichuan-13b": {
        "local_model_path": "model_hub/Baichuan-13B-Chat",
        "api_base_url": "http://0.0.0.0:8888/v1"
        "api_key": "EMPTY"
    },

**Comment by Gzj369** [comment]
> langchain-chatchat 版本v0.2.3， python3.9.17 [bc0a39a](https://github.com/chatchat-space/Langchain-Chatchat/commit/bc0a39ab8223a37f80df05cef9dd683e7c6aa655) 显卡A6000，45G显存 不用langchain，单独直接运行baichuan官方项目代码，只需显存31G左右 但是，用了langchain-chatchat ，直接干到了150G显存需求 另外chatglm2-6b和qwen-7b-chat都能运行正常。
> 
> 报错如下： Process model_worker - baichuan-13b: Traceback (most recent call last): File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/xoxo/pyproj/Langchain-Chatchat/startup.py", line 319, in run_model_worker app = create_model_worker_app(log_level=log_level, **kwargs) File "/home/xoxo/pyproj/Langchain-Chatchat/startup.py", line 133, in create_model_worker_app worker = ModelWorker( File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 207, in **init** self.model, self.tokenizer = load_model( File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 274, in load_model model.to(device) File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2014, in to return super().to(*args, **kwargs) File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to return self._apply(convert) File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply module._apply(fn) File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply module._apply(fn) File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply module._apply(fn) [Previous line repeated 2 more times] File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply param_applied = fn(param) File "/home/xoxo/miniconda3/envs/langchain2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking) torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 150.00 MiB
> 
> model_config.py中配置 "baichuan-13b": { "local_model_path": "model_hub/Baichuan-13B-Chat", "api_base_url": "http://0.0.0.0:8888/v1" "api_key": "EMPTY" },

我这边使用Baichuan-13B-Chat或者Baichuan2-13B-Chat，没有量化的情况下，通过langchain v0.2.3或v0.2.4加载，需要30多个G的显存即可
