### ISSUE TITLE
[BUG] 更新Langchain-Chatchat v0.2.3 后无论如何设置都只会加载智普api 不会加载本地llm

### ISSUE THREAD

**Issue by cokll** [chatchat-space/Langchain-Chatchat#1401]
``**问题描述 / Problem Description**
`2023-09-07 14:33:00 | ERROR | root | Invalid response object from API: '{"object":"error","message":"Only  allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400)`

**复现问题的步骤 / Steps to Reproduce**
1. clone git
2. python startup.py --all-webui --model-name chatglm2-6b

**预期的结果 / Expected Result**
0.2.3以前版本会直接加载本地llm

**实际结果 / Actual Result**
无法加载任何本地llm

`
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
项目版本：v0.2.3
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b @ cuda
{'api_base_url': 'http://localhost:8502/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'THUDM/chatglm2-6b'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-09-07 14:35:34 | INFO | root | 正在启动服务：
2023-09-07 14:35:34 | INFO | root | 如需查看 llm_api 日志，请前往 H:\Langchain-Chatchat\webui\logs
2023-09-07 14:35:36 | ERROR | stderr | INFO:     Started server process [21512]
2023-09-07 14:35:36 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-07 14:35:36 | ERROR | stderr | INFO:     Application startup complete.
2023-09-07 14:35:36 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20001 (Press CTRL+C to quit)
2023-09-07 14:35:39 | ERROR | stderr | INFO:     Started server process [13964]
2023-09-07 14:35:39 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-07 14:35:39 | ERROR | stderr | INFO:     Application startup complete.
2023-09-07 14:35:39 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:8502 (Press CTRL+C to quit)
INFO:     Started server process [24548]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
项目版本：v0.2.3
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b @ cuda
{'api_base_url': 'http://localhost:8502/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'THUDM/chatglm2-6b'}
当前Embbedings模型： m3e-base @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:8502/v1
     (请确认llm_model_dict中配置的api_base_url与上面地址一致。)
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

2023-09-07 14:35:47 | INFO | stdout | INFO:     127.0.0.1:5218 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 14:35:47 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:5217 - "POST /llm_model/list_models HTTP/1.1" 200 OK
2023-09-07 14:35:47 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_models "HTTP/1.1 200 OK"
2023-09-07 14:36:38 | INFO | stdout | INFO:     127.0.0.1:5238 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 14:36:38 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:5237 - "POST /llm_model/list_models HTTP/1.1" 200 OK
2023-09-07 14:36:38 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_models "HTTP/1.1 200 OK"
2023-09-07 14:36:41 | INFO | stdout | INFO:     127.0.0.1:5249 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 14:36:41 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:5248 - "POST /llm_model/list_models HTTP/1.1" 200 OK
2023-09-07 14:36:41 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_models "HTTP/1.1 200 OK"
received input message:
{'history': [], 'model_name': 'chatglm2-6b', 'query': '测试', 'stream': True}
INFO:     127.0.0.1:5250 - "POST /chat/chat HTTP/1.1" 200 OK
2023-09-07 14:36:41 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-09-07 14:36:43 | INFO | stdout | INFO:     127.0.0.1:5259 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 14:36:43 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-09-07 14:36:43 | INFO | stdout | INFO:     127.0.0.1:5258 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-09-07 14:36:43 | INFO | openai | message='OpenAI API response' path=http://localhost:8502/v1/chat/completions processing_ms=None request_id=None response_code=400
2023-09-07 14:36:43 | WARNING | langchain.llms.base | Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only  allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400).
2023-09-07 14:36:49 | INFO | stdout | INFO:     127.0.0.1:5262 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 14:36:49 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-09-07 14:36:49 | INFO | stdout | INFO:     127.0.0.1:5261 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-09-07 14:36:49 | INFO | openai | message='OpenAI API response' path=http://localhost:8502/v1/chat/completions processing_ms=None request_id=None response_code=400
2023-09-07 14:36:49 | WARNING | langchain.llms.base | Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only  allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400).

`

**Comment by Kun1605** [comment]
我也不行

**Comment by Kun1605** [comment]
=======================================
2023-09-07 15:43:29 | INFO | stdout | INFO:     127.0.0.1:36002 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 15:43:29 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42474 - "POST /llm_model/list_models HTTP/1.1" 200 OK
2023-09-07 15:43:29 | INFO | httpx | HTTP Request: POST http://0.0.0.0:7861/llm_model/list_models "HTTP/1.1 200 OK"
received input message:
{'history': [], 'model_name': 'chatglm2-6b', 'query': '你好 ', 'stream': True}
INFO:     127.0.0.1:42486 - "POST /chat/chat HTTP/1.1" 200 OK
2023-09-07 15:43:29 | INFO | httpx | HTTP Request: POST http://0.0.0.0:7861/chat/chat "HTTP/1.1 200 OK"
2023-09-07 15:43:29 | INFO | stdout | INFO:     127.0.0.1:36008 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 15:43:29 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20001/list_models "HTTP/1.1 200 OK"
2023-09-07 15:43:29 | INFO | stdout | INFO:     127.0.0.1:34866 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-09-07 15:43:29 | INFO | openai | message='OpenAI API response' path=http://0.0.0.0:8888/v1/chat/completions processing_ms=None request_id=None response_code=400
2023-09-07 15:43:29 | WARNING | langchain.llms.base | Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only chatglm-api allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400).
2023-09-07 15:43:33 | INFO | stdout | INFO:     127.0.0.1:36020 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 15:43:33 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20001/list_models "HTTP/1.1 200 OK"
2023-09-07 15:43:33 | INFO | stdout | INFO:     127.0.0.1:34882 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-09-07 15:43:33 | INFO | openai | message='OpenAI API response' path=http://0.0.0.0:8888/v1/chat/completions processing_ms=None request_id=None response_code=400
Caught exception: Invalid response object from API: '{"object":"error","message":"Only chatglm-api allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400)
2023-09-07 15:43:33.631 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/search/ai/langchain-ChatGLM/webui.py", line 72, in <module>
    pages[selected_page]["func"](api)
  File "/search/ai/langchain-ChatGLM/webui_pages/dialogue/dialogue.py", line 145, in dialogue_page
    chat_box.update_msg(text, streaming=False)  # 更新最终的字符串，去除光标
  File "/usr/local/lib/python3.10/dist-packages/streamlit_chatbox/messages.py", line 191, in update_msg
    old_element = self.history[history_index]["elements"][element_index]
  File "/usr/local/lib/python3.10/dist-packages/streamlit_chatbox/messages.py", line 64, in history
    return st.session_state.get(self._session_key).get(self._chat_name)
AttributeError: 'NoneType' object has no attribute 'get'
2023-09-07 15:43:33 | INFO | stdout | INFO:     127.0.0.1:36034 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 15:43:33 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20001/list_models "HTTP/1.1 200 OK"
2023-09-07 15:43:33 | INFO | stdout | INFO:     127.0.0.1:34884 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-09-07 15:43:33 | INFO | openai | message='OpenAI API response' path=http://0.0.0.0:8888/v1/chat/completions processing_ms=None request_id=None response_code=400
2023-09-07 15:43:33 | WARNING | langchain.llms.base | Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only chatglm-api allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400).
2023-09-07 15:43:37 | INFO | stdout | INFO:     127.0.0.1:36050 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 15:43:37 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20001/list_models "HTTP/1.1 200 OK"
2023-09-07 15:43:37 | INFO | stdout | INFO:     127.0.0.1:34896 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-09-07 15:43:37 | INFO | openai | message='OpenAI API response' path=http://0.0.0.0:8888/v1/chat/completions processing_ms=None request_id=None response_code=400
2023-09-07 15:43:37 | WARNING | langchain.llms.base | Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only chatglm-api allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400).
2023-09-07 15:43:42 | INFO | stdout | INFO:     127.0.0.1:57924 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 15:43:42 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20001/list_models "HTTP/1.1 200 OK"
2023-09-07 15:43:42 | INFO | stdout | INFO:     127.0.0.1:41318 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-09-07 15:43:42 | INFO | openai | message='OpenAI API response' path=http://0.0.0.0:8888/v1/chat/completions processing_ms=None request_id=None response_code=400
2023-09-07 15:43:42 | WARNING | langchain.llms.base | Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only chatglm-api allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400).
2023-09-07 15:43:50 | INFO | stdout | INFO:     127.0.0.1:34402 - "POST /list_models HTTP/1.1" 200 OK
2023-09-07 15:43:50 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20001/list_models "HTTP/1.1 200 OK"
2023-09-07 15:43:50 | INFO | stdout | INFO:     127.0.0.1:35128 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-09-07 15:43:50 | INFO | openai | message='OpenAI API response' path=http://0.0.0.0:8888/v1/chat/completions processing_ms=None request_id=None response_code=400
2023-09-07 15:43:50 | WARNING | langchain.llms.base | Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only chatglm-api allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400).

**Comment by AaronMKk** [comment]
试一下这个：https://github.com/chatchat-space/Langchain-Chatchat/issues/1389

**Comment by Kun1605** [comment]
> 试一下这个：#1389

不行

**Comment by qqinc** [comment]
部署一样的错误，大家解决了没？

**Comment by javablogss** [comment]
有人解决了吗？我的部署没有错误，但是问答的时候一直是没有消息
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/33540004/c7483137-f4ff-460e-9ab7-78d95fdc166a)

**Comment by qinb** [comment]
+1

**Comment by sfeng95** [comment]
我的也是

**Comment by zhuhaifengaaa** [comment]
+1

**Comment by cokll** [comment]
`2023-09-13 20:45:49 | WARNING | langchain.llms.base | Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only chatglm-api allowed now, your model chatglm-6b","code":40301}' (HTTP response code was 400).`

仍然无法加载

**Comment by nicole828** [comment]
我也看不懂这段话，也没人解决

**Comment by Gzj369** [comment]
我也遇到了，请问有人解决了吗？

**Comment by iu521** [comment]
+1

**Comment by Gzj369** [comment]
> +1

升级到v0.2.4版本，该问题被解决了
