### ISSUE TITLE
[BUG] 启动llm本地模型时报错：JSONDecodeError

### ISSUE THREAD

**Issue by jeremy-lyoko** [chatchat-space/Langchain-Chatchat#1420]
情况：
运行教程案例时，启动llm本地模型服务报错
webui显示：JSONDecodeError

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Applications/Software/Langchain/Langchain-Chatchat-0.2.3/server/llm_api.py", line 187, in run_model_worker
    app = create_model_worker_app(*args, **kwargs)
  File "/Applications/Software/Langchain/Langchain-Chatchat-0.2.3/server/llm_api.py", line 121, in create_model_worker_app
    worker = ModelWorker(
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/fastchat/serve/model_worker.py", line 207, in __init__
    self.model, self.tokenizer = load_model(
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/fastchat/model/model_adapter.py", line 274, in load_model
    model.to(device)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/transformers/modeling_utils.py", line 2053, in to
    return super().to(*args, **kwargs)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: MPS backend out of memory (MPS allocated: 6.61 GB, other allocations: 179.85 MB, max allowed: 6.80 GB). Tried to allocate 32.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

环境信息：
主机：macpro intel 16g内存
langchain-chatchat：0.2.3
模型：使用默认模型 [THUDM/chatglm2-6b]和 [moka-ai/m3e-base]

**Comment by Dreamsting** [comment]
解决办法有了吗

**Comment by judgementc** [comment]
兄弟解决没，我用gpt3.5也是这个错误

**Comment by libo119111** [comment]
还是不能解决吗

**Comment by Dreamsting** [comment]
startup.py 文件中 添加     os.environ['PYTORCH_MPS_HIGH_WATERMARK_RATIO'] = '0.0' 之后可以跑起来 但是会把内存跑满

**Comment by zRzRzRzRzRzRzR** [comment]
MPS backend out of memory (MPS allocated: 6.61 GB, other allocations: 179.85 MB, max allowed: 6.80 GB). Tried to allocate 32.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
 从这里就能看出来应该是mps出现了问题，按照报错的提示操作或换更小的模型能解决这问题
 或者寻求pytorch的帮助解决问题。
