### ISSUE TITLE
ERROR:    Application startup failed. Exiting.

### ISSUE THREAD

**Issue by hongsihe** [chatchat-space/Langchain-Chatchat#1426]
(base) PS E:\Langchain-Chatchat> & e:/Langchain-Chatchat/langchain/Scripts/Activate.ps1
(langchain) (base) PS E:\Langchain-Chatchat> python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.3
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b @ cuda
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'E:/Langchain-Chatchat/models/chatglm2-6b'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-09-10 22:06:44 | INFO | root | 正在启动服务：
2023-09-10 22:06:44 | INFO | root | 如需查看 llm_api 日志，请前往 E:\Langchain-Chatchat\logs
2023-09-10 22:06:46 | ERROR | stderr | INFO:     Started server process [12444]
2023-09-10 22:06:46 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-10 22:06:46 | ERROR | stderr | ERROR:    Traceback (most recent call last):
2023-09-10 22:06:46 | ERROR | stderr |   File "E:\Langchain-Chatchat\langchain\lib\site-packages\starlette\routing.py", line 677, in lifespan
2023-09-10 22:06:46 | ERROR | stderr |     async with self.lifespan_context(app) as maybe_state:
2023-09-10 22:06:46 | ERROR | stderr |   File "E:\Langchain-Chatchat\langchain\lib\site-packages\starlette\routing.py", line 566, in __aenter__
2023-09-10 22:06:46 | ERROR | stderr |     await self._router.startup()
2023-09-10 22:06:46 | ERROR | stderr |   File "E:\Langchain-Chatchat\langchain\lib\site-packages\starlette\routing.py", line 654, in startup
2023-09-10 22:06:46 | ERROR | stderr |     await handler()
2023-09-10 22:06:46 | ERROR | stderr |   File "E:\Langchain-Chatchat\startup.py", line 198, in on_startup
2023-09-10 22:06:46 | ERROR | stderr |     set_httpx_timeout()
2023-09-10 22:06:46 | ERROR | stderr |   File "E:\Langchain-Chatchat\server\utils.py", line 277, in set_httpx_timeout
2023-09-10 22:06:46 | ERROR | stderr |     from configs.server_config import HTTPX_DEFAULT_TIMEOUT
2023-09-10 22:06:46 | ERROR | stderr | ImportError: cannot import name 'HTTPX_DEFAULT_TIMEOUT' from 'configs.server_config' (E:\Langchain-Chatchat\configs\server_config.py)
2023-09-10 22:06:46 | ERROR | stderr | 
2023-09-10 22:06:46 | ERROR | stderr | ERROR:    Application startup failed. Exiting.

**Comment by hongsihe** [comment]
重新配置就解决了
