### ISSUE TITLE
init_database.py   执行报错

### ISSUE THREAD

**Issue by Andrewwils** [chatchat-space/Langchain-Chatchat#1428]
**问题描述 / Problem Description**
init_database.py   执行报错

Traceback (most recent call last):
  File "/root/Langchain-Chatchat/init_database.py", line 1, in <module>
    from server.knowledge_base.migrate import create_tables, folder2db, recreate_all_vs, list_kbs_from_folder
  File "/root/Langchain-Chatchat/server/knowledge_base/migrate.py", line 2, in <module>
    from server.knowledge_base.utils import get_file_path, list_kbs_from_folder, list_docs_from_folder, KnowledgeFile
  File "/root/Langchain-Chatchat/server/knowledge_base/utils.py", line 2, in <module>
    from langchain.embeddings.huggingface import HuggingFaceEmbeddings
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/__init__.py", line 36, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/agents/__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/agents/agent_iterator.py", line 21, in <module>
    from langchain.callbacks.manager import (
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/callbacks/__init__.py", line 10, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/callbacks/aim_callback.py", line 5, in <module>
    from langchain.schema import AgentAction, AgentFinish, LLMResult
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/schema/__init__.py", line 5, in <module>
    from langchain.schema.memory import BaseChatMessageHistory, BaseMemory
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/schema/memory.py", line 7, in <module>
    from langchain.schema.messages import AIMessage, BaseMessage, HumanMessage
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/langchain/schema/messages.py", line 149, in <module>
    class HumanMessageChunk(HumanMessage, BaseMessageChunk):
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.11/site-packages/pydantic/main.py", line 367, in __new__
    cls = super().__new__(mcs, name, bases, new_namespace, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
TypeError: multiple bases have instance lay-out conflict

**Comment by zRzRzRzRzRzRzR** [comment]
是否为支持的格式，最新的版本还有遇到这个问题吗
