### ISSUE TITLE
[BUG] Torch 无法激活CUDA

### ISSUE THREAD

**Issue by TzehoMar** [chatchat-space/Langchain-Chatchat#1453]
所有的库全部安装完成了，cuda是12.2，python是3.8.6，显卡是RTX 2080 22G显存版，配置应该够，跑6b 32k用CPU都能跑起来，配置文件里面改成cuda每次启动一半就说torch编译时未激活cuda，求大神帮帮忙啊！！

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22000-SP0.
python版本：3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
项目版本：v0.2.3
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b-32k @ cuda
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'G:/AI/AI_model/chatglm2-6b-32k'}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2023-09-13 01:53:05 | INFO | root | 正在启动服务：
2023-09-13 01:53:05 | INFO | root | 如需查看 llm_api 日志，请前往 G:\AI\Langchain-Chatchat-master\logs
2023-09-13 01:53:07 | ERROR | stderr | INFO:     Started server process [8552]
2023-09-13 01:53:07 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-13 01:53:07 | ERROR | stderr | INFO:     Application startup complete.
2023-09-13 01:53:07 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20001 (Press CTRL+C to quit)
2023-09-13 01:53:09 | INFO | model_worker | Loading the model ['chatglm2-6b-32k'] on worker 7d744463 ...
2023-09-13 01:53:09 | INFO | model_worker | Register to controller
2023-09-13 01:53:09 | INFO | controller | Register a new worker: http://127.0.0.1:20003
2023-09-13 01:53:09 | INFO | controller | Register done: http://127.0.0.1:20003, {'model_names': ['chatglm-api'], 'speed': 1, 'queue_length': 0}
2023-09-13 01:53:09 | INFO | stdout | INFO:     127.0.0.1:57612 - "POST /register_worker HTTP/1.1" 200 OK
INFO:     Started server process [19964]
INFO:     Waiting for application startup.
2023-09-13 01:53:09 | ERROR | stderr | INFO:     Started server process [13100]
2023-09-13 01:53:09 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-13 01:53:09 | ERROR | stderr | INFO:     Application startup complete.
2023-09-13 01:53:09 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
Loading checkpoint shards:  29%|█████████████████████████████████████████████████▏                                                                                                                          | 2/7 [00:03<00:07,  1.55s/it]INFO:     Started server process [6932]
INFO:     Waiting for application startup.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.55s/it]
Process model_worker - chatglm2-6b-32k:
Traceback (most recent call last):
  File "C:\Program Files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "G:\AI\Langchain-Chatchat-master\startup.py", line 319, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "G:\AI\Langchain-Chatchat-master\startup.py", line 133, in create_model_worker_app
    worker = ModelWorker(
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\fastchat\serve\model_worker.py", line 207, in __init__
    self.model, self.tokenizer = load_model(
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\fastchat\model\model_adapter.py", line 274, in load_model
    model.to(device)
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\transformers\modeling_utils.py", line 2053, in to
    return super().to(*args, **kwargs)
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "G:\AI\Langchain-Chatchat-master\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by imClumsyPanda** [comment]
请参考pytorch官网，检查cuda版本要求及对应pytorch版本。

**Comment by TzehoMar** [comment]
感谢，换了CUDA 11.8就好了，666！

**Comment by kenshintiti** [comment]
> 感谢，换了CUDA 11.8就好了，666！

CUDA 11.8有镜像地址吗。。官网下载的太慢了

**Comment by zoneRohn** [comment]
> 感谢，换了CUDA 11.8就好了，666！

我在运行向量库初始化的那一步也报这个错了，到Pytorch官网查了对应CUDA版本之后就重下了个CUDA12.1的，结果还是一样
```
D:\Langchain-Chatchat_v0.2.7> python init_database.py --recreate-vs
recreating all vector stores
2023-11-27 18:18:47,613 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/m3e-base' from disk.
2023-11-27 18:18:50,897 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: D:\Langchain-Chatchat_v0.2.7\LLM&EMB_MODELS\m3e-base
2023-11-27 18:18:52,252 - embeddings_api.py[line:39] - ERROR: Torch not compiled with CUDA enabled
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Langchain-Chatchat_v0.2.7\init_database.py", line 108, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\migrate.py", line 118, in folder2db
    kb.create_kb()
  File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\base.py", line 80, in create_kb
    self.do_create_kb()
  File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\faiss_kb_service.py", line 47, in do_create_kb
    self.load_vector_store()
  File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_cache\faiss_cache.py", line 90, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_cache\faiss_cache.py", line 48, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
  File "D:\Poon\Python\lib\site-packages\langchain\schema\vectorstore.py", line 510, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "D:\Poon\Python\lib\site-packages\langchain\vectorstores\faiss.py", line 911, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\base.py", line 380, in embed_documents
    return normalize(embeddings).tolist()
  File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "D:\Poon\Python\lib\site-packages\numpy\linalg\linalg.py", line 2541, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
```

**Comment by CapitaineNemo** [comment]
> > 感谢，换了CUDA 11.8就好了，666！
> 
> 我在运行向量库初始化的那一步也报这个错了，到Pytorch官网查了对应CUDA版本之后就重下了个CUDA12.1的，结果还是一样
> 
> ```
> D:\Langchain-Chatchat_v0.2.7> python init_database.py --recreate-vs
> recreating all vector stores
> 2023-11-27 18:18:47,613 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/m3e-base' from disk.
> 2023-11-27 18:18:50,897 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: D:\Langchain-Chatchat_v0.2.7\LLM&EMB_MODELS\m3e-base
> 2023-11-27 18:18:52,252 - embeddings_api.py[line:39] - ERROR: Torch not compiled with CUDA enabled
> AttributeError: 'NoneType' object has no attribute 'conjugate'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:\Langchain-Chatchat_v0.2.7\init_database.py", line 108, in <module>
>     folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
>   File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\migrate.py", line 118, in folder2db
>     kb.create_kb()
>   File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\base.py", line 80, in create_kb
>     self.do_create_kb()
>   File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\faiss_kb_service.py", line 47, in do_create_kb
>     self.load_vector_store()
>   File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\faiss_kb_service.py", line 28, in load_vector_store
>     return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
>   File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_cache\faiss_cache.py", line 90, in load_vector_store
>     vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
>   File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_cache\faiss_cache.py", line 48, in new_vector_store
>     vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
>   File "D:\Poon\Python\lib\site-packages\langchain\schema\vectorstore.py", line 510, in from_documents
>     return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
>   File "D:\Poon\Python\lib\site-packages\langchain\vectorstores\faiss.py", line 911, in from_texts
>     embeddings = embedding.embed_documents(texts)
>   File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\base.py", line 380, in embed_documents
>     return normalize(embeddings).tolist()
>   File "D:\Langchain-Chatchat_v0.2.7\server\knowledge_base\kb_service\base.py", line 37, in normalize
>     norm = np.linalg.norm(embeddings, axis=1)
>   File "<__array_function__ internals>", line 200, in norm
>   File "D:\Poon\Python\lib\site-packages\numpy\linalg\linalg.py", line 2541, in norm
>     s = (x.conj() * x).real
> TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
> ```

你得根据你的cuda安装对应的torch, 新建一个环境。我把我的cuda升到了12.3 重新装了才行。

**Comment by TongDog** [comment]
m1部署的时候也出现了这个问题，装支持mps的版本就可以了吗
