### ISSUE TITLE
docker版本上传pdf添加至向量库报错

### ISSUE THREAD

**Issue by xbdba** [chatchat-space/Langchain-Chatchat#1471]
**问题描述 / Problem Description**
上传pdf成功，添加至向量库报错

2023-09-13 17:39:03 | ERROR | root | timed out
2023-09-13 17:39:03.072 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/langchain-chatchat/webui.py", line 71, in <module>
    pages[selected_page]["func"](api)
  File "/langchain-chatchat/webui_pages/dialogue/dialogue.py", line 76, in dialogue_page
    running_models = api.list_running_models()
  File "/langchain-chatchat/webui_pages/utils.py", line 663, in list_running_models
    return r.json().get("data", [])
AttributeError: 'NoneType' object has no attribute 'json'
2023-09-13 17:39:19 | ERROR | root | timed out
2023-09-13 17:39:19 | ERROR | root | 'NoneType' object has no attribute 'json'
2023-09-13 17:39:22 | ERROR | root | timed out
2023-09-13 17:39:22 | ERROR | root | 'NoneType' object has no attribute 'json'
2023-09-13 17:39:23 | ERROR | root | timed out
2023-09-13 17:39:23 | ERROR | root | 'NoneType' object has no attribute 'json'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.3
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec-bge-large-chinese
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Redhat Linux 7

**Comment by bg1avd** [comment]
俺也一样

**Comment by qingyuan9906** [comment]
me too

**Comment by zRzRzRzRzRzRzR** [comment]
等待0.2.5版本docker，这两天会推出
