### ISSUE TITLE
ValueError: Collection not found

### ISSUE THREAD

**Issue by jiashaokun** [chatchat-space/Langchain-Chatchat#1476]
**问题描述 / Problem Description**
执行命令 python init_database.py --recreate-vs 报错

**附加信息 / Additional Information**
正在将 samples/test.txt 添加到向量库，共包含83条文档
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.88it/s]
Traceback (most recent call last):
  File "/alidata/llm/Langchain-Chatchat/init_database.py", line 35, in <module>
    recreate_all_vs()
  File "/alidata/llm/Langchain-Chatchat/server/knowledge_base/migrate.py", line 122, in recreate_all_vs
    folder2db(kb_name, "recreate_vs", vs_type, embed_mode, **kwargs)
  File "/alidata/llm/Langchain-Chatchat/server/knowledge_base/migrate.py", line 67, in folder2db
    kb.add_doc(kb_file=kb_file, docs=docs, not_refresh_vs_cache=True)
  File "/alidata/llm/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 93, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
  File "/alidata/llm/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 65, in do_add_doc
    ids = self.pg_vector.add_documents(docs)
  File "/alidata/env/chat/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 104, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/alidata/env/chat/lib/python3.10/site-packages/langchain/vectorstores/pgvector.py", line 269, in add_texts
    return self.add_embeddings(
  File "/alidata/env/chat/lib/python3.10/site-packages/langchain/vectorstores/pgvector.py", line 237, in add_embeddings
    raise ValueError("Collection not found")
ValueError: Collection not found

**Comment by imbirdy** [comment]
i have the same issue. 
![055dd2f17685bc846cf6801a9964ba6](https://github.com/chatchat-space/Langchain-Chatchat/assets/144639163/20d91bb2-9dad-49af-8984-7d69e1a0d9ca)

**Comment by woshikid** [comment]
我也遇到了同样的问题

**Comment by woshikid** [comment]
pull了最新的代码就解决了
