### ISSUE TITLE
baichuan2-13B-chat量化版无法使用

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [chatchat-space/Langchain-Chatchat#1481]
HF上的baichuan-inc/Baichuan2-13B-Chat本地量化为int8后可以直接使用无误
```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation.utils import GenerationConfig
from IPython import display

model_path='/home/Code/llm/models/baichuan-13B-chat-8bit'

# 使用离线量化8bit版
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", trust_remote_code=True)
model.generation_config = GenerationConfig.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False, trust_remote_code=True)
messages = []
messages.append({"role": "user", "content": "我有一个吹风机，额定电压是110V，请问是否能够直接在中国使用它？"})
final_result=""
for response in model.chat(tokenizer, messages, stream = True):
    print(response)
    final_result=response
    display.clear_output(wait=True)
print(final_result)
messages.append({"role": "machine", "content": final_result})
```

集成时启动即报错，配置方式应该没啥问题，ChatGLM2-6B正常运行

```
(llm) chenchen@ps:~/Code/Langchain-Chatchat$ python startup.py -a
2023-09-14 17:52:27,761 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpnq1osujk
2023-09-14 17:52:27,761 - instantiator.py[line:76] - INFO: Writing /tmp/tmpnq1osujk/_remote_module_non_scriptable.py
2023-09-14 17:52:29,057 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp5zs2hpm8
2023-09-14 17:52:29,058 - instantiator.py[line:76] - INFO: Writing /tmp/tmp5zs2hpm8/_remote_module_non_scriptable.py


==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.2.0-31-generic-x86_64-with-glibc2.35.
python版本：3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
项目版本：v0.2.3
langchain版本：0.0.266. fastchat版本：0.2.24


当前LLM模型：baichuan2-13B-chat-8bit @ cuda
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': '/home/chenchen/Code/llm/models/baichuan-13B-chat-8bit'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================


2023-09-14 17:52:30 | INFO | root | 正在启动服务：
2023-09-14 17:52:30 | INFO | root | 如需查看 llm_api 日志，请前往 /home/chenchen/Code/Langchain-Chatchat/logs
2023-09-14 17:52:30,849 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmppv5k6x2p
2023-09-14 17:52:30,850 - instantiator.py[line:76] - INFO: Writing /tmp/tmppv5k6x2p/_remote_module_non_scriptable.py
2023-09-14 17:52:31 | ERROR | stderr | INFO:     Started server process [678059]
2023-09-14 17:52:31 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-14 17:52:31 | ERROR | stderr | INFO:     Application startup complete.
2023-09-14 17:52:31 | ERROR | stderr | INFO:     Uvicorn running on http://192.168.24.252:20001 (Press CTRL+C to quit)
2023-09-14 17:52:32,222 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpcr7ahvmh
2023-09-14 17:52:32,222 - instantiator.py[line:76] - INFO: Writing /tmp/tmpcr7ahvmh/_remote_module_non_scriptable.py
2023-09-14 17:52:32,223 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpud_vdpcw
2023-09-14 17:52:32,223 - instantiator.py[line:76] - INFO: Writing /tmp/tmpud_vdpcw/_remote_module_non_scriptable.py
2023-09-14 17:52:32,230 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpdp_ksxtt
2023-09-14 17:52:32,230 - instantiator.py[line:76] - INFO: Writing /tmp/tmpdp_ksxtt/_remote_module_non_scriptable.py
2023-09-14 17:52:32,231 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpz8rc285n
2023-09-14 17:52:32,231 - instantiator.py[line:76] - INFO: Writing /tmp/tmpz8rc285n/_remote_module_non_scriptable.py
2023-09-14 17:52:32,236 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpm1p8n34u
2023-09-14 17:52:32,236 - instantiator.py[line:76] - INFO: Writing /tmp/tmpm1p8n34u/_remote_module_non_scriptable.py
2023-09-14 17:52:32 | INFO | model_worker | Loading the model ['baichuan2-13B-chat-8bit'] on worker f31c6ee4 ...
2023-09-14 17:52:32 | INFO | model_worker | Register to controller
2023-09-14 17:52:32 | INFO | controller | Register a new worker: http://192.168.24.252:20003
2023-09-14 17:52:32 | INFO | controller | Register done: http://192.168.24.252:20003, {'model_names': ['chatglm-api'], 'speed': 1, 'queue_length': 0}
2023-09-14 17:52:32 | INFO | stdout | INFO:     192.168.24.252:50706 - "POST /register_worker HTTP/1.1" 200 OK
INFO:     Started server process [678168]
INFO:     Waiting for application startup.
2023-09-14 17:52:32 | ERROR | stderr | INFO:     Started server process [678166]
2023-09-14 17:52:32 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-14 17:52:32 | ERROR | stderr | INFO:     Application startup complete.
2023-09-14 17:52:32 | ERROR | stderr | INFO:     Uvicorn running on http://192.168.24.252:7889 (Press CTRL+C to quit)
Loading checkpoint shards:   0%|                                                                | 0/2 [00:00<?, ?it/s]INFO:     Started server process [678169]
INFO:     Waiting for application startup.
Loading checkpoint shards: 100%|????????????????????????????????????????????????????????| 2/2 [00:10<00:00,  5.43s/it]
2023-09-14 17:52:43 | WARNING | accelerate.big_modeling | You shouldn't move a model when it is dispatched on multiple devices.
Process model_worker - baichuan2-13B-chat-8bit:
Traceback (most recent call last):
  File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chenchen/Code/Langchain-Chatchat/startup.py", line 319, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenchen/Code/Langchain-Chatchat/startup.py", line 133, in create_model_worker_app
    worker = ModelWorker(
             ^^^^^^^^^^^^
  File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 207, in __init__
    self.model, self.tokenizer = load_model(
                                 ^^^^^^^^^^^
  File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 274, in load_model
    model.to(device)
  File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/site-packages/accelerate/big_modeling.py", line 411, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2048, in to
    raise ValueError(
ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
2023-09-14 17:53:17 | INFO | model_worker | Send heart beat. Models: ['chatglm-api']. Semaphore: None. call_ct: 0. worker_id: 1e991c17. 
2023-09-14 17:53:17 | INFO | controller | Receive heart beat. http://192.168.24.252:20003
2023-09-14 17:53:17 | INFO | stdout | INFO:     192.168.24.252:50712 - "POST /receive_heart_beat HTTP/1.1" 200 OK

```

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58684828/43613a33-2cdc-4907-807f-ec0d018f46f0)
目前测试来看baichuan系列必挂，每一个模型都会爆出不同的错误，chatglm系列没问题，图中的模型使用transformers的方式都可以正常使用

追源码看了一下没看出所以然，在startup.py中强制替换ModelWorker的模型后提示`raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BaichuanForCausalLM' object has no attribute 'stream_generate'`请教一下大佬们为什么会这样

**Comment by thinkinds** [comment]
我是使用的百川提供的4bits版本，也是遇到这个问题：
`ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype``
尝试过升级accelerate, transformers，无法解决

**Comment by ilovesouthpark** [comment]
我能正常量化，但是问了问题的回答就是不断重复乱说

**Comment by WilliamChen-luckbob** [comment]
> 我能正常量化，但是问了问题的回答就是不断重复乱说

重复乱说可能是用的文本生成模式并且最大输出token开高了吧，chat版的好像没有这种问题

**Comment by WilliamChen-luckbob** [comment]
> 我是使用的百川提供的4bits版本，也是遇到这个问题： `ValueError: `.to`is not supported for`4-bit`or`8-bit`bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct`dtype`` 尝试过升级accelerate, transformers，无法解决

目前我试过直接手敲尝试集成到langchain也不行，似乎有什么方法不支持用pipeline集成

**Comment by iaoxuesheng** [comment]
> HF上的baichuan-inc/Baichuan2-13B-Chat本地量化为int8后可以直接使用无误
> 
> ```
> import torch
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from transformers.generation.utils import GenerationConfig
> from IPython import display
> 
> model_path='/home/chenchen/Code/llm/models/baichuan-13B-chat-8bit'
> 
> # 使用离线量化8bit版
> model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", trust_remote_code=True)
> model.generation_config = GenerationConfig.from_pretrained(model_path)
> tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False, trust_remote_code=True)
> messages = []
> messages.append({"role": "user", "content": "我有一个吹风机，额定电压是110V，请问是否能够直接在中国使用它？"})
> final_result=""
> for response in model.chat(tokenizer, messages, stream = True):
>     print(response)
>     final_result=response
>     display.clear_output(wait=True)
> print(final_result)
> messages.append({"role": "machine", "content": final_result})
> ```
> 
> ![image](https://user-images.githubusercontent.com/58684828/267938661-08b8889e-fb8d-4a03-9050-25d64f071489.png)
> 
> 集成时启动即报错，配置方式应该没啥问题，ChatGLM2-6B正常运行
> 
> ```
> (llm) chenchen@ps:~/Code/Langchain-Chatchat$ python startup.py -a
> 2023-09-14 17:52:27,761 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpnq1osujk
> 2023-09-14 17:52:27,761 - instantiator.py[line:76] - INFO: Writing /tmp/tmpnq1osujk/_remote_module_non_scriptable.py
> 2023-09-14 17:52:29,057 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp5zs2hpm8
> 2023-09-14 17:52:29,058 - instantiator.py[line:76] - INFO: Writing /tmp/tmp5zs2hpm8/_remote_module_non_scriptable.py
> 
> 
> ==============================Langchain-Chatchat Configuration==============================
> 操作系统：Linux-6.2.0-31-generic-x86_64-with-glibc2.35.
> python版本：3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
> 项目版本：v0.2.3
> langchain版本：0.0.266. fastchat版本：0.2.24
> 
> 
> 当前LLM模型：baichuan2-13B-chat-8bit @ cuda
> {'api_base_url': 'http://localhost:8888/v1',
>  'api_key': 'EMPTY',
>  'local_model_path': '/home/chenchen/Code/llm/models/baichuan-13B-chat-8bit'}
> 当前Embbedings模型： m3e-base @ cuda
> ==============================Langchain-Chatchat Configuration==============================
> 
> 
> 2023-09-14 17:52:30 | INFO | root | 正在启动服务：
> 2023-09-14 17:52:30 | INFO | root | 如需查看 llm_api 日志，请前往 /home/chenchen/Code/Langchain-Chatchat/logs
> 2023-09-14 17:52:30,849 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmppv5k6x2p
> 2023-09-14 17:52:30,850 - instantiator.py[line:76] - INFO: Writing /tmp/tmppv5k6x2p/_remote_module_non_scriptable.py
> 2023-09-14 17:52:31 | ERROR | stderr | INFO:     Started server process [678059]
> 2023-09-14 17:52:31 | ERROR | stderr | INFO:     Waiting for application startup.
> 2023-09-14 17:52:31 | ERROR | stderr | INFO:     Application startup complete.
> 2023-09-14 17:52:31 | ERROR | stderr | INFO:     Uvicorn running on http://192.168.24.252:20001 (Press CTRL+C to quit)
> 2023-09-14 17:52:32,222 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpcr7ahvmh
> 2023-09-14 17:52:32,222 - instantiator.py[line:76] - INFO: Writing /tmp/tmpcr7ahvmh/_remote_module_non_scriptable.py
> 2023-09-14 17:52:32,223 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpud_vdpcw
> 2023-09-14 17:52:32,223 - instantiator.py[line:76] - INFO: Writing /tmp/tmpud_vdpcw/_remote_module_non_scriptable.py
> 2023-09-14 17:52:32,230 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpdp_ksxtt
> 2023-09-14 17:52:32,230 - instantiator.py[line:76] - INFO: Writing /tmp/tmpdp_ksxtt/_remote_module_non_scriptable.py
> 2023-09-14 17:52:32,231 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpz8rc285n
> 2023-09-14 17:52:32,231 - instantiator.py[line:76] - INFO: Writing /tmp/tmpz8rc285n/_remote_module_non_scriptable.py
> 2023-09-14 17:52:32,236 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpm1p8n34u
> 2023-09-14 17:52:32,236 - instantiator.py[line:76] - INFO: Writing /tmp/tmpm1p8n34u/_remote_module_non_scriptable.py
> 2023-09-14 17:52:32 | INFO | model_worker | Loading the model ['baichuan2-13B-chat-8bit'] on worker f31c6ee4 ...
> 2023-09-14 17:52:32 | INFO | model_worker | Register to controller
> 2023-09-14 17:52:32 | INFO | controller | Register a new worker: http://192.168.24.252:20003
> 2023-09-14 17:52:32 | INFO | controller | Register done: http://192.168.24.252:20003, {'model_names': ['chatglm-api'], 'speed': 1, 'queue_length': 0}
> 2023-09-14 17:52:32 | INFO | stdout | INFO:     192.168.24.252:50706 - "POST /register_worker HTTP/1.1" 200 OK
> INFO:     Started server process [678168]
> INFO:     Waiting for application startup.
> 2023-09-14 17:52:32 | ERROR | stderr | INFO:     Started server process [678166]
> 2023-09-14 17:52:32 | ERROR | stderr | INFO:     Waiting for application startup.
> 2023-09-14 17:52:32 | ERROR | stderr | INFO:     Application startup complete.
> 2023-09-14 17:52:32 | ERROR | stderr | INFO:     Uvicorn running on http://192.168.24.252:7889 (Press CTRL+C to quit)
> Loading checkpoint shards:   0%|                                                                | 0/2 [00:00<?, ?it/s]INFO:     Started server process [678169]
> INFO:     Waiting for application startup.
> Loading checkpoint shards: 100%|????????????????????????????????????????????????????????| 2/2 [00:10<00:00,  5.43s/it]
> 2023-09-14 17:52:43 | WARNING | accelerate.big_modeling | You shouldn't move a model when it is dispatched on multiple devices.
> Process model_worker - baichuan2-13B-chat-8bit:
> Traceback (most recent call last):
>   File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
>     self.run()
>   File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/chenchen/Code/Langchain-Chatchat/startup.py", line 319, in run_model_worker
>     app = create_model_worker_app(log_level=log_level, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/chenchen/Code/Langchain-Chatchat/startup.py", line 133, in create_model_worker_app
>     worker = ModelWorker(
>              ^^^^^^^^^^^^
>   File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 207, in __init__
>     self.model, self.tokenizer = load_model(
>                                  ^^^^^^^^^^^
>   File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 274, in load_model
>     model.to(device)
>   File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/site-packages/accelerate/big_modeling.py", line 411, in wrapper
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/home/chenchen/anaconda3/envs/llm/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2048, in to
>     raise ValueError(
> ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
> 2023-09-14 17:53:17 | INFO | model_worker | Send heart beat. Models: ['chatglm-api']. Semaphore: None. call_ct: 0. worker_id: 1e991c17. 
> 2023-09-14 17:53:17 | INFO | controller | Receive heart beat. http://192.168.24.252:20003
> 2023-09-14 17:53:17 | INFO | stdout | INFO:     192.168.24.252:50712 - "POST /receive_heart_beat HTTP/1.1" 200 OK
> ```
> 
> ![image](https://user-images.githubusercontent.com/58684828/267937084-43613a33-2cdc-4907-807f-ec0d018f46f0.png) 目前测试来看baichuan系列必挂，每一个模型都会爆出不同的错误，chatglm系列没问题，图中的模型使用transformers的方式都可以正常使用
> 
> 追源码看了一下没看出所以然，在startup.py中强制替换ModelWorker的模型后提示`raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'BaichuanForCausalLM' object has no attribute 'stream_generate'`请教一下大佬们为什么会这样

求一下你baichuan2-13B-Chat量化8bit版本下载地址

**Comment by WilliamChen-luckbob** [comment]
> 求一下你baichuan2-13B-Chat量化8bit版本下载地址
我可以直接外网访问，直接在huggingface上面下载的，然后自己转了8bit版本，当然直接使用原版，传入参数--load-8bit也可以，我现在还卡在集成fastchat上，这个项目的一键启动似乎没有写明如何使用int8量化来启动模型，我是本地硬编码改了一键启动配置，能够输出但是输出乱码

**Comment by iaoxuesheng** [comment]
好的谢谢

**Comment by WilliamChen-luckbob** [comment]
0.2.4已经集成fastchat 0.2.28版本已经支持了baichuan2-13b-chat了，尽管还有诸多bug

**Comment by lanybass** [comment]
> 0.2.4已经集成fastchat 0.2.28版本已经支持了baichuan2-13b-chat了，尽管还有诸多bug

只能说是，初始运行没报错了，但是无法正常回答问题，一问问题就报一个choices的错误。。要么重复回复几十次同一个符号，要么只蹦一两个字出来。。

**Comment by zxyza** [comment]
transformers版本降一下
pip install transformers==4.34.0，直接加载就行了
