### ISSUE TITLE
运行python startup.py --all-webui 报错： AssertionError

### ISSUE THREAD

**Issue by ArlanCooper** [chatchat-space/Langchain-Chatchat#1517]
**问题描述 / Problem Description**
运行：
python startup.py --all-webui 
报错

**复现问题的步骤 / Steps to Reproduce**
进到git目录，运行：
python startup.py --all-webui 

**预期的结果 / Expected Result**
正常启动服务

**实际结果 / Actual Result**
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.19.118-1.el7.centos.x86_64-x86_64-with-glibc2.27.
python版本：3.9.12 (main, Jun  1 2022, 11:38:51)
[GCC 7.5.0]
项目版本：v0.2.4
langchain版本：0.0.287. fastchat版本：0.2.28

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ cuda
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': '/data/share/rwq/chatglm2-6b'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-09-18 18:51:49,895 - startup.py[line:541] - INFO: 正在启动服务：
2023-09-18 18:51:49,895 - startup.py[line:542] - INFO: 如需查看 llm_api 日志，请前往 /home/powerop/work/rwq/Langchain-Chatchat/logs
2023-09-18 18:51:50,491 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpc2mwoqrn
2023-09-18 18:51:50,492 - instantiator.py[line:76] - INFO: Writing /tmp/tmpc2mwoqrn/_remote_module_non_scriptable.py
2023-09-18 18:51:50 | ERROR | root | AttributeError: 在线模型 ‘qianfan-api’ 的provider没有正确配置
2023-09-18 18:51:53 | ERROR | stderr | INFO:     Started server process [442125]
2023-09-18 18:51:53 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-18 18:51:53 | ERROR | stderr | INFO:     Application startup complete.
2023-09-18 18:51:53 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
2023-09-18 18:51:57,980 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpmbkegjxa
2023-09-18 18:51:57,980 - instantiator.py[line:76] - INFO: Writing /tmp/tmpmbkegjxa/_remote_module_non_scriptable.py
2023-09-18 18:51:58,089 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpsnn8de3d
2023-09-18 18:51:58,090 - instantiator.py[line:76] - INFO: Writing /tmp/tmpsnn8de3d/_remote_module_non_scriptable.py
2023-09-18 18:51:58,114 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpah4h88zq
2023-09-18 18:51:58,115 - instantiator.py[line:76] - INFO: Writing /tmp/tmpah4h88zq/_remote_module_non_scriptable.py
2023-09-18 18:51:58,149 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmps6a545gx
2023-09-18 18:51:58,149 - instantiator.py[line:76] - INFO: Writing /tmp/tmps6a545gx/_remote_module_non_scriptable.py
Process api_worker - zhipu-api:
Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 107, in create_model_worker_app
    worker = worker_class(model_names=args.model_names,
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/zhipu.py", line 23, in __init__
    super().__init__(**kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
    self.init_heart_beat()
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/base.py", line 67, in init_heart_beat
    self.register_to_controller()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 113, in register_to_controller
    assert r.status_code == 200
AssertionError
Process api_worker - xinghuo-api:
Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 107, in create_model_worker_app
    worker = worker_class(model_names=args.model_names,
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/xinghuo.py", line 39, in __init__
    super().__init__(**kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
    self.init_heart_beat()
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/base.py", line 67, in init_heart_beat
    self.register_to_controller()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 113, in register_to_controller
    assert r.status_code == 200
AssertionError
Process api_worker - minimax-api:
Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 107, in create_model_worker_app
    worker = worker_class(model_names=args.model_names,
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/minimax.py", line 23, in __init__
    super().__init__(**kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
    self.init_heart_beat()
  File "/home/powerop/work/rwq/Langchain-Chatchat/server/model_workers/base.py", line 67, in init_heart_beat
    self.register_to_controller()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 113, in register_to_controller
    assert r.status_code == 200
AssertionError
Loading checkpoint shards: 100%|████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.54s/it]
Process model_worker - chatglm2-6b:
Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    worker = ModelWorker(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 232, in __init__
    self.init_heart_beat()
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 115, in _new_init_heart_beat
    self.register_to_controller()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 113, in register_to_controller
    assert r.status_code == 200
AssertionError

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.0.287
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Linux-4.19.118-1.el7.centos.x86_64-x86_64-with-glibc2.27.
- Python 版本 / Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by yutianchen666** [comment]
我也出现了同样的问题，重新部署在另一台服务器还是相同的结果，请问解决了吗

**Comment by ArlanCooper** [comment]
> 我也出现了同样的问题，重新部署在另一台服务器还是相同的结果，请问解决了吗

没有，不知道问题出在哪里

**Comment by ArlanCooper** [comment]
> 我也出现了同样的问题，重新部署在另一台服务器还是相同的结果，请问解决了吗

我参考了这个，https://github.com/chatchat-space/Langchain-Chatchat/issues/1166#issuecomment-1713327374，可以了

**Comment by yutianchen666** [comment]
感谢，我尝试一下

**Comment by ArlanCooper** [comment]
参考该链接，https://github.com/chatchat-space/Langchain-Chatchat/issues/1166#issuecomment-1713327374
就可以解决问题。
如果自己设置的ip是0.0.0.0的话，需要这样设置:
export no_proxy='$no_proxy,0.0.0.0'
就可以了。

**Comment by LJ854640097** [comment]
> 参考该链接，[#1166 (comment)](https://github.com/chatchat-space/Langchain-Chatchat/issues/1166#issuecomment-1713327374) 就可以解决问题。 如果自己设置的ip是0.0.0.0的话，需要这样设置: export no_proxy='$no_proxy,0.0.0.0' 就可以了。
请问
这个export no_proxy='$no_proxy,0.0.0.0‘ 具体需要写在哪里

**Comment by mayuseless** [comment]
关掉代理 
unset http_proxy
unset https_proxy
解决
