### ISSUE TITLE
v0.2.4版本，执行CUDA_VISIBLE_DEVICES=5 python startup.py -a，发现回答非常慢，查看日志发现使用的是CPU

### ISSUE THREAD

**Issue by Gzj369** [chatchat-space/Langchain-Chatchat#1526]
**问题描述 / Problem Description**
v0.2.4版本，执行CUDA_VISIBLE_DEVICES=5 python startup.py -a，发现回答非常慢，查看日志发现使用的是CPU；
但是执行CUDA_VISIBLE_DEVICES=0 python startup.py -a，查看日志发现使用的是cuda【**换了个GPU编号就不行了**】

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/d15fd5ed-e946-4405-8c8c-238510abf201)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.4
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Baichuan2-13B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 20.04.2 LTS
- Python 版本 / Python version:  3.10.9

麻烦大佬帮忙看看

**Comment by monifeng** [comment]
你先看看是不是真的有5卡，你能不能访问到5卡？
可以用`nvidia-smi`看一下
如果有的话，就去`langchain-chatchat/configs/server_config.py`里修改配置

**Comment by Gzj369** [comment]
> 你先看看是不是真的有5卡，你能不能访问到5卡？ 可以用`nvidia-smi`看一下 如果有的话，就去`langchain-chatchat/configs/server_config.py`里修改配置

查看nvidia-smi，发现编号为5的卡是正常的
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/0443e725-ef91-48fc-b17e-aa4ee8ad50dd)

然后configs/server_config.py中配置了也没有生效
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/cb703e1b-1232-4415-b833-6db01cee353d)

具体报错如下
(base) root@llama-new:/home/Langchain-Chatchat-master-v024# python startup.py -a 
True
True


==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.31.
python版本：3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0]
项目版本：v0.2.4
langchain版本：0.0.287. fastchat版本：0.2.28


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Baichuan2-13B-Chat'] @ cuda
{'api_base_url': 'http://0.0.0.0:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': '/home/Baichuan2-13B-Chat'}
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================


2023-09-19 15:08:38,063 - startup.py[line:546] - INFO: 正在启动服务：
2023-09-19 15:08:38,063 - startup.py[line:547] - INFO: 如需查看 llm_api 日志，请前往 /home/Langchain-Chatchat-master-v024/logs
Setting ds_accelerator to cuda (auto detect)
True
2023-09-19 15:08:41 | ERROR | stderr | INFO:     Started server process [88841]
2023-09-19 15:08:41 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-19 15:08:41 | ERROR | stderr | INFO:     Application startup complete.
2023-09-19 15:08:41 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20001 (Press CTRL+C to quit)
True
True
2023-09-19 15:08:43 | ERROR | stderr | INFO:     Started server process [89001]
2023-09-19 15:08:43 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-19 15:08:43 | ERROR | stderr | INFO:     Application startup complete.
2023-09-19 15:08:43 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
Setting ds_accelerator to cuda (auto detect)
2023-09-19 15:08:44 | INFO | model_worker | Loading the model ['Baichuan2-13B-Chat'] on worker 203d883a ...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:21<00:00,  7.11s/it]
Process model_worker - Baichuan2-13B-Chat:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 260, in _lazy_init
    queued_call()
  File "/root/anaconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 145, in _check_capability
    capability = get_device_capability(d)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 381, in get_device_capability
    prop = get_device_properties(device)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Langchain-Chatchat-master-v024/startup.py", line 308, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/Langchain-Chatchat-master-v024/startup.py", line 140, in create_model_worker_app
    worker = ModelWorker(
  File "/root/anaconda3/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 213, in __init__
    self.model, self.tokenizer = load_model(
  File "/root/anaconda3/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 292, in load_model
    model.to(device)
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2014, in to
    return super().to(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 264, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

CUDA call was originally invoked at:

['  File "<string>", line 1, in <module>\n', '  File "/root/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\n    exitcode = _main(fd, parent_sentinel)\n', '  File "/root/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\n    prepare(preparation_data)\n', '  File "/root/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\n    _fixup_main_from_path(data[\'init_main_from_path\'])\n', '  File "/root/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\n    main_content = runpy.run_path(main_path,\n', '  File "/root/anaconda3/lib/python3.10/runpy.py", line 289, in run_path\n    return _run_module_code(code, init_globals, run_name,\n', '  File "/root/anaconda3/lib/python3.10/runpy.py", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n', '  File "/root/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code\n    exec(code, run_globals)\n', '  File "/home/Langchain-Chatchat-master-v024/startup.py", line 9, in <module>\n    import torch\n', '  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n', '  File "/root/anaconda3/lib/python3.10/site-packages/torch/__init__.py", line 1146, in <module>\n    _C._initExtension(manager_path())\n', '  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n', '  File "/root/anaconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 197, in <module>\n    _lazy_call(_check_capability)\n', '  File "/root/anaconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 195, in _lazy_call\n    _queued_calls.append((callable, traceback.format_stack()))\n']

**Comment by Gzj369** [comment]
问题已经解决，虽然表面的编号是5，但实际上按可用的顺序来看，为2。
CUDA_VISIBLE_DEVICES=2 python startup.py -a 问题解决

**Comment by Gzj369** [comment]
> 你先看看是不是真的有5卡，你能不能访问到5卡？ 可以用`nvidia-smi`看一下 如果有的话，就去`langchain-chatchat/configs/server_config.py`里修改配置

非常感谢！
