### ISSUE TITLE
[BUG] Load LLM model (vicuna-13b-v1.5-16k and dolly-v2-12b) failure

### ISSUE THREAD

**Issue by oldmikeyang** [chatchat-space/Langchain-Chatchat#1551]
**问题描述 / Problem Description**
Load LLM model (vicuna-13b-v1.5-16k and dolly-v2-12b) failure, with incorrect input parameter embed_in_truncate

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
It should load the LLM correctly.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

Process model_worker - vicuna-13b-v1.5-16k:
Traceback (most recent call last):
  File "/home/disk1/llm/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/disk1/llm/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/disk1/llm/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/disk1/llm/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    worker = ModelWorker(
TypeError: ModelWorker.__init__() got an unexpected keyword argument 'embed_in_truncate'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.4
- 是否使用 Docker 部署（是/否）：No
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：vicuna-13b-v1.5-16k and dolly-v2-12b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：all-mpnet-base-v2
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: CentOS Stream 9
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by oldmikeyang** [comment]
Fix this issue after upgrade the fschat[model_worker]==0.2.28
