### ISSUE TITLE
4. 知识库初始化报错  python init_database.py --recreate-vs 请大佬帮忙看看什么问题

### ISSUE THREAD

**Issue by uchihayou** [chatchat-space/Langchain-Chatchat#1559]
前面安装依赖都正常
执行python init_database.py --recreate-vs时报错：
Traceback (most recent call last):
  File "/opt/Chatchat/Langchain-Chatchat-0.2.4/init_database.py", line 1, in <module>
    from server.knowledge_base.migrate import create_tables, reset_tables, folder2db, recreate_all_vs, list_kbs_from_folder
  File "/opt/Chatchat/Langchain-Chatchat-0.2.4/server/knowledge_base/migrate.py", line 3, in <module>
    from server.knowledge_base.utils import (get_file_path, list_kbs_from_folder,
  File "/opt/Chatchat/Langchain-Chatchat-0.2.4/server/knowledge_base/utils.py", line 19, in <module>
    from text_splitter import zh_title_enhance
  File "/opt/Chatchat/Langchain-Chatchat-0.2.4/text_splitter/__init__.py", line 1, in <module>
    from .chinese_text_splitter import ChineseTextSplitter
  File "/opt/Chatchat/Langchain-Chatchat-0.2.4/text_splitter/chinese_text_splitter.py", line 1, in <module>
    from langchain.text_splitter import CharacterTextSplitter
  File "/opt/python3/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/opt/python3/lib/python3.9/site-packages/langchain/agents/__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "/opt/python3/lib/python3.9/site-packages/langchain/agents/agent.py", line 23, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "/opt/python3/lib/python3.9/site-packages/langchain/agents/agent_iterator.py", line 21, in <module>
    from langchain.callbacks.manager import (
  File "/opt/python3/lib/python3.9/site-packages/langchain/callbacks/__init__.py", line 10, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler
  File "/opt/python3/lib/python3.9/site-packages/langchain/callbacks/aim_callback.py", line 5, in <module>
    from langchain.schema import AgentAction, AgentFinish, LLMResult
  File "/opt/python3/lib/python3.9/site-packages/langchain/schema/__init__.py", line 3, in <module>
    from langchain.schema.cache import BaseCache
  File "/opt/python3/lib/python3.9/site-packages/langchain/schema/cache.py", line 6, in <module>
    from langchain.schema.output import Generation
  File "/opt/python3/lib/python3.9/site-packages/langchain/schema/output.py", line 7, in <module>
    from langchain.load.serializable import Serializable
  File "/opt/python3/lib/python3.9/site-packages/langchain/load/serializable.py", line 4, in <module>
    from langchain.pydantic_v1 import BaseModel, PrivateAttr
ImportError: cannot import name 'BaseModel' from 'langchain.pydantic_v1' (/opt/python3/lib/python3.9/site-packages/langchain/pydantic_v1/__init__.py)

**Comment by liyun1125** [comment]
应该是langchain的版本不对

**Comment by WilliamChen-luckbob** [comment]
在你的项目的虚拟环境下
`pip uninstall -r requirements.txt -y`
`pip install -r requirements.txt`
重装一下服务依赖再启动试试呢？

**Comment by glide-the** [comment]
你的环境可能存在多个，默认系统软件包会覆盖虚拟环境的软件包，你需要找到系统包清空依赖。**请注意！您的依赖修改之前请确认影响范围**

**Comment by uchihayou** [comment]
感谢各位大佬，问提已解决！

**Comment by zhanbei1** [comment]
@uchihayou 如何解决的，可以贴一下处理步骤吗

**Comment by uchihayou** [comment]
> @uchihayou 如何解决的，可以贴一下处理步骤吗

pip uninstall pydantic
pip install pydantic
解决的
