### ISSUE TITLE
set the option `trust_remote_code=True` to remove this error

### ISSUE THREAD

**Issue by xiaojing-503** [chatchat-space/Langchain-Chatchat#1584]
请问在哪设置=`trust_remote_code=True` ，搜索了from_pretrained的地方改掉了也不行
Traceback (most recent call last):
  File "/home/xb/anaconda3/envs/envlc/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/xb/anaconda3/envs/envlc/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xb/jhy/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/xb/jhy/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    worker = ModelWorker(
  File "/home/xb/anaconda3/envs/envlc/lib/python3.8/site-packages/fastchat/serve/model_worker.py", line 213, in __init__
    self.model, self.tokenizer = load_model(
  File "/home/xb/anaconda3/envs/envlc/lib/python3.8/site-packages/fastchat/model/model_adapter.py", line 279, in load_model
    model, tokenizer = adapter.load_model(model_path, kwargs)
  File "/home/xb/anaconda3/envs/envlc/lib/python3.8/site-packages/fastchat/model/model_adapter.py", line 74, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/xb/anaconda3/envs/envlc/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 527, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/xb/anaconda3/envs/envlc/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 1026, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/home/xb/anaconda3/envs/envlc/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 608, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading this model requires you to execute execute some code in that repo on your local machine. Make sure you have read the code at https://hf.co//home/xb/jhy/Langchain-Chatchat/model/ to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

**Comment by kk19990709** [comment]
请问这个是怎么解决的？

**Comment by lihongyong** [comment]
请问怎么解决的？

**Comment by pingxue-hfut** [comment]
修改\envs\longchain\Lib\site-packages\transformers\dynamic_module_utils.py的resolve_trust_remote_code函数，让其始终return True
