### ISSUE TITLE
[BUG] ChatGLM2-6B无法在8bit量化下启动服务

### ISSUE THREAD

**Issue by 18239256** [chatchat-space/Langchain-Chatchat#1589]
**问题描述 / Problem Description**
按照配置完全配置好后，可以正常开启所有服务，且工作正常。但在server_config.py里面开启量化8bit的时候报错，无法启动环境。
"load_8bit": True, # 开启8bit量化

**复现问题的步骤 / Steps to Reproduce**
1. server_config.py中打开“"load_8bit": True”，并配置为True
2. 用$ python startup.py -a 开启所有服务

**预期的结果 / Expected Result**
服务开启正常

**实际结果 / Actual Result**
无法正常启动

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.0.287
- 是否使用 Docker 部署（是）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec-large-chinese
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: ubuntu
- Python 版本 / Python version: 3.8.10

**附加信息 / Additional Information**
错误日志如下：
2023-09-25 12:25:44,595 - startup.py[line:542] - INFO: 正在启动服务：
2023-09-25 12:25:44,595 - startup.py[line:543] - INFO: 如需查看 llm_api 日志，请前往 /root/Langchain-Chatchat/logs
2023-09-25 12:25:44,904 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp_x7x9go0
2023-09-25 12:25:44,904 - instantiator.py[line:76] - INFO: Writing /tmp/tmp_x7x9go0/_remote_module_non_scriptable.py
2023-09-25 12:25:46 | ERROR | stderr | INFO:     Started server process [1875]
2023-09-25 12:25:46 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-25 12:25:46 | ERROR | stderr | INFO:     Application startup complete.
2023-09-25 12:25:46 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:10001 (Press CTRL+C to quit)
2023-09-25 12:25:47,831 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpk1a9m7ym
2023-09-25 12:25:47,831 - instantiator.py[line:76] - INFO: Writing /tmp/tmpk1a9m7ym/_remote_module_non_scriptable.py
2023-09-25 12:25:47,844 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp5m8s03lo
2023-09-25 12:25:47,844 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpxnycof4n
2023-09-25 12:25:47,844 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpb1or3men
2023-09-25 12:25:47,844 - instantiator.py[line:76] - INFO: Writing /tmp/tmp5m8s03lo/_remote_module_non_scriptable.py
2023-09-25 12:25:47,844 - instantiator.py[line:76] - INFO: Writing /tmp/tmpxnycof4n/_remote_module_non_scriptable.py
2023-09-25 12:25:47,844 - instantiator.py[line:76] - INFO: Writing /tmp/tmpb1or3men/_remote_module_non_scriptable.py
2023-09-25 12:25:47,854 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp6ecjf3vf
2023-09-25 12:25:47,854 - instantiator.py[line:76] - INFO: Writing /tmp/tmp6ecjf3vf/_remote_module_non_scriptable.py
Process model_worker - chatglm2-6b:
Traceback (most recent call last):
  File "/root/miniconda3/envs/aigc/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/aigc/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/root/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    worker = ModelWorker(
  File "/root/miniconda3/envs/aigc/lib/python3.8/site-packages/fastchat/serve/model_worker.py", line 213, in __init__
    self.model, self.tokenizer = load_model(
  File "/root/miniconda3/envs/aigc/lib/python3.8/site-packages/fastchat/model/model_adapter.py", line 230, in load_model
    model, tokenizer = adapter.load_compress_model(
  File "/root/miniconda3/envs/aigc/lib/python3.8/site-packages/fastchat/model/model_adapter.py", line 84, in load_compress_model
    return load_compress_model(
  File "/root/miniconda3/envs/aigc/lib/python3.8/site-packages/fastchat/model/compression.py", line 126, in load_compress_model
    model = AutoModelForCausalLM.from_config(config, trust_remote_code=True)
  File "/root/miniconda3/envs/aigc/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 448, in from_config
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by 18239256** [comment]
更正一下：是否使用 Docker 部署（是）：否  !!!!

**Comment by zRzRzRzRzRzRzR** [comment]
在startup.py设置试试，最新代码中在startup.py中设置没有复现出这个问题

**Comment by hzg0601** [comment]
此为fschat的compression模块的bug，尝试更新fschat至最新版本，如仍有问题，可向fschat提issue
