### ISSUE TITLE
[BUG] 报错AssertionError: Only one of "bf16", "fp16", "fp32" can be true

### ISSUE THREAD

**Issue by qihangf** [chatchat-space/Langchain-Chatchat#1595]
**问题描述 / Problem Description**
是不支持用qlora出来的模型进行启动吗，还是其他的原因，我应该怎么去修改呢，麻烦大大指点一二

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'python startup.py -a

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
Process model_worker - peft-qw14:
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    worker = ModelWorker(
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 213, in__init__
    self.model, self.tokenizer = load_model(
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 279, in load_model
    model, tokenizer = adapter.load_model(model_path, kwargs)
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 503, in load_model
    base_model, tokenizer = base_adapter.load_model(
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 1353, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 488, in from_pretrained
    return model_class.from_pretrained(
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 807, in __init__
    assert (
AssertionError: Only one of "bf16", "fp16", "fp32" can be true

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)新版
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): qwen14b的qlora
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): m3e
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:乌班图
- Python 版本 / Python version:3.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by qihangf** [comment]
难道是还不支持qwen14b

**Comment by theafromhua** [comment]
修改下config.json，fp16改成true，bf16和fp32都是false，就能用了

**Comment by zRzRzRzRzRzRzR** [comment]
修改Qwen模型中的config.json，应该把fp16改成true，bf16和fp32改为false，即可解决问题
