### ISSUE TITLE
建议增加对智谱向量模型API的支持，提示词模板做成配置文件

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#1601]
**功能描述 / Feature Description**
1、建议Embedding增加对智谱在线的向量模型API的支持。我们发现智谱Embedding再搭配智谱模型，效果会更好。
2、建议将提示词模板做成配置文件或者可编辑，现在是在zhipu.py里面，无法实时修改。

**解决的问题 / Problem Solved**
智谱的在线知识库，对文档的装载、切片、Embedding效果是非常不错的，就是只有20M，空间太小。
建议用智谱在线的大模型和Embedding API，矢量库放本地。基于langchain-chatchat，只需要一台普通服务器，就可以快速搭建企业大模型应用。

**实现建议 / Implementation Suggestions**
现在智谱、商汤、minmax、讯飞星火都出了开放平台，token都非常便宜。企业完全没必要购买GPU服务器，只需要基于langchain-chatchat，将矢量库放在本地。就可以实现数据不出场，并将大模型和企业现有业务快速结合。

**Comment by justforword** [comment]
数据不出场？调用向量模型的时候，数据也会通过api出去的吧。

**Comment by zRzRzRzRzRzRzR** [comment]
已经支持

**Comment by dengliming** [comment]
我这边按wiki配置了智谱的在线模型，但是报错

```
2023-12-18 12:19:36,737 - utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/data/Langchain-Chatchat/Langchain-Chatchat-master/server/utils.py", line 22, in wrap_done
    await fn
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/usr/local/python3.8.13/lib/python3.8/site-packages/langchain/chat_models/openai.py", line 477, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2023-12-18 12:19:36,738 - utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
```

**Comment by LaoK263** [comment]
> 已经支持

如何在配置文件中修改，以便让系统支持智谱的embedding-2向量模型API呢？目前还没有找到相关的文档，尝试把model_config.py的EMBEDDING_MODEL修改为embedding-2，但是收到了”ValueError: 'embedding-2' is not in list“的运行时错误
