### ISSUE TITLE
[BUG] 知识库问答偶尔报“API通信遇到错误”或者能回答但是没有用知识库，点击“依据源文件重建向量库”就正常

### ISSUE THREAD

**Issue by kevindany** [chatchat-space/Langchain-Chatchat#1609]
**问题描述
报“API通信遇到错误”时，或者能回答但是没有用知识库的时候（lm对话都是ok的），我发现“依据源文件重建向量库”就好使了。非常诡异。
具体定位不到更详细的异常，搜索了相关的bug也没有找到答案，有朋友遇到的话麻烦告知，多谢。

error log如下：root _httpx_stream2generator 261 12545]  RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/server/work/anaconda3/envs/py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/server/work/anaconda3/envs/py3.10/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 197, in _receive_event
    event = self._h11_state.next_event()
  File "/server/work/anaconda3/envs/py3.10/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/server/work/anaconda3/envs/py3.10/lib/python3.10/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
  File "/server/work/anaconda3/envs/py3.10/lib/python3.10/site-packages/h11/_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**复现问题的步骤 / Steps to Reproduce**
情形1:
1. 重新启动所有服务之后，选择知识库问答
2. 偶尔会发现回答根本没有用到知识库
3. 点击“依据源文件重建向量库”就正常了

情形2:
1. 知识库问答中，开始正常，某个时刻UI报：API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
2. 重启所有服务不生效
3. 点击“依据源文件重建向量库”就正常了

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(dev分支v0.2.4-preview)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Centos 7
- Python 版本 / Python version: 3.10

langchain 版本：0.0.266

**Comment by zRzRzRzRzRzRzR** [comment]
更新啊到最新版本后再次尝试一下是否还有这个问题

**Comment by wilson1229** [comment]
下载了最新版本。尝试了重启，重建，知识库问答还是一直报这个错误。

**Comment by chiehpower** [comment]
请问这个问题还有解决吗?

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题一直没能被复现出来，我们0.2.6版本修复了一些bug，如果0.2.6还有出现，重新提一下issue

**Comment by ShawnALiu** [comment]
2023-11-20 23:10:26 | ERROR | root | RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "D:\Miniconda3\envs\chatchat\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\Miniconda3\envs\chatchat\lib\site-packages\httpcore\_sync\http11.py", line 197, in _receive_event
    event = self._h11_state.next_event()
  File "D:\Miniconda3\envs\chatchat\lib\site-packages\h11\_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "D:\Miniconda3\envs\chatchat\lib\site-packages\h11\_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
  File "D:\Miniconda3\envs\chatchat\lib\site-packages\h11\_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
