### ISSUE TITLE
[BUG]启动加载zhipu在线模型报错

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#1632]
**问题描述 / Problem Description**
启动，加载zhipu_ai在线模型报错

**复现问题的步骤 / Steps to Reproduce**
1. 配置model_config.py，增加zhipu key，并将默认模型改为zhipu_ai
2.python startup.py -a 启动
3.可以出现WebUI，但输入信息，无反馈
4.命令行界面有报错

**预期的结果 / Expected Result**
连接在线大模型，反馈结果

**实际结果 / Actual Result**
无反馈结果

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm pro（zhipu ai在线模型）
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: windows2022 server
- Python 版本 / Python version:3.10.11
- 其他相关环境信息 / Other relevant environment information:无

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

(chatchat) C:\tmp\Langchain-Chatchat>python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.20348-SP0.
python版本：3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
项目版本：v0.2.5
langchain版本：0.0.304. fastchat版本：0.2.29

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['zhipu-api'] @ cpu
{'api_key': '494484b045a56586bb3821a02731a707.xXsxQaNTbtheuFed',
 'device': 'cpu',
 'host': '10.0.0.3',
 'infer_turbo': False,
 'model_path': None,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_pro',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2023-09-29 23:01:36 | INFO | root | 正在启动服务：
2023-09-29 23:01:36 | INFO | root | 如需查看 llm_api 日志，请前往 C:\tmp\Langchain-Chatchat\logs
2023-09-29 23:02:07 | ERROR | stderr | INFO:     Started server process [6932]
2023-09-29 23:02:08 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-29 23:02:08 | ERROR | stderr | INFO:     Application startup complete.
2023-09-29 23:02:08 | ERROR | stderr | INFO:     Uvicorn running on http://10.0.0.3:20000 (Press CTRL+C to quit)
INFO:     Started server process [6240]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://10.0.0.3:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.20348-SP0.
python版本：3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
项目版本：v0.2.5
langchain版本：0.0.304. fastchat版本：0.2.29

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['zhipu-api'] @ cpu
{'api_key': '494484b045a56586bb3821a02731a707.xXsxQaNTbtheuFed',
 'device': 'cpu',
 'host': '10.0.0.3',
 'infer_turbo': False,
 'model_path': None,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_pro',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
当前Embbedings模型： m3e-base @ cpu

服务端运行信息：
    OpenAI API Server: http://10.0.0.3:20000/v1
    Chatchat  API  Server: http://10.0.0.3:7861
    Chatchat WEBUI Server: http://10.0.0.3:8501
==============================Langchain-Chatchat Configuration==============================

      Welcome to Streamlit!

      If you’d like to receive helpful onboarding emails, news, offers, promotions,
      and the occasional swag, please enter your email address below. Otherwise,
      leave this field blank.

      Email:  dengdi@tom.com

  You can find our privacy policy at https://streamlit.io/privacy-policy

  Summary:
  - This open source library collects usage statistics.
  - We cannot see and do not store information contained inside Streamlit apps,
    such as text, charts, images, etc.
  - Telemetry data is stored in servers in the United States.
  - If you'd like to opt out, add the following to %userprofile%/.streamlit/config.toml,
    creating that file if necessary:

    [browser]
    gatherUsageStats = false

  You can now view your Streamlit app in your browser.

  URL: http://10.0.0.3:8501

2023-09-29 23:03:20 | INFO | httpx | HTTP Request: POST http://10.0.0.3:20001/list_models "HTTP/1.1 200 OK"
INFO:     10.0.0.3:53160 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-09-29 23:03:20 | INFO | httpx | HTTP Request: POST http://10.0.0.3:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     10.0.0.3:53160 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-09-29 23:03:20 | INFO | httpx | HTTP Request: POST http://10.0.0.3:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-09-29 23:07:19 | INFO | httpx | HTTP Request: POST http://10.0.0.3:20001/list_models "HTTP/1.1 200 OK"
INFO:     10.0.0.3:53304 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-09-29 23:07:19 | INFO | httpx | HTTP Request: POST http://10.0.0.3:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     10.0.0.3:53304 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-09-29 23:07:19 | INFO | httpx | HTTP Request: POST http://10.0.0.3:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-09-29 23:07:30 | INFO | httpx | HTTP Request: POST http://10.0.0.3:20001/list_models "HTTP/1.1 200 OK"
INFO:     10.0.0.3:53313 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-09-29 23:07:30 | INFO | httpx | HTTP Request: POST http://10.0.0.3:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     10.0.0.3:53313 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-09-29 23:07:30 | INFO | httpx | HTTP Request: POST http://10.0.0.3:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'model_name': 'zhipu-api',
 'prompt_name': 'llm_chat',
 'query': '你是谁',
 'stream': True,
 'temperature': 0.7}
INFO:     10.0.0.3:53313 - "POST /chat/chat HTTP/1.1" 200 OK
2023-09-29 23:07:30 | INFO | httpx | HTTP Request: POST http://10.0.0.3:7861/chat/chat "HTTP/1.1 200 OK"
count token
{'model': 'zhipu-api', 'prompt': '你是一个聪明、对人类有帮助的人工智能，你可以对人类提出的问题给出有用、详细、礼貌的回答。\n### Human: 你是谁\n### Assistant:'}
2023-09-29 23:07:30 | INFO | stdout | INFO:     10.0.0.3:53316 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-09-29 23:07:30 | INFO | openai | message='OpenAI API response' path=http://10.0.0.3:20000/v1/chat/completions processing_ms=None request_id=None response_code=200
2023-09-29 23:07:30 | INFO | httpx | HTTP Request: POST http://10.0.0.3:21001/worker_generate_stream "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
  File "C:\tmp\Langchain-Chatchat\server\model_workers\zhipu.py", line 38, in generate_stream_gate
    import zhipuai
ModuleNotFoundError: No module named 'zhipuai'
2023-09-29 23:07:30 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-09-29 23:07:30 | ERROR | stderr | Traceback (most recent call last):
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
2023-09-29 23:07:30 | ERROR | stderr |     yield
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpcore\_async\http11.py", line 197, in _receive_event
2023-09-29 23:07:30 | ERROR | stderr |     event = self._h11_state.next_event()
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\h11\_connection.py", line 469, in next_event
2023-09-29 23:07:30 | ERROR | stderr |     event = self._extract_next_receive_event()
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\h11\_connection.py", line 419, in _extract_next_receive_event
2023-09-29 23:07:30 | ERROR | stderr |     event = self._reader.read_eof()  # type: ignore[attr-defined]
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\h11\_readers.py", line 204, in read_eof
2023-09-29 23:07:30 | ERROR | stderr |     raise RemoteProtocolError(
2023-09-29 23:07:30 | ERROR | stderr | h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2023-09-29 23:07:30 | ERROR | stderr |
2023-09-29 23:07:30 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-09-29 23:07:30 | ERROR | stderr |
2023-09-29 23:07:30 | ERROR | stderr | Traceback (most recent call last):
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
2023-09-29 23:07:30 | ERROR | stderr |     yield
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpx\_transports\default.py", line 239, in __aiter__
2023-09-29 23:07:30 | ERROR | stderr |     async for part in self._httpcore_stream:
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpcore\_async\connection_pool.py", line 347, in __aiter__
2023-09-29 23:07:30 | ERROR | stderr |     async for part in self._stream:
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpcore\_async\http11.py", line 325, in __aiter__
2023-09-29 23:07:30 | ERROR | stderr |     raise exc
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpcore\_async\http11.py", line 317, in __aiter__
2023-09-29 23:07:30 | ERROR | stderr |     async for chunk in self._connection._receive_response_body(**kwargs):
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_body
2023-09-29 23:07:30 | ERROR | stderr |     event = await self._receive_event(timeout=timeout)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpcore\_async\http11.py", line 196, in _receive_event
2023-09-29 23:07:30 | ERROR | stderr |     with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
2023-09-29 23:07:30 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
2023-09-29 23:07:30 | ERROR | stderr |     raise to_exc(exc) from exc
2023-09-29 23:07:30 | ERROR | stderr | httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2023-09-29 23:07:30 | ERROR | stderr |
2023-09-29 23:07:30 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-09-29 23:07:30 | ERROR | stderr |
2023-09-29 23:07:30 | ERROR | stderr | Traceback (most recent call last):
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
2023-09-29 23:07:30 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\fastapi\applications.py", line 292, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\applications.py", line 122, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     raise exc
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     await self.app(scope, receive, send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     raise exc
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     raise e
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     await self.app(scope, receive, send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\routing.py", line 718, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\routing.py", line 276, in handle
2023-09-29 23:07:30 | ERROR | stderr |     await self.app(scope, receive, send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\routing.py", line 69, in app
2023-09-29 23:07:30 | ERROR | stderr |     await response(scope, receive, send)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\responses.py", line 270, in __call__
2023-09-29 23:07:30 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
2023-09-29 23:07:30 | ERROR | stderr |     raise exceptions[0]
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\responses.py", line 273, in wrap
2023-09-29 23:07:30 | ERROR | stderr |     await func()
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\starlette\responses.py", line 262, in stream_response
2023-09-29 23:07:30 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\fastchat\serve\openai_api_server.py", line 431, in chat_completion_stream_generator
2023-09-29 23:07:30 | ERROR | stderr |     async for content in generate_completion_stream(gen_params, worker_addr):
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\fastchat\serve\openai_api_server.py", line 602, in generate_completion_stream
2023-09-29 23:07:30 | ERROR | stderr |     async for raw_chunk in response.aiter_raw():
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpx\_models.py", line 985, in aiter_raw
2023-09-29 23:07:30 | ERROR | stderr |     async for raw_stream_bytes in self.stream:
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpx\_client.py", line 146, in __aiter__
2023-09-29 23:07:30 | ERROR | stderr |     async for chunk in self._stream:
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpx\_transports\default.py", line 238, in __aiter__
2023-09-29 23:07:30 | ERROR | stderr |     with map_httpcore_exceptions():
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
2023-09-29 23:07:30 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2023-09-29 23:07:30 | ERROR | stderr |   File "C:\tmp\Langchain-Chatchat\chatchat\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
2023-09-29 23:07:30 | ERROR | stderr |     raise mapped_exc(message) from exc
2023-09-29 23:07:30 | ERROR | stderr | httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2023-09-29 23:07:30 | ERROR | root | ClientPayloadError: Caught exception: Response payload is not completed

**Comment by szdengdi** [comment]
已经解决，应当是智谱在线api不支持海外ip导致，更改为minimax，解决。

**Comment by szdengdi** [comment]
因国内访问huggingface.co困难，做了一个windows下的整合包，内置了chatglm2-6B、m3e-base，可以本地运行langchain-chatchat0.2.5的LLM、知识库、搜索增强等功能。

链接:https://caiyun.139.com/m/i?135ClpbtTooUm
提取码:mTjG

【准备工作】
1、（建议）提前在智谱、minimax、讯飞星火等大模型平台申请账号和key
2、提前在微软azure.com上注册账号，并订阅bing搜索服务，申请Key（可以选择免费版本）
3、下载langchain-chatchat0.2.5.zip文件

【安装】
1、解压Langchain-Chatchat0.2.5.zip，例如解压到 c:\tmp\Langchain-Chatchat 目录
2-1、如果没有GPU或者GPU显存小于12G，建议用在线大模型：用文本编辑器修改config目录中的model_config.py文件，将申请的大模型key输入到114~184行，同时修改100行LLM_MODEL为对应大模型，例如："zhipu-api"
2-2、如果有12G显存以上GPU，修改100行LLM_MODEL为本地大模型，例如："chatglm2-6b"
3、修改config目录中kb_config.py的37行，将BING_SUBSCRIPTION_KEY改为azure上申请的bing key
4、建议安装anaconda，对python虚拟环境进行管理（https://www.anaconda.com/download/）
5、点击“开始”-》Anaconda3-》Anaconda Powershell Prompt
6、创建python虚拟环境：conda create -n chatchat python==3.10.9
7、激活python虚拟环境：conda activate chatchat
8、进入程序目录：cd c:\tmp\Langchain-Chatchat
9、安装依赖包：pip install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/

【运行】
1、点击“开始”-》Anaconda3-》Anaconda Powershell Prompt
2、进入目录，输入：cd c:\tmp\Langchain-Chatchat
3、激活python环境：conda activate chatchat
4、运行程序：python startup.py -a
