### ISSUE TITLE
[BUG] DefaultCPUAllocator 与 404 Not Found

### ISSUE THREAD

**Issue by Moon-404** [chatchat-space/Langchain-Chatchat#1641]
**问题描述 / Problem Description**
```
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 112197632 bytes.
2023-10-02 16:19:37 | INFO | stdout | INFO:     ::1:61051 - "GET / HTTP/1.1" 404 Not Found
````

**复现问题的步骤 / Steps to Reproduce**
1. 使用copy_config_example.py复制config（其中还有一个拼写错误）
2. 下载ChatGLM2-6B-int4与m3e-base模型
3. 使用init_databse.py初始化
4. 运行startup.py -a

**预期的结果 / Expected Result**

正常进入webui

**实际结果 / Actual Result**
```
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
项目版本：v0.2.5
langchain版本：0.0.305. fastchat版本：0.2.29

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b-int4'] @ cuda
{'device': 'cuda',
 'host': 'localhost',
 'infer_turbo': False,
 'max_gpu_memory': '6GiB',
 'model_path': 'F:\\Projects\\ChatGLM2-6B\\model',
 'port': 20002}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2023-10-02 16:13:06 | INFO | root | 正在启动服务：
2023-10-02 16:13:06 | INFO | root | 如需查看 llm_api 日志，请前往 f:\Projects\Langchain-Chatchat\logs
2023-10-02 16:13:13 | ERROR | stderr | INFO:     Started server process [11140]
2023-10-02 16:13:13 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-02 16:13:13 | ERROR | stderr | INFO:     Application startup complete.
2023-10-02 16:13:13 | ERROR | stderr | INFO:     Uvicorn running on http://localhost:20000 (Press CTRL+C to quit)
Process model_worker - chatglm2-6b-int4:
Traceback (most recent call last):
  File "E:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "E:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "f:\Projects\Langchain-Chatchat\startup.py", line 366, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "f:\Projects\Langchain-Chatchat\startup.py", line 194, in create_model_worker_app
    worker = ModelWorker(
  File "E:\Python\lib\site-packages\fastchat\serve\model_worker.py", line 221, in __init__
    self.model, self.tokenizer = load_model(
  File "E:\Python\lib\site-packages\fastchat\model\model_adapter.py", line 288, in load_model
    model, tokenizer = adapter.load_model(model_path, kwargs)
  File "E:\Python\lib\site-packages\fastchat\model\model_adapter.py", line 692, in load_model
    model = AutoModel.from_pretrained(
  File "E:\Python\lib\site-packages\transformers\models\auto\auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "E:\Python\lib\site-packages\transformers\modeling_utils.py", line 2675, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\model\modeling_chatglm.py", line 854, in __init__
    self.transformer = ChatGLMModel(config, empty_init=empty_init, device=device)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\model\modeling_chatglm.py", line 754, in __init__
    self.encoder = init_method(GLMTransformer, config, **init_kwargs)
  File "E:\Python\lib\site-packages\torch\nn\utils\init.py", line 52, in skip_init
    return module_cls(*args, **kwargs).to_empty(device=final_device)
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1024, in to_empty
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1024, in <lambda>
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "E:\Python\lib\site-packages\torch\_refs\__init__.py", line 4254, in empty_like
    return torch.empty_strided(
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 112197632 bytes.
2023-10-02 16:19:37 | INFO | stdout | INFO:     ::1:61051 - "GET / HTTP/1.1" 404 Not Found
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：e88d926
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B-int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Windows 11
- Python 版本 / Python version: 3.10.11
- 其他相关环境信息 / Other relevant environment information: NVIDIA GeForce RTX 3060 Laptop GPU

**附加信息 / Additional Information**

我的设备是6G显存16G内存，已经测试过可以正常运行ChatGLM2-6B-int4了，目前想询问是否有不升级设备的情况下可以成功运行的方法。可以允许损失性能，只要能跑通测试，我就可以以此去申请更好的设备了。

相关issue我都翻阅一遍了，解决方案都是让我更新到最新版，然而我已经是最新版。

**Comment by beybin** [comment]
8G显存+16G内存跑ChatGLM2-6B-int4也提示“not enough memory”

**Comment by zRzRzRzRzRzRzR** [comment]
6G显存基本不行，大部分模型基本得超过了这个数，int4的Qwen7B可以试试，其他估计都跑不了，确实得升级显存
