### ISSUE TITLE
[求助] 初始化知识库发生错误

### ISSUE THREAD

**Issue by ye7love7** [chatchat-space/Langchain-Chatchat#1657]
**问题描述 / Problem Description**
初始化知识库python init_database.py --recreate-vs
发生报错，AssertionError

**环境信息 / Environment Information**
- 版本：0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：piccolo-large-zh
- 使用的向量库类型: faiss
- 操作系统及版本 / Operating system and version:Ubuntu22.04
- Python 版本 / Python version:310
(chatchat) tskj@tskj:~/Langchain-Chatchat-0.2.5/Langchain-Chatchat-master$ python init_database.py --recreate-vs
database talbes reseted
recreating all vector stores
2023-10-04 14:51:12,101 - faiss_cache.py[line:75] - INFO: loading vector store in 'samples/vector_store' from disk.
{}
2023-10-04 14:51:14,248 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /home/tskj/MOD/piccolo-large-zh
2023-10-04 14:51:14,248 - SentenceTransformer.py[line:805] - WARNING: No sentence-transformers model found with name /home/tskj/MOD/piccolo-large-zh. Creating a new one with MEAN pooling.
2023-10-04 14:51:15,149 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpbtqppi2i
2023-10-04 14:51:15,150 - instantiator.py[line:76] - INFO: Writing /tmp/tmpbtqppi2i/_remote_module_non_scriptable.py
[2023-10-04 14:51:15,247] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-10-04 14:51:23,173 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-10-04 14:51:23,188 - loader.py[line:56] - INFO: Successfully loaded faiss with AVX2 support.
2023-10-04 14:51:23,276 - utils.py[line:289] - INFO: UnstructuredFileLoader used for /home/tskj/Langchain-Chatchat-0.2.5/Langchain-Chatchat-master/knowledge_base/samples/content/test.txt
2023-10-04 14:51:23,900 - utils.py[line:148] - INFO: Note: NumExpr detected 56 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-10-04 14:51:23,901 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
----------------之后开始切分文本-------------------
Traceback (most recent call last):
  File "/home/tskj/Langchain-Chatchat-0.2.5/Langchain-Chatchat-master/init_database.py", line 81, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs")
  File "/home/tskj/Langchain-Chatchat-0.2.5/Langchain-Chatchat-master/server/knowledge_base/migrate.py", line 76, in folder2db
    files2vs(kb_name, kb_files)
  File "/home/tskj/Langchain-Chatchat-0.2.5/Langchain-Chatchat-master/server/knowledge_base/migrate.py", line 63, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "/home/tskj/Langchain-Chatchat-0.2.5/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 100, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
  File "/home/tskj/Langchain-Chatchat-0.2.5/Langchain-Chatchat-master/server/knowledge_base/kb_service/faiss_kb_service.py", line 72, in do_add_doc
    ids = vs.add_documents(docs)
  File "/home/tskj/miniconda3/envs/chatchat/lib/python3.10/site-packages/langchain/schema/vectorstore.py", line 104, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/home/tskj/miniconda3/envs/chatchat/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 167, in add_texts
    return self.__add(texts, embeddings, metadatas=metadatas, ids=ids)
  File "/home/tskj/miniconda3/envs/chatchat/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 139, in __add
    self.index.add(vector)
  File "/home/tskj/miniconda3/envs/chatchat/lib/python3.10/site-packages/faiss/class_wrappers.py", line 228, in replacement_add
    assert d == self.d
AssertionError

**Comment by ye7love7** [comment]
已解决，将原来知识库中的内容都删除即可。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月5日(周四) 晚上10:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] [求助] 初始化知识库发生错误 (Issue #1657)




 
安装transformers==4.33.3试一下。

**Comment by cwyalpha** [comment]
同样的问题，删除原知识库从头安装未解决

**Comment by cwyalpha** [comment]
> 你是什么系统？如果跟我一样的话，这个方法应该是有效的。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月6日(周五) 晚上7:13 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [chatchat-space/Langchain-Chatchat] [求助] 初始化知识库发生错误 (Issue #1657) 同样的问题，删除原知识库从头安装未解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以了，要把knowledgebase目录里的vector store也都删了。。

**Comment by 1748995976** [comment]
请问原知识库的路径是在哪里可以看到呢？

**Comment by toby911** [comment]
你好,liunux4odoo,知识库报错修复了了吗
