### ISSUE TITLE
[BUG] 'BaichuanTokenizer' object has no attribute 'sp_model'

### ISSUE THREAD

**Issue by liushifu12138** [chatchat-space/Langchain-Chatchat#1665]
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.5
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-13B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

Traceback (most recent call last):
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xiaoduo/liu/Langchain-Chatchat-0.2.5/startup.py", line 367, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/xiaoduo/liu/Langchain-Chatchat-0.2.5/startup.py", line 195, in create_model_worker_app
    worker = ModelWorker(
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 221, in __init__
    self.model, self.tokenizer = load_model(
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 288, in load_model
    model, tokenizer = adapter.load_model(model_path, kwargs)
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 1167, in load_model
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/xiaoduo/.cache/huggingface/modules/transformers_modules/baichuan2/tokenization_baichuan.py", line 71, in __init__
    super().__init__(
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "/home/xiaoduo/miniconda3/envs/chat25/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/home/xiaoduo/.cache/huggingface/modules/transformers_modules/baichuan2/tokenization_baichuan.py", line 105, in get_vocab
    vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
  File "/home/xiaoduo/.cache/huggingface/modules/transformers_modules/baichuan2/tokenization_baichuan.py", line 101, in vocab_size
    return self.sp_model.get_piece_size()
AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'

**Comment by tanglu86** [comment]
同样的问题

**Comment by jessiewiswjc** [comment]
`transformers==4.33.1` and `tokenizers==0.13.3` work for me

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新的Transformers

**Comment by zhang-ning** [comment]
transformers-4.34.0 not work, but transformers-4.33.1 works

**Comment by BigPeng** [comment]
> transformers-4.34.0 not work, but transformers-4.33.1 works

改了后有效了

**Comment by Billzyf** [comment]
https://github.com/baichuan-inc/Baichuan2/issues/204
在baichuan的issue有不用修改环境的方法

**Comment by adrianJW421** [comment]
transformers-4.32.1 works
