### ISSUE TITLE
[BUG] Qianwen-14B 模型问答有问题

### ISSUE THREAD

**Issue by SnowyLchen** [chatchat-space/Langchain-Chatchat#1684]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52272752/2144e38a-4c60-4c93-9fb4-cb116fb8a3e0)

使用qianwen-14b模型，问答出现各种字符串，这是模型的问题吗？

**Comment by SnowyLchen** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52272752/416e0d2d-c98a-45e0-a7d4-283b9d931a10)
li连续问答有几率出现这个问题

**Comment by qihangf** [comment]
试试chat模型

**Comment by SnowyLchen** [comment]
> 试试chat模型

换chat模型了，正常了

**Comment by tonymhl** [comment]
本地加载Qwen-14B-Chat出现报错：
(langchain) mahongli@ops-NF5468M6:~/Langchain-Chatchat$ CUDA_VISIBLE_DEVICES=3 python startup.py --all-webui


==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.2.0-32-generic-x86_64-with-glibc2.35.
python版本：3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0]
项目版本：v0.2.5
langchain版本：0.0.310. fastchat版本：0.2.29


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-14B-Chat'] @ cuda
2023-10-09 14:26:02,003 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpqsry6ch4
2023-10-09 14:26:02,004 - instantiator.py[line:76] - INFO: Writing /tmp/tmpqsry6ch4/_remote_module_non_scriptable.py
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'model_path': 'Qwen-14B-Chat',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================


2023-10-09 14:26:02 | INFO | root | 正在启动服务：
2023-10-09 14:26:02 | INFO | root | 如需查看 llm_api 日志，请前往 /home/mahongli/Langchain-Chatchat/logs
2023-10-09 14:26:05,044 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp5b32_myz
2023-10-09 14:26:05,045 - instantiator.py[line:76] - INFO: Writing /tmp/tmp5b32_myz/_remote_module_non_scriptable.py
2023-10-09 14:26:08,423 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmprte124q3
2023-10-09 14:26:08,423 - instantiator.py[line:76] - INFO: Writing /tmp/tmprte124q3/_remote_module_non_scriptable.py
2023-10-09 14:26:08,432 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpise_owas
2023-10-09 14:26:08,432 - instantiator.py[line:76] - INFO: Writing /tmp/tmpise_owas/_remote_module_non_scriptable.py
2023-10-09 14:26:08,434 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpdd0uziwz
2023-10-09 14:26:08,434 - instantiator.py[line:76] - INFO: Writing /tmp/tmpdd0uziwz/_remote_module_non_scriptable.py
2023-10-09 14:26:08,438 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpqpltbzzn
2023-10-09 14:26:08,439 - instantiator.py[line:76] - INFO: Writing /tmp/tmpqpltbzzn/_remote_module_non_scriptable.py
2023-10-09 14:26:08,439 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp7z_zfayw
2023-10-09 14:26:08,439 - instantiator.py[line:76] - INFO: Writing /tmp/tmp7z_zfayw/_remote_module_non_scriptable.py
2023-10-09 14:26:08,456 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpkbiqkwgb
2023-10-09 14:26:08,456 - instantiator.py[line:76] - INFO: Writing /tmp/tmpkbiqkwgb/_remote_module_non_scriptable.py
2023-10-09 14:26:08,470 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpjq5qjbfo
2023-10-09 14:26:08,470 - instantiator.py[line:76] - INFO: Writing /tmp/tmpjq5qjbfo/_remote_module_non_scriptable.py
2023-10-09 14:26:08,483 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpnol3shmb
2023-10-09 14:26:08,484 - instantiator.py[line:76] - INFO: Writing /tmp/tmpnol3shmb/_remote_module_non_scriptable.py
2023-10-09 14:26:09 | ERROR | stderr | INFO:     Started server process [55464]
2023-10-09 14:26:09 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-09 14:26:09 | ERROR | stderr | INFO:     Application startup complete.
2023-10-09 14:26:09 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
INFO 10-09 14:26:09 llm_engine.py:72] Initializing an LLM engine with config: model='Qwen-14B-Chat', tokenizer='Qwen-14B-Chat', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=1, seed=0)
WARNING 10-09 14:26:10 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
2023-10-09 14:26:10 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 0
2023-10-09 14:26:10 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:2 to store for rank: 0
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 1 nodes.
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:3 to store for rank: 0
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:3 with 1 nodes.
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:4 to store for rank: 0
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:4 with 1 nodes.
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:5 to store for rank: 0
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:5 with 1 nodes.
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:6 to store for rank: 0
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:6 with 1 nodes.
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:7 to store for rank: 0
2023-10-09 14:26:15 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:7 with 1 nodes.
Process model_worker - Qwen-14B-Chat:
Traceback (most recent call last):
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mahongli/Langchain-Chatchat/startup.py", line 366, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/mahongli/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 442, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 250, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 279, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_workers(distributed_init_method)
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 134, in _init_workers
    self._run_workers(
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 678, in _run_workers
    output = executor(*args, **kwargs)
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/model_executor/model_loader.py", line 66, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/home/mahongli/anaconda3/envs/langchain/lib/python3.9/site-packages/vllm/model_executor/models/qwen.py", line 280, in load_weights
    loaded_weight = loaded_weight.view(3, total_num_heads,
RuntimeError: shape '[3, 32, 128]' is invalid for input of size 15360

**Comment by zRzRzRzRzRzRzR** [comment]
这个新的报错可以关注Qwen，这个Qwen的issue内有

**Comment by start-dzl** [comment]
可以给个链接吗，看了一下午没找到

**Comment by ShinyWey** [comment]
> 可以给个链接吗，看了一下午没找到

hhh, 我前段时间也是去Qwen的issue里找了一下午没找到😂

**Comment by start-dzl** [comment]
> > 可以给个链接吗，看了一下午没找到
> 
> hhh, 我前段时间也是去Qwen的issue里找了一下午没找到😂

chatchat 更新到0.26就行了

**Comment by ShinyWey** [comment]
> > > 可以给个链接吗，看了一下午没找到
> > 
> > 
> > hhh, 我前段时间也是去Qwen的issue里找了一下午没找到😂
> 
> chatchat 更新到0.26就行了

哈哈， 谢谢， 问题已经解决了
