### ISSUE TITLE
python startup.py -a 运行正常/Vscode通过F5 debug 出现AssertionError

### ISSUE THREAD

**Issue by yutianchen666** [chatchat-space/Langchain-Chatchat#1695]
**问题描述 / Problem Description**
通过F5 debug 项目，出现使用vpn时会出现的AssertionError bug，现象与https://github.com/chatchat-space/Langchain-Chatchat/issues/1517   一致
使用终端python startup.py -a正常运行
vscode debug出现错误

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' cd /home/yutianchen/code ; /usr/bin/env /home/yutianchen/.conda/envs/langchain-chat/bin/python /home/yutianchen/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 36835 -- /home/yutianchen/code/llm/Langchain-Chatchat-old/startup.py -a  '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:27<00:00,  3.88s/it] '...'
4. 问题出现 / Problem occurs
Process model_worker - chatglm2-6b:
Traceback (most recent call last):
  File "/home/yutianchen/.conda/envs/langchain-chat/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/yutianchen/.conda/envs/langchain-chat/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yutianchen/code/llm/Langchain-Chatchat-old/startup.py", line 304, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/yutianchen/code/llm/Langchain-Chatchat-old/startup.py", line 136, in create_model_worker_app
    worker = ModelWorker(
  File "/home/yutianchen/.conda/envs/langchain-chat/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 232, in __init__
    self.init_heart_beat()
  File "/home/yutianchen/code/llm/Langchain-Chatchat-old/startup.py", line 116, in _new_init_heart_beat
    self.register_to_controller()
  File "/home/yutianchen/.conda/envs/langchain-chat/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 113, in register_to_controller
    assert r.status_code == 200
AssertionError

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
2023-10-08 08:02:49,576 - instantiator.py[line:76] - INFO: Writing /tmp/tmpuq1e9t9d/_remote_module_non_scriptable.py
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:11<00:00,  1.64s/it]
INFO:     Started server process [3231816]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:6861 (Press CTRL+C to quit)

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
2023-10-08 08:33:55,660 - instantiator.py[line:76] - INFO: Writing /tmp/tmpzup6tzc2/_remote_module_non_scriptable.py
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:27<00:00,  3.88s/it]
Process model_worker - chatglm2-6b:
Traceback (most recent call last):
  File "/home/yutianchen/.conda/envs/langchain-chat/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/yutianchen/.conda/envs/langchain-chat/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yutianchen/code/llm/Langchain-Chatchat-old/startup.py", line 304, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/yutianchen/code/llm/Langchain-Chatchat-old/startup.py", line 136, in create_model_worker_app
    worker = ModelWorker(
  File "/home/yutianchen/.conda/envs/langchain-chat/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 232, in __init__
    self.init_heart_beat()
  File "/home/yutianchen/code/llm/Langchain-Chatchat-old/startup.py", line 116, in _new_init_heart_beat
    self.register_to_controller()
  File "/home/yutianchen/.conda/envs/langchain-chat/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 113, in register_to_controller
    assert r.status_code == 200
AssertionError

**环境信息 / Environment Information**

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-83-generic-x86_64-with-glibc2.35.
python版本：3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0]
项目版本：v0.2.4
langchain版本：0.0.287. fastchat版本：0.2.28

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ cuda
{'api_base_url': 'http://localhost:6888/v1',
 'api_key': 'EMPTY',
 'local_model_path': '/home/yutianchen/code/llm/model/chatglm2-6b'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
模型读入失败了或者你的联网模型配置不对，
另外，建议更新到最新版本，老版本没有维护

**Comment by Orion-Zheng** [comment]
我也遇到了同样的问题，使用了export no_proxy='$no_proxy,0.0.0.0'之后解决了，应该是之前服务器配置了代理，然后使用代理去访问0.0.0.0结果报错了，export no_proxy='$no_proxy,0.0.0.0'可以让0.0.0.0不走代理

**Comment by applepieiris** [comment]
> 模型读入失败了或者你的联网模型配置不对， 另外，建议更新到最新版本，老版本没有维护

不一定必须要配置联网模型吧？
