### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by liushifu12138** [chatchat-space/Langchain-Chatchat#1720]
Process model_worker - baichuan2-13b:
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/environment/miniconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/featurize/work/chat/Langchain-Chatchat-0.2.5/startup.py", line 366, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/featurize/work/chat/Langchain-Chatchat-0.2.5/startup.py", line 194, in create_model_worker_app
    worker = ModelWorker(
  File "/environment/miniconda3/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 242, in __init__
    self.init_heart_beat()
  File "/environment/miniconda3/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 101, in init_heart_beat
    self.register_to_controller()
  File "/environment/miniconda3/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 119, in register_to_controller
    assert r.status_code == 200
AssertionError

- langchain-ChatGLM 版本/commit 号：0.2.5
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): baichuan2-13b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:3.10

**Comment by YangQianli92** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/issues/1517  I referenced this, and the probable cause is the open proxy
