### ISSUE TITLE
[FEATURE] milvus版本较低

### ISSUE THREAD

**Issue by dayphosphor** [chatchat-space/Langchain-Chatchat#1722]
**功能描述 / Feature Description**
目前milvus版本是v2.1.3， 现在都v2.3.* ,   我尝试升级，但是代码会报错
INFO:     127.0.0.1:59276 - "POST /knowledge_base/create_knowledge_base HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/langchain-chatchat/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/local/Langchain-Chatchat/server/knowledge_base/kb_api.py", line 29, in create_kb
    kb = KBServiceFactory.get_service(knowledge_base_name, vector_store_type, embed_model)
  File "/home/local/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 237, in get_service
    vector_store_type = getattr(SupportedVSType, vector_store_type.upper())
AttributeError: type object 'SupportedVSType' has no attribute 'MILIVUS'

**Comment by ilovesouthpark** [comment]
milvus lite还是可以升级到2.2.4，升级不了2.3.0及以上，不知道为啥，
