### ISSUE TITLE
[BUG] 简洁阐述问题 / OSError: [Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by great-wind** [chatchat-space/Langchain-Chatchat#1727]
**问题描述 / Problem Description**
使用`python startup.py --all-webui`命令启动服务时，出现以下错误：

```
Traceback (most recent call last):
  File "/home/root/anaconda3/envs/langchain-chatchat/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/web/cli.py", line 233, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/web/cli.py", line 269, in _main_run
    bootstrap.run(file, command_line, args, flag_options)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/web/bootstrap.py", line 411, in run
    _install_pages_watcher(main_script_path)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/web/bootstrap.py", line 386, in _install_pages_watcher
    watch_dir(
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/watcher/path_watcher.py", line 153, in watch_dir
    return _watch_path(
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/watcher/path_watcher.py", line 128, in _watch_path
    watcher_class(
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/watcher/event_based_path_watcher.py", line 92, in __init__
    path_watcher.watch_path(
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/watcher/event_based_path_watcher.py", line 170, in watch_path
    folder_handler.watch = self._observer.schedule(
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/api.py", line 301, in schedule
    emitter.start()
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 92, in start
    self.on_thread_start()
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 179, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 402, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
    Inotify._raise_error()
  File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 428, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：拉取master分支
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：ChatGLM2-6B-int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本: centos7
- Python 版本: python3.8.18

请问是什么原因导致的该问题？

**Comment by alexxchen** [comment]
3.10.9同样遇到这个问题

**Comment by hzg0601** [comment]
百度 inotify watch limit reached

**Comment by dereksjtu** [comment]
cat /proc/sys/fs/inotify/max_user_watches  # 默认应该是 8192
echo 81920 > /proc/sys/fs/inotify/max_user_watches

**Comment by FelixZhang7** [comment]
> **问题描述 / Problem Description** 使用`python startup.py --all-webui`命令启动服务时，出现以下错误：
> 
> ```
> Traceback (most recent call last):
>   File "/home/root/anaconda3/envs/langchain-chatchat/bin/streamlit", line 8, in <module>
>     sys.exit(main())
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/web/cli.py", line 233, in main_run
>     _main_run(target, args, flag_options=kwargs)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/web/cli.py", line 269, in _main_run
>     bootstrap.run(file, command_line, args, flag_options)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/web/bootstrap.py", line 411, in run
>     _install_pages_watcher(main_script_path)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/web/bootstrap.py", line 386, in _install_pages_watcher
>     watch_dir(
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/watcher/path_watcher.py", line 153, in watch_dir
>     return _watch_path(
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/watcher/path_watcher.py", line 128, in _watch_path
>     watcher_class(
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/watcher/event_based_path_watcher.py", line 92, in __init__
>     path_watcher.watch_path(
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/streamlit/watcher/event_based_path_watcher.py", line 170, in watch_path
>     folder_handler.watch = self._observer.schedule(
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/api.py", line 301, in schedule
>     emitter.start()
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 92, in start
>     self.on_thread_start()
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
>     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
>     self._inotify = Inotify(path, recursive)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 179, in __init__
>     self._add_dir_watch(path, recursive, event_mask)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 402, in _add_dir_watch
>     self._add_watch(full_path, mask)
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
>     Inotify._raise_error()
>   File "/home/root/anaconda3/envs/langchain-chatchat/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 428, in _raise_error
>     raise OSError(errno.ENOSPC, "inotify watch limit reached")
> OSError: [Errno 28] inotify watch limit reached
> ```
> 
> **环境信息 / Environment Information**
> 
> * langchain-ChatGLM 版本/commit 号：拉取master分支
> * 是否使用 Docker 部署（是/否）：否
> * 使用的模型：ChatGLM2-6B-int4
> * 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
> * 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
> * 操作系统及版本: centos7
> * Python 版本: python3.8.18
> 
> 请问是什么原因导致的该问题？

请问您解决了吗，是怎么解决的呢？

**Comment by great-wind** [comment]
`cat /proc/sys/fs/inotify/max_user_watches`，该命令会输出一个值，该值过小导致出现`inotify watch limit reached`问题；
运行`echo 99999 > /proc/sys/fs/inotify/max_user_watches`将限制值扩大，即可解决
