### ISSUE TITLE
[BUG] 对话知识库经常出现Uncaught app exception

### ISSUE THREAD

**Issue by leoterry-ulrica** [chatchat-space/Langchain-Chatchat#1732]
问题描述 / Problem Description
对话知识库经常出现Uncaught app exception
错误信息：
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
{'answer': '，'}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
2023-10-11 10:00:08.756 Uncaught app exception
Traceback (most recent call last):
  File "/mnt/anaconda3/envs/python3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/mnt/llm/Langchain-Chatchat/webui.py", line 118, in <module>
    pages[selected_page]["func"](api)
  File "/mnt/llm/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 228, in dialogue_page
    chat_box.update_msg(text, element_index=0)
  File "/mnt/anaconda3/envs/python3.10/lib/python3.10/site-packages/streamlit_chatbox/messages.py", line 318, in update_msg
    self.init_session()
  File "/mnt/anaconda3/envs/python3.10/lib/python3.10/site-packages/streamlit_chatbox/messages.py", line 48, in init_session
    self.reset_history(self._chat_name)
  File "/mnt/anaconda3/envs/python3.10/lib/python3.10/site-packages/streamlit_chatbox/messages.py", line 55, in reset_history
    st.session_state[self._session_key][name] = []
  File "/mnt/anaconda3/envs/python3.10/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
  File "/mnt/anaconda3/envs/python3.10/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 111, in __getitem__
    raise KeyError(key)

环境信息 / Environment Information

langchain-ChatGLM 版本/commit 号：v0.2.5
是否使用 Docker 部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B-32k
使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: Ubuntu
Python 版本 / Python version: python3.10

**Comment by leoterry-ulrica** [comment]
@imClumsyPanda 请问能从哪些方面进行排查？

**Comment by liunux4odoo** [comment]
首先，确认已经按requirements更新了所有依赖
其次，把当前控制台关掉，重新启动一个虚拟环境再运行试试
