### ISSUE TITLE
[BUG] 求助llm对话报错

### ISSUE THREAD

**Issue by yueyann** [chatchat-space/Langchain-Chatchat#1743]
对话和知识库问答模式问了问题之后报错，切换0.2.4和0.2.5版本也是一样的问题。基本都是默认设置，没怎么改动。

```
python版本：3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.4
langchain版本：0.0.310. fastchat版本：0.2.29


当前使用的分词器：ChineseTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ cpu
{'device': 'cpu',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'E:\\chatchat\\github\\models\\chatglm-6b',
 'port': 20002}
当前Embbedings模型： m3e-base @ cpu

报错如下：

received input message:
{'history': [],
 'knowledge_base_name': 'samples',
 'local_doc_url': False,
 'model_name': 'chatglm2-6b',
 'prompt_name': 'knowledge_base_chat',
 'query': '你好',
 'score_threshold': 1.0,
 'stream': True,
 'temperature': 0.7,
 'top_k': 3}
INFO:     127.0.0.1:59211 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
2023-10-12 15:30:09 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
2023-10-12 15:30:15 | INFO | sentence_transformers.SentenceTransformer | Load pretrained SentenceTransformer: E:\chatchat\aliendao-main\dataroot\models\moka-ai\m3e-base
2023-10-12 15:30:39 | INFO | root | loading vector store in 'samples/vector_store' from disk.
{'kb_name': 'samples', 'vs_type': 'faiss', 'embed_model': 'm3e-base', 'file_count': 1, 'create_time': datetime.datetime(2023, 10, 11, 9, 2, 2)}
2023-10-12 15:30:39 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-10-12 15:30:39 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-10-12 15:30:39 | INFO | faiss.loader | Loading faiss.
2023-10-12 15:30:39 | INFO | faiss.loader | Successfully loaded faiss.
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
2023-10-12 15:30:46 | INFO | stdout | INFO:     127.0.0.1:59227 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-10-12 15:30:46 | INFO | openai | message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None request_id=None response_code=200
2023-10-12 15:30:47 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2023-10-12 15:32:30 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-10-12 15:32:30 | ERROR | stderr | Traceback (most recent call last):
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_backends\anyio.py", line 34, in read
2023-10-12 15:32:30 | ERROR | stderr |     return await self._stream.receive(max_bytes=max_bytes)
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 1203, in receive
2023-10-12 15:32:30 | ERROR | stderr |     await self._protocol.read_event.wait()
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\asyncio\locks.py", line 213, in wait
2023-10-12 15:32:30 | ERROR | stderr |     await fut
2023-10-12 15:32:30 | ERROR | stderr | asyncio.exceptions.CancelledError
2023-10-12 15:32:30 | ERROR | stderr |
2023-10-12 15:32:30 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-10-12 15:32:30 | ERROR | stderr |
2023-10-12 15:32:30 | ERROR | stderr | Traceback (most recent call last):
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
2023-10-12 15:32:30 | ERROR | stderr |     yield
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
2023-10-12 15:32:30 | ERROR | stderr |     with anyio.fail_after(timeout):
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\anyio\_core\_tasks.py", line 119, in __exit__
2023-10-12 15:32:30 | ERROR | stderr |     raise TimeoutError
2023-10-12 15:32:30 | ERROR | stderr | TimeoutError
2023-10-12 15:32:30 | ERROR | stderr |
2023-10-12 15:32:30 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-10-12 15:32:30 | ERROR | stderr |
2023-10-12 15:32:30 | ERROR | stderr | Traceback (most recent call last):
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
2023-10-12 15:32:30 | ERROR | stderr |     yield
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpx\_transports\default.py", line 239, in __aiter__
2023-10-12 15:32:30 | ERROR | stderr |     async for part in self._httpcore_stream:
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\connection_pool.py", line 347, in __aiter__
2023-10-12 15:32:30 | ERROR | stderr |     async for part in self._stream:
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 325, in __aiter__
2023-10-12 15:32:30 | ERROR | stderr |     raise exc
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 317, in __aiter__
2023-10-12 15:32:30 | ERROR | stderr |     async for chunk in self._connection._receive_response_body(**kwargs):
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_body
2023-10-12 15:32:30 | ERROR | stderr |     event = await self._receive_event(timeout=timeout)
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 200, in _receive_event
2023-10-12 15:32:30 | ERROR | stderr |     data = await self._network_stream.read(
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_backends\anyio.py", line 31, in read
2023-10-12 15:32:30 | ERROR | stderr |     with map_exceptions(exc_map):
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\contextlib.py", line 153, in __exit__
2023-10-12 15:32:30 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2023-10-12 15:32:30 | ERROR | stderr |   File "F:\apps\Anaconda3\envs\chatchat\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
2023-10-12 15:32:30 | ERROR | stderr |     raise to_exc(exc) from exc
2023-10-12 15:32:30 | ERROR | stderr | httpcore.ReadTimeout
```

**Comment by liunux4odoo** [comment]
你这个langchain的版本过高了，按照requirements里面的版本更新依赖。另外可以把httpx_timeout调高一些试试。

**Comment by yueyann** [comment]
> 你这个langchain的版本过高了，按照requirements里面的版本更新依赖。另外可以把httpx_timeout调高一些试试。

langchain版本降低到0.0.304，timeout设置了600，但还是报了一样的错

**Comment by liunux4odoo** [comment]
> > 你这个langchain的版本过高了，按照requirements里面的版本更新依赖。另外可以把httpx_timeout调高一些试试。
> 
> langchain版本降低到0.0.304，timeout设置了600，但还是报了一样的错

0.2.4的requirements里langchain==0.0.287

**Comment by yueyann** [comment]
哦哦不好意思，换回了0.2.5，langchain版本降低到0.2.4，还是继续报错

**Comment by uchihayou** [comment]
我也遇到这个问题了，mark一下，等大佬

**Comment by guanyuwl** [comment]
知识库能回答，但是会有空白，后台会报同样的错误，langchain = 0.0.319
