### ISSUE TITLE
启动服务报错，AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by xbsdsongnan** [chatchat-space/Langchain-Chatchat#1748]
Process model_worker - chatglm-6b-int4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Langchain-Chatchat/startup.py", line 366, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/Langchain-Chatchat/startup.py", line 194, in create_model_worker_app
    worker = ModelWorker(
  File "/usr/local/lib/python3.8/dist-packages/fastchat/serve/model_worker.py", line 210, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/fastchat/serve/model_worker.py", line 84, in __init__
    if model_path.endswith("/"):
AttributeError: 'NoneType' object has no attribute 'endswith'
2023-10-13 04:19:00 | ERROR | stderr | INFO:     Started server process [214]
2023-10-13 04:19:00 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-13 04:19:00 | ERROR | stderr | INFO:     Application startup complete.
2023-10-13 04:19:00 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
^C2023-10-13 04:19:46 | WARNING | root | Sending SIGKILL to {'fangzhou-api': <Process name='api_worker - fangzhou-api (216)' pid=216 parent=100 started daemon>, 'zhipu-api': <Process name='api_worker - zhipu-api (217)' pid=217 parent=100 started daemon>, 'xinghuo-api': <Process name='api_worker - xinghuo-api (218)' pid=218 parent=100 started daemon>, 'qwen-api': <Process name='api_worker - qwen-api (219)' pid=219 parent=100 started daemon>, 'minimax-api': <Process name='api_worker - minimax-api (220)' pid=220 parent=100 started daemon>, 'qianfan-api': <Process name='api_worker - qianfan-api (221)' pid=221 parent=100 started daemon>}
2023-10-13 04:19:46 | WARNING | root | Sending SIGKILL to {'chatglm-6b-int4': <Process name='model_worker - chatglm-6b-int4 (215)' pid=215 parent=100 stopped exitcode=1 daemon>}
2023-10-13 04:19:46 | WARNING | root | Sending SIGKILL to <Process name='controller (183)' pid=183 parent=100 started daemon>
2023-10-13 04:19:46 | WARNING | root | Sending SIGKILL to <Process name='openai_api (214)' pid=214 parent=100 started daemon>
2023-10-13 04:19:46 | WARNING | root | Sending SIGKILL to <Process name='API Server' parent=100 initial daemon>

**Comment by liunux4odoo** [comment]
把控制台输出的配置信息贴上来

**Comment by 1249815869** [comment]
我也遇到了同样的问题，报错如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/65490763/9e7247e6-2c35-4d07-be37-92ac05dc9cd1)

**Comment by 1249815869** [comment]
仔细检查一下配置有没有写对，检查红框里显示的是否是你的模型路径
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/65490763/3a0699d7-4688-4549-8578-665f3cbfa71b)

**Comment by xbsdsongnan** [comment]
已解决，是模型加载错了
