### ISSUE TITLE
加载Qwen-14B-Chat-Int4模型报错

### ISSUE THREAD

**Issue by yubeier** [chatchat-space/Langchain-Chatchat#1753]
Process model_worker - Qwen-14B-Chat-Int4:
Traceback (most recent call last):
  File "D:\soft\anaconda3\envs\chatchat\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\soft\anaconda3\envs\chatchat\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\chatGPT\Langchain-Chatchat\startup.py", line 366, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "D:\chatGPT\Langchain-Chatchat\startup.py", line 194, in create_model_worker_app
    worker = ModelWorker(
  File "D:\soft\anaconda3\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 221, in __init__
    self.model, self.tokenizer = load_model(
  File "D:\soft\anaconda3\envs\chatchat\lib\site-packages\fastchat\model\model_adapter.py", line 288, in load_model
    model, tokenizer = adapter.load_model(model_path, kwargs)
  File "D:\soft\anaconda3\envs\chatchat\lib\site-packages\fastchat\model\model_adapter.py", line 1368, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "D:\soft\anaconda3\envs\chatchat\lib\site-packages\transformers\models\auto\auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "D:\soft\anaconda3\envs\chatchat\lib\site-packages\transformers\modeling_utils.py", line 3250, in from_pretrained
    model = quantizer.post_init_model(model)
  File "D:\soft\anaconda3\envs\chatchat\lib\site-packages\optimum\gptq\quantizer.py", line 482, in post_init_model
    raise ValueError(
ValueError: Found modules on cpu/disk. Using Exllama backend requires all the modules to be on GPU.You can deactivate exllama backend by setting `disable_exllama=True` in the quantization config object

**Comment by ShinyWey** [comment]
the same situation before

**Comment by Orion-zhen** [comment]
similar error with ubuntu23.04, python3.11, loading qwen-chat-14b-int4 with command `python startup.py -a`
error message is listed below
```
Process model_worker - Qwen-14B-Chat:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/orion/share/ai/langchain-Chatchat/startup.py", line 366, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orion/share/ai/langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    engine = AsyncLLMEngine.from_engine_args(engine_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 442, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 250, in __init__
    self.engine = self._init_engine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 279, in _init_engine
    return engine_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_workers(distributed_init_method)
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 134, in _init_workers
    self._run_workers(
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 678, in _run_workers
    output = executor(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/model_executor/model_loader.py", line 66, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/home/orion/share/ai/langchain-Chatchat/.venv/lib/python3.11/site-packages/vllm/model_executor/models/qwen.py", line 302, in load_weights
    param = state_dict[name]
            ~~~~~~~~~~^^^^^^
KeyError: 'transformer.h.15.mlp.c_proj.bias'
```

**Comment by zRzRzRzRzRzRzR** [comment]
qwen的issue内有这个问题的解决办法，去那边看一下

**Comment by zhanghui-china** [comment]
查了一下，这个 [https://github.com/QwenLM/Qwen/issues/385](url) 比较详细。

**Comment by zhanghui-china** [comment]
实际上在原模型的config.json中增加 "disable_exllama": true 即可
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/b7141edc-a9ef-4e49-a34e-2a26d2445a9e)

**Comment by zhanghui-china** [comment]
实际上在原模型的config.json中增加 "disable_exllama": true 即可
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/b7141edc-a9ef-4e49-a34e-2a26d2445a9e)

**Comment by hiddenblue** [comment]
还有一种可能是缺少了autu-gptq这个包，可能需要pip安装才行，用qwen 1.5 32 int gptq遇到的
