### ISSUE TITLE
[BUG] 部署后加载启动出现错误

### ISSUE THREAD

**Issue by Guanchaofeng** [chatchat-space/Langchain-Chatchat#1756]
```
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-73-generic-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
项目版本：v0.2.5
langchain版本：0.0.278. fastchat版本：0.2.31


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ cuda
2023-10-14 22:57:20,658 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpao9y5yhe
2023-10-14 22:57:20,659 - instantiator.py[line:76] - INFO: Writing /tmp/tmpao9y5yhe/_remote_module_non_scriptable.py
[2023-10-14 22:57:21,361] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'model_path': '/data/LLMs/chatglm2-6b',
 'port': 20013}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================


2023-10-14 22:57:21 | INFO | root | 正在启动服务：
2023-10-14 22:57:21 | INFO | root | 如需查看 llm_api 日志，请前往 /data/Langchain-Chatchat/logs
2023-10-14 22:57:24,764 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpe8wysk41
2023-10-14 22:57:24,764 - instantiator.py[line:76] - INFO: Writing /tmp/tmpe8wysk41/_remote_module_non_scriptable.py
[2023-10-14 22:57:25,410] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-10-14 22:57:29,959 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpem2gjd5k
2023-10-14 22:57:29,960 - instantiator.py[line:76] - INFO: Writing /tmp/tmpem2gjd5k/_remote_module_non_scriptable.py
2023-10-14 22:57:30,046 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpvaay6lkw
2023-10-14 22:57:30,048 - instantiator.py[line:76] - INFO: Writing /tmp/tmpvaay6lkw/_remote_module_non_scriptable.py
2023-10-14 22:57:30,221 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp77ns3eo8
2023-10-14 22:57:30,222 - instantiator.py[line:76] - INFO: Writing /tmp/tmp77ns3eo8/_remote_module_non_scriptable.py
2023-10-14 22:57:30,275 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpp_w_9sne
2023-10-14 22:57:30,275 - instantiator.py[line:76] - INFO: Writing /tmp/tmpp_w_9sne/_remote_module_non_scriptable.py
2023-10-14 22:57:30,286 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp2xbbvnvp
2023-10-14 22:57:30,287 - instantiator.py[line:76] - INFO: Writing /tmp/tmp2xbbvnvp/_remote_module_non_scriptable.py
2023-10-14 22:57:30,315 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp48f9620w
2023-10-14 22:57:30,315 - instantiator.py[line:76] - INFO: Writing /tmp/tmp48f9620w/_remote_module_non_scriptable.py
2023-10-14 22:57:30,320 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpl65_oxfw
2023-10-14 22:57:30,321 - instantiator.py[line:76] - INFO: Writing /tmp/tmpl65_oxfw/_remote_module_non_scriptable.py
2023-10-14 22:57:30,341 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmprtoufet1
2023-10-14 22:57:30,341 - instantiator.py[line:76] - INFO: Writing /tmp/tmprtoufet1/_remote_module_non_scriptable.py
[2023-10-14 22:57:30,698] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-14 22:57:30,808] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-14 22:57:30,995] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-10-14 22:57:31 | INFO | model_worker | Register to controller
2023-10-14 22:57:31 | ERROR | stderr | Process api_worker - minimax-api:
2023-10-14 22:57:31 | ERROR | stderr | Traceback (most recent call last):
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-10-14 22:57:31 | ERROR | stderr |     self.run()
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-10-14 22:57:31 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 366, in run_model_worker
2023-10-14 22:57:31 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 92, in create_model_worker_app
2023-10-14 22:57:31 | ERROR | stderr |     worker = worker_class(model_names=args.model_names,
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/minimax.py", line 23, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     super().__init__(**kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     self.init_heart_beat()
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 69, in init_heart_beat
2023-10-14 22:57:31 | ERROR | stderr |     target=fastchat.serve.model_worker.heart_beat_worker, args=(self,), daemon=True,
2023-10-14 22:57:31 | ERROR | stderr | AttributeError: module 'fastchat.serve.model_worker' has no attribute 'heart_beat_worker'
[2023-10-14 22:57:31,033] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-14 22:57:31,051] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-14 22:57:31,065] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-14 22:57:31,088] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-10-14 22:57:31 | INFO | model_worker | Register to controller
[2023-10-14 22:57:31,116] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-10-14 22:57:31 | ERROR | stderr | Process api_worker - qianfan-api:
2023-10-14 22:57:31 | ERROR | stderr | Traceback (most recent call last):
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-10-14 22:57:31 | ERROR | stderr |     self.run()
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-10-14 22:57:31 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 366, in run_model_worker
2023-10-14 22:57:31 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 92, in create_model_worker_app
2023-10-14 22:57:31 | ERROR | stderr |     worker = worker_class(model_names=args.model_names,
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/qianfan.py", line 121, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     super().__init__(**kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     self.init_heart_beat()
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 69, in init_heart_beat
2023-10-14 22:57:31 | ERROR | stderr |     target=fastchat.serve.model_worker.heart_beat_worker, args=(self,), daemon=True,
2023-10-14 22:57:31 | ERROR | stderr | AttributeError: module 'fastchat.serve.model_worker' has no attribute 'heart_beat_worker'
2023-10-14 22:57:31 | INFO | model_worker | Register to controller
2023-10-14 22:57:31 | ERROR | stderr | Process api_worker - qwen-api:
2023-10-14 22:57:31 | ERROR | stderr | Traceback (most recent call last):
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-10-14 22:57:31 | ERROR | stderr |     self.run()
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-10-14 22:57:31 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 366, in run_model_worker
2023-10-14 22:57:31 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 92, in create_model_worker_app
2023-10-14 22:57:31 | ERROR | stderr |     worker = worker_class(model_names=args.model_names,
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/qwen.py", line 69, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     super().__init__(**kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     self.init_heart_beat()
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 69, in init_heart_beat
2023-10-14 22:57:31 | ERROR | stderr |     target=fastchat.serve.model_worker.heart_beat_worker, args=(self,), daemon=True,
2023-10-14 22:57:31 | ERROR | stderr | AttributeError: module 'fastchat.serve.model_worker' has no attribute 'heart_beat_worker'
2023-10-14 22:57:31 | INFO | model_worker | Register to controller
2023-10-14 22:57:31 | ERROR | stderr | Process api_worker - fangzhou-api:
2023-10-14 22:57:31 | ERROR | stderr | Traceback (most recent call last):
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-10-14 22:57:31 | ERROR | stderr |     self.run()
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-10-14 22:57:31 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 366, in run_model_worker
2023-10-14 22:57:31 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 92, in create_model_worker_app
2023-10-14 22:57:31 | ERROR | stderr |     worker = worker_class(model_names=args.model_names,
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/fangzhou.py", line 70, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     super().__init__(**kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     self.init_heart_beat()
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 69, in init_heart_beat
2023-10-14 22:57:31 | ERROR | stderr |     target=fastchat.serve.model_worker.heart_beat_worker, args=(self,), daemon=True,
2023-10-14 22:57:31 | ERROR | stderr | AttributeError: module 'fastchat.serve.model_worker' has no attribute 'heart_beat_worker'
2023-10-14 22:57:31 | INFO | model_worker | Register to controller
2023-10-14 22:57:31 | ERROR | stderr | Process api_worker - xinghuo-api:
2023-10-14 22:57:31 | ERROR | stderr | Traceback (most recent call last):
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-10-14 22:57:31 | ERROR | stderr |     self.run()
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-10-14 22:57:31 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 366, in run_model_worker
2023-10-14 22:57:31 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 92, in create_model_worker_app
2023-10-14 22:57:31 | ERROR | stderr |     worker = worker_class(model_names=args.model_names,
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/xinghuo.py", line 39, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     super().__init__(**kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     self.init_heart_beat()
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 69, in init_heart_beat
2023-10-14 22:57:31 | ERROR | stderr |     target=fastchat.serve.model_worker.heart_beat_worker, args=(self,), daemon=True,
2023-10-14 22:57:31 | ERROR | stderr | AttributeError: module 'fastchat.serve.model_worker' has no attribute 'heart_beat_worker'
2023-10-14 22:57:31 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 93cd8b62 ...
2023-10-14 22:57:31 | ERROR | stderr | INFO:     Started server process [2168493]
2023-10-14 22:57:31 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-14 22:57:31 | ERROR | stderr | INFO:     Application startup complete.
2023-10-14 22:57:31 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20012 (Press CTRL+C to quit)
2023-10-14 22:57:31 | INFO | model_worker | Register to controller
2023-10-14 22:57:31 | ERROR | stderr | Process api_worker - zhipu-api:
2023-10-14 22:57:31 | ERROR | stderr | Traceback (most recent call last):
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-10-14 22:57:31 | ERROR | stderr |     self.run()
2023-10-14 22:57:31 | ERROR | stderr |   File "/root/miniconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-10-14 22:57:31 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 366, in run_model_worker
2023-10-14 22:57:31 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/startup.py", line 92, in create_model_worker_app
2023-10-14 22:57:31 | ERROR | stderr |     worker = worker_class(model_names=args.model_names,
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/zhipu.py", line 23, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     super().__init__(**kwargs)
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 43, in __init__
2023-10-14 22:57:31 | ERROR | stderr |     self.init_heart_beat()
2023-10-14 22:57:31 | ERROR | stderr |   File "/data/Langchain-Chatchat/server/model_workers/base.py", line 69, in init_heart_beat
2023-10-14 22:57:31 | ERROR | stderr |     target=fastchat.serve.model_worker.heart_beat_worker, args=(self,), daemon=True,
2023-10-14 22:57:31 | ERROR | stderr | AttributeError: module 'fastchat.serve.model_worker' has no attribute 'heart_beat_worker'
Loading checkpoint shards:   0%|                                                                                 | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|██████████▍                                                              | 1/7 [00:01<00:09,  1.64s/it]
Loading checkpoint shards:  29%|████████████████████▊                                                    | 2/7 [00:03<00:07,  1.48s/it]
Loading checkpoint shards:  43%|███████████████████████████████▎                                         | 3/7 [00:04<00:05,  1.42s/it]
Loading checkpoint shards:  57%|█████████████████████████████████████████▋                               | 4/7 [00:05<00:04,  1.36s/it]
Loading checkpoint shards:  71%|████████████████████████████████████████████████████▏                    | 5/7 [00:06<00:02,  1.36s/it]
Loading checkpoint shards:  86%|██████████████████████████████████████████████████████████████▌          | 6/7 [00:08<00:01,  1.35s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.17s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.30s/it]
2023-10-14 22:57:40 | ERROR | stderr | 
2023-10-14 22:57:45 | INFO | model_worker | Register to controller
2023-10-14 22:58:30 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: 93cd8b62. 
2023-10-14 22:59:15 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: 93cd8b62.
```

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.5版本依赖要重装，按照Requirements的全部重装
