### ISSUE TITLE
[BUG] OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

### ISSUE THREAD

**Issue by zhanghui-china** [chatchat-space/Langchain-Chatchat#1759]
**问题描述 / Problem Description**
windows 11 GPU：
python startup.py --all-webui 
启动后报
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

**复现问题的步骤 / Steps to Reproduce**
依赖都已经安装完毕。
本地知识库也初始化完毕
`(chatchat) PS D:\Langchain-Chatchat> python init_database.py --recreate-vs
database talbes reseted
recreating all vector stores
2023-10-15 19:17:48,706 - faiss_cache.py[line:75] - INFO: loading vector store in 'samples/vector_store' from disk.
{}
2023-10-15 19:17:48,832 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: D:\Langchain-Chatchat\models\moka-ai\m3e-base
2023-10-15 19:17:50,110 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-10-15 19:17:50,110 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-10-15 19:17:50,110 - loader.py[line:64] - INFO: Loading faiss.
2023-10-15 19:17:50,137 - loader.py[line:66] - INFO: Successfully loaded faiss.
2023-10-15 19:17:50,164 - utils.py[line:289] - INFO: UnstructuredFileLoader used for D:\Langchain-Chatchat\knowledge_base\samples\content\test.txt
2023-10-15 19:17:53,441 - utils.py[line:148] - INFO: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-10-15 19:17:53,441 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))"), '(Request ID: bfb8261b-6b15-4d41-b9df-767bfdb73116)')
文档切分示例：page_content='ChatGPT是OpenAI开发的一个大型语言模型，可以提供各种主题的信息，\n\n# 如何向 ChatGPT 提问以获得高质量答案：提示技巧工程完全指南\n\n## 介绍\n\n我很高兴欢 迎您阅读我的最新书籍《The Art of Asking ChatGPT for High-Quality Answers: A complete Guide to Prompt Engineering Techniques》。本书是一本全面指南，介绍了各种提示技术，用于从ChatGPT中生成高质量的答案。' metadata={'source': 'D:\\Langchain-Chatchat\\knowledge_base\\samples\\content\\test.txt'}
正在将 samples/test.txt 添加到向量库，共包含83条文档`
`2023-10-15 19:18:01,713 - faiss_cache.py[line:20] - INFO: 已将向量库 ('samples', 'vector_store') 保存到磁盘
总计用时： 0:00:13.207255`

执行 2023-10-15 19:18:01,713 - faiss_cache.py[line:20] - INFO: 已将向量库 ('samples', 'vector_store') 保存到磁盘
总计用时： 0:00:13.207255

**预期的结果 / Expected Result**
启动web服务成功。

**实际结果 / Actual Result**
`(chatchat) PS D:\Langchain-Chatchat> python startup.py --all-webui

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.23555-SP0.
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.5
langchain版本：0.0.314. fastchat版本：0.2.29

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'D:\\ChatGLM2-6B\\THUDM\\chatglm2-6b',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-10-15 19:18:56 | INFO | root | 正在启动服务：
2023-10-15 19:18:56 | INFO | root | 如需查看 llm_api 日志，请前往 D:\Langchain-Chatchat\logs
2023-10-15 19:19:02 | ERROR | stderr | INFO:     Started server process [9036]
2023-10-15 19:19:02 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-15 19:19:02 | ERROR | stderr | INFO:     Application startup complete.
2023-10-15 19:19:02 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:12<00:00,  1.80s/it]
Process model_worker - chatglm2-6b:
Traceback (most recent call last):
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "L:\Anaconda\envs\chatchat\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "L:\Anaconda\envs\chatchat\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "L:\Anaconda\envs\chatchat\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "L:\Anaconda\envs\chatchat\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "L:\Anaconda\envs\chatchat\lib\http\client.py", line 976, in send
    self.connect()
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000254FFC89930>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\Anaconda\envs\chatchat\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "L:\Anaconda\envs\chatchat\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000254FFC89930>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\Anaconda\envs\chatchat\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "L:\Anaconda\envs\chatchat\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Langchain-Chatchat\startup.py", line 366, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "D:\Langchain-Chatchat\startup.py", line 194, in create_model_worker_app
    worker = ModelWorker(
  File "L:\Anaconda\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 242, in __init__
    self.init_heart_beat()
  File "L:\Anaconda\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 101, in init_heart_beat
    self.register_to_controller()
  File "L:\Anaconda\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 118, in register_to_controller
    r = requests.post(url, json=data)
  File "L:\Anaconda\envs\chatchat\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "L:\Anaconda\envs\chatchat\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "L:\Anaconda\envs\chatchat\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "L:\Anaconda\envs\chatchat\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "L:\Anaconda\envs\chatchat\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000254FFC89930>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))`
![af2b92520d6b66e50061da73c7296ef](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/6eb76b09-f5cb-4ffa-9750-41f54e6d686d)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:Windows 11 
- Python 版本 / Python version:Python 3.10.13
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
windows 不要用0.0.0.0 用127.0.0.1

**Comment by tommickey2020** [comment]
用'chatglm2-6b-32k-int4'模型，即使服务器IP更改还是会有这个错误。OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

2023-10-22 22:08:21 | INFO | model_worker | Loading the model ['chatglm2-6b-32k-int4'] on worker 1c496e00 ...
2023-10-22 22:08:44 | WARNING | transformers_modules.chatglm2-6b-32k-int4.quantization | Load parallel cpu kernel failed C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\chatglm2-6b-32k-int4\quantization_kernels_parallel.so: Traceback (most recent call last):
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm2-6b-32k-int4\quantization.py", line 148, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "D:\server\miniconda3-win64\envs\king6\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "D:\server\miniconda3-win64\envs\king6\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
