### ISSUE TITLE
ImportError: libcudart.so.11.0

### ISSUE THREAD

**Issue by ShinyWey** [chatchat-space/Langchain-Chatchat#1788]
**问题描述 / Problem Description**
看样子是cuda版本的问题, 但我换了122和118都试了, 都有报错

**复现问题的步骤 / Steps to Reproduce**
看着教程一步步来的, 之前在云服务器上跑过很多次一直没问题, 这次用公司的服务器, 具体是执行到python startup.py -a报的错

**实际结果 / Actual Result**
2023-10-18 17:06:19 | ERROR | stderr | INFO:     Started server process [15778]
2023-10-18 17:06:19 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-18 17:06:19 | ERROR | stderr | INFO:     Application startup complete.
2023-10-18 17:06:19 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000/ (Press CTRL+C to quit)
INFO 10-18 17:06:19 llm_engine.py:72] Initializing an LLM engine with config: model='/home/hello2ai/model/llm/qwen/Qwen-14B-Chat', tokenizer='/home/hello2ai/model/llm/qwen/Qwen-14B-Chat', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=1, seed=0)
WARNING 10-18 17:06:20 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Process model_worker - Qwen-14B-Chat:
Traceback (most recent call last):
File "/root/anaconda3/envs/qw/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/root/anaconda3/envs/qw/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/home/hello2ai/Langchain-Chatchat-v0.0.1/startup.py", line 366, in run_model_worker
app = create_model_worker_app(log_level=log_level, **kwargs)
File "/home/hello2ai/Langchain-Chatchat-v0.0.1/startup.py", line 135, in create_model_worker_app
engine = AsyncLLMEngine.from_engine_args(engine_args)
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 442, in from_engine_args
engine = cls(engine_args.worker_use_ray,
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 250, in init
self.engine = self._init_engine(*args, **kwargs)
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 279, in _init_engine
return engine_class(*args, **kwargs)
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 102, in init
self._init_workers(distributed_init_method)
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 120, in _init_workers
from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/worker/worker.py", line 10, in <module>
from vllm.model_executor import get_model, InputMetadata, set_random_seed
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/model_executor/init.py", line 2, in <module>
from vllm.model_executor.model_loader import get_model
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 10, in <module>
from vllm.model_executor.models import *  # pylint: disable=wildcard-import
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/model_executor/models/init.py", line 1, in <module>
from vllm.model_executor.models.aquila import AquilaForCausalLM
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/model_executor/models/aquila.py", line 34, in <module>
from vllm.model_executor.layers.activation import SiluAndMul
File "/root/anaconda3/envs/qw/lib/python3.10/site-packages/vllm/model_executor/layers/activation.py", line 5, in <module>
from vllm import activation_ops
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**环境信息 / Environment Information**
- langchain-Chatchat 版本/commit 号：0.2.5
- 是否使用 Docker 部署：no
- 使用的模型： Qwen-14B-Chat
- 使用的 Embedding 模型: moka-ai/m3e-base
- 使用的向量库类型: faiss
- 操作系统及版本: Ubuntu 20.04.6 LTS
- Python 版本: 3.10.13

**Comment by simzhangbest** [comment]
同样遇到，求解

**Comment by simzhangbest** [comment]
INFO 10-18 17:22:14 llm_engine.py:72] Initializing an LLM engine with config: model='/mnt/zmy/data/weights/baichuan-7B', tokenizer='/mnt/zmy/data/weights/baichuan-7B', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=1, seed=0)
WARNING 10-18 17:22:14 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Process model_worker - baichuan-7b:
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/zmy/code/Langchain-Chatchat/startup.py", line 366, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/mnt/zmy/code/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 442, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 250, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 279, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_workers(distributed_init_method)
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 120, in _init_workers
    from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/worker/worker.py", line 10, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 10, in <module>
    from vllm.model_executor.models import *  # pylint: disable=wildcard-import
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/models/__init__.py", line 1, in <module>
    from vllm.model_executor.models.aquila import AquilaForCausalLM
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/models/aquila.py", line 34, in <module>
    from vllm.model_executor.layers.activation import SiluAndMul
  File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/layers/activation.py", line 5, in <module>
    from vllm import activation_ops
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by ShinyWey** [comment]
> INFO 10-18 17:22:14 llm_engine.py:72] Initializing an LLM engine with config: model='/mnt/zmy/data/weights/baichuan-7B', tokenizer='/mnt/zmy/data/weights/baichuan-7B', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=1, seed=0) WARNING 10-18 17:22:14 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead. Process model_worker - baichuan-7b: Traceback (most recent call last): File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap self.run() File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/mnt/zmy/code/Langchain-Chatchat/startup.py", line 366, in run_model_worker app = create_model_worker_app(log_level=log_level, **kwargs) File "/mnt/zmy/code/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app engine = AsyncLLMEngine.from_engine_args(engine_args) File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 442, in from_engine_args engine = cls(engine_args.worker_use_ray, File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 250, in **init** self.engine = self._init_engine(*args, **kwargs) File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 279, in _init_engine return engine_class(*args, **kwargs) File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 102, in **init** self._init_workers(distributed_init_method) File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 120, in _init_workers from vllm.worker.worker import Worker # pylint: disable=import-outside-toplevel File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/worker/worker.py", line 10, in from vllm.model_executor import get_model, InputMetadata, set_random_seed File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/**init**.py", line 2, in from vllm.model_executor.model_loader import get_model File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 10, in from vllm.model_executor.models import * # pylint: disable=wildcard-import File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/models/**init**.py", line 1, in from vllm.model_executor.models.aquila import AquilaForCausalLM File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/models/aquila.py", line 34, in from vllm.model_executor.layers.activation import SiluAndMul File "/home/test/anaconda3/envs/mmpose-sim/lib/python3.10/site-packages/vllm/model_executor/layers/activation.py", line 5, in from vllm import activation_ops ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

我重装了一下cuda版本和对应的pytorch版本就解决了, 不过又有了新的问题, 你可以试试先将cuda卸载了, 装个118版本的cuda, 再装对应的pytorch2.0.1.

**Comment by GoldenLoong** [comment]
额，我本地运行的，类似的报错，我强行把所有的“0.0.0.0” 替换成了"127.0.0.1"，结果行了。
