### ISSUE TITLE
[BUG] docker部署0.2.3版本报错

### ISSUE THREAD

**Issue by NathanTQ96** [chatchat-space/Langchain-Chatchat#1803]
使用官方文档的docker run -d --gpus all -p 80:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.3 在18.04.1-Ubuntu上部署
报错：PyCapsule_Import could not import module "datetime"
详细日志：
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/__init__.py", line 23                                                                                                             , in <module>
    from . import multiarray
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/multiarray.py", line                                                                                                              10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/overrides.py", line 6                                                                                                             , in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 141, in                                                                                                              <module>
    from . import core
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/__init__.py", line 49                                                                                                             , in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/usr/bin/python3"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"

2023-10-20 07:14:56,557 - instantiator.py[line:21] - INFO: Created a temporary d                                                                                                             irectory at /tmp/tmpctmn_hs9
2023-10-20 07:14:56,557 - instantiator.py[line:76] - INFO: Writing /tmp/tmpctmn_                                                                                                             hs9/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/langchain-chatchat/startup.py", line 727, in <module>
    loop.run_until_complete(start_main_server())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_comp                                                                                                             lete
    return future.result()
  File "/langchain-chatchat/startup.py", line 527, in start_main_server
    queue = manager.Queue()
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 723, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 606, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 630, in SocketC                                                                                                             lient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
All done.

**Comment by zRzRzRzRzRzRzR** [comment]
更新到新版本docker重试
