### ISSUE TITLE
[BUG] 自定义LLM api需要添加修改哪些配置？

### ISSUE THREAD

**Issue by MolianWH** [chatchat-space/Langchain-Chatchat#1812]
我需要使用一个自定义的llm api接口，已经在server/model_workers中添加我的llm类文件，init中导入该类，并修改了model_config.py和server_config.py，运行时报错片段如下（已打印详细报错日志）：
```shell
received input message:
{'history': [],
 'model_name': 'sensenova-api',
 'prompt_name': 'llm_chat',
 'query': '你好',
 'stream': True,
 'temperature': 0.7}
INFO:     127.0.0.1:39746 - "POST /chat/chat HTTP/1.1" 200 OK
2023-10-20 20:02:19 | INFO | httpx | HTTP Request: POST http://0.0.0.0:7861/chat/chat "HTTP/1.1 200 OK"
2023-10-20 20:02:19 | INFO | stdout | INFO:     127.0.0.1:54108 - "POST /list_models HTTP/1.1" 200 OK
2023-10-20 20:02:19 | INFO | controller | names: ['http://0.0.0.0:21007'], queue_lens: [0.0], ret: http://0.0.0.0:21007
2023-10-20 20:02:19 | INFO | stdout | INFO:     127.0.0.1:54114 - "POST /get_worker_address HTTP/1.1" 200 OK
INFO:     127.0.0.1:47826 - "POST /worker_get_conv_template HTTP/1.1" 200 OK
INFO:     127.0.0.1:47830 - "POST /model_details HTTP/1.1" 200 OK
count token
{'model': 'sensenova-api', 'prompt': '\n### user: 你好\n### assistant:'}
INFO:     127.0.0.1:47838 - "POST /count_token HTTP/1.1" 200 OK
2023-10-20 20:02:19 | INFO | stdout | INFO:     127.0.0.1:58302 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-10-20 20:02:19 | INFO | openai | message='OpenAI API response' path=http://0.0.0.0:20000/v1/chat/completions processing_ms=None request_id=None response_code=200
INFO:     127.0.0.1:47844 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-10-20 20:02:19 | INFO | httpx | HTTP Request: POST http://0.0.0.0:21007/worker_generate_stream "HTTP/1.1 200 OK"
2023-10-20 20:02:19 | ERROR | root | KeyError: Caught exception: 'choices'
Traceback (most recent call last):
  File "/home/dreamdeck/Documents/Langchain-Chatchat-master/server/utils.py", line 23, in wrap_done
    await fn
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    raise e
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 369, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 239, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 117, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/base.py", line 479, in agenerate_prompt
    return await self.agenerate(
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/base.py", line 439, in agenerate
    raise exceptions[0]
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/base.py", line 540, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 431, in _agenerate
    return await _agenerate_from_stream(stream_iter)
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/base.py", line 73, in _agenerate_from_stream
    async for chunk in stream:
  File "/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 403, in _astream
    if len(chunk["choices"]) == 0:
KeyError: 'choices'
```
可以看到的是，由于字典使用了不存在的属性 'choices'，我的llm类中并没有该字段，post请求中也不包含该字段。从日志看这个错误首先在 `/home/dreamdeck/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py`的第403行被触发。我不确定这是在哪一步出现的错误，为什么要调用openai，是否是由于配置不当导致？还是由于我的llm api返回的json格式有问题？

下面是我的model_config.py中涉及到修改的配置片段
```python
# 选用的 Embedding 名称
EMBEDDING_MODEL = "m3e-base" # 可以尝试最新的嵌入式sota模型：piccolo-large-zh


# Embedding 模型运行设备。设为"auto"会自动检测，也可手动设定为"cuda","mps","cpu"其中之一。
EMBEDDING_DEVICE = "auto"

# LLM 名称
LLM_MODEL = "sensenova-api"

# LLM 运行设备。设为"auto"会自动检测，也可手动设定为"cuda","mps","cpu"其中之一。
LLM_DEVICE = "auto"

# 历史对话轮数
HISTORY_LEN = 3

# LLM通用对话参数
TEMPERATURE = 0.7
# TOP_P = 0.95 # ChatOpenAI暂不支持该参数

ONLINE_LLM_MODEL = {
    #  为方便显示这部分原来的配置省略
    # 自定义
    "sensenova-api": {
        "version": "***",
        "api_key": "****", 
        "provider": "SensenovaWorker",
    }
}

```

**Comment by MolianWH** [comment]
已经解决了。该issues关闭。

**Comment by Gavin-China** [comment]
你好，怎么解决的，我也碰到这个问题

**Comment by qianbaidu1266** [comment]
您好，请问是怎么解决的呢
