### ISSUE TITLE
[BUG] ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`

### ISSUE THREAD

**Issue by leoterry-ulrica** [chatchat-space/Langchain-Chatchat#1820]
执行向量库初始化：python init_database.py --recreate-vs

提示错误：
`
Traceback (most recent call last):
  File "/mnt/llm/Langchain-Chatchat/init_database.py", line 83, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs")
  File "/mnt/llm/Langchain-Chatchat/server/knowledge_base/migrate.py", line 71, in folder2db
    kb.create_kb()
  File "/mnt/llm/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 65, in create_kb
    self.do_create_kb()
  File "/mnt/llm/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "/mnt/llm/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 33, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "/mnt/llm/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 85, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "/mnt/llm/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 40, in new_vector_store
    embeddings = embeddings_pool.load_embeddings(embed_model, embed_device)
  File "/mnt/llm/Langchain-Chatchat/server/knowledge_base/kb_cache/base.py", line 136, in load_embeddings
    embeddings = HuggingFaceBgeEmbeddings(model_name=get_model_path(model),
  File "/mnt/anaconda3/envs/python3.10/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 228, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu  22.04
- Python 版本 / Python version: python3.10
- 其他相关环境信息 / Other relevant environment information:

>>>执行安装脚本：pip install sentence_transformers，依然没有解决。

**Comment by leoterry-ulrica** [comment]
解决办法：
这个错误是由于缺少 sentence_transformers Python 包引起的。要修复这个错误，可以执行以下步骤：

1、确保你的环境中已经安装了 sentence_transformers 包。你可以使用以下命令来安装它：
`pip install sentence_transformers`
2、如果已经安装了 sentence_transformers 包，但仍然出现错误，可以尝试更新它：
`pip install --upgrade sentence_transformers`
3、确保你的Python环境与 sentence_transformers 包的依赖兼容。有时候，不同的Python版本和包版本之间可能会出现兼容性问题。检查包的官方文档以获取兼容性信息。
4、如果你使用的是Conda环境，还可以考虑更新Conda本身和PyTorch，因为错误信息中涉及到了PyTorch。你可以使用以下命令来更新Conda：
`conda update --all`
5、然后，更新PyTorch：
`conda install pytorch torchvision torchaudio -c pytorch`
