### ISSUE TITLE
MarkdownHeaderTextSplitter使用中无法正确分割知识库并存储

### ISSUE THREAD

**Issue by digitalghost** [chatchat-space/Langchain-Chatchat#1825]
**问题描述 / Problem Description**
我建立一个markdown格式的知识库文件，大致内容为：
......
# 故障代码: XXXX
故障代码: XXXX
所属系统: 门
故障产生原因: 脱敏脱敏脱敏
故障检修方法: 脱敏脱敏脱敏

# 故障代码: YYYY
故障代码: YYYY
所属系统: 门
故障产生原因: 脱敏脱敏脱敏
故障检修方法: 脱敏脱敏脱敏
......（这样的故障有2052条）

最终思路是考虑使用MarkdownHeaderTextSplitter基于每个故障做清晰的分割。事实上，这样似乎是可以的。但是存在以下问题：

1. 我把这个文件命名为.md后缀的时候，上传文件到知识库，无法正确分割。表现为，上传成功后不报异常（应该有2052个文档，但是实际在知识库界面查看刚才上传的文档，只显示文档数量是1），然后只要基于知识库进行问答就报下面这个错误
2. 如果把文件名命名为.txt是可以进行分割的，但是实际分割出来的文档数量，小于实际内容中Header的数量（应该有2052个文档，但是实际在知识库界面查看刚才上传的文档，只显示文档数量是1797），这明显就是不正确的。在这种情况下，只要进行问答，挑文档后面一点的知识去问，就会报以下的异常：

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/fastapi/applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/alan/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/alan/projects/Langchain-Chatchat-master/server/chat/knowledge_base_chat.py", line 74, in knowledge_base_chat_iterator
    filename = os.path.split(doc.metadata["source"])[-1]
                             ~~~~~~~~~~~~^^^^^^^^^^

我感觉是文档分割器在分割文档的时候没有按照预期存入向量库，所以在查询的时候导致这个异常，请问有什么解决方法么？

**Comment by zRzRzRzRzRzRzR** [comment]
markdownsplitter分割非常严格，正常的文件都用不了，可以去langcahin了解一下他是怎么分词的
我们不推荐用这个分词器，因为他适配不了大部分的文件
精准划分段落还需要自定义分词
