### ISSUE TITLE
0.2.6版Qwen回答报错ERROR: KeyError: Caught exception: 'choices'

### ISSUE THREAD

**Issue by maikgithub** [chatchat-space/Langchain-Chatchat#1840]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.2.0-34-generic-x86_64-with-glibc2.35.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.6
langchain版本：0.0.319. fastchat版本：0.2.31

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-14B-Chat-Int8'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'Qwen/Qwen-14B-Chat-Int8',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================
错误部分：
2023-10-23 15:25:17,587 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'Qwen-14B-Chat-Int8',
 'prompt_name': 'default',
 'query': '你好',
 'stream': True,
 'temperature': 0.7}
INFO:     127.0.0.1:55526 - "POST /chat/chat HTTP/1.1" 200 OK
2023-10-23 15:25:17,602 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-10-23 15:25:17 | INFO | stdout | INFO:     127.0.0.1:33468 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-10-23 15:25:17,626 - util.py[line:67] - INFO: message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None request_id=None response_code=200
2023-10-23 15:25:17 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2023-10-23 15:25:17,641 - utils.py[line:26] - ERROR: KeyError: Caught exception: 'choices'

**Comment by maikgithub** [comment]
第2个问题，如果不用量化Qwen服务启动错误：
2023-10-23 15:28:12 | ERROR | stderr | 
2023-10-23 15:28:12 | ERROR | stderr | Process model_worker - Qwen-14B-Chat:
2023-10-23 15:28:12 | ERROR | stderr | Traceback (most recent call last):
2023-10-23 15:28:12 | ERROR | stderr |   File "/home/wtubt/anaconda3/envs/wtchat/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-10-23 15:28:12 | ERROR | stderr |     self.run()
2023-10-23 15:28:12 | ERROR | stderr |   File "/home/wtubt/anaconda3/envs/wtchat/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-10-23 15:28:12 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-10-23 15:28:12 | ERROR | stderr |   File "/home/wtubt/work/pro/Langchain-Chatchat/startup.py", line 382, in run_model_worker
2023-10-23 15:28:12 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-10-23 15:28:12 | ERROR | stderr |   File "/home/wtubt/work/pro/Langchain-Chatchat/startup.py", line 210, in create_model_worker_app
2023-10-23 15:28:12 | ERROR | stderr |     worker = ModelWorker(
2023-10-23 15:28:12 | ERROR | stderr |   File "/home/wtubt/anaconda3/envs/wtchat/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-10-23 15:28:12 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-10-23 15:28:12 | ERROR | stderr |   File "/home/wtubt/anaconda3/envs/wtchat/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 308, in load_model
2023-10-23 15:28:12 | ERROR | stderr |     model.to(device)
2023-10-23 15:28:12 | ERROR | stderr |   File "/home/wtubt/anaconda3/envs/wtchat/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2174, in to
2023-10-23 15:28:12 | ERROR | stderr |     raise ValueError(
2023-10-23 15:28:12 | ERROR | stderr | ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.

**Comment by ShinyWey** [comment]
2023-10-23 16:23:09,130 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'Qwen-14B-Chat',
 'prompt_name': 'py',
 'query': '请编写一个Python的冒泡排序',
 'stream': True,
 'temperature': 0.7}
INFO:     127.0.0.1:34682 - "POST /chat/chat HTTP/1.1" 200 OK
2023-10-23 16:23:09,169 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-10-23 16:23:09 | INFO | stdout | INFO:     127.0.0.1:55224 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-10-23 16:23:09,225 - util.py[line:67] - INFO: message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None request_id=None response_code=200
2023-10-23 16:23:09 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2023-10-23 16:23:09,255 - utils.py[line:26] - ERROR: KeyError: Caught exception: 'choices'
同样的错误

**Comment by ShinyWey** [comment]
> 2023-10-23 16:23:09,130 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" received input message: {'history': [], 'max_tokens': None, 'model_name': 'Qwen-14B-Chat', 'prompt_name': 'py', 'query': '请编写一个Python的冒泡排序', 'stream': True, 'temperature': 0.7} INFO: 127.0.0.1:34682 - "POST /chat/chat HTTP/1.1" 200 OK 2023-10-23 16:23:09,169 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK" 2023-10-23 16:23:09 | INFO | stdout | INFO: 127.0.0.1:55224 - "POST /v1/chat/completions HTTP/1.1" 200 OK 2023-10-23 16:23:09,225 - util.py[line:67] - INFO: message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None request_id=None response_code=200 2023-10-23 16:23:09 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK" 2023-10-23 16:23:09,255 - utils.py[line:26] - ERROR: KeyError: Caught exception: 'choices' 同样的错误

prompt_name切成default也是一样

**Comment by qihangf** [comment]
+1，我也是用qwen同样的问题

**Comment by miclee521** [comment]
+1, Qwen-14B-Chat-Int4,  也报错ERROR: KeyError: Caught exception: 'choices'

**Comment by jhw0510** [comment]
+1, Qwen-14B-Chat-Int4, 也报错ERROR: KeyError: Caught exception: 'choices'，0.2.5是正常使用的

**Comment by nathubs** [comment]
+1  使用qwen-api ，baichuan-api ，qianfan-api时报
utils.py[line:26] - ERROR: KeyError: Caught exception: 'choices'

只有zhipu-api是正常？

**Comment by invokerbyxv** [comment]
我也遇到了，但实际报错是fastchat抛出的：
```
{
  "text": "**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(Unrecognized tensor type ID: AutocastCUDA)",
  "error_code": 50001
}
```

**Comment by pdo2013** [comment]
可暂时将torch降级到2.0.1解决这个问题。

**Comment by 1787812757** [comment]
> 可暂时将torch降级到2.0.1解决这个问题。

我降低了torch版本,还是报错了
KeyError: Caught exception: 'choices'

**Comment by pdo2013** [comment]
这个问题似乎不是这个项目这边的原因导致的。最新的版本langchain-chatchat安装依赖时安装了torch2.1.0。对于的cuda变成12。但是在Qwen-14B-Chat-Int4这边的modeling_qwen.py调用了auto-gptq，auto-gptq调用时目前仅支持到11.8。因此出现报错。
你可以试试：
1.删除整个venv
2.把requirements.txt中torch>=2.0.1 # 推荐2.1改成torch==2.0.1 # 推荐2.1
3.重新安装requirements

**Comment by maikgithub** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12423777/a4ae80f2-a58b-4dd6-b863-d30ebce55af8)

**Comment by hzg0601** [comment]
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
conda install -y -c "nvidia/label/cuda-11.8.0" cuda-runtime
pip uninstall auto-gptq
pip install "git+https://github.com/PanQiWei/AutoGPTQ.git@v0.4.2"

**Comment by wzhty86** [comment]
> 这个问题似乎不是这个项目这边的原因导致的。最新的版本langchain-chatchat安装依赖时安装了torch2.1.0。对应的cuda变成12。但是在Qwen-14B-Chat-Int4这边的modeling_qwen.py调用了auto-gptq，auto-gptq调用时目前仅支持到11.8。因此出现报错。


除了torch版本降级，还有其他解决方案吗？因为要支持多个其他模型，担心降级后，会影响到其他模型

**Comment by maikgithub** [comment]
用的0.2.6版确实需要降级。新版本还没使用，你可以试试。







在 2023-12-26 16:27:54，"wzhty86" ***@***.***> 写道：

这个问题似乎不是这个项目这边的原因导致的。最新的版本langchain-chatchat安装依赖时安装了torch2.1.0。对应的cuda变成12。但是在Qwen-14B-Chat-Int4这边的modeling_qwen.py调用了auto-gptq，auto-gptq调用时目前仅支持到11.8。因此出现报错。

除了torch版本降级，还有其他解决方案吗？因为要支持多个其他模型，担心降级后，会影响到其他模型

**Comment by wzhty86** [comment]
> 用的0.2.6版确实需要降级。新版本还没使用，你可以试试。

尝试了新版本0.2.8，部署运行Qwen-7B-Chat/Qwen-14B-Chat都会报类似的错误

**Comment by Modas-Li** [comment]
same issue

**Comment by Modas-Li** [comment]
> ![image](https://private-user-images.githubusercontent.com/12423777/278928459-a4ae80f2-a58b-4dd6-b863-d30ebce55af8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTU0MzEsIm5iZiI6MTcwNTY1NTEzMSwicGF0aCI6Ii8xMjQyMzc3Ny8yNzg5Mjg0NTktYTRhZTgwZjItYTU4Yi00ZGQ2LWI4NjMtZDMwZWJjZTU1YWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA5MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNGZkNDU3M2UzOTA3NGM4YmYxYWQ5Mzg4ZmY3MjcxNjdkMjkwNzg3MzFlZmJhZTU2Y2JlOTkxN2ZmYWUzNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1eavqU7Wt4F8-jfBMDI1_Or-G1C03LxTvT4anCn0jkA) @pdo2013 requirements.txt和requirements.txt_api.txt 按以上设置Qwen可以访问。谢谢！

大哥发全一点，指定下这些版本，你的requirements_api.txt和requirements.txt发一下，谢谢

**Comment by maikgithub** [comment]
这个不是最新版本
















在 2024-01-19 17:12:33，"Modas Li" ***@***.***> 写道：

@pdo2013 requirements.txt和requirements.txt_api.txt 按以上设置Qwen可以访问。谢谢！

大哥发全一点，指定下这些版本，你的requirements_api.txt和requirements.txt发一下，谢谢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
langchain>=0.0.319
langchain-experimental>=0.0.30
# fschat[model_worker]==0.2.31
fschat[model_worker]
# xformers>=0.0.22.post4
xformers
openai>=0.28.1
sentence_transformers
transformers>=4.34
torch==2.0.1 # 推荐2.1
torchvision
torchaudio
fastapi>=0.104
nltk>=3.8.1
uvicorn~=0.23.1
starlette~=0.27.0
pydantic~=1.10.11
unstructured[all-docs]>=0.10.12
python-magic-bin; sys_platform == 'win32'
SQLAlchemy==2.0.19
faiss-cpu
accelerate
spacy
PyMuPDF
rapidocr_onnxruntime

requests
pathlib
pytest
scikit-learn
numexpr
vllm>=0.2.0; sys_platform == "linux"
# online api libs
# zhipuai
# dashscope>=1.10.0 # qwen
# qianfan
# volcengine>=1.0.106 # fangzhou

# uncomment libs if you want to use corresponding vector store
# pymilvus==2.1.3 # requires milvus==2.1.3
# psycopg2
# pgvector

numpy~=1.24.4
pandas~=2.0.3
streamlit>=1.26.0
streamlit-option-menu>=0.3.6
streamlit-antd-components>=0.1.11
streamlit-chatbox==1.1.10
streamlit-aggrid>=0.3.4.post3
httpx~=0.24.1
watchdog
tqdm
websockets
tiktoken
einops
scipy
transformers_stream_generator==0.0.4

langchain>=0.0.319
langchain-experimental>=0.0.30
# fschat[model_worker]==0.2.31
fschat[model_worker]
# xformers>=0.0.22.post4
xformers
openai>=0.28.1
sentence_transformers>=2.2.2
transformers>=4.34
# torch>=2.1
torch==2.0.1
torchvision
torchaudio
fastapi>=0.104
nltk~=3.8.1
uvicorn~=0.23.1
starlette~=0.27.0
pydantic~=1.10.11
unstructured[all-docs]>=0.10.4
python-magic-bin; sys_platform == 'win32'
SQLAlchemy==2.0.19
faiss-cpu
accelerate
spacy
PyMuPDF==1.22.5
rapidocr_onnxruntime>=1.3.2
requests
pathlib
pytest
scikit-learn
numexpr

vllm>=0.2.0; sys_platform == "linux"


# online api libs
# zhipuai
# dashscope>=1.10.0 # qwen
# qianfan
# volcengine>=1.0.106 # fangzhou
# duckduckgo-searchd #duckduckgo搜索

# uncomment libs if you want to use corresponding vector store
# pymilvus==2.1.3 # requires milvus==2.1.3
# psycopg2
# pgvector

**Comment by Modas-Li** [comment]
我把知识库里的长文本内容删除后，问题有所缓解
