### ISSUE TITLE
为什么使用Milvus向量数据库, 也会报没有Faiss的错呢

### ISSUE THREAD

**Issue by ShinyWey** [chatchat-space/Langchain-Chatchat#1849]
**问题描述 / Problem Description**
为什么使用Milvus向量数据库, 也会报没有Faiss的错呢

**复现问题的步骤 / Steps to Reproduce**
项目启动没问题, 正常LLM对话也没问题, webui切换到知识库/新建知识库的时候就会报错

**预期的结果 / Expected Result**
描述应该出现的结果: 没有问题

**实际结果 / Actual Result**
2023-10-24 11:17:32,791 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54480 - "POST /knowledge_base/create_knowledge_base HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/fastapi/applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/test003/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/hello2ai/Langchain-Chatchat-0.2.6/server/knowledge_base/kb_api.py", line 29, in create_kb
    kb = KBServiceFactory.get_service(knowledge_base_name, vector_store_type, embed_model)
  File "/home/hello2ai/Langchain-Chatchat-0.2.6/server/knowledge_base/kb_service/base.py", line 253, in get_service
    from server.knowledge_base.kb_service.milvus_kb_service import MilvusKBService
  File "/home/hello2ai/Langchain-Chatchat-0.2.6/server/knowledge_base/kb_service/milvus_kb_service.py", line 4, in <module>
    from faiss import normalize_L2
ModuleNotFoundError: No module named 'faiss'
2023-10-24 11:17:47,156 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/create_knowledge_base "HTTP/1.1 500 Internal Server Error"
2023-10-24 11:17:47.158 Please replace `st.experimental_rerun` with `st.rerun`.

`st.experimental_rerun` will be removed after 2024-04-01.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.6
- 是否使用 Docker 部署（是/否）：NO
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-Chat
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： Milvus

**Comment by liunux4odoo** [comment]
感谢反馈，后续将修复。
