### ISSUE TITLE
[BUG] v0.2.6 install error: subprocess-exited-with-error解决方案

### ISSUE THREAD

**Issue by cspung** [chatchat-space/Langchain-Chatchat#1868]
**问题描述 / Problem Description**
执行 `pip install -r requirements.txt`，报错如下：

`Collecting wavedrom (from markdown2[all]->fschat==0.2.31->fschat[model_worker]==0.2.31->-r requirements.txt (line 3))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/be/71/6739e3abac630540aaeaaece4584c39f88b5f8658ce6ca517efec455e3de/wavedrom-2.0.3.post3.tar.gz (137 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [126 lines of output]
      /opt/conda/envs/langchain/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools-scm/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools-scm/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools-scm/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools-scm/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools-scm/
      ERROR: Exception:
      Traceback (most recent call last):
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
          yield
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
          data = self._fp_read(amt) if not fp_closed else b""
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
          return self._fp.read(amt) if amt is not None else self._fp.read()
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
          data: bytes = self.__fp.read(amt)
        File "/opt/conda/envs/langchain/lib/python3.10/http/client.py", line 466, in read
          s = self.fp.read(amt)
        File "/opt/conda/envs/langchain/lib/python3.10/socket.py", line 705, in readinto
          return self._sock.recv_into(b)
        File "/opt/conda/envs/langchain/lib/python3.10/ssl.py", line 1274, in recv_into
          return self.read(nbytes, buffer)
        File "/opt/conda/envs/langchain/lib/python3.10/ssl.py", line 1130, in read
          return self._sslobj.read(len, buffer)
      TimeoutError: The read operation timed out

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
          status = run_func(*args)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
          return func(self, options, args)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/commands/wheel.py", line 147, in run
          requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
          result = self._result = resolver.resolve(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
          if not criterion.candidates:
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
          return bool(self._sequence)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
          super().__init__(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
          self.dist = self._prepare()
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
          dist = self._prepare_distribution()
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 519, in prepare_linked_requirement
          metadata_dist = self._fetch_metadata_only(req)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 371, in _fetch_metadata_only
          return self._fetch_metadata_using_link_data_attr(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 391, in _fetch_metadata_using_link_data_attr
          metadata_file = get_http_url(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 109, in get_http_url
          from_path, content_type = download(link, temp_dir.path)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
          for chunk in chunks:
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
          for chunk in response.raw.stream(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
          data = self.read(amt=amt, decode_content=decode_content)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
          with self._error_catcher():
        File "/opt/conda/envs/langchain/lib/python3.10/contextlib.py", line 153, in __exit__
          self.gen.throw(typ, value, traceback)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
          raise ReadTimeoutError(self._pool, None, "Read timed out.")
      pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
      Traceback (most recent call last):
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/opt/conda/envs/langchain/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/conda/envs/langchain/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpp6z6tdxx', '--quiet', 'setuptools_scm']' returned non-zero exit status 2.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-0zubqwlh/wavedrom_36dde82dab114940963770b8f2eef61a/setup.py", line 28, in <module>
          setup(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/setuptools/dist.py", line 907, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
        File "/opt/conda/envs/langchain/lib/python3.10/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/opt/conda/envs/langchain/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpp6z6tdxx', '--quiet', 'setuptools_scm']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

查看上述报错信息，发现`pip install wavedrom`安装时所需依赖`setuptools-scm`安装不成功，单独安装依赖：
`pip install setuptools_scm`
重新执行`pip install -r requirements.txt`可安装成功

**Comment by cspung** [comment]
已解决
