### ISSUE TITLE
[BUG] 知识库初始化报错：requests.exceptions.ConnectionError:

### ISSUE THREAD

**Issue by zoneRohn** [chatchat-space/Langchain-Chatchat#1878]
**问题描述 / Problem Description**
按照最新RM文档的快速上手中的步骤执行到初始化之前都是顺利的，当执行初始化这一步时就报错：
`requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/moka-ai/m3e-base (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba6c540b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: efd125a3-dc97-41e8-9e8f-aab01d8efd53)')`
用不用墙都是这样，不知道是哪里的配置出了问题...

**复现问题的步骤 / Steps to Reproduce**
ubuntu22.04 命令行执行 `python init_database.py --recreate-vs`

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本号：v0.2.6
- 是否使用 Docker 部署：否，本地部署
- 使用的模型：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:Win10下的WSL Ubuntu22.04子系统
- Python 版本 / Python version:3.10.5

**附加信息 / Additional Information**
完整命令行执行记录如下：
```
root@DESKTOP-VUUCO7E:~/Langchain-Chatchat# python3 init_database.py --recreate-vs
/usr/local/lib/python3.10/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
database talbes reseted
recreating all vector stores
2023-10-25 16:20:19,529 - faiss_cache.py[line:75] - INFO: loading vector store in 'samples/vector_store' from disk.
2023-10-25 16:20:19,554 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: moka-ai/m3e-base
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fba6c540b50>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/moka-ai/m3e-base (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba6c540b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Langchain-Chatchat/init_database.py", line 83, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs")
  File "/root/Langchain-Chatchat/server/knowledge_base/migrate.py", line 70, in folder2db
    kb.create_kb()
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 65, in create_kb
    self.do_create_kb()
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 33, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 85, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 40, in new_vector_store
    embeddings = embeddings_pool.load_embeddings(embed_model, embed_device)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_cache/base.py", line 142, in load_embeddings
    embeddings = HuggingFaceEmbeddings(model_name=get_model_path(model), model_kwargs={'device': device})
  File "/usr/local/lib/python3.10/dist-packages/langchain/embeddings/huggingface.py", line 66, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/usr/local/lib/python3.10/dist-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/sentence_transformers/util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 1697, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/moka-ai/m3e-base (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba6c540b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: efd125a3-dc97-41e8-9e8f-aab01d8efd53)')
root@DESKTOP-VUUCO7E:~/Langchain-Chatchat#
```

**Comment by glide-the** [comment]
尝试使用代理，huggingface网站因为不可抗原因现在不稳定

**Comment by zoneRohn** [comment]
> 尝试使用代理，huggingface网站因为不可抗原因现在不稳定
使用代理是翻墙吗？我试过开墙了也是这样呀，老哥有没有可以参考的方式提供一下 感谢~
