### ISSUE TITLE
[BUG] API调用报错：openai.error.APIError: Invalid response object from API: '{"object":"error","message":"Only  allowed now, your model Azure-OpenAI","code":40301}' (HTTP response code was 400)

### ISSUE THREAD

**Issue by love520222** [chatchat-space/Langchain-Chatchat#1883]
**问题描述 / Problem Description**
API调用报错：openai.error.APIError: Invalid response object from API: '{"object":"error","message":"Only  allowed now, your model Azure-OpenAI","code":40301}' (HTTP response code was 400)

**复现问题的步骤 / Steps to Reproduce**
**1. 执行 '...' / python startup.py -a '...'
Log：**

PS E:\AI\Langchain-Chatchat\Langchain-Chatchat> python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
项目版本：v0.2.6
langchain版本：0.0.323. fastchat版本：0.2.31

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Azure-OpenAI'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'langchain_model': True,
 'port': 20002,
 'worker_class': ''}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-10-26 18:29:55,036 - startup.py[line:626] - INFO: 正在启动服务：
2023-10-26 18:29:55,036 - startup.py[line:627] - INFO: 如需查看 llm_api 日志，请前往 E:\AI\Langchain-Chatchat\Langchain-Chatchat\logs
2023-10-26 18:29:56 | ERROR | stderr | INFO:     Started server process [17912]
2023-10-26 18:29:56 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-26 18:29:56 | ERROR | stderr | INFO:     Application startup complete.
2023-10-26 18:29:56 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
INFO:     Started server process [9460]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
项目版本：v0.2.6
langchain版本：0.0.323. fastchat版本：0.2.31

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Azure-OpenAI'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'langchain_model': True,
 'port': 20002,
 'worker_class': ''}
当前Embbedings模型： m3e-base @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-10-26 18:30:04,701 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53302 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
。。。。。。。

**按照startup.py里面最后一段的api调用方法改的代码如下：**
```
import openai
openai.api_key = "EMPTY" # Not support yet
openai.api_base = "http://127.0.0.1:20000/v1"

# model = "Azure-OpenAI"
# user = input(":::")
# create a chat completion
completion = openai.ChatCompletion.create(
  model="Azure-OpenAI",
  messages=[{"role": "user", "content": "你好"}],
  temperature=6
)
# print the completion
print(completion.choices[0].message.content)

```
**### 执行后报错：**

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\openai\api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\M930t\Desktop\AI语音交互\to_wenda\to_fastapi.py", line 8, in <module>
    completion = openai.ChatCompletion.create(
  File "D:\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "D:\Python310\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\Python310\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "D:\Python310\lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
  File "D:\Python310\lib\site-packages\openai\api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"object":"error","message":"Only  allowed now, your model Azure-OpenAI","code":40301}' (HTTP response code was 400)

执行python startup.py -a的终端报错记录：

2023-10-26 18:30:52 | INFO | stdout | INFO:     127.0.0.1:53317 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request

**### 顺便问下怎么通过api调用知识库问答？**

*
<img width="1118" alt="微信图片_20231026183240" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/58250367/e88acc05-9659-4261-9060-251859b2eb0c">

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
更新到dev这个bug修了
