### ISSUE TITLE
[BUG] python startup.py 启动报错

### ISSUE THREAD

**Issue by Leitast** [chatchat-space/Langchain-Chatchat#1893]
**问题描述**
执行 python startup.py -a 失败.

**预期的结果**
跳出启动界面

**实际结果 / Actual Result**
```
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.6
langchain版本：0.0.324. fastchat版本：0.2.31

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ cpu
{'device': 'cpu',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'chatglm2-6b',
 'port': 20002}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2023-10-27 13:32:51,840 - startup.py[line:626] - INFO: 正在启动服务：
2023-10-27 13:32:51,841 - startup.py[line:627] - INFO: 如需查看 llm_api 日志，请前往 D:\worksapce\vscode\Langchain-Chatchat\logs
2023-10-27 13:32:55 | ERROR | stderr | INFO:     Started server process [9548]
2023-10-27 13:32:55 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-27 13:32:55 | ERROR | stderr | INFO:     Application startup complete.
2023-10-27 13:32:55 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2023-10-27 13:32:55 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker d9adc580 ...
2023-10-27 13:32:55 | INFO | model_worker | Register to controller
2023-10-27 13:32:55 | ERROR | stderr | Process model_worker - chatglm2-6b:
2023-10-27 13:32:55 | ERROR | stderr | Traceback (most recent call last):
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\multiprocessing\process.py", line 314, in _bootstrap
2023-10-27 13:32:55 | ERROR | stderr |     self.run()
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\multiprocessing\process.py", line 108, in run
2023-10-27 13:32:55 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\worksapce\vscode\Langchain-Chatchat\startup.py", line 382, in run_model_worker
2023-10-27 13:32:55 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\worksapce\vscode\Langchain-Chatchat\startup.py", line 210, in create_model_worker_app
2023-10-27 13:32:55 | ERROR | stderr |     worker = ModelWorker(
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\site-packages\fastchat\serve\model_worker.py", line 74, in __init__
2023-10-27 13:32:55 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\site-packages\fastchat\model\model_adapter.py", line 294, in load_model
2023-10-27 13:32:55 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\site-packages\fastchat\model\model_adapter.py", line 716, in load_model
2023-10-27 13:32:55 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 738, in from_pretrained
2023-10-27 13:32:55 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\site-packages\transformers\tokenization_utils_base.py", line 2017, in from_pretrained
2023-10-27 13:32:55 | ERROR | stderr |     return cls._from_pretrained(
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\site-packages\transformers\tokenization_utils_base.py", line 2249, in _from_pretrained
2023-10-27 13:32:55 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2023-10-27 13:32:55 | ERROR | stderr |   File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm2-6b\tokenization_chatglm.py", line 72, in __init__
2023-10-27 13:32:55 | ERROR | stderr |     self.tokenizer = SPTokenizer(vocab_file)
2023-10-27 13:32:55 | ERROR | stderr |   File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm2-6b\tokenization_chatglm.py", line 13, in __init__
2023-10-27 13:32:55 | ERROR | stderr |     assert os.path.isfile(model_path), model_path
2023-10-27 13:32:55 | ERROR | stderr |   File "D:\ProgramData\anaconda3\envs\chatglm2-6b\lib\genericpath.py", line 30, in isfile
2023-10-27 13:32:55 | ERROR | stderr |     st = os.stat(path)
2023-10-27 13:32:55 | ERROR | stderr | TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 操作系统及版本: Windows-11
- Python 版本: 3.10.12

**附加信息 / Additional Information**
本地部署模型

**Comment by Leitast** [comment]
下载模型时遗漏了tokenizer.model
