### ISSUE TITLE
[BUG] 简洁阐述问题 / RuntimeError: Error in __cdecl faiss::FileIOWriter::FileIOWriter(const char *)

### ISSUE THREAD

**Issue by wcxxxxx** [chatchat-space/Langchain-Chatchat#1926]
2023-10-31 15:24:30,660 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-10-31 15:24:30,660 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-10-31 15:24:30,660 - loader.py[line:64] - INFO: Loading faiss.
2023-10-31 15:24:30,674 - loader.py[line:66] - INFO: Successfully loaded faiss.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "D:\Langchain-Chatchat\server\chat\knowledge_base_chat.py", line 56, in knowledge_base_chat_iterator
    docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_doc_api.py", line 32, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 152, in search_docs
    docs = self.do_search(query, top_k, score_threshold, embeddings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 63, in do_search
    with self.load_vector_store().acquire() as vs:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 33, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_cache\faiss_cache.py", line 86, in load_vector_store
    vector_store.save_local(vs_path)
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\langchain\vectorstores\faiss.py", line 695, in save_local
    faiss.write_index(
  File "D:\Langchain-Chatchat\venv\Lib\site-packages\faiss\swigfaiss.py", line 9789, in write_index
    return _swigfaiss.write_index(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in __cdecl faiss::FileIOWriter::FileIOWriter(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:98: Error: 'f' failed: could not open D:\Langchain-Chatchat\knowledge_base\测试\vector_store\index.faiss for writing: No such file or directory
2023-10-31 15:24:30,690 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

请问这是什么问题呀

**Comment by wcxxxxx** [comment]
中文路径问题

**Comment by 77coming** [comment]
我可以请问一下\vector_store\index.faiss这个是怎么来的吗？
