### ISSUE TITLE
[BUG] [WinError 2] 系统找不到指定的文件

### ISSUE THREAD

**Issue by lhtpluto** [chatchat-space/Langchain-Chatchat#1933]
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]
项目版本：v0.2.6
langchain版本：0.0.327. fastchat版本：0.2.31

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'model\\chatglm3-6b',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda

异常如下：
![屏幕截图 2023-11-01 115350](https://github.com/chatchat-space/Langchain-Chatchat/assets/132045861/690fd580-f8aa-47e4-97af-13c89bf00ce4)

Process WEBUI Server:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\ProgramData\anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\168知识库办公助手\startup.py", line 447, in run_webui
    p = subprocess.Popen(["streamlit", "run", "webui.py",
  File "C:\ProgramData\anaconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\anaconda3\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新版本试一下

**Comment by Jethro-Cheng** [comment]
我也遇到了 你解决了吗

**Comment by a994862495** [comment]
我也遇到了这个问题

**Comment by a994862495** [comment]
Process WEBUI Server:
Traceback (most recent call last):
  File "D:\PythonTools\Anaconda3\AnacondaPythonOther\LangChain\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\PythonTools\Anaconda3\AnacondaPythonOther\LangChain\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\PythonProject\Langchain-Chatchat-0.2.6\startup.py", line 447, in run_webui
    p = subprocess.Popen(["streamlit", "run", "webui.py",
  File "D:\PythonTools\Anaconda3\AnacondaPythonOther\LangChain\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\PythonTools\Anaconda3\AnacondaPythonOther\LangChain\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by a994862495** [comment]
升级即可解决此错误

**Comment by ouyyy18** [comment]
我也是这个问题，更新到最新版本也无法解决

**Comment by a994862495** [comment]
拉取最新的代码
python版本3.10.12，安装对应的torch gpu，再安装
pip install -r requirements.txt 
pip install -r requirements_api.txt
pip install -r requirements_webui.txt
在Centos7上CUDA11.2 ,windows11上CUDA12.1都成功了
@ouyyy18

**Comment by DspringL** [comment]
v0.2.9在win11下也遇到这个问题了

**Comment by 948024326** [comment]
> v0.2.9在win11下也遇到这个问题了

我也是，请问解决了吗？

**Comment by Rmj99** [comment]
采用最轻模式lite本地部署方案，报异常
Traceback (most recent call last):
  File "D:\SoftWare\anaconda3\envs\Langchain-chatchat\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\SoftWare\anaconda3\envs\Langchain-chatchat\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "F:\tphy\code\Langchain-Chatchat-master\startup.py", line 467, in run_webui
    p = subprocess.Popen(cmd)
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\SoftWare\anaconda3\envs\Langchain-chatchat\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\SoftWare\anaconda3\envs\Langchain-chatchat\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by oscar-sxf** [comment]
我找到原因是安装的streamlit不能运行，需要把steamlit执行文件加入到环境变量里，就可以了。

**Comment by manfwong** [comment]
> 我找到原因是安装的streamlit不能运行，需要把steamlit执行文件加入到环境变量里，就可以了。
'streamlit' is not recognized as an internal or external command,
operable program or batch file.

我也出現這個信息，那麼可以怎樣把 streamlit 執行文件加入環境變量呢? 實際如何做呢? 煩請指教，謝謝。

**Comment by zixiaotan21** [comment]
> 我找到原因是安装的streamlit不能运行，需要把steamlit执行文件加入到环境变量里，就可以了。

同样遇到这个问题，想问问如何把steamlit执行文件加入到环境变量呀

**Comment by zixiaotan21** [comment]
同样遇到这个问题，我用的是v0.2.9在win10下运行，想问问各位大佬解决了吗
