### ISSUE TITLE
[BUG] 启动报错 / 默认启动报错

### ISSUE THREAD

**Issue by chengyuanyao** [chatchat-space/Langchain-Chatchat#1946]
**问题描述 / Problem Description**
2023-11-01 18:26:28,034 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://127.0.0.1:7890', 'https://': 'http://127.0.0.1:7890', 'all://': None, '127.0.0.1': None, 'localhost': None}}
2023-11-01 18:26:28,054 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
2023-11-01 18:26:28.055 Uncaught app exception
Traceback (most recent call last):
  File "/home/crscu/anaconda3/envs/ChatGLM2-6B/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/data/ts/Langchain-Chatchat-master/webui.py", line 60, in <module>
    pages[selected_page]["func"](api)
  File "/data/ts/Langchain-Chatchat-master/webui_pages/dialogue/dialogue.py", line 114, in dialogue_page
    index = llm_models.index(st.session_state.get("cur_llm_model", get_default_llm_model(api)[0]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: '' is not in list

**Comment by chengyuanyao** [comment]
本机开了代理的原因，关闭之后解决
