### ISSUE TITLE
chatglm2-6b-int4无法顺利启动

### ISSUE THREAD

**Issue by lannykov** [chatchat-space/Langchain-Chatchat#1958]
**问题描述 
已经下载chatglm2-6B及chatglm2-6B-in4到本地，修改configs/中的model_config.py，使得：
# LLM 名称
LLM_MODEL = "chatglm2-6b-int4"

**预期的结果 / Expected Result**
LLM顺利启用chatglm2-6b-int4，就像使用默认chatglm2-6B一样。

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
2023-11-03 10:58:02 | INFO | model_worker | Loading the model ['chatglm2-6b-int4'] on worker 37498dbb ...
2023-11-03 10:58:06 | WARNING | transformers_modules.chatglm2-6b-int4.quantization | Failed to load cpm_kernels:No module named 'cpm_kernels'
2023-11-03 10:58:06 | ERROR | stderr | Process model_worker - chatglm2-6b-int4:
2023-11-03 10:58:06 | ERROR | stderr | Traceback (most recent call last):
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-03 10:58:06 | ERROR | stderr |     self.run()
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-03 10:58:06 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-03 10:58:06 | ERROR | stderr |   File "/opt/Langchain-Chatchat/startup.py", line 382, in run_model_worker
2023-11-03 10:58:06 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-03 10:58:06 | ERROR | stderr |   File "/opt/Langchain-Chatchat/startup.py", line 210, in create_model_worker_app
2023-11-03 10:58:06 | ERROR | stderr |     worker = ModelWorker(
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-11-03 10:58:06 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 294, in load_model
2023-11-03 10:58:06 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 719, in load_model
2023-11-03 10:58:06 | ERROR | stderr |     model = AutoModel.from_pretrained(
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
2023-11-03 10:58:06 | ERROR | stderr |     return model_class.from_pretrained(
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3085, in from_pretrained
2023-11-03 10:58:06 | ERROR | stderr |     model = cls(config, *model_args, **model_kwargs)
2023-11-03 10:58:06 | ERROR | stderr |   File "/home/lewin/.cache/huggingface/modules/transformers_modules/chatglm2-6b-int4/modeling_chatglm.py", line 861, in __init__
2023-11-03 10:58:06 | ERROR | stderr |     self.quantize(self.config.quantization_bit, empty_init=True)
2023-11-03 10:58:06 | ERROR | stderr |   File "/home/lewin/.cache/huggingface/modules/transformers_modules/chatglm2-6b-int4/modeling_chatglm.py", line 1197, in quantize
2023-11-03 10:58:06 | ERROR | stderr |     self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
2023-11-03 10:58:06 | ERROR | stderr |   File "/home/lewin/.cache/huggingface/modules/transformers_modules/chatglm2-6b-int4/quantization.py", line 511, in quantize
2023-11-03 10:58:06 | ERROR | stderr |     layer.self_attention.query_key_value = QuantizedLinear(
2023-11-03 10:58:06 | ERROR | stderr |   File "/home/lewin/.cache/huggingface/modules/transformers_modules/chatglm2-6b-int4/quantization.py", line 494, in __init__
2023-11-03 10:58:06 | ERROR | stderr |     self.weight = Parameter(self.weight.to(device), requires_grad=False)
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1712, in __setattr__
2023-11-03 10:58:06 | ERROR | stderr |     self.register_parameter(name, value)
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py", line 123, in register_empty_parameter
2023-11-03 10:58:06 | ERROR | stderr |     module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs)
2023-11-03 10:58:06 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/parameter.py", line 39, in __new__
2023-11-03 10:58:06 | ERROR | stderr |     return torch.Tensor._make_subclass(cls, data, requires_grad)
2023-11-03 10:58:06 | ERROR | stderr | RuntimeError: Only Tensors of floating point and complex dtype can require gradients

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：2.0.6最新版
- 是否使用 Docker 部署（是/否）：否
- (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B，ChatGLM2-6B-int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base（下载到本地了）
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / ubuntu22.04 server
- Python 版本 / Python version:3.10.12
- 其他相关环境信息 / 双3070GPU，8GB显存，设置了双卡

**附加信息 / Additional Information**
如何才能顺利跑chatglm2-6B-int4这类量化模型？双3070GPU，8GB显存，设置了双卡,合计有16GB显存，但光是LLM(ChatGLM2-6B）就占用了13GB显存，构建私有知识库的过程都无法继续，所以想到使用int4的量化版本。如果实在不行，那这套系统就用openai的api了。

**Comment by hzg0601** [comment]
这个是chatglm2-6b-int4的qunatization.py的问题，请移步至THUDM反馈

**Comment by Hty30** [comment]
解决了吗？
