### ISSUE TITLE
[BUG] 无法调用fastchat的api，使用远程服务器fastchat部署的llm模型

### ISSUE THREAD

**Issue by plancktree** [chatchat-space/Langchain-Chatchat#1968]
尝试修改model_config调用 xxx.xxx.xxx.xxx的服务器上使用fastchat部署llm模型，使用多种调用方式，仍然无法成功调用其api。在本工程0.1.17版本可正常调用该服务器的fastchat的api
配置文件中主要修改代码如下，注释部分为其他尝试的调用方法
```

`LANGCHAIN_LLM_MODEL = {

    # 这些配置文件的名字不能改动
    "Azure-OpenAI": {
        "deployment_name": "your Azure deployment name",
        "model_version": "0701",
        "openai_api_type": "azure",
        "api_base_url": "https://your Azure point.azure.com",
        "api_version": "2023-07-01-preview",
        "api_key": "your Azure api key",
        "openai_proxy": "",
    },
   "OpenAI": {
        "model_name": "vicuna-v1.5",  # "name"修改为fastchat服务中的"model_name"
        "model": "vicuna-v1.5",  # "name"修改为fastchat服务中的"model_name"
        "pretrained_model_name": "vicuna-v1.5",
        "local_model_path": None,
        "provides": "FastChatOpenAILLMChain",  # 使用fastchat api时，需保证"provides"为"FastChatOpenAILLMChain"
        "api_b:ase_url": "http://xxx.xxx.xxx.xxx:xxxx/v1",  # "name"修改为fastchat服务中的"api_base_url"
        "api_key": "EMPTY"
    },
   # "OpenAI": {
   #     "model_name": "vicuna-v1.5",
   #     "api_base_url": "http://xxx.xxx.xxx.xxx:xxxx/v1",
   #     "api_key": "EMPTY",
   #     "openai_proxy": "",
   # },
   #"FastChat": {
   #     "model_name": "vicuna-v1.5",  # "name"修改为fastchat服务中的"model_name"
   #     "model": "vicuna-v1.5",  # "name"修改为fastchat服务中的"model_name"
   #     "pretrained_model_name": "vicuna-v1.5",
   #     "local_model_path": None,
   #     "provides": "FastChatOpenAILLMChain",  # 使用fastchat api时，需保证"provides"为"FastChatOpenAILLMChain"
   #     "api_b:ase_url": "http://xxx.xxx.xxx.xxx:xxxx/v1",  # "name"修改为fastchat服务中的"api_base_url"
   #     "api_key": "EMPTY"
   # },
   # "FastChat": {
   #     "model_name": "vicuna-v1.5",
   #     "api_base_url": "http://xxx.xxx.xxx.xxx:xxxx/v1",
   #     "api_key": "EMPTY",
   #     "openai_proxy": "",
   # },
    "Anthropic": {
        "model_name": "your claude model name(such as claude2-100k)",
        "api_key":"your ANTHROPIC_API_KEY",
    }
}`
```
报错
2023-11-03 15:41:29,906 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
received input message:
{'history': [{'content': '你好', 'role': 'user'},
             {'content': '正在思考...', 'role': 'assistant'}],
 'max_tokens': None,
 'model_name': 'OpenAI',
 'prompt_name': 'default',
 'query': '你好',
 'stream': True,
 'temperature': 0.3}
INFO:     127.0.0.1:45572 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-03 15:41:29,920 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-11-03 15:41:37 | INFO | stdout | INFO:     127.0.0.1:36700 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2023-11-03 15:41:37 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-11-03 15:41:37 | ERROR | stderr | Traceback (most recent call last):
2023-11-03 15:41:37 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-11-03 15:41:37 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)2023-11-03 15:41:37 | ERROR | stderr |   File "/data/app/anaconda3/envs/rag/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-03 15:41:37 | ERROR | stderr |     raise exc
2023-11-03 15:41:37 | ERROR | stderr |   File "/data/app/anaconda3/envs/rag/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-03 15:41:37 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-11-03 15:41:37 | ERROR | stderr |   File "/data/app/anaconda3/envs/rag/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-11-03 15:41:37 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-11-03 15:41:37 | ERROR | stderr |   File "/data/app/anaconda3/envs/rag/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-11-03 15:41:37 | ERROR | stderr |     await self.app(scope, receive, send)
2023-11-03 15:41:37 | ERROR | stderr |   File "/data/app/anaconda3/envs/rag/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-11-03 15:41:37 | ERROR | stderr |     response = await func(request)
2023-11-03 15:41:37 | ERROR | stderr |   File "/data/app/anaconda3/envs/rag/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
2023-11-03 15:41:37 | ERROR | stderr |     conv_template = await fetch_remote(
2023-11-03 15:41:37 | ERROR | stderr |   File "/data/app/anaconda3/envs/rag/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 82, in fetch_remote
2023-11-03 15:41:37 | ERROR | stderr |     res = res[name]
2023-11-03 15:41:37 | ERROR | stderr | KeyError: 'conv'
2023-11-03 15:41:37,429 - util.py[line:67] - INFO: message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None request_id=None response_code=500
2023-11-03 15:41:37,429 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIError: Invalid ronse object from API: 'Internal Server Error' (HTTP response code was 500).
2023-11-03 15:41:47 | INFO | stdout | INFO:     127.0.0.1:36732 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2023-11-03 15:41:47 | ERROR | stderr | ERROR:    Exception in ASGI application

**Comment by yhfgyyf** [comment]
2023-11-03 15:41:29,906 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
这里显示还是调用本地模型，不要使用Langchain_LLM_Model里设置，应该在server_config.py里设置FSCHAT_OPENAI_API，FSCHAT_MODEL_WORKERS,FSCHAT_CONTROLLER这几个参数为fastchat服务地址，本地只要启动server/api.py 和webui.py，fastchat服务器正常启动服务，这里可以用fastchat项目提供的命令分布启动，也可以直接用langchain-chatchat项目里startup.py --llm-api 来启动模型（如果有在线模型需要注册，建议以这种方式启动，启动时应设置config_server.py里FSCHAT_OPENAI_API地址为0.0.0.0，并且防火墙上放开所有fastchat服务端口，包括controller端口，worker端口（包括所有在线模型的），和openai api端口），如果端口开放不全，llm_model/list_running_models 无法获取到模型，会报‘’list错误。

**Comment by plancktree** [comment]
> 2023-11-03 15:41:29,906 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" 这里显示还是调用本地模型，不要使用Langchain_LLM_Model里设置，应该在server_config.py里设置FSCHAT_OPENAI_API，FSCHAT_MODEL_WORKERS,FSCHAT_CONTROLLER这几个参数为fastchat服务地址，本地只要启动server/api.py 和webui.py，fastchat服务器正常启动服务，这里可以用fastchat项目提供的命令分布启动，也可以直接用langchain-chatchat项目里startup.py --llm-api 来启动模型（如果有在线模型需要注册，建议以这种方式启动，启动时应设置config_server.py里FSCHAT_OPENAI_API地址为0.0.0.0，并且防火墙上放开所有fastchat服务端口，包括controller端口，worker端口（包括所有在线模型的），和openai api端口），如果端口开放不全，llm_model/list_running_models 无法获取到模型，会报‘’list错误。

我使用了您的建议修改，但依然有报错key_error,无法加载list
`当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['vicuan-v1.5'] @ cuda
{'device': 'cuda',
 'host': 'xxx',
 'infer_turbo': False,
 'langchain_model': True,
 'model_names': ['vicuan-v1.5'],
 'port': 8091,
 'worker_class': ''}
当前Embbedings模型： m3e-base @ cuda


服务端运行信息：
    Chatchat  API  Server: http://127.0.0.1:7861
==============================Langchain-Chatchat Configuration==============================


INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'all://http://xxx': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-06 16:20:25,410 - _client.py[line:1013] - INFO: HTTP Request: POST http://xxx/list_models "HTTP/1.1 404 Not Found"
2023-11-06 16:20:25,411 - llm_api.py[line:22] - ERROR: KeyError: 'models'
INFO:     127.0.0.1:39292 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'all://http://xxx': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-06 16:20:25,530 - _client.py[line:1013] - INFO: HTTP Request: POST http://xxx/list_models "HTTP/1.1 404 Not Found"
2023-11-06 16:20:25,530 - llm_api.py[line:22] - ERROR: KeyError: 'models'
INFO:     127.0.0.1:39292 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
INFO:     127.0.0.1:39292 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'all://http://xxx': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-06 16:20:25,549 - _client.py[line:1013] - INFO: HTTP Request: POST http://xxx/list_models "HTTP/1.1 404 Not Found"
2023-11-06 16:20:25,549 - llm_api.py[line:22] - ERROR: KeyError: 'models'
INFO:     127.0.0.1:39292 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK`

**Comment by plancktree** [comment]
> 2023-11-06 16:20:25,549 - _client.py[line:1013] - INFO: HTTP Request: POST http://xxx/list_models "HTTP/1.1 404 Not Found" 2023-11-06 16:20:25,549 - llm_api.py[line:22] - ERROR: KeyError: 'models' configs/server_config.py 最后 FSCHAT_CONTROLLER = { "host": ****, "port": ****, "dispatch_method": "shortest_queue", } 这里配置一定要是fastchat服务器的地址，并且端口开放，fastchat服务默认的controller端口是21001（如果不指定端口的话），chatchat项目中默认的是20001，建议先telnet 测试下fastchat服务器端口，端口如果正常，用postman测试下，或者在fastapi界面http://localhost:7861/docs#/llm_model/list_running_models 这个端口上测试下，看下返回值，只有返回正常的情况下，才能排除掉list报错。

均以配置远程服务对应端口，且telnet对应端口可以通
`# fastchat openai_api server
FSCHAT_OPENAI_API = {
    "host": xxx,
    "port": xxxx,
}

FSCHAT_MODEL_WORKERS = {
    # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
    "default": {
        "host": xxx,
        "port": xxxx,
        "device": "cuda",
...}
FSCHAT_CONTROLLER = {
    "host": xxx,
    "port":xxxx,
    "dispatch_method": "shortest_queue",
}`

**Comment by plancktree** [comment]
> 均以配置远程服务对应端口，且telnet对应端口可以通 `# fastchat openai_api server FSCHAT_OPENAI_API = { "host": xxx, "port": xxxx, }
> 
> FSCHAT_MODEL_WORKERS = { # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。 "default": { "host": xxx, "port": xxxx, "device": "cuda", ...} FSCHAT_CONTROLLER = { "host": xxx, "port":xxxx, "dispatch_method": "shortest_queue", }`

均以配置远程服务对应端口，且telnet对应端口可以通
`# fastchat openai_api server
FSCHAT_OPENAI_API = {
"host": xxx,
"port": xxxx,
}

FSCHAT_MODEL_WORKERS = {
# 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
"default": {
"host": xxx,
"port": xxxx,
"device": "cuda",
...}
FSCHAT_CONTROLLER = {
"host": xxx,
"port":xxxx,
"dispatch_method": "shortest_queue",
}`

配置了

**Comment by yhfgyyf** [comment]
api日志上看下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49861869/a6c05d91-de34-4a92-9431-6bba1461f9c1)
这里的ip地址和端口,与server_config.py是否一致，
FSCHAT_CONTROLLER = {
"host": xxx,
"port":xxxx,
"dispatch_method": "shortest_queue",
}`
如果一致，用postman测试下，是否正常返回
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49861869/c2549d2c-0e24-419d-88dd-f4c567483c1c)

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.7修复了这个问题，去掉了LANGCHAIN_LLM_MODEL，直接都用fschat走了
