### ISSUE TITLE
RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by IssacCzy** [chatchat-space/Langchain-Chatchat#1969]
### 服务正常启动
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17309821/ed3e2393-1b08-441a-bb6e-62743217ea9d)

### 但进行推理时报如下异常：
`
UnboundLocalError: local variable 'model' referenced before assignment
2023-11-04 14:27:11,114 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
`

### 详细日志如下：

`INFO:     127.0.0.1:54793 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-04 14:27:11,099 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'chatglm2-6b',
 'prompt_name': 'default',
 'query': '你是谁',
 'stream': True,
 'temperature': 0.7}
INFO:     127.0.0.1:54793 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-04 14:27:11,109 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "d:\ProgramData\anaconda3\envs\chatchat_3.10\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "D:\Projects\Langchain-Chatchat\server\chat\chat.py", line 37, in chat_iterator
    model = get_ChatOpenAI(
  File "D:\Projects\Langchain-Chatchat\server\utils.py", line 100, in get_ChatOpenAI
    return model
UnboundLocalError: local variable 'model' referenced before assignment
2023-11-04 14:27:11,114 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)`

### model_config.py 配置如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17309821/3739eed7-2b3e-4c5c-80c8-fa273ffdd60c)

### server_config.py 配置如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17309821/f740ee59-d649-4e87-a159-437982d1513c)

求老师帮忙指点问题，非常感谢

**Comment by zhmfalove** [comment]
我也是同样的错误 完全没法使用

**Comment by lv199882** [comment]
我也是

**Comment by mangx** [comment]
我也是

**Comment by bulabaka** [comment]
同

**Comment by snamper** [comment]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: chat_history
[SQL: INSERT INTO chat_history (id, chat_type, "query", response, meta_data, feedback_score, feedback_reason, create_time) VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP) RETURNING create_time]
[parameters: ('bf2ab0ddd7394746b8c704ce2bb9b257', 'llm_chat', '好', '', '{}', -1, '')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
 应该是没初始化表问题吧

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新0.2.7版本，按照wiki的步骤来配置，这个配置感觉不对

**Comment by nanayashiki1215** [comment]
把openai版本从1.1换成0.28.1，或者把langchain版本换为>=v0.0.331rc2

**Comment by IssacCzy** [comment]
我现在升级到了最新版本 0.2.7 依然存在该问题，readme.md 写的太简陋了

**Comment by IssacCzy** [comment]
> 把openai版本从1.1换成0.28.1，或者把langchain版本换为>=v0.0.331rc2

谢谢，试了，没有效果，问题依然存在

**Comment by applepieiris** [comment]
> > 更新到最新0.2.7版本，按照wiki的步骤来配置，这个配置感觉不对
> 
> 是最新版本了，就是按照wiki来走的，问题依然存在 主要是配置文件建议官方写的再详细一些，按照 readme.md 根本起不来

是的，旧版本的都跑的起来，git merge新的更新之后我也是这个问题，着急死了。

**Comment by callanwu** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/issues/2014#issuecomment-1806967863

**Comment by zRzRzRzRzRzRzR** [comment]
有一个wiki，可以看一下，这类问题应该能解决
