### ISSUE TITLE
[BUG] API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by bulabaka** [chatchat-space/Langchain-Chatchat#1990]
**问题描述 / Problem Description**
UI界面访问时报错
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

用API访问也报错
ERROR: AttributeError: 获取ChatCompletion时出错：module 'openai' has no attribute 'ChatCompletion' 

**复现问题的步骤 / Steps to Reproduce**
2023.11.8 从git拉最新代码V0.2.6
严格按“快速上手”描述的步骤执行，配置文件只改了model_config.py中的MODEL_ROOT_PATH，指定为本地模型根路径

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.6
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：默认
- 操作系统及版本 / Operating system and version:win10
- Python 版本 / Python version:3.10.12
- 其他相关环境信息 / Other relevant environment information:

----UI界面访问时报错------------------------------

  URL: http://127.0.0.1:8501

{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://':
 None, 'https://': None, 'all://': None, 'http://localhost': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': No
ne, 'http://localhost': None}}
2023-11-08 10:46:18,172 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59737 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-08 10:46:18,174 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': No
ne, 'http://localhost': None}}
2023-11-08 10:46:18,512 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59737 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-08 10:46:18,514 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59737 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-08 10:46:18,517 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': No
ne, 'http://localhost': None}}
2023-11-08 10:46:18,747 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59737 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-08 10:46:18,749 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://':
 None, 'https://': None, 'all://': None, 'http://localhost': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': No
ne, 'http://localhost': None}}
2023-11-08 10:46:20,977 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59757 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-08 10:46:20,980 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': No
ne, 'http://localhost': None}}
2023-11-08 10:46:21,326 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59757 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-08 10:46:21,329 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59757 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-08 10:46:21,334 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': No
ne, 'http://localhost': None}}
2023-11-08 10:46:21,583 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59757 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-08 10:46:21,585 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://':
 None, 'https://': None, 'all://': None, 'http://localhost': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': No
ne, 'http://localhost': None}}
2023-11-08 10:46:24,501 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59788 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-08 10:46:24,503 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59788 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-08 10:46:24,506 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': No
ne, 'http://localhost': None}}
2023-11-08 10:46:24,741 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59788 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-08 10:46:24,744 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'chatglm2-6b',
 'prompt_name': 'default',
 'query': '你好',
 'stream': True,
 'temperature': 0.7}
INFO:     127.0.0.1:59788 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-08 10:46:24,750 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 250, in listen_for_disconnect
    message = await receive()
  File "G:\python\anaconda3\envs\langchain\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 538, in receive
    await self.message_event.wait()
  File "G:\python\anaconda3\envs\langchain\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 28564fcdc90

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\fastapi\applications.py", line 1106, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
  |     raise exc
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
  |     await self.app(scope, receive, sender)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
  |     raise e
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
  |     await self.app(scope, receive, send)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 718, in __call__
  |     await route.handle(scope, receive, send)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 276, in handle
  |     await self.app(scope, receive, send)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 69, in app
  |     await response(scope, receive, send)
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 270, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 273, in wrap
    |     await func()
    |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 262, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "G:\python\python_workspace\Langchain-Chatchat\server\chat\chat.py", line 37, in chat_iterator
    |     model = get_ChatOpenAI(
    |   File "G:\python\python_workspace\Langchain-Chatchat\server\utils.py", line 87, in get_ChatOpenAI
    |     model = ChatOpenAI(
    |   File "G:\python\anaconda3\envs\langchain\lib\site-packages\langchain\load\serializable.py", line 97, in __init__
    |     super().__init__(**kwargs)
    |   File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    | pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
    | __root__
    |   `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgra
de openai`. (type=value_error)
    +------------------------------------
2023-11-08 10:46:24,759 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

----用API访问也报错--------------------------------------------------------------------------------------
openai.api_key='EMPTY'
openai.api_base='http://127.0.0.1:20000/v1'
model='chatglm2-6b' messages=[OpenAiMessage(role='user', content='hello')] temperature=0.7 n=1 max_tokens=0 stop=[] stream=False presence_penalty=0 freque
ncy_penalty=0
INFO:     127.0.0.1:60554 - "POST /chat/fastchat HTTP/1.1" 200 OK
2023-11-08 10:57:19,182 - openai_chat.py[line:52] - ERROR: AttributeError: 获取ChatCompletion时出错：module 'openai' has no attribute 'ChatCompletion'

**Comment by hawcat** [comment]
把openai版本从1.1换成0.28.1再试试，想兼容1.1得等他们来更新了

**Comment by Mercy1101** [comment]
> 把openai版本从1.1换成0.28.1，或者把langchain版本换为>=v0.0.331rc2

我把openai降级为0.28.1 可以运行

**Comment by bulabaka** [comment]
> > 把openai版本从1.1换成0.28.1，或者把langchain版本换为>=v0.0.331rc2
> 
> 我把openai降级为0.28.1 可以运行

谢谢，搞定，不过为什么会用到openai，不是本地私有化部署？这样断网了还能用吗？

**Comment by amberccR** [comment]
> > > 把openai版本从1.1换成0.28.1，或者把langchain版本换为>=v0.0.331rc2
> > 
> > 
> > 我把openai降级为0.28.1 可以运行
> 
> 谢谢，搞定，不过为什么会用到openai，不是本地私有化部署？这样断网了还能用吗？

> 请问就是简单的pip install openai==0.28.1就可以吗？还是直接修改requirements.txt直接下载呢？好像还会出现其他的适配问题

**Comment by Alan-zhong** [comment]
openai降级后报错：mportError: cannot import name 'AsyncOpenAI' from 'openai' (F:\Users\ASUS\anaconda3\envs\chat_environment2\Lib\site-packages\openai\__init__.py)怎么解决哇

**Comment by LIXUEGUANG002** [comment]
> openai降级后报错：mportError: cannot import name 'AsyncOpenAI' from 'openai' (F:\Users\ASUS\anaconda3\envs\chat_environment2\Lib\site-packages\openai__init__.py)怎么解决哇

我也遇到了这样的问题 ，请问一下您是怎么解决的呢？

**Comment by kernelLZ** [comment]
> > openai降级后报错：mportError: cannot import name 'AsyncOpenAI' from 'openai' (F:\Users\ASUS\anaconda3\envs\chat_environment2\Lib\site-packages\openai__init__.py)怎么解决哇
> 
> 我也遇到了这样的问题 ，请问一下您是怎么解决的呢？

我也是，求解决方法。

**Comment by TwinkleYR** [comment]
> > > openai降级后报错：mportError: cannot import name 'AsyncOpenAI' from 'openai' (F:\Users\ASUS\anaconda3\envs\chat_environment2\Lib\site-packages\openai__init__.py)怎么解决哇
> > 
> > 
> > 我也遇到了这样的问题 ，请问一下您是怎么解决的呢？
> 
> 我也是，求解决方法。

我查看代码，注释了knowledge_base_chat.py中的from server.reranker.reranker import LangchainReranker，即不调用openai，不报上面的错了，但是还是会报peer closed connection without sending complete message body的问题
