### ISSUE TITLE
[BUG] 使用-p启动无法建立连接

### ISSUE THREAD

**Issue by Xintakazi** [chatchat-space/Langchain-Chatchat#1993]
**问题描述 / Problem Description**
直接启动会报错
```bash
2023-11-08 15:31:06 | ERROR | stderr | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6725fed150>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**复现问题的步骤 / Steps to Reproduce**
1. clone下最新仓库
2. 配置好环境（可以本地部署）
3. 配置好智谱的KEY
4. 使用`python startup.py -p`运行
5. 报错

**预期的结果 / Expected Result**
调用智谱的API运行知识库

**实际结果 / Actual Result**
```bash
2023-11-08 15:31:02,839 - startup.py[line:626] - INFO: 正在启动服务：
2023-11-08 15:31:02,839 - startup.py[line:627] - INFO: 如需查看 llm_api 日志，请前往 /home/davis/Langchain-Chatchat/logs
2023-11-08 15:31:06 | INFO | model_worker | Register to controller
2023-11-08 15:31:06 | ERROR | stderr | Process api_worker - zhipu-api:
2023-11-08 15:31:06 | ERROR | stderr | Traceback (most recent call last):
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
2023-11-08 15:31:06 | ERROR | stderr |     sock = connection.create_connection(
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
2023-11-08 15:31:06 | ERROR | stderr |     raise err
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
2023-11-08 15:31:06 | ERROR | stderr |     sock.connect(sa)
2023-11-08 15:31:06 | ERROR | stderr | ConnectionRefusedError: [Errno 111] Connection refused
2023-11-08 15:31:06 | ERROR | stderr |
2023-11-08 15:31:06 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-11-08 15:31:06 | ERROR | stderr |
2023-11-08 15:31:06 | ERROR | stderr | Traceback (most recent call last):
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
2023-11-08 15:31:06 | ERROR | stderr |     response = self._make_request(
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
2023-11-08 15:31:06 | ERROR | stderr |     conn.request(
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
2023-11-08 15:31:06 | ERROR | stderr |     self.endheaders()
2023-11-08 15:31:06 | ERROR | stderr |   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
2023-11-08 15:31:06 | ERROR | stderr |     self._send_output(message_body, encode_chunked=encode_chunked)
2023-11-08 15:31:06 | ERROR | stderr |   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
2023-11-08 15:31:06 | ERROR | stderr |     self.send(msg)
2023-11-08 15:31:06 | ERROR | stderr |   File "/usr/lib/python3.10/http/client.py", line 976, in send
2023-11-08 15:31:06 | ERROR | stderr |     self.connect()
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
2023-11-08 15:31:06 | ERROR | stderr |     self.sock = self._new_conn()
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
2023-11-08 15:31:06 | ERROR | stderr |     raise NewConnectionError(
2023-11-08 15:31:06 | ERROR | stderr | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6725fed150>: Failed to establish a new connection: [Errno 111] Connection refused
2023-11-08 15:31:06 | ERROR | stderr |
2023-11-08 15:31:06 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-11-08 15:31:06 | ERROR | stderr |
2023-11-08 15:31:06 | ERROR | stderr | Traceback (most recent call last):
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
2023-11-08 15:31:06 | ERROR | stderr |     resp = conn.urlopen(
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
2023-11-08 15:31:06 | ERROR | stderr |     retries = retries.increment(
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
2023-11-08 15:31:06 | ERROR | stderr |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2023-11-08 15:31:06 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6725fed150>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-11-08 15:31:06 | ERROR | stderr |
2023-11-08 15:31:06 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-11-08 15:31:06 | ERROR | stderr |
2023-11-08 15:31:06 | ERROR | stderr | Traceback (most recent call last):
2023-11-08 15:31:06 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-08 15:31:06 | ERROR | stderr |     self.run()
2023-11-08 15:31:06 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-08 15:31:06 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/Langchain-Chatchat/startup.py", line 382, in run_model_worker
2023-11-08 15:31:06 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/Langchain-Chatchat/startup.py", line 97, in create_model_worker_app
2023-11-08 15:31:06 | ERROR | stderr |     worker = worker_class(model_names=args.model_names,
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/Langchain-Chatchat/server/model_workers/zhipu.py", line 23, in __init__
2023-11-08 15:31:06 | ERROR | stderr |     super().__init__(**kwargs)
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/Langchain-Chatchat/server/model_workers/base.py", line 44, in __init__
2023-11-08 15:31:06 | ERROR | stderr |     self.init_heart_beat()
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/fastchat/serve/base_model_worker.py", line 79, in init_heart_beat
2023-11-08 15:31:06 | ERROR | stderr |     self.register_to_controller()
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/fastchat/serve/base_model_worker.py", line 96, in register_to_controller
2023-11-08 15:31:06 | ERROR | stderr |     r = requests.post(url, json=data)
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/requests/api.py", line 115, in post
2023-11-08 15:31:06 | ERROR | stderr |     return request("post", url, data=data, json=json, **kwargs)
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
2023-11-08 15:31:06 | ERROR | stderr |     return session.request(method=method, url=url, **kwargs)
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
2023-11-08 15:31:06 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
2023-11-08 15:31:06 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2023-11-08 15:31:06 | ERROR | stderr |   File "/home/davis/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
2023-11-08 15:31:06 | ERROR | stderr |     raise ConnectionError(e, request=request)
2023-11-08 15:31:06 | ERROR | stderr | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6725fed150>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.6 
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：智谱API KEY
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本: WSL Ubuntu22.04
- Python 版本 / Python version:  3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
- 已经成功本地运行，由于显卡太差切换智谱API KEY

**Comment by promexjm** [comment]
本地运行，你没遇到这个问题?
ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by Xintakazi** [comment]
> 本地运行，你没遇到这个问题?
> ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

在刚刚有一个关闭的issue有解。
requirement里面改为openai降0.28.1 可

**Comment by pengyixuan** [comment]
> > 本地运行，你没遇到这个问题?
> > ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
> 
> 在刚刚有一个关闭的issue有解。 requirement里面改为openai~=0.28.1 就可以了

卸载后直接使用openai==0.28.1，就可以了

**Comment by Xintakazi** [comment]
并没有我自己问题的解决方案出现，为什么关闭issue了呢
