### ISSUE TITLE
请问如何支持YI模型，即零一万物最新的模型

### ISSUE THREAD

**Issue by ArlanCooper** [chatchat-space/Langchain-Chatchat#1994]
零一万物刚上线了一个支持200k输入的大模型，github地址如下：
https://github.com/01-ai/Yi

我在直接配置到model_config里面之后：
```
"Yi-6B-200K": {
        "local_model_path": "/data/share/Yi-6B-200K",
        "api_base_url": "http://localhost:8888/v1",  # "name"修改为fastchat服务中的"api_base_url"
        "api_key": "EMPTY"
    },

```

然后报错：
```

Process model_worker - Yi-6B-200K:
Traceback (most recent call last):
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 63, in load_model
tokenizer = AutoTokenizer.from_pretrained(
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 723, in from_pretrained
return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
return cls._from_pretrained(
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
tokenizer = cls(*init_inputs, **init_kwargs)
File "/home/powerop/.cache/huggingface/modules/transformers_modules/Yi-6B-200K/tokenization_yi.py", line 72, in init
self.sp_model.Load(vocab_file)
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/init.py", line 905, in Load
return self.LoadFromFile(model_file)
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/init.py", line 310, in LoadFromFile
return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 303, in run_model_worker
app = create_model_worker_app(log_level=log_level, **kwargs)
File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
worker = ModelWorker(
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 213, in init
self.model, self.tokenizer = load_model(
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 279, in load_model
model, tokenizer = adapter.load_model(model_path, kwargs)
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 70, in load_model
tokenizer = AutoTokenizer.from_pretrained(
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 723, in from_pretrained
return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
return cls._from_pretrained(
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
tokenizer = cls(*init_inputs, **init_kwargs)
File "/home/powerop/.cache/huggingface/modules/transformers_modules/Yi-6B-200K/tokenization_yi.py", line 72, in init
self.sp_model.Load(vocab_file)
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/init.py", line 905, in Load
return self.LoadFromFile(model_file)
File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/init.py", line 310, in LoadFromFile
return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

```

请问下可以支持这个模型吗？

**Comment by liuxjerry** [comment]
当前fastchat还不支持，本项目通过fastchat调用LLM，所以暂时还不支持。
另外，Yi当前是base模型不是chat模型，所以即使支持了对本项目也没有直接的用处。

**Comment by pingxue-hfut** [comment]
使用本地模型方式，通过修改\envs\longchain\Lib\site-packages\transformers\dynamic_module_utils.py的resolve_trust_remote_code函数，让其始终return True，可以跳过检查，支持Yi模型
