### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [chatchat-space/Langchain-Chatchat#1995]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

Package                       Version
----------------------------- ------------
accelerate                    0.24.1
aiofiles                      23.2.1
aiohttp                       3.8.6
aiosignal                     1.3.1
altair                        5.1.2
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
async-timeout                 4.0.3
attrs                         23.1.0
backoff                       2.2.1
beautifulsoup4                4.12.2
blinker                       1.7.0
blis                          0.7.11
Brotli                        1.1.0
cachetools                    5.3.2
catalogue                     2.0.10
certifi                       2023.7.22
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpathlib                  0.16.0
colorama                      0.4.6
coloredlogs                   15.0.1
confection                    0.1.3
contourpy                     1.2.0
cryptography                  41.0.5
cycler                        0.12.1
cymem                         2.0.8
dataclasses-json              0.6.1
distro                        1.8.0
duckduckgo-search             3.9.4
effdet                        0.4.1
einops                        0.7.0
emoji                         2.8.0
et-xmlfile                    1.1.0
exceptiongroup                1.1.3
faiss-cpu                     1.7.4
fastapi                       0.104.1
filelock                      3.13.1
filetype                      1.2.0
flatbuffers                   23.5.26
fonttools                     4.44.0
frozenlist                    1.4.0
fschat                        0.2.31
fsspec                        2023.10.0
gitdb                         4.0.11
GitPython                     3.1.40
greenlet                      3.0.1
h11                           0.14.0
h2                            4.1.0
hpack                         4.0.0
httpcore                      0.17.3
httpx                         0.25.1
huggingface-hub               0.17.3
humanfriendly                 10.0
hyperframe                    6.0.1
idna                          3.4
importlib-metadata            6.8.0
iniconfig                     2.0.0
iopath                        0.1.10
Jinja2                        3.1.2
joblib                        1.3.2
jsonpatch                     1.33
jsonpointer                   2.4
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
kiwisolver                    1.4.5
langchain                     0.0.331
langchain-experimental        0.0.38
langcodes                     3.3.0
langdetect                    1.0.9
langsmith                     0.0.60
layoutparser                  0.3.4
lxml                          4.9.3
Markdown                      3.5.1
markdown-it-py                3.0.0
markdown2                     2.4.10
MarkupSafe                    2.1.3
marshmallow                   3.20.1
matplotlib                    3.8.1
mdurl                         0.1.2
mpmath                        1.3.0
msg-parser                    1.2.0
multidict                     6.0.4
murmurhash                    1.0.10
mypy-extensions               1.0.0
networkx                      3.2.1
nh3                           0.2.14
nltk                          3.8.1
numexpr                       2.8.7
numpy                         1.24.4
olefile                       0.46
omegaconf                     2.3.0
onnx                          1.15.0
onnxruntime                   1.15.1
openai                        0.28.1
opencv-python                 4.8.1.78
openpyxl                      3.1.2
packaging                     23.2
pandas                        2.0.3
pathlib                       1.0.1
pdf2image                     1.16.3
pdfminer.six                  20221105
pdfplumber                    0.10.3
peft                          0.6.0
Pillow                        10.1.0
pip                           23.3.1
pluggy                        1.3.0
portalocker                   2.8.2
preshed                       3.0.9
prompt-toolkit                3.0.39
protobuf                      4.25.0
psutil                        5.9.6
pyarrow                       14.0.0
pyclipper                     1.3.0.post5
pycocotools                   2.0.7
pycparser                     2.21
pydantic                      1.10.13
pydeck                        0.8.1b0
Pygments                      2.16.1
PyMuPDF                       1.22.5
PyMuPDFb                      1.23.6
pypandoc                      1.12
pyparsing                     3.1.1
pypdfium2                     4.23.1
pyreadline3                   3.4.1
PySocks                       1.7.1
pytesseract                   0.3.10
pytest                        7.4.3
python-dateutil               2.8.2
python-decouple               3.8
python-docx                   1.1.0
python-iso639                 2023.6.15
python-magic                  0.4.27
python-magic-bin              0.4.14
python-multipart              0.0.6
python-pptx                   0.6.21
pytz                          2023.3.post1
pywin32                       306
PyYAML                        6.0.1
rapidfuzz                     3.5.2
rapidocr-onnxruntime          1.3.8
referencing                   0.30.2
regex                         2023.10.3
requests                      2.31.0
rich                          13.6.0
rpds-py                       0.12.0
safetensors                   0.4.0
scikit-learn                  1.3.2
scipy                         1.11.3
sentence-transformers         2.2.2
sentencepiece                 0.1.99
setuptools                    68.2.2
shapely                       2.0.2
shortuuid                     1.0.11
simplejson                    3.19.2
six                           1.16.0
smart-open                    6.4.0
smmap                         5.0.1
sniffio                       1.3.0
socksio                       1.0.0
soupsieve                     2.5
spacy                         3.7.2
spacy-legacy                  3.0.12
spacy-loggers                 1.0.5
SQLAlchemy                    2.0.19
srsly                         2.4.8
starlette                     0.27.0
streamlit                     1.28.1
streamlit-aggrid              0.3.4.post3
streamlit-antd-components     0.2.3
streamlit-chatbox             1.1.10
streamlit-option-menu         0.3.6
svgwrite                      1.4.3
sympy                         1.12
tabulate                      0.9.0
tenacity                      8.2.3
thinc                         8.2.1
threadpoolctl                 3.2.0
tiktoken                      0.5.1
timm                          0.9.10
tokenizers                    0.14.1
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
torch                         2.1.0
torchaudio                    2.1.0
torchvision                   0.16.0
tornado                       6.3.3
tqdm                          4.66.1
transformers                  4.35.0
transformers-stream-generator 0.0.4
typer                         0.9.0
typing_extensions             4.8.0
typing-inspect                0.9.0
tzdata                        2023.3
tzlocal                       5.2
unstructured                  0.10.29
unstructured-inference        0.7.11
unstructured.pytesseract      0.3.12
urllib3                       2.0.7
uvicorn                       0.23.2
validators                    0.22.0
watchdog                      3.0.0
wavedrom                      2.0.3.post3
wcwidth                       0.2.9
weasel                        0.3.4
websockets                    12.0
wheel                         0.41.3
win-inet-pton                 1.1.0
xformers                      0.0.22.post7
xlrd                          2.0.1
XlsxWriter                    3.1.9
yarl                          1.9.2
zipp                          3.17.0

python版本：3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:18:13) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.6
langchain版本：0.0.319. fastchat版本：0.2.31
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b-int4'] @ cuda

received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'chatglm2-6b-int4',
 'prompt_name': 'default',
 'query': '你好',
 'stream': True,
 'temperature': 0.7}
INFO:     127.0.0.1:16715 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-08 20:02:23,173 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-11-08 20:02:23 | INFO | stdout | INFO:     127.0.0.1:16719 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-11-08 20:02:23,246 - util.py[line:67] - INFO: message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None request_id=None response_code=20
0
2023-11-08 20:02:23 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 104, in generate_stream_gate
    for output in self.generate_stream_func(
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastchat\model\model_chatglm.py", line 71, in generate_stream_chatglm
    for total_ids in model.stream_generate(**inputs, **gen_kwargs):
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 1149, in stream_generate
    outputs = self(
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 544, in forward
    attention_output, kv_cache = self.self_attention(
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 376, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 502, in forward
    output = W8A16Linear.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 75, in forward
    weight = extract_weight_to_half(quant_w, scale_w, weight_bit_width)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 287, in extract_weight_to_half
    func = kernels.int4WeightExtractionHalf
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'
2023-11-08 20:02:26 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-11-08 20:02:26 | ERROR | stderr | Traceback (most recent call last):
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
2023-11-08 20:02:26 | ERROR | stderr |     yield
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 197, in _receive_event
2023-11-08 20:02:26 | ERROR | stderr |     event = self._h11_state.next_event()
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\h11\_connection.py", line 469, in next_event
2023-11-08 20:02:26 | ERROR | stderr |     event = self._extract_next_receive_event()
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\h11\_connection.py", line 419, in _extract_next_receive_event
2023-11-08 20:02:26 | ERROR | stderr |     event = self._reader.read_eof()  # type: ignore[attr-defined]
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\h11\_readers.py", line 204, in read_eof
2023-11-08 20:02:26 | ERROR | stderr |     raise RemoteProtocolError(
2023-11-08 20:02:26 | ERROR | stderr | h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2023-11-08 20:02:26 | ERROR | stderr |
2023-11-08 20:02:26 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-11-08 20:02:26 | ERROR | stderr |
2023-11-08 20:02:26 | ERROR | stderr | Traceback (most recent call last):
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions      
2023-11-08 20:02:26 | ERROR | stderr |     yield
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpx\_transports\default.py", line 249, in __aiter__
2023-11-08 20:02:26 | ERROR | stderr |     async for part in self._httpcore_stream:
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\connection_pool.py", line 347, in __aiter__
2023-11-08 20:02:26 | ERROR | stderr |     async for part in self._stream:
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 325, in __aiter__
2023-11-08 20:02:26 | ERROR | stderr |     raise exc
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 317, in __aiter__
2023-11-08 20:02:26 | ERROR | stderr |     async for chunk in self._connection._receive_response_body(**kwargs):
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_body
2023-11-08 20:02:26 | ERROR | stderr |     event = await self._receive_event(timeout=timeout)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpcore\_async\http11.py", line 196, in _receive_event
2023-11-08 20:02:26 | ERROR | stderr |     with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\contextlib.py", line 153, in __exit__
2023-11-08 20:02:26 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
2023-11-08 20:02:26 | ERROR | stderr |     raise to_exc(exc) from exc
2023-11-08 20:02:26 | ERROR | stderr | httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2023-11-08 20:02:26 | ERROR | stderr |
2023-11-08 20:02:26 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-11-08 20:02:26 | ERROR | stderr |
2023-11-08 20:02:26 | ERROR | stderr | Traceback (most recent call last):
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
2023-11-08 20:02:26 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastapi\applications.py", line 1106, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\applications.py", line 122, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     raise exc
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     await self.app(scope, receive, send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     raise exc
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     raise e
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     await self.app(scope, receive, send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\routing.py", line 718, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\routing.py", line 276, in handle
2023-11-08 20:02:26 | ERROR | stderr |     await self.app(scope, receive, send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\routing.py", line 69, in app
2023-11-08 20:02:26 | ERROR | stderr |     await response(scope, receive, send)
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\responses.py", line 270, in __call__
2023-11-08 20:02:26 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
2023-11-08 20:02:26 | ERROR | stderr |     raise exceptions[0]
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\responses.py", line 273, in wrap
2023-11-08 20:02:26 | ERROR | stderr |     await func()
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\starlette\responses.py", line 262, in stream_response
2023-11-08 20:02:26 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastchat\serve\openai_api_server.py", line 422, in chat_completion_strea
m_generator
2023-11-08 20:02:26 | ERROR | stderr |     async for content in generate_completion_stream(gen_params, worker_addr):
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\fastchat\serve\openai_api_server.py", line 592, in generate_completion_s
tream
2023-11-08 20:02:26 | ERROR | stderr |     async for raw_chunk in response.aiter_raw():
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpx\_models.py", line 990, in aiter_raw
2023-11-08 20:02:26 | ERROR | stderr |     async for raw_stream_bytes in self.stream:
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpx\_client.py", line 146, in __aiter__
2023-11-08 20:02:26 | ERROR | stderr |     async for chunk in self._stream:
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\site-packages\httpx\_transports\default.py", line 248, in __aiter__
2023-11-08 20:02:26 | ERROR | stderr |     with map_httpcore_exceptions():
2023-11-08 20:02:26 | ERROR | stderr |   File "C:\Users\anaconda3\envs\chatchat\lib\contextlib.py", line 153, in __exit__
2023-11-08 20:02:26 | ERROR | stderr |     self.gen.throw(typ, value, traceback)

**Comment by LIXUEGUANG002** [comment]
请问怎么解决的呢 ？ 我也出现了这样的错误
