### ISSUE TITLE
[BUG] Docker版镜像执行錯誤: torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by TheresaCBE** [chatchat-space/Langchain-Chatchat#2006]
**问题描述 / Problem Description**
## Docker Log
報錯後就一直卡在尾部
```BASH
2023-11-09 23:46:19,557 - startup.py[line:626] - INFO: 正在启动服务：
2023-11-09 23:46:19,557 - startup.py[line:627] - INFO: 如需查看 llm_api 日志，请前往 /langchain-chatchat/logs
2023-11-09 23:46:21,468 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpexoim9cg
2023-11-09 23:46:21,468 - instantiator.py[line:76] - INFO: Writing /tmp/tmpexoim9cg/_remote_module_non_scriptable.py
2023-11-09 23:46:21 | ERROR | stderr | INFO:     Started server process [149]
2023-11-09 23:46:21 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-09 23:46:21 | ERROR | stderr | INFO:     Application startup complete.
2023-11-09 23:46:21 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-11-09 23:46:21,498 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpbxiga_x1
2023-11-09 23:46:21,498 - instantiator.py[line:76] - INFO: Writing /tmp/tmpbxiga_x1/_remote_module_non_scriptable.py
2023-11-09 23:46:21 | INFO | model_worker | Register to controller
2023-11-09 23:46:21 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 839c70ed ...
Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|█▍        | 1/7 [00:00<00:03,  1.51it/s]
Loading checkpoint shards:  29%|██▊       | 2/7 [00:01<00:03,  1.45it/s]
Loading checkpoint shards:  43%|████▎     | 3/7 [00:02<00:02,  1.44it/s]
Loading checkpoint shards:  57%|█████▋    | 4/7 [00:02<00:02,  1.47it/s]
Loading checkpoint shards:  71%|███████▏  | 5/7 [00:03<00:01,  1.45it/s]
Loading checkpoint shards:  86%|████████▌ | 6/7 [00:04<00:00,  1.44it/s]
Loading checkpoint shards: 100%|██████████| 7/7 [00:04<00:00,  1.69it/s]
Loading checkpoint shards: 100%|██████████| 7/7 [00:04<00:00,  1.55it/s]
2023-11-09 23:46:26 | ERROR | stderr | 
2023-11-09 23:46:27 | ERROR | stderr | Process model_worker - chatglm2-6b:
2023-11-09 23:46:27 | ERROR | stderr | Traceback (most recent call last):
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-09 23:46:27 | ERROR | stderr |     self.run()
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-09 23:46:27 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-09 23:46:27 | ERROR | stderr |   File "/langchain-chatchat/startup.py", line 382, in run_model_worker
2023-11-09 23:46:27 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-09 23:46:27 | ERROR | stderr |   File "/langchain-chatchat/startup.py", line 210, in create_model_worker_app
2023-11-09 23:46:27 | ERROR | stderr |     worker = ModelWorker(
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-11-09 23:46:27 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 308, in load_model
2023-11-09 23:46:27 | ERROR | stderr |     model.to(device)
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2179, in to
2023-11-09 23:46:27 | ERROR | stderr |     return super().to(*args, **kwargs)
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1145, in to
2023-11-09 23:46:27 | ERROR | stderr |     return self._apply(convert)
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 797, in _apply
2023-11-09 23:46:27 | ERROR | stderr |     module._apply(fn)
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 797, in _apply
2023-11-09 23:46:27 | ERROR | stderr |     module._apply(fn)
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 820, in _apply
2023-11-09 23:46:27 | ERROR | stderr |     param_applied = fn(param)
2023-11-09 23:46:27 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1143, in convert
2023-11-09 23:46:27 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2023-11-09 23:46:27 | ERROR | stderr | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 508.00 MiB (GPU 0; 11.56 GiB total capacity; 11.16 GiB already allocated; 138.62 MiB free; 11.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```
## NVIDIA SMI
```bash
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   44C    P8              25W / 350W |      4MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**复现问题的步骤 / Steps to Reproduce**
1. 执行此專案Docker image v0.2.6
2. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
打开WEBUI或成功執行镜像

**实际结果 / Actual Result**
`无法`打开WEBUI或成功執行镜像

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：`使用 Docker 部署`
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Linux Kernel 6.1.49 (Ubuntu 22.04)
- Python 版本 / Python version: `使用 Docker 部署`
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
在一众大佬们帮忙下，虽然Docker版Image成功修复
但却执行不起来了，请各位先进们帮忙看一下了!

**Comment by zRzRzRzRzRzRzR** [comment]
12G显存可能恰好不够执行
因为 6B模型的fp16版本 + embed模型很容易就超过12G了
您需要提高硬件配置，或者，你用源码安装并用int4模型
