### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by soyisou** [chatchat-space/Langchain-Chatchat#2008]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/116480575/fadec2db-400b-4b18-9a07-f7f3a3cf5c77)

问题描述：
2023-11-10 02:00:37,911 - startup.py[line:626] - INFO: 正在启动服务：
2023-11-10 02:00:37,912 - startup.py[line:627] - INFO: 如需查看 llm_api 日志，请前往 /public26_data/ljm/Langchain-Chatchat/logs
2023-11-10 02:00:39 | ERROR | stderr | INFO:     Started server process [39139]
2023-11-10 02:00:39 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-10 02:00:39 | ERROR | stderr | INFO:     Application startup complete.
2023-11-10 02:00:39 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-11-10 02:00:41 | INFO | model_worker | Register to controller
2023-11-10 02:00:43 | ERROR | stderr | Process api_worker - zhipu-api:
2023-11-10 02:00:43 | ERROR | stderr | Traceback (most recent call last):
2023-11-10 02:00:43 | ERROR | stderr |   File "/root/anaconda/envs/chatchat/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-10 02:00:43 | ERROR | stderr |     self.run()
2023-11-10 02:00:43 | ERROR | stderr |   File "/root/anaconda/envs/chatchat/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-10 02:00:43 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-10 02:00:43 | ERROR | stderr |   File "/public26_data/ljm/Langchain-Chatchat/startup.py", line 382, in run_model_worker
2023-11-10 02:00:43 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-10 02:00:43 | ERROR | stderr |   File "/public26_data/ljm/Langchain-Chatchat/startup.py", line 97, in create_model_worker_app
2023-11-10 02:00:43 | ERROR | stderr |     worker = worker_class(model_names=args.model_names,
2023-11-10 02:00:43 | ERROR | stderr |   File "/public26_data/ljm/Langchain-Chatchat/server/model_workers/zhipu.py", line 23, in __init__
2023-11-10 02:00:43 | ERROR | stderr |     super().__init__(**kwargs)
2023-11-10 02:00:43 | ERROR | stderr |   File "/public26_data/ljm/Langchain-Chatchat/server/model_workers/base.py", line 44, in __init__
2023-11-10 02:00:43 | ERROR | stderr |     self.init_heart_beat()
2023-11-10 02:00:43 | ERROR | stderr |   File "/root/anaconda/envs/chatchat/lib/python3.10/site-packages/fastchat/serve/base_model_worker.py", line 79, in init_heart_beat
2023-11-10 02:00:43 | ERROR | stderr |     self.register_to_controller()
2023-11-10 02:00:43 | ERROR | stderr |   File "/root/anaconda/envs/chatchat/lib/python3.10/site-packages/fastchat/serve/base_model_worker.py", line 97, in register_to_controller
2023-11-10 02:00:43 | ERROR | stderr |     assert r.status_code == 200
2023-11-10 02:00:43 | ERROR | stderr | AssertionError

个人操作步骤：
1. git clone官方代码
2.pip安装三个requirements
3. 修改m3e-base路径，并指定Openai模型
4. 初始化数据库和配置文件
5.一键启动

**Comment by soyisou** [comment]
已经更替换了3台机器，严格按照官方文档重装了环境，但是依然出现此问题

**Comment by zRzRzRzRzRzRzR** [comment]
因为不能使用OpeAI启动，这个是0.2.6的bug，试着换0.2.7

**Comment by zRzRzRzRzRzRzR** [comment]
大部分的代码优化都是针对本地模型的

**Comment by HuengchI** [comment]
请问解决了吗？我今天还是遇到这个问题

**Comment by HuengchI** [comment]
> 因为不能使用OpeAI启动，这个是0.2.6的bug，试着换0.2.7

请问怎么换0.2.7呢？tag里面只能找到0.2.6。main分支上拉取下来的代码`assert r.status_code == 200`一直报错

**Comment by mars-ou1991** [comment]
执行 pip install transformers==4.33.1 ，然后  python init_database.py --recreate-vs 重新初始化知识库试试？

**Comment by liunux4odoo** [comment]
看Wiki常见问题

**Comment by HuengchI** [comment]
> 看Wiki常见问题

设置`export no_proxy='127.0.0.1'`后可以正确注册controller，但是打开webui后会出现如下错误：
```
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
2023-11-13 10:41:42,999 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
2023-11-13 10:41:43,033 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
2023-11-13 10:41:43,067 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
2023-11-13 10:41:43,218 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
2023-11-13 10:41:43,255 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
2023-11-13 10:41:43,293 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
2023-11-13 10:41:43.294 Uncaught app exception
Traceback (most recent call last):
  File "/data/bin/miniconda3/envs/py-3.10-torch-2.1/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/data/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/data/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 83, in dialogue_page
    running_models = list(api.list_running_models())
TypeError: 'NoneType' object is not iterable

```

**Comment by aleSheng** [comment]
> > 看Wiki常见问题
> 
> 设置`export no_proxy='127.0.0.1'`后可以正确注册controller，但是打开webui后会出现如下错误：
> 
> ```
> {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
> 2023-11-13 10:41:42,999 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
> {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
> 2023-11-13 10:41:43,033 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
> {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
> 2023-11-13 10:41:43,067 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
> {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
> 2023-11-13 10:41:43,218 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
> {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
> 2023-11-13 10:41:43,255 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
> {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://10.249.42.241:41122', 'https://': 'http://10.249.42.241:41122', 'all://': None, '127.0.0.1': None}}
> 2023-11-13 10:41:43,293 - utils.py[line:94] - ERROR: ValueError: error when post /llm_model/list_running_models: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "127.0.0.1", use "127.0.0.1://"
> 2023-11-13 10:41:43.294 Uncaught app exception
> Traceback (most recent call last):
>   File "/data/bin/miniconda3/envs/py-3.10-torch-2.1/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
>     exec(code, module.__dict__)
>   File "/data/Langchain-Chatchat/webui.py", line 64, in <module>
>     pages[selected_page]["func"](api=api, is_lite=is_lite)
>   File "/data/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 83, in dialogue_page
>     running_models = list(api.list_running_models())
> TypeError: 'NoneType' object is not iterable
> ```

升级之后我也碰到这个问题。之前没有

**Comment by Hagtaril** [comment]
我出现错误：
2023-11-10 02:00:43 | ERROR | stderr | assert r.status_code == 200
2023-11-10 02:00:43 | ERROR | stderr | AssertionError

然后我把代理关了就好了
