### ISSUE TITLE
[BUG] 使用最新的代码，启动项目web报错

### ISSUE THREAD

**Issue by jerryliang122** [chatchat-space/Langchain-Chatchat#2016]
**问题描述 / Problem Description**
当时仅使用openai-api 启动webui 界面时候出现报错

**报错内容如下**
2023-11-11 15:52:48,333 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-11-11 15:52:48.333 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/root/langchain-ChatGLM/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/root/langchain-ChatGLM/webui_pages/dialogue/dialogue.py", line 94, in dialogue_page
    index = llm_models.index(st.session_state.get("cur_llm_model", api.get_default_llm_model()[0]))
ValueError: '' is not in list

**实际结果 / Actual Result**
如果增加zhipu-api进LLM_MODELS ，无法在网页上选择openai-api

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：[72a1f5d]
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：openai-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / 
- 操作系统及版本 / Operating system and version: ubuntu 22.04
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information: GPU P4

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
更新到0.2.7试试，我们没有做openai的 wrapper因此这个list找不到，不能把openai放在第一个启动，如果放在第一个，会启动到其他本地模型

**Comment by jerryliang122** [comment]
更新了最新的代码。现在是这么写得
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25032918/fdc668db-1941-4d09-8efb-8b9786f701fd)
但是当启动后只有zhipu-api没有其他的了。

**Comment by erjiguan** [comment]
解决了吗
