### ISSUE TITLE
[BUG] 模型切换问题，单次切换和多次切换

### ISSUE THREAD

**Issue by Vimos** [chatchat-space/Langchain-Chatchat#2040]
1. 配置好`chatglm2-6b`和`zhipu-api`
2. 在页面上切换模型
3. 切换一次，报`ERROR: KeyError: Caught exception: 'choices'`
4. 来回切换，报下面错误

```shell

2023-11-13 16:11:34,808 - utils.py[line:25] - ERROR: KeyError: Caught exception: 'choices'
2023-11-13 16:11:34.809 Uncaught app exception
Traceback (most recent call last):
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/tt/git/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/tt/git/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 223, in dialogue_page
    chat_box.show_feedback(**feedback_kwargs,
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit_chatbox/messages.py", line 309, in show_feedback
    return streamlit_feedback(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit_feedback/__init__.py", line 97, in streamlit_feedback
    component_value = _component_func(
                      ^^^^^^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit/components/v1/components.py", line 80, in __call__
    return self.create_instance(*args, default=default, key=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 396, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit/components/v1/components.py", line 241, in create_instance
    return_value = marshall_component(dg, element)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit/components/v1/components.py", line 212, in marshall_component
    component_state = register_widget(
                      ^^^^^^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit_option_menu/streamlit_callback.py", line 20, in wrapper_register_widget
    return register_widget(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/state/widgets.py", line 161, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/state/widgets.py", line 194, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple widgets with the same `key=''`.

To fix this, please make sure that the `key` argument is unique for each
widget you create.
```

**Comment by Leweibo** [comment]
我也出现此错误，调用ONLINE_LLM_MODEL出错。

**Comment by Leweibo** [comment]
DuplicateWidgetID: There are multiple widgets with the same key=''.

To fix this, please make sure that the key argument is unique for each widget you create.

Traceback:
File "D:\Wechat\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
File "D:\Wechat\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 178, in dialogue_page
    chat_box.output_messages()
File "C:\Users\lwb\.conda\envs\lc\lib\site-packages\streamlit_chatbox\messages.py", line 337, in output_messages
    self.show_feedback(history_index=i, **feedback_kwargs)
File "C:\Users\lwb\.conda\envs\lc\lib\site-packages\streamlit_chatbox\messages.py", line 309, in show_feedback
    return streamlit_feedback(**kwargs)
File "C:\Users\lwb\.conda\envs\lc\lib\site-packages\streamlit_feedback\__init__.py", line 97, in streamlit_feedback
    component_value = _component_func(
File "C:\Users\lwb\.conda\envs\lc\lib\site-packages\streamlit_option_menu\streamlit_callback.py", line 20, in wrapper_register_widget
    return register_widget(*args, **kwargs)

**Comment by zRzRzRzRzRzRzR** [comment]
更新到0.2.8解决问题

**Comment by DOVEEEEEEEEEEEEE** [comment]
> 20231205，安装0.2.8后依旧出现此现象，尝试过更新langchain，版本0.0.345 ![image](https://private-user-images.githubusercontent.com/30493911/288063223-fe712b81-2fa8-436e-9225-5946860ba3fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTEyMzAsIm5iZiI6MTcwMzIxMDkzMCwicGF0aCI6Ii8zMDQ5MzkxMS8yODgwNjMyMjMtZmU3MTJiODEtMmZhOC00MzZlLTkyMjUtNTk0Njg2MGJhM2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAyMDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNjU3YmU1MjQ3OTllZGUzY2Y3YzE5NGYxMzMwZDEyMjQwOWZkODQzNTU5MmFjODk0ZjA5YmViZmI3Zjg3YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.56lM9EJuTq7KukROAtgkiLo5cTdItmv4tm2O9Quaap4)

请问解决了嘛 我也遇到了类似的
