### ISSUE TITLE
相同底座的lora模型切换时不需要重新加载底座

### ISSUE THREAD

**Issue by Fraudsterrrr** [chatchat-space/Langchain-Chatchat#2042]
**功能描述 / Feature Description**
切换相同底座的lora模型不需要重新加载底座。

**解决的问题 / Problem Solved**
加快模型切换的效率。

**实现建议 / Implementation Suggestions**
看见FastChat已经有了相关的方法不知道能否实现在这个项目上。
https://github.com/lm-sys/FastChat/pull/1905

感谢！

**Comment by zRzRzRzRzRzRzR** [comment]
现在暂时没有做这方面的工作
欢迎提供PR，这可以加速我们的工作

**Comment by Fraudsterrrr** [comment]
@zRzRzRzRzRzRzR 
我根据https://github.com/chatchat-space/Langchain-Chatchat/issues/1130#issuecomment-1685291822尝试分步去启动，能成功启动服务并且调用到fastchatAPI但是打开本项目提供的API管理页面[/docs](http://127.0.0.1:7861/docs#/)时报错

"GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/fastapi/applications.py", line 1061, in openapi
    return JSONResponse(self.openapi())
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/fastapi/applications.py", line 1033, in openapi
    self.openapi_schema = get_openapi(
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/fastapi/openapi/utils.py", line 475, in get_openapi
    field_mapping, definitions = get_definitions(
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/fastapi/_compat.py", line 471, in get_definitions
    return {}, get_model_definitions(
  File "/root/anaconda3/envs/LangChain-ChatChat/lib/python3.10/site-packages/fastapi/_compat.py", line 374, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.Body_knowledge_base_chat_chat_knowledge_base_chat_post'>


### 具体启动流程为
1. python3 -m fastchat.serve.controller
2. PEFT_SHARE_BASE_WEIGHTS=true python3 -m fastchat.serve.multi_model_worker \
    --model-path /root/ai/model/lora/peft_sft_yimei_20231025_1 \
    --model-names yimei \
    --model-path /root/ai/model/lora/peft_to_sft_food \
    --model-names food \
    --model-path /root/ai/model/lora/peft_to_doctor \
    --model-names doctor \
    --num-gpus 2
3. python3 -m fastchat.serve.openai_api_server --host 127.0.0.1 --port 6868
4. python startup.py --all-api

### ==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-88-generic-x86_64-with-glibc2.31.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.7
langchain版本：0.0.335. fastchat版本：0.2.32


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['SZSM'] @ cuda
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/root/ai/model/Qwen/output_qwen_self_231020',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861

**Comment by Fraudsterrrr** [comment]
@zRzRzRzRzRzRzR 尝试了下 已经可以做到了 套用了fastchat中multi_model_worker.py的create_multi_model_worker函数 虽然修改后的代码非常的死板。

1. 修改create_model_worker_app中调用本地模型的非vllm分支
2. 强制设定model_names 和 model_path为相同底座的lora模型
3. 修改加载ModelWorker的流程如下：
                if args.conv_template is None:
                    args.conv_template = [None] * len(args.model_path)
                elif len(args.conv_template) == 1:  # Repeat the same template
                    args.conv_template = args.conv_template * len(args.model_path)
                workers = []
                for conv_template, model_path, model_names in zip(
                        args.conv_template, args.model_path, args.model_names
                ):
                    worker = ModelWorker(
                        controller_addr=args.controller_address,
                        worker_addr=args.worker_address,
                        worker_id=worker_id,
                        model_path=model_path,
                        model_names=model_names,
                        limit_worker_concurrency=args.limit_worker_concurrency,
                        no_register=args.no_register,
                        device=args.device,
                        num_gpus=args.num_gpus,
                        max_gpu_memory=args.max_gpu_memory,
                        load_8bit=args.load_8bit,
                        cpu_offloading=args.cpu_offloading,
                        gptq_config=gptq_config,
                        awq_config=awq_config,
                        stream_interval=args.stream_interval,
                        conv_template=conv_template,
                        embed_in_truncate=args.embed_in_truncate,
                    )
                    workers.append(worker)
                # Register all models
                import requests
                url = args.controller_address + "/register_worker"
                data = {
                    "worker_name": workers[0].worker_addr,
                    "check_heart_beat": not args.no_register,
                    "worker_status": {
                        "model_names": [m for w in workers for m in w.model_names],
                        "speed": 1,
                        "queue_length": sum([w.get_queue_length() for w in workers]),
                    },
                }
                r = requests.post(url, json=data)
                assert r.status_code == 200

最后一步是在启动服务时加入新的环境变量：
PEFT_SHARE_BASE_WEIGHTS=true python startup.py -a

使用PEFT_SHARE_BASE_WEIGHTS=true共享底座模型权重时要把启动模型流程放在同一个进程中，不然好像是不起作用的。

还有就是在使用该项目的0.2.7版本时发现通过配置项同时启动多个本地模型时会发生20002端口占用的错误（ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 20002): address already in use），猜测是不同模型启动过程中重复调用了端口，导致启动的多个模型只有最后一个模型是在运行的状态。

如果以上操作能给你们提供帮助，非常荣幸。
再次感谢本项目各位的付出。

**Comment by zRzRzRzRzRzRzR** [comment]
看到了，我们尝试一下，感谢你的意见
