### ISSUE TITLE
[BUG] 在更新版本后启动python startup.py -a ,报错AttributeError: 'FieldInfo' object has no attribute 'required'

### ISSUE THREAD

**Issue by qihangf** [chatchat-space/Langchain-Chatchat#2050]
**问题描述 / Problem Description**
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/startup.py", line 383, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/startup.py", line 168, in create_model_worker_app
    from fastchat.serve.model_worker import app, GptqConfig, AWQConfig, ModelWorker, worker_id
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 18, in<module>
    from fastchat.model.model_adapter import (
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastchat/model/__init__.py", line 1, in <module>
    from fastchat.model.model_adapter import (
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 15, in <module>
    import accelerate
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/utils/__init__.py", line 133, in <module>
    from .launch import (
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/utils/launch.py", line 33, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/utils/other.py", line 30, in <module>
    from deepspeed import DeepSpeedEngine
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/__init__.py", line 16, in <module>
    from . import module_inject
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 792, in <module>
    from ..pipe import PipelineModule
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/pipe/__init__.py", line 6,in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 29, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/__init__.py", line 6,in <module>
    from .partition_parameters import ZeroParamType
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 616, in <module>
    class Init(InsertPostInitMethodToModuleSubClasses):
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 618, in Init
    param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/config_utils.py", line 115, in get_config_default
    assert not config.__fields__.get(
AttributeError: 'FieldInfo' object has no attribute 'required'

**复现问题的步骤 / Steps to Reproduce**
pip install -r requirements.txt
再重建知识库
最后python startup.py -a

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): qwen-14b-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): bge-large_zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:ubt
- Python 版本 / Python version:3.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by qihangf** [comment]
还发现模型都是加载到cpu上了，还有这样的warning，UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driverby downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your versionof the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
但我就用的v100，我看最高就支持cuda11.6，我已经是11.6了，这该如何呢

**Comment by zRzRzRzRzRzRzR** [comment]
跟显卡没有关系，跟驱动有关系，V100也可以用cuda 12.3

**Comment by yqyu2317** [comment]
看报错里的packages，是accelerate和deepspeed，把他们都更新一遍，就可以了
`pip install --upgrade deepspeed`
`pip install --upgrade accelerate`
更新之后我的问题解决了，可以试试
