### ISSUE TITLE
[BUG] 安装依赖报错

### ISSUE THREAD

**Issue by yueyann** [chatchat-space/Langchain-Chatchat#2054]
**问题描述 / Problem Description**
新建了conda环境，准备试用0.2.7，安装requirements.txt和requirements_api.txt里面的依赖都有报错。今早clone的项目，不存在requirements.txt有中文的问题

**复现问题的步骤 / Steps to Reproduce**
1. 执行 pip install -r requirements_api.txt

2. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Ignoring python-magic-bin: markers 'sys_platform == "win32"' don't match your environment
Ignoring vllm: markers 'sys_platform == "linux"' don't match your environment
Collecting langchain>=0.0.329 (from -r requirements_api.txt (line 3))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/15/f9/e79403efb880425babaa91f8ab19e1b6218dc694551fa6e7f40197b5a72a/langchain-0.0.335-py3-none-any.whl (2.0 MB)
Collecting langchain-experimental>=0.0.30 (from -r requirements_api.txt (line 4))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5d/a0/5c192859d36c62e3a9752700f73aad8b55c1c9351fc5f28ce8b98a41ea7b/langchain_experimental-0.0.40-py3-none-any.whl (160 kB)
Collecting fschat==0.2.32 (from fschat[model_worker]==0.2.32->-r requirements_api.txt (line 5))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3b/1e/55db8a11c3ec1fd5789abff8255a56682b168f3802771480accfa524361c/fschat-0.2.32-py3-none-any.whl (211 kB)
Collecting xformers>=0.0.22.post4 (from -r requirements_api.txt (line 6))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3c/b2/9416a89b78b5b8e06bce0d0a04cb76813df4242507690b62eb2b0e57199d/xformers-0.0.22.post7.tar.gz (3.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/t5/p8kpxtyd5pv1pbb0zmgx6gzh0000gn/T/pip-install-3myzsg5_/xformers_667742eb62dc4d0988654838a2e20899/setup.py", line 23, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.7
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): 否
- 操作系统及版本 / Operating system and version: mac
- Python 版本 / Python version: 3.10.12

求指点是什么原因报错～

**Comment by Vaaaas** [comment]
> https://github.com/chatchat-space/Langchain-Chatchat/blob/c094b5f91cc2161cc790b5158dc3cbc5efad1cb6/requirements_api.txt#L19
这里指定了操作系统为Windows，但是你运行的操作系统是MacOS。可能是这个原因？

**Comment by maxusheng123** [comment]
我也是想在本地调试一下，win，也是到这里报错（Preparing metadata (setup.py) ... error）。

**Comment by yueyann** [comment]
应该是xformers安装报的错，查了一下，可能是因为pip的setuptools版本不对，目前是68.2.2，但还是不知道应该切换到哪个版本，有没有安装成功的好心人，可以看下pip list看下是什么版本吗？

**Comment by fqdltd** [comment]
ERROR: No matching distribution found for streamlit>=1.25.0  我安装依赖的时候 一直报这个错···有大神碰到这个问题么？该如何解决？

**Comment by zRzRzRzRzRzRzR** [comment]
不要用镜像，去官方源安装

**Comment by fanlun008** [comment]
python -m pip install pip==21.1.3
downgrade your pip, work for me
