### ISSUE TITLE
[BUG] 请问CPU机器可以使用该模型吗？我执行的时候报错了。

### ISSUE THREAD

**Issue by 1guo1** [chatchat-space/Langchain-Chatchat#2068]
**问题描述 / Problem Description**
执行pip install -r requirements.txt时报错

**复现问题的步骤 / Steps to Reproduce**
pip install -r requirements.txt

**预期的结果 / Expected Result**
```
Collecting vllm>=0.2.0 (from -r requirements.txt (line 30))
  Downloading http://cmc-cd-mirror.rnd.huawei.com/pypi/packages/b2/2e/b5f6222ff465405c60d2b9b2fb1e1e63009887f25b63f602c934b95e82a1/vllm-0.2.1.post1.tar.gz (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 29.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ?─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/guo/anaconda3/envs/gzj/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/guo/anaconda3/envs/gzj/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/guo/anaconda3/envs/gzj/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-aws87mrk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-aws87mrk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-aws87mrk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 28, in <module>
      RuntimeError: Cannot find CUDA_HOME. CUDA must be available to build the package.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
?─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

提示我需要安装CUDA，是需要注释哪些配置吗
**实际结果 / Actual Result**
执行pip install -r requirements.txt失败

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型：m3e-base
- 使用的向量库类型
- 操作系统及版本 / Operating system and version: ubuntu 22.0
- Python 版本 / Python version: 3.10.13
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
可以，你这是环境装成cuda的环境了，转成cpu的torch就行
