### ISSUE TITLE
 请求对本地模型其他格式支持的扩充（例如gguf等格式）以及本地模型加载配置的举例说明

### ISSUE THREAD

**Issue by Aridea2021** [chatchat-space/Langchain-Chatchat#2078]
尊敬的开发组：
       你们好！首先得感谢您开源这么好的项目，真的很棒。我再本地使用中注意到llm_model模型都是transformers hf之类的，能不能支持一下gguf格式的量化模型呢，量化后模型在纯cpu推理时会快速很多，对内存需求也会降低不少。
       此外模型配置文件model_config.py里如何指定本地模型地址我一直没看明白，对于已经下载好的本地模型单gguf文件或含bin格式文件夹类模型该如何指定加载。能否给个列子 例如我想加载/mnt/d/models文件夹里的chatglm3-6b文件夹模型和wizardlm-13b-v1.2.Q5_K_M.gguf单文件模型，该如何修改model_config.py里得配置呢？
       我有尝试过以下修改：
    MODEL_ROOT_PATH = "/mnt/d/models"
    LLM_MODELS = ["chatglm3-6b", "wizardlm-13b-v1.2", "openai-api"]

    "llm_model": {
        # 以下部分模型并未完全测试，仅根据fastchat和vllm模型的模型列表推定支持
        "chatglm3-6b": "THUDM/chatglm3-6b",
        "wizardlm-13b-v1.2.": "/mnt/d/models/wizardlm-13b-v1.2.Q5_K_M.gguf",
最后会报错呢：

2023-11-16 04:29:58 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-11-16 04:30:01 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 1aa5eb25 ...
2023-11-16 04:30:01 | ERROR | stderr | Process model_worker - chatglm3-6b:
2023-11-16 04:30:01 | ERROR | stderr | Traceback (most recent call last):
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-16 04:30:01 | ERROR | stderr |     self.run()
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-16 04:30:01 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-16 04:30:01 | ERROR | stderr |   File "/mnt/d/chatbot/Langchain-Chatchat/startup.py", line 383, in run_model_worker
2023-11-16 04:30:01 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-16 04:30:01 | ERROR | stderr |   File "/mnt/d/chatbot/Langchain-Chatchat/startup.py", line 211, in create_model_worker_app
2023-11-16 04:30:01 | ERROR | stderr |     worker = ModelWorker(
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-11-16 04:30:01 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 306, in load_model
2023-11-16 04:30:01 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 730, in load_model
2023-11-16 04:30:01 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 755, in from_pretrained
2023-11-16 04:30:01 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
2023-11-16 04:30:01 | ERROR | stderr |     return cls._from_pretrained(
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
2023-11-16 04:30:01 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenization_chatglm.py", line 101, in __init__
2023-11-16 04:30:01 | ERROR | stderr |     self.tokenizer = SPTokenizer(vocab_file)
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenization_chatglm.py", line 14, in __init__
2023-11-16 04:30:01 | ERROR | stderr |     assert os.path.isfile(model_path), model_path
2023-11-16 04:30:01 | ERROR | stderr |   File "/home/aridea/software/Anaconda3/envs/chatpaper/lib/python3.10/genericpath.py", line 30, in isfile
2023-11-16 04:30:01 | ERROR | stderr |     st = os.stat(path)
2023-11-16 04:30:01 | ERROR | stderr | TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by Aridea2021** [comment]
如果不用本地模型，用没有的chatglm2，程序就会自动下载并成功加载 能进入webui, 正常使用：
"llm_model": {
    "chatglm2-6b": "THUDM/chatglm2-6b",
不知道本地模型加载是啥原因

**Comment by zRzRzRzRzRzRzR** [comment]
gguf不支持，因为目前基于fschat，fscaht只能支持hf模型

**Comment by RiotEnd** [comment]
fschat是可以支持ExllamaV2 GPTQ 量化的本地推理模型的吧，我chatchat的配置手动修改，加上
exllama_config = ExllamaConfig(
                max_seq_len=2048,
                gpu_split="14,14,14",
                cache_8bit=False,
            )

尝试加载了下，能够启动成功，但是交互不太成功，内容有点莫名其妙的输出，大佬是不是可以考虑调整一下尝试支持，这个对资源的要求降低得非常显著

**Comment by Aridea2021** [comment]
autoreply：Your mail has been received, and I will reply as soon as I canBest Regards；）
