### ISSUE TITLE
[BUG]使用es构建知识库，查询es返回错误

### ISSUE THREAD

**Issue by zhengwanbo** [chatchat-space/Langchain-Chatchat#2089]
**问题描述 / Problem Description**
使用es构建知识库，数据已经加载成功，es index和dense_vector都有值，通过知识库查询es返回错误。 ES版本8.9.0.

2023-11-17 02:16:44,614 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/opc/LLM/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 58, in knowledge_base_chat_iterator
    docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
  File "/home/opc/LLM/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 37, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "/home/opc/LLM/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 172, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "/home/opc/LLM/Langchain-Chatchat/server/knowledge_base/kb_service/es_kb_service.py", line 129, in do_search
    docs = self.db_init.similarity_search_with_score(query=query,
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/langchain/vectorstores/elasticsearch.py", line 700, in similarity_search_with_score
    return self._search(query=query, k=k, filter=filter, **kwargs)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/langchain/vectorstores/elasticsearch.py", line 777, in _search
    response = self.client.search(
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 402, in wrapped
    return api(*args, **kwargs)
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 3733, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/home/opc/anaconda3/envs/faiss/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: [knn] queries are only supported on [dense_vector] fields')
2023-11-17 02:16:44,627 - utils.py[line:187] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by ShinyWey** [comment]
跟你一样的情况, Elasticsearch==7.17
```
2023-11-17 10:40:31,407 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/hello2ai/project/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 58, in knowledge_base_chat_iterator
    docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
  File "/home/hello2ai/project/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 37, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "/home/hello2ai/project/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 172, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "/home/hello2ai/project/Langchain-Chatchat/server/knowledge_base/kb_service/es_kb_service.py", line 129, in do_search
    docs = self.db_init.similarity_search_with_score(query=query,
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/langchain/vectorstores/elasticsearch.py", line 700, in similarity_search_with_score
    return self._search(query=query, k=k, filter=filter, **kwargs)
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/langchain/vectorstores/elasticsearch.py", line 779, in _search
    response = self.client.search(
  File "/root/anaconda3/envs/lc/lib/python3.10/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: Elasticsearch.search() got an unexpected keyword argument 'knn'
2023-11-17 10:40:31,410 - utils.py[line:187] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
```

**Comment by zhengwanbo** [comment]
找到错误了，不能提前建es 索引，因此，需要注销这行

            self.es_client_python.indices.create(index=self.index_name)

**Comment by menglong988** [comment]
我也是同样的问题，楼主解决了嘛
