### ISSUE TITLE
[BUG] 运行api.py后在浏览器上查看文档，后端报错

### ISSUE THREAD

**Issue by AlanLu0808** [chatchat-space/Langchain-Chatchat#2112]
**问题描述 / Problem Description**
打开api.py服务后，用浏览器访问后端文档，后端报错。（0.2.6可以运行，0.2.7的依赖包均已升级）报错信息如下：
```
INFO:     10.56.112.161:11768 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/anaconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/anaconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1061, in openapi
    return JSONResponse(self.openapi())
  File "/root/anaconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1033, in openapi
    self.openapi_schema = get_openapi(
  File "/root/anaconda3/lib/python3.10/site-packages/fastapi/openapi/utils.py", line 475, in get_openapi
    field_mapping, definitions = get_definitions(
  File "/root/anaconda3/lib/python3.10/site-packages/fastapi/_compat.py", line 471, in get_definitions
    return {}, get_model_definitions(
  File "/root/anaconda3/lib/python3.10/site-packages/fastapi/_compat.py", line 374, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.Body_recreate_vector_store_knowledge_base_recreate_vector_store_post'>

```

**复现问题的步骤 / Steps to Reproduce**
1. 执行python server/api.py
2. 浏览器上查看文档
3. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
0.2.6版本可以直接查看文档，但是新版本安装依赖包后报错

**实际结果 / Actual Result**
报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.7
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Baichuan2-13B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu20
- Python 版本 / Python version:3.10

**Comment by xiang19911014** [comment]
请问您是怎么解决这个问题的？
