### ISSUE TITLE
docker 启动无法使用宿主机上的gpu资源

### ISSUE THREAD

**Issue by JHGo123** [chatchat-space/Langchain-Chatchat#2113]
docker 一键部署后 发现无法使用宿主机显卡资源
启动日志：
<img width="913" alt="iShot_2023-11-20_18 17 21" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/42494758/72cfd064-4d2d-4f01-a23d-78aa4850d8c5">
model_config.py手动指定使用cuda 也无效直接报错
<img width="960" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/42494758/dd9ea683-7032-4f77-893a-e80a294592f5">

2023-11-20 08:04:20 | ERROR | stderr |
2023-11-20 08:04:20 | ERROR | stderr | Process model_worker - chatglm2-6b:
2023-11-20 08:04:20 | ERROR | stderr | Traceback (most recent call last):
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-20 08:04:20 | ERROR | stderr |     self.run()
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-20 08:04:20 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-20 08:04:20 | ERROR | stderr |   File "/langchain-chatchat/startup.py", line 382, in run_model_worker
2023-11-20 08:04:20 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-20 08:04:20 | ERROR | stderr |   File "/langchain-chatchat/startup.py", line 210, in create_model_worker_app
2023-11-20 08:04:20 | ERROR | stderr |     worker = ModelWorker(
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-11-20 08:04:20 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 294, in load_model
2023-11-20 08:04:20 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 719, in load_model
2023-11-20 08:04:20 | ERROR | stderr |     model = AutoModel.from_pretrained(
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
2023-11-20 08:04:20 | ERROR | stderr |     return model_class.from_pretrained(
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3307, in from_pretrained
2023-11-20 08:04:20 | ERROR | stderr |     ) = cls._load_pretrained_model(
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3695, in _load_pretrained_model
2023-11-20 08:04:20 | ERROR | stderr |     new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 741, in _load_state_dict_into_meta_model
2023-11-20 08:04:20 | ERROR | stderr |     set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 317, in set_module_tensor_to_device
2023-11-20 08:04:20 | ERROR | stderr |     new_value = value.to(device)
2023-11-20 08:04:20 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
2023-11-20 08:04:20 | ERROR | stderr |     torch._C._cuda_init()
2023-11-20 08:04:20 | ERROR | stderr | RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
在宿主机上和容器内都可以执行 nvidia-smi 看到显卡信息,nvidia-container-cli -V 运行也没问题

**Comment by yyxp1989** [comment]
我的问题和你类似，但显示模型加载时cuda，但实际使用的是cpu，容器内 nvidia-smi 可见独立显卡信息。
容器添加了 --runtime=nvidia 和 NVIDIA_VISIBLE_DEVICES GPUID
`==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.19.17-Unraid-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
项目版本：v0.2.7
langchain版本：0.0.334. fastchat版本：0.2.32


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/chatglm2-6b',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-35-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： text2vec-bge-large-chinese @ cuda
==============================Langchain-Chatchat Configuration==============================


2023-11-20 15:43:22 | INFO | model_worker | Register to controller
2023-11-20 15:43:22 | ERROR | stderr | INFO:     Started server process [91]
2023-11-20 15:43:22 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-20 15:43:22 | ERROR | stderr | INFO:     Application startup complete.
2023-11-20 15:43:22 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-11-20 15:43:22,812 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmp7_sss4_w
2023-11-20 15:43:22,812 - instantiator.py[line:76] - INFO: Writing /tmp/tmp7_sss4_w/_remote_module_non_scriptable.py
2023-11-20 15:43:23 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker d1e68764 ...
Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|█▍        | 1/7 [00:03<00:23,  3.99s/it]
Loading checkpoint shards:  29%|██▊       | 2/7 [00:08<00:21,  4.20s/it]
Loading checkpoint shards:  43%|████▎     | 3/7 [00:12<00:17,  4.25s/it]
Loading checkpoint shards:  57%|█████▋    | 4/7 [00:16<00:12,  4.20s/it]`

**Comment by JHGo123** [comment]
驱动不兼容的问题，已解决

**Comment by yyxp1989** [comment]
> 驱动不兼容的问题，已解决

你好，我也是这个问题，能了解下用哪个版本驱动解决的吗？
