### ISSUE TITLE
使用vllm加速报错

### ISSUE THREAD

**Issue by ZEROYXY** [chatchat-space/Langchain-Chatchat#2129]
CUDA: 12.1
Pytorch: 2.1.0+cu121
transformers: 4.35.1
vllm: 0.2.2
xformers: 0.0.22.post7

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
项目版本：v0.2.7
langchain版本：0.0.335. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b-32k'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'model_path': '/home/cloud/LLM/THUDM/chatglm2-6b-32k',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-11-21 21:15:18,261 - startup.py[line:648] - INFO: 正在启动服务：
2023-11-21 21:15:18,261 - startup.py[line:649] - INFO: 如需查看 llm_api 日志，请前往 /home/cloud/0.2.7-langchain-chatchat/logs
2023-11-21 21:15:20 | ERROR | stderr | INFO:     Started server process [2563]
2023-11-21 21:15:20 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-21 21:15:20 | ERROR | stderr | INFO:     Application startup complete.
2023-11-21 21:15:20 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
INFO 11-21 21:15:21 llm_engine.py:72] Initializing an LLM engine with config: model='/home/cloud/LLM/THUDM/chatglm2-6b-32k', tokenizer='/home/cloud/LLM/THUDM/chatglm2-6b-32k', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
WARNING 11-21 21:15:21 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 11-21 21:16:24 llm_engine.py:207] # GPU blocks: 909, # CPU blocks: 9362
WARNING 11-21 21:16:24 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
2023-11-21 21:16:24 | ERROR | stderr | Process model_worker - chatglm2-6b-32k:
2023-11-21 21:16:24 | ERROR | stderr | Traceback (most recent call last):
2023-11-21 21:16:24 | ERROR | stderr |   File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
2023-11-21 21:16:24 | ERROR | stderr |     self.run()
2023-11-21 21:16:24 | ERROR | stderr |   File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-21 21:16:24 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-21 21:16:24 | ERROR | stderr |   File "/home/cloud/0.2.7-langchain-chatchat/startup.py", line 384, in run_model_worker
2023-11-21 21:16:24 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-21 21:16:24 | ERROR | stderr |   File "/home/cloud/0.2.7-langchain-chatchat/startup.py", line 156, in create_model_worker_app
2023-11-21 21:16:24 | ERROR | stderr |     worker_id = worker_id,
2023-11-21 21:16:24 | ERROR | stderr | UnboundLocalError: local variable 'worker_id' referenced before assignment

I tried to change the value of worker_id with 12345678 instead the value of "worker_id" in the file: startup.py.
The the services can be started but the error "name 'worker' is not defined" as below reported when communicated with LLM with the Web UI

(vllm_awq) cloud@SuperCloud-ROG:~/0.2.7-langchain-chatchat$ python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
项目版本：v0.2.7
langchain版本：0.0.335. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b-32k'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'model_path': '/home/cloud/LLM/THUDM/chatglm2-6b-32k',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-11-21 21:17:35,061 - startup.py[line:648] - INFO: 正在启动服务：
2023-11-21 21:17:35,061 - startup.py[line:649] - INFO: 如需查看 llm_api 日志，请前往 /home/cloud/0.2.7-langchain-chatchat/logs
2023-11-21 21:17:37 | ERROR | stderr | INFO:     Started server process [2839]
2023-11-21 21:17:37 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-21 21:17:37 | ERROR | stderr | INFO:     Application startup complete.
2023-11-21 21:17:37 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
INFO 11-21 21:17:38 llm_engine.py:72] Initializing an LLM engine with config: model='/home/cloud/LLM/THUDM/chatglm2-6b-32k', tokenizer='/home/cloud/LLM/THUDM/chatglm2-6b-32k', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
WARNING 11-21 21:17:38 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 11-21 21:18:43 llm_engine.py:207] # GPU blocks: 909, # CPU blocks: 9362
WARNING 11-21 21:18:43 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
2023-11-21 21:18:43 | INFO | model_worker | Loading the model ['chatglm2-6b-32k'] on worker 12345678, worker type: vLLM worker...
2023-11-21 21:18:43 | INFO | model_worker | Register to controller
INFO:     Started server process [2965]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
项目版本：v0.2.7
langchain版本：0.0.335. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b-32k'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'model_path': '/home/cloud/LLM/THUDM/chatglm2-6b-32k',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

  A new version of Streamlit is available.

  See what's new at https://discuss.streamlit.io/c/announcements

  Enter the following command to upgrade:
  $ pip install streamlit --upgrade

{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-21 21:19:03,311 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42060 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-21 21:19:03,313 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-21 21:19:03,420 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42060 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-21 21:19:03,422 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42060 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-21 21:19:03,423 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-21 21:19:03,429 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42060 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-21 21:19:03,430 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-21 21:19:09,145 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42074 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-21 21:19:09,146 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42074 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-21 21:19:09,148 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-21 21:19:09,154 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42074 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-21 21:19:09,155 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'chatglm2-6b-32k',
 'prompt_name': 'default',
 'query': 'Hello',
 'stream': True,
 'temperature': 0.7}
INFO:     127.0.0.1:42074 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-21 21:19:09,222 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/cloud/anaconda3/envs/vllm_awq/lib/python3.10/site-packages/fastchat/serve/vllm_worker.py", line 206, in api_get_conv
    return worker.get_conv_template()
NameError: name 'worker' is not defined

  How can I fix that?

**Comment by ZEROYXY** [comment]
有木有同学遇到了类似的问题，可以透露一下怎么改能够把它们修复嘞

**Comment by hzg0601** [comment]
vllm目前并不原生支持chatglm,你如果要用，需要手动创建engine

**Comment by ZEROYXY** [comment]
<img width="1010" alt="vllm v0 2 2 supported model list" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/efad15b1-d4cf-4a27-af7e-6bba12185fd2">
我是用的是vllm v0.2.2，经官方发布信息确认，该版本vllm开始已经支持对GLM架构模型进行支持。
因此我认为这不是vllm不原生支持ChatGLM的问题

**Comment by ZEROYXY** [comment]
<img width="1280" alt="单启vllm加载chatglm2-6B-32K加速成功" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/2dc26231-c394-45ab-a029-4fb09ae55e76">
且于本地已测试过，单启vllm加载chatglm2-6b-32k运行，是没有问题的。但通过chatchat加载时，先是会报出worker_id找不到的问题。手动赋值给worker_id之后，服务可以被启动，但会报出如上最开始的：name 'worker' is not defined问题，前端会话亦无返回信息

**Comment by hzg0601** [comment]
你在model_config的vllm_model支持列表里添加chatglm了吗

**Comment by ZEROYXY** [comment]
<img width="401" alt="chatchat_model_config_1" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/8d45532f-4d2e-480f-95e2-d38bdb96006a">
<img width="590" alt="chatchat_model_config_2" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/17a5b6ae-5c0f-487a-bd30-f5e181f912ce">
<img width="710" alt="chatchat_model_config_3" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/2e36db74-4b2f-495d-b7f9-07437ca996a7">
是滴，我在ChatChat项目中的configs/model_config.py下，共配置了三处，chatglm2-6b及chatglm2-6b-32k相关信息

**Comment by hzg0601** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/22924096/f6886571-a5f3-4c23-b905-1929218ddac9)
你在这里的app后面加一个worker_id

**Comment by ZEROYXY** [comment]
并且为了解决首先报出的找不到worker_id的问题，我在startup.py中手动修改了worker_id的值
<img width="656" alt="更改startup worker_id" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/0b70afc1-0cbf-46a2-963d-f01622432afe">

**Comment by hzg0601** [comment]
worker_id不能自行指定的，你按照上面的引用

**Comment by ZEROYXY** [comment]
稍等我试一下

**Comment by hzg0601** [comment]
正常了吗？

**Comment by ZEROYXY** [comment]
startup.py文件中，已于指定处增加worker_id变量，找不到worker_id的问题已解决
<img width="656" alt="更改startup worker_id" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/47acef89-4357-42ed-9866-cecc9606e1f4">
但又出现了如下报错：
<img width="1280" alt="worker_id问题解决后报断言错误" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/00048df8-4b77-4118-9b43-525168a060a7">

**Comment by ZEROYXY** [comment]
<img width="569" alt="1700816482435" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/ebc376db-40aa-40d4-9c8b-2bba339b6396">

所使用的fastchat版本如图所示为0.2.32

**Comment by ZEROYXY** [comment]
Sorry上方图贴错了
<img width="701" alt="start_up中添加worker_id变量" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/49576528/f04f9327-70d0-434d-b37f-ce3fb71d4be2">

**Comment by hzg0601** [comment]
是不是用了代理？

**Comment by ZEROYXY** [comment]
我在我在，我在65群，不良人萧十一郎

**Comment by hzg0601** [comment]
重新拉去0.2.7的代码，并按server_config.py.example的修改fschat的代码

**Comment by lunalulu** [comment]
请问最后怎么解决的？ @ZEROYXY
