### ISSUE TITLE
使用自定义关键词的embedding模型后报错

### ISSUE THREAD

**Issue by promisecc** [chatchat-space/Langchain-Chatchat#2133]
运行embeddings/add_embedding_keywords.py后得到embedding模型，然后重新命名为m3e-base，替换原来的m3e-base，原来的model_config.py未改动，初始化数据库后报错

运行结果如下：
recreating all vector stores
2023-11-22 00:59:51,734 - base.py[line:35] - INFO: thread 740721 开始操作：('samples', 'm3e-base')。初始化
2023-11-22 00:59:51,734 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/m3e-base' from disk.
2023-11-22 00:59:51,734 - base.py[line:35] - INFO: thread 740721 开始操作：('m3e-base', 'cuda')。初始化
2023-11-22 00:59:52,062 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /home/lijinrun/lgs/backbone/m3e-base
2023-11-22 00:59:52,062 - SentenceTransformer.py[line:805] - WARNING: No sentence-transformers model found with name /home/lijinrun/lgs/backbone/m3e-base. Creating a new one with MEAN pooling.
2023-11-22 00:59:53,226 - base.py[line:39] - INFO: thread 740721 结束操作：('m3e-base', 'cuda')。初始化
2023-11-22 00:59:53,226 - embeddings_api.py[line:39] - ERROR: Error(s) in loading state_dict for BertModel:
        size mismatch for embeddings.word_embeddings.weight: copying a param with shape torch.Size([34144, 768]) from checkpoint, the shape in current model is torch.Size([34127, 768]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
2023-11-22 00:59:53,251 - base.py[line:39] - INFO: thread 740721 结束操作：('samples', 'm3e-base')。初始化
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lijinrun/lgs/Langchain-Chatchat/init_database.py", line 108, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/migrate.py", line 118, in folder2db
    kb.create_kb()
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 80, in create_kb
    self.do_create_kb()
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 47, in do_create_kb
    self.load_vector_store()
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 90, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 48, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/anaconda3/envs/lang/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 510, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/anaconda3/envs/lang/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 911, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 380, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in norm
  File "/home/lijinrun/anaconda3/envs/lang/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 2541, in norm
    s = (x.conj() * x).real
         ^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
(lang) lijinrun@cocolab:~/lgs/Langchain-Chatchat$ python init_database.py --recreate-vs
recreating all vector stores
2023-11-22 01:03:42,657 - base.py[line:35] - INFO: thread 741173 开始操作：('samples', 'm3e-base')。初始化
2023-11-22 01:03:42,658 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/m3e-base' from disk.
2023-11-22 01:03:42,658 - base.py[line:35] - INFO: thread 741173 开始操作：('m3e-base', 'cuda')。初始化
2023-11-22 01:03:42,987 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /home/lijinrun/lgs/backbone/m3e-base
2023-11-22 01:03:42,987 - SentenceTransformer.py[line:805] - WARNING: No sentence-transformers model found with name /home/lijinrun/lgs/backbone/m3e-base. Creating a new one with MEAN pooling.
2023-11-22 01:03:44,144 - base.py[line:39] - INFO: thread 741173 结束操作：('m3e-base', 'cuda')。初始化
2023-11-22 01:03:44,144 - embeddings_api.py[line:39] - ERROR: Error(s) in loading state_dict for BertModel:
        size mismatch for embeddings.word_embeddings.weight: copying a param with shape torch.Size([34144, 768]) from checkpoint, the shape in current model is torch.Size([34127, 768]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
2023-11-22 01:03:44,160 - base.py[line:39] - INFO: thread 741173 结束操作：('samples', 'm3e-base')。初始化
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lijinrun/lgs/Langchain-Chatchat/init_database.py", line 108, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/migrate.py", line 118, in folder2db
    kb.create_kb()
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 80, in create_kb
    self.do_create_kb()
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 47, in do_create_kb
    self.load_vector_store()
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 90, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 48, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/anaconda3/envs/lang/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 510, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/anaconda3/envs/lang/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 911, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 380, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/lgs/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in norm
  File "/home/lijinrun/anaconda3/envs/lang/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 2541, in norm
    s = (x.conj() * x).real
         ^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by liuxjerry** [comment]
我倒是成功加载了，但使用自定义关键词的embedding模型没有任何效果，反而变差了。问关键词，在向量数据库里都检索不到相关内容。

**Comment by promisecc** [comment]
> 我倒是成功加载了，但使用自定义关键词的embedding模型没有任何效果，反而变差了。问关键词，在向量数据库里都检索不到相关内容。

请问您是不是直接跑的startup.py文件呢，直接跑startup可以跑通，但是init_database.py --recreate_vs会出现上面的错误

**Comment by shishi11** [comment]
我试的时候感觉如果是这种错误，基本上就是包冲突了，要严格按requirements的要求，可能还差一点。我调了好久，重装了n个包。

**Comment by slliao445** [comment]
一样的错误，请问后来解决了吗？

**Comment by murdonson** [comment]
加了关键词 效果反而变差了 +1
