### ISSUE TITLE
不通过startup.py --api来启动api.py服务，单独运行server/api.py启动服务，但这样会报错

### ISSUE THREAD

**Issue by msm-2023** [chatchat-space/Langchain-Chatchat#2145]
如题：单独运行api.py，在拉取api接口页面时还是会报错，不知需要前面加载那些东西了或者添加那些参数
INFO:     192.168.31.248:59484 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1061, in openapi
    return JSONResponse(self.openapi())
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1033, in openapi
    self.openapi_schema = get_openapi(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/openapi/utils.py", line 475, in get_openapi
    field_mapping, definitions = get_definitions(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/_compat.py", line 471, in get_definitions
    return {}, get_model_definitions(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/_compat.py", line 374, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.Body_update_docs_knowledge_base_update_docs_post'>

**Comment by msm-2023** [comment]
版本为：0.27版本

**Comment by msm-2023** [comment]
之前0.21版本单独启动是没有问题
