### ISSUE TITLE
遇到一点小问题[BUG]：ChatGLM2-6B-->ptuning 微调模型 按照`微调模型加载实操` 出错误

### ISSUE THREAD

**Issue by Bo-LiangD** [chatchat-space/Langchain-Chatchat#2147]
**问题描述 / Problem Description**
使用 ChatGLM2-6B-->ptuning 微调模型 按照`微调模型加载实操` 出错误

**复现问题的步骤 / Steps to Reproduce**
1. 使用 ChatGLM2-6B ddeptuning 微调微调模型；
2. 按照 `https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5#%E6%8E%A8%E8%8D%90%E7%9A%84%E6%A8%A1%E5%9E%8B%E7%BB%84%E5%90%88`(微调模型加载实操)
3. 这是我的 主体目录结构
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/e3677265-376b-4112-b0ff-3253bd1c36ad)

4. 这是我的 ptuning  
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/adce59de-2157-4f5b-8f4d-6dceb37c7d5c);
5. 执行 PEFT_SHARE_BASE_WEIGHTS=true python startup.py -a 
6. 问题出现  
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /home/wb/THUDM/chatglm2-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2023-11-22 20:57:30 | ERROR | stderr | Process model_worker - chatglm2-6b:
2023-11-22 20:57:30 | ERROR | stderr | Traceback (most recent call last):
2023-11-22 20:57:30 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-22 20:57:30 | ERROR | stderr |     self.run()
2023-11-22 20:57:30 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-22 20:57:30 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-22 20:57:30 | ERROR | stderr |   File "/home/wb/Langchain-Chatchat/startup.py", line 370, in run_model_worker
2023-11-22 20:57:30 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-22 20:57:30 | ERROR | stderr |   File "/home/wb/Langchain-Chatchat/startup.py", line 197, in create_model_worker_app
2023-11-22 20:57:30 | ERROR | stderr |     worker = ModelWorker(
2023-11-22 20:57:30 | ERROR | stderr |   File "/home/wb/.local/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-11-22 20:57:30 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-22 20:57:30 | ERROR | stderr |   File "/home/wb/.local/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 303, in load_model
2023-11-22 20:57:30 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-11-22 20:57:30 | ERROR | stderr |   File "/home/wb/.local/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 594, in load_model
2023-11-22 20:57:30 | ERROR | stderr |     model = get_peft_model(base_model,config,adapter_name=model_path)
2023-11-22 20:57:30 | ERROR | stderr |   File "/home/wb/.local/lib/python3.10/site-packages/peft/mapping.py", line 98, in get_peft_model
2023-11-22 20:57:30 | ERROR | stderr |     return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
2023-11-22 20:57:30 | ERROR | stderr |   File "/home/wb/.local/lib/python3.10/site-packages/peft/peft_model.py", line 893, in __init__
2023-11-22 20:57:30 | ERROR | stderr |     super().__init__(model, peft_config, adapter_name)
2023-11-22 20:57:30 | ERROR | stderr |   File "/home/wb/.local/lib/python3.10/site-packages/peft/peft_model.py", line 112, in __init__
2023-11-22 20:57:30 | ERROR | stderr |     self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
2023-11-22 20:57:30 | ERROR | stderr | TypeError: PrefixEncoder.__init__() takes 2 positional arguments but 4 were given
2023-11-22 20:58:09 | INFO | model_worker | Send heart beat. Models: ['zhipu-api']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 5817e19f.

**预期的结果 / Expected Result**
预计成功后 应该是 启动程序，并且按照微调的模型，进行知识库展示

**实际结果 / Actual Result**
没有访问成功，出现了错误

**环境信息 / Environment Information**
操作系统：Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
项目版本：v0.2.7
langchain版本：0.0.339. fastchat版本：0.2.32
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 

在线求大佬解答

**Comment by hzg0601** [comment]
看起来可能是你的adapter_config写的有问题，或者peft的版本不匹配
