### ISSUE TITLE
启动就报错，问题出在哪里？缺少configuration_chatglm.py吗？

### ISSUE THREAD

**Issue by wywywy1990** [chatchat-space/Langchain-Chatchat#2192]
E:\Langchain-Chatchat>echo "Start VENV"
"Start VENV"

E:\Langchain-Chatchat>call Miniconda3\Scripts\activate.bat

(base) E:\Langchain-Chatchat>goto :run

(base) E:\Langchain-Chatchat>echo "Start API + WebUI"
"Start API + WebUI"

(base) E:\Langchain-Chatchat>python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19044-SP0.
python版本：3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.7
langchain版本：0.0.340. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b-int4', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'E:\\Langchain-Chatchat\\THUDM\\chatglm3-6b-int4',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-11-27 21:10:27,153 - startup.py[line:653] - INFO: 正在启动服务：
2023-11-27 21:10:27,153 - startup.py[line:654] - INFO: 如需查看 llm_api 日志，请前往 E:\Langchain-Chatchat\logs
2023-11-27 21:10:35 | INFO | model_worker | Register to controller
2023-11-27 21:10:35 | ERROR | stderr | INFO:     Started server process [8644]
2023-11-27 21:10:35 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-27 21:10:35 | ERROR | stderr | INFO:     Application startup complete.
2023-11-27 21:10:35 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2023-11-27 21:10:36 | INFO | model_worker | Loading the model ['chatglm3-6b-int4'] on worker 3417b00a ...
Could not locate the configuration_chatglm.py inside THUDM/chatglm3-6b.
2023-11-27 21:10:51 | ERROR | stderr | Process model_worker - chatglm3-6b-int4:
2023-11-27 21:10:51 | ERROR | stderr | Traceback (most recent call last):
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
2023-11-27 21:10:51 | ERROR | stderr |     httplib_response = self._make_request(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
2023-11-27 21:10:51 | ERROR | stderr |     self._validate_conn(conn)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
2023-11-27 21:10:51 | ERROR | stderr |     conn.connect()
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\urllib3\connection.py", line 419, in connect
2023-11-27 21:10:51 | ERROR | stderr |     self.sock = ssl_wrap_socket(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
2023-11-27 21:10:51 | ERROR | stderr |     ssl_sock = _ssl_wrap_socket_impl(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
2023-11-27 21:10:51 | ERROR | stderr |     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\ssl.py", line 513, in wrap_socket
2023-11-27 21:10:51 | ERROR | stderr |     return self.sslsocket_class._create(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\ssl.py", line 1071, in _create
2023-11-27 21:10:51 | ERROR | stderr |     self.do_handshake()
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\ssl.py", line 1342, in do_handshake
2023-11-27 21:10:51 | ERROR | stderr |     self._sslobj.do_handshake()
2023-11-27 21:10:51 | ERROR | stderr | ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
2023-11-27 21:10:51 | ERROR | stderr |
2023-11-27 21:10:51 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-11-27 21:10:51 | ERROR | stderr |
2023-11-27 21:10:51 | ERROR | stderr | Traceback (most recent call last):
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\requests\adapters.py", line 489, in send
2023-11-27 21:10:51 | ERROR | stderr |     resp = conn.urlopen(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
2023-11-27 21:10:51 | ERROR | stderr |     retries = retries.increment(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
2023-11-27 21:10:51 | ERROR | stderr |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-11-27 21:10:51 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/configuration_chatglm.py (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
2023-11-27 21:10:51 | ERROR | stderr |
2023-11-27 21:10:51 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-11-27 21:10:51 | ERROR | stderr |
2023-11-27 21:10:51 | ERROR | stderr | Traceback (most recent call last):
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\multiprocessing\process.py", line 314, in _bootstrap
2023-11-27 21:10:51 | ERROR | stderr |     self.run()
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\multiprocessing\process.py", line 108, in run
2023-11-27 21:10:51 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\startup.py", line 385, in run_model_worker
2023-11-27 21:10:51 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\startup.py", line 213, in create_model_worker_app
2023-11-27 21:10:51 | ERROR | stderr |     worker = ModelWorker(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\fastchat\serve\model_worker.py", line 74, in __init__
2023-11-27 21:10:51 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\fastchat\model\model_adapter.py", line 306, in load_model
2023-11-27 21:10:51 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\fastchat\model\model_adapter.py", line 733, in load_model
2023-11-27 21:10:51 | ERROR | stderr |     model = AutoModel.from_pretrained(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 526, in from_pretrained
2023-11-27 21:10:51 | ERROR | stderr |     config, kwargs = AutoConfig.from_pretrained(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1057, in from_pretrained
2023-11-27 21:10:51 | ERROR | stderr |     config_class = get_class_from_dynamic_module(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\transformers\dynamic_module_utils.py", line 487, in get_class_from_dynamic_module
2023-11-27 21:10:51 | ERROR | stderr |     final_module = get_cached_module_file(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\transformers\dynamic_module_utils.py", line 293, in get_cached_module_file
2023-11-27 21:10:51 | ERROR | stderr |     resolved_module_file = cached_file(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\transformers\utils\hub.py", line 430, in cached_file
2023-11-27 21:10:51 | ERROR | stderr |     resolved_file = hf_hub_download(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
2023-11-27 21:10:51 | ERROR | stderr |     return fn(*args, **kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\huggingface_hub\file_download.py", line 1232, in hf_hub_download
2023-11-27 21:10:51 | ERROR | stderr |     metadata = get_hf_file_metadata(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
2023-11-27 21:10:51 | ERROR | stderr |     return fn(*args, **kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\huggingface_hub\file_download.py", line 1599, in get_hf_file_metadata
2023-11-27 21:10:51 | ERROR | stderr |     r = _request_wrapper(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\huggingface_hub\file_download.py", line 417, in _request_wrapper
2023-11-27 21:10:51 | ERROR | stderr |     response = _request_wrapper(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\huggingface_hub\file_download.py", line 452, in _request_wrapper
2023-11-27 21:10:51 | ERROR | stderr |     return http_backoff(
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\huggingface_hub\utils\_http.py", line 258, in http_backoff
2023-11-27 21:10:51 | ERROR | stderr |     response = session.request(method=method, url=url, **kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\requests\sessions.py", line 587, in request
2023-11-27 21:10:51 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\requests\sessions.py", line 701, in send
2023-11-27 21:10:51 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
2023-11-27 21:10:51 | ERROR | stderr |     return super().send(request, *args, **kwargs)
2023-11-27 21:10:51 | ERROR | stderr |   File "E:\Langchain-Chatchat\Miniconda3\lib\site-packages\requests\adapters.py", line 563, in send
2023-11-27 21:10:51 | ERROR | stderr |     raise SSLError(e, request=request)
2023-11-27 21:10:51 | ERROR | stderr | requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/configuration_chatglm.py (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))"), '(Request ID: ead7fd63-78e8-4b65-9611-f8e5af634ce5)')

**Comment by zRzRzRzRzRzRzR** [comment]
模型文件没有全，或者没有更新到最新的文件（最新的配置文件才支持4.34以上的Transformers）
