### ISSUE TITLE
[BUG] 如何正确使用本地下载的模型呀？为什么还是加载的huggingface cache的模型！修改了model_config.py好像不管用

### ISSUE THREAD

**Issue by douya222** [chatchat-space/Langchain-Chatchat#2193]
# model_config.py
 MODEL_ROOT_PATH = "/data/datasets/user1801004151/model_weights/"

# python startup.py -a 
错误输出如下 
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-84-generic-x86_64-with-glibc2.31.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.7
langchain版本：0.0.330. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '**/data/datasets/user1801004151/model_weights/chatglm2-6b**',
 'port': 20002}
{'api_key': '',
 'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-11-27 21:48:39,510 - startup.py[line:648] - INFO: 正在启动服务：
2023-11-27 21:48:39,510 - startup.py[line:649] - INFO: 如需查看 llm_api 日志，请前往 /data/user1801004151/research/Langchain-Chatchat/logs
2023-11-27 21:48:41 | INFO | model_worker | Register to controller
2023-11-27 21:48:41 | ERROR | stderr | INFO:     Started server process [41763]
2023-11-27 21:48:41 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-27 21:48:41 | ERROR | stderr | INFO:     Application startup complete.
2023-11-27 21:48:41 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-11-27 21:48:43 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 04015716 ...
2023-11-27 21:48:43 | ERROR | stderr | Process model_worker - chatglm2-6b:
2023-11-27 21:48:43 | ERROR | stderr | Traceback (most recent call last):
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-27 21:48:43 | ERROR | stderr |     self.run()
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-27 21:48:43 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/research/Langchain-Chatchat/startup.py", line 385, in run_model_worker
2023-11-27 21:48:43 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/research/Langchain-Chatchat/startup.py", line 213, in create_model_worker_app
2023-11-27 21:48:43 | ERROR | stderr |     worker = ModelWorker(
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-11-27 21:48:43 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 306, in load_model
2023-11-27 21:48:43 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 730, in load_model
2023-11-27 21:48:43 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 755, in from_pretrained
2023-11-27 21:48:43 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
2023-11-27 21:48:43 | ERROR | stderr |     return cls._from_pretrained(
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
2023-11-27 21:48:43 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2023-11-27 21:48:43 | ERROR | stderr |   File **"/data/user1801004151/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py**", line 69, in __init__
2023-11-27 21:48:43 | ERROR | stderr |     super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces, **kwargs)
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 367, in __init__
2023-11-27 21:48:43 | ERROR | stderr |     self._add_tokens(
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
2023-11-27 21:48:43 | ERROR | stderr |     current_vocab = self.get_vocab().copy()
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 112, in get_vocab
2023-11-27 21:48:43 | ERROR | stderr |     vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
2023-11-27 21:48:43 | ERROR | stderr |   File "/data/user1801004151/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 108, in vocab_size
2023-11-27 21:48:43 | ERROR | stderr |     return self.tokenizer.n_words
2023-11-27 21:48:43 | ERROR | stderr | **AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'**
^C2023-11-27 21:48:47,486 - startup.py[line:853] - WARNING: Sending SIGKILL to {'zhipu-api': <Process name='api_worker - zhipu-api (41765)' pid=41765 parent=41510 started daemon>}
2023-11-27 21:48:47,487 - startup.py[line:853] - WARNING: Sending SIGKILL to {'chatglm2-6b': <Process name='model_worker - chatglm2-6b (41764)' pid=41764 parent=41510 stopped exitcode=1 daemon>}
2023-11-27 21:48:47,487 - startup.py[line:853] - WARNING: Sending SIGKILL to <Process name='controller (41668)' pid=41668 parent=41510 started daemon>
2023-11-27 21:48:47,488 - startup.py[line:853] - WARNING: Sending SIGKILL to <Process name='openai_api (41763)' pid=41763 parent=41510 started daemon>
2023-11-27 21:48:47,489 - startup.py[line:853] - WARNING: Sending SIGKILL to <Process name='API Server' parent=41510 initial daemon>
Traceback (most recent call last):
  File "/data/user1801004151/research/Langchain-Chatchat/startup.py", line 761, in start_main_server
    e.wait()
  File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/multiprocessing/managers.py", line 1093, in wait
    return self._callmethod('wait', (timeout,))
  File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/data/user1801004151/research/Langchain-Chatchat/startup.py", line 606, in f
    raise KeyboardInterrupt(f"{signalname} received")
KeyboardInterrupt: SIGINT received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user1801004151/research/Langchain-Chatchat/startup.py", line 878, in <module>
    loop.run_until_complete(start_main_server())
  File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data/user1801004151/research/Langchain-Chatchat/startup.py", line 861, in start_main_server
    p.kill()
  File "/data/user1801004151/anaconda3/envs/Langchain-Chatchat/lib/python3.10/multiprocessing/process.py", line 140, in kill
    self._popen.kill()
AttributeError: 'NoneType' object has no attribute 'kill'

**Comment by favouriter** [comment]
```bash
从这里克隆到本地
| 魔塔社区 | [modelscope](https://modelscope.cn/models) |

| 始智AI | [wisemodel](https://wisemodel.cn/models) |
```

**Comment by zRzRzRzRzRzRzR** [comment]
下载模型后，记得该model_config上的模型路径并选择你的模型，确保模型是完整的
直接该对应模型的名称的绝对路径更好
比如 chatglm你就直接改下面字典中的glm模型的绝对路径
