### ISSUE TITLE
[BUG] YI-6B-200K报错

### ISSUE THREAD

**Issue by favouriter** [chatchat-space/Langchain-Chatchat#2195]
**YI-6B-200K报错**
'BaseModelOutputWithPast' object has no attribute 'logits'

**环境信息 / Environment Information**
- langchain-chat:v0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：YI-6B-200K
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-large @ cuda
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Windows11
- Python 版本 / Python version:3.10

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22631-SP0.
python版本：3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
项目版本：v0.2.7
langchain版本：0.0.335. fastchat版本：0.2.32

```bash
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Yi-6B-200K'] @ cuda
{'device': 'cuda',
 'host': '192.168.3.5',
 'infer_turbo': False,
 'model_path': 'D:\\langchainChatGLM\\models\\llm_model\\Yi-6B-200K',
 'port': 20002}
当前Embbedings模型： m3e-large @ cuda


received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'Yi-6B-200K',
 'prompt_name': 'default',
 'query': '你能帮我生成stable diffusion提示词吗',
 'stream': True,
 'temperature': 0.8}


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\langchainChatGLM\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\langchainChatGLM\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\langchainChatGLM\venv\lib\site-packages\fastapi\applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\langchainChatGLM\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\langchainChatGLM\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "D:\langchainChatGLM\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "D:\langchainChatGLM\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\langchainChatGLM\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\langchainChatGLM\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\langchainChatGLM\venv\lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
  File "D:\langchainChatGLM\venv\lib\site-packages\fastchat\serve\model_worker.py", line 104, in generate_stream_gate
    for output in self.generate_stream_func(
  File "D:\langchainChatGLM\venv\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\langchainChatGLM\venv\lib\site-packages\fastchat\serve\inference.py", line 131, in generate_stream
    logits = out.logits
AttributeError: 'BaseModelOutputWithPast' object has no attribute 'logits'
```

**Comment by zRzRzRzRzRzRzR** [comment]
没有支持这个模型，此外，这是个base模型，不是chat
