### ISSUE TITLE
[BUG] 向量化比较大的文件时报错，但可以成功向量化

### ISSUE THREAD

**Issue by Lijia0** [chatchat-space/Langchain-Chatchat#2198]
**问题描述 / Problem Description**
向量化比较大的文件时报错，但可以成功向量化

**复现问题的步骤 / Steps to Reproduce**
1. 上传一个比较大的文件
2. 点击 '添加至向量库'

**预期的结果 / Expected Result**
文件可以向量化成功

**实际结果 / Actual Result**
文件可以向量化成功，但报错，之前的版本没有报错
报错如下：
Batches:  35%|███▌      | 52/147 [02:47<05:24,  3.41s/it]                                      2023-11-28 07:00:13,860 - utils.py[line:94] - ERROR: ReadTimeout: error when post /knowledge_base/update_docs: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 28, in read
    return self._sock.recv(max_bytes)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 96, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 121, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 99, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 164, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 200, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 26, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Langchain-Chatchat/webui_pages/utils.py", line 91, in post
    return self.client.post(url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1132, in post
    return self.request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：zhipu-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： pg
- 操作系统及版本 / Operating system and version:Linux
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by Lijia0** [comment]
还有其他问题，向量后的数据是多条。日志中出现像下面这样的三个批处理，查询时会查到3条相同的记录
Batches:  73%|███████▎  | 331/452 [35:48<10:38,  5.28s/it]
Batches:  56%|█████▌    | 251/452 [30:42<18:47,  5.61s/it]
Batches:  45%|████▌     | 204/452 [25:43<21:16,  5.15s/it]

**Comment by Lijia0** [comment]
知道是怎么回事了，超时重试了，可以增大超时时间，或者用api的方式上传。

**Comment by dark-lake** [comment]
请问我如何设置这个upload_docs路由的超时时间呢? 不是注解的方式我有目前不太清楚如何解决这个问题

**Comment by Modas-Li** [comment]
请问我如何设置这个upload_docs路由的超时时间呢? 不是注解的方式我有目前不太清楚如何解决这个问题

**Comment by dark-lake** [comment]
> 请问我如何设置这个upload_docs路由的超时时间呢? 不是注解的方式我有目前不太清楚如何解决这个问题

直接先调接口, 先用着, 然后等下个版本

**Comment by Modas-Li** [comment]
Thank you for your email !您好，你的邮件我已收到，我会尽快给你回复。
