### ISSUE TITLE
# win11 wsl2 Ubuntu22.04 无法启动 `dev v0.2.8`

### ISSUE THREAD

**Issue by auroralzone** [chatchat-space/Langchain-Chatchat#2200]
```shell
# python=3.10.12
git clone -b dev https.....git
cd -
pip ...txt
python copy_config_example.py  # 配置`model_config.py`
python init_database.py --recreate-vs
python startup.py -a # 报错
```

错误：
```
Loading checkpoint shards: 100%|████████████████████████████████████████| 7/7 [00:14<00:00,  2.04s/it]
2023-11-28 16:03:34 | ERROR | stderr | 
2023-11-28 16:03:37 | INFO | model_worker | Register to controller
Process API Server:
Traceback (most recent call last):
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/code/a/Langchain-Chatchat/startup.py", line 430, in run_api_server
    from server.api import create_app
  File "/root/code/a/Langchain-Chatchat/server/api.py", line 18, in <module>
    from server.chat.completion import completion
  File "/root/code/a/Langchain-Chatchat/server/chat/completion.py", line 9, in <module>
    from langchain.prompts.chat import PromptTemplate
ImportError: cannot import name 'PromptTemplate' from 'langchain.prompts.chat' (/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/prompts/chat.py)
```

**Comment by culaccino0** [comment]
请问咋解决了，我也遇到了同样问题

**Comment by auroralzone** [comment]
> 请问咋解决了，我也遇到了同样问题

解：`pip install langchain==0.0.334`

**Comment by culaccino0** [comment]
确实可以了，感谢
