### ISSUE TITLE
[BUG] `dev v0.2.8` API通信遇到错误

### ISSUE THREAD

**Issue by auroralzone** [chatchat-space/Langchain-Chatchat#2202]
# win11 wsl2 Ubuntu22.04 启动 `dev v0.2.8` 报错
> `API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)`

- `python=2.10.12`
- `langchain==0.0.334`

`python startup.py -a` 启动正常

对话报错：

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42070770/ae7ca005-41b7-420c-bcdc-75e2e7f7c9f4)

```
2023-11-28 16:47:53,854 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:48570 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-28 16:47:53,857 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{}
2023-11-28 16:47:53,873 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:48570 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-28 16:47:53,878 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{}
INFO:     127.0.0.1:48570 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-28 16:47:53,913 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
received input message:
{'conversation_id': '81aea6f7c4b845c79822cd271b4e25af',
 'history': [],
 'max_tokens': None,
 'model_name': 'chatglm3-6b',
 'prompt_name': 'default',
 'query': '你好',
 'stream': True,
 'temperature': 0.7}
{}
INFO:     127.0.0.1:48570 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-28 16:47:53,924 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/code/a/Langchain-Chatchat/server/chat/chat.py", line 48, in chat_iterator
    if isinstance(max_tokens, int) and max_tokens <= 0:
UnboundLocalError: local variable 'max_tokens' referenced before assignment
2023-11-28 16:47:53,925 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
```

**Comment by liunux4odoo** [comment]
开发版已修复：
https://github.com/chatchat-space/Langchain-Chatchat/commit/7d580d9a47c9455f420e87e9fbdd3188a712582e

**Comment by auroralzone** [comment]
> 开发版已修复： [7d580d9](https://github.com/chatchat-space/Langchain-Chatchat/commit/7d580d9a47c9455f420e87e9fbdd3188a712582e)

**可以了**

***

但是出现新的问题：**openai-api** 无法使用

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42070770/3d892c35-c48c-46c0-84d4-b0b552beba26)

```
INFO:     127.0.0.1:32778 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-29 11:30:24,805 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
received input message:
{'conversation_id': 'c2f9ca6d09114a15b74ae3c6be5a0d25',
 'history': [],
 'max_tokens': None,
 'model_name': 'openai-api',
 'prompt_name': 'default',
 'query': '你好',
 'stream': True,
 'temperature': 0.3}
{}
INFO:     127.0.0.1:32778 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-29 11:30:24,821 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-11-29 11:30:33,299 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-11-29 11:30:42,754 - utils.py[line:24] - ERROR: Error communicating with OpenAI
Traceback (most recent call last):
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "uvloop/loop.pyx", line 2039, in create_connection
  File "uvloop/loop.pyx", line 2015, in uvloop.loop.Loop.create_connection
  File "uvloop/handles/tcp.pyx", line 182, in uvloop.loop.TCPTransport.connect
  File "uvloop/handles/tcp.pyx", line 204, in uvloop.loop._TCPConnectRequest.connect
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/openai/api_requestor.py", line 678, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [Network is unreachable]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/code/a/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    raise e
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chains/base.py", line 373, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chains/llm.py", line 280, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chains/llm.py", line 147, in agenerate
    return await self.llm.agenerate_prompt(
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chat_models/base.py", line 469, in agenerate_prompt
    return await self.agenerate(
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chat_models/base.py", line 429, in agenerate
    raise exceptions[0]
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chat_models/base.py", line 532, in _agenerate_with_cache
    return await self._agenerate(
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 497, in _agenerate
    return await _agenerate_from_stream(stream_iter)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chat_models/base.py", line 70, in _agenerate_from_stream
    async for chunk in stream:
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 463, in _astream
    async for chunk in await acompletion_with_retry(
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 110, in acompletion_with_retry
    return await _completion_with_retry(**kwargs)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 108, in _completion_with_retry
    return await llm.client.acreate(**kwargs)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 219, in acreate
    response, _, api_key = await requestor.arequest(
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/openai/api_requestor.py", line 374, in arequest
    result = await self.arequest_raw(
  File "/root/miniconda3/envs/Langchain-Chatchat-dev/lib/python3.10/site-packages/openai/api_requestor.py", line 695, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
2023-11-29 11:30:42,757 - utils.py[line:27] - ERROR: APIConnectionError: Caught exception: Error communicating with OpenAI
```
