### ISSUE TITLE
[BUG] agent/tools/calculate.py如何做单元测试?

### ISSUE THREAD

**Issue by CaptainDP** [chatchat-space/Langchain-Chatchat#2207]
**问题描述 / Problem Description**
agent/tools下面的工具如何做单元测试，比如：calculate.py

**复现问题的步骤 / Steps to Reproduce**
执行calculate.py文件的代码：
if __name__ == "__main__":
    result = calculate("2的三次方")
    print("答案:",result)

**预期的结果 / Expected Result**
调用LLM_MODELS已经配置的大模型或者指定特定模型，进行计算

**实际结果 / Actual Result**
Traceback (most recent call last):
  File "D:\workspace\llm_workspace\Langchain-Chatchat\server\agent\tools\calculate.py", line 72, in <module>
    result = calculate("2的三次方")
  File "D:\workspace\llm_workspace\Langchain-Chatchat\server\agent\tools\calculate.py", line 67, in calculate
    llm_math = LLMMathChain.from_llm(model, verbose=True, prompt=PROMPT)
  File "D:\software\lang\venv3\lib\site-packages\langchain\chains\llm_math\base.py", line 184, in from_llm
    llm_chain = LLMChain(llm=llm, prompt=prompt)
  File "D:\software\lang\venv3\lib\site-packages\langchain\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)

**环境信息 / Environment Information**
==============================Langchain-Chatchat Configuration==============================
python版本：3.8.10
项目版本：v0.2.7
langchain版本：0.0.336. fastchat版本：0.2.32

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
没有办法做，目前必须吊起来整个服务才能测试Agent
