### ISSUE TITLE
[bug] setup之后无法load模型，显示 ValueError: Invalid device: auto

### ISSUE THREAD

**Issue by MengzhenJia** [chatchat-space/Langchain-Chatchat#2222]
**问题描述 / Problem Description**
在setup那步，/ Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py --all-webui --model-name chatglm3-6b' / Run '...' 
3. 点击 '...' / Click '...'
4. 滚动到 '...' / Scroll to '...'
5. 问题出现 / Problem occurs
(chatchat) C:\Users\admin\jupyter\chatbot\Langchain-Chatchat>python startup.py --all-webui --model-name chatglm3-6b
2023-11-29 22:06:42,522 - startup.py[line:649] - INFO: 正在启动服务：
2023-11-29 22:06:42,522 - startup.py[line:650] - INFO: 如需查看 llm_api 日志，请前往 C:\Users\admin\jupyter\chatbot\Langchain-Chatchat\logs
2023-11-29 22:06:46 | ERROR | stderr | INFO:     Started server process [21500]
2023-11-29 22:06:46 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-29 22:06:46 | ERROR | stderr | INFO:     Application startup complete.
2023-11-29 22:06:46 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2023-11-29 22:06:46 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 6d49ed13 ...
2023-11-29 22:06:46 | ERROR | stderr | Process model_worker - chatglm3-6b:
2023-11-29 22:06:46 | ERROR | stderr | Traceback (most recent call last):
2023-11-29 22:06:46 | ERROR | stderr |   File "C:\Users\admin\anaconda3\envs\chatchat\lib\multiprocessing\process.py", line 315, in _bootstrap
2023-11-29 22:06:46 | ERROR | stderr |     self.run()
2023-11-29 22:06:46 | ERROR | stderr |   File "C:\Users\admin\anaconda3\envs\chatchat\lib\multiprocessing\process.py", line 108, in run
2023-11-29 22:06:46 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-29 22:06:46 | ERROR | stderr |   File "C:\Users\admin\jupyter\chatbot\Langchain-Chatchat\startup.py", line 385, in run_model_worker
2023-11-29 22:06:46 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-29 22:06:46 | ERROR | stderr |   File "C:\Users\admin\jupyter\chatbot\Langchain-Chatchat\startup.py", line 213, in create_model_worker_app
2023-11-29 22:06:46 | ERROR | stderr |     worker = ModelWorker(
2023-11-29 22:06:46 | ERROR | stderr |   File "C:\Users\admin\anaconda3\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2023-11-29 22:06:46 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-29 22:06:46 | ERROR | stderr |   File "C:\Users\admin\anaconda3\envs\chatchat\lib\site-packages\fastchat\model\model_adapter.py", line 234, in load_model
2023-11-29 22:06:46 | ERROR | stderr |     raise ValueError(f"Invalid device: {device}")
2023-11-29 22:06:46 | ERROR | stderr | ValueError: Invalid device: auto

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
应该是setup成功的
**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
显示 ValueError: Invalid device: auto
**环境信息 / Environment Information**
- 操作系统：Windows-10-10.0.22621-SP0.
- python版本：3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)]
- 项目版本：v0.2.7
- langchain版本：0.0.342. fastchat版本：0.2.33
- 当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'auto', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
- 当前Embbedings模型： m3e-base @ cuda
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): yes

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by Flagami** [comment]
解决了吗？亲
我用的Baichuan2-7B-Chat模型

**Comment by zRzRzRzRzRzRzR** [comment]
升级成python 3.10，然后配置文件直接吧auto 该改成cuda

**Comment by hotdogarea** [comment]
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
cannot import name '_sentencepiece' from partially initialized module 'sentencepiece'
升级3.10后 也更改了auto=>cuda
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/11146882/29813827-f207-4dab-869a-92691b097ac5)
