### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by litterGuy** [chatchat-space/Langchain-Chatchat#2226]
使用baichuan2-13b本地模型，启动正常、进行问答时就报错
```
TypeError: object of type 'NoneType' has no len()
```
请问这个错误该怎么处理？
详细日志如下：
```


==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
项目版本：v0.2.7                                                                            
langchain版本：0.0.340. fastchat版本：0.2.32                                                


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['baichuan2-13b'] @ cuda
2023-11-30 09:45:56 | INFO | stdout | {'device': 'cuda',
2023-11-30 09:45:56 | INFO | stdout |  'host': '127.0.0.1',
2023-11-30 09:45:56 | INFO | stdout |  'infer_turbo': False,
2023-11-30 09:45:56 | INFO | stdout |  'model_path': 'F:\\Langchain-Chatchat\\models\\baichuan-inc\\Baichuan2-13B-Chat',
2023-11-30 09:45:56 | INFO | stdout |  'port': 20002}
2023-11-30 09:45:56 | INFO | stdout | 当前Embbedings模型： m3e-base @ cuda
2023-11-30 09:45:56 | INFO | stdout | ==============================Langchain-Chatchat Configuration==============================
2023-11-30 09:45:56 | INFO | root | 如需查看 llm_api 日志，请前往 F:\Langchain-Chatchat\logs
2023-11-30 09:45:59 | ERROR | stderr | INFO:     Started server process [11508]
2023-11-30 09:45:59 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-30 09:45:59 | ERROR | stderr | INFO:     Application startup complete.
2023-11-30 09:45:59 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20001 (Press CTRL+C to quit)
2023-11-30 09:46:02 | INFO | model_worker | Loading the model ['baichuan2-13b'] on worker 3228c85c ...
2023-11-30 09:46:03 | ERROR | stderr | INFO:     Started server process [20328]
2023-11-30 09:46:03 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-30 09:46:03 | ERROR | stderr | INFO:     Application startup complete.
2023-11-30 09:46:03 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2023-11-30 09:46:03 | WARNING | xformers | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading checkpoint shards:   0%|                                                                                                                                                                             | 0/3 [00:00<?, ?it/s] 
Loading checkpoint shards:  33%|███████████████████████████████████████████████████████                                                                                                              | 1/3 [00:06<00:12,  6.41s/it]
Loading checkpoint shards:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                       | 2/3 [00:09<00:04,  4.64s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:15<00:00,  4.98s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:15<00:00,  5.07s/it]
2023-11-30 09:46:18 | ERROR | stderr |
2023-11-30 09:46:25 | INFO | model_worker | Register to controller
2023-11-30 09:46:25 | INFO | controller | Register a new worker: http://127.0.0.1:20002
2023-11-30 09:46:25 | INFO | controller | Register done: http://127.0.0.1:20002, {'model_names': ['baichuan2-13b'], 'speed': 1, 'queue_length': 0}
2023-11-30 09:46:25 | INFO | stdout | INFO:     127.0.0.1:55414 - "POST /register_worker HTTP/1.1" 200 OK
2023-11-30 09:46:25 | ERROR | stderr | INFO:     Started server process [1344]
2023-11-30 09:46:25 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-30 09:46:25 | ERROR | stderr | INFO:     Application startup complete.
2023-11-30 09:46:25 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20002 (Press CTRL+C to quit)
2023-11-30 09:46:31 | ERROR | stderr | INFO:     Started server process [19988]
2023-11-30 09:46:31 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-30 09:46:31 | ERROR | stderr | INFO:     Application startup complete.
2023-11-30 09:46:31 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
2023-11-30 09:46:34 | INFO | stdout | 
2023-11-30 09:46:34 | INFO | stdout | 
2023-11-30 09:46:34 | INFO | stdout | ==============================Langchain-Chatchat Configuration==============================
2023-11-30 09:46:34 | INFO | stdout | 操作系统：Windows-10-10.0.19045-SP0.
2023-11-30 09:46:34 | INFO | stdout | python版本：3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
2023-11-30 09:46:34 | INFO | stdout | 项目版本：v0.2.7
2023-11-30 09:46:34 | INFO | stdout | langchain版本：0.0.340. fastchat版本：0.2.32
2023-11-30 09:46:34 | INFO | stdout |
2023-11-30 09:46:34 | INFO | stdout |
2023-11-30 09:46:34 | INFO | stdout | 当前使用的分词器：ChineseRecursiveTextSplitter
2023-11-30 09:46:34 | INFO | stdout | 当前启动的LLM模型：['baichuan2-13b'] @ cuda
2023-11-30 09:46:34 | INFO | stdout | {'device': 'cuda',
2023-11-30 09:46:34 | INFO | stdout |  'host': '127.0.0.1',
2023-11-30 09:46:34 | INFO | stdout |  'infer_turbo': False,
2023-11-30 09:46:34 | INFO | stdout |  'model_path': 'F:\\Langchain-Chatchat\\models\\baichuan-inc\\Baichuan2-13B-Chat',
2023-11-30 09:46:34 | INFO | stdout |  'port': 20002}
2023-11-30 09:46:34 | INFO | stdout | 当前Embbedings模型： m3e-base @ cuda
2023-11-30 09:46:34 | INFO | stdout |
2023-11-30 09:46:34 | INFO | stdout |
2023-11-30 09:46:34 | INFO | stdout | 服务端运行信息：
2023-11-30 09:46:34 | INFO | stdout |     OpenAI API Server: http://127.0.0.1:20000/v1
2023-11-30 09:46:34 | INFO | stdout |     Chatchat  API  Server: http://127.0.0.1:7861
2023-11-30 09:46:34 | INFO | stdout |     Chatchat WEBUI Server: http://127.0.0.1:8501
2023-11-30 09:46:34 | INFO | stdout | ==============================Langchain-Chatchat Configuration==============================
2023-11-30 09:46:34 | INFO | stdout |
2023-11-30 09:46:34 | INFO | stdout |

  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

2023-11-30 09:46:39 | INFO | stdout | {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': N
one, 'http://localhost': None}}
2023-11-30 09:46:39 | INFO | stdout | {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-30 09:46:39 | INFO | stdout | INFO:     127.0.0.1:55442 - "POST /list_models HTTP/1.1" 200 OK
2023-11-30 09:46:39 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-11-30 09:46:39 | INFO | stdout | INFO:     127.0.0.1:55441 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-30 09:46:39 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-11-30 09:46:39 | INFO | stdout | {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-30 09:46:39 | INFO | stdout | INFO:     127.0.0.1:55446 - "POST /list_models HTTP/1.1" 200 OK
2023-11-30 09:46:39 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-11-30 09:46:39 | INFO | stdout | INFO:     127.0.0.1:55441 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-30 09:46:39 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-11-30 09:46:39 | INFO | stdout | INFO:     127.0.0.1:55441 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-30 09:46:39 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-11-30 09:46:39 | INFO | stdout | {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-30 09:46:39 | INFO | stdout | INFO:     127.0.0.1:55447 - "POST /list_models HTTP/1.1" 200 OK
2023-11-30 09:46:39 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-11-30 09:46:39 | INFO | stdout | INFO:     127.0.0.1:55441 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-30 09:46:39 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-11-30 09:46:44 | INFO | stdout | {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': N
one, 'http://localhost': None}}
2023-11-30 09:46:44 | INFO | stdout | {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55449 - "POST /list_models HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55448 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55448 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-11-30 09:46:44 | INFO | stdout | {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}      
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55450 - "POST /list_models HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55448 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-11-30 09:46:44 | INFO | stdout | received input message:
2023-11-30 09:46:44 | INFO | stdout | {'history': [],
2023-11-30 09:46:44 | INFO | stdout |  'max_tokens': None,
2023-11-30 09:46:44 | INFO | stdout |  'model_name': 'baichuan2-13b',
2023-11-30 09:46:44 | INFO | stdout |  'prompt_name': 'default',
2023-11-30 09:46:44 | INFO | stdout |  'query': '1234',
2023-11-30 09:46:44 | INFO | stdout |  'stream': True,
2023-11-30 09:46:44 | INFO | stdout |  'temperature': 0.7}
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55448 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-11-30 09:46:44 | INFO | stdout | 
2023-11-30 09:46:44 | INFO | stdout | 
2023-11-30 09:46:44 | INFO | stdout | > Entering new LLMChain chain...
2023-11-30 09:46:44 | INFO | stdout | Prompt after formatting:
2023-11-30 09:46:44 | INFO | stdout | user: 1234
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55452 - "POST /list_models HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | controller | names: ['http://127.0.0.1:20002'], queue_lens: [0.0], ret: http://127.0.0.1:20002
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55453 - "POST /get_worker_address HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55454 - "POST /worker_get_conv_template HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55455 - "POST /model_details HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55456 - "POST /count_token HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55451 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2023-11-30 09:46:44 | INFO | stdout | INFO:     127.0.0.1:55457 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-11-30 09:46:44 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2023-11-30 09:46:50 | ERROR | root | TypeError: Caught exception: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "F:\Langchain-Chatchat\server\utils.py", line 21, in wrap_done
    await fn
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chains\base.py", line 379, in acall
    raise e
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chains\base.py", line 373, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chains\llm.py", line 280, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chains\llm.py", line 147, in agenerate
    return await self.llm.agenerate_prompt(
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chat_models\base.py", line 469, in agenerate_prompt
    return await self.agenerate(
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chat_models\base.py", line 429, in agenerate
    raise exceptions[0]
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chat_models\base.py", line 532, in _agenerate_with_cache
    return await self._agenerate(
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chat_models\openai.py", line 502, in _agenerate
    return await _agenerate_from_stream(stream_iter)
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chat_models\base.py", line 70, in _agenerate_from_stream
    async for chunk in stream:
  File "F:\Langchain-Chatchat\venv\lib\site-packages\langchain\chat_models\openai.py", line 473, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()

```

**Comment by zaoqishibing** [comment]
我的最后发现是显卡的显存爆满了导致的，把词嵌入模型归到cpu下，解决了

**Comment by zRzRzRzRzRzRzR** [comment]
emm，你是把两个模型都放在内存中吗，那估计是有问题的，这个我们没有测，主要是测GPU，GPU不会出现这个问题

**Comment by litterGuy** [comment]
后续替替换了baichuan2-13b-chat-4bits。因为使用的是windows跑的百川模型，安装windows下的bitsandbytes，目前倒是正常运行了
```
pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
```

**Comment by ForgetThatNight** [comment]
我用的azure，解决了好多bug好不容易启动了，又来这个bug

**Comment by litterGuy** [comment]
可以打印下具体报错内容是什么，
修改下openai.py文件，打印下错误信息。位置参照/root/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/chat_models
```
 if not isinstance(chunk, dict):
                chunk = chunk.dict()
            **print(chunk)**
            if len(chunk["choices"]) == 0:
                continue
```
查看报错信息，再决定是什么情况。
我这里报错是
```
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx)
```
在服务器上没有GPU，使用cpu跑baichuan2-13b-chat-4bits。而该模型不支持cpu、无奈更换baichuan2-13b-chat。
速度慢的不行。。。。

**Comment by JerryYao80** [comment]
我用的是 0.2.9版本 在RED HAT 4.8.5上也是同样的问题 请教如何解决

**Comment by Liwan-Chen** [comment]
> 我用的azure，解决了好多bug好不容易启动了，又来这个bug

我也是用azure api ，遇到这个bug，请问是怎么解决的
