### ISSUE TITLE
启动时报错（python startup.py -a），如下，是硬件不够吗？

### ISSUE THREAD

**Issue by digital-wuzhy** [chatchat-space/Langchain-Chatchat#2239]
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.15063-SP0.
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.7
langchain版本：0.0.342. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cpu',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'E:\\software\\Langchain-Chatchat-master\\chatglm2-6b',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2023-11-30 18:19:26,770 - startup.py[line:647] - INFO: 正在启动服务：
2023-11-30 18:19:26,770 - startup.py[line:648] - INFO: 如需查看 llm_api 日志，请前往 E:\software\Langchain-Chatchat-master\logs
2023-11-30 18:19:42 | INFO | model_worker | Register to controller
2023-11-30 18:19:43 | ERROR | stderr | INFO:     Started server process [10672]
2023-11-30 18:19:43 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-30 18:19:43 | ERROR | stderr | INFO:     Application startup complete.
2023-11-30 18:19:43 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2023-11-30 18:19:52 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker e95839f8 ...
2023-11-30 18:20:17 | ERROR | stderr | INFO:     Shutting down
2023-11-30 18:20:17,631 - startup.py[line:852] - WARNING: Sending SIGKILL to {'zhipu-api': <Process name='api_worker - zhipu-api (11540)' pid=11540 parent=9260 started daemon>}
2023-11-30 18:20:17,647 - startup.py[line:852] - WARNING: Sending SIGKILL to {'chatglm2-6b': <Process name='model_worker - chatglm2-6b (8592)' pid=8592 parent=9260 started daemon>}
2023-11-30 18:20:17,647 - startup.py[line:852] - WARNING: Sending SIGKILL to <Process name='controller (10096)' pid=10096 parent=9260 started daemon>
2023-11-30 18:20:17,647 - startup.py[line:852] - WARNING: Sending SIGKILL to <Process name='openai_api (10672)' pid=10672 parent=9260 started daemon>
2023-11-30 18:20:17,647 - startup.py[line:852] - WARNING: Sending SIGKILL to <Process name='API Server' parent=9260 initial daemon>
Traceback (most recent call last):
  File "E:\software\Langchain-Chatchat-master\startup.py", line 760, in start_main_server
    e.wait()
  File "E:\software\Anaconda3\envs\chatchat\lib\multiprocessing\managers.py", line 1093, in wait
    return self._callmethod('wait', (timeout,))
  File "E:\software\Anaconda3\envs\chatchat\lib\multiprocessing\managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "E:\software\Anaconda3\envs\chatchat\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "E:\software\Anaconda3\envs\chatchat\lib\multiprocessing\connection.py", line 305, in _recv_bytes
    waitres = _winapi.WaitForMultipleObjects(
  File "E:\software\Langchain-Chatchat-master\startup.py", line 605, in f
    raise KeyboardInterrupt(f"{signalname} received")
KeyboardInterrupt: SIGINT received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\software\Langchain-Chatchat-master\startup.py", line 877, in <module>
    loop.run_until_complete(start_main_server())
  File "E:\software\Anaconda3\envs\chatchat\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\software\Langchain-Chatchat-master\startup.py", line 860, in start_main_server
    p.kill()
  File "E:\software\Anaconda3\envs\chatchat\lib\multiprocessing\process.py", line 140, in kill
    self._popen.kill()
AttributeError: 'NoneType' object has no attribute 'kill'

**Comment by zRzRzRzRzRzRzR** [comment]
应该是，查看wiki中要求的最低标准

**Comment by yanzhang404** [comment]
请问解决了吗，我也遇到了这个问题
