### ISSUE TITLE
> wi如果你是用llama-factory那套来做的话，你应该按照wiki中的合并peft的方式或者直接用factory的导出成一个完整的大模型

### ISSUE THREAD

**Issue by ShanJianSoda** [chatchat-space/Langchain-Chatchat#2249]
> wi如果你是用llama-factory那套来做的话，你应该按照wiki中的合并peft的方式或者直接用factory的导出成一个完整的大模型

如果 **wiki中的合并peft的方式** 指的是**非p-tuning类PEFT加载**加载的话

```
本项目基于 FastChat 加载 LLM 服务，故需以 FastChat 加载 PEFT 路径，针对chatglm,falcon，codet5p以外的模型，以及非p-tuning以外的peft方法，需对peft文件进行修改，步骤如下：

将config.json文件修改为adapter_config.json;
保证文件夹包含pytorch_model.bin文件；
修改文件夹名称，保证文件夹包含'peft'一词；
将peft文件夹移入项目目录下；
确保adapter_config.json文件夹中base_model_name_or_path指向基础模型；
将peft路径添加到model_config.py的llm_dict中，键为模型名，值为peft路径，注意使用相对路径，如"peft"；
开启 PEFT_SHARE_BASE_WEIGHTS=true环境变量，再执行python startup.py -a
```
我将文件夹修改为 chatglm3-6b-peft，并因为model_config.py没有llm_dict，自己添加了一个，并在model_path里也加上了路径。

peft文件夹
（我不是很清楚peft文件夹是什么，所以我把llama-factory导出的完整模型所在的文件夹path_to_export和训练后生成的文件夹sft_checkpoint都试了一遍，都不行）
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/128208553/f8312774-bc59-4e1a-a00d-7f1503f2dad9)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/128208553/6470d7e1-30da-4dee-ac94-c5777fa1d0a7)

然后其他步骤相同，运行后爆了如下错误
```
2023-12-01 14:46:46 | INFO | stdout | ===================================BUG REPORT===================================
2023-12-01 14:46:46 | INFO | stdout | Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
2023-12-01 14:46:46 | INFO | stdout | ================================================================================
2023-12-01 14:46:46 | INFO | stdout | binary_path: e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Loading binary e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
2023-12-01 14:46:46 | INFO | stdout | Could not find module 'e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Loading binary e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
2023-12-01 14:46:46 | INFO | stdout | Could not find module 'e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Loading binary e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
2023-12-01 14:46:46 | INFO | stdout | Could not find module 'e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
2023-12-01 14:46:46 | INFO | stdout | CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
2023-12-01 14:37:50 | ERROR | stderr | Process model_worker - chatglm3-6b-peft:
2023-12-01 14:37:50 | ERROR | stderr | Traceback (most recent call last):
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
2023-12-01 14:37:50 | ERROR | stderr |     self.run()
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\multiprocessing\process.py", line 108, in run
2023-12-01 14:37:50 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-12-01 14:37:50 | ERROR | stderr |   File "E:\langchain\Langchain-Chatchat\startup.py", line 383, in run_model_worker
2023-12-01 14:37:50 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-12-01 14:37:50 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01 14:37:50 | ERROR | stderr |   File "E:\langchain\Langchain-Chatchat\startup.py", line 211, in create_model_worker_app
2023-12-01 14:37:50 | ERROR | stderr |     worker = ModelWorker(
2023-12-01 14:37:50 | ERROR | stderr |              ^^^^^^^^^^^^
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\serve\model_worker.py", line 63, in __init__
2023-12-01 14:37:50 | ERROR | stderr |     super().__init__(
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\serve\base_model_worker.py", line 47, in __init__
2023-12-01 14:37:50 | ERROR | stderr |     self.conv = self.make_conv_template(conv_template, model_path)
2023-12-01 14:37:50 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\serve\base_model_worker.py", line 75, in make_conv_template
2023-12-01 14:37:50 | ERROR | stderr |     conv = get_conversation_template(model_path)
2023-12-01 14:37:50 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\model\model_adapter.py", line 334, in get_conversation_template
2023-12-01 14:37:50 | ERROR | stderr |     return adapter.get_default_conv_template(model_path)
2023-12-01 14:37:50 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\model\model_adapter.py", line 567, in get_default_conv_template
2023-12-01 14:37:50 | ERROR | stderr |     from peft import PeftConfig, PeftModel
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\__init__.py", line 22, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from .auto import (
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\auto.py", line 31, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\mapping.py", line 23, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from .peft_model import (
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\peft_model.py", line 39, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from .tuners import (
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from .lora import LoraConfig, LoraModel
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\tuners\lora\__init__.py", line 21, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from .model import LoraModel
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\tuners\lora\model.py", line 45, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     import bitsandbytes as bnb
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from .autograd._functions import (
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from ._functions import undo_layout, get_inverse_transform_indices
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     import bitsandbytes.functional as F
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     from .cextension import COMPILED_WITH_CUDA, lib
2023-12-01 14:37:50 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
2023-12-01 14:37:50 | ERROR | stderr |     raise RuntimeError('''
2023-12-01 14:37:50 | ERROR | stderr | RuntimeError:
2023-12-01 14:37:50 | ERROR | stderr |         CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
```

我的cuda还是没问题的，跑没有微调的chatglm3-6b是能跑的
```
>>> import torch
>>> print(torch.__version__)
2.1.0+cu121
>>> print(torch.cuda.is_available())
True
>>>
```

未找到有效解决方法

_Originally posted by @ShanJianSoda in https://github.com/chatchat-space/Langchain-Chatchat/issues/2204#issuecomment-1835559782_

**Comment by L-HeliantHuS** [comment]
所以到最后怎么解决的，到底是要的什么文件捏。
