### ISSUE TITLE
[BUG] 服务启动后无法正常请求openai接口

### ISSUE THREAD

**Issue by Ethenlalala** [chatchat-space/Langchain-Chatchat#2255]
服务启动成功后，在web界面选择openai api，发送请求报错。
python 版本： 3.10.3

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59350597/5a919790-c305-47d9-98d0-3773c1675958)

```
当前Embbedings模型： bge-base-zh-v1.5 @ cuda


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================



  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

2023-12-02 18:48:59,163 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56937 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:48:59,166 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-02 18:48:59,458 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56937 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:48:59,459 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56937 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-02 18:48:59,470 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-12-02 18:49:00,511 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56943 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:49:00,513 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-02 18:49:00,793 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56943 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:49:00,794 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56943 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-02 18:49:00,803 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-12-02 18:49:14,107 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56971 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:49:14,110 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-02 18:49:14,387 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56971 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:49:14,388 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56971 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-02 18:49:14,397 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56979 - "POST /llm_model/get_model_config HTTP/1.1" 200 OK
2023-12-02 18:49:33,501 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/get_model_config "HTTP/1.1 200 OK"
2023-12-02 18:49:33,863 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56980 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:49:33,865 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-02 18:49:34,046 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56980 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:49:34,048 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56980 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-02 18:49:34,058 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-12-02 18:49:36,438 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56983 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:49:36,439 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-02 18:49:36,610 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56983 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-02 18:49:36,612 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56983 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-02 18:49:36,621 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:56983 - "POST /chat/chat HTTP/1.1" 200 OK
2023-12-02 18:49:36,628 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-12-02 18:49:58,092 - _base_client.py[line:1360] - INFO: Retrying request to /chat/completions in 0.793840 seconds
2023-12-02 18:50:19,913 - _base_client.py[line:1360] - INFO: Retrying request to /chat/completions in 1.763818 seconds
2023-12-02 18:50:42,721 - utils.py[line:24] - ERROR: Connection error.
Traceback (most recent call last):
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\anyio\_core\_sockets.py", line 167, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\anyio\_backends\_asyncio.py", line 1627, in connect_tcp
    await get_running_loop().create_connection(
  File "D:\Program Files\miniconda3\envs\p100\lib\asyncio\base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "D:\Program Files\miniconda3\envs\p100\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "D:\Program Files\miniconda3\envs\p100\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\Program Files\miniconda3\envs\p100\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\Program Files\miniconda3\envs\p100\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "D:\Program Files\miniconda3\envs\p100\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_backends\anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\anyio\_core\_sockets.py", line 225, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_async\connection_pool.py", line 268, in handle_async_request
    raise exc
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_async\connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_backends\anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "D:\Program Files\miniconda3\envs\p100\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\_base_client.py", line 1307, in _request
    response = await self._client.send(request, auth=self.custom_auth, stream=stream)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "D:\Program Files\miniconda3\envs\p100\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Langchain-Chatchat-master\server\utils.py", line 22, in wrap_done
    await fn
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain\chains\base.py", line 381, in acall
    raise e
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain\chains\base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain_core\language_models\chat_models.py", line 491, in agenerate_prompt
    return await self.agenerate(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain_core\language_models\chat_models.py", line 451, in agenerate
    raise exceptions[0]
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain_core\language_models\chat_models.py", line 554, in _agenerate_with_cache        
    return await self._agenerate(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain\chat_models\openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain_core\language_models\chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain\chat_models\openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\langchain\chat_models\openai.py", line 101, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\resources\chat\completions.py", line 1199, in create
    return await self._post(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\_base_client.py", line 1482, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\_base_client.py", line 1283, in request
    return await self._request(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\_base_client.py", line 1337, in _request
    return await self._retry_request(options, cast_to, retries, stream=stream, stream_cls=stream_cls)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\_base_client.py", line 1364, in _retry_request
    return await self._request(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\_base_client.py", line 1337, in _request
    return await self._retry_request(options, cast_to, retries, stream=stream, stream_cls=stream_cls)
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\_base_client.py", line 1364, in _retry_request
    return await self._request(
  File "D:\Program Files\miniconda3\envs\p100\lib\site-packages\openai\_base_client.py", line 1338, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
2023-12-02 18:50:42,735 - utils.py[line:27] - ERROR: APIConnectionError: Caught exception: Connection error.

```

**Comment by zRzRzRzRzRzRzR** [comment]
在我们的环境下测试正常，windows暂时测不了

**Comment by zRzRzRzRzRzRzR** [comment]
有可能是你隧道的问题，检查一下你20000和7861成功翻墙了没

**Comment by haohao0725** [comment]
> 有可能是你隧道的问题，检查一下你20000和7861成功翻墙了没

请问如何检查是否成功翻墙？谢谢
