### ISSUE TITLE
chatglm3-6b模型加载失败

### ISSUE THREAD

**Issue by YQisme** [chatchat-space/Langchain-Chatchat#2260]
加载chatglm3-6b的7个模块中的第2个模块时出现问题
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/80308783/3e9e2cb6-9fd3-4c83-9c62-b99062553936)
详细log如下

2023-12-03 13:40:14 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 07fb48d9 ...
2023-12-03 13:40:15 | ERROR | stderr | 
Loading checkpoint shards:   0%|                                    | 0/7 [00:00<?, ?it/s]
2023-12-03 13:40:16 | ERROR | stderr | 
Loading checkpoint shards:  14%|████                        | 1/7 [00:01<00:06,  1.09s/it]
2023-12-03 13:40:16 | ERROR | stderr | 
Loading checkpoint shards:  14%|████                        | 1/7 [00:01<00:06,  1.09s/it]
2023-12-03 13:40:16 | ERROR | stderr | 
2023-12-03 13:40:16 | ERROR | stderr | Process model_worker - chatglm3-6b:
2023-12-03 13:40:16 | ERROR | stderr | Traceback (most recent call last):
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/transformers/modeling_utils.py", line 484, in load_state_dict
2023-12-03 13:40:16 | ERROR | stderr |     return torch.load(checkpoint_file, map_location=map_location)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
2023-12-03 13:40:16 | ERROR | stderr |     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/torch/serialization.py", line 1231, in _legacy_load
2023-12-03 13:40:16 | ERROR | stderr |     return legacy_load(f)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/torch/serialization.py", line 1117, in legacy_load
2023-12-03 13:40:16 | ERROR | stderr |     tar.extract('storages', path=tmpdir)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/tarfile.py", line 2295, in extract
2023-12-03 13:40:16 | ERROR | stderr |     tarinfo = self._get_extract_tarinfo(member, filter_function, path)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/tarfile.py", line 2302, in _get_extract_tarinfo
2023-12-03 13:40:16 | ERROR | stderr |     tarinfo = self.getmember(member)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/tarfile.py", line 1985, in getmember
2023-12-03 13:40:16 | ERROR | stderr |     raise KeyError("filename %r not found" % name)
2023-12-03 13:40:16 | ERROR | stderr | KeyError: "filename 'storages' not found"
2023-12-03 13:40:16 | ERROR | stderr | 
2023-12-03 13:40:16 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-12-03 13:40:16 | ERROR | stderr | 
2023-12-03 13:40:16 | ERROR | stderr | Traceback (most recent call last):
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/transformers/modeling_utils.py", line 495, in load_state_dict
2023-12-03 13:40:16 | ERROR | stderr |     raise ValueError(
2023-12-03 13:40:16 | ERROR | stderr | ValueError: Unable to locate the file chatglm3-6b/pytorch_model-00002-of-00007.bin which is necessary to load this pretrained model. Make sure you have saved the model properly.
2023-12-03 13:40:16 | ERROR | stderr | 
2023-12-03 13:40:16 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-12-03 13:40:16 | ERROR | stderr | 
2023-12-03 13:40:16 | ERROR | stderr | Traceback (most recent call last):
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-12-03 13:40:16 | ERROR | stderr |     self.run()
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-12-03 13:40:16 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/yq/Langchain-Chatchat/startup.py", line 386, in run_model_worker
2023-12-03 13:40:16 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/yq/Langchain-Chatchat/startup.py", line 214, in create_model_worker_app
2023-12-03 13:40:16 | ERROR | stderr |     worker = ModelWorker(
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2023-12-03 13:40:16 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 312, in load_model
2023-12-03 13:40:16 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 768, in load_model
2023-12-03 13:40:16 | ERROR | stderr |     model = AutoModel.from_pretrained(
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
2023-12-03 13:40:16 | ERROR | stderr |     return model_class.from_pretrained(
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3480, in from_pretrained
2023-12-03 13:40:16 | ERROR | stderr |     ) = cls._load_pretrained_model(
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3856, in _load_pretrained_model
2023-12-03 13:40:16 | ERROR | stderr |     state_dict = load_state_dict(shard_file)
2023-12-03 13:40:16 | ERROR | stderr |   File "/home/dahe09/anaconda3/envs/chatchat/lib/python3.10/site-packages/transformers/modeling_utils.py", line 500, in load_state_dict
2023-12-03 13:40:16 | ERROR | stderr |     raise OSError(
2023-12-03 13:40:16 | ERROR | stderr | OSError: Unable to load weights from pytorch checkpoint file for 'chatglm3-6b/pytorch_model-00002-of-00007.bin' at 'chatglm3-6b/pytorch_model-00002-of-00007.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by zRzRzRzRzRzRzR** [comment]
模型没全把，我从hf下载的没有这个问题

**Comment by YQisme** [comment]
- 使用 Modelscope 下载模型
```
git lfs install
git clone https://www.modelscope.cn/ZhipuAI/chatglm3-6b.git
```
  - 使用 SwanHub 下载模型
 ```
git lfs install
git clone https://swanhub.co/ZhipuAI/chatglm3-6b.git
```
