### ISSUE TITLE
[BUG] 已开启科学上网，使用duckduckgo提示连接超时问题

### ISSUE THREAD

**Issue by wuwusky** [chatchat-space/Langchain-Chatchat#2268]
输出日志如下：
2023-12-04 10:58:37,479 - _client.py[line:1013] - INFO: HTTP Request: POST http://10.200.4.76:7861/chat/search_engine_chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "E:\ZH\LLM\langchain\server\chat\search_engine_chat.py", line 162, in search_engine_chat_iterator
    docs = await lookup_search_engine(query, search_engine_name, top_k, split_result=split_result)
  File "E:\ZH\LLM\langchain\server\chat\search_engine_chat.py", line 112, in lookup_search_engine
    results = await run_in_threadpool(search_engine, query, result_len=top_k, split_result=split_result)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\ZH\LLM\langchain\server\chat\search_engine_chat.py", line 37, in duckduckgo_search
    return search.results(text, result_len)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\langchain\utilities\duckduckgo_search.py", line 108, in results
    for i, res in enumerate(results, 1):
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 105, in text
    for i, result in enumerate(results, start=1):
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 133, in _text_api
    vqd = self._get_vqd(keywords)
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 63, in _get_vqd
    resp = self._get_url("POST", "https://duckduckgo.com", data={"q": keywords})
  File "C:\Users\ADMIN\miniconda3\envs\langchain\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 53, in _get_url
    raise TimeoutException(f"_get_url() {url} TimeoutException: {ex}")
duckduckgo_search.exceptions.TimeoutException: _get_url() https://duckduckgo.com TimeoutException: timed out
2023-12-04 10:58:48,076 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

问题描述：已开启开学上学，并且浏览器直接访问https://duckduckgo.com是正常的，但是服务选择duck搜索就会提示连接超时，其他配置应该都正常，llm问答，知识库问答，只有这个duck检索出现这个问题

**Comment by wuwusky** [comment]
感谢，我测试了下，可以连通，结果和代码如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34291546/a920d7a9-e376-4b8b-9602-cefde53bdffe)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34291546/ee8d54ee-641a-4632-93f6-d0825a0cf1ae)
但是服务还会提示连接超时，这个是哪里配置不对吗？

**Comment by zRzRzRzRzRzRzR** [comment]
windows的不是简单翻墙就这么简单，你得看我们项目中duckduckgo从哪里转发出去，你得在那个端口放隧道，不是放个梯子就完了

**Comment by M1saka10010** [comment]
> windows的不是简单翻墙就这么简单，你得看我们项目中duckduckgo从哪里转发出去，你得在那个端口放隧道，不是放个梯子就完了

我尝试在env里设置http和https的代理，发现并没有生效。然后看了一圈代码应该是修改langchain的`duckduckgo_search.py`中的
```python
        with DDGS() as ddgs:
```

为

```python
        with DDGS(proxies="socks5://xxxxx", timeout=20) as ddgs:
```

注意一共有两处。 @wuwusky

**Comment by liduang** [comment]
> > windows的不是简单翻墙就这么简单，你得看我们项目中duckduckgo从哪里转发出去，你得在那个端口放隧道，不是放个梯子就完了
> 
> 我尝试在env里设置http和https的代理，发现并没有生效。然后看了一圈代码应该是修改langchain的`duckduckgo_search.py`中的
> 
> ```python
>         with DDGS() as ddgs:
> ```
> 
> 为
> 
> ```python
>         with DDGS(proxies="socks5://xxxxx", timeout=20) as ddgs:
> ```
> 
> 注意一共有两处。 @wuwusky

按照您的方式改了，我调用的时候，多数情况会出现返回202，少数情况正常返回200，奇了怪了，更新到v0.2.9出现的。之前在v0.2.8版本没遇到。不知道是代码问题，还是我的梯子问题

**Comment by M1saka10010** [comment]
> > > windows的不是简单翻墙就这么简单，你得看我们项目中duckduckgo从哪里转发出去，你得在那个端口放隧道，不是放个梯子就完了
> > 
> > 
> > 我尝试在env里设置http和https的代理，发现并没有生效。然后看了一圈代码应该是修改langchain的`duckduckgo_search.py`中的
> > ```python
> >         with DDGS() as ddgs:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 为
> > ```python
> >         with DDGS(proxies="socks5://xxxxx", timeout=20) as ddgs:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注意一共有两处。 @wuwusky
> 
> 按照您的方式改了，我调用的时候，多数情况会出现返回202，少数情况正常返回200，奇了怪了，更新到v0.2.9出现的。之前在v0.2.8版本没遇到。不知道是代码问题，还是我的梯子问题

多半是梯子问题，你可以尝试回退版本试试

**Comment by ShinyWey** [comment]
> > > > windows的不是简单翻墙就这么简单，你得看我们项目中duckduckgo从哪里转发出去，你得在那个端口放隧道，不是放个梯子就完了
> > > 
> > > 
> > > 我尝试在env里设置http和https的代理，发现并没有生效。然后看了一圈代码应该是修改langchain的`duckduckgo_search.py`中的
> > > ```python
> > >         with DDGS() as ddgs:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 为
> > > ```python
> > >         with DDGS(proxies="socks5://xxxxx", timeout=20) as ddgs:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 注意一共有两处。 @wuwusky
> > 
> > 
> > 按照您的方式改了，我调用的时候，多数情况会出现返回202，少数情况正常返回200，奇了怪了，更新到v0.2.9出现的。之前在v0.2.8版本没遇到。不知道是代码问题，还是我的梯子问题
> 
> 多半是梯子问题，你可以尝试回退版本试试

应该不是梯子问题, 我们公司拉了国际专线, 0.2.8可以正常用duckduckgo, 0.2.10不行

**Comment by chuanSir123** [comment]
大佬解决了么，我也无限202，报错说是rateLimit,但是我把https://links.duckduckgo.com/d.js?q=拿出来访问也是202
