### ISSUE TITLE
[BUG] 3. 初始化知识库和配置文件 报错  python init_database.py --recreate-vs

### ISSUE THREAD

**Issue by yangtzelsl** [chatchat-space/Langchain-Chatchat#2283]
拉取最新master代码
按照readme教程，先初始化环境，然后下载模型到本地
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/33994422/e5a7f35e-7bbc-48e6-b191-643f07f14308)

PS E:\PyCharm2019\Langchain-Chatchat> python --version                            
Python 3.11.3 
PS E:\PyCharm2019\Langchain-Chatchat> pip --version
pip 23.3.1 from C:\Python311\Lib\site-packages\pip (python 3.11)

执行3. 初始化知识库和配置文件时报错

PS E:\PyCharm2019\Langchain-Chatchat> python init_database.py --recreate-vs
recreating all vector stores
2023-12-05 23:49:57,505 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/bge-large-zh' from disk.
2023-12-05 23:49:58,128 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh
2023-12-05 23:50:01,397 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh (Caused by SSLError(SSLEOFError(8, 'EOF
 occurred in violation of protocol (_ssl.c:1002)')))"), '(Request ID: 768f0d91-383d-4f69-bfb6-1e49fa0801d7)')
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\PyCharm2019\Langchain-Chatchat\init_database.py", line 108, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "E:\PyCharm2019\Langchain-Chatchat\server\knowledge_base\migrate.py", line 121, in folder2db
    kb.create_kb()
  File "E:\PyCharm2019\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 81, in create_kb
    self.do_create_kb()
  File "E:\PyCharm2019\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 47, in do_create_kb
    self.load_vector_store()
  File "E:\PyCharm2019\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyCharm2019\Langchain-Chatchat\server\knowledge_base\kb_cache\faiss_cache.py", line 90, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyCharm2019\Langchain-Chatchat\server\knowledge_base\kb_cache\faiss_cache.py", line 48, in new_vector_store
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain\vectorstores\faiss.py", line 911, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyCharm2019\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 399, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyCharm2019\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 38, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in norm
  File "C:\Python311\Lib\site-packages\numpy\linalg\linalg.py", line 2541, in norm
    s = (x.conj() * x).real
         ^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

请问是模型下载到本地放置的路径不对么？应该怎么放置呢？

**Comment by lpl071528** [comment]
我也遇到这样的问题，终端运行报错，在pycharm编译器可以正常运行，报错如下：
recreating all vector stores
2023-12-06 10:37:02,408 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/m3e-base' from disk.
2023-12-06 10:37:02,415 - embeddings_api.py[line:39] - ERROR: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ps/lpl/Langchain-Chatchat/init_database.py", line 109, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/ps/lpl/Langchain-Chatchat/server/knowledge_base/migrate.py", line 123, in folder2db
    kb.create_kb()
  File "/home/ps/lpl/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 80, in create_kb
    self.do_create_kb()
  File "/home/ps/lpl/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 47, in do_create_kb
    self.load_vector_store()
  File "/home/ps/lpl/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/lpl/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 90, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/lpl/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 48, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/langchain_sengoic_env/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 510, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/langchain_sengoic_env/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 911, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/lpl/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 380, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/lpl/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/langchain_sengoic_env/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 2582, in norm
    s = (x.conj() * x).real
         ^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

该怎么解决？

**Comment by zRzRzRzRzRzRzR** [comment]
这就是模型没全

**Comment by lly277365** [comment]
我也遇到这个问题，执行了pip install sentence-transformers就可以了

**Comment by zRzRzRzRzRzRzR** [comment]
模型文件没全或者错误，去huggingface 对比一下

**Comment by SHIsue** [comment]
同遇到该问题，执行了pip install sentence-transformers并且去huggingface手动下载bge-large-zh模型，把model_config.py里面的EMBEDDING_MODEL和MODEL_PATH相关的路径改成自己放模型的地方，就好了

**Comment by hustmse1** [comment]
> 同遇到该问题，执行了pip install sentence-transformers并且去huggingface手动下载bge-large-zh模型，把model_config.py里面的EMBEDDING_MODEL和MODEL_PATH相关的路径改成自己放模型的地方，就好了

怎么修改哈？谢谢了！

**Comment by teacher-cow** [comment]
> > 同遇到该问题，执行了pip install sentence-transformers并且去huggingface手动下载bge-large-zh模型，把model_config.py里面的EMBEDDING_MODEL和MODEL_PATH相关的路径改成自己放模型的地方，就好了
> 
> 怎么修改哈？谢谢了！

**Comment by irisrain** [comment]
> > 同遇到该问题，执行了pip install sentence-transformers并且去huggingface手动下载bge-large-zh模型，把model_config.py里面的EMBEDDING_MODEL和MODEL_PATH相关的路径改成自己放模型的地方，就好了
> 
> 怎么修改哈？谢谢了！

configs/model_config.py.example
这个文件直接改就行，改完执行
python copy_config_example.py

**Comment by kevinchi8781** [comment]
> > > 同遇到该问题，执行了pip install sentence-transformers并且去huggingface手动下载bge-large-zh模型，把model_config.py里面的EMBEDDING_MODEL和MODEL_PATH相关的路径改成自己放模型的地方，就好了
> > 
> > 
> > 怎么修改哈？谢谢了！
> 
> configs/model_config.py.example 这个文件直接改就行，改完执行 python copy_config_example.py

还是不行

**Comment by cackako** [comment]
> pip install sentence-transformers

请问您解决了吗

**Comment by cackako** [comment]
> > > > 同遇到该问题，执行了pip install sentence-transformers并且去huggingface手动下载bge-large-zh模型，把model_config.py里面的EMBEDDING_MODEL和MODEL_PATH相关的路径改成自己放模型的地方，就好了
> > > 
> > > 
> > > 怎么修改哈？谢谢了！
> > 
> > 
> > configs/model_config.py.example 这个文件直接改就行，改完执行 python copy_config_example.py
> 
> 还是不行
请问您解决了吗

**Comment by xiaoma444** [comment]
请问您已经解决了吗，我遇到了这个问题，已经按照上述操作都执行过了，但是还是没有效果，感谢

**Comment by AMAG-AB** [comment]
确实解决不了，换了三种方式下载emb模型了，都是报一样的错None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

**Comment by LiiXIAN** [comment]
我也遇到相同的问题了，各种办法尝试了半个月，包括去hug下载模型，改路径，用conda装环境。全都没有效果。
