### ISSUE TITLE
 python startup.py -a出错

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#2286]
目前只有一张4070的显卡，跑chatglm2-6b提示显存不够，所以跑的是chatglm2-6b-int4模型，直接把名字改成了chatglm2-6b。
python startup.py -a
log如下：

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.2.0-37-generic-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
项目版本：v0.2.7
langchain版本：0.0.345. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'gpus': '0',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'max_gpu_memory': '12GiB',
 'model_path': '/home/brother/models/chatglm2-6b',
 'num_gpus': 1,
 'port': 20002}
{'api_key': '',
 'device': 'cuda',
 'gpus': '0',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'max_gpu_memory': '12GiB',
 'num_gpus': 1,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'cuda',
 'gpus': '0',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'max_gpu_memory': '12GiB',
 'model_name': 'gpt-3.5-turbo',
 'num_gpus': 1,
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-12-06 09:35:43,953 - startup.py[line:649] - INFO: 正在启动服务：
2023-12-06 09:35:43,953 - startup.py[line:650] - INFO: 如需查看 llm_api 日志，请前往 /home/brother/Langchain-Chatchat/logs
2023-12-06 09:35:44 | INFO | model_worker | Register to controller
2023-12-06 09:35:45 | ERROR | stderr | INFO:     Started server process [6342]
2023-12-06 09:35:45 | ERROR | stderr | INFO:     Waiting for application startup.
2023-12-06 09:35:45 | ERROR | stderr | INFO:     Application startup complete.
2023-12-06 09:35:45 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-12-06 09:35:45 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker c1627890 ...
2023-12-06 09:35:47 | WARNING | transformers_modules.chatglm2-6b.quantization | Failed to load cpm_kernels:No module named 'cpm_kernels'
2023-12-06 09:35:49 | INFO | model_worker | Register to controller
Process API Server:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brother/Langchain-Chatchat/startup.py", line 429, in run_api_server
    from server.api import create_app
  File "/home/brother/Langchain-Chatchat/server/api.py", line 18, in <module>
    from server.chat.completion import completion
  File "/home/brother/Langchain-Chatchat/server/chat/completion.py", line 9, in <module>
    from langchain.prompts.chat import PromptTemplate
ImportError: cannot import name 'PromptTemplate' from 'langchain.prompts.chat' (/home/brother/myenv/lib/python3.10/site-packages/langchain/prompts/chat.py)

如果我采用文档中指定模型的命令，python startup.py --all-webui --model-name chatglm2，会有新的错误，
log如下：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.2.0-37-generic-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
项目版本：v0.2.7
langchain版本：0.0.345. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2'] @ cuda
{'device': 'cuda',
 'gpus': '0',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'max_gpu_memory': '12GiB',
 'num_gpus': 1,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-12-06 09:40:24,266 - startup.py[line:649] - INFO: 正在启动服务：
2023-12-06 09:40:24,266 - startup.py[line:650] - INFO: 如需查看 llm_api 日志，请前往 /home/brother/Langchain-Chatchat/logs
2023-12-06 09:40:25 | ERROR | stderr | INFO:     Started server process [6743]
2023-12-06 09:40:25 | ERROR | stderr | INFO:     Waiting for application startup.
2023-12-06 09:40:25 | ERROR | stderr | INFO:     Application startup complete.
2023-12-06 09:40:25 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-12-06 09:40:26 | INFO | model_worker | Loading the model ['chatglm2'] on worker 5ac45a82 ...
2023-12-06 09:40:26 | ERROR | stderr | Process model_worker - chatglm2:
2023-12-06 09:40:26 | ERROR | stderr | Traceback (most recent call last):
2023-12-06 09:40:26 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-12-06 09:40:26 | ERROR | stderr |     self.run()
2023-12-06 09:40:26 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-12-06 09:40:26 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/Langchain-Chatchat/startup.py", line 385, in run_model_worker
2023-12-06 09:40:26 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/Langchain-Chatchat/startup.py", line 213, in create_model_worker_app
2023-12-06 09:40:26 | ERROR | stderr |     worker = ModelWorker(
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-12-06 09:40:26 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 306, in load_model
2023-12-06 09:40:26 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 69, in load_model
2023-12-06 09:40:26 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
2023-12-06 09:40:26 | ERROR | stderr |     tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 550, in get_tokenizer_config
2023-12-06 09:40:26 | ERROR | stderr |     resolved_config_file = cached_file(
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/transformers/utils/hub.py", line 430, in cached_file
2023-12-06 09:40:26 | ERROR | stderr |     resolved_file = hf_hub_download(
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
2023-12-06 09:40:26 | ERROR | stderr |     validate_repo_id(arg_value)
2023-12-06 09:40:26 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 164, in validate_repo_id
2023-12-06 09:40:26 | ERROR | stderr |     raise HFValidationError(
2023-12-06 09:40:26 | ERROR | stderr | huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''.

不论我把模型改成什么名字，都报同样的错误.

**Comment by 1184565534** [comment]
请看一下是不是模型加入的位置存在错误。请在“llm_model“字段中加入。

**Comment by qianma819** [comment]
> 请看一下是不是模型加入的位置存在错误。请在“llm_model“字段中加入。

我在model_config.py.example中，定义MODEL_ROOT_PATH=“home/borther/models/"，模型统一放到这个文件下面了。
请在“llm_model“字段中加入。这个是什么意思？

**Comment by 1184565534** [comment]
在model_config.py文件中，有一个MODEL_PATH字段，在该字段下的"llm_model"字段中配置你的量化模型路径。
