### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by zhanghu11** [chatchat-space/Langchain-Chatchat#2290]
配置：
MODEL_ROOT_PATH = "D:/chat/Langchain-Chatchat/model/"
LLM_MODELS = ["chatglm3-6b"] # "Qwen-1_8B-Chat",
EMBEDDING_MODEL = "bge-large-zh"
MODEL_PATH = {
    "embed_model": {
                "bge-large-zh": "D:/chat/Langchain-Chatchat/model/bge-large-zh"
    },
    "llm_model": {
        "chatglm3-6b": "D:/chat/Langchain-Chatchat/model/chatglm3-6b",
    },
}
我只修改了这些配置，无论我怎么修改都是报错
2023-12-06 16:31:12 | ERROR | stderr |
2023-12-06 16:31:16 | INFO | model_worker | Register to controller
INFO:     Started server process [9740]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
Process WEBUI Server:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\chat\Langchain-Chatchat\startup.py", line 464, in run_webui
    p = subprocess.Popen(cmd)

**Comment by CuteCuteYu** [comment]
streamlit添加到环境变量就好了
