### ISSUE TITLE
[BUG] LLM添加Qwen-14B-Chat无法找到模型文件 / LLM added Qwen-14B-Chat unable to find model file

### ISSUE THREAD

**Issue by HaoHaoDaYouXi** [chatchat-space/Langchain-Chatchat#2293]
**问题描述 / Problem Description**
LLM添加Qwen-14B-Chat无法找到模型文件 / LLM added Qwen-14B-Chat unable to find model file

**复现问题的步骤 / Steps to Reproduce**
"llm_model": {
    "Qwen-14B-Chat": "Qwen-14B-Chat",
},
 
LLM_MODELS = ["Qwen-14B-Chat"]
修改加载模型为Qwen-14B-Chat，并添加模型地址，模型文件是通过hf上命令下载整个的 / Modify the loading model to Qwen-14B-Chat and add the model address，The model file is downloaded as a whole through the command on hf

**预期的结果 / Expected Result**
加载模型数据 / Load model data

**实际结果 / Actual Result**
无法找到模型文件 / Unable to find model file
错误信息 / error message
2023-12-06 16:03:58 | WARNING | transformers_modules.Qwen-14B-Chat.modeling_qwen | The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
2023-12-06 16:03:58 | WARNING | transformers_modules.Qwen-14B-Chat.modeling_qwen | Try importing flash-attention for faster inference...
2023-12-06 16:03:58 | WARNING | transformers_modules.Qwen-14B-Chat.modeling_qwen | Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
2023-12-06 16:03:58 | WARNING | transformers_modules.Qwen-14B-Chat.modeling_qwen | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
2023-12-06 16:03:59 | ERROR | stderr | Process model_worker - Qwen-14B-Chat:
2023-12-06 16:03:59 | ERROR | stderr | Traceback (most recent call last):
2023-12-06 16:03:59 | ERROR | stderr |   File "F:\AI\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
2023-12-06 16:03:59 | ERROR | stderr |     self.run()
2023-12-06 16:03:59 | ERROR | stderr |   File "F:\AI\Python310\lib\multiprocessing\process.py", line 108, in run
2023-12-06 16:03:59 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-12-06 16:03:59 | ERROR | stderr |   File "F:\AI\Langchain-Chatchat\startup.py", line 383, in run_model_worker
2023-12-06 16:03:59 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-12-06 16:03:59 | ERROR | stderr |   File "F:\AI\Langchain-Chatchat\startup.py", line 211, in create_model_worker_app
2023-12-06 16:03:59 | ERROR | stderr |     worker = ModelWorker(
2023-12-06 16:03:59 | ERROR | stderr |   File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\fastchat\serve\model_worker.py", line 74, in __init__
2023-12-06 16:03:59 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-12-06 16:03:59 | ERROR | stderr |   File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\fastchat\model\model_adapter.py", line 251, in load_model
2023-12-06 16:03:59 | ERROR | stderr |     model, tokenizer = adapter.load_compress_model(
2023-12-06 16:03:59 | ERROR | stderr |   File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\fastchat\model\model_adapter.py", line 96, in load_compress_model
2023-12-06 16:03:59 | ERROR | stderr |     return load_compress_model(
2023-12-06 16:03:59 | ERROR | stderr |   File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\fastchat\model\compression.py", line 172, in load_compress_model
2023-12-06 16:03:59 | ERROR | stderr |     raise ValueError(
2023-12-06 16:03:59 | ERROR | stderr | ValueError: Cannot find any model weight files. Please check your (cached) weight path: F:\AI\Qwen-14B-Chat
2023-12-06 16:04:08,727 - startup.py[line:852] - WARNING: Sending SIGKILL to {}
2023-12-06 16:04:08,727 - startup.py[line:852] - WARNING: Sending SIGKILL to {'Qwen-14B-Chat': <Process name='model_worker - Qwen-14B-Chat (11648)' pid=11648 parent=9992 stopped exitcode=1 daemon>}
2023-12-06 16:04:08,727 - startup.py[line:852] - WARNING: Sending SIGKILL to <Process name='controller (7596)' pid=7596 parent=9992 started daemon>
2023-12-06 16:04:08,727 - startup.py[line:852] - WARNING: Sending SIGKILL to <Process name='openai_api (8896)' pid=8896 parent=9992 started daemon>
2023-12-06 16:04:08,727 - startup.py[line:852] - WARNING: Sending SIGKILL to <Process name='API Server' parent=9992 initial daemon>

**Comment by HaoHaoDaYouXi** [comment]
chatglm3-6b的模型数据加载正常的，替换成chatglm3-6b就可以正常加载

**Comment by pengyixuan** [comment]
可以在startup.py文件的第385行插入如下代码：
    if model_name in ["Qwen-14B-Chat","Qwen-7B-Chat"]:
       kwargs["model_path"] = model_path + "/"
       print("this is path:"+kwargs["model_path"])

**Comment by HaoHaoDaYouXi** [comment]
模型地址应该没错的，GLM3的是可以使用的，更换成qwen的启动时加载不了权重文件

**Comment by openai1998** [comment]
一样问题

**Comment by zRzRzRzRzRzRzR** [comment]
> 模型地址应该没错的，GLM3的是可以使用的，更换成qwen的启动时加载不了权重文件，Qwen单独启动显存不够，所以想着通过langchat启动试试

我们也是用hf载入的，单独启动显存不够我们启动显存也是不够的

**Comment by HaoHaoDaYouXi** [comment]
暂时只能通过hf载入模型是么？

**Comment by HaoHaoDaYouXi** [comment]
> > 模型地址应该没错的，GLM3的是可以使用的，更换成qwen的启动时加载不了权重文件，Qwen单独启动显存不够，所以想着通过langchat启动试试
> 
> 我们也是用hf载入的，单独启动显存不够我们启动显存也是不够的

暂时只能通过hf载入启动是么？

**Comment by zRzRzRzRzRzRzR** [comment]
是的
