### ISSUE TITLE
0.2.8版本LLM问答API报错

### ISSUE THREAD

**Issue by ShinyWey** [chatchat-space/Langchain-Chatchat#2294]
**问题描述 / Problem Description**
0.2.7的api都是能用的, 0.2.8的LLMChain的API回答如下:
````
Traceback (most recent call last):
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/ai1/miniconda3/envs/lc/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/ai1/project/Langchain-Chatchat/server/chat/chat.py", line 99, in chat_iterator
    {"text": answer, "message_id": message_id},
UnboundLocalError: local variable 'message_id' referenced before assignment
````

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.8
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-Chat
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： Milvus

**Comment by ShinyWey** [comment]
看到多了个history_len和conversation_id字段, 想问下第一个默认的-1是什么意思, 第二个id需要手动指定吗

**Comment by zRzRzRzRzRzRzR** [comment]
这个conversation_id和history_len是从webui传进来的，可以为None

**Comment by chenwenfeng** [comment]
conversation_id 默认 webui 会生成 如果自己开发 ui 好像得自己生成 不传会报错

**Comment by ShinyWey** [comment]
> 这个conversation_id和history_len是从webui传进来的，可以为None

conversation_id必须得赋值, 实测None不行, 不传该参数也不行
history_len倒是没什么问题
