### ISSUE TITLE
[BUG]  500 Internal Server Error

### ISSUE THREAD

**Issue by wade2s** [chatchat-space/Langchain-Chatchat#2302]
**问题描述 / Problem Description**

API, webUI均能正常打开，知识库管理也能正常检索文档，但是无法调用本地大模型回答问题
[issue.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/13596300/issue.txt)

2023-12-07 14:14:32 | INFO | model_worker | Register to controller
2023-12-07 14:14:46 | ERROR | stderr | INFO:     Started server process [30008]
2023-12-07 14:14:46 | ERROR | stderr | INFO:     Waiting for application startup.
2023-12-07 14:14:46 | ERROR | stderr | INFO:     Application startup complete.
2023-12-07 14:14:46 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
2023-12-07 14:14:53 | INFO | stdout |
2023-12-07 14:14:53 | INFO | stdout |
2023-12-07 14:14:53 | INFO | stdout | ==============================Langchain-Chatchat Configuration==============================
2023-12-07 14:14:53 | INFO | stdout | 操作系统：Windows-10-10.0.22621-SP0.
2023-12-07 14:14:53 | INFO | stdout | python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
2023-12-07 14:14:53 | INFO | stdout | 项目版本：v0.2.8
2023-12-07 14:14:53 | INFO | stdout | langchain版本：0.0.310. fastchat版本：0.2.29
2023-12-07 14:14:53 | INFO | stdout |
2023-12-07 14:14:53 | INFO | stdout |
2023-12-07 14:14:53 | INFO | stdout | 当前使用的分词器：ChineseRecursiveTextSplitter
2023-12-07 14:14:53 | INFO | stdout | 当前启动的LLM模型：['chatglm3-6b'] @ cuda
2023-12-07 14:14:53 | INFO | stdout | {'device': 'cuda',
2023-12-07 14:14:53 | INFO | stdout |  'host': '127.0.0.1',
2023-12-07 14:14:53 | INFO | stdout |  'infer_turbo': False,
2023-12-07 14:14:53 | INFO | stdout |  'model_path': 'D:\\downloads\\Programs\\wenda-0725\\wd-git\\wenda\\model\\chatglm3-6b',
2023-12-07 14:14:53 | INFO | stdout |  'model_path_exists': True,
2023-12-07 14:14:53 | INFO | stdout |  'port': 20002}
2023-12-07 14:14:53 | INFO | stdout | 当前Embbedings模型： m3e-base @ cuda
2023-12-07 14:14:53 | INFO | stdout |
2023-12-07 14:14:53 | INFO | stdout |
2023-12-07 14:14:53 | INFO | stdout | 服务端运行信息：
2023-12-07 14:14:53 | INFO | stdout |     OpenAI API Server: http://127.0.0.1:20000/v1
2023-12-07 14:14:53 | INFO | stdout |     Chatchat  API  Server: http://127.0.0.1:7861
2023-12-07 14:14:53 | INFO | stdout |     Chatchat WEBUI Server: http://127.0.0.1:8501
2023-12-07 14:14:53 | INFO | stdout | ==============================Langchain-Chatchat Configuration==============================
2023-12-07 14:14:53 | INFO | stdout |
2023-12-07 14:14:53 | INFO | stdout |

  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

2023-12-07 14:15:06 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-12-07 14:15:06 | INFO | stdout | INFO:     127.0.0.1:6736 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-07 14:15:06 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-07 14:15:06 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-12-07 14:15:06 | INFO | stdout | INFO:     127.0.0.1:6736 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-07 14:15:06 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-07 14:15:06 | INFO | stdout | INFO:     127.0.0.1:6736 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-07 14:15:06 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-12-07 14:15:13 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-12-07 14:15:13 | INFO | stdout | INFO:     127.0.0.1:6769 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-07 14:15:13 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-07 14:15:13 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2023-12-07 14:15:13 | INFO | stdout | INFO:     127.0.0.1:6769 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-07 14:15:13 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-07 14:15:13 | INFO | stdout | INFO:     127.0.0.1:6769 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-07 14:15:13 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-12-07 14:15:13 | INFO | stdout | INFO:     127.0.0.1:6769 - "POST /chat/chat HTTP/1.1" 200 OK
2023-12-07 14:15:13 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\fastchat\serve\model_worker.py", line 456, in api_get_conv
    return worker.get_conv_template()
NameError: name 'worker' is not defined
2023-12-07 14:15:14 | INFO | stdout | INFO:     127.0.0.1:6773 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2023-12-07 14:15:14 | INFO | openai | message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None request_id=None response_code=500
2023-12-07 14:15:14 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-12-07 14:15:14 | ERROR | stderr | Traceback (most recent call last):
2023-12-07 14:15:14 | ERROR | stderr |   File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
2023-12-07 14:15:14 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-12-07 14:15:14 | ERROR | stderr |   File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
2023-12-07 14:15:14 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-12-07 14:15:14 | ERROR | stderr |   File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\fastapi\applications.py", line 292, in __call__
2023-12-07 14:15:14 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-12-07 14:15:14 | ERROR | stderr |   File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\applications.py", line 122, in __call__
2023-12-07 14:15:14 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-12-07 14:15:14 | ERROR | stderr |   File "C:\Users\xiaoj\AppData\Roaming\Python\Python310\site-packages\starlette\middleware\errors.py", line 184, in __call__
2023-12-07 14:15:14 | ERROR | stderr |     raise exc
(langchain-chatchat) C:\Users\xiaoj\chatchat>

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v0.2.8
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B / 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: win11
- Python 版本 / Python version:

**Comment by zRzRzRzRzRzRzR** [comment]
大概率是配置文件没配对，按照wiki配了后告诉我配置文件

**Comment by liunux4odoo** [comment]
按照requirements更新依赖

**Comment by dancruiser** [comment]
问题解决了吗？如何解决的啊？

**Comment by zRzRzRzRzRzRzR** [comment]
按照requirements更新依赖

**Comment by pangliye** [comment]
问题解决了吗？如何解决的啊？我也遇到了
