### ISSUE TITLE
[BUG] python init_database.py --recreate-vs执行报错

### ISSUE THREAD

**Issue by strLights** [chatchat-space/Langchain-Chatchat#2306]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
执行 ‘python init_database.py --recreate-vs’出现报错
**复现问题的步骤 / Steps to Reproduce**
1. 执行 ‘python init_database.py --recreate-vs’
2. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
正常执行
**实际结果 / Actual Result**
报错

- langchain-ChatGLM 版本/commit 号：v0.2.8
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：  faiss
- 操作系统及版本 / Operating system and version:  miniconda
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
Traceback (most recent call last):
  File "E:\code\python\an\Langchain-Chatchat\init_database.py", line 3, in <module>
    from server.knowledge_base.migrate import (create_tables, reset_tables, import_from_db,
  File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\migrate.py", line 1, in <module>
    from configs import (
  File "E:\code\python\an\Langchain-Chatchat\configs\__init__.py", line 1, in <module>
    from .basic_config import *
  File "E:\code\python\an\Langchain-Chatchat\configs\basic_config.py", line 3, in <module>
    import langchain
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\agents\tools.py", line 4, in <module>
    from langchain.callbacks.manager import (
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\callbacks\__init__.py", line 3, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\callbacks\aim_callback.py", line 4, in <module>
    from langchain.callbacks.base import BaseCallbackHandler
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\callbacks\base.py", line 7, in <module>
    from langchain.schema import (
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\schema.py", line 147, in <module>
    class ChatGeneration(Generation):
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\langchain\schema.py", line 154, in ChatGeneration
    def set_text(cls, values: Dict[str, Any]) -> Dict[str, Any]:
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\pydantic\deprecated\class_validators.py", line 231, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "C:\Users\LeeYoung\.conda\envs\pytorch\lib\site-packages\pydantic\deprecated\class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip

**Comment by zRzRzRzRzRzRzR** [comment]
pydantic版本多少

**Comment by strLights** [comment]
pydantic~1.10.12

**Comment by liunux4odoo** [comment]
> > pydantic版本多少
> 
> 1.10.12

可这个报错信息像是 v2 的。

**Comment by energy888666** [comment]
> 现在这个问题没有了，报了新的错误 Traceback (most recent call last): File "E:\code\python\an\Langchain-Chatchat\init_database.py", line 3, in from server.knowledge_base.migrate import (create_tables, reset_tables, import_from_db, File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\migrate.py", line 11, in from server.knowledge_base.kb_service.base import KBServiceFactory File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 29, in from server.embeddings_api import embed_texts File "E:\code\python\an\Langchain-Chatchat\server\embeddings_api.py", line 3, in from server.model_workers.base import ApiEmbeddingsParams File "E:\code\python\an\Langchain-Chatchat\server\model_workers__init__.py", line 1, in from .base import * File "E:\code\python\an\Langchain-Chatchat\server\model_workers\base.py", line 5, in from fastchat.serve.base_model_worker import BaseModelWorker ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'

如何 解决呢？  我现在也是 这个报错？
