### ISSUE TITLE
使用知识库问答时报错

### ISSUE THREAD

**Issue by xiaobai1026** [chatchat-space/Langchain-Chatchat#2307]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 75, in knowledge_base_chat_iterator
    docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 37, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 181, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 64, in do_search
    embeddings = embed_func.embed_query(query)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 403, in embed_query
    query_embed = embeddings[0]
TypeError: 'NoneType' object is not subscriptable
2023-12-07 16:26:36,085 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by zdxy** [comment]
你好，请问这个问题怎么解决的
