### ISSUE TITLE
已开vpn，浏览器能访问openai接口，但是选择LLM模型为openai-api的时候聊天报错openai.APIConnectionError: Connection error.

### ISSUE THREAD

**Issue by zhanghaotian123** [chatchat-space/Langchain-Chatchat#2318]
2023-12-08 09:05:21,918 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58441 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-08 09:05:21,921 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-08 09:05:22,109 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58441 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-08 09:05:22,111 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58441 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-08 09:05:22,123 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58441 - "POST /chat/chat HTTP/1.1" 200 OK
2023-12-08 09:05:22,132 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
-----------------------用户输入prompt-----------------------
input_variables=['input'] messages=[ChatMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='{% raw %}你好{% endraw %}', template_format='jinja2'), role='user'), ChatMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='{% raw %}{% endraw %}', template_format='jinja2'), role='assistant'), ChatMessagePromptTemplate(prompt=PromptTemplate(input_variables=['input'], template='{{ input }}', template_format='jinja2'), role='user')]
-----------------------------------------------------
-----------------------用户选择的模型model-----------------------
verbose=True callbacks=[<langchain.callbacks.streaming_aiter.AsyncIteratorCallbackHandler object at 0x000001EDF9362260>, <server.callback_handler.conversation_callback_handler.ConversationCallbackHandler object at 0x000001EDF93611E0>] client=<openai.resources.chat.completions.Completions object at 0x000001EDF9361390> async_client=<openai.resources.chat.completions.AsyncCompletions object at 0x000001EDF9376FB0> openai_api_key='sk-g1BkAbR7DJxXXXXXXXXPY90aXXXXVPvKuuq' **openai_api_base='https://api.openai.com/v1'** openai_proxy='' streaming=True
-----------------------------------------------------
-----------------------用户聊天记忆memory-----------------------
None
-----------------------------------------------------
2023-12-08 09:05:43,545 - _base_client.py[line:1420] - INFO: Retrying request to /chat/completions in 0.792232 seconds
2023-12-08 09:06:05,419 - _base_client.py[line:1420] - INFO: Retrying request to /chat/completions in 1.715061 seconds
2023-12-08 09:06:28,150 - utils.py[line:24] - ERROR: Connection error.
Traceback (most recent call last):
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\anyio\_core\_sockets.py", line 167, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\anyio\_backends\_asyncio.py", line 1627, in connect_tcp
    await get_running_loop().create_connection(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\asyncio\base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_backends\anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\anyio\_core\_sockets.py", line 225, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_async\connection_pool.py", line 268, in handle_async_request
    raise exc
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_async\connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_backends\anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\_base_client.py", line 1342, in _request
    response = await self._client.send(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zht\Desktop\AI\project\localknowledge\Langchain-Chatchat\server\utils.py", line 22, in wrap_done
    await fn
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain\chains\base.py", line 381, in acall
    raise e
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain\chains\base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain_core\language_models\chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain_core\language_models\chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain_core\language_models\chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain\chat_models\openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain_core\language_models\chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain\chat_models\openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\langchain\chat_models\openai.py", line 101, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\resources\chat\completions.py", line 1199, in create
    return await self._post(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\_base_client.py", line 1542, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\_base_client.py", line 1316, in request
    return await self._request(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\_base_client.py", line 1389, in _request
    return await self._retry_request(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\_base_client.py", line 1424, in _retry_request
    return await self._request(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\_base_client.py", line 1389, in _request
    return await self._retry_request(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\_base_client.py", line 1424, in _retry_request
    return await self._request(
  File "C:\Users\zht\.conda\envs\new_chatchat\lib\site-packages\openai\_base_client.py", line 1398, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
2023-12-08 09:06:28,155 - utils.py[line:27] - ERROR: APIConnectionError: Caught exception: Connection error.

**Comment by zRzRzRzRzRzRzR** [comment]
windows 系统下你要指定7861端口成功穿透到外网而不是简单开个vpn就行了

**Comment by WenxuanZhao** [comment]
我使用命令提示符设置了代理后（同时软件开全局），可以使用openai，但是如果模型同时存在zhipuai就会报错。

**Comment by iwannabeluchi** [comment]
> windows 系统下你要指定7861端口成功穿透到外网而不是简单开个vpn就行了

请问windows系统下要怎么穿透到外网呀，查了好久都不行求教，谢谢

**Comment by Amber-nannan** [comment]
我打开windows设置->代理服务器设置，发现自己的地址和端口分别是127.0.0.1和33210，然后加上
import os
os.environ["http_proxy"] = "http://127.0.0.1:33210"
os.environ["https_proxy"] = "http://127.0.0.1:33210"
结果就好了（虽然我依旧不太懂这是为什么）

**Comment by Wbbetty** [comment]
> 我打开windows设置->代理服务器设置，发现自己的地址和端口分别是127.0.0.1和33210，然后加上 import os os.environ["http_proxy"] = "http://127.0.0.1:33210" os.environ["https_proxy"] = "http://127.0.0.1:33210" 结果就好了（虽然我依旧不太懂这是为什么）

这是加在哪里呀
