### ISSUE TITLE
启动最后一步报AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by hopeforus** [chatchat-space/Langchain-Chatchat#2319]
host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/hope/work/models/chatglm3-6b-32k',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:7002
==============================Langchain-Chatchat Configuration==============================

Traceback (most recent call last):
  File "/home/hope/.local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by hopeforus** [comment]
'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================


2023-12-08 09:12:24,031 - startup.py[line:650] - INFO: 正在启动服务：
2023-12-08 09:12:24,031 - startup.py[line:651] - INFO: 如需查看 llm_api 日志，请前往 /home/hope/work/Langchain-Chatchat/logs
2023-12-08 09:12:32 | ERROR | stderr | INFO:     Started server process [2650482]
2023-12-08 09:12:32 | ERROR | stderr | INFO:     Waiting for application startup.
2023-12-08 09:12:32 | ERROR | stderr | INFO:     Application startup complete.
2023-12-08 09:12:32 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-12-08 09:12:33 | INFO | model_worker | Loading the model ['chatglm3-6b-32k'] on worker adfd6d63 ...
Loading checkpoint shards:   0%|                                                                                                                       | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|███████████████▊                                                                                               | 1/7 [00:01<00:07,  1.28s/it]
Loading checkpoint shards:  29%|███████████████████████████████▋                                                                               | 2/7 [00:02<00:06,  1.33s/it]
Loading checkpoint shards:  43%|███████████████████████████████████████████████▌                                                               | 3/7 [00:03<00:05,  1.33s/it]
Loading checkpoint shards:  57%|███████████████████████████████████████████████████████████████▍                                               | 4/7 [00:05<00:03,  1.31s/it]
Loading checkpoint shards:  71%|███████████████████████████████████████████████████████████████████████████████▎                               | 5/7 [00:06<00:02,  1.32s/it]
Loading checkpoint shards:  86%|███████████████████████████████████████████████████████████████████████████████████████████████▏               | 6/7 [00:07<00:01,  1.32s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.15s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.24s/it]
2023-12-08 09:12:42 | ERROR | stderr | 
2023-12-08 09:12:45 | INFO | model_worker | Register to controller
INFO:     Started server process [2650550]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)

**Comment by zRzRzRzRzRzRzR** [comment]
确定是按照req装的吗
`AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'`这个错误估计是你环境问题

**Comment by hopeforus** [comment]
是的，我按照req安装了两次，我再安装一次试一下，是不是不支持 GLM 32K 的原因？
