### ISSUE TITLE
调用自己的私有化模型API，能正常返回结果，但是结束之后总会出现API Error的错误

### ISSUE THREAD

**Issue by mayidu** [chatchat-space/Langchain-Chatchat#2323]
你好，我现在给项目中添加了自己的私有化模型的API接口，以线上调用的方式进行，可以正常调用，但每次对话结束之后会有一个如下的报错，请您帮我看一下这个问题是哪里的问题呢？（备注：报错也不影响后面的使用）

023-12-08 10:17:38,864 - utils.py[line:24] - ERROR: An error ocurred during streaming
Traceback (most recent call last):
  File "/home/xxx/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 491, in agenerate_prompt
    return await self.agenerate(
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 451, in agenerate
    raise exceptions[0]
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_streaming.py", line 94, in __aiter__
    async for item in self._iterator:
  File "/home/xxx/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_streaming.py", line 114, in __stream__
    raise APIError(
openai.APIError: An error ocurred during streaming
2023-12-08 10:17:38,866 - utils.py[line:27] - ERROR: APIError: Caught exception: An error ocurred during streaming

**Comment by zRzRzRzRzRzRzR** [comment]
使用类似OpenAI的格式来做，这样就能调用langchain的openai-api功能，或者使用类似`server\model_worker`中的模型实现方式从`fschat`中注册

**Comment by lamwin24** [comment]
> 使用类似OpenAI的格式来做，这样就能调用langchain的openai-api功能，或者使用类似`server\model_worker`中的模型实现方式从`fschat`中注册

大佬，能指教下调用本地部署openai吗？方便的话加Q:295899951

**Comment by LeFuGang** [comment]
请问下大佬，你是怎么调用自己私有化大模型得，怎么配置呀？能说下不，谢谢了

**Comment by zRzRzRzRzRzRzR** [comment]
就是把我们配置文件里面openai的url换成你自己的，前提是你的后端要是跟openai完全一样

**Comment by LeFuGang** [comment]
> 就是把我们配置文件里面openai的url换成你自己的，前提是你的后端要是跟openai完全一样

> 就是把我们配置文件里面openai的url换成你自己的，前提是你的后端要是跟openai完全一样

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/28383188/508ef05a-28ba-4f45-bcb6-3211bf952d52)
这样吗？

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/28383188/8e5bf8e5-9547-43af-980b-64e09fd18657)
openai我使用得是chatglm.cpp中得openai_api.py文件生成得，这样可以吗

**Comment by zRzRzRzRzRzRzR** [comment]
可以，你自己要能调通就行
