### ISSUE TITLE
web 页面无法进行对话、 无法创建知识库

### ISSUE THREAD

**Issue by dancruiser** [chatchat-space/Langchain-Chatchat#2335]
安装了 langchian-chatchat v 0.2.7 和 v 0.2.8 .都可以正常启动，模型也都可以加载。web对话页面、知识库页面都可以正常出现。
但是，在对话页面 输入 “你是谁” , 感觉系统卡死在 “思考中”， 不能生成对话。
系统报错信息：
2023-12-09 03:20:52,048 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-12-09 03:20:52 | INFO | stdout | INFO:     127.0.0.1:35782 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-12-09 03:20:52,143 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2023-12-09 03:20:52 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2023-12-09 03:22:32 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-12-09 03:22:32 | ERROR | stderr | Traceback (most recent call last):
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 34, in read
2023-12-09 03:22:32 | ERROR | stderr |     return await self._stream.receive(max_bytes=max_bytes)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1203, in receive
2023-12-09 03:22:32 | ERROR | stderr |     await self._protocol.read_event.wait()
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/asyncio/locks.py", line 214, in wait
2023-12-09 03:22:32 | ERROR | stderr |     await fut
2023-12-09 03:22:32 | ERROR | stderr | asyncio.exceptions.CancelledError
2023-12-09 03:22:32 | ERROR | stderr |
2023-12-09 03:22:32 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-12-09 03:22:32 | ERROR | stderr |
2023-12-09 03:22:32 | ERROR | stderr | Traceback (most recent call last):
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
2023-12-09 03:22:32 | ERROR | stderr |     yield
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 32, in read
2023-12-09 03:22:32 | ERROR | stderr |     with anyio.fail_after(timeout):
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 119, in __exit__
2023-12-09 03:22:32 | ERROR | stderr |     raise TimeoutError
2023-12-09 03:22:32 | ERROR | stderr | TimeoutError
2023-12-09 03:22:32 | ERROR | stderr |
2023-12-09 03:22:32 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-12-09 03:22:32 | ERROR | stderr |
2023-12-09 03:22:32 | ERROR | stderr | Traceback (most recent call last):
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
2023-12-09 03:22:32 | ERROR | stderr |     yield
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 249, in __aiter__
2023-12-09 03:22:32 | ERROR | stderr |     async for part in self._httpcore_stream:
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
2023-12-09 03:22:32 | ERROR | stderr |     async for part in self._stream:
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
2023-12-09 03:22:32 | ERROR | stderr |     raise exc
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
2023-12-09 03:22:32 | ERROR | stderr |     async for chunk in self._connection._receive_response_body(**kwargs):
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
2023-12-09 03:22:32 | ERROR | stderr |     event = await self._receive_event(timeout=timeout)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
2023-12-09 03:22:32 | ERROR | stderr |     data = await self._network_stream.read(
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 31, in read
2023-12-09 03:22:32 | ERROR | stderr |     with map_exceptions(exc_map):
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/contextlib.py", line 153, in __exit__
2023-12-09 03:22:32 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2023-12-09 03:22:32 | ERROR | stderr |     raise to_exc(exc) from exc
2023-12-09 03:22:32 | ERROR | stderr | httpcore.ReadTimeout
2023-12-09 03:22:32 | ERROR | stderr |
2023-12-09 03:22:32 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-12-09 03:22:32 | ERROR | stderr |
2023-12-09 03:22:32 | ERROR | stderr | Traceback (most recent call last):
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-12-09 03:22:32 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     raise exc
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     await self.app(scope, receive, send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     raise exc
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     raise e
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     await self.app(scope, receive, send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-12-09 03:22:32 | ERROR | stderr |     await self.app(scope, receive, send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
2023-12-09 03:22:32 | ERROR | stderr |     await response(scope, receive, send)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2023-12-09 03:22:32 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2023-12-09 03:22:32 | ERROR | stderr |     raise exceptions[0]
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2023-12-09 03:22:32 | ERROR | stderr |     await func()
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
2023-12-09 03:22:32 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 472, in chat_completion_stream_generator
2023-12-09 03:22:32 | ERROR | stderr |     async for content in generate_completion_stream(gen_params, worker_addr):
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 657, in generate_completion_stream
2023-12-09 03:22:32 | ERROR | stderr |     async for raw_chunk in response.aiter_raw():
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_models.py", line 990, in aiter_raw
2023-12-09 03:22:32 | ERROR | stderr |     async for raw_stream_bytes in self.stream:
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_client.py", line 146, in __aiter__
2023-12-09 03:22:32 | ERROR | stderr |     async for chunk in self._stream:
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 248, in __aiter__
2023-12-09 03:22:32 | ERROR | stderr |     with map_httpcore_exceptions():
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/contextlib.py", line 153, in __exit__
2023-12-09 03:22:32 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2023-12-09 03:22:32 | ERROR | stderr |   File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
2023-12-09 03:22:32 | ERROR | stderr |     raise mapped_exc(message) from exc
2023-12-09 03:22:32 | ERROR | stderr | httpx.ReadTimeout
2023-12-09 03:22:32,175 - utils.py[line:24] - ERROR: peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/h11/_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 249, in __aiter__
    async for part in self._httpcore_stream:
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
    async for part in self._stream:
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
    raise exc
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_async/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/root/anaconda3/envs/chatchat/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Langchain-Chatchat-0.28/server/utils.py", line 22, in wrap_done
    await fn
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_streaming.py", line 94, in __aiter__
    async for item in self._iterator:
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_streaming.py", line 107, in __stream__
    async for sse in iterator:
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_streaming.py", line 98, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_streaming.py", line 190, in aiter
    async for line in iterator:
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_models.py", line 966, in aiter_lines
    async for text in self.aiter_text():
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_models.py", line 953, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_models.py", line 932, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_models.py", line 990, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 248, in __aiter__
    with map_httpcore_exceptions():
  File "/root/anaconda3/envs/chatchat/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2023-12-09 03:22:32,200 - utils.py[line:27] - ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)
2023-12-09 03:22:42,787 - faiss_cache.py[line:80] - INFO: loading vector store in 'University History OutLine/vector_store/bge-large-zh' from disk.
2023-12-09 03:22:43,194 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: bge-large-zh
2023-12-09 03:22:53,890 - embeddings_api.py[line:39] - ERROR: [Errno 2] No such file or directory: 'bge-large-zh/1_Pooling/config.json'
2023-12-09 03:22:53,903 - kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
INFO:     127.0.0.1:42032 - "POST /knowledge_base/create_knowledge_base HTTP/1.1" 200 OK
2023-12-09 03:22:53,905 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/create_knowledge_base "HTTP/1.1 200 OK"
INFO:     127.0.0.1:41910 - "POST /knowledge_base/upload_docs HTTP/1.1" 200 OK
2023-12-09 03:22:57,329 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/upload_docs "HTTP/1.1 200 OK"
INFO:     127.0.0.1:47306 - "POST /knowledge_base/upload_docs HTTP/1.1" 200 OK
2023-12-09 03:23:05,506 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/upload_docs "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53550 - "POST /knowledge_base/upload_docs HTTP/1.1" 200 OK
2023-12-09 03:23:18,233 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/upload_docs "HTTP/1.1 200 OK"
2023-12-09 03:23:23,613 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53562 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-09 03:23:23,615 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-09 03:23:23,671 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53562 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-09 03:23:23,672 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53562 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-09 03:23:23,688 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
^C  Stopping...
2023-12-09 03:30:22,497 - startup.py[line:855] - WARNING: Sending SIGKILL to {}
2023-12-09 03:30:22,497 - startup.py[line:855] - WARNING: Sending SIGKILL to {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (71603)' pid=71603 parent=71525 started daemon>}
2023-12-09 03:30:22,497 - startup.py[line:855] - WARNING: Sending SIGKILL to <Process name='controller (71577)' pid=71577 parent=71525 started daemon>
2023-12-09 03:30:22,498 - startup.py[line:855] - WARNING: Sending SIGKILL to <Process name='openai_api (71602)' pid=71602 parent=71525 started daemon>
2023-12-09 03:30:22,498 - startup.py[line:855] - WARNING: Sending SIGKILL to <Process name='API Server (71738)' pid=71738 parent=71525 started daemon>
2023-12-09 03:30:22,498 - startup.py[line:855] - WARNING: Sending SIGKILL to <Process name='WEBUI Server (71803)' pid=71803 parent=71525 started daemon>
2023-12-09 03:30:22,498 - startup.py[line:866] - INFO: Process status: {}
2023-12-09 03:30:22,498 - startup.py[line:866] - INFO: Process status: {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (71603)' pid=71603 parent=71525 started daemon>}
2023-12-09 03:30:22,498 - startup.py[line:866] - INFO: Process status: <Process name='controller (71577)' pid=71577 parent=71525 started daemon>
2023-12-09 03:30:22,498 - startup.py[line:866] - INFO: Process status: <Process name='openai_api (71602)' pid=71602 parent=71525 started daemon>
2023-12-09 03:30:22,498 - startup.py[line:866] - INFO: Process status: <Process name='API Server (71738)' pid=71738 parent=71525 started daemon>
2023-12-09 03:30:22,499 - startup.py[line:866] - INFO: Process status: <Process name='WEBUI Server (71803)' pid=71803 parent=71525 started daemon>
Traceback (most recent call last):
  File "/root/Langchain-Chatchat-0.28/startup.py", line 880, in <module>
    loop.run_until_complete(start_main_server())
  File "/root/anaconda3/envs/chatchat/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/root/anaconda3/envs/chatchat/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/root/anaconda3/envs/chatchat/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/root/anaconda3/envs/chatchat/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/Langchain-Chatchat-0.28/startup.py", line 778, in start_main_server
    cmd = queue.get() # 收到切换模型的消息
  File "<string>", line 2, in get
  File "/root/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/root/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/root/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/root/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/root/Langchain-Chatchat-0.28/startup.py", line 608, in f
    raise KeyboardInterrupt(f"{signalname} received")
KeyboardInterrupt: SIGINT received

(chatchat) root@i-B37F1F75:~/Langchain-Chatchat-0.28# /root/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
^C

**Comment by zRzRzRzRzRzRzR** [comment]
试试127.0.0.1
`ERROR: peer closed connection without sending complete message body (incomplete chunked read)`大概率是模型没有传回来东西或者api出问题

**Comment by dancruiser** [comment]
多谢大佬。查了问题出在使用的 vGPU的 license 不对。配置了正确的 license 后，解决了这个问题。
