### ISSUE TITLE
[BUG]启动时不定期出现FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\***\\AppData\\Local\\Temp\\chatchat'

### ISSUE THREAD

**Issue by MolianWH** [chatchat-space/Langchain-Chatchat#2344]
**描述：**每次启动时，有时会报错找不到文件，有时不会报，一旦报错就无法启动成功。

**报错完整日志：**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\envs\chatchat\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\anaconda3\envs\chatchat\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\anaconda3\envs\chatchat\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\anaconda3\envs\chatchat\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\anaconda3\envs\chatchat\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\anaconda3\envs\chatchat\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\anaconda3\envs\chatchat\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Documents\Code\Chat\Langchain-Chatchat\startup.py", line 21, in <module>
    from configs import (
  File "D:\Documents\Code\Chat\Langchain-Chatchat\configs\__init__.py", line 1, in <module>
    from .basic_config import *
  File "D:\Documents\Code\Chat\Langchain-Chatchat\configs\basic_config.py", line 29, in <module>
    shutil.rmtree(BASE_TEMP_DIR)
  File "D:\anaconda3\envs\chatchat\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\anaconda3\envs\chatchat\lib\shutil.py", line 624, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "D:\anaconda3\envs\chatchat\lib\shutil.py", line 622, in _rmtree_unsafe
    os.rmdir(path)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\***\\AppData\\Local\\Temp\\chatchat'
```

**修改建议：**
[basic_config.py.example#L27](https://github.com/chatchat-space/Langchain-Chatchat/blob/fdd6eb5f6dea00ee0ada02f6a9d1a810c66645c8/configs/basic_config.py.example#L27)
```python
if os.path.isdir(BASE_TEMP_DIR) and os.path.exists(BASE_TEMP_DIR):
    shutil.rmtree(BASE_TEMP_DIR)
```

**疑问：**
判断文件是否存在后再删除，偶尔还是会出现FileNotFoundError: [WinError 2] 系统找不到指定的文件。只是频率低了。

**Comment by zRzRzRzRzRzRzR** [comment]
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/93239683/956860fa-957d-4263-98f1-58b14faccbf6)
这个是用做文件对话的，我们看一下windows的情况，可能接下来用一下相对路径放在项目里

**Comment by MolianWH** [comment]
这个路径是确实存在的，只是时而启动报错，时而启动不报错。似乎不止一个线程/代码对这一路径做删除/创建工作。

**Comment by adong2000** [comment]
怎么解决没人有办法么
