### ISSUE TITLE
[BUG] 使用知识库问答报错

### ISSUE THREAD

**Issue by xiaobai1026** [chatchat-space/Langchain-Chatchat#2345]
模型问答正常 但是使用知识库问答报错这个 这个是什么原因？
2023-12-11 13:29:02,359 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /root/bge-large-zh
2023-12-11 13:29:02,926 - embeddings_api.py[line:39] - ERROR: Error while deserializing header: HeaderTooLarge
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 75, in knowledge_base_chat_iterator
    docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 37, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 181, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 64, in do_search
    embeddings = embed_func.embed_query(query)
  File "/root/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 403, in embed_query
    query_embed = embeddings[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by xiaobai1026** [comment]
使用的版本为v0.2.8,模型使用的chatglm3

**Comment by xiaobai1026** [comment]
你试试把embedding模型换成m3e-base，我是换成这个就正常了 用默认bge-large-zh会有问题

**Comment by xiaobai1026** [comment]
> ![55](https://private-user-images.githubusercontent.com/129894765/289885580-cbe0e8cd-66c5-4762-a52f-10302f3adb41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQ0NDcsIm5iZiI6MTcwMjQzNDE0NywicGF0aCI6Ii8xMjk4OTQ3NjUvMjg5ODg1NTgwLWNiZTBlOGNkLTY2YzUtNDc2Mi1hNTJmLTEwMzAyZjNhZGI0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmJlNWFmNjZhMmJhYWEwNzViZjRmMTgxZGVmNzA2MjkyN2YzNzQ0NWExOTZhMjgwZjNjMzVkMDgwNGYxYjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JPy_tUgLkcXID-lOPDGc69draU2hRAef_MctQwLq49g) ![11](https://private-user-images.githubusercontent.com/129894765/289885674-f513ba0b-6cb1-436f-b233-767fbad37690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQ0NDcsIm5iZiI6MTcwMjQzNDE0NywicGF0aCI6Ii8xMjk4OTQ3NjUvMjg5ODg1Njc0LWY1MTNiYTBiLTZjYjEtNDM2Zi1iMjMzLTc2N2ZiYWQzNzY5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzJmZjkyZjkxNGNjYzM5YTQ5NjkxNzhhN2JiMGRiMTgyNjQ2ZGViNDc5OGYyNzlmODM5ZGFiYjFmYTA3NDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fbrScBmIsxtxzaLDwZxzhd1CVAMxvruJfEul61ocx8k) ![22](https://private-user-images.githubusercontent.com/129894765/289885706-0162fca7-8649-48bf-9d84-339f4f4b7ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQ0NDcsIm5iZiI6MTcwMjQzNDE0NywicGF0aCI6Ii8xMjk4OTQ3NjUvMjg5ODg1NzA2LTAxNjJmY2E3LTg2NDktNDhiZi05ZDg0LTMzOWY0ZjRiN2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTc4OTIzMTgwN2IyYTQ5ZGZkZTE5YmZhMTNlYzQxOTE0Mzc0MGQ3NGYzYWNkMWI2ZDVmNmM4M2JjY2VmYzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.joQVPS1K0UkwbqM9GwEOufQrLz-f8HqiMsh-LdSUJRg) ![33](https://private-user-images.githubusercontent.com/129894765/289885729-816e06dc-46f7-410f-8074-b29fc2953fec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQ0NDcsIm5iZiI6MTcwMjQzNDE0NywicGF0aCI6Ii8xMjk4OTQ3NjUvMjg5ODg1NzI5LTgxNmUwNmRjLTQ2ZjctNDEwZi04MDc0LWIyOWZjMjk1M2ZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWIzYTczZTg3YjE1ZTk2ZDg2YjZiYTYyOWUwMzYyMzUyZTUyYjZhYTk5NGMwM2JkMWUwNWI2NmQxZDY0YWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1oAMsfytrlc6jnBs5XlBvAyjYkvdDf3lDdzie_r4dC4) ![44](https://private-user-images.githubusercontent.com/129894765/289885772-42bf4afb-64a4-489e-8839-b88581f2fadb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQ0NDcsIm5iZiI6MTcwMjQzNDE0NywicGF0aCI6Ii8xMjk4OTQ3NjUvMjg5ODg1NzcyLTQyYmY0YWZiLTY0YTQtNDg5ZS04ODM5LWI4ODU4MWYyZmFkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODdlMmJkNDFlMTE5ZjY3MmRkYTBmODg2MmRmMThkZjkwM2Q1YjE0OWI2MTdjMzk4NmZkZTQxOTY3NDBkZWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sciiRfyO5FM0DTv9v_ERITrtlTK-AfCyhf30ssX0HAY) ![55IP](https://private-user-images.githubusercontent.com/129894765/289885780-6bf076e8-ec9b-4cb0-9e0d-12dfc04f6782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQ0NDcsIm5iZiI6MTcwMjQzNDE0NywicGF0aCI6Ii8xMjk4OTQ3NjUvMjg5ODg1NzgwLTZiZjA3NmU4LWVjOWItNGNiMC05ZTBkLTEyZGZjMDRmNjc4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjgwOTE4ZGExNmRiMjE1ODQ0ZjM2NTk5MGNiODE1YWMzYmJiNjMxZmU5MmJiNTJmOTJkMDUzMzQ4NmQ2NjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8SVTaOxtCL8FIqX4sRQxSYSizMeXkFRMyqELgY-aB4w)同样的问题，对话没问题，知识库问答和上传不了文件，求解


你试试把embedding模型换成m3e-base，我是换成这个就正常了 用默认bge-large-zh会有问题

**Comment by danny-zhu** [comment]
检查一下model_config中配置的EMBEDDING_MODEL路径是否正确；另外检查一下嵌入模型的文件是否有缺失，我自己也遇到同样的报错，发现是自己不小心把m3e-base的模型文件中的1_Pooling目录拷贝的时候漏掉导致的。
