### ISSUE TITLE
[BUG]文件问答报错

### ISSUE THREAD

**Issue by JHGo123** [chatchat-space/Langchain-Chatchat#2346]
**问题描述 / Problem Description**
文件问答模式，上传ppt后，第一次提问无法回答，同样的问题再次提问才能回答，等待不超过2分钟后就报服务断开
报下列错误：
Batches: 100%|██████████| 1/1 [00:00<00:00, 30.24it/s]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/Langchain-Chatchat/server/chat/file_chat.py", line 138, in knowledge_base_chat_iterator
    input_msg = History(role="user", content=prompt_template).to_msg_template(False)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for History
content

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.8
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：openai
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-base-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- Python 版本 / Python version:3.10.12

**Comment by JHGo123** [comment]
webui报错信息；
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by Ikaros-521** [comment]
相同问题 插眼

**Comment by liunux4odoo** [comment]
把 prompt_config.py 中 knowledge_base_chat 下面的 "empty" 改成 "Empty"试试

**Comment by Ikaros-521** [comment]
> 先把 prompt_config.py 中 knowledge_base_chat 下面的 "empty" 改成 "Empty"试试。 后面会统一为“empty"，请注意更新。

亲测有用
