### ISSUE TITLE
ERROR: KeyError: Caught exception: 'choices'

### ISSUE THREAD

**Issue by maxusheng123** [chatchat-space/Langchain-Chatchat#2351]
Traceback (most recent call last):
  File "/root/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/root/miniconda3/envs/prompt/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 477, in _astream
    if len(chunk["choices"]) == 0:
KeyError: 'choices'
2023-12-11 18:02:34,469 - utils.py[line:27] - ERROR: KeyError: Caught exception: 'choices'

**Comment by Lijia0** [comment]
应该是qwen-api报错，可以打断点看看具体报的是啥错

**Comment by pengyixuan** [comment]
调用zhipu-api报同一个错，有解决办法么？

**Comment by pengyixuan** [comment]
> 调用zhipu-api报同一个错，有解决办法么？

刚看了一下zhipuai.py，发现没有安装zhipuai，安装一下，再启动就好了。你检查一下qwen.py，看是不是要安装和处理一下dashscope

**Comment by a136214808** [comment]
你或许可以删一下log里面的日志文件(反正我是这样解决的)
