### ISSUE TITLE
API chat/chat报错

### ISSUE THREAD

**Issue by strLights** [chatchat-space/Langchain-Chatchat#2363]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
项目运行起来之后，使用chat/chat接口报错
**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py -a' 
2. 点击 '7861端口，chat/chat请求'
3. 后台报错

**预期的结果 / Expected Result**
swagger上的请求能正常返回

**实际结果 / Actual Result**
报错，
页面上：net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
后台：ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/tutorial-env/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/data/Ly/chatchat/new-version/Langchain-Chatchat/server/chat/chat.py", line 99, in chat_iterator
    {"text": answer, "message_id": message_id},
UnboundLocalError: local variable 'message_id' referenced before assignment

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.8
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）： moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: miniconda
- Python 版本 / Python version: 3.10.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
0.2.8版本里需要传一个conversation_id参数，下个版本会修复这个问题。

**Comment by zhanghaotian123** [comment]
请问修复后的版本更新了吗~

**Comment by mountain1275** [comment]
除了楼上po出来的错误，我的还跟着其他error
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/workspace/Langchain-Chatchat-master/server/chat/chat.py", line 99, in chat_iterator
    {"text": answer, "message_id": message_id},
UnboundLocalError: local variable 'message_id' referenced before assignment
2023-12-20 03:46:48,482 - utils.py[line:24] - ERROR: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> <html><head> <meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8"> <title>ERROR: The requested URL could not be retrieved</title> <style type="text/css"><!--   %l  body :lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; } :lang(he) { direction: rtl; }  --></style> </head><body id=ERR_CONNECT_FAIL> <div id="titles"> <h1>ERROR</h1> <h2>The requested URL could not be retrieved</h2> </div> <hr>  <div id="content"> <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:20000/v1/chat/completions">http://127.0.0.1:20000/v1/chat/completions</a></p>  <blockquote id="error"> <p><b>Connection to 127.0.0.1 failed.</b></p> </blockquote>  <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>  <p>The remote host or network may be down. Please try the request again.</p>  <p>Your cache administrator is <a href="mailto:webmaster">webmaster</a>.</p>  <br> </div>  <hr> <div id="footer"> <p>Generated Wed, 20 Dec 2023 03:46:48 GMT by localhost (squid/2.7.STABLE9)</p> <!-- ERR_CONNECT_FAIL --> </div> </body></html>
Traceback (most recent call last):
  File "/workspace/Langchain-Chatchat-master/server/utils.py", line 22, in wrap_done
    await fn
  File "/opt/conda/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/opt/conda/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/opt/conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/opt/conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/opt/conda/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/opt/conda/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/opt/conda/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/opt/conda/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 101, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1199, in create
    return await self._post(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1306, in request
    return await self._request(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1344, in _request
    return await self._retry_request(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1414, in _retry_request
    return await self._request(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1344, in _request
    return await self._retry_request(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1414, in _retry_request
    return await self._request(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1358, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> <html><head> <meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8"> <title>ERROR: The requested URL could not be retrieved</title> <style type="text/css"><!--   %l  body :lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; } :lang(he) { direction: rtl; }  --></style> </head><body id=ERR_CONNECT_FAIL> <div id="titles"> <h1>ERROR</h1> <h2>The requested URL could not be retrieved</h2> </div> <hr>  <div id="content"> <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:20000/v1/chat/completions">http://127.0.0.1:20000/v1/chat/completions</a></p>  <blockquote id="error"> <p><b>Connection to 127.0.0.1 failed.</b></p> </blockquote>  <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>  <p>The remote host or network may be down. Please try the request again.</p>  <p>Your cache administrator is <a href="mailto:webmaster">webmaster</a>.</p>  <br> </div>  <hr> <div id="footer"> <p>Generated Wed, 20 Dec 2023 03:46:48 GMT by localhost (squid/2.7.STABLE9)</p> <!-- ERR_CONNECT_FAIL --> </div> </body></html>
2023-12-20 03:46:48,484 - utils.py[line:27] - ERROR: InternalServerError: Caught exception: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> <html><head> <meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8"> <title>ERROR: The requested URL could not be retrieved</title> <style type="text/css"><!--   %l  body :lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; } :lang(he) { direction: rtl; }  --></style> </head><body id=ERR_CONNECT_FAIL> <div id="titles"> <h1>ERROR</h1> <h2>The requested URL could not be retrieved</h2> </div> <hr>  <div id="content"> <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:20000/v1/chat/completions">http://127.0.0.1:20000/v1/chat/completions</a></p>  <blockquote id="error"> <p><b>Connection to 127.0.0.1 failed.</b></p> </blockquote>  <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>  <p>The remote host or network may be down. Please try the request again.</p>  <p>Your cache administrator is <a href="mailto:webmaster">webmaster</a>.</p>  <br> </div>  <hr> <div id="footer"> <p>Generated Wed, 20 Dec 2023 03:46:48 GMT by localhost (squid/2.7.STABLE9)</p> <!-- ERR_CONNECT_FAIL --> </div> </body></html>
```
基本配置是相似的
```
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-46-generic-x86_64-with-glibc2.31.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.34
```

**Comment by dijkstra-mose** [comment]
chat.py里把21行：
               conversation_id: str = Body("", description="对话框ID"),
改为：
               conversation_id: str = Body(" ", description="对话框ID"),
原因在于下面43行：
    if conversation_id: 
python 把 None 和 ‘’ 都作为布尔False来处理。

或者在调用api时指定参数conversation_id=‘1’ ，指定任意一个值不能为空。

**Comment by YangFW** [comment]
> 除了楼上po出来的错误，我的还跟着其他error
> 
> ```
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
>     return await self.app(scope, receive, send)
>   File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
>     await super().__call__(scope, receive, send)
>   File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
>     raise exc
>   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
>     raise exc
>   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
>     raise e
>   File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
>     await self.app(scope, receive, send)
>   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
>     await route.handle(scope, receive, send)
>   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
>     await self.app(scope, receive, send)
>   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
>     await response(scope, receive, send)
>   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
>     async with anyio.create_task_group() as task_group:
>   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
>     raise exceptions[0]
>   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
>     await func()
>   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
>     async for chunk in self.body_iterator:
>   File "/workspace/Langchain-Chatchat-master/server/chat/chat.py", line 99, in chat_iterator
>     {"text": answer, "message_id": message_id},
> UnboundLocalError: local variable 'message_id' referenced before assignment
> 2023-12-20 03:46:48,482 - utils.py[line:24] - ERROR: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> <html><head> <meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8"> <title>ERROR: The requested URL could not be retrieved</title> <style type="text/css"></style> </head><body id=ERR_CONNECT_FAIL> <div id="titles"> <h1>ERROR</h1> <h2>The requested URL could not be retrieved</h2> </div> <hr>  <div id="content"> <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:20000/v1/chat/completions">http://127.0.0.1:20000/v1/chat/completions</a></p>  <blockquote id="error"> <p><b>Connection to 127.0.0.1 failed.</b></p> </blockquote>  <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>  <p>The remote host or network may be down. Please try the request again.</p>  <p>Your cache administrator is <a href="mailto:webmaster">webmaster</a>.</p>  <br> </div>  <hr> <div id="footer"> <p>Generated Wed, 20 Dec 2023 03:46:48 GMT by localhost (squid/2.7.STABLE9)</p>  </div> </body></html>
> Traceback (most recent call last):
>   File "/workspace/Langchain-Chatchat-master/server/utils.py", line 22, in wrap_done
>     await fn
>   File "/opt/conda/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
>     raise e
>   File "/opt/conda/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
>     await self._acall(inputs, run_manager=run_manager)
>   File "/opt/conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
>     response = await self.agenerate([inputs], run_manager=run_manager)
>   File "/opt/conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
>     return await self.llm.agenerate_prompt(
>   File "/opt/conda/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
>     return await self.agenerate(
>   File "/opt/conda/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
>     raise exceptions[0]
>   File "/opt/conda/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
>     return await self._agenerate(
>   File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
>     return await agenerate_from_stream(stream_iter)
>   File "/opt/conda/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
>     async for chunk in stream:
>   File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 472, in _astream
>     async for chunk in await acompletion_with_retry(
>   File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 101, in acompletion_with_retry
>     return await llm.async_client.create(**kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1199, in create
>     return await self._post(
>   File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in post
>     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
>   File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1306, in request
>     return await self._request(
>   File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1344, in _request
>     return await self._retry_request(
>   File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1414, in _retry_request
>     return await self._request(
>   File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1344, in _request
>     return await self._retry_request(
>   File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1414, in _retry_request
>     return await self._request(
>   File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1358, in _request
>     raise self._make_status_error_from_response(err.response) from None
> openai.InternalServerError: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> <html><head> <meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8"> <title>ERROR: The requested URL could not be retrieved</title> <style type="text/css"></style> </head><body id=ERR_CONNECT_FAIL> <div id="titles"> <h1>ERROR</h1> <h2>The requested URL could not be retrieved</h2> </div> <hr>  <div id="content"> <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:20000/v1/chat/completions">http://127.0.0.1:20000/v1/chat/completions</a></p>  <blockquote id="error"> <p><b>Connection to 127.0.0.1 failed.</b></p> </blockquote>  <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>  <p>The remote host or network may be down. Please try the request again.</p>  <p>Your cache administrator is <a href="mailto:webmaster">webmaster</a>.</p>  <br> </div>  <hr> <div id="footer"> <p>Generated Wed, 20 Dec 2023 03:46:48 GMT by localhost (squid/2.7.STABLE9)</p>  </div> </body></html>
> 2023-12-20 03:46:48,484 - utils.py[line:27] - ERROR: InternalServerError: Caught exception: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> <html><head> <meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8"> <title>ERROR: The requested URL could not be retrieved</title> <style type="text/css"></style> </head><body id=ERR_CONNECT_FAIL> <div id="titles"> <h1>ERROR</h1> <h2>The requested URL could not be retrieved</h2> </div> <hr>  <div id="content"> <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:20000/v1/chat/completions">http://127.0.0.1:20000/v1/chat/completions</a></p>  <blockquote id="error"> <p><b>Connection to 127.0.0.1 failed.</b></p> </blockquote>  <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>  <p>The remote host or network may be down. Please try the request again.</p>  <p>Your cache administrator is <a href="mailto:webmaster">webmaster</a>.</p>  <br> </div>  <hr> <div id="footer"> <p>Generated Wed, 20 Dec 2023 03:46:48 GMT by localhost (squid/2.7.STABLE9)</p>  </div> </body></html>
> ```
> 
> 基本配置是相似的
> 
> ```
> ==============================Langchain-Chatchat Configuration==============================
> 操作系统：Linux-5.15.0-46-generic-x86_64-with-glibc2.31.
> python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
> 项目版本：v0.2.8
> langchain版本：0.0.344. fastchat版本：0.2.34
> ```

请问你的这个问题解决了吗 ，await fn 这个问题，我现在是在调用/chat/chat请求时，如果history里带有内容会报这个错，如果没有内容是正常成功的
