### ISSUE TITLE
切换模型，知识库时出现RuntimeError: error checking inheritance of typing.Any (type: _SpecialForm)错误

### ISSUE THREAD

**Issue by xldistance** [chatchat-space/Langchain-Chatchat#2389]
pydantic版本是1.10.13，这是streamlit的问题吗,出现频率比较高，刷新网页也不行只能重启模型

```
2023-12-16 09:28:47.937 Uncaught app exception
Traceback (most recent call last):
  File "pydantic\validators.py", line 751, in pydantic.validators.find_validators
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Langchain-Chatchat\glut\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\Langchain-Chatchat\webui.py", line 2, in <module>
    from webui_pages.utils import *
  File "E:\Langchain-Chatchat\webui_pages\utils.py", line 27, in <module>
    from server.utils import set_httpx_config, api_address, get_httpx_client
  File "E:\Langchain-Chatchat\server\utils.py", line 88, in <module>
    class BaseResponse(BaseModel):
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic\validators.py", line 760, in find_validators
RuntimeError: error checking inheritance of typing.Any (type: _SpecialForm)
```

**Comment by zRzRzRzRzRzRzR** [comment]
没有出现这类问题，应该不是框架问题
