### ISSUE TITLE
[BUG] 混用langchain的tool和自定义tool时，tests/agent/test_agent_function.py会报错 

### ISSUE THREAD

**Issue by shishi11** [chatchat-space/Langchain-Chatchat#2400]
**问题描述 / Problem Description**
混用langchain的tool和自定义tool时，tests/agent/test_agent_function.py会报错 ，说langchain的tool不是Tool

**复现问题的步骤 / Steps to Reproduce**
1. 在server/agent/tools_select.py中增加
 Tool.from_function(
        func=search_youtube,
        name="search_youtube",
        description="use this tools to search youtube videos",
        args_schema=YoutubeInput,
    ),
    HumanInputRun(input_func=get_input),#-------》增加的tool  from langchain.tools.human import HumanInputRun
]
2. 运行tests/agent/test_agent_function.py
3. 问题出现 / Problem occurs
Traceback (most recent call last):
  File "E:\Langchain-Chatchat\tests\agent\test_agent_function.py", line 25, in <module>
    prompt=CustomPromptTemplate(
  File "E:\Programs\Python\Python38\Lib\site-packages\langchain_core\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CustomPromptTemplate
tools -> 8
  __init__() missing 1 required positional argument: 'func' (type=type_error)

**预期的结果 / Expected Result**
自定义的tool可以与langchain的tool混合使用

**附加信息 / Additional Information**
通过修改server/agent/custom_template.py可以正常使用
from langchain_core.tools import BaseTool

from configs import SUPPORT_AGENT_MODEL
from server.agent import model_container
class CustomPromptTemplate(StringPromptTemplate):
    template: str
    tools: List[BaseTool]#-------》原来是Tool
**最终结果
测试可以使用自定义Tool与langchain的stand tool混合使用
部分结果如下：
    text_answer = agent_executor.run("我的朋友有几个？")
'''
> Entering new AgentExecutor chain...

> Entering new LLMChain chain...
Prompt after formatting:

Answer the following questions as best you can. If it is in order, you can use some tools appropriately.You have access to the following tools:

calculate: Useful for when you need to answer questions about simple calculations
arxiv: A wrapper around Arxiv.org for searching and retrieving scientific articles in various fields.
weather_check: 
shell: Use Shell to execute Linux commands
search_knowledgebase_complex: Use Use this tool to search local knowledgebase and get information
search_internet: Use this tool to use bing search engine to search the internet
Wolfram: Useful for when you need to calculate difficult formulas
search_youtube: use this tools to search youtube videos
human: You can ask a human for guidance when you think you got stuck or you are not sure what to do next. The input should be a question for the human.

Please note that the "知识库查询工具" is information about the "西交利物浦大学" ,and if a question is asked about it, you must answer with the knowledge base，
Please note that the "天气查询工具" can only be used once since Question begin.

Use the following format:
Question: the input question you must answer1
Thought: you should always think about what to do and what tools to use.
Action: the action to take, should be one of [calculate, arxiv, weather_check, shell, search_knowledgebase_complex, search_internet, Wolfram, search_youtube, human]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question
Begin!

history: 

Question: 我的朋友有几个？

Thought: 

2023-12-18 11:03:22,335 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"

> Finished chain.
这个问题是关于你的朋友的数量，所以我们需要从你的社交媒体账户或者联系人列表中获取这个信息。

Action: human

Action Input: "你能告诉我你有多少个朋友吗？"

你能告诉我你有多少个朋友吗？
Insert your text. Enter 'q' or press Ctrl-D (or Ctrl-Z on Windows) to end.
小李，小王，小林都是我的朋友
q

Observation:小李，小王，小林都是我的朋友

> Entering new LLMChain chain...
Prompt after formatting:

Answer the following questions as best you can. If it is in order, you can use some tools appropriately.You have access to the following tools:

calculate: Useful for when you need to answer questions about simple calculations
arxiv: A wrapper around Arxiv.org for searching and retrieving scientific articles in various fields.
weather_check: 
shell: Use Shell to execute Linux commands
search_knowledgebase_complex: Use Use this tool to search local knowledgebase and get information
search_internet: Use this tool to use bing search engine to search the internet
Wolfram: Useful for when you need to calculate difficult formulas
search_youtube: use this tools to search youtube videos
human: You can ask a human for guidance when you think you got stuck or you are not sure what to do next. The input should be a question for the human.

Please note that the "知识库查询工具" is information about the "西交利物浦大学" ,and if a question is asked about it, you must answer with the knowledge base，
Please note that the "天气查询工具" can only be used once since Question begin.

Use the following format:
Question: the input question you must answer1
Thought: you should always think about what to do and what tools to use.
Action: the action to take, should be one of [calculate, arxiv, weather_check, shell, search_knowledgebase_complex, search_internet, Wolfram, search_youtube, human]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question
Begin!

history: 

Question: 我的朋友有几个？

Thought: 这个问题是关于你的朋友的数量，所以我们需要从你的社交媒体账户或者联系人列表中获取这个信息。

Action: human

Action Input: "你能告诉我你有多少个朋友吗？"

-------------------->这里输入------->小李，小王，小林都是我的朋友
Observation: 小李，小王，小林都是我的朋友
Thought: 

2023-12-18 11:04:14,263 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"

> Finished chain.
看来你的朋友数量是3个。

Final Answer: 3

> Finished chain.

Process finished with exit code 0
'''

**Comment by zRzRzRzRzRzRzR** [comment]
是可以正常使用的，你新建一个文件写自己的工具然后注册就行，wiki有明确的写法
