### ISSUE TITLE
[BUG] 折腾一周了，这个错误始终无法消除，模型事ChatGLM3-6b-32k 环境配置都没有问题，模型正常加载，然后报错

### ISSUE THREAD

**Issue by hopeforus** [chatchat-space/Langchain-Chatchat#2409]
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b-32k'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/hope/work/models/chatglm3-6b-32k',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:7002
==============================Langchain-Chatchat Configuration==============================

Traceback (most recent call last):
  File "/home/hope/.local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by CaffeineOddity** [comment]
看起来是pb版本有问题。

**Comment by hopeforus** [comment]
> protobuf
的版本吗？

**Comment by hopeforus** [comment]
> 看起来是pb版本有问题。
libprotoc 3.14.0

**Comment by CaffeineOddity** [comment]
protobuf                      4.25.1

**Comment by hopeforus** [comment]
> protobuf 4.25.1

好 我安装一下
