### ISSUE TITLE
[BUG]第一次提问显示API通信错误，第二次提问显示DuplicateWidgetID: There are multiple widgets with the same key=''. 通信错误

### ISSUE THREAD

**Issue by DOVEEEEEEEEEEEEE** [chatchat-space/Langchain-Chatchat#2422]
使用的是微调后的ChatGLM2-6B 按照wiki步骤实现部署
已更新到0.2.8
第一次提问显示api通信错误 第二次提问也提示api错误，还报错DuplicateWidgetID: There are multiple widgets with the same key=''. 
```
2023-12-20 14:35:52,788 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53216 - "POST /llm_model/list_running_models HTTP/1.1" 200                                                        OK
2023-12-20 14:35:52,792 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-20 14:35:52,920 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53216 - "POST /llm_model/list_running_models HTTP/1.1" 200                                                        OK
2023-12-20 14:35:52,923 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53216 - "POST /llm_model/list_config_models HTTP/1.1" 200 O                                                       K
2023-12-20 14:35:52,938 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-12-20 14:35:59 | INFO | model_worker | Send heart beat. Models: ['zhipu-ap                                                       i']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 980f34                                                       09.
2023-12-20 14:36:19 | INFO | model_worker | Send heart beat. Models: ['chatglm2                                                       -6b']. Semaphore: None. call_ct: 0. worker_id: 02d149c8.
2023-12-20 14:36:31,099 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:40788 - "POST /llm_model/list_running_models HTTP/1.1" 200                                                        OK
2023-12-20 14:36:31,102 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-20 14:36:31,228 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:40788 - "POST /llm_model/list_running_models HTTP/1.1" 200                                                        OK
2023-12-20 14:36:31,231 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:40788 - "POST /llm_model/list_config_models HTTP/1.1" 200 O                                                       K
2023-12-20 14:36:31,244 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-12-20 14:36:44 | INFO | model_worker | Send heart beat. Models: ['zhipu-ap                                                       i']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 980f34                                                       09.
2023-12-20 14:37:04 | INFO | model_worker | Send heart beat. Models: ['chatglm2                                                       -6b']. Semaphore: None. call_ct: 0. worker_id: 02d149c8.
2023-12-20 14:37:17,834 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49086 - "POST /llm_model/list_running_models HTTP/1.1" 200                                                        OK
2023-12-20 14:37:17,838 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-20 14:37:17,862 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49086 - "POST /llm_model/list_running_models HTTP/1.1" 200                                                        OK
2023-12-20 14:37:17,864 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49086 - "POST /llm_model/list_config_models HTTP/1.1" 200 O                                                       K
2023-12-20 14:37:17,880 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49086 - "POST /chat/chat HTTP/1.1" 200 OK
2023-12-20 14:37:17,911 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/uvicorn/pro                                                       tocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/uvicorn/mid                                                       dleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/fastapi/app                                                       lications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/a                                                       pplications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/m                                                       iddleware/errors.py", line 184, in __call__
    raise exc
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/m                                                       iddleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/m                                                       iddleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/m                                                       iddleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/fastapi/mid                                                       dleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/fastapi/mid                                                       dleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       outing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       outing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       outing.py", line 69, in app
    await response(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       esponses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/anyio/_back                                                       ends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       esponses.py", line 273, in wrap
    await func()
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       esponses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/data/linzj/langchainchatchat2/server/chat/chat.py", line 44, in chat_i                                                       terator
    message_id = add_message_to_db(chat_type="llm_chat", query=query, conversat                                                       ion_id=conversation_id)
  File "/data/linzj/langchainchatchat2/server/db/session.py", line 26, in wrapp                                                       er
    result = f(session, *args, **kwargs)
  File "/data/linzj/langchainchatchat2/server/db/repository/message_repository.                                                       py", line 19, in add_message_to_db
    session.commit()
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 4299, in _flush
    transaction.rollback(_capture_exception=True)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1412, in execute
    return meth(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: mess                                                       age
[SQL: INSERT INTO message (id, conversation_id, chat_type, "query", response, m                                                       eta_data, feedback_score, feedback_reason, create_time) VALUES (?, ?, ?, ?, ?,                                                        ?, ?, ?, CURRENT_TIMESTAMP) RETURNING create_time]
[parameters: ('31bcd99e5ddf4c1ab53e64f7dce86ac8', 'b37f008c74b94b48ae8c41cfbc1a                                                       9201', 'llm_chat', '你好', '', '{}', -1, '')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-12-20 14:37:17,918 - utils.py[line:188] - ERROR: RemoteProtocolError: API                                                       通信遇到错误：peer closed connection without sending complete message body (inc                                                       omplete chunked read)
2023-12-20 14:37:29 | INFO | model_worker | Send heart beat. Models: ['zhipu-ap                                                       i']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 980f34                                                       09.
2023-12-20 14:37:49 | INFO | model_worker | Send heart beat. Models: ['chatglm2                                                       -6b']. Semaphore: None. call_ct: 0. worker_id: 02d149c8.
2023-12-20 14:38:14 | INFO | model_worker | Send heart beat. Models: ['zhipu-ap                                                       i']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 980f34                                                       09.
2023-12-20 14:38:34 | INFO | model_worker | Send heart beat. Models: ['chatglm2                                                       -6b']. Semaphore: None. call_ct: 0. worker_id: 02d149c8.
2023-12-20 14:38:47,390 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:60742 - "POST /llm_model/list_running_models HTTP/1.1" 200                                                        OK
2023-12-20 14:38:47,393 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-20 14:38:47,416 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:60742 - "POST /llm_model/list_running_models HTTP/1.1" 200                                                        OK
2023-12-20 14:38:47,420 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:60742 - "POST /llm_model/list_config_models HTTP/1.1" 200 O                                                       K
2023-12-20 14:38:47,434 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:60742 - "POST /chat/chat HTTP/1.1" 200 OK
2023-12-20 14:38:47,453 - _client.py[line:1013] - INFO: HTTP Request: POST http                                                       ://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/uvicorn/pro                                                       tocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/uvicorn/mid                                                       dleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/fastapi/app                                                       lications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/a                                                       pplications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/m                                                       iddleware/errors.py", line 184, in __call__
    raise exc
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/m                                                       iddleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/m                                                       iddleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/m                                                       iddleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/fastapi/mid                                                       dleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/fastapi/mid                                                       dleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       outing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       outing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       outing.py", line 69, in app
    await response(scope, receive, send)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       esponses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/anyio/_back                                                       ends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       esponses.py", line 273, in wrap
    await func()
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/starlette/r                                                       esponses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/data/linzj/langchainchatchat2/server/chat/chat.py", line 44, in chat_i                                                       terator
    message_id = add_message_to_db(chat_type="llm_chat", query=query, conversat                                                       ion_id=conversation_id)
  File "/data/linzj/langchainchatchat2/server/db/session.py", line 26, in wrapp                                                       er
    result = f(session, *args, **kwargs)
  File "/data/linzj/langchainchatchat2/server/db/repository/message_repository.                                                       py", line 19, in add_message_to_db
    session.commit()
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 4299, in _flush
    transaction.rollback(_capture_exception=True)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1412, in execute
    return meth(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/sqlalchemy/                                                       engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: mess                                                       age
[SQL: INSERT INTO message (id, conversation_id, chat_type, "query", response, m                                                       eta_data, feedback_score, feedback_reason, create_time) VALUES (?, ?, ?, ?, ?,                                                        ?, ?, ?, CURRENT_TIMESTAMP) RETURNING create_time]
[parameters: ('ad591fc183d8408fa7e11dc759ba8e5d', 'b37f008c74b94b48ae8c41cfbc1a                                                       9201', 'llm_chat', '1', '', '{}', -1, '')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-12-20 14:38:47,455 - utils.py[line:188] - ERROR: RemoteProtocolError: API                                                       通信遇到错误：peer closed connection without sending complete message body (inc                                                       omplete chunked read)
2023-12-20 14:38:47.456 Uncaught app exception
Traceback (most recent call last):
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit/r                                                       untime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/data/linzj/langchainchatchat2/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/data/linzj/langchainchatchat2/webui_pages/dialogue/dialogue.py", line                                                        326, in dialogue_page
    chat_box.show_feedback(**feedback_kwargs,
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit_c                                                       hatbox/messages.py", line 309, in show_feedback
    return streamlit_feedback(**kwargs)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit_f                                                       eedback/__init__.py", line 104, in streamlit_feedback
    component_value = _component_func(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit/c                                                       omponents/v1/components.py", line 80, in __call__
    return self.create_instance(*args, default=default, key=key, **kwargs)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit/r                                                       untime/metrics_util.py", line 396, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit/c                                                       omponents/v1/components.py", line 241, in create_instance
    return_value = marshall_component(dg, element)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit/c                                                       omponents/v1/components.py", line 212, in marshall_component
    component_state = register_widget(
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit_o                                                       ption_menu/streamlit_callback.py", line 20, in wrapper_register_widget
    return register_widget(*args, **kwargs)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit/r                                                       untime/state/widgets.py", line 161, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, eleme                                                       nt_type)
  File "/data/linzj/anaconda3/envs/chen/lib/python3.9/site-packages/streamlit/r                                                       untime/state/widgets.py", line 194, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple widgets with the same `k                                                       ey=''`.

To fix this, please make sure that the `key` argument is unique for each
widget you create.
2023-12-20 14:38:59 | INFO | model_worker | Send heart beat. Models: ['zhipu-ap                                                       i']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 980f34                                                       09.
2023-12-20 14:39:19 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: 02d149c8.
2023-12-20 14:39:44 | INFO | model_worker | Send heart beat. Models: ['zhipu-api']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 980f3409.
2023-12-20 14:40:04 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: 02d149c8.
2023-12-20 14:40:30 | INFO | model_worker | Send heart beat. Models: ['zhipu-api']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 980f3409.
2023-12-20 14:40:49 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: 02d149c8.
2023-12-20 14:41:15 | INFO | model_worker | Send heart beat. Models: ['zhipu-api']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 980f3409.
2023-12-20 14:41:34 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b']. Semaphore: None. call_ct: 0. worker_id: 02d149c8.
```
![Uploading 屏幕截图 2023-12-20 144247.png…]()

**Comment by hq221** [comment]
同样的问题。。你解决了吗？

**Comment by STUPIDDDD0** [comment]
同样的问题

**Comment by liunux4odoo** [comment]
执行 python init_database.py --create-tables 或者 完全重建知识库都可以。

**Comment by tommy3266** [comment]
embedding模型位置不对吧

**Comment by kaixuanjames** [comment]
在线跑模型要安装对应的SDK
