### ISSUE TITLE
[BUG] 简洁阐述问题 / 系统运行过程中还会切换python版本吗？ steam后感觉版本变了，langchain 都报错

### ISSUE THREAD

**Issue by hopeforus** [chatchat-space/Langchain-Chatchat#2442]
当前启动的LLM模型：['chatglm3-6b-32k'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/hope/work/models/chatglm3-6b-32k',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:7002
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:7002

2023-12-22 10:48:33.341 Uncaught app exception
Traceback (most recent call last):
  File "/home/hope/.local/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/hope/work/Langchain-Chatchat/webui.py", line 2, in <module>
    from webui_pages.utils import *
  File "/home/hope/work/Langchain-Chatchat/webui_pages/utils.py", line 8, in <module>
    from configs import (
  File "/home/hope/work/Langchain-Chatchat/configs/__init__.py", line 1, in <module>
    from .basic_config import *
  File "/home/hope/work/Langchain-Chatchat/configs/basic_config.py", line 3, in <module>
    import langchain
ModuleNotFoundError: No module named 'langchain'

**Comment by zRzRzRzRzRzRzR** [comment]
按照req和wiki安装对应的python版本
