### ISSUE TITLE
OSError: [Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by hao310810401** [chatchat-space/Langchain-Chatchat#2443]
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

Traceback (most recent call last):
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/streamlit/web/cli.py", line 233, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/streamlit/web/cli.py", line 269, in _main_run
    bootstrap.run(file, command_line, args, flag_options)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/streamlit/web/bootstrap.py", line 411, in run
    _install_pages_watcher(main_script_path)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/streamlit/web/bootstrap.py", line 386, in _install_pages_watcher
    watch_dir(
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/streamlit/watcher/path_watcher.py", line 153, in watch_dir
    return _watch_path(
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/streamlit/watcher/path_watcher.py", line 128, in _watch_path
    watcher_class(
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/streamlit/watcher/event_based_path_watcher.py", line 92, in __init__
    path_watcher.watch_path(
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/streamlit/watcher/event_based_path_watcher.py", line 170, in watch_path
    folder_handler.watch = self._observer.schedule(
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/watchdog/observers/api.py", line 301, in schedule
    emitter.start()
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 92, in start
    self.on_thread_start()
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 179, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 402, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
    Inotify._raise_error()
  File "/home/user/netdisk/data/13b/Langchain-Chatchat-master/myenv/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 428, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
在揽睿平台服务器出现了inotify 监控限制问题，因揽睿平台是容器方式无法修改系统参数，想问问看有什么其他方式可以解决吗？

**Comment by hao310810401** [comment]
已解决，感谢
