### ISSUE TITLE
weather_check.py 运行异常

### ISSUE THREAD

**Issue by HappyWHoo** [chatchat-space/Langchain-Chatchat#2452]
本地调试：
agent_executor.run("广州今晚热吗？")

> Entering new AgentExecutor chain...
2023-12-22 16:59:10,184 - _client.py[line:1013] - INFO: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
This question is asking about the weather in Guangzhou tonight. I can use the weather_check tool to find the answer.

Action: weather_check
Action Input: location = "Guangzhou"

> Entering new LLMWeatherChain chain...
location = "Guangzhou2023-12-22 16:59:12,723 - _client.py[line:1013] - INFO: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
答案: 缺少信息。请提供具体的区域或城市名称。
> Finished chain.

Observation:输入的格式不对: 答案: 缺少信息。请提供具体的区域或城市名称。,应该输入 (市 区)的组合
2023-12-22 16:59:14,532 - _client.py[line:1013] - INFO: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
The input format is incorrect. The tool is asking for a specific district or city name in the format (city district). 

Action: weather_check
Action Input: location = "Guangzhou Tianhe"

> Entering new LLMWeatherChain chain...
location = "Guangzhou Tianhe2023-12-22 16:59:16,964 - _client.py[line:1013] - INFO: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2023-12-22 16:59:16,964 - _base_client.py[line:927] - INFO: Retrying request to /chat/completions in 0.889281 seconds
2023-12-22 16:59:20,141 - _client.py[line:1013] - INFO: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2023-12-22 16:59:20,141 - _base_client.py[line:927] - INFO: Retrying request to /chat/completions in 1.672087 seconds
2023-12-22 16:59:24,081 - _client.py[line:1013] - INFO: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
Traceback (most recent call last):
  File "E:\workspace-ai\quickool-ai\test\test.py", line 59, in <module>
    agent_executor.run("广州今晚热吗？", callbacks=[callback])
  File "E:\installed software\python\Lib\site-packages\langchain\chains\base.py", line 507, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain\chains\base.py", line 312, in __call__
    raise e
  File "E:\installed software\python\Lib\site-packages\langchain\chains\base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "E:\installed software\python\Lib\site-packages\langchain\agents\agent.py", line 1312, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain\agents\agent.py", line 1038, in _take_next_step
    [
  File "E:\installed software\python\Lib\site-packages\langchain\agents\agent.py", line 1038, in <listcomp>
    [
  File "E:\installed software\python\Lib\site-packages\langchain\agents\agent.py", line 1134, in _iter_next_step
    observation = tool.run(
                  ^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain_core\tools.py", line 365, in run
    raise e
  File "E:\installed software\python\Lib\site-packages\langchain_core\tools.py", line 337, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "E:\installed software\python\Lib\site-packages\langchain_core\tools.py", line 516, in _run
    else self.func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\workspace-ai\quickool-ai\tools\weather_check.py", line 329, in weathercheck
    ans = llm_weather.run(query)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain\chains\base.py", line 507, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain\chains\base.py", line 312, in __call__
    raise e
  File "E:\installed software\python\Lib\site-packages\langchain\chains\base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "E:\workspace-ai\quickool-ai\tools\weather_check.py", line 290, in _call
    llm_output = self.llm_chain.predict(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain\chains\llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain\chains\base.py", line 312, in __call__
    raise e
  File "E:\installed software\python\Lib\site-packages\langchain\chains\base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "E:\installed software\python\Lib\site-packages\langchain\chains\llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain\chains\llm.py", line 115, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain_core\language_models\chat_models.py", line 491, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain_core\language_models\chat_models.py", line 378, in generate
    raise e
  File "E:\installed software\python\Lib\site-packages\langchain_core\language_models\chat_models.py", line 368, in generate
    self._generate_with_cache(
  File "E:\installed software\python\Lib\site-packages\langchain_core\language_models\chat_models.py", line 524, in _generate_with_cache
    return self._generate(
           ^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain_community\chat_models\openai.py", line 427, in _generate
    return generate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain_core\language_models\chat_models.py", line 61, in generate_from_stream
    for chunk in stream:
  File "E:\installed software\python\Lib\site-packages\langchain_community\chat_models\openai.py", line 393, in _stream
    for chunk in self.completion_with_retry(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\langchain_community\chat_models\openai.py", line 352, in completion_with_retry
    return self.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\_utils\_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\resources\chat\completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\_base_client.py", line 1063, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\_base_client.py", line 842, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\_base_client.py", line 873, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\_base_client.py", line 933, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\_base_client.py", line 873, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\_base_client.py", line 933, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "E:\installed software\python\Lib\site-packages\openai\_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-3.5-turbo-16k in organization org-W9mgsbGHtueU3XF3QBk0QdVn on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}

Process finished with exit code 1

问题：
1. 请求llm供应商次数过多报错
2. 按理说只提供市也可以识别并运行
3. 已经Finished chain.了，还重新执行chain

**Comment by zhuhaifengaaa** [comment]
我也遇到了你说的问题，三个问题总结的很好。。这个项目的agent感觉非常不好用

**Comment by zRzRzRzRzRzRzR** [comment]
因为这个函数只有GPT4能用
