### ISSUE TITLE
[BUG] 接口调用问题

### ISSUE THREAD

**Issue by luojihaohuawei** [chatchat-space/Langchain-Chatchat#2486]
**问题描述 / Problem Description**
1.没有在model_config.py配置openai-api的api_key是不是调用不了openai接口；

2.调用与llm模型对话（直接与fastchat api）接口出现错误；
命令：
curl -X 'POST' \
  'http://127.0.0.1:7861/chat/fastchat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "model": "chatglm3-6b",
  "messages": [
    {
      "role": "user",
      "content": "hello"
    }
  ],
  "temperature": 0.7,
  "n": 1,
  "max_tokens": 0,
  "stop": [],
  "stream": false,
  "presence_penalty": 0,
  "frequency_penalty": 0
}'
问题：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/151513501/a57b6b8a-9e54-46d1-b89b-b86ce59bcb38)

3.调用与llm模型对话（通过LLMChain）接口出现错误；
命令：
curl -X 'POST' \
  'http://127.0.0.1:7861/chat/chat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "恼羞成怒",
  "conversation_id": "",
  "history_len": -1,
  "history": [
    {
      "role": "user",
      "content": "我们来玩成语接龙，我先来，生龙活虎"
    },
    {
      "role": "assistant",
      "content": "虎头虎脑"
    }
  ],
  "stream": false,
  "model_name": "chatglm3-6b",
  "temperature": 0.7,
  "max_tokens": 0,
  "prompt_name": "default"
}'
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/151513501/df7f7aa6-a38b-4b24-9c99-cd2db438d044)
后台报错内容：
INFO:     127.0.0.1:41352 - "POST /chat/chat HTTP/1.1" 200 OK
2023-12-27 17:04:51 | INFO | stdout | INFO:     127.0.0.1:35208 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-12-27 17:04:51,020 - util.py[line:67] - INFO: message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None request_id=None response_code=200
2023-12-27 17:04:51 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/ma-user/infer/Langchain-Chatchat/server/chat/chat.py", line 99, in chat_iterator
    {"text": answer, "message_id": message_id},
UnboundLocalError: local variable 'message_id' referenced before assignment

补充说明：
能够成功调用与知识库对话的接口
http://127.0.0.1:7861/chat/knowledge_base_chat

**Comment by liunux4odoo** [comment]
你需要传入一个非空的 conversation_id 参数。下个版本会修复这个问题。

**Comment by luojihaohuawei** [comment]
> 你需要传入一个非空的 conversation_id 参数。下个版本会修复这个问题。

您好，感谢回答，这个参数该如何加，这个参数的作用是什么

**Comment by XUshicong** [comment]
你可以将 conversation_id 参数设为1试一下

**Comment by luojihaohuawei** [comment]
> 你可以将 conversation_id 参数设为1试一下

好的，已解决，多谢！
