### ISSUE TITLE
agent对话时调用知识库对话报错

### ISSUE THREAD

**Issue by maxusheng123** [chatchat-space/Langchain-Chatchat#2487]
Traceback (most recent call last):
  File "/root/Langchain_Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/agents/agent.py", line 1361, in _acall
    next_step_output = await self._atake_next_step(
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/agents/agent.py", line 1164, in _atake_next_step
    [
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/agents/agent.py", line 1164, in <listcomp>
    [
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/agents/agent.py", line 1285, in _aiter_next_step
    result = await asyncio.gather(
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/agents/agent.py", line 1263, in _aperform_agent_action
    observation = await tool.arun(
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain_core/tools.py", line 440, in arun
    raise e
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain_core/tools.py", line 412, in arun
    await self._arun(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain_core/tools.py", line 541, in _arun
    return await asyncio.get_running_loop().run_in_executor(
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain_core/tools.py", line 516, in _run
    else self.func(*args, **kwargs)
  File "/root/Langchain_Chatchat/server/agent/tools/search_knowledgebase_complex.py", line 271, in search_knowledgebase_complex
    ans = llm_knowledge.run(query)
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/chains/base.py", line 507, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
  File "/root/miniconda3/envs/xiaoka/lib/python3.10/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/root/Langchain_Chatchat/server/agent/tools/search_knowledgebase_complex.py", line 234, in _call
    return self._process_llm_result(llm_output, _run_manager)
  File "/root/Langchain_Chatchat/server/agent/tools/search_knowledgebase_complex.py", line 172, in _process_llm_result
    queries = [(line.split("，")[0].strip(), line.split("，")[1].strip()) for line in lines]
  File "/root/Langchain_Chatchat/server/agent/tools/search_knowledgebase_complex.py", line 172, in <listcomp>
    queries = [(line.split("，")[0].strip(), line.split("，")[1].strip()) for line in lines]
IndexError: list index out of range
2023-12-27 18:04:52,597 - utils.py[line:27] - ERROR: IndexError: Caught exception: list index out of range

**Comment by maxusheng123** [comment]
原始代码中，截止到报错的这一步，期望的lines的格式是什么样子的？这步的目的是什么？为什么我没有改过这块的代码还会出现这样的问题？

**Comment by maxusheng123** [comment]
> _🤖_
> 
> 你好，@maxusheng123! 🤖 我是[Dosu](https://dosu.dev)，一个机器人助手，能帮助你解决bug，回答问题，甚至成为贡献者。在等待人类维护者的回复时，我会在这里提供帮助。请放心，我会尽力帮助你解决问题。😊
> 
> 您的错误信息显示在 `search_knowledgebase_complex.py` 文件的 `search_knowledgebase_complex` 函数中出现了 "IndexError: list index out of range" 错误。这个错误通常发生在尝试访问列表中不存在的索引时。
> 
> 在您的错误堆栈中，问题出在这一行：
> 
> ```python
> queries = [(line.split("，")[0].strip(), line.split("，")[1].strip()) for line in lines]
> ```
> 
> 这行代码试图将每一行分割成两部分，然后分别去除两部分的前后空格。如果某一行没有包含 "，"，那么 `line.split("，")` 就只会返回一个元素的列表，然后当你试图访问 `line.split("，")[1]` 时，就会出现 "IndexError: list index out of range" 错误。
> 
> 为了解决这个问题，你需要确保每一行都包含 "，"。你可以通过添加一个检查来实现这一点。例如：
> 
> ```python
> queries = [(line.split("，")[0].strip(), line.split("，")[1].strip()) for line in lines if "，" in line]
> ```
> 
> 这段代码只会处理包含 "，" 的行，所以不会出现 "IndexError: list index out of range" 错误。
> 
> 如果你不能确定所有的行都包含 "，"，那么你可能需要修改你的代码，使其能够处理不包含 "，" 的行。例如，你可以使用 `try/except` 来捕获 "IndexError" 错误：
> 
> ```python
> queries = []
> for line in lines:
>     try:
>         part1, part2 = line.split("，")
>         queries.append((part1.strip(), part2.strip()))
>     except IndexError:
>         # Handle the case where line does not contain "，"
> ```
> 
> 这段代码会捕获 "IndexError" 错误，并允许你处理不包含 "，" 的行。
> 
> 希望这个答案能帮到你。如果你还有其他问题，欢迎随时向我提问。
> 
> ## Sources
> * [server/chat/knowledge_base_chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/knowledge_base_chat.py)
> * [server/agent/tools/search_knowledgebase_complex.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools/search_knowledgebase_complex.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

原始代码中，截止到报错的这一步，期望的lines的格式是什么样子的？这步的目的是什么？为什么我没有改过这块的代码还会出现这样的问题？

**Comment by maxusheng123** [comment]
> _🤖_
> 
> `search_knowledgebase_complex`函数的目的是在给定查询的知识库中进行搜索。它使用`LLMKnowledgeChain`类来处理查询并返回答案。
> 
> `lines`变量预期是一个字符串列表，其中每个字符串是包含数据库名称和查询的文本行，用逗号分隔。例如，`["bigdata,大数据专业的男女比例", "robotic,机器人专业的优势"]`。
> 
> "IndexError: list index out of range"错误可能在`queries = [(line.split("，")[0].strip(), line.split("，")[1].strip()) for line in lines]`这行代码上出现，如果`lines`列表中的任何行都不包含逗号。这是因为`split`函数被用来根据逗号将每一行分成两部分，如果没有逗号，`split`函数将返回只有一个元素的列表，当试图访问第二个元素时会引发IndexError。
> 
> 这是由以下代码片段支持的：
> 
> ```python
> # 通过换行符将cleaned_input_str分割来创建lines变量
> lines = cleaned_input_str.split("\n")
> 
> # 通过逗号分割每一行来创建queries变量
> try:
>     queries = [(line.split(",")[0].strip(), line.split(",")[1].strip()) for line in lines]
> except:
>     queries = [(line.split("，")[0].strip(), line.split("，")[1].strip()) for line in lines]
> ```
> 
> 错误处理代码表明，开发人员预见到一些行可能不包含逗号，并试图通过在第一个`split`操作引发异常时分割不同的字符来处理这个问题。然而，如果一行既不包含逗号也不包含替代字符，仍然会引发IndexError。
> 
> `search_knowledgebase_complex`函数期望接收一个单独的字符串作为输入。这个字符串代表要在知识库中搜索的查询。
> 
> 这是相关的代码片段：
> 
> ```python
> def search_knowledgebase_complex(query: str):
>     model = model_container.MODEL
>     llm_knowledge = LLMKnowledgeChain.from_llm(model, verbose=True, prompt=PROMPT)
>     ans = llm_knowledge.run(query)
>     return ans
> ```
> 
> 在代码的上下文中，`query`是用户想要在知识库中搜索的问题或陈述。例如，在主函数中，查询是"机器人和大数据在代码教学上有什么区别"。
> 
> 因此，如果你的输入数据不符合这个格式，那么就可能会出现你所遇到的问题。你需要确保你的输入数据是一个字符串列表，每个字符串都包含一个数据库名称和一个查询，用逗号分隔。如果你的输入数据不符合这个格式，那么`split`函数可能无法正确地将每一行分割成两部分，从而导致IndexError。
> 
> 你可以通过检查你的输入数据来解决这个问题，确保每一行都包含一个逗号，并且在逗号之前和之后都有文本。如果你的输入数据符合这个格式，那么`split`函数应该能够正确地将每一行分割成两部分，从而避免IndexError。
> 
> 希望这个解答能帮助你解决问题。如果你还有其他问题，或者需要更多的信息，请随时向我提问。
> 
> ## Sources
> * [server/agent/tools/search_knowledgebase_complex.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools/search_knowledgebase_complex.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

原生代码可能有细节处理问题，我测试了一下autodl镜像的agent_chat，也是到这步报同样的错误。
