### ISSUE TITLE
[BUG] 项目与es链接出错 

### ISSUE THREAD

**Issue by AOnlineFish** [chatchat-space/Langchain-Chatchat#2496]
**问题描述 / Problem Description**
执行数据库迁移的时候报错 
Traceback (most recent call last):
  File "/home/user/Q/Langchain-Chatchat/init_database.py", line 108, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/user/Q/Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/home/user/Q/Langchain-Chatchat/server/knowledge_base/migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "/home/user/Q/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 129, in add_doc
    self.delete_doc(kb_file)
  File "/home/user/Q/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 143, in delete_doc
    self.do_delete_doc(kb_file, **kwargs)
  File "/home/user/Q/Langchain-Chatchat/server/knowledge_base/kb_service/es_kb_service.py", line 138, in do_delete_doc
    if self.es_client_python.indices.exists(index=self.index_name):
  File "/home/user/miniconda3/envs/mychat_test/lib/python3.10/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/user/miniconda3/envs/mychat_test/lib/python3.10/site-packages/elasticsearch/client/indices.py", line 332, in exists
    return self.transport.perform_request(
  File "/home/user/miniconda3/envs/mychat_test/lib/python3.10/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/home/user/miniconda3/envs/mychat_test/lib/python3.10/site-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/user/miniconda3/envs/mychat_test/lib/python3.10/site-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/user/miniconda3/envs/mychat_test/lib/python3.10/site-packages/elasticsearch/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, '')

执行python init_database.py --recreate-vs
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 es
- 操作系统及版本 / Operating system and version:
- Python 版本：3.10
操作系统：Linux-5.15.0-91-generic-x86_64-with-glibc2.31.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.34
当前使用的分词器：ChineseRecursiveTextSplitter

**Comment by AOnlineFish** [comment]
`    "es": {
        "host": "127.0.0.1",
        "port": "9200",
        "index_name": "my_index",
        "user": "elastic",
        "password": "NT4MaHmZNUANcERq0rjn" # 重置密码的命令： bin/elasticsearch-reset-password -u elastic
    }`
    
这是我的es配置
`# Elasticsearch集群名称
cluster.name: elasticsearch

# 节点名称
node.name: node-1

# 绑定的网络地址，0.0.0.0表示接受所有IP地址的连接
network.host: 0.0.0.0

# Elasticsearch HTTP服务端口
http.port: 9200

# 初始主节点的列表
cluster.initial_master_nodes: ["node-1"]

# 启用安全功能
xpack.security.enabled: true

# 启用SSL/TLS加密的传输层
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: /home/user/Q/es/config/certs/elastic-certificates.p12
xpack.security.transport.ssl.keystore.password: gwPQNk4e8r0SQJc5gKrJ
xpack.security.transport.ssl.truststore.path: /home/user/Q/es/config/certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.password: gwPQNk4e8r0SQJc5gKrJ

# 注释掉与Kibana和HTTP SSL相关的所有配置
# xpack.security.http.ssl.enabled: ...
# xpack.security.http.ssl.keystore.path: ...
# xpack.security.http.ssl.keystore.password: ...
# xpack.security.http.ssl.truststore.path: ...
   `

**Comment by goldSunshine** [comment]
我也遇到过类似的问题，主要还因为鉴权。按照项目中ES部署指南中的步骤是可以成功的，去掉xpack鉴权，版本在8.0以上。

`
docker run -id --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "xpack.security.enabled=false" -e "xpack.security.http.ssl.enabled=false" -t docker.elastic.co/elasticsearch/elasticsearch:8.8.2
`

**Comment by AOnlineFish** [comment]
感谢您的回答，不胜感激
