### ISSUE TITLE
[BUG] mac m1启动后，本地chatGLM6b模型问答报错 utils.py[line:24] - ERROR: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by jeceldx** [chatchat-space/Langchain-Chatchat#2508]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
本地chatGLM6b模型问答报错 utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
**复现问题的步骤 / Steps to Reproduce**
1. 执行 python startup.py -a
2. 输入问答内容
<img width="1695" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/44993781/beebd499-3260-498c-92ff-54244af0d833">
3. 问题出现 ：返回空白内容，后台报错：

```

==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-12.6.2-arm64-arm-64bit.
python版本：3.10.13 (main, Nov  1 2023, 16:33:59) [Clang 14.0.0 (clang-1400.0.29.202)]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.34


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ mps
{'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/Users/daixun/IdeaProjects/ai/models/THUDM_chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ mps
==============================Langchain-Chatchat Configuration==============================


2023-12-29 10:35:25,468 - startup.py[line:650] - INFO: 正在启动服务：
2023-12-29 10:35:25,468 - startup.py[line:651] - INFO: 如需查看 llm_api 日志，请前往 /Users/daixun/IdeaProjects/ai/Langchain-Chatchat/logs
2023-12-29 10:35:26 | INFO | model_worker | Register to controller
2023-12-29 10:35:26 | ERROR | stderr | INFO:     Started server process [9897]
2023-12-29 10:35:26 | ERROR | stderr | INFO:     Waiting for application startup.
2023-12-29 10:35:26 | ERROR | stderr | INFO:     Application startup complete.
2023-12-29 10:35:26 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-12-29 10:35:27 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker b0503d31 ...
Loading checkpoint shards:   0%|                                                                                           | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|███████████▊                                                                       | 1/7 [00:00<00:03,  1.91it/s]
Loading checkpoint shards:  29%|███████████████████████▋                                                           | 2/7 [00:01<00:02,  1.79it/s]
Loading checkpoint shards:  43%|███████████████████████████████████▌                                               | 3/7 [00:01<00:02,  1.79it/s]
Loading checkpoint shards:  57%|███████████████████████████████████████████████▍                                   | 4/7 [00:02<00:01,  1.81it/s]
Loading checkpoint shards:  71%|███████████████████████████████████████████████████████████▎                       | 5/7 [00:03<00:01,  1.30it/s]
Loading checkpoint shards:  86%|███████████████████████████████████████████████████████████████████████▏           | 6/7 [00:04<00:00,  1.02it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.13it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.29it/s]
2023-12-29 10:35:33 | ERROR | stderr | 
2023-12-29 10:35:36 | INFO | model_worker | Register to controller
INFO:     Started server process [9910]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)


==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-12.6.2-arm64-arm-64bit.
python版本：3.10.13 (main, Nov  1 2023, 16:33:59) [Clang 14.0.0 (clang-1400.0.29.202)]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.34


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ mps
{'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/Users/daixun/IdeaProjects/ai/models/THUDM_chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ mps


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================



  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2023-12-29 10:35:40,884 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51503 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-29 10:35:40,886 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-29 10:35:41,000 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51503 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-29 10:35:41,001 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51503 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-29 10:35:41,006 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2023-12-29 10:35:51,007 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51541 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-29 10:35:51,008 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2023-12-29 10:35:51,016 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51541 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-12-29 10:35:51,018 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51541 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-12-29 10:35:51,026 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51541 - "POST /chat/chat HTTP/1.1" 200 OK
2023-12-29 10:35:51,031 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-12-29 10:35:51 | INFO | stdout | INFO:     127.0.0.1:51544 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-12-29 10:35:51,103 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2023-12-29 10:35:51 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
/Users/daixun/.cache/huggingface/modules/transformers_modules/THUDM_chatglm3-6b/modeling_chatglm.py:818: UserWarning: MPS: no support for int64 for all_all_out, downcasting to a smaller data type (int32/float32). Native support for int64 has been added in macOS 13.3. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/ReduceOps.mm:1399.)
  if (attention_mask is not None and not attention_mask.all()) or (past_key_values and seq_length != 1):
2023-12-29 10:35:51,186 - utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/daixun/IdeaProjects/ai/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/opt/homebrew/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/opt/homebrew/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/opt/homebrew/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 477, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2023-12-29 10:35:51,187 - utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
```

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

正常回答

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

无回答内容

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.8
- 是否使用 Docker 部署（是/否）: 否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：: ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等): faiss
- 操作系统及版本 / Operating system and version: macOS 12.6.2
- Python 版本 / Python version: 3.10.13

**Comment by jeceldx** [comment]
按照bot的知道，输出错误如下：
2```
023-12-29 13:33:03,525 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
--------报错信息-------
{'id': 'chatcmpl-3CmkZn39zy4vLNw3BVtinD', 'choices': [{'delta': {'content': None, 'function_call': None, 'role': 'assistant', 'tool_calls': None}, 'finish_reason': None, 'index': 0, 'logprobs': None}], 'created': None, 'model': 'chatglm3-6b', 'object': None, 'system_fingerprint': None}
2023-12-29 13:33:03 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
/Users/daixun/.cache/huggingface/modules/transformers_modules/THUDM_chatglm3-6b/modeling_chatglm.py:818: UserWarning: MPS: no support for int64 for all_all_out, downcasting to a smaller data type (int32/float32). Native support for int64 has been added in macOS 13.3. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/ReduceOps.mm:1399.)
  if (attention_mask is not None and not attention_mask.all()) or (past_key_values and seq_length != 1):
--------报错信息-------
{'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'text': '**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(MPS: power op with int64 input is supported natively starting from macOS 13.2)', 'error_code': 50001}
2023-12-29 13:33:03,641 - utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/daixun/IdeaProjects/ai/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/opt/homebrew/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/opt/homebrew/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/opt/homebrew/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 508, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 479, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()

```

是不是意味着我需要升级系统到13.2？是否有折中的方式，能先调整不使用int64的方法呢？

**Comment by jeceldx** [comment]
升级macOS版本后解决
