### ISSUE TITLE
[BUG] RemoteProtocolError: Caught exception: peer closed connection without sending 

### ISSUE THREAD

**Issue by CyanMystery** [chatchat-space/Langchain-Chatchat#2522]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...' 自定义agent问答都是这样的报错 debug了貌似是await太久了没返回就报这个错了 是我电脑泰辣鸡了吗
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

INFO:     127.0.0.1:60249 - "POST /chat/agent_chat HTTP/1.1" 200 OK
1947
2024-01-02 10:37:29,304 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/agent_chat "HTTP/1.1 200 OK"

> Entering new AgentExecutor chain...
2024-01-02 10:37:58 | INFO | stdout | INFO:     127.0.0.1:60263 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-02 10:37:58,804 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-02 10:37:59 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-02 10:39:39 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-01-02 10:39:39 | ERROR | stderr | Traceback (most recent call last):
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_backends\anyio.py", line 34, in read
2024-01-02 10:39:39 | ERROR | stderr |     return await self._stream.receive(max_bytes=max_bytes)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\anyio\_backends\_asyncio.py", line 1203, in receive
2024-01-02 10:39:39 | ERROR | stderr |     await self._protocol.read_event.wait()
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\asyncio\locks.py", line 214, in wait
2024-01-02 10:39:39 | ERROR | stderr |     await fut
2024-01-02 10:39:39 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-01-02 10:39:39 | ERROR | stderr | 
2024-01-02 10:39:39 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-01-02 10:39:39 | ERROR | stderr | 
2024-01-02 10:39:39 | ERROR | stderr | Traceback (most recent call last):
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
2024-01-02 10:39:39 | ERROR | stderr |     yield
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
2024-01-02 10:39:39 | ERROR | stderr |     with anyio.fail_after(timeout):
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\anyio\_core\_tasks.py", line 119, in __exit__
2024-01-02 10:39:39 | ERROR | stderr |     raise TimeoutError
2024-01-02 10:39:39 | ERROR | stderr | TimeoutError
2024-01-02 10:39:39 | ERROR | stderr | 
2024-01-02 10:39:39 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-01-02 10:39:39 | ERROR | stderr | 
2024-01-02 10:39:39 | ERROR | stderr | Traceback (most recent call last):
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
2024-01-02 10:39:39 | ERROR | stderr |     yield
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_transports\default.py", line 252, in __aiter__
2024-01-02 10:39:39 | ERROR | stderr |     async for part in self._httpcore_stream:
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\connection_pool.py", line 361, in __aiter__
2024-01-02 10:39:39 | ERROR | stderr |     async for part in self._stream:
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 337, in __aiter__
2024-01-02 10:39:39 | ERROR | stderr |     raise exc
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 329, in __aiter__
2024-01-02 10:39:39 | ERROR | stderr |     async for chunk in self._connection._receive_response_body(**kwargs):
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 198, in _receive_response_body
2024-01-02 10:39:39 | ERROR | stderr |     event = await self._receive_event(timeout=timeout)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 212, in _receive_event
2024-01-02 10:39:39 | ERROR | stderr |     data = await self._network_stream.read(
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_backends\anyio.py", line 31, in read
2024-01-02 10:39:39 | ERROR | stderr |     with map_exceptions(exc_map):
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\contextlib.py", line 153, in __exit__
2024-01-02 10:39:39 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
2024-01-02 10:39:39 | ERROR | stderr |     raise to_exc(exc) from exc
2024-01-02 10:39:39 | ERROR | stderr | httpcore.ReadTimeout
2024-01-02 10:39:39 | ERROR | stderr | 
2024-01-02 10:39:39 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-01-02 10:39:39 | ERROR | stderr | 
2024-01-02 10:39:39 | ERROR | stderr | Traceback (most recent call last):
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
2024-01-02 10:39:39 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\applications.py", line 122, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     raise exc
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     await self.app(scope, receive, send)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     raise exc
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     await self.app(scope, receive, sender)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\routing.py", line 718, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\routing.py", line 276, in handle
2024-01-02 10:39:39 | ERROR | stderr |     await self.app(scope, receive, send)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\routing.py", line 69, in app
2024-01-02 10:39:39 | ERROR | stderr |     await response(scope, receive, send)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\responses.py", line 270, in __call__
2024-01-02 10:39:39 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
2024-01-02 10:39:39 | ERROR | stderr |     raise exceptions[0]
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\responses.py", line 273, in wrap
2024-01-02 10:39:39 | ERROR | stderr |     await func()
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\responses.py", line 262, in stream_response
2024-01-02 10:39:39 | ERROR | stderr |     async for chunk in self.body_iterator:
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\fastchat\serve\openai_api_server.py", line 472, in chat_completion_stream_generator
2024-01-02 10:39:39 | ERROR | stderr |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\fastchat\serve\openai_api_server.py", line 657, in generate_completion_stream
2024-01-02 10:39:39 | ERROR | stderr |     async for raw_chunk in response.aiter_raw():
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_models.py", line 991, in aiter_raw
2024-01-02 10:39:39 | ERROR | stderr |     async for raw_stream_bytes in self.stream:
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_client.py", line 147, in __aiter__
2024-01-02 10:39:39 | ERROR | stderr |     async for chunk in self._stream:
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_transports\default.py", line 251, in __aiter__
2024-01-02 10:39:39 | ERROR | stderr |     with map_httpcore_exceptions():
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\contextlib.py", line 153, in __exit__
2024-01-02 10:39:39 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2024-01-02 10:39:39 | ERROR | stderr |   File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
2024-01-02 10:39:39 | ERROR | stderr |     raise mapped_exc(message) from exc
2024-01-02 10:39:39 | ERROR | stderr | httpx.ReadTimeout
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "F:\python_project\Langchain-Chatchat\server\chat\agent_chat.py", line 134, in agent_chat_iterator
    tools_use.append("\n```\n")
KeyError: 'tool_name'
2024-01-02 10:39:39,163 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
2024-01-02 10:39:39,163 - utils.py[line:24] - ERROR: peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\h11\_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\h11\_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\h11\_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    yield
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_transports\default.py", line 252, in __aiter__
    async for part in self._httpcore_stream:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\connection_pool.py", line 361, in __aiter__
    async for part in self._stream:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 337, in __aiter__
    raise exc
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 329, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 198, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_async\http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "F:\Program Files\anaconda3\envs\chat\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\python_project\Langchain-Chatchat\server\utils.py", line 22, in wrap_done
    await fn
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chains\base.py", line 381, in acall
    raise e
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chains\base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\agents\agent.py", line 1361, in _acall
    next_step_output = await self._atake_next_step(
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\agents\agent.py", line 1164, in _atake_next_step
    [
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\agents\agent.py", line 1164, in <listcomp>
    [
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\agents\agent.py", line 1192, in _aiter_next_step
    output = await self.agent.aplan(
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\agents\agent.py", line 656, in aplan
    full_output = await self.llm_chain.apredict(callbacks=callbacks, **full_inputs)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chains\llm.py", line 310, in apredict
    return (await self.acall(kwargs, callbacks=callbacks))[self.output_key]
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chains\base.py", line 381, in acall
    raise e
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chains\base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain_core\language_models\chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain_core\language_models\chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain_core\language_models\chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chat_models\openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain_core\language_models\chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\langchain\chat_models\openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\openai\_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\openai\_streaming.py", line 129, in __stream__
    async for sse in iterator:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\openai\_streaming.py", line 120, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\openai\_streaming.py", line 231, in aiter
    async for line in iterator:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_models.py", line 967, in aiter_lines
    async for text in self.aiter_text():
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_models.py", line 954, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_models.py", line 933, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_models.py", line 991, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_client.py", line 147, in __aiter__
    async for chunk in self._stream:
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_transports\default.py", line 251, in __aiter__
    with map_httpcore_exceptions():
  File "F:\Program Files\anaconda3\envs\chat\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "F:\Program Files\anaconda3\envs\chat\lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-01-02 10:39:39,209 - utils.py[line:27] - ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456) v0.2.8
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by CyanMystery** [comment]
解决了     把不需要的tool注释掉

**Comment by yumu7777777** [comment]
您好，注释的那一块能看看吗

**Comment by ZhichaoOuyang** [comment]
> 解决了 把不需要的tool注释掉

你好，能分享下解决方案吗

**Comment by Changgeng-Wei** [comment]
> > 解决了 把不需要的tool注释掉
> 
> 你好，能分享下解决方案吗

有解决方案吗？

**Comment by LIXUEGUANG002** [comment]
能分享一下 如何解决的吗？ 哪些tool去掉呢？
