### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by nswz** [chatchat-space/Langchain-Chatchat#2529]
INFO:     21.0.8.254:58374 - "POST /knowledge_base/upload_temp_docs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/model/Langchain-Chatchat/server/chat/file_chat.py", line 88, in upload_temp_docs
    vs.add_documents(documents)
  File "/usr/local/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 122, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 223, in add_texts
    embeddings = self._embed_documents(texts)
  File "/usr/local/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 135, in _embed_documents
    return self.embedding_function.embed_documents(texts)
  File "/home/model/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 399, in embed_documents
    return normalize(embeddings).tolist()
  File "/home/model/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 38, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "/usr/local/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 2542, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

文件对话时，上传文件报错，有的pdf可以，有的pdf不可以，环境是阿里云的函数FC，自己打包的镜像

**Comment by nswz** [comment]
加载知识库时报错，我应该如何排查问题 libGL.so.1: cannot open shared object file: No such file or directory

**Comment by nswz** [comment]
FC Invoke Start RequestId: 1-6598b6f1-137786fc-77ce1f054dc9
c-6598b56c-133554d8-85a33d9c63d92024-01-06 10:12:022024-01-06 02:12:02,012 - utils.py[line:289] - INFO: UnstructuredWordDocumentLoader used for /home/model/chatchat/tmp1u3fpk2b/1.doc
c-6598b56c-133554d8-85a33d9c63d92024-01-06 10:12:05
FC Invoke End RequestId: 1-6598b6f1-137786fc-77ce1f054dc9
c-6598b56c-133554d8-85a33d9c63d92024-01-06 10:12:052024-01-06 02:12:05,008 - faiss_cache.py[line:129] - INFO: loading vector store in 'tmp1u3fpk2b' to memory.

Batches:   0% 0/1 [00:00<?, ?it/s]
Batches: 100% 1/1 [00:00<00:00, 48.53it/s]
/usr/local/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(

Batches: 0it [00:00, ?it/s]
Batches: 0it [00:00, ?it/s]
INFO:     21.0.8.254:44406 - "POST /knowledge_base/upload_temp_docs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/model/Langchain-Chatchat/server/chat/file_chat.py", line 88, in upload_temp_docs
    vs.add_documents(documents)
  File "/usr/local/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 225, in add_texts
    embeddings = self._embed_documents(texts)
  File "/usr/local/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 137, in _embed_documents
    return self.embedding_function.embed_documents(texts)
  File "/home/model/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 421, in embed_documents
    return normalize(embeddings).tolist()
  File "/home/model/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "/usr/local/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 2583, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1

上传文件时报错，同样的文件，在windows下是没有问题的

**Comment by zRzRzRzRzRzRzR** [comment]
wiki有这个错误的的解决方法
 libGL.so.1: cannot open shared object file: No such file or directory
