### ISSUE TITLE
[BUG] 在线模型api切换bug

### ISSUE THREAD

**Issue by 1195332939** [chatchat-space/Langchain-Chatchat#2532]
**问题描述 / Problem Description**
两个在线模型api接口切换时，streamlit 异常

**复现问题的步骤 **
配置好两个在线模型接口，我当前配置的是智普和千问两个在线api接口，调用官方案例，在当前环境是可以成功的，在浏览器进行切换调用时，提示该异常。

问题异常详细报错信息：
2024-01-03 14:11:31.603 Uncaught app exception
Traceback (most recent call last):
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 326, in dialogue_page
    chat_box.show_feedback(**feedback_kwargs,
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit_chatbox/messages.py", line 309, in show_feedback
    return streamlit_feedback(**kwargs)
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit_feedback/__init__.py", line 104, in streamlit_feedback
    component_value = _component_func(
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit/components/v1/components.py", line 80, in __call__
    return self.create_instance(*args, default=default, key=key, **kwargs)
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 396, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit/components/v1/components.py", line 241, in create_instance
    return_value = marshall_component(dg, element)
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit/components/v1/components.py", line 212, in marshall_component
    component_state = register_widget(
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit_option_menu/streamlit_callback.py", line 20, in wrapper_register_widget
    return register_widget(*args, **kwargs)
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit/runtime/state/widgets.py", line 161, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
  File "/opt/langchain-env/lib/python3.10/site-packages/streamlit/runtime/state/widgets.py", line 194, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple widgets with the same `key=''`.

To fix this, please make sure that the `key` argument is unique for each
widget you create.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.8
- 是否使用 Docker 部署（是/否）：是 
- Python 版本 / Python version: 3.10.12

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="1378" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/93239683/95b708dd-adf2-4f14-aa38-3a5b32c831a3">
没有出现，因该是你上一次没回答出来或者没回答完，streamlit位置冲突
