### ISSUE TITLE
zhipu-api轻量化部署报错

### ISSUE THREAD

**Issue by lcdisme** [chatchat-space/Langchain-Chatchat#2535]
我是mac上用zhipu-api做llm、embedding，启动没有问题，但是在知识库向量化的时候，会报错
--- Logging error ---
Traceback (most recent call last):
  File "/Users/lcd/opt/anaconda3/envs/langchain_pj/lib/python3.10/site-packages/zhipuai/utils/http_client.py", line 26, in post
    raise Exception("响应异常：" + resp.content)
TypeError: can only concatenate str (not "bytes") to str

 logging.exception("请求异常", e)
Message: '请求异常'
Arguments: (TypeError('can only concatenate str (not "bytes") to str'),)

File "/Users/lcd/Downloads/pip_pkg/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 78, in do_add_doc
    ids = vs.add_embeddings(text_embeddings=zip(data["texts"], data["embeddings"]),
TypeError: 'NoneType' object is not subscriptable

感觉是向zhipu-api发送embedding post的时候没成功，断点复现响应码是400。但是同样的post，同样的url、header、token、data，我新开一个运行窗口测试post正常，可以正常返回embedding后的向量，奇怪，请求大神支持~~~

**Comment by zRzRzRzRzRzRzR** [comment]
我们会在之后修复这个问题，zhipu APi请求可能会重写
