### ISSUE TITLE
 数据库初始化是报错   loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

### ISSUE THREAD

**Issue by hponiang** [chatchat-space/Langchain-Chatchat#2537]
python 3.9  Mac pro 2018

50-1-80-34 Langchain-Chatchat % python init_database.py --recreate-vs
recreating all vector stores
2024-01-03 16:35:04,827 - faiss_cache.py[line:94] - INFO: loading vector store in 'samples/vector_store/bge-large-zh' from disk.
2024-01-03 16:35:06,631 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh
2024-01-03 16:35:07,322 - embeddings_api.py[line:40] - ERROR: Error while deserializing header: MetadataIncompleteBuffer
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/init_database.py", line 108, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/server/knowledge_base/migrate.py", line 121, in folder2db
    kb.create_kb()
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 80, in create_kb
    self.do_create_kb()
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 104, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 62, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
  File "/Users/dtisme/miniconda3/envs/py390/lib/python3.9/site-packages/langchain_core/vectorstores.py", line 510, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/Users/dtisme/miniconda3/envs/py390/lib/python3.9/site-packages/langchain_community/vectorstores/faiss.py", line 914, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 421, in embed_documents
    return normalize(embeddings).tolist()
  File "/Users/dtisme/wwwroots/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "/Users/dtisme/miniconda3/envs/py390/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 2582, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by hponiang** [comment]
@

> _🤖_
> 
> 你好 @hponiang 👋，我是[Dosu](https://dosu.dev)！让我来帮助你解决问题，回答你的疑问，甚至成为贡献者。虽然我是一个机器人，但在等待人类维护者的同时，我在这里为你提供帮助。😄
> 
> 根据您提供的错误信息，这个问题可能是由于某个函数期望得到一个数值类型（如整数或浮点数），但是却收到了一个NoneType。然而，从提供的上下文中，我们无法确定这个错误是在哪里发生的，因为没有直接使用numpy的ufunc或任何其他可能导致这个错误的数值计算。这个错误可能来自于一个更深层次的导入模块或函数，这些模块或函数并没有包含在提供的上下文中。
> 
> 因此，如果没有更具体的错误发生位置信息（如完整的回溯或更多的上下文），我们无法提供一个确定的解决方案。
> 
> 另外，我在Langchain-Chatchat的问题库中找到了一些类似的已解决问题，可能对您有所帮助：
> 
> 1. [[BUG] 3. 初始化知识库和配置文件 报错  python init_database.py --recreate-vs](https://github.com/chatchat-space/Langchain-Chatchat/issues/2283)
>    建议的解决方案是：
>    
>    1. 如果尚未安装`sentence-transformers`包，请安装：
>       ```
>       pip install sentence-transformers
>       ```
>    2. 手动从Hugging Face下载`bge-large-zh`模型。
>    3. 修改`model_config.py`文件，更新`EMBEDDING_MODEL`和`MODEL_PATH`为您放置下载模型的路径。
>    4. 修改`model_config.py`后，执行以下命令应用更改：
>       ```
>       python copy_config_example.py
>       ```
> 2. [python init_database.py --recreate-vs 初始数据库失败：](https://github.com/chatchat-space/Langchain-Chatchat/issues/2421)
>    建议的解决方案是：
>    
>    1. 更新代码。
>    2. 注意模型路径和使用双反斜杠(`\\`)。
>    3. 删除`info.db`，然后重新创建知识库。
> 3. [运行 python init_database --recreate-vs 报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2300)
>    这个问题被以下问题引用：
>    
>    * [英文版bge-large-en-v1.5 embeddings 向量无法加载](https://github.com/chatchat-space/Langchain-Chatchat/issues/2456)
>      建议的解决方案是：
>    
>    > OpenAIEmbeddings配置需要改下，embeddings = OpenAIEmbeddings(model=model,
> 
> 如果以上的解决方案不能解决您的问题，或者您需要更多的帮助，欢迎您提供更多的上下文信息或完整的错误回溯。
> 
> ## Sources
> * [[BUG] 3. 初始化知识库和配置文件 报错  python init_database.py --recreate-vs](https://github.com/chatchat-space/Langchain-Chatchat/issues/2283)
> * [python init_database.py --recreate-vs 初始数据库失败：](https://github.com/chatchat-space/Langchain-Chatchat/issues/2421)
> * [运行 python init_database --recreate-vs 报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2300)
> * [startup.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/startup.py)
> * [init_database.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/init_database.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

这些方法都试过了，哎，有点烦

**Comment by hponiang** [comment]
解决了，是# 选用的 Embedding 名称 bge-large-zh太大了，下载有问题，改这个小型的就好了，一般在本地cpu 跑都用这个，建议分多个配置文件版本，像 privategpt那样
EMBEDDING_MODEL = "bge-small-zh"

**Comment by shaotiancai** [comment]
我的是显存不足，换了一张显存大点的卡就解决了。

**Comment by WGS-note** [comment]
我是中文名引发的这个问题
