### ISSUE TITLE
运行webui时提示pyarrow包报错

### ISSUE THREAD

**Issue by limi1** [chatchat-space/Langchain-Chatchat#2550]
在anaconda的虚拟环境中运行  python webui.py -a
报一下错误，是我的pyarrow的版本没用下载对吗
Traceback (most recent call last):
  File "E:\workspace\python\langchain-ChatGLM\webui.py", line 1, in <module>
    import streamlit as st
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\__init__.py", line 56, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\delta_generator.py", line 37, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\runtime\__init__.py", line 15, in <module>
    from streamlit.runtime.runtime import Runtime, RuntimeConfig, RuntimeState
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\runtime\runtime.py", line 30, in <module>
    from streamlit.runtime.app_session import AppSession
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\runtime\app_session.py", line 36, in <module>
    from streamlit.runtime import caching, legacy_caching
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\runtime\caching\__init__.py", line 21, in <module>
    from streamlit.runtime.caching.cache_data_api import (
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\runtime\caching\cache_data_api.py", line 32, in <module>
    from streamlit.runtime.caching.cache_errors import CacheError, CacheKeyNotFoundError
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\runtime\caching\cache_errors.py", line 18, in <module>
    from streamlit import type_util
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\streamlit\type_util.py", line 42, in <module>
    import pyarrow as pa
  File "C:\Users\13924\.conda\envs\langchain\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: DLL load failed while importing lib: 找不到指定的程序。

**Comment by limi1** [comment]
我虚拟环境的python是3.10.12、pyarrow是14.0.2

**Comment by zRzRzRzRzRzRzR** [comment]
没有遇到过类似问题，难道是windows的吗，我linux的环境跟你一样没有遇到这个问题
