### ISSUE TITLE
[v0.2.9]使用vllm加速原版Qwen-7B-Chat和chatglm2-6b均报错，上个版本(v0.2.8)没有这个情况

### ISSUE THREAD

**Issue by ImmNaruto** [chatchat-space/Langchain-Chatchat#2571]
**问题描述 / Problem Description**
vllm加速原版Qwen-7B-Chat和chatglm2-6b均报错

**复现问题的步骤 / Steps to Reproduce**
1. 配置好环境后，未使用vllm加速启动，正常推理
2. 修改server_config.py中
`FSCHAT_MODEL_WORKERS = {
    # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
    "default": {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
        # vllm对一些模型支持还不成熟，暂时默认关闭
        # fschat=0.2.33的代码有bug, 如需使用，源码修改fastchat.server.vllm_worker，
        # 将103行中sampling_params = SamplingParams的参数stop=list(stop)修改为stop= [i for i in stop if i!=""]
        "infer_turbo": 'vllm',

        # model_worker多卡加载需要配置的参数
        # "gpus": None, # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        # "num_gpus": 1, # 使用GPU的数量
        # "max_gpu_memory": "20GiB", # 每个GPU占用的最大显存

        # 以下为model_worker非常用参数，可根据需要配置
        # "load_8bit": False, # 开启8bit量化
        # "cpu_offloading": None,
        # "gptq_ckpt": None,
        # "gptq_wbits": 16,
        # "gptq_groupsize": -1,
        # "gptq_act_order": False,
        # "awq_ckpt": None,
        # "awq_wbits": 16,
        # "awq_groupsize": -1,
        # "model_names": LLM_MODELS,
        # "conv_template": None,
        # "limit_worker_concurrency": 5,
        # "stream_interval": 2,
        # "no_register": False,
        # "embed_in_truncate": False,

        # 以下为vllm_worker配置参数,注意使用vllm必须有gpu，仅在Linux测试通过

        # tokenizer = model_path # 如果tokenizer与model_path不一致在此处添加
        'tokenizer_mode':'auto',
        'trust_remote_code':True,
        'download_dir':None,
        'load_format':'auto',
        'dtype':'auto',
        'seed':0,
        'worker_use_ray':False,
        'pipeline_parallel_size':1,
        'tensor_parallel_size':1,
        'block_size':16,
        'swap_space':4 , # GiB
        'gpu_memory_utilization':0.90,
        'max_num_batched_tokens':2560,
        'max_num_seqs':256,
        'disable_log_stats':False,
        'conv_template':None,
        'limit_worker_concurrency':5,
        'no_register':False,
        'num_gpus': 1,
        'engine_use_ray': False,
        'disable_log_requests': False
    },`
3. 再次启动，问题出现 / Problem occurs
`2024-01-06 10:04:15 | INFO | model_worker | Register to controller
2024-01-06 10:04:16 | ERROR | stderr | Process model_worker - Qwen-7B-Chat:
2024-01-06 10:04:16 | ERROR | stderr | Traceback (most recent call last):
2024-01-06 10:04:16 | ERROR | stderr |   File "/workspace/anaconda3/envs/langchat029/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-01-06 10:04:16 | ERROR | stderr |     self.run()
2024-01-06 10:04:16 | ERROR | stderr |   File "/workspace/anaconda3/envs/langchat029/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-01-06 10:04:16 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-06 10:04:16 | ERROR | stderr |   File "/workspace/AIProjects/Langchain-Chatchat-v0.2.9/startup.py", line 387, in run_model_worker
2024-01-06 10:04:16 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-06 10:04:16 | ERROR | stderr |   File "/workspace/AIProjects/Langchain-Chatchat-v0.2.9/startup.py", line 153, in create_model_worker_app
2024-01-06 10:04:16 | ERROR | stderr |     engine_args = AsyncEngineArgs.from_cli_args(args)
2024-01-06 10:04:16 | ERROR | stderr |   File "/workspace/anaconda3/envs/langchat029/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 210, in from_cli_args
2024-01-06 10:04:16 | ERROR | stderr |     engine_args = cls(**{attr: getattr(args, attr) for attr in attrs})
2024-01-06 10:04:16 | ERROR | stderr |   File "/workspace/anaconda3/envs/langchat029/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 210, in <dictcomp>
2024-01-06 10:04:16 | ERROR | stderr |     engine_args = cls(**{attr: getattr(args, attr) for attr in attrs})
2024-01-06 10:04:16 | ERROR | stderr | AttributeError: 'Namespace' object has no attribute 'max_parallel_loading_workers'`

**预期的结果 / Expected Result**
正常运行

**实际结果 / Actual Result**
无法注册

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: v0.2.9
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B/ Qwen-7B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:centos 9
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:
  操作系统：Linux-5.14.0-362.el9.x86_64-x86_64-with-glibc2.34.
  python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
  项目版本：v0.2.9
  langchain版本：0.0.352. fastchat版本：0.2.34

**附加信息 / Additional Information**
上个版本无问题

**Comment by weipeng008005** [comment]
您好作者，请问这个问题解决了吗？

**Comment by ImmNaruto** [comment]
@weipeng008005 目前还没解决，我用了新版0.2.10也是一样的

**Comment by ImmNaruto** [comment]
@weipeng008005 更新：已解决，多谢 @Lijia0 大佬提醒，在vllm配置中添加如下4行：
"max_parallel_loading_workers":1,
"enforce_eager":False,
"max_context_len_to_capture":2048,
"max_model_len":2048
即可正常运行

**Comment by GXKIM** [comment]
> @weipeng008005 更新：已解决，多谢 @Lijia0 大佬提醒，在vllm配置中添加如下4行： "max_parallel_loading_workers":1, "enforce_eager":False, "max_context_len_to_capture":2048, "max_model_len":2048 即可正常运行

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/125621025/daab9401-6c3d-45b1-b626-937caecbc412)
是这么加吗

**Comment by Wimeremce7** [comment]
多卡并行怎么使用vllm，有大佬配置过吗
