### ISSUE TITLE
[BUG] 简洁阐述问题 / 更新最新版本后 执行 py start -a  就会出现 fsatapi 模块不存在 

### ISSUE THREAD

**Issue by Bo-LiangD** [chatchat-space/Langchain-Chatchat#2574]
2024-01-06 17:55:49.539 Uncaught app exception
Traceback (most recent call last):
  File "/home/wb/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/wb/Langchain-Chatchat-0.2.9/webui.py", line 2, in <module>
    from webui_pages.utils import *
  File "/home/wb/Langchain-Chatchat-0.2.9/webui_pages/utils.py", line 27, in <module>
    from server.utils import set_httpx_config, api_address, get_httpx_client
  File "/home/wb/Langchain-Chatchat-0.2.9/server/utils.py", line 4, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
2024-01-06 17:55:51.077 Uncaught app exception
Traceback (most recent call last):
  File "/home/wb/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/wb/Langchain-Chatchat-0.2.9/webui.py", line 2, in <module>
    from webui_pages.utils import *
  File "/home/wb/Langchain-Chatchat-0.2.9/webui_pages/utils.py", line 27, in <module>
    from server.utils import set_httpx_config, api_address, get_httpx_client
  File "/home/wb/Langchain-Chatchat-0.2.9/server/utils.py", line 4, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'

**Comment by Bo-LiangD** [comment]
找了很多发放貌似 都不行

**Comment by Bo-LiangD** [comment]
找了很多方法， 貌似都不行

**Comment by zRzRzRzRzRzRzR** [comment]
没有出现相似问题，先试试是否能pip list 到这个模块
