### ISSUE TITLE
[BUG] 文件对话上传时internal 500 错误，可能在memo_faiss_pool.load_vector_store(id).acquire()出错

### ISSUE THREAD

**Issue by aotsukiqx** [chatchat-space/Langchain-Chatchat#2575]
**问题描述 / Problem Description**
文件对话上传时internal 500 错误，upload_temp_docs接口可能在memo_faiss_pool.load_vector_store(id).acquire()出错

**复现问题的步骤 / Steps to Reproduce**
1. 安装lite requirements所有依赖库，（llm在另外的机器上部署了openai like api，数据库是远程milvus；本地运行chatchat框架负责webui、embedding）
2. 验证搜索和知识库对话功能正常。
3. 选择文件对话，选择上传文件一个文件，并点击开始上传

**预期的结果 / Expected Result**
应当正常完成文件的上传与向量化，并正常使用问答。

**实际结果 / Actual Result**
embedding后提示faiss 加载完成，然后报错
2024-01-07 08:22:49,269 - utils.py[line:289] - INFO: UnstructuredMarkdownLoader used for /tmp/chatchat/tmpol_vq_19/Readme.md
2024-01-07 08:22:49,270 - faiss_cache.py[line:129] - INFO: loading vector store in 'tmpol_vq_19' to memory.
2024-01-07 08:22:49,271 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: models/shibing624/text2vec-bge-large-chinese
2024-01-07 08:22:49,271 - SentenceTransformer.py[line:805] - WARNING: No sentence-transformers model found with name models/shibing624/text2vec-bge-large-chinese. Creating a new one with MEAN pooling.
Batches: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.08s/it]
2024-01-07 08:22:51,943 - loader.py[line:64] - INFO: Loading faiss.
2024-01-07 08:22:51,971 - loader.py[line:66] - INFO: Successfully loaded faiss.
/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(
Batches: 0it [00:00, ?it/s]
INFO:     192.168.2.8:58322 - "POST /knowledge_base/upload_temp_docs HTTP/1.1" 500 Internal Server Error
2024-01-07 08:22:52,014 - _client.py[line:1013] - INFO: HTTP Request: POST http://[domain name]:7861/knowledge_base/upload_temp_docs "HTTP/1.1 500 Internal Server Error"
2024-01-07 08:22:52.015 Uncaught app exception
Traceback (most recent call last):
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 87, in get
    entry_bytes = self._read_from_mem_cache(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 137, in _read_from_mem_cache
    raise CacheStorageKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 634, in read_result
    pickled_entry = self.storage.get(key)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 89, in get
    entry_bytes = self._persist_storage.get(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/storage/local_disk_cache_storage.py", line 155, in get
    raise CacheStorageKeyNotFoundError(
streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Local disk cache storage is disabled (persist=None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 636, in read_result
    raise CacheKeyNotFoundError(str(e)) from e
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError: Local disk cache storage is disabled (persist=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 87, in get
    entry_bytes = self._read_from_mem_cache(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 137, in _read_from_mem_cache
    raise CacheStorageKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 634, in read_result
    pickled_entry = self.storage.get(key)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 89, in get
    entry_bytes = self._persist_storage.get(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/storage/local_disk_cache_storage.py", line 155, in get
    raise CacheStorageKeyNotFoundError(
streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Local disk cache storage is disabled (persist=None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 636, in read_result
    raise CacheKeyNotFoundError(str(e)) from e
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError: Local disk cache storage is disabled (persist=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/colin/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/colin/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 261, in dialogue_page
    st.session_state["file_chat_id"] = upload_temp_docs(files, api)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 50, in upload_temp_docs
    return _api.upload_temp_docs(files).get("data", {}).get("id")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/Langchain-Chatchat/server/chat/file_chat.py", line 90, in upload_temp_docs
    vs.add_documents(documents)
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 225, in add_texts
    embeddings = self._embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 137, in _embed_documents
    return self.embedding_function.embed_documents(texts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 421, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 2583, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1

**环境信息 / Environment Information**
- langchain-ChatGLM v0.2.9
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：OpenAI LIKE API
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：shibing624/text2vec-bge-large-chinese、moka-ai/m3e-large-zh等都试过一样结果
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): milvus用于KB，faiss是框架本地对话默认vs
- 操作系统及版本 / Operating system and version: ubuntu23.04 x86_64，在macos M2上也有同样问题
- Python 版本 / Python version:3.11.6
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by aotsukiqx** [comment]
继续尝试了多次，仔细分析日志，每次重新启动后的第一次进行文件对话的结果，好像都是在faiss临时向量库加载ok后又再次尝试导致的错误，相关日志如下：
2024-01-07 08:22:49,270 - faiss_cache.py[line:129] - INFO: loading vector store in 'tmpol_vq_19' to memory.
2024-01-07 08:22:49,271 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: models/shibing624/text2vec-bge-large-chinese
2024-01-07 08:22:49,271 - SentenceTransformer.py[line:805] - WARNING: No sentence-transformers model found with name models/shibing624/text2vec-bge-large-chinese. Creating a new one with MEAN pooling.
Batches: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00, 1.08s/it]
2024-01-07 08:22:51,943 - loader.py[line:64] - INFO: Loading faiss.
2024-01-07 08:22:51,971 - loader.py[line:66] - INFO: Successfully loaded faiss.
/home/colin/mambaforge/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
warnings.warn(
Batches: 0it [00:00, ?it/s]
INFO: 192.168.2.8:58322 - "POST /knowledge_base/upload_temp_docs HTTP/1.1" 500 Internal Server Error

**Comment by nswz** [comment]
我也遇到这个问题，我的是faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
有的文件可以上传成功，部分文件上传不成功，无从下手了有点

**Comment by aotsukiqx** [comment]
> 我也遇到这个问题，我的是faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT 有的文件可以上传成功，部分文件上传不成功，无从下手了有点

这个warning是不影响后续逻辑的，至于上传不成功要看是什么文件，比较常见的可能是langchain的document loader需要的依赖没有装。但是也遇到过opencv的问题确实报错导致有些图片无法识别而造成的失败。和我提的这个bug还是不太一样的。

**Comment by zRzRzRzRzRzRzR** [comment]
图片识别问题，当前版本估计很难解决这个bug，后续版本处理一下

**Comment by zRzRzRzRzRzRzR** [comment]
> > 我也遇到这个问题，我的是faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT 有的文件可以上传成功，部分文件上传不成功，无从下手了有点
> 
> 这个warning是不影响后续逻辑的，至于上传不成功要看是什么文件，比较常见的可能是langchain的document loader需要的依赖没有装。但是也遇到过opencv的问题确实报错导致有些图片无法识别而造成的失败。和我提的这个bug还是不太一样的。

这个不是缺少依赖的问题，应该是在ocr的时候有一些奇怪的符号或者一些图像信息被传进来了没法用语言的方法决定，你的问题文件中有图像吗

**Comment by nswz** [comment]
> > > 我也遇到这个问题，我是faiss.py:121: UserWarning: Normalizing L2 is not unavailable for metric type: METRIC_INNER_PRODUCT 有的文件上传可以成功，部分文件上传不成功，无从下手了一点
> > 
> > 
> > 这个警告是不影响后续逻辑的，至于上传不成功除了什么文件，比较常见的可能是langchain的文档加载器需要的依赖没有安装。但是也遇到过opencv的问题确实报错导致一些无法图片识别而造成的失败。和我提的这个bug还是不太一样的。
> 
> 这不是缺少依赖的问题，应该是在ocr的时候有一些奇怪的符号或者一些图像信息被传入了无法用语言的方法决定，你的问题文件在图像吗

识别不了的文件或图片，把rapidocr_paddle[gpu]这个包卸载了就可以识别了，windows上没遇到这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
rapidocr_paddle[gpu] 是GPU版本，你的GPU和paddle捆绑对吗
CPU版本可能会很慢

**Comment by aotsukiqx** [comment]
是任何类型的文件都不行，txt都一样的错误，总结就是目前文件问答没法用。
今天重新checkout master分支，直接pull最新的commit，只是保留了原来的configs下的配置，问题依旧。
我的环境是mac M2 ultra，配置都指定了mps

**Comment by ixiami1314** [comment]
我发现我也是这样的。有些文件是成功的，但有些就是提示steamlit的Key not found in mem cache 类似的问题

**Comment by zRzRzRzRzRzRzR** [comment]
m2系列或许是faiss的问题，因为测的时候用的是Linux，得问一下开发组有谁在mac

**Comment by zRzRzRzRzRzRzR** [comment]
那就是没有成功载入到faiss，或许得查询一下关于faiss的安装问题
