### ISSUE TITLE
启动出现报错OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by gsz18** [chatchat-space/Langchain-Chatchat#2579]
win10专业版系统
python startup.py -a启动的时候卡住了，出现报错
![捕获](https://github.com/chatchat-space/Langchain-Chatchat/assets/41658959/56cf08d8-c571-4ad7-bdf8-4fd25827008f)
是什么原因呢？

**Comment by gsz18** [comment]
这是报错日志信息
2024-01-08 10:42:13 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 21da9ec9 ...
2024-01-08 10:42:33 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
2024-01-08 10:42:34 | ERROR | stderr |     conn = connection.create_connection(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
2024-01-08 10:42:34 | ERROR | stderr |     raise err
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
2024-01-08 10:42:34 | ERROR | stderr |     sock.connect(sa)
2024-01-08 10:42:34 | ERROR | stderr | TimeoutError: timed out
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
2024-01-08 10:42:34 | ERROR | stderr |     httplib_response = self._make_request(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
2024-01-08 10:42:34 | ERROR | stderr |     self._validate_conn(conn)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
2024-01-08 10:42:34 | ERROR | stderr |     conn.connect()
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connection.py", line 358, in connect
2024-01-08 10:42:34 | ERROR | stderr |     self.sock = conn = self._new_conn()
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
2024-01-08 10:42:34 | ERROR | stderr |     raise ConnectTimeoutError(
2024-01-08 10:42:34 | ERROR | stderr | urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000019BDAFDDF00>, 'Connection to huggingface.co timed out. (connect timeout=10)')
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\requests\adapters.py", line 486, in send
2024-01-08 10:42:34 | ERROR | stderr |     resp = conn.urlopen(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
2024-01-08 10:42:34 | ERROR | stderr |     retries = retries.increment(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\util\retry.py", line 592, in increment
2024-01-08 10:42:34 | ERROR | stderr |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2024-01-08 10:42:34 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000019BDAFDDF00>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 1238, in hf_hub_download
2024-01-08 10:42:34 | ERROR | stderr |     metadata = get_hf_file_metadata(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
2024-01-08 10:42:34 | ERROR | stderr |     return fn(*args, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
2024-01-08 10:42:34 | ERROR | stderr |     r = _request_wrapper(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
2024-01-08 10:42:34 | ERROR | stderr |     response = _request_wrapper(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
2024-01-08 10:42:34 | ERROR | stderr |     response = get_session().request(method=method, url=url, **params)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\requests\sessions.py", line 589, in request
2024-01-08 10:42:34 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\requests\sessions.py", line 703, in send
2024-01-08 10:42:34 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
2024-01-08 10:42:34 | ERROR | stderr |     return super().send(request, *args, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\requests\adapters.py", line 507, in send
2024-01-08 10:42:34 | ERROR | stderr |     raise ConnectTimeout(e, request=request)
2024-01-08 10:42:34 | ERROR | stderr | requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000019BDAFDDF00>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: c114c93d-3b48-40f3-bf62-c9603c936ea1)')
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\utils\hub.py", line 389, in cached_file
2024-01-08 10:42:34 | ERROR | stderr |     resolved_file = hf_hub_download(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
2024-01-08 10:42:34 | ERROR | stderr |     return fn(*args, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 1371, in hf_hub_download
2024-01-08 10:42:34 | ERROR | stderr |     raise LocalEntryNotFoundError(
2024-01-08 10:42:34 | ERROR | stderr | huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\multiprocessing\process.py", line 314, in _bootstrap
2024-01-08 10:42:34 | ERROR | stderr |     self.run()
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\multiprocessing\process.py", line 108, in run
2024-01-08 10:42:34 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\Langchain-Chatchat\startup.py", line 387, in run_model_worker
2024-01-08 10:42:34 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\Langchain-Chatchat\startup.py", line 215, in create_model_worker_app
2024-01-08 10:42:34 | ERROR | stderr |     worker = ModelWorker(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-01-08 10:42:34 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\fastchat\model\model_adapter.py", line 323, in load_model
2024-01-08 10:42:34 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\fastchat\model\model_adapter.py", line 774, in load_model
2024-01-08 10:42:34 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 752, in from_pretrained
2024-01-08 10:42:34 | ERROR | stderr |     config = AutoConfig.from_pretrained(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1082, in from_pretrained
2024-01-08 10:42:34 | ERROR | stderr |     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\configuration_utils.py", line 644, in get_config_dict
2024-01-08 10:42:34 | ERROR | stderr |     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\configuration_utils.py", line 699, in _get_config_dict
2024-01-08 10:42:34 | ERROR | stderr |     resolved_config_file = cached_file(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\utils\hub.py", line 429, in cached_file
2024-01-08 10:42:34 | ERROR | stderr |     raise EnvironmentError(
2024-01-08 10:42:34 | ERROR | stderr | OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named config.json.
2024-01-08 10:42:34 | ERROR | stderr | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by zRzRzRzRzRzRzR** [comment]
这不报错链接不上huggingface吗，你路径没改

**Comment by gsz18** [comment]
> huggingfac

这个路径在哪改，我是本地部署的

**Comment by gsz18** [comment]
> 这不报错链接不上huggingface吗，你路径没改

这个路径在哪改，我是本地部署的
