### ISSUE TITLE
python startup.py -a执行报错卡住

### ISSUE THREAD

**Issue by gsz18** [chatchat-space/Langchain-Chatchat#2580]
**问题描述 / Problem Description**
![捕获](https://github.com/chatchat-space/Langchain-Chatchat/assets/41658959/fbd75b7a-c9b0-4e8c-a310-e71e62bb6443)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'  python startup.py -a

**预期的结果 / Expected Result**
操作系统：Windows-10-10.0.19044-SP0.
python版本：3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]
项目版本：v0.2.6
langchain版本：0.0.330. fastchat版本：0.2.31
————————————————
版权声明：本文为CSDN博主「码农丁丁」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/xqdd/article/details/134247532

**实际结果 / Actual Result**
2024-01-08 10:42:13 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 21da9ec9 ...
2024-01-08 10:42:33 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
2024-01-08 10:42:34 | ERROR | stderr |     conn = connection.create_connection(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
2024-01-08 10:42:34 | ERROR | stderr |     raise err
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
2024-01-08 10:42:34 | ERROR | stderr |     sock.connect(sa)
2024-01-08 10:42:34 | ERROR | stderr | TimeoutError: timed out
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
2024-01-08 10:42:34 | ERROR | stderr |     httplib_response = self._make_request(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
2024-01-08 10:42:34 | ERROR | stderr |     self._validate_conn(conn)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
2024-01-08 10:42:34 | ERROR | stderr |     conn.connect()
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connection.py", line 358, in connect
2024-01-08 10:42:34 | ERROR | stderr |     self.sock = conn = self._new_conn()
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
2024-01-08 10:42:34 | ERROR | stderr |     raise ConnectTimeoutError(
2024-01-08 10:42:34 | ERROR | stderr | urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000019BDAFDDF00>, 'Connection to huggingface.co timed out. (connect timeout=10)')
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\requests\adapters.py", line 486, in send
2024-01-08 10:42:34 | ERROR | stderr |     resp = conn.urlopen(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
2024-01-08 10:42:34 | ERROR | stderr |     retries = retries.increment(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\urllib3\util\retry.py", line 592, in increment
2024-01-08 10:42:34 | ERROR | stderr |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2024-01-08 10:42:34 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000019BDAFDDF00>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 1238, in hf_hub_download
2024-01-08 10:42:34 | ERROR | stderr |     metadata = get_hf_file_metadata(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
2024-01-08 10:42:34 | ERROR | stderr |     return fn(*args, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
2024-01-08 10:42:34 | ERROR | stderr |     r = _request_wrapper(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
2024-01-08 10:42:34 | ERROR | stderr |     response = _request_wrapper(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
2024-01-08 10:42:34 | ERROR | stderr |     response = get_session().request(method=method, url=url, **params)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\requests\sessions.py", line 589, in request
2024-01-08 10:42:34 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\requests\sessions.py", line 703, in send
2024-01-08 10:42:34 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
2024-01-08 10:42:34 | ERROR | stderr |     return super().send(request, *args, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\requests\adapters.py", line 507, in send
2024-01-08 10:42:34 | ERROR | stderr |     raise ConnectTimeout(e, request=request)
2024-01-08 10:42:34 | ERROR | stderr | requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000019BDAFDDF00>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: c114c93d-3b48-40f3-bf62-c9603c936ea1)')
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\utils\hub.py", line 389, in cached_file
2024-01-08 10:42:34 | ERROR | stderr |     resolved_file = hf_hub_download(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
2024-01-08 10:42:34 | ERROR | stderr |     return fn(*args, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\huggingface_hub\file_download.py", line 1371, in hf_hub_download
2024-01-08 10:42:34 | ERROR | stderr |     raise LocalEntryNotFoundError(
2024-01-08 10:42:34 | ERROR | stderr | huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-01-08 10:42:34 | ERROR | stderr | 
2024-01-08 10:42:34 | ERROR | stderr | Traceback (most recent call last):
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\multiprocessing\process.py", line 314, in _bootstrap
2024-01-08 10:42:34 | ERROR | stderr |     self.run()
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\multiprocessing\process.py", line 108, in run
2024-01-08 10:42:34 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\Langchain-Chatchat\startup.py", line 387, in run_model_worker
2024-01-08 10:42:34 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\Langchain-Chatchat\startup.py", line 215, in create_model_worker_app
2024-01-08 10:42:34 | ERROR | stderr |     worker = ModelWorker(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-01-08 10:42:34 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\fastchat\model\model_adapter.py", line 323, in load_model
2024-01-08 10:42:34 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\fastchat\model\model_adapter.py", line 774, in load_model
2024-01-08 10:42:34 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 752, in from_pretrained
2024-01-08 10:42:34 | ERROR | stderr |     config = AutoConfig.from_pretrained(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1082, in from_pretrained
2024-01-08 10:42:34 | ERROR | stderr |     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\configuration_utils.py", line 644, in get_config_dict
2024-01-08 10:42:34 | ERROR | stderr |     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\configuration_utils.py", line 699, in _get_config_dict
2024-01-08 10:42:34 | ERROR | stderr |     resolved_config_file = cached_file(
2024-01-08 10:42:34 | ERROR | stderr |   File "C:\Users\admin\.conda\envs\l2\lib\site-packages\transformers\utils\hub.py", line 429, in cached_file
2024-01-08 10:42:34 | ERROR | stderr |     raise EnvironmentError(
2024-01-08 10:42:34 | ERROR | stderr | OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named config.json.
2024-01-08 10:42:34 | ERROR | stderr | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
报错：
  File "C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 165, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "C:\Users\admin\.conda\envs\l2\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\admin\.conda\envs\l2\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: win10专业版
- Python 版本 / Python version:3.10.12

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
We couldn't connect to 'https://huggingface.co/' to load this file, couldn
没链接上hf
