### ISSUE TITLE
[BUG] model_worker多卡加载后，模型返回结果明显错误

### ISSUE THREAD

**Issue by start-dzl** [chatchat-space/Langchain-Chatchat#2581]
**问题描述 / Problem Description**
 model_worker多卡加载后，模型返回结果明显错误

**复现问题的步骤 / Steps to Reproduce**
正常启动
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38344086/2a98274c-14c8-4fc3-a65f-cfa31a3af104)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38344086/c7e46deb-4629-424b-8eef-1e831099fc3f)

配置修改
        # model_worker多卡加载需要配置的参数
        "gpus": "3,4,5", # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        "num_gpus": 3, # 使用GPU的数量
        "max_gpu_memory": "44GiB", # 每个GPU占用的最大显存

**预期的结果 / Expected Result**
可以正常对话

**实际结果 / Actual Result**
无法对话
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38344086/fb4f63b2-e0ca-4b59-ae12-99f192086ab0)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.9
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Yi-34B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-reranker-large
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: 	Ubuntu 20.04.5 LTS
- Python 版本 / Python version:  3.9.18
- 其他相关环境信息 /
- 显卡 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38344086/1cac1178-f349-4c35-9051-9f7f0014314a)
使用3.4.5

**附加信息 / Additional Information**
异常日志：
2024-01-08 11:47:47,215 - utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/data/chatchat/Langchain-Chatchat-0.2.9/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 506, in agenerate_prompt
    return await self.agenerate(
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 466, in agenerate
    raise exceptions[0]
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 569, in _agenerate_with_cache
    return await self._agenerate(
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain_community/chat_models/openai.py", line 518, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 85, in agenerate_from_stream
    async for chunk in stream:
  File "/data/anaconda3/envs/lc29/lib/python3.9/site-packages/langchain_community/chat_models/openai.py", line 489, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-01-08 11:47:47,215 - utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by start-dzl** [comment]
将配置改成      
  "gpus": "4,5", # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        "num_gpus": 2, # 使用GPU的数量
        "max_gpu_memory": "44GiB", # 每个GPU占用的最大显存
可以正常对话，真是奇怪

**Comment by start-dzl** [comment]
后面加载qwen-72B-chat 也是出现这个问题

**Comment by start-dzl** [comment]
麻烦看下如何解决

**Comment by zRzRzRzRzRzRzR** [comment]
这个属于没有找到，估计是因为模型没被找到，你是vllm吗

**Comment by start-dzl** [comment]
> 这个属于没有找到，估计是因为模型没被找到，你是vllm吗

没，我没有开

**Comment by start-dzl** [comment]
发现 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38344086/13cd1b40-c16d-4670-bc2e-a6c2324cded2)
多卡的时候，GPU-Util 还是单卡

**Comment by zRzRzRzRzRzRzR** [comment]
哦确实是单卡推理呀，在第一张卡推理，剩下只是加载分担显存

**Comment by start-dzl** [comment]
> 哦确实是单卡推理呀，在第一张卡推理，剩下只是加载分担显存

这个是什么问题，感觉也没有要配置的

**Comment by start-dzl** [comment]
我很奇怪，我qwen 14b单卡跑都很顺利，但是多卡反而卡，而且乱

**Comment by zRzRzRzRzRzRzR** [comment]
不是，这个多卡只是因为显存不够所以需要分担显存，其实还是单卡推理，效果差很多事很正常的，模型被拆了，但是一直在第一块卡推

**Comment by start-dzl** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38344086/b6dbc8b1-4080-49ae-b04f-825d6ef05fee)
哦，理解，我调整一下重新跑了，有两块是其他模型的，现在调整一下，2,3,4,5是多卡加载  yi-34b 的，返回会出现上图问题，还会打出
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38344086/6c36869f-fc94-4504-93a0-31f1710d4acf)

**Comment by zRzRzRzRzRzRzR** [comment]
那你要看一下yi这个模型的载入方式是不是fschat支持的了，这个很显然是模型调用都出问题了，都不在我们的项目框架内

**Comment by John-ken** [comment]
> 不是，这个多卡只是因为显存不够所以需要分担显存，其实还是单卡推理，效果差很多事很正常的，模型被拆了，但是一直在第一块卡推

你好，请问这个使用多卡加载模型推理更慢，有别的解决方案吗？  使用更大的模型，单卡加载不了，多卡就会非常慢，甚至请求超时
