### ISSUE TITLE
執行python startup.py -a後報錯

### ISSUE THREAD

**Issue by Kimdow220807** [chatchat-space/Langchain-Chatchat#2596]
執行python startup.py -a後報錯：如下
C:\Users\OM-PC-089\miniconda3\envs\ChatChat\lib\site-packages\langchain\__init__.py:34: UserWarning: Importing Cohere from langchain root module is no longer supported. Please use langchain.llms.Cohere instead.
  warnings.warn(
C:\Users\OM-PC-089\miniconda3\envs\ChatChat\lib\site-packages\langchain\__init__.py:34: UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
  warnings.warn(
C:\Users\OM-PC-089\miniconda3\envs\ChatChat\lib\site-packages\langchain\__init__.py:34: UserWarning: Importing OpenAI from langchain root module is no longer supported. Please use langchain.llms.OpenAI instead.
  warnings.warn(
Process API Server:
Traceback (most recent call last):
  File "C:\Users\OM-PC-089\miniconda3\envs\ChatChat\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\OM-PC-089\miniconda3\envs\ChatChat\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AIGC\ChatChat\startup.py", line 436, in run_api_server
    app = create_app(run_mode=run_mode)
  File "D:\AIGC\ChatChat\server\api.py", line 51, in create_app
    mount_app_routes(app, run_mode=run_mode)
  File "D:\AIGC\ChatChat\server\api.py", line 77, in mount_app_routes
    mount_knowledge_routes(app)
  File "D:\AIGC\ChatChat\server\api.py", line 140, in mount_knowledge_routes
    from server.chat.knowledge_base_chat import knowledge_base_chat
  File "D:\AIGC\ChatChat\server\chat\knowledge_base_chat.py", line 24, in <module>
    from server.reranker.reranker import LangchainReranker
  File "D:\AIGC\ChatChat\server\reranker\reranker.py", line 11, in <module>
    from llama_index.bridge.pydantic import Field, PrivateAttr
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\keyword_table\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\keyword_table\base.py", line 17, in <module>
    from llama_index.indices.base import BaseGPTIndex, QueryMap
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\base.py", line 16, in <module>
    from llama_index.indices.query.base import BaseGPTIndexQuery
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\query\base.py", line 18, in <module>
    from llama_index.indices.postprocessor.node import (
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\postprocessor\__init__.py", line 5, in <module>
    from llama_index.indices.postprocessor.node import (
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\postprocessor\node.py", line 11, in <module>
    from llama_index.indices.response.type import ResponseMode
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\response\__init__.py", line 4, in <module>
    from llama_index.indices.response.response_builder import (
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\response\response_builder.py", line 17, in <module>
    from llama_index.indices.common_tree.base import GPTTreeIndexBuilder
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\common_tree\base.py", line 13, in <module>
    from llama_index.indices.service_context import ServiceContext
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\service_context.py", line 6, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\indices\prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 6, in <module>
    from llama_index.llm_predictor.base import (  # noqa: F401
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\llm_predictor\__init__.py", line 4, in <module>
    from llama_index.llm_predictor.base import LLMPredictor
  File "C:\Users\OM-PC-089\AppData\Roaming\Python\Python310\site-packages\llama_index\llm_predictor\base.py", line 12, in <module>
    from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (C:\Users\OM-PC-089\miniconda3\envs\ChatChat\lib\site-packages\langchain\schema\__init__.py)

**Comment by zRzRzRzRzRzRzR** [comment]
安装langchain 0.0.x版本
