### ISSUE TITLE
将docx文档添加到milvus向量库失败

### ISSUE THREAD

**Issue by zhz292** [chatchat-space/Langchain-Chatchat#2597]
**问题描述 / Problem Description**
将docx文档添加到milvus向量库失败

**复现问题的步骤 / Steps to Reproduce**
1.新建milvus向量库
2.上传docx文件
3.添加文件到知识库
4.问题出现 / Problem occurs
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/74390259/4effef80-b2c9-41d3-9591-0f84ec2c6ad7)
2024-01-10 10:30:11 | ERROR | pymilvus.decorators | RPC error: [query], <MilvusException: (code=65535, message=cannot parse expression: pk in ['446895949923776194'], error: value ''4468
95949923776194'' in list cannot be casted to Int64)>, <Time:{'RPC start': '2024-01-10 10:30:11.080996', 'RPC error': '2024-01-10 10:30:11.084653'}>
INFO:     127.0.0.1:63616 - "POST /knowledge_base/search_docs HTTP/1.1" 500 Internal Server Error
2024-01-10 10:30:11,085 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Data\Code\Python\pangu-thbrain-service-python-llm\pangu-thbrain-service-rag\rag\server\knowledge_base\kb_doc_api.py", line 41, in search_docs
    data = kb.list_docs(file_name=file_name, metadata=metadata)
  File "E:\Data\Code\Python\pangu-thbrain-service-python-llm\pangu-thbrain-service-rag\rag\server\knowledge_base\kb_service\base.py", line 214, in list_docs
    doc_info = self.get_doc_by_ids([x["id"]])[0]
  File "E:\Data\Code\Python\pangu-thbrain-service-python-llm\pangu-thbrain-service-rag\rag\server\knowledge_base\kb_service\milvus_kb_service.py", line 28, in get_doc_by_ids
    data_list = self.milvus.col.query(expr=f'pk in {ids}', output_fields=["*"])
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\pymilvus\orm\collection.py", line 925, in query
    return conn.query(
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\pymilvus\decorators.py", line 135, in handler
    raise e from e
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\pymilvus\decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\pymilvus\decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\pymilvus\decorators.py", line 110, in handler
    raise e from e
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\pymilvus\decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\pymilvus\client\grpc_handler.py", line 1330, in query
    check_status(response.status)
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\pymilvus\client\utils.py", line 54, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=cannot parse expression: pk in ['446895949923776194'], error: value ''446895949923776194'' in list cannot be 
casted to Int64)>
2024-01-10 10:30:11.088 Uncaught app exception
Traceback (most recent call last):
  File "E:\SoftWare\anaconda3\envs\langchain\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\Data\Code\Python\pangu-thbrain-service-python-llm\pangu-thbrain-service-rag\rag\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "E:\Data\Code\Python\pangu-thbrain-service-python-llm\pangu-thbrain-service-rag\rag\webui_pages\knowledge_base\knowledge_base.py", line 328, in knowledge_base_page
    data = [{"seq": i+1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
  File "E:\Data\Code\Python\pangu-thbrain-service-python-llm\pangu-thbrain-service-rag\rag\webui_pages\knowledge_base\knowledge_base.py", line 328, in <listcomp>
    data = [{"seq": i+1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
TypeError: string indices must be integers

**环境信息 / Environment Information**
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['qwen-api'] @ cpu
{'api_key': 'sk-********',
 'device': 'auto',
 'embed_model': 'text-embedding-v1',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21006,
 'provider': 'QwenWorker',
 'version': 'qwen-turbo',
 'worker_class': <class 'server.model_workers.qwen.QwenWorker'>}
当前Embbedings模型： qwen-api @ cpu

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by linnnff** [comment]
解决了嘛

**Comment by linnnff** [comment]
我也出现这个问题

**Comment by gli-wish** [comment]
我也出现这个问题
