### ISSUE TITLE
启动网页后报错StreamlitAPIException: Both value and arguments must be of the same type. value has list type. min_value has float type. max_value has float type.

### ISSUE THREAD

**Issue by zyy543370785** [chatchat-space/Langchain-Chatchat#2598]
各位好，网页启动后报错如下，该如何解决：
Traceback (most recent call last):
  File "/Langchain-Chatchat/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/opt/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/opt/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 227, in dialogue_page
    temperature = st.slider("Temperature：", 0.0, 2.0, TEMPERATURE, 0.05)
  File "/Langchain-Chatchat/lib/python3.8/site-packages/streamlit/runtime/metrics_util.py", line 396, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/Langchain-Chatchat/lib/python3.8/site-packages/streamlit/elements/widgets/slider.py", line 339, in slider
    return self._slider(
  File "/Langchain-Chatchat/lib/python3.8/site-packages/streamlit/elements/widgets/slider.py", line 556, in _slider
    raise StreamlitAPIException(
streamlit.errors.StreamlitAPIException: Both value and arguments must be of the same type.
`value` has list type.
`min_value` has float type.
`max_value` has float type.

**Comment by HHY2333** [comment]
是不是把配置文件里TEMPERATURE改成整数了，比如说把TEMPERATURE=0.0写成TEMPERATURE=0了，我刚才报的这个错，改过来就好了
