### ISSUE TITLE
minimax-api    agent-chat对话报错ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by maxusheng123** [chatchat-space/Langchain-Chatchat#2607]
**问题描述 / Problem Description**
minimax-api    agent-chat对话报错ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()    换成qwen-api可以正常访问

langchain-chatchat版本号：v0.2.9

**环境**
# API requirements

langchain==0.0.344
langchain-experimental>=0.0.42
pydantic==1.10.13
fschat>=0.2.33
xformers>=0.0.22.post7
openai>=1.3.6
sentence_transformers
transformers>=4.35.2
torch==2.1.0  ##on Windows system, install the cuda version manually from https://pytorch.org/
torchvision  #on Windows system, install the cuda version manually from https://pytorch.org/
torchaudio  #on Windows system, install the cuda version manually from https://pytorch.org/
fastapi>=0.104
nltk>=3.8.1
uvicorn>=0.24.0.post1
starlette~=0.27.0
unstructured[all-docs]==0.11.0
python-magic-bin; sys_platform == 'win32'
SQLAlchemy==2.0.19
faiss-cpu
accelerate>=0.24.1
spacy>=3.7.2
PyMuPDF
rapidocr_onnxruntime
requests>=2.31.0
pathlib>=1.0.1
pytest>=7.4.3
numexpr>=2.8.7
strsimpy>=0.2.1
markdownify>=0.11.6
tiktoken>=0.5.1
tqdm>=4.66.1
websockets
numpy~=1.24.4
pandas~=2.0.3
einops>=0.7.0
transformers_stream_generator==0.0.4
vllm==0.2.2; sys_platform == "linux"

# Online api libs dependencies

# zhipuai>=1.0.7
# dashscope>=1.10.0
# qianfan>=0.2.0
# volcengine>=1.0.106
# pymilvus>=2.3.3
# psycopg2
# pgvector>=0.2.4

# Agent and Search Tools

arxiv>=2.0.0
youtube-search>=2.1.2
duckduckgo-search>=3.9.9
metaphor-python>=0.1.23

# WebUI requirements

streamlit>=1.29.0
streamlit-option-menu>=0.3.6
streamlit-antd-components>=0.2.3
streamlit-chatbox>=1.1.11
streamlit-modal>=0.1.0
streamlit-aggrid>=0.3.4.post3
httpx[brotli,http2,socks]>=0.25.2
watchdog>=3.0.0

**报错内容**
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/Langchain-Chatchat/server/chat/agent_chat.py", line 493, in agent_chat_iterator
    answer += "工具名称: " + data["tool_name"] + "\n"
KeyError: 'tool_name'
2024-01-10 17:04:47,361 - utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/root/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 1361, in _acall
    next_step_output = await self._atake_next_step(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 1164, in _atake_next_step
    [
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 1164, in <listcomp>
    [
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 1192, in _aiter_next_step
    output = await self.agent.aplan(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 556, in aplan
    output = await self.llm_chain.arun(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 592, in arun
    await self.acall(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 520, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 491, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-01-10 17:04:47,363 - utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by maxusheng123** [comment]
> _🤖_
> 
> 你好 @maxusheng123! 👋 我是[Dosu](https://dosu.dev)，一个人工智能机器人，我可以帮助你解决bugs，回答问题，并成为贡献者。在等待人类维护者的同时，我在这里为你提供帮助。很高兴与你相遇！
> 
> 根据您提供的错误信息，这个问题可能是由于在处理`minimax-api`返回的数据时，某个预期为字典类型的对象实际上是`None`，导致在尝试获取其长度时引发`TypeError`。这可能是由于`minimax-api`返回的数据格式与预期不符，或者在某个阶段没有正确处理`None`值。
> 
> 在Langchain-Chatchat的问题跟踪中，我找到了一些类似的已解决问题，可能对您有所帮助：
> 
> 1. [调用zhipu-api和qwen-api等在线模型时报错TypeError: Caught exception: object of type 'NoneType' has no len()](https://github.com/chatchat-space/Langchain-Chatchat/issues/2062)
> 2. [TypeError: object of type 'NoneType' has no len()](https://github.com/chatchat-space/Langchain-Chatchat/issues/2226)
> 3. [[BUG] mac m1启动后，本地chatGLM6b模型问答报错 utils.py[line:24] - ERROR: object of type 'NoneType' has no len()](https://github.com/chatchat-space/Langchain-Chatchat/issues/2508)
> 
> 这些问题的解决方案主要包括确保GPU内存不满、在CPU上运行模型、安装特定版本的`bitsandbytes`，以及修改`openai.py`文件以打印出错误信息进行进一步诊断。
> 
> 如果这些解决方案不能解决您的问题，我建议您检查`minimax-api`返回的数据，看看是否有可能返回`None`，并在代码中适当地处理这种情况。例如，您可以在尝试获取长度之前检查对象是否为`None`，如果是，则跳过处理或抛出更具体的错误信息。
> 
> 如果您需要进一步的帮助，欢迎提供更多的错误信息或代码片段，以便我们更好地理解和解决问题。
> 
> ## Sources
> * [调用zhipu-api和qwen-api等在线模型时报错TypeError: Caught exception: object of type 'NoneType' has no len()](https://github.com/chatchat-space/Langchain-Chatchat/issues/2062)
> * [TypeError: object of type 'NoneType' has no len()](https://github.com/chatchat-space/Langchain-Chatchat/issues/2226)
> * [[BUG] mac m1启动后，本地chatGLM6b模型问答报错 utils.py[line:24] - ERROR: object of type 'NoneType' has no len()](https://github.com/chatchat-space/Langchain-Chatchat/issues/2508)
> * [server/model_workers/minimax.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/minimax.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Traceback (most recent call last):
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/Langchain-Chatchat/server/chat/agent_chat.py", line 493, in agent_chat_iterator
    answer += "工具名称: " + data["tool_name"] + "\n"
KeyError: 'tool_name'
2024-01-10 18:01:47,329 - utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/root/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 1361, in _acall
    next_step_output = await self._atake_next_step(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 1164, in _atake_next_step
    [
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 1164, in <listcomp>
    [
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 1192, in _aiter_next_step
    output = await self.agent.aplan(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/agents/agent.py", line 556, in aplan
    output = await self.llm_chain.arun(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 592, in arun
    await self.acall(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 521, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "/root/miniconda3/envs/xiaoka_new/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 492, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-01-10 18:01:47,330 - utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

我给openai报错位置打印了chunk，下面是打印的内容，发现只返回到第二轮就报错了，而且第一轮似乎也不正常，我核实了minimax-api的key和group id，都是对的
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/138666362/2e925fa9-80c9-430a-83d9-b281c0dafa34)

{'id': 'chatcmpl-3KgBBAL2CCBrYkpyaW7Hap', 'choices': [{'delta': {'content': None, 'function_call': None, 'role': 'assistant', 'tool_calls': None}, 'finish_reason': None, 'index': 0, 'logprobs': None}], 'created': None, 'model': 'minimax-api', 'object': None, 'system_fingerprint': None}
{'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'error_code': 500, 'text': "minimax-api请求API时发生错误：'USER'"}
