### ISSUE TITLE
轻量部署的时候一直报这个错误

### ISSUE THREAD

**Issue by aixiaozhusogood** [chatchat-space/Langchain-Chatchat#2616]
==============================Langchain-Chatchat Configuration==============================

2024-01-11 10:38:10,120 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-11 10:38:10,121 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 /root/Langchain-Chatchat/logs
2024-01-11 10:43:18,604 - startup.py[line:848] - ERROR: 
2024-01-11 10:43:18,604 - startup.py[line:849] - WARNING: Caught KeyboardInterrupt! Setting stop event...
2024-01-11 10:43:18,605 - startup.py[line:856] - WARNING: Sending SIGKILL to {'zhipu-api': <Process name='api_worker - zhipu-api (7360)' pid=7360 parent=6645 started daemon>, 'qianfan-api': <Process name='api_worker - qianfan-api (7361)' pid=7361 parent=6645 started daemon>}
2024-01-11 10:43:19,203 - startup.py[line:856] - WARNING: Sending SIGKILL to {}
2024-01-11 10:43:19,203 - startup.py[line:856] - WARNING: Sending SIGKILL to <Process name='controller (7155)' pid=7155 parent=6645 stopped exitcode=-SIGKILL daemon>
2024-01-11 10:43:19,204 - startup.py[line:856] - WARNING: Sending SIGKILL to <Process name='openai_api (7359)' pid=7359 parent=6645 started daemon>
2024-01-11 10:43:19,204 - startup.py[line:856] - WARNING: Sending SIGKILL to <Process name='API Server' parent=6645 initial daemon>
Traceback (most recent call last):
  File "/root/Langchain-Chatchat/startup.py", line 883, in <module>
    loop.run_until_complete(start_main_server())
  File "/usr/local/python3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/Langchain-Chatchat/startup.py", line 864, in start_main_server
    p.kill()
  File "/usr/local/python3/lib/python3.9/multiprocessing/process.py", line 140, in kill
    self._popen.kill()
AttributeError: 'NoneType' object has no attribute 'kill'

**Comment by zRzRzRzRzRzRzR** [comment]
KeyboardInterrupt 这是你自己结束的命令吧
