### ISSUE TITLE
单独运行streamlit run webui.py时出现TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by uirlx** [chatchat-space/Langchain-Chatchat#2624]
2024-01-11 09:24:05,102 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-01-11 09:24:05,102 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-01-11 09:24:05,103 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-01-11 09:24:05,207 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-01-11 09:24:05,208 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-01-11 09:24:05,209 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-01-11 09:24:05.209 Uncaught app exception
Traceback (most recent call last):
  File "/home/hanjiale/m/miniconda/envs/LangChain/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/hanjiale/hjl/Private_Chat_GLM/Langchain-Chatchat-master/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/hanjiale/hjl/Private_Chat_GLM/Langchain-Chatchat-master/webui_pages/dialogue/dialogue.py", line 165, in dialogue_page
    running_models = list(api.list_running_models())
TypeError: 'NoneType' object is not iterable

**Comment by zRzRzRzRzRzRzR** [comment]
因为没有运行后端，没有找到对应的模型
