### ISSUE TITLE
访问web时出现404错误

### ISSUE THREAD

**Issue by xzl12080** [chatchat-space/Langchain-Chatchat#2625]
具体代码如下
操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.17.
python版本：3.8.16 (default, Jun 12 2023, 18:09:05) 
[GCC 11.2.0]
项目版本：v0.2.9
langchain版本：0.0.352. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'model/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： text2vec-large-chinese @ cpu
==============================Langchain-Chatchat Configuration==============================

2024-01-11 17:33:54,938 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-11 17:33:54,938 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 /mnt/workspace/Langchain-Chatchat/logs
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
2024-01-11 17:34:01 | INFO | model_worker | Register to controller
2024-01-11 17:34:02 | ERROR | stderr | INFO:     Started server process [2368]
2024-01-11 17:34:02 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-11 17:34:02 | ERROR | stderr | INFO:     Application startup complete.
2024-01-11 17:34:02 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-01-11 17:34:02 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker e0476b21 ...
Loading checkpoint shards:   0%|                                                                                             | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████████▏                                                                        | 1/7 [00:00<00:03,  1.78it/s]
Loading checkpoint shards:  29%|████████████████████████▎                                                            | 2/7 [00:01<00:02,  1.73it/s]
Loading checkpoint shards:  43%|████████████████████████████████████▍                                                | 3/7 [00:01<00:02,  1.75it/s]
Loading checkpoint shards:  57%|████████████████████████████████████████████████▌                                    | 4/7 [00:02<00:01,  1.77it/s]
Loading checkpoint shards:  71%|████████████████████████████████████████████████████████████▋                        | 5/7 [00:02<00:01,  1.76it/s]
Loading checkpoint shards:  86%|████████████████████████████████████████████████████████████████████████▊            | 6/7 [00:03<00:00,  1.75it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.95it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.83it/s]
2024-01-11 17:34:07 | ERROR | stderr | 
2024-01-11 17:34:07 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-01-11 17:34:07 | ERROR | stderr | Traceback (most recent call last):
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
2024-01-11 17:34:07 | ERROR | stderr |     self.run()
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
2024-01-11 17:34:07 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-11 17:34:07 | ERROR | stderr |   File "/mnt/workspace/Langchain-Chatchat/startup.py", line 387, in run_model_worker
2024-01-11 17:34:07 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-11 17:34:07 | ERROR | stderr |   File "/mnt/workspace/Langchain-Chatchat/startup.py", line 215, in create_model_worker_app
2024-01-11 17:34:07 | ERROR | stderr |     worker = ModelWorker(
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-01-11 17:34:07 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/fastchat/model/model_adapter.py", line 337, in load_model
2024-01-11 17:34:07 | ERROR | stderr |     model.to(device)
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2460, in to
2024-01-11 17:34:07 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1160, in to
2024-01-11 17:34:07 | ERROR | stderr |     return self._apply(convert)
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-11 17:34:07 | ERROR | stderr |     module._apply(fn)
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-11 17:34:07 | ERROR | stderr |     module._apply(fn)
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-11 17:34:07 | ERROR | stderr |     module._apply(fn)
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 833, in _apply
2024-01-11 17:34:07 | ERROR | stderr |     param_applied = fn(param)
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1158, in convert
2024-01-11 17:34:07 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-01-11 17:34:07 | ERROR | stderr |   File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
2024-01-11 17:34:07 | ERROR | stderr |     torch._C._cuda_init()
2024-01-11 17:34:07 | ERROR | stderr | RuntimeError: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by zRzRzRzRzRzRzR** [comment]
untimeError: The NVIDIA driver on your system is too old (found version 11080). 
显卡驱动不对

**Comment by xzl12080** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
root@dsw-303649-97c5645f4-b2fk9:/mnt/workspace# python startup.py -a
python: can't open file 'startup.py': [Errno 2] No such file or directory
root@dsw-303649-97c5645f4-b2fk9:/mnt/workspace# cd ./Langchain-Chatchat
root@dsw-303649-97c5645f4-b2fk9:/mnt/workspace/Langchain-Chatchat# python startup.py -a
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
但是我明明看它的版本是11.8，pytorch版本是2.1.2，应该是适配的，不知道为什么启动项目的时候它检查到的版本变成了11.08

**Comment by Sapphire025** [comment]
> @nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0 root@dsw-303649-97c5645f4-b2fk9:/mnt/workspace# python startup.py -a python: can't open file 'startup.py': [Errno 2] No such file or directory root@dsw-303649-97c5645f4-b2fk9:/mnt/workspace# cd ./Langchain-Chatchat root@dsw-303649-97c5645f4-b2fk9:/mnt/workspace/Langchain-Chatchat# python startup.py -a /opt/conda/lib/python3.8/site-packages/torch/cuda/**init**.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.) 但是我明明看它的版本是11.8，pytorch版本是2.1.2，应该是适配的，不知道为什么启动项目的时候它检查到的版本变成了11.08 @zRzRzRzRzRzRzR @

同样的问题 请问解决了吗
