### ISSUE TITLE
[BUG] 创建向量库报connection refused 500 错误

### ISSUE THREAD

**Issue by zolibra** [chatchat-space/Langchain-Chatchat#2645]
问题描述 / Problem Description 在使用 langchain-ChatGLM 进行操作时，遇到了 RemoteProtocolError: Server disconnected without sending a response. 的错误。

复现问题的步骤 / Steps to Reproduce
1. python startup.sh -a 
2. 创建向量库

预期的结果 / Expected Result 预期服务器能正常响应请求，不会出现断开连接的情况。

实际结果 / Actual Result 实际上，服务器在没有发送响应的情况下断开了连接，导致了 RemoteProtocolError: Server disconnected without sending a response. 的错误。

环境信息 / Environment Information

操作系统：macOS-10.16-x86_64-i386-64bit
Python 版本：3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:23:49) [Clang 15.0.7 ]
项目版本：v0.2.9
langchain 版本：0.2.34
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['baichuan2-7b'] @ mps
当前Embbedings模型： bge-small-zh-v1.5 @ mps
服务端运行信息：
OpenAI API Server: [http://127.0.0.0:20000/v1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
Chatchat API Server: [http://127.0.0.0:7861](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
Chatchat WEBUI Server: [http://0.0.0.0:8501](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
附加信息 / Additional Information 错误发生在执行 /knowledge_base/create_knowledge_base 请求时。具体的错误堆栈信息如下：

```
2024-01-13 09:26:02,369 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /Users/didi/Work/projects/llm/model/BAAI/bge-small-zh-v1.5 2024-01-13 09:26:03,538 - base.py[line:40] - INFO: thread 2004633 结束操作：('bge-small-zh-v1.5', 'mps')。初始化 Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1.73it/s] 2024-01-13 09:26:04,545 - loader.py[line:64] - INFO: Loading faiss. 2024-01-13 09:26:04,638 - loader.py[line:66] - INFO: Successfully loaded faiss.
Traceback (most recent call last):
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 226, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.
```

更多报错
```
Traceback (most recent call last):
  File "<user_path>/Work/projects/opensource/Langchain-Chatchat/webui_pages/utils.py", line 92, in post
    return self.client.post(url, data=data, json=json, **kwargs)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_client.py", line 1132, in post
    return self.request(
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "<user_path>/opt/anaconda3/envs/llm/lib/python3.8/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 61] Connection refused
2024-01-13 09:26:04,669 - utils.py[line:222] - ERROR: AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
Traceback (most recent call last):
  File "<user_path>/Work/projects/opensource/Langchain-Chatchat/webui_pages/utils.py", line 218, in to_json
    return r.json()
AttributeError: 'NoneType' object has no attribute 'json'
```

**Comment by zRzRzRzRzRzRzR** [comment]
估计知识库没有成功初始化，所以请求不到
