### ISSUE TITLE
startup.py出错

### ISSUE THREAD

**Issue by KID-max** [chatchat-space/Langchain-Chatchat#2653]
Process API Server:
Traceback (most recent call last):
  File "C:\Users\songyang\.conda\envs\chat2\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\songyang\.conda\envs\chat2\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Langchain-Chatchat\startup.py", line 436, in run_api_server
    app = create_app(run_mode=run_mode)
  File "D:\Langchain-Chatchat\server\api.py", line 51, in create_app
    mount_app_routes(app, run_mode=run_mode)
  File "D:\Langchain-Chatchat\server\api.py", line 77, in mount_app_routes
    mount_knowledge_routes(app)
  File "D:\Langchain-Chatchat\server\api.py", line 142, in mount_knowledge_routes
    from server.chat.agent_chat import agent_chat
  File "D:\Langchain-Chatchat\server\chat\agent_chat.py", line 4, in <module>
    from server.agent.tools_select import tools, tool_names
  File "D:\Langchain-Chatchat\server\agent\tools_select.py", line 7, in <module>
    Tool.from_function(
  File "C:\Users\songyang\.conda\envs\chat2\lib\site-packages\langchain_core\tools.py", line 572, in from_function
    return cls(
  File "C:\Users\songyang\.conda\envs\chat2\lib\site-packages\langchain_core\tools.py", line 552, in __init__
    super(Tool, self).__init__(
  File "C:\Users\songyang\.conda\envs\chat2\lib\site-packages\langchain_core\load\serializable.py", line 107, in __init__
    super().__init__(**kwargs)
  File "C:\Users\songyang\.conda\envs\chat2\lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Tool
args_schema
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)

**Comment by KID-max** [comment]
这是tools_select.py里面的代码怎么解决上述问题呢
from langchain.tools import Tool
from server.agent.tools import *

## 请注意，如果你是为了使用AgentLM，在这里，你应该使用英文版本。

tools = [
    Tool.from_function(
        func=calculate,
        name="calculate",
        description="Useful for when you need to answer questions about simple calculations",
        args_schema=CalculatorInput,
    ),
    Tool.from_function(
        func=arxiv,
        name="arxiv",
        description="A wrapper around Arxiv.org for searching and retrieving scientific articles in various fields.",
        args_schema=ArxivInput,
    ),
    Tool.from_function(
        func=weathercheck,
        name="weather_check",
        description="",
        args_schema=WhetherSchema,
    ),
    Tool.from_function(
        func=shell,
        name="shell",
        description="Use Shell to execute Linux commands",
        args_schema=ShellInput,
    ),
    Tool.from_function(
        func=search_knowledgebase_complex,
        name="search_knowledgebase_complex",
        description="Use Use this tool to search local knowledgebase and get information",
        args_schema=KnowledgeSearchInput,
    ),
    Tool.from_function(
        func=search_internet,
        name="search_internet",
        description="Use this tool to use bing search engine to search the internet",
        args_schema=SearchInternetInput,
    ),
    Tool.from_function(
        func=wolfram,
        name="Wolfram",
        description="Useful for when you need to calculate difficult formulas",
        args_schema=WolframInput,
    ),
    Tool.from_function(
        func=search_youtube,
        name="search_youtube",
        description="use this tools to search youtube videos",
        args_schema=YoutubeInput,
    ),
]

tool_names = [tool.name for tool in tools]

**Comment by zRzRzRzRzRzRzR** [comment]
所以这个报错好像不是模型的问题吧，我好像没有遇到，你试试删掉schma后还有没有

**Comment by XienXX** [comment]
我也遇到了这个问题，同问

**Comment by ruthy-wei** [comment]
> 我也遇到了这个问题，同问

你解决了嘛？我也遇到同样的问题

**Comment by XienXX** [comment]
> > 我也遇到了这个问题，同问
> 
> 你解决了嘛？我也遇到同样的问题

我直接切linux了

**Comment by lhyscau** [comment]
删除pydantic，重装对应版本即可
