### ISSUE TITLE
aws ec2云服务器，无gpu能跑起来吗

### ISSUE THREAD

**Issue by wuhaipinm** [chatchat-space/Langchain-Chatchat#2664]
**问题描述 / Problem Description**
aws ec2云服务器，启动的时候报错。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python3 startup.py -a
2. 问题出现 / 
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

配置已经修改成CPU：
EMBEDDING_DEVICE = "cpu"

LLM_DEVICE = "cpu"

日志如下：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.2.0-1017-aws-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cpu
==============================Langchain-Chatchat Configuration==============================

2024-01-15 03:06:05,351 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-15 03:06:05,352 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 /root/Langchain-Chatchat/logs
2024-01-15 03:06:26 | INFO | model_worker | Register to controller
2024-01-15 03:06:27 | ERROR | stderr | INFO:     Started server process [16660]
2024-01-15 03:06:27 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-15 03:06:27 | ERROR | stderr | INFO:     Application startup complete.
2024-01-15 03:06:27 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-01-15 03:06:29 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 98e8dc42 ...
Loading checkpoint shards:   0%|                                                                                                                                                         | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████████████████▋                                                                                                                            | 1/7 [00:38<03:48, 38.16s/it]
Loading checkpoint shards:  29%|█████████████████████████████████████████▍                                                                                                       | 2/7 [01:23<03:30, 42.17s/it]
Loading checkpoint shards:  43%|██████████████████████████████████████████████████████████████▏                                                                                  | 3/7 [02:08<02:54, 43.65s/it]
Loading checkpoint shards:  57%|██████████████████████████████████████████████████████████████████████████████████▊                                                              | 4/7 [02:52<02:11, 43.89s/it]
Loading checkpoint shards:  71%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 5/7 [03:39<01:29, 44.92s/it]
Loading checkpoint shards:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 6/7 [04:13<00:41, 41.15s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [04:33<00:00, 34.22s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [04:33<00:00, 39.05s/it]
2024-01-15 03:11:03 | ERROR | stderr | 
2024-01-15 03:11:04 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-01-15 03:11:04 | ERROR | stderr | Traceback (most recent call last):
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-01-15 03:11:04 | ERROR | stderr |     self.run()
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-01-15 03:11:04 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-15 03:11:04 | ERROR | stderr |   File "/root/Langchain-Chatchat/startup.py", line 387, in run_model_worker
2024-01-15 03:11:04 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-15 03:11:04 | ERROR | stderr |   File "/root/Langchain-Chatchat/startup.py", line 215, in create_model_worker_app
2024-01-15 03:11:04 | ERROR | stderr |     worker = ModelWorker(
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-01-15 03:11:04 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 337, in load_model
2024-01-15 03:11:04 | ERROR | stderr |     model.to(device)
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2460, in to
2024-01-15 03:11:04 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1160, in to
2024-01-15 03:11:04 | ERROR | stderr |     return self._apply(convert)
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-15 03:11:04 | ERROR | stderr |     module._apply(fn)
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-15 03:11:04 | ERROR | stderr |     module._apply(fn)
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
2024-01-15 03:11:04 | ERROR | stderr |     module._apply(fn)
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 833, in _apply
2024-01-15 03:11:04 | ERROR | stderr |     param_applied = fn(param)
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1158, in convert
2024-01-15 03:11:04 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-01-15 03:11:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
2024-01-15 03:11:04 | ERROR | stderr |     torch._C._cuda_init()
2024-01-15 03:11:04 | ERROR | stderr | RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by zRzRzRzRzRzRzR** [comment]
装cpu的torch
