### ISSUE TITLE
无法访问chachat的api

### ISSUE THREAD

**Issue by wuliaodeashuai** [chatchat-space/Langchain-Chatchat#2670]
(python3.10_langchain_chatchat) F:\python_langchian_xiangmu\Langchain-Chatchat-master>python startup.py --all-api

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9
langchain版本：0.0.352. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-1_8B-Chat', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'F:\\python_langchian_xiangmu\\Langchain-Chatchat-master\\datast\\model\\qwen8B_chat',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-01-16 08:57:43,825 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-16 08:57:43,826 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 F:\python_langchian_xiangmu\Langchain-Chatchat-master\logs
2024-01-16 08:57:48 | INFO | model_worker | Register to controller
2024-01-16 08:57:48 | ERROR | stderr | INFO:     Started server process [4168]
2024-01-16 08:57:48 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-16 08:57:48 | ERROR | stderr | INFO:     Application startup complete.
2024-01-16 08:57:48 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2024-01-16 08:57:48 | INFO | model_worker | Loading the model ['Qwen-1_8B-Chat'] on worker 031ca01f ...
2024-01-16 08:57:49 | WARNING | transformers_modules.qwen8B_chat.modeling_qwen | Try importing flash-attention for faster inference...
2024-01-16 08:57:49 | WARNING | transformers_modules.qwen8B_chat.modeling_qwen | Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree
/main/csrc/rotary
2024-01-16 08:57:49 | WARNING | transformers_modules.qwen8B_chat.modeling_qwen | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attentio
n/tree/main/csrc/layer_norm
2024-01-16 08:57:49 | WARNING | transformers_modules.qwen8B_chat.modeling_qwen | Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards:   0%|                                                                                                                                                                                 | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 1/2 [00:00<00:00,  1.63it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.73it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.72it/s]
2024-01-16 08:57:50 | ERROR | stderr |
2024-01-16 08:57:51 | INFO | model_worker | Register to controller
INFO:     Started server process [20904]
INFO:     Waiting for application startup.

INFO:     Application startup complete.

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9
langchain版本：0.0.352. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-1_8B-Chat', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'F:\\python_langchian_xiangmu\\Langchain-Chatchat-master\\datast\\model\\qwen8B_chat',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
    Chatchat  API  Server: http://127.0.0.1:7861
==============================Langchain-Chatchat Configuration==============================

INFO:     127.0.0.1:63636 - "POST /v1 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:63646 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:63654 - "POST /v1/chat/completions/chat/completions HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:63704 - "POST /v1 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:63707 - "POST /v1 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:63711 - "POST /v1 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:63749 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:63775 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found

访问代码：import openai
openai.api_key = "EMPTY" # Not support yet
openai.api_base = "http://127.0.0.1:7861/v1"

model = "Qwen-1_8B-Chat"

# create a chat completion
completion = openai.ChatCompletion.create(
  model=model,
  messages=[{"role": "user", "content": "你好"}]
)
# print the completion
print(completion.choices[0].message.content)

model_config中设置为：LLM_MODELS = ["Qwen-1_8B-Chat", "zhipu-api", "openai-api"] 

报错：Traceback (most recent call last):
  File "D:\anaconda\envs\python3.8_ner\lib\site-packages\openai\api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Admin/PycharmProjects/1/2.py", line 8, in <module>
    completion = openai.ChatCompletion.create(
  File "D:\anaconda\envs\python3.8_ner\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\anaconda\envs\python3.8_ner\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\anaconda\envs\python3.8_ner\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\anaconda\envs\python3.8_ner\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "D:\anaconda\envs\python3.8_ner\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
  File "D:\anaconda\envs\python3.8_ner\lib\site-packages\openai\api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404)

**Comment by zRzRzRzRzRzRzR** [comment]
API不是这么调用的，查看7860端口查看使用用法
