### ISSUE TITLE
[BUG] 使用rerank模型后回答报错

### ISSUE THREAD

**Issue by cuijianxxx0** [chatchat-space/Langchain-Chatchat#2678]
**问题描述 / Problem Description**
使用rerank模型后回答报错

**复现问题的步骤 / Steps to Reproduce**
1. 在model_config.py中的USE_RERANKER改为True
2. 下载bge-reranker-large模型，并修改配置的模型路径
3. 重启服务
4. 上传文档
5. 请求服务
6. 出现报错：API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**预期的结果 / Expected Result**
预期对挑选的doc排序后回答结果

**实际结果 / Actual Result**
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): baichuan2-13b-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:ubuntu
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
有的请求可以回复，有的请求报错，看起来像是短一点的没问题，稍微长一点的请求就报错

报错日志如下：
2024-01-16 15:04:46,210 - embeddings_api.py[line:40] - ERROR: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/cuijian/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/cuijian/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/cuijian/.local/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/cuijian/.local/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/home/cuijian/.local/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
    async for data in self.body_iterator:
  File "/storage/cuijian/Langchain-Chatchat-18501/server/chat/knowledge_base_chat.py", line 81, in knowledge_base_chat_iterator
    docs = await run_in_threadpool(search_docs,
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/storage/cuijian/Langchain-Chatchat-18501/server/knowledge_base/kb_doc_api.py", line 38, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "/storage/cuijian/Langchain-Chatchat-18501/server/knowledge_base/kb_service/base.py", line 181, in search_docs
   docs = self.do_search(query, top_k, score_threshold)
  File "/storage/cuijian/Langchain-Chatchat-18501/server/knowledge_base/kb_service/faiss_kb_service.py", line 66, in do_search
    yield
  File "/home/cuijian/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 110, in __iter__
    for part in self._httpcore_stream:
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 361, in __iter__
    for part in self._stream:
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 337, in __iter__
    raise exc
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 329, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 198, in _receive_response_body
    event = self._receive_event(timeout=timeout)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/home/xianzb/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/xianzb/anaconda3/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/cuijian/Langchain-Chatchat-18501/webui_pages/utils.py", line 165, in ret_sync
    for chunk in r.iter_text(None):
  File "/home/cuijian/.local/lib/python3.10/site-packages/httpx/_models.py", line 849, in iter_text
    for byte_content in self.iter_bytes():
  File "/home/cuijian/.local/lib/python3.10/site-packages/httpx/_models.py", line 828, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/home/cuijian/.local/lib/python3.10/site-packages/httpx/_models.py", line 886, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/home/cuijian/.local/lib/python3.10/site-packages/httpx/_client.py", line 123, in __iter__
    for chunk in self._stream:
  File "/home/cuijian/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 109, in __iter__
    with map_httpcore_exceptions():
  File "/home/xianzb/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/cuijian/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**Comment by zRzRzRzRzRzRzR** [comment]
2024-01-16 15:04:46,210 - embeddings_api.py[line:40] - ERROR: CUDA error: device-side assert triggered这个大概率是你模型或者显卡的问题，导致了越界
