### ISSUE TITLE
ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by AnitaSherry** [chatchat-space/Langchain-Chatchat#2680]
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
`
(sakura) [root@localhost My-Langchain-Chatchat]# python startup.py 
2024-01-16 16:27:24,797 - utils.py[line:551] - WARNING: npu is available, device = npu
2024-01-16 16:27:30,457 - utils.py[line:551] - WARNING: npu is available, device = npu

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.10.0-60.118.0.145.oe2203.aarch64-aarch64-with-glibc2.34.
python版本：3.9.1 (default, Mar 15 2021, 21:15:48) 
[GCC 10.2.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-16 16:27:31,147 - utils.py[line:527] - WARNING: npu is available, device = npu
当前启动的LLM模型：['chatglm3-6b'] @ npu
2024-01-16 16:27:31,148 - utils.py[line:527] - WARNING: npu is available, device = npu
{'device': 'npu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/HwHiAiUser/models/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
2024-01-16 16:27:31,148 - utils.py[line:551] - WARNING: npu is available, device = npu
当前Embbedings模型： bge-large-zh-v1.5 @ npu
==============================Langchain-Chatchat Configuration==============================

2024-01-16 16:27:42 | ERROR | stderr | INFO:     Started server process [901821]
2024-01-16 16:27:42 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-16 16:27:42 | ERROR | stderr | INFO:     Application startup complete.
2024-01-16 16:27:42 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)

Traceback (most recent call last):
  File "/usr/local/Ascend/nnae/latest/python/site-packages/te_fusion/parallel_compilation.py", line 1031, in init_multi_process_env
    res = compiler.start()
  File "/usr/local/Ascend/nnae/latest/python/site-packages/te_fusion/parallel_compilation.py", line 622, in start
    worker.start()
  File "/home/anaconda3/envs/sakura/lib/python3.9/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
torch && torch_npu import successfully
2024-01-16 16:27:56 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker e46154c1 ...
2024-01-16 16:27:56 | ERROR | stderr | /home/anaconda3/envs/sakura/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:124: RuntimeWarning: torch.jit.script will be disabled by transfer_to_npu, which currently does not support it, if you need to enable torch.jit.script, please do not use transfer_to_npu.
2024-01-16 16:27:56 | ERROR | stderr |   warnings.warn(msg, RuntimeWarning)
Loading checkpoint shards:   0%|                                                                                    | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|██████████▊                                                                 | 1/7 [00:01<00:11,  1.99s/it]
Loading checkpoint shards:  29%|█████████████████████▋                                                      | 2/7 [00:03<00:09,  1.95s/it]
Loading checkpoint shards:  43%|████████████████████████████████▌                                           | 3/7 [00:06<00:08,  2.06s/it]
Loading checkpoint shards:  57%|███████████████████████████████████████████▍                                | 4/7 [00:07<00:05,  1.99s/it]
Loading checkpoint shards:  71%|██████████████████████████████████████████████████████▎                     | 5/7 [00:10<00:04,  2.07s/it]
Loading checkpoint shards:  86%|█████████████████████████████████████████████████████████████████▏          | 6/7 [00:12<00:02,  2.12s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████| 7/7 [00:13<00:00,  1.82s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████| 7/7 [00:13<00:00,  1.95s/it]
2024-01-16 16:28:10 | ERROR | stderr | 
2024-01-16 16:28:20 | INFO | model_worker | Register to controller
2024-01-16 16:28:20 | ERROR | stderr | /home/HwHiAiUser/work/My-Langchain-Chatchat/startup.py:278: DeprecationWarning:
2024-01-16 16:28:20 | ERROR | stderr |         on_event is deprecated, use lifespan event handlers instead.
2024-01-16 16:28:20 | ERROR | stderr | 
2024-01-16 16:28:20 | ERROR | stderr |         Read more about it in the
2024-01-16 16:28:20 | ERROR | stderr |         [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
2024-01-16 16:28:20 | ERROR | stderr | 
2024-01-16 16:28:20 | ERROR | stderr |   @app.on_event("startup")
2024-01-16 16:28:20 | ERROR | stderr | /home/anaconda3/envs/sakura/lib/python3.9/site-packages/fastapi/applications.py:4495: DeprecationWarning:
2024-01-16 16:28:20 | ERROR | stderr |         on_event is deprecated, use lifespan event handlers instead.
2024-01-16 16:28:20 | ERROR | stderr | 
2024-01-16 16:28:20 | ERROR | stderr |         Read more about it in the
2024-01-16 16:28:20 | ERROR | stderr |         [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
2024-01-16 16:28:20 | ERROR | stderr | 
2024-01-16 16:28:20 | ERROR | stderr |   return self.router.on_event(event_type)

Traceback (most recent call last):
  File "/usr/local/Ascend/nnae/latest/python/site-packages/te_fusion/parallel_compilation.py", line 1031, in init_multi_process_env
    res = compiler.start()
  File "/usr/local/Ascend/nnae/latest/python/site-packages/te_fusion/parallel_compilation.py", line 622, in start
    worker.start()
  File "/home/anaconda3/envs/sakura/lib/python3.9/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children

/home/HwHiAiUser/work/My-Langchain-Chatchat/startup.py:278: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @app.on_event("startup")
/home/anaconda3/envs/sakura/lib/python3.9/site-packages/fastapi/applications.py:4495: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  return self.router.on_event(event_type)
INFO:     Started server process [904138]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
2024-01-16 16:28:49,018 - utils.py[line:551] - WARNING: npu is available, device = npu
2024-01-16 16:28:49,728 - utils.py[line:527] - WARNING: npu is available, device = npu

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.10.0-60.118.0.145.oe2203.aarch64-aarch64-with-glibc2.34.
python版本：3.9.1 (default, Mar 15 2021, 21:15:48) 
[GCC 10.2.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-16 16:28:49,758 - utils.py[line:527] - WARNING: npu is available, device = npu
当前启动的LLM模型：['chatglm3-6b'] @ npu
2024-01-16 16:28:49,759 - utils.py[line:527] - WARNING: npu is available, device = npu
{'device': 'npu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/HwHiAiUser/models/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
2024-01-16 16:28:49,759 - utils.py[line:551] - WARNING: npu is available, device = npu
当前Embbedings模型： bge-large-zh-v1.5 @ npu

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2024-01-16 16:29:11,474 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:43504 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-16 16:29:11,478 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-16 16:29:11,596 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:43504 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-16 16:29:11,598 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:43504 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-01-16 16:29:11,614 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-01-16 16:29:15,127 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2024-01-16 16:29:15,127 - utils.py[line:527] - WARNING: npu is available, device = npu
INFO:     127.0.0.1:43520 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-16 16:29:15,129 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-16 16:29:15,144 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:43520 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-16 16:29:15,145 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:43520 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-01-16 16:29:15,166 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:43520 - "POST /chat/chat HTTP/1.1" 200 OK
2024-01-16 16:29:15,178 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.1.0 and will be removed in 0.2.0. Use langchain_openai.ChatOpenAI instead.
  warn_deprecated(
2024-01-16 16:29:15 | INFO | stdout | INFO:     127.0.0.1:56666 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-16 16:29:15,455 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
{'id': 'chatcmpl-38RnMaK7bhgreYemK8ty2a', 'choices': [{'delta': {'content': None, 'function_call': None, 'role': 'assistant', 'tool_calls': None}, 'finish_reason': None, 'index': 0, 'logprobs': None}], 'created': None, 'model': 'chatglm3-6b', 'object': None, 'system_fingerprint': None}
2024-01-16 16:29:15 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
{'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'text': '**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(allocate:/usr1/02/workspace/j_vqN6BFvg/pytorch/torch_npu/csrc/core/npu/NPUCachingAllocator.cpp:1406 NPU error, error code is 107002\n[Error]: The context is empty.\n        Check whether acl.rt.set_context or acl.rt.set_device is called.\nEE1001: The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]\n        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n        TraceBack (most recent call last):\n        ctx is NULL![FUNC:GetDevErrMsg][FILE:api_impl.cc][LINE:4290]\n        The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]\n)', 'error_code': 50001}
2024-01-16 16:29:15,484 - utils.py[line:25] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/HwHiAiUser/work/My-Langchain-Chatchat/server/utils.py", line 23, in wrap_done
    await fn
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain_community/chat_models/openai.py", line 521, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "/home/anaconda3/envs/sakura/lib/python3.9/site-packages/langchain_community/chat_models/openai.py", line 492, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-01-16 16:29:15,485 - utils.py[line:28] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
`

**Comment by zRzRzRzRzRzRzR** [comment]
{'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'text': 'NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.\n\n(allocate:/usr1/02/workspace/j_vqN6BFvg/pytorch/torch_npu/csrc/core/npu/NPUCachingAllocator.cpp:1406 NPU error, error code is 107002\n[Error]: The context is empty.\n Check whether acl.rt.set_context or acl.rt.set_device is called.\nEE1001: The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]\n Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n TraceBack (most recent call last):\n ctx is NULL![FUNC:GetDevErrMsg][FILE:api_impl.cc][LINE:4290]\n The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer 
运行的时候出错了，所以没有请求到，检查运行无误在提出issue

**Comment by Buezw** [comment]
torch版本问题
