### ISSUE TITLE
[BUG] 启动WebUI后，在页面聊天，后台报错

### ISSUE THREAD

**Issue by buctwp** [chatchat-space/Langchain-Chatchat#2716]
**问题描述 / Problem Description**
启动WebUI后，在页面聊天，后台报错。

**复现问题的步骤 / Steps to Reproduce**
1. 执行  python startup.py -a
2. 访问 http://0.0.0.0:8501
3. 输入任意对话内容，后发送
4. 页面无法显示大模型回复的内容。

**预期的结果 / Expected Result**
页面能显示大模型回复的内容。能正常对话

**实际结果 / Actual Result**
页面不能显示大模型回复的内容。不能正常对话

**环境信息 / Environment Information**
- langchain-ChatChat
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-1_8B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：faiss 
- 操作系统及版本 : Ubuntu 22.0
- Python 版本 / Python version: 3.10

**附加信息 / Additional Information**
控制台报错如下：

received input message:
{'conversation_id': 'b16533b3ce26493e8d38683e79376764',
 'history': [],
 'history_len': -1,
 'max_tokens': None,
 'model_name': 'chatglm2-6b-int4',
 'prompt_name': 'default',
 'query': '测试',
 'stream': True,
 'temperature': 0.1}
INFO:     127.0.0.1:40584 - "POST /chat/chat HTTP/1.1" 200 OK
2024-01-18 21:08:13,085 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
2024-01-18 21:08:13,087 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-18 21:08:13,096 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-01-18 21:08:13,318 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-01-18 21:08:13,331 - _base_client.py[line:1456] - INFO: Retrying request to /chat/completions in 0.794364 seconds
2024-01-18 21:08:14,127 - _base_client.py[line:1456] - INFO: Retrying request to /chat/completions in 1.532651 seconds
2024-01-18 21:08:15,663 - utils.py[line:24] - ERROR: Connection error.
Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 487, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 411, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_readers.py", line 100, in maybe_read_from_SEND_RESPONSE_server
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 133, in handle_async_request
    raise exc
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: illegal request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1367, in _request
    response = await self._client.send(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: illegal request line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 487, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 411, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_readers.py", line 100, in maybe_read_from_SEND_RESPONSE_server
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 133, in handle_async_request
    raise exc
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: illegal request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1367, in _request
    response = await self._client.send(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: illegal request line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 487, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_connection.py", line 411, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/h11/_readers.py", line 100, in maybe_read_from_SEND_RESPONSE_server
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 133, in handle_async_request
    raise exc
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: illegal request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1367, in _request
    response = await self._client.send(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: illegal request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpt/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 101, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1291, in create
    return await self._post(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1578, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1339, in request
    return await self._request(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1391, in _request
    return await self._retry_request(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1460, in _retry_request
    return await self._request(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1391, in _request
    return await self._retry_request(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1460, in _retry_request
    return await self._request(
  File "/home/gpt/Langchain-Chatchat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1401, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
2024-01-18 21:08:15,668 - utils.py[line:27] - ERROR: APIConnectionError: Caught exception: Connection error.

**Comment by buctwp** [comment]
抱歉打扰，排查发现todesk程序占用了20000端口，在server_config.py中将FSCHAT_OPENAI_API的端口改为30000，问题即解决。
