### ISSUE TITLE
使用百川模型出错[BUG] 

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#2717]
环境如下：
操作系统：Linux-6.5.0-14-generic-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.34
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Baichuan2-7B-Chat-4bits'] @ cuda
{'device': 'cuda',
 'gpus': '0',
 'host': '10.244.4.81',
 'infer_turbo': False,
 'max_gpu_memory': '12GiB',
 'model_path': '/home/brother/models/Baichuan2-7B-Chat-4bits',
 'model_path_exists': True,
 'num_gpus': 1,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
初始化一切正常启动，随便提一个问题就出错了。错误log如下：
2024-01-19 10:24:58,494 - _client.py[line:1013] - INFO: HTTP Request: POST http://10.244.4.81:7861/chat/chat "HTTP/1.1 200 OK"
2024-01-19 10:24:58 | INFO | stdout | INFO:     10.244.4.81:59298 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-19 10:24:58,547 - _client.py[line:1729] - INFO: HTTP Request: POST http://10.244.4.81:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-19 10:24:58 | INFO | httpx | HTTP Request: POST http://10.244.4.81:20002/worker_generate_stream "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/brother/myenv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/brother/myenv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/brother/myenv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/brother/myenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "/home/brother/myenv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/brother/myenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/brother/myenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/brother/myenv/lib/python3.10/site-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
  File "/home/brother/myenv/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 109, in generate_stream_gate
    for output in self.generate_stream_func(
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/brother/myenv/lib/python3.10/site-packages/fastchat/serve/inference.py", line 132, in generate_stream
    out = model(input_ids=start_ids, use_cache=True)
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/brother/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 685, in forward
    outputs = self.model(
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/brother/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 461, in forward
    layer_outputs = decoder_layer(
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/brother/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 273, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/brother/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 205, in forward
    proj = self.W_pack(hidden_states)
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/brother/myenv/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 256, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/home/brother/myenv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 577, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "/home/brother/myenv/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/brother/myenv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 516, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)
  File "/home/brother/myenv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1017, in dequantize_4bit
    absmax = quant_state.absmax
AttributeError: 'list' object has no attribute 'absmax'
2024-01-19 10:24:58 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-01-19 10:24:58 | ERROR | stderr | Traceback (most recent call last):
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
2024-01-19 10:24:58 | ERROR | stderr |     yield
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 209, in _receive_event
2024-01-19 10:24:58 | ERROR | stderr |     event = self._h11_state.next_event()
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
2024-01-19 10:24:58 | ERROR | stderr |     event = self._extract_next_receive_event()
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
2024-01-19 10:24:58 | ERROR | stderr |     event = self._reader.read_eof()  # type: ignore[attr-defined]
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/h11/_readers.py", line 204, in read_eof
2024-01-19 10:24:58 | ERROR | stderr |     raise RemoteProtocolError(
2024-01-19 10:24:58 | ERROR | stderr | h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-01-19 10:24:58 | ERROR | stderr |
2024-01-19 10:24:58 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-01-19 10:24:58 | ERROR | stderr |
2024-01-19 10:24:58 | ERROR | stderr | Traceback (most recent call last):
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
2024-01-19 10:24:58 | ERROR | stderr |     yield
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_transports/default.py", line 249, in __aiter__
2024-01-19 10:24:58 | ERROR | stderr |     async for part in self._httpcore_stream:
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
2024-01-19 10:24:58 | ERROR | stderr |     async for part in self._stream:
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
2024-01-19 10:24:58 | ERROR | stderr |     raise exc
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
2024-01-19 10:24:58 | ERROR | stderr |     async for chunk in self._connection._receive_response_body(**kwargs):
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
2024-01-19 10:24:58 | ERROR | stderr |     event = await self._receive_event(timeout=timeout)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 208, in _receive_event
2024-01-19 10:24:58 | ERROR | stderr |     with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
2024-01-19 10:24:58 | ERROR | stderr |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
2024-01-19 10:24:58 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-01-19 10:24:58 | ERROR | stderr |     raise to_exc(exc) from exc
2024-01-19 10:24:58 | ERROR | stderr | httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-01-19 10:24:58 | ERROR | stderr |
2024-01-19 10:24:58 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-01-19 10:24:58 | ERROR | stderr |
2024-01-19 10:24:58 | ERROR | stderr | Traceback (most recent call last):
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-01-19 10:24:58 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     raise exc
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     await self.app(scope, receive, send)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     raise exc
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     await self.app(scope, receive, sender)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-01-19 10:24:58 | ERROR | stderr |     await self.app(scope, receive, send)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
2024-01-19 10:24:58 | ERROR | stderr |     await response(scope, receive, send)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2024-01-19 10:24:58 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2024-01-19 10:24:58 | ERROR | stderr |     raise exceptions[0]
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2024-01-19 10:24:58 | ERROR | stderr |     await func()
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
2024-01-19 10:24:58 | ERROR | stderr |     async for chunk in self.body_iterator:
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 472, in chat_completion_stream_generator
2024-01-19 10:24:58 | ERROR | stderr |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 657, in generate_completion_stream
2024-01-19 10:24:58 | ERROR | stderr |     async for raw_chunk in response.aiter_raw():
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_models.py", line 990, in aiter_raw
2024-01-19 10:24:58 | ERROR | stderr |     async for raw_stream_bytes in self.stream:
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_client.py", line 146, in __aiter__
2024-01-19 10:24:58 | ERROR | stderr |     async for chunk in self._stream:
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_transports/default.py", line 248, in __aiter__
2024-01-19 10:24:58 | ERROR | stderr |     with map_httpcore_exceptions():
2024-01-19 10:24:58 | ERROR | stderr |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
2024-01-19 10:24:58 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2024-01-19 10:24:58 | ERROR | stderr |   File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
2024-01-19 10:24:58 | ERROR | stderr |     raise mapped_exc(message) from exc
2024-01-19 10:24:58 | ERROR | stderr | httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-01-19 10:24:58,801 - utils.py[line:24] - ERROR: peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
  File "/home/brother/myenv/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/home/brother/myenv/lib/python3.10/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
  File "/home/brother/myenv/lib/python3.10/site-packages/h11/_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_transports/default.py", line 249, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
    async for part in self._stream:
  File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
    raise exc
  File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/brother/myenv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/brother/Langchain-Chatchat-master/server/utils.py", line 22, in wrap_done
    await fn
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/home/brother/myenv/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "/home/brother/myenv/lib/python3.10/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/home/brother/myenv/lib/python3.10/site-packages/openai/_streaming.py", line 129, in __stream__
    async for sse in iterator:
  File "/home/brother/myenv/lib/python3.10/site-packages/openai/_streaming.py", line 120, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/home/brother/myenv/lib/python3.10/site-packages/openai/_streaming.py", line 231, in aiter
    async for line in iterator:
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_models.py", line 966, in aiter_lines
    async for text in self.aiter_text():
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_models.py", line 953, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_models.py", line 932, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_models.py", line 990, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_transports/default.py", line 248, in __aiter__
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/brother/myenv/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
麻烦大佬看下是模型的问题还是其他什么原因。

**Comment by zRzRzRzRzRzRzR** [comment]
4bit问题很多的，我们没有做4bit支持
