### ISSUE TITLE
请删除

### ISSUE THREAD

**Issue by Aikoin** [chatchat-space/Langchain-Chatchat#2720]
delete

**Comment by Aikoin** [comment]
出现了新的问题

> _🤖_
> 
> Hey @Aikoin! Great to see you back here again. Let's get this sorted out for you.
> 
> To configure Langchain-Chatchat v0.2.9 to use only the online OpenAI model and avoid the OSError when it tries to load the local ChatGLM model 'THUDM/chatglm3-6b' on a Linux system with Python version 3.10.10, you need to modify the `LLM_MODELS` list in the `configs/model_config.py.example` file.
> 
> You should remove the local model "chatglm3-6b" and leave only the "openai-api" in the list.
> 
> Here is the modified code:
> 
> ```python
> # 要运行的 LLM 名称，可以包括本地模型和在线模型。列表中本地模型将在启动项目时全部加载。
> # 列表中第一个模型将作为 API 和 WEBUI 的默认模型。
> LLM_MODELS = ["openai-api"]  # Removed "chatglm3-6b"
> ```
> 
> This change will make Langchain-Chatchat use only the online OpenAI model and it will not try to load the local model 'THUDM/chatglm3-6b', thus avoiding the OSError.
> 
> Please note that you also need to provide your OpenAI API key in the `ONLINE_LLM_MODEL` dictionary for the "openai-api" model:
> 
> ```python
> "openai-api": {
>     "model_name": "gpt-3.5-turbo",
>     "api_base_url": "https://api.openai.com/v1",
>     "api_key": "<Your OpenAI API Key>",  # Replace <Your OpenAI API Key> with your actual OpenAI API key
>     "openai_proxy": "",
> },
> ```
> 
> Remember to rename the `configs/model_config.py.example` file to `configs/model_config.py` after making these changes.
> 
> For more information, you can refer to the [configs/model_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example) file in the Langchain-Chatchat codebase.
> 
> If you have any other questions or need further clarification, feel free to ask.
> 
> -[Dosu](https://dosu.dev)
> 
> ## Sources
> * [configs/model_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

出现了新的问题：
==============================Langchain-Chatchat Configuration==============================


2024-01-19 12:51:50,554 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-19 12:51:50,554 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 /data/jiale.lu/Langchain-Chatchat/logs
2024-01-19 12:51:53,622 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 20001): address already in use
2024-01-19 12:51:58,393 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-19 12:51:58,393 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-19 12:51:59 | ERROR | stderr | INFO:     Started server process [17003]
2024-01-19 12:51:59 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-19 12:51:59 | ERROR | stderr | INFO:     Application startup complete.
2024-01-19 12:51:59 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20002 (Press CTRL+C to quit)
Process API Server:
Traceback (most recent call last):
  File "/data/jiale.lu/miniconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/data/jiale.lu/miniconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/jiale.lu/Langchain-Chatchat/startup.py", line 436, in run_api_server
    app = create_app(run_mode=run_mode)
  File "/data/jiale.lu/Langchain-Chatchat/server/api.py", line 51, in create_app
    mount_app_routes(app, run_mode=run_mode)
  File "/data/jiale.lu/Langchain-Chatchat/server/api.py", line 77, in mount_app_routes
    mount_knowledge_routes(app)
  File "/data/jiale.lu/Langchain-Chatchat/server/api.py", line 140, in mount_knowledge_routes
    from server.chat.knowledge_base_chat import knowledge_base_chat
  File "/data/jiale.lu/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 24, in <module>
    from server.reranker.reranker import LangchainReranker
  File "/data/jiale.lu/Langchain-Chatchat/server/reranker/reranker.py", line 10, in <module>
    from langchain.retrievers.document_compressors.base import BaseDocumentCompressor
  File "/data/jiale.lu/miniconda3/lib/python3.10/site-packages/langchain/retrievers/__init__.py", line 60, in <module>
    from langchain.retrievers.self_query.base import SelfQueryRetriever
  File "/data/jiale.lu/miniconda3/lib/python3.10/site-packages/langchain/retrievers/self_query/base.py", line 33, in <module>
    from langchain.chains.query_constructor.base import load_query_constructor_runnable
  File "/data/jiale.lu/miniconda3/lib/python3.10/site-packages/langchain/chains/query_constructor/base.py", line 23, in <module>
    from langchain.chains.query_constructor.parser import get_parser
  File "/data/jiale.lu/miniconda3/lib/python3.10/site-packages/langchain/chains/query_constructor/parser.py", line 9, in <module>
    check_package_version("lark", gte_version="1.1.5")
  File "/data/jiale.lu/miniconda3/lib/python3.10/site-packages/langchain_core/utils/utils.py", line 124, in check_package_version
    raise ValueError(
ValueError: Expected lark version to be >= 1.1.5. Received 1.1.2.
