### ISSUE TITLE
[BUG] 简洁阐述问题 / 使用api运行chatglm3报错

### ISSUE THREAD

**Issue by WangShengzhao** [chatchat-space/Langchain-Chatchat#2722]
ERROR | root | Error code: 400 - {'object': 'error', 'message': 'Only zhipu-api allowed now, your model chatglm3-6b', 'code': 40301}
Traceback (most recent call last):
  File "/home/wsz/Langchain-Chatchat-master/server/utils.py", line 23, in wrap_done
    await fn
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 105, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1291, in create
    return await self._post(
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/openai/_base_client.py", line 1578, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/openai/_base_client.py", line 1339, in request
    return await self._request(
  File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/openai/_base_client.py", line 1429, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Only zhipu-api allowed now, your model chatglm3-6b', 'code': 40301}
2024-01-19 16:11:59 | ERROR | root | BadRequestError: Caught exception: Error code: 400 - {'object': 'error', 'message': 'Only zhipu-api allowed now, your model chatglm3-6b', 'code': 40301}

**Comment by zRzRzRzRzRzRzR** [comment]
glm要重写了，现在他们的库版本太高了不兼容了

**Comment by Autism-al** [comment]
请问这个问题您解决了吗，我今天也遇到了同样的问题，尝试了很长时间都没法解决

**Comment by MusicOfWind** [comment]
> glm要重写了，现在他们的库版本太高了不兼容了

是什么和什么的版本不兼容

**Comment by MusicOfWind** [comment]
> 请问这个问题您解决了吗，我今天也遇到了同样的问题，尝试了很长时间都没法解决

你解决了嘛

**Comment by MusicOfWind** [comment]
> ERROR | root | Error code: 400 - {'object': 'error', 'message': 'Only zhipu-api allowed now, your model chatglm3-6b', 'code': 40301} Traceback (most recent call last): File "/home/wsz/Langchain-Chatchat-master/server/utils.py", line 23, in wrap_done await fn File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall raise e File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall await self._acall(inputs, run_manager=run_manager) File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall response = await self.agenerate([inputs], run_manager=run_manager) File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate return await self.llm.agenerate_prompt( File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 553, in agenerate_prompt return await self.agenerate( File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 513, in agenerate raise exceptions[0] File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 616, in _agenerate_with_cache return await self._agenerate( File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate return await agenerate_from_stream(stream_iter) File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 86, in agenerate_from_stream async for chunk in stream: File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream async for chunk in await acompletion_with_retry( File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 105, in acompletion_with_retry return await llm.async_client.create(**kwargs) File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1291, in create return await self._post( File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/openai/_base_client.py", line 1578, in post return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls) File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/openai/_base_client.py", line 1339, in request return await self._request( File "/home/wsz/anaconda3/envs/py310chat/lib/python3.10/site-packages/openai/_base_client.py", line 1429, in _request raise self._make_status_error_from_response(err.response) from None openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Only zhipu-api allowed now, your model chatglm3-6b', 'code': 40301} 2024-01-19 16:11:59 | ERROR | root | BadRequestError: Caught exception: Error code: 400 - {'object': 'error', 'message': 'Only zhipu-api allowed now, your model chatglm3-6b', 'code': 40301}

你解决了嘛
