### ISSUE TITLE
[BUG] 使用zhipuai的glm-4在线大模型不适配

### ISSUE THREAD

**Issue by FanHeran** [chatchat-space/Langchain-Chatchat#2736]
**问题描述 / Problem Description**
使用zhipuai的glm-4在线大模型不适配

**复现问题的步骤 / Steps to Reproduce**
model_config.py中设置zhipu-api version 为glm-4，启动web-ui使用zhipu-api，default模板，对话框中输入任意内容并发送。

**实际结果 / Actual Result**
2024-01-21 06:19:20 | ERROR | model_worker | 请求智谱 API 时发生错误：{'error_code': 500, 'text': '[1214][prompt 参数非法。请检查档。]', 'error': {'message': '[1214][prompt 参数非法。请检查文档。]', 'type': 'invalid_request_error', 'param': None, 'code': Non}
2024-01-21 06:19:20,624 - utils.py[line:25] - ERROR: An error occurred during streaming
Traceback (most recent call last):
  File "/root/Langchain-Chatchat/server/utils.py", line 23, in wrap_done
    await fn
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 553, in anerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 513, in anerate
    raise exceptions[0]
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 616, in _enerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 86, in agerate_from_stream
    async for chunk in stream:
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astrm
    async for chunk in await acompletion_with_retry(
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/root/anaconda3/envs/Chatchat/lib/python3.11/site-packages/openai/_streaming.py", line 136, in __stream__
    raise APIError(
openai.APIError: An error occurred during streaming

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.9
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：glm4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 20.04.5 LTS
- Python 版本 / Python version: 3.11.7

**Comment by zRzRzRzRzRzRzR** [comment]
本版本暂时难以适配，在dev中用http走fschat的形式注册了一个，但是可能bug很多，0.3.x开始弃用fschat后会修改的
