### ISSUE TITLE
langchain-chathat 调用Dify应用的api接口时报错： ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by qianbaidu1266** [chatchat-space/Langchain-Chatchat#2739]
使用最新版的langchain-chathat 调用Dify应用的api接口时，页面正常返回信息，但是terminal终端一直报错：

INFO:     127.0.0.1:6231 - "POST /chat/chat HTTP/1.1" 200 OK
2024-01-21 20:48:11,301 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
F:\Anaconda3\envs\py310\lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_
models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the 
langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import Ch
atOpenAI`.
  warn_deprecated(
2024-01-21 20:48:12 | INFO | stdout | INFO:     127.0.0.1:6238 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-21 20:48:12,553 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-21 20:48:12 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21010/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-21 20:48:26 | INFO | httpx | HTTP Request: POST https://api.dify.ai/v1/chat-messages "HTTP/1.1 200 OK"
2024-01-21 20:48:28,099 - utils.py[line:25] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "G:\AIGC\Langchain\laster-bak\server\utils.py", line 23, in wrap_done
    await fn
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain_core\language_models\chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain_core\language_models\chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain_core\language_models\chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain_community\chat_models\openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain_core\language_models\chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "F:\Anaconda3\envs\py310\lib\site-packages\langchain_community\chat_models\openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-01-21 20:48:28,144 - utils.py[line:28] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

应该怎么解决呢？看了之前的帖子说降低torch 版本到 2.0.1， 试过了还是报错

**Comment by qianbaidu1266** [comment]
没有降低torch版本的时候，报错信息如下：

**Comment by qianbaidu1266** [comment]
没有降低torch版本时，报错信息如下：

2024-01-21 21:22:19,431 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-01-21 21:22:19 | INFO | stdout | INFO:     127.0.0.1:4541 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-21 21:22:19,850 - util.py[line:67] - INFO: message='OpenAI API response' path=http://127.0.0.1:20000/v1/chat/completions processing_ms=None
 request_id=None response_code=200
2024-01-21 21:22:20 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21010/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-21 21:22:30 | INFO | httpx | HTTP Request: POST https://api.dify.ai/v1/chat-messages "HTTP/1.1 200 OK"
2024-01-21 21:22:31,938 - utils.py[line:26] - ERROR: 'choices'
Traceback (most recent call last):
  File "G:\AIGC\Langchain\Langchain-Chatchat\server\utils.py", line 24, in wrap_done
    await fn
  File "F:\Anaconda3\envs\langchain\lib\site-packages\langchain\chains\base.py", line 381, in acall
    raise e
  File "F:\Anaconda3\envs\langchain\lib\site-packages\langchain\chains\base.py", line 375, in acall
  File "F:\Anaconda3\envs\langchain\lib\site-packages\langchain_core\language_models\chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "F:\Anaconda3\envs\langchain\lib\site-packages\langchain_core\language_models\chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "F:\Anaconda3\envs\langchain\lib\site-packages\langchain_core\language_models\chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "F:\Anaconda3\envs\langchain\lib\site-packages\langchain\chat_models\openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "F:\Anaconda3\envs\langchain\lib\site-packages\langchain_core\language_models\chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "F:\Anaconda3\envs\langchain\lib\site-packages\langchain\chat_models\openai.py", line 477, in _astream
    if len(chunk["choices"]) == 0:
KeyError: 'choices'
2024-01-21 21:22:31,941 - utils.py[line:29] - ERROR: KeyError: Caught exception: 'choices'

**Comment by zRzRzRzRzRzRzR** [comment]
这个就是没找到模型，不太清楚dify，我们应该只对模型侧读取啊

**Comment by qianbaidu1266** [comment]
不是没找到模型，没找到模型的话不会有问答结果呀

**Comment by zRzRzRzRzRzRzR** [comment]
if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
这个应该是没有找到模型啊，你确定不试走了dify的模型接入来返回的么
