### ISSUE TITLE
toml.decoder.TomlDecodeError: Found invalid character in key name: '/'

### ISSUE THREAD

**Issue by 18782961008** [chatchat-space/Langchain-Chatchat#2755]
**问题描述 / Problem Description**
初始化知识库后执行python startup.py -a 一键命令启动后报错：

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-163-generic-x86_64-with-glibc2.31.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-22 15:36:45,163 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/tfswx/lidan/ChatGLM3/model_repository/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
2024-01-22 15:36:45,164 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前Embbedings模型： bge-large-zh @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

Traceback (most recent call last):
  File "/home/tfswx/anaconda3/envs/chatchat/bin/streamlit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/streamlit/web/cli.py", line 201, in main_run
    bootstrap.load_config_options(flag_options=kwargs)
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/streamlit/web/bootstrap.py", line 367, in load_config_options
    config.get_config_options(force_reparse=True, options_from_flags=options_from_flags)
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/streamlit/config.py", line 1287, in get_config_options
    _update_config_with_toml(file_contents, filename)
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/streamlit/config.py", line 1165, in _update_config_with_toml
    parsed_config_file = toml.loads(raw_toml)
                         ^^^^^^^^^^^^^^^^^^^^
  File "/home/tfswx/anaconda3/envs/chatchat/lib/python3.11/site-packages/toml/decoder.py", line 260, in loads
    raise TomlDecodeError("Found invalid character in key name: '" +
toml.decoder.TomlDecodeError: Found invalid character in key name: '/'. Try quoting the key name. (line 3 column 3 char 61)

**Comment by 18782961008** [comment]
![捕获](https://github.com/chatchat-space/Langchain-Chatchat/assets/30662245/d329752b-7515-49e4-af4d-b53fe57931ef)

**Comment by 18782961008** [comment]
问题已解决，不知为何~/.streamlit/config.toml这个文件的第三行没有注释符号，以至于解析该文件是“/”符号不能识别，打开文件~/.streamlit/config.toml注释掉第三行即可。
![捕获](https://github.com/chatchat-space/Langchain-Chatchat/assets/30662245/ec41b0ed-20c5-429f-9370-0c27773137b1)
