### ISSUE TITLE
在执行初始化知识库和配置文件出现报错：UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb7' in position 8: surrogates not allowed

### ISSUE THREAD

**Issue by wu-sv** [chatchat-space/Langchain-Chatchat#2756]
RapidOCRPDFLoader context page index: 7: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:02<00:00,  7.86s/it]
文档切分示例：page_content='See discussions, stats, and author profiles for this publication at: https://www.researchgate.net/publication/372669736\nCreating Large Language Model Applications Utilizing LangChain: A Primer on\nDeveloping LLM Apps Fast\nArticle\xa0\xa0in\xa0\xa0International Conference on Applied Engineering and Natural Sciences · July 2023\nDOI: 10.59287/icaens.1127\nCITATIONS\n0\nREADS\n47\n2 authors:\nSome of the authors of this publication are also working on these related projects:\nTHALIA: Test Harness for the Assessment of Legacy Information Integration Approaches View project\nAnalysis of Feroresonance with Signal Processing Technique View project\nOguzhan Topsakal' metadata={'source': '/root/autodl-tmp/Langchain-Chatchat/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain.pdf'}

Traceback (most recent call last):
  File "/root/autodl-tmp/Langchain-Chatchat/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/root/autodl-tmp/Langchain-Chatchat/Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/root/autodl-tmp/Langchain-Chatchat/Langchain-Chatchat/server/knowledge_base/migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "/root/autodl-tmp/Langchain-Chatchat/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 129, in add_doc
    self.delete_doc(kb_file)
  File "/root/autodl-tmp/Langchain-Chatchat/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 144, in delete_doc
    status = delete_file_from_db(kb_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Langchain-Chatchat/Langchain-Chatchat/server/db/session.py", line 26, in wrapper
    result = f(session, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Langchain-Chatchat/Langchain-Chatchat/server/db/repository/knowledge_file_repository.py", line 128, in delete_file_from_db
    .first())
     ^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2747, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2342, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/root/miniconda3/envs/Chat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb7' in position 8: surrogates not allowed

**Comment by zRzRzRzRzRzRzR** [comment]
你这个是pdf有些字符没法用utf8吧，pdf偶尔出现这样的问题

**Comment by wu-sv** [comment]
> 你这个是pdf有些字符没法用utf8吧，pdf偶尔出现这样的问题

我在实际使用时，出现这个报错后，再运行python init_database.py --create-tables发现还是能正常初始化数据库，并且在后续启动时也能正常运行，所以实际上应该是可以忽略这个报错的

**Comment by zRzRzRzRzRzRzR** [comment]
emm，我建议你在尝试查询这个文件的内容看能不能查询到，可能是这个文件失败了，数据库没有失败

**Comment by wu-sv** [comment]
> emm，我建议你在尝试查询这个文件的内容看能不能查询到，可能是这个文件失败了，数据库没有失败

我尝试按照bot给出的忽略掉任何无法以 'utf-8' 编码的字符后就可以正常运行了
