### ISSUE TITLE
在文件对话，功能中，上传文件报错

### ISSUE THREAD

**Issue by bobjiao** [chatchat-space/Langchain-Chatchat#2770]
在文件对话，功能中，上传文件报错。
10.0.34.181:53447 - "POST /knowledge_base/upload_temp_docs HTTP/1.1" 500 Internal Server Error

错误信息如下：

2024-01-23 17:16:15,731 - faiss_cache.py[line:115] - INFO: loading vector store in 'tmp4gmcchcq' to memory.
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.84it/s]
Batches: 0it [00:00, ?it/s]
INFO:     10.0.34.181:53447 - "POST /knowledge_base/upload_temp_docs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\anaconda3\envs\langchain\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\anaconda3\envs\langchain\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\anaconda3\envs\langchain\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\anaconda3\envs\langchain\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "D:\anaconda3\envs\langchain\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "D:\anaconda3\envs\langchain\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\anaconda3\envs\langchain\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\anaconda3\envs\langchain\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\anaconda3\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\anaconda3\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\1.pythonCode\Langchain-Chatchat\server\chat\file_chat.py", line 88, in upload_temp_docs
    vs.add_documents(documents)
  File "D:\anaconda3\envs\langchain\lib\site-packages\langchain_core\vectorstores.py", line 122, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "D:\anaconda3\envs\langchain\lib\site-packages\langchain\vectorstores\faiss.py", line 223, in add_texts
    embeddings = self._embed_documents(texts)
  File "D:\anaconda3\envs\langchain\lib\site-packages\langchain\vectorstores\faiss.py", line 135, in _embed_documents
    return self.embedding_function.embed_documents(texts)
  File "D:\1.pythonCode\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 399, in embed_documents
    return normalize(embeddings).tolist()
  File "D:\1.pythonCode\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 38, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "D:\anaconda3\envs\langchain\lib\site-packages\numpy\linalg\linalg.py", line 2583, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1

**Comment by guchengxi1994** [comment]
@bobjiao 我不知道你的问题和我的一不一样，我的langchain-chatchat是部署在服务器上的，但是每次启动有的有的时候是直接把xshell关掉，有的时候是ctrl c终止，今天才发现后台一直有个python的程序没有终止，（就是启动的web ui的那个进程）。手动把这个进程终止之后，就可以正常上传文件提问题了

**Comment by AIBlocker** [comment]
确实有这个问题，怎么解决
