### ISSUE TITLE
windows下在知识库管理页面，点击添加至向量库报错

### ISSUE THREAD

**Issue by leizhu1989** [chatchat-space/Langchain-Chatchat#2771]
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：master分支
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: windows 11
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

知识库管理页面，想把知识库已有的文件添加到向量库，报错：
2024-01-23 17:30:13,787 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/update_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-23 17:30:15,824 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/update_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-23 17:30:17,867 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/update_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-23 17:30:20,162 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-23 17:30:22,217 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-23 17:30:24,274 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-23 17:30:24.276 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\zhulei\.conda\envs\Langchain_Chat\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\project\NLP\Langchain-Chatchat-master\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\project\NLP\Langchain-Chatchat-master\webui_pages\knowledge_base\knowledge_base.py", line 333, in knowledge_base_page
    data = [{"seq": i+1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
  File "D:\project\NLP\Langchain-Chatchat-master\webui_pages\knowledge_base\knowledge_base.py", line 333, in <listcomp>
    data = [{"seq": i+1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                               ~^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by leizhu1989** [comment]
启动到执行“添加文件到知识库”、“添加至向量库”报的错误：

2024-01-24 10:50:03,273 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:50:06,351 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto


==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:27:59) [MSC v.1937 64 bit (AMD64)]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34


当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-24 10:50:06,790 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'F:\\NLP\\model\\chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
2024-01-24 10:50:06,814 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================


2024-01-24 10:50:06,816 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-24 10:50:06,820 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 D:\project\NLP\Langchain-Chatchat-master\logs
2024-01-24 10:50:09,320 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:50:13,135 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:50:13,150 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:50:13,162 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:50:13 | INFO | model_worker | Register to controller
2024-01-24 10:50:13 | ERROR | stderr | INFO:     Started server process [30288]
2024-01-24 10:50:13 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-24 10:50:13 | ERROR | stderr | INFO:     Application startup complete.
2024-01-24 10:50:13 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2024-01-24 10:50:14 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 3487579c ...
Loading checkpoint shards:   0%|                                                                                                                                                              | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|█████████████████████▍                                                                                                                                | 1/7 [00:15<01:34, 15.70s/it]
Loading checkpoint shards:  29%|██████████████████████████████████████████▊                                                                                                           | 2/7 [00:31<01:18, 15.64s/it]
Loading checkpoint shards:  43%|████████████████████████████████████████████████████████████████▎                                                                                     | 3/7 [00:48<01:06, 16.53s/it]
Loading checkpoint shards:  57%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                | 4/7 [01:04<00:48, 16.07s/it]
Loading checkpoint shards:  71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                          | 5/7 [01:20<00:32, 16.01s/it]
Loading checkpoint shards:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 6/7 [01:36<00:15, 15.99s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:44<00:00, 13.62s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:44<00:00, 14.98s/it]
2024-01-24 10:52:00 | ERROR | stderr |
2024-01-24 10:52:16 | INFO | model_worker | Register to controller
2024-01-24 10:52:21,423 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:26,577 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:26,578 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:26,578 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:26,579 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
INFO:     Started server process [4656]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
2024-01-24 10:52:29,593 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto


==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:27:59) [MSC v.1937 64 bit (AMD64)]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34


当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-24 10:52:30,008 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'F:\\NLP\\model\\chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
2024-01-24 10:52:30,036 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前Embbedings模型： m3e-base @ cuda


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================



  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

2024-01-24 10:52:36,433 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:37,550 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57425 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-24 10:52:37,553 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-24 10:52:37,804 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57425 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-24 10:52:37,806 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-24 10:52:37,808 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:37,808 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:37,846 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
INFO:     127.0.0.1:57425 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-01-24 10:52:37,851 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-01-24 10:52:41,525 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:41,562 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:41,563 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:41,563 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:42,934 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57443 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-24 10:52:42,936 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-24 10:52:43,078 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57443 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-24 10:52:43,081 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-24 10:52:43,082 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:52:43,083 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
INFO:     127.0.0.1:57443 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-01-24 10:52:43,124 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-01-24 10:53:00,778 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57473 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-24 10:53:00,780 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-24 10:53:00,924 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57473 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-24 10:53:00,927 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-24 10:53:00,938 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:53:00,946 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:53:00,948 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:53:00,948 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-24 10:53:00,949 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
INFO:     127.0.0.1:57473 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-01-24 10:53:00,968 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57473 - "POST /chat/chat HTTP/1.1" 200 OK
2024-01-24 10:53:00,973 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
C:\Users\zhulei\.conda\envs\Langchain_Chat\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-01-24 10:53:01 | INFO | stdout | INFO:     127.0.0.1:57476 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-24 10:53:01,662 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-24 10:53:01 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-24 10:54:19,752 - utils.py[line:289] - INFO: UnstructuredMarkdownLoader used for D:\project\NLP\Langchain-Chatchat-master\knowledge_base\samples\content\大模型应用技术原理.md
2024-01-24 10:54:23,930 - utils.py[line:95] - ERROR: ReadError: error when post /knowledge_base/upload_docs: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-01-24 10:54:25,966 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/upload_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:54:28,002 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/upload_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:54:37,815 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:54:39,853 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:54:41,882 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:54:41.883 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\zhulei\.conda\envs\Langchain_Chat\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\project\NLP\Langchain-Chatchat-master\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\project\NLP\Langchain-Chatchat-master\webui_pages\knowledge_base\knowledge_base.py", line 333, in knowledge_base_page
    data = [{"seq": i+1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\NLP\Langchain-Chatchat-master\webui_pages\knowledge_base\knowledge_base.py", line 333, in <listcomp>
    data = [{"seq": i+1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                               ~^^^^^^
TypeError: string indices must be integers, not 'str'
2024-01-24 10:55:16,188 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/update_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:55:18,218 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/update_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:55:20,278 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/update_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:55:22,586 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:55:24,650 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:55:26,708 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-24 10:55:26.709 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\zhulei\.conda\envs\Langchain_Chat\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\project\NLP\Langchain-Chatchat-master\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\project\NLP\Langchain-Chatchat-master\webui_pages\knowledge_base\knowledge_base.py", line 333, in knowledge_base_page
    data = [{"seq": i+1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
  File "D:\project\NLP\Langchain-Chatchat-master\webui_pages\knowledge_base\knowledge_base.py", line 333, in <listcomp>
    data = [{"seq": i+1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                               ~^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by leizhu1989** [comment]
此外：我的显存8G，在向量化时是不是调用emmbeding模型，但是看提示“ReadError: error when post /knowledge_base/update_docs: [WinError 10054] 远程主机强迫关闭了一个现有的连接”是什么意思

**Comment by zRzRzRzRzRzRzR** [comment]
估计带不动了，你可以看看初始化知识库没有

**Comment by leizhu1989** [comment]
所有打印的消息都在这，这是没有初始化知识库吧，我再换成v100试试

**Comment by 948024326** [comment]
> 所有打印的消息都在这，这是没有初始化知识库吧，我再换成v100试试

解决了吗请问

**Comment by zRzRzRzRzRzRzR** [comment]
应该是设备问题，今天已经再次测试，没有相关bug

**Comment by LeyenQian** [comment]
在milvus_kb_service.py
试试看，把vector字段删除。应该是to_json错误导致的。

    def get_doc_by_ids(self, ids: List[str]) -> List[Document]:
        result = []
        if self.milvus.col:
            # ids = [int(id) for id in ids]  # for milvus if needed #pr 2725
            data_list = self.milvus.col.query(expr=f'pk in {[int(_id) for _id in ids]}', output_fields=["*"])

         
            del data_list[0]['vector']


            for data in data_list:
                text = data.pop("text")
                result.append(Document(page_content=text, metadata=data))
        return result

**Comment by LeyenQian** [comment]
utils.py下_get_response_value里面的to_json导致的错误

修改milvus_kb_service.py（删除vector字段）
    def get_doc_by_ids(self, ids: List[str]) -> List[Document]:
        result = []
        if self.milvus.col:
            # ids = [int(id) for id in ids]  # for milvus if needed #pr 2725
            data_list = self.milvus.col.query(expr=f'pk in {[int(_id) for _id in ids]}', output_fields=["*"])
            for data in data_list:
                del data['vector']
                text = data.pop("text")
                result.append(Document(page_content=text, metadata=data))
        return result

**Comment by xxWeiDG** [comment]
请问一下最后怎么解决了呢
