### ISSUE TITLE
[BUG] 使用百川在线API,调用时显示错误

### ISSUE THREAD

**Issue by liurr9810** [chatchat-space/Langchain-Chatchat#2786]
2024-01-24 22:03:09 | ERROR | model_worker | 请求百川 API 时发生错误：{'error_code': 10105, 'text': 'Invalid Signature parameter in request header', 'error': {'message': 'Invalid Signature parameter in request header', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-01-24 22:03:09,738 - utils.py[line:24] - ERROR: An error occurred during streaming
Traceback (most recent call last):
  File "/home/gaea/langchain-chat/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 506, in agenerate_prompt
    return await self.agenerate(
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 466, in agenerate
    raise exceptions[0]
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 569, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 518, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 85, in agenerate_from_stream
    async for chunk in stream:
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 484, in _astream
    async for chunk in await acompletion_with_retry(
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/home/gaea/miniconda3/envs/langchain-update/lib/python3.10/site-packages/openai/_streaming.py", line 136, in __stream__
    raise APIError(
openai.APIError: An error occurred during streaming
2024-01-24 22:03:09,741 - utils.py[line:27] - ERROR: APIError: Caught exception: An error occurred during streaming

**Comment by liurr9810** [comment]
> _🤖_
> 
> 你好，@liurr9810！好久不见，希望一切都好。谢谢您再次提出问题，我们会一直在这里帮助您解决问题。
> 
> 根据您提供的错误日志，问题似乎出在调用百川 API 时的签名参数。错误代码 10105 表示请求头中的签名参数无效。这可能是由于在生成签名时出现了问题，或者在将签名添加到请求时时头时出现了问题。
> 
> 在 Langchain-Chachat 应用中，百川 API 的生成签名过程通常在`BaiChuanWorker`类`do_chat`方法中进行。该方法负责向百川 API 的聊天端点发送 POST 请求，并在请求头中包含授权令牌、时间、使用 MD5 加密计算的签名等信息。
> 
> 如果签名生成过程中出现问题，可能会导致无效的签名参数错误。这可能是由于以下原因：
> 
> * 按键使用不正确
> * 签名生成算法有误
> * 在计算签名时，输入的数据顺序、格式或内容有错误
> 
> 我为您检查`BaiChuanWorker`类中的签名生成代码，确保密钥、算法和输入数据建议都是正确的。如果问题仍然存在，可能需要进一步调试代码以了解问题的具体原因。
> 
> 如果您需要更多的帮助，或者有更多的信息可以提供，欢迎继续在本问题下留言。
> 
> ## 来源
> * [服务器/model_workers/baichuan.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/baichuan.py)
> 
> 此回复旨在有用并节省您的时间。它不是**一个准确的解决方案**，而是您自己研究的起点。
> 
> 帮助我变得更有用！如果这有帮助，请留下👍；如果不相关，请留下👎。
> 
> 如果您想继续对话，请以以下方式开始回复@dosu-bot。

如何获取百川的secret key？

**Comment by zRzRzRzRzRzRzR** [comment]
config配置有，你看一下对应的网页去申请

**Comment by ZhichaoOuyang** [comment]
> config配置有，你看一下对应的网页去申请

你好，对应网页里面获取不到 secret_key ，请问怎么解决哈
