### ISSUE TITLE
[BUG] 初始化知识库抛异常信息'PGVector' object has no attribute 'connect'

### ISSUE THREAD

**Issue by MartinH04** [chatchat-space/Langchain-Chatchat#2790]
**初始化知识库抛异常信息/ Problem Description**
'PGVector' object has no attribute 'connect' / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python.exe .\init_database.py --recreate-vs' / Run 'python.exe .\init_database.py --recreate-vs'
2. 问题出现 / Problem occurs
Traceback (most recent call last):
  File "D:\Langchain-Chatchat-0.2.9\init_database.py", line 108, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "D:\Langchain-Chatchat-0.2.9\server\knowledge_base\migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "D:\Langchain-Chatchat-0.2.9\server\knowledge_base\migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "D:\Langchain-Chatchat-0.2.9\server\knowledge_base\kb_service\base.py", line 129, in add_doc
    self.delete_doc(kb_file)
  File "D:\Langchain-Chatchat-0.2.9\server\knowledge_base\kb_service\base.py", line 143, in delete_doc
    self.do_delete_doc(kb_file, **kwargs)
  File "D:\Langchain-Chatchat-0.2.9\server\knowledge_base\kb_service\pg_kb_service.py", line 72, in do_delete_doc
    with self.pg_vector.connect() as connect:
AttributeError: 'PGVector' object has no attribute 'connect'

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
win10

python version: 3.10.11

Name: pgvector
Version: 0.2.4
Summary: pgvector support for Python
Home-page: https://github.com/pgvector/pgvector-python
Author: Andrew Kane
Author-email: andrew@ankane.org
License: MIT
Location: d:\Langchain-Chatchat-0.2.9\venv\lib\site-packages
Requires: numpy
Required-by:

**Comment by MartinH04** [comment]
I find the bug-fix Merge，It‘s work now
https://github.com/chatchat-space/Langchain-Chatchat/pull/2591/commits/205dcd8b396ead6021fa107f5efaf675022b4275
