### ISSUE TITLE
启动python startup.py -a时，加载本地模型报路径错误，模型无法加载

### ISSUE THREAD

**Issue by linnengbo** [chatchat-space/Langchain-Chatchat#2794]
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-01-25 16:18:25,435 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-25 16:18:25,435 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 /mnt/PD-L1/xiaoming/hugging_face/Langchain-Chatchat/logs
2024-01-25 16:18:36,819 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-25 16:18:59,324 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-25 16:18:59,329 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-25 16:18:59,406 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-25 16:19:03 | INFO | model_worker | Register to controller
2024-01-25 16:19:04 | ERROR | stderr | INFO:     Started server process [43037]
2024-01-25 16:19:04 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-25 16:19:04 | ERROR | stderr | INFO:     Application startup complete.
2024-01-25 16:19:04 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-01-25 16:19:10 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 229b2245 ...
2024-01-25 16:19:10 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-01-25 16:19:10 | ERROR | stderr | Traceback (most recent call last):
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/xiaoming/soft/anaconda3/envs/1-langchat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-01-25 16:19:10 | ERROR | stderr |     self.run()
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/xiaoming/soft/anaconda3/envs/1-langchat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-01-25 16:19:10 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/PD-L1/xiaoming/hugging_face/Langchain-Chatchat/startup.py", line 387, in run_model_worker
2024-01-25 16:19:10 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-25 16:19:10 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/PD-L1/xiaoming/hugging_face/Langchain-Chatchat/startup.py", line 215, in create_model_worker_app
2024-01-25 16:19:10 | ERROR | stderr |     worker = ModelWorker(
2024-01-25 16:19:10 | ERROR | stderr |              ^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/xiaoming/soft/anaconda3/envs/1-langchat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-01-25 16:19:10 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-01-25 16:19:10 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/xiaoming/soft/anaconda3/envs/1-langchat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 323, in load_model
2024-01-25 16:19:10 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-01-25 16:19:10 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/xiaoming/soft/anaconda3/envs/1-langchat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 774, in load_model
2024-01-25 16:19:10 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-01-25 16:19:10 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/xiaoming/soft/anaconda3/envs/1-langchat/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 774, in from_pretrained
2024-01-25 16:19:10 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2024-01-25 16:19:10 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/xiaoming/soft/anaconda3/envs/1-langchat/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2028, in from_pretrained
2024-01-25 16:19:10 | ERROR | stderr |     return cls._from_pretrained(
2024-01-25 16:19:10 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/xiaoming/soft/anaconda3/envs/1-langchat/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2260, in _from_pretrained
2024-01-25 16:19:10 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-01-25 16:19:10 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/PD-L1/xiaoming/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenization_chatglm.py", line 109, in __init__
2024-01-25 16:19:10 | ERROR | stderr |     self.tokenizer = SPTokenizer(vocab_file)
2024-01-25 16:19:10 | ERROR | stderr |                      ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "/mnt/PD-L1/xiaoming/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenization_chatglm.py", line 17, in __init__
2024-01-25 16:19:10 | ERROR | stderr |     assert os.path.isfile(model_path), model_path
2024-01-25 16:19:10 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 16:19:10 | ERROR | stderr |   File "<frozen genericpath>", line 30, in isfile
2024-01-25 16:19:10 | ERROR | stderr | TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by zRzRzRzRzRzRzR** [comment]
这个不是模型地址错么，按照机器人的改

**Comment by linnengbo** [comment]
> _🤖_
> 
> 你好，@linnengbo！ 再次很高兴见到你。希望你这一天过得愉快！
> 
> 您遇到的错误可能是由于在配置文件中未正确指定本地模型的路径。在`configs/model_config.py.example`文件中，`MODEL_ROOT_PATH`被设置为一个空字符串。该变量应该包含所有Embedding和LLM模型存储的绝对路径。
> 
> 要解决这个问题，您应该在`MODEL_ROOT_PATH`变量中指定存储模型的目录的绝对路径。例如，如果您的模型存储在项目根目录下名为“models”的目录中，您应该设置`MODEL_ROOT_PATH = "/path/to/your/project/models"`。
> 
> 另外，确保您尝试加载的模型包含在`LLM_MODELS`列表中。如果它是本地模型，它应该在`MODEL_ROOT_PATH`指定的目录中可用。如果它是在线模型，确保在`ONLINE_LLM_MODEL`字典中提供正确的API密钥和其他必要条件的详细信息信息。
> 
> 如果您已经完成了所有这些但仍然遇到问题，可能是模型文件本身丢失或损坏。在这种情况下，您需要重新下载或修复模型文件。
> 
> 参考资料：
> 
> * [配置/model_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example)
> 
> ## 来源
> * [配置/model_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example)
> 
> 此回复旨在有用并节省您的时间。它不是**一个准确的解决方案**，而是您自己研究的起点。
> 
> 帮助我变得更有用！如果这有帮助，请留下👍；如果不相关，请留下👎。
> 
> 如果您想继续对话，请以以下方式开始回复@dosu-bot。

模型地址已经指定了，显示也有识别到：启动时基本信息如下
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1160.105.1.el7.x86_64-x86_64-with-glibc2.31.
python版本：3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/mnt/PD-L1/xiaoming/hugging_face/models/THUDM/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================

**Comment by zRzRzRzRzRzRzR** [comment]
模型文件是全的吗，huggingface下载的？

**Comment by linnengbo** [comment]
> 模型文件是全的吗，huggingface下载的？

是的，手动下载的

**Comment by zRzRzRzRzRzRzR** [comment]
估计是少了什么文件

**Comment by lty7711** [comment]
你把模型文件放在LangChain-Chatchat，目录下就好，下面这张图是我的，我用Chatglm3，项目当你不设置模型路径时，会首先找chatglm3，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/93381305/9a9b1d7d-c837-4e9f-9905-665e45c31550)

**Comment by linnengbo** [comment]
是model少了2个文件，已经解决了，感谢
