### ISSUE TITLE
[BUG] 在线接口模式，配置的zhipu-api的key，成功启动界面，并输入一个问题，然后后台日志显示去找openai-api

### ISSUE THREAD

**Issue by datadrivenhorse** [chatchat-space/Langchain-Chatchat#2811]
**问题描述 / Problem Description**
在线接口模式，只配置了zhipu-api的key，没有配置openai-api的key，成功启动界面，并输入一个问题，然后后台日志显示去找openai-api报错，

**复现问题的步骤 / Steps to Reproduce**
1. 后台执行 python3 startup.py -a --lite，成功启动服务
2. 前端web页面成功显示，“选择LLM模型：” zhipu-api（Running）
3. 前端web页面对话框输入一个问题，“请讲一下锻炼身体的方法？”，然后界面无答案返回
4. 后端日志输出报错

**预期的结果 / Expected Result**
在界面，输入一个问题后，后台调用zhipu-api，前端页面展现结果

**实际结果 / Actual Result**
前端页面无答案返回，后台日志显示openai-api报错

**环境信息 / Environment Information**
- langchain-ChatGLM v0.2.10版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: centos 7.9
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
后端命令行输出，如下：
[root@bogon Langchain-Chatchat-master]# python3 startup.py -a --lite
['chatglm3-6b', 'zhipu-api', 'openai-api']
['chatglm3-6b', 'zhipu-api', 'openai-api']
Namespace(all_webui=True, all_api=False, llm_api=False, openai_api=False, model_worker=False, model_name=['chatglm3-6b', 'zhipu-api', 'openai-api'], controller_address=None, api=False, api_worker=False, webui=False, quiet=False, lite=True)

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.11.7 (main, Dec 23 2023, 12:30:31) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'port': 20002}
{'api_key': '2da232b6470a9b914a0f271a27780335.HAFk85n1RWpXdo4O',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cpu
==============================Langchain-Chatchat Configuration==============================

2024-01-27 19:15:56,905 - startup.py[line:658] - INFO: 正在启动服务：
2024-01-27 19:15:56,905 - startup.py[line:659] - INFO: 如需查看 llm_api 日志，请前往 /media/sf_chatglm/Langchain-Chatchat-master/logs
['chatglm3-6b', 'zhipu-api', 'openai-api']
/usr/local/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
['chatglm3-6b', 'zhipu-api', 'openai-api']
['chatglm3-6b', 'zhipu-api', 'openai-api']
Namespace()
2024-01-27 19:16:05 | INFO | model_worker | Register to controller
2024-01-27 19:16:05 | ERROR | stderr | INFO:     Started server process [1930]
2024-01-27 19:16:05 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-27 19:16:05 | ERROR | stderr | INFO:     Application startup complete.
2024-01-27 19:16:05 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
['chatglm3-6b', 'zhipu-api', 'openai-api']
INFO:     Started server process [1947]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
['chatglm3-6b', 'zhipu-api', 'openai-api']

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.11.7 (main, Dec 23 2023, 12:30:31) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'port': 20002}
{'api_key': '2da232b6470a9b914a0f271a27780335.HAFk85n1RWpXdo4O',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cpu

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501
2024-01-27 19:17:14,437 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58462 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-27 19:17:14,442 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-01-27 19:17:14,561 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58462 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-01-27 19:17:14,564 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58462 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-01-27 19:17:14,607 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"  

2024-01-27 19:19:57,825 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
/usr/local/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-01-27 19:19:57 | INFO | stdout | INFO:     127.0.0.1:44050 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-27 19:19:57,989 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-27 19:19:58 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21001/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-27 19:19:58,274 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/media/sf_chatglm/Langchain-Chatchat-master/server/utils.py", line 36, in wrap_done
    await fn
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-01-27 19:19:58,282 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

openai_api_server.log内容如下：
2024-01-27 16:15:16 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m2013[0m]
2024-01-27 16:15:16 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-01-27 16:15:16 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-01-27 16:15:16 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:20000[0m (Press CTRL+C to quit)
2024-01-27 16:16:45 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50838 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-01-27 16:18:58 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50912 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-01-27 19:16:05 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1930[0m]
2024-01-27 19:16:05 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-01-27 19:16:05 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-01-27 19:16:05 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:20000[0m (Press CTRL+C to quit)
2024-01-27 19:19:57 | INFO | stdout | [32mINFO[0m:     127.0.0.1:44050 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m

**Comment by zRzRzRzRzRzRzR** [comment]
你选的是zhipu的吗

**Comment by datadrivenhorse** [comment]
> ass is designed to return an error if the method isn't implemented. Here's the relevant code snippet:

选的是zhipu。
今天我又做了实验，配置了qwen-api的key，然后再次启动，就运行正常了

**Comment by jayofhust** [comment]
今天我又做了实验，配置了qwen-api的key，然后再次启动，就运行正常了
是指的是：配置了qwen-api的key之后运行zhipu启动成功了吗？

**Comment by zRzRzRzRzRzRzR** [comment]
不是啊，还有这种操作？？我今天只配了智谱的key并选择了智谱（没选openai）是正常的啊

**Comment by zRzRzRzRzRzRzR** [comment]
已经再次做过测试，zhipuai是没有问题的

**Comment by MSZheng20** [comment]
检查一下zhipuai的SDK版本，升级到V4再试试
