### ISSUE TITLE
在线对话模型调用zhipu的api的时候，告诉我请求智谱 API 时发生错误：{'error_code': 500, 'text': '[1214][prompt 参数非法。请检查文档。]', 'error': {'message': '[1214][prompt 参数非法。请检查文档。]', 'type': 'invalid_request_error', 'param': None, 'code': None}}

### ISSUE THREAD

**Issue by jayofhust** [chatchat-space/Langchain-Chatchat#2815]
本人环境为：
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34
当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-28 14:38:22,400 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'E:\\ChatGLM3-6B\\model',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '54ca1088cbc93d66aa1876641607Vktmi6UKu',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
2024-01-28 14:38:22,402 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前Embbedings模型： bge-large-zh @ cuda
-----------------------------------------------------------------------------
报错信息为：
2024-01-28 14:46:49 | ERROR | model_worker | 请求智谱 API 时发生错误：{'error_code': 500, 'text': '[1214][prompt 参数非法。请检查文档。]', 'error': {'message': '[1214][prompt 参数非法。请检查文档。]', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-01-28 14:46:49,607 - utils.py[line:25] - ERROR: An error occurred during streaming
Traceback (most recent call last):
  File "E:\Langchain-CHAT\Langchain-Chatchat\server\utils.py", line 23, in wrap_done
    await fn
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_core\language_models\chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_core\language_models\chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_core\language_models\chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_community\chat_models\openai.py", line 520, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_core\language_models\chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_community\chat_models\openai.py", line 486, in _astream
    async for chunk in await acompletion_with_retry(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\openai\_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\openai\_streaming.py", line 136, in __stream__
    raise APIError(
openai.APIError: An error occurred during streaming
2024-01-28 14:46:49,611 - utils.py[line:28] - ERROR: APIError: Caught exception: An error occurred during streaming

**Comment by zRzRzRzRzRzRzR** [comment]
你是在对话还是套用了知识库的回答，我这没有出现
智谱API 的 一些参数是不能改变的，输入长度不能超过4k，温度必须大于0 top p小于1

**Comment by jayofhust** [comment]
我使用的是LLM对话 选择LLM模型选择的：zhipu-api 没有使用知识库问答

**Comment by jayofhust** [comment]
2024-01-28 15:10:25,304 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
INFO:     127.0.0.1:60002 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-01-28 15:10:25,314 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:60002 - "POST /chat/chat HTTP/1.1" 200 OK
2024-01-28 15:10:25,322 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-01-28 15:10:25 | INFO | stdout | INFO:     127.0.0.1:60006 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-28 15:10:25,837 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-28 15:10:26 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21001/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-28 15:10:26 | ERROR | model_worker | 请求智谱 API 时发生错误：{'error_code': 500, 'text': '[1214][prompt 参数非法。请检查文档。]', 'error': {'message': '[1214][prompt 参数非法。请检查文档。]', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-01-28 15:10:26,496 - utils.py[line:25] - ERROR: An error occurred during streaming
Traceback (most recent call last):
  File "E:\Langchain-CHAT\Langchain-Chatchat\server\utils.py", line 23, in wrap_done
    await fn
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_core\language_models\chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_core\language_models\chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_core\language_models\chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_community\chat_models\openai.py", line 520, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_core\language_models\chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain_community\chat_models\openai.py", line 486, in _astream
    async for chunk in await acompletion_with_retry(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\openai\_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\openai\_streaming.py", line 136, in __stream__
    raise APIError(
openai.APIError: An error occurred during streaming
2024-01-28 15:10:26,498 - utils.py[line:28] - ERROR: APIError: Caught exception: An error occurred during streaming

一直都是这个报错
