### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by ALLENROGERDAI** [chatchat-space/Langchain-Chatchat#2821]
用streamlit启动webui.py时出现页面背景但显示TypeError？？？

大佬们好：

下面是我打开cmd之后的全过程：

Microsoft Windows [版本 10.0.22621.3007]
(c) Microsoft Corporation。保留所有权利。

C:\GLM\Langchain-Chatchat>conda activate langchain

(langchain) C:\GLM\Langchain-Chatchat>streamlit run webui.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.197.24.73:8501

2024-01-29 10:00:44,509 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-29 10:00:46,540 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-29 10:00:48,572 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-29 10:00:50,734 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-29 10:00:52,769 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-29 10:00:54,786 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-29 10:00:54.786 Uncaught app exception
Traceback (most recent call last):
  File "C:\Anaconda3\envs\langchain\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\GLM\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "C:\GLM\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

如上。

issue2094、2314、2460的方法试了没用捏？

- langchain-ChatGLM 0.2.10
- 没用docker部署
- llm用的chatglm3-6b
- embedding用的bge-large-zh-v1.5
- 我好像都没到这一步？默认的没改过
- win11
- Python 3.11.7
- torch2.1.2
- torchvision0.16.2
- cuda12.3.2
- cudnn8700
- httpx试了用2.4.0但是没用捏？

大佬，饿饿，饭饭（
不胜感激

**Comment by ALLENROGERDAI** [comment]
但是怎么操作捏？

**Comment by zRzRzRzRzRzRzR** [comment]
wiki中有写如何配置大模型，估计是你没有配置正确
