### ISSUE TITLE
[BUG] python init_database.py --recreate-vs 无反应

### ISSUE THREAD

**Issue by tersapp** [chatchat-space/Langchain-Chatchat#2828]
**问题描述 / Problem Description**
运行命令卡死，有GPU卡但不知如何使用。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...' :  **python init_database.py --recreate-vs**

**预期的结果 / Expected Result**
应该顺利通过。可以进行下一步。

**实际结果 / Actual Result** 运行如下，并且许久无反应:
**(chatchat) PS D:\gitrepos\langchain\Langchain-Chatchat> git lfs install
Git LFS initialized.
(chatchat) PS D:\gitrepos\langchain\Langchain-Chatchat> python copy_config_example.py
(chatchat) PS D:\gitrepos\langchain\Langchain-Chatchat> python init_database.py --recreate-vs
recreating all vector stores
2024-01-29 12:32:29,106 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh-v1.5' from disk.
2024-01-29 12:32:29,919 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.77it/s]
2024-01-29 12:32:31,923 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2024-01-29 12:32:31,923 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2024-01-29 12:32:31,923 - loader.py[line:64] - INFO: Loading faiss.
2024-01-29 12:32:32,236 - loader.py[line:66] - INFO: Successfully loaded faiss.
C:\Users\Ferr\anaconda3\envs\chatchat\Lib\site-packages\langchain_community\vectorstores\faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(
2024-01-29 12:32:32,329 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-124076-270516.jpg
2024-01-29 12:32:32,329 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-20096-279847.jpg
2024-01-29 12:32:32,329 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-220157-552735.jpg
2024-01-29 12:32:32,329 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-36114-765327.jpg
2024-01-29 12:32:32,329 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-392521-261326.jpg
2024-01-29 12:32:32,329 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-42284-124759.jpg
2024-01-29 12:32:32,329 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-57107-679259.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-618350-869132.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-838373-426344.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/分布式训练技术原理-幕布图片-906937-836104.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型应用技术原理-幕布图片-108319-429731.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型应用技术原理-幕布图片-580318-260070.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型应用技术原理-幕布图片-793118-735987.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型应用技术原理-幕布图片-918388-323086.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型技术栈-算法与原理-幕布图片-19929-302935.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型技术栈-算法与原理-幕布图片-299768-254064.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型技术栈-算法与原理-幕布图片-454007-940199.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型技术栈-算法与原理-幕布图片-628857-182232.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型技术栈-算法与原理-幕布图片-729151-372321.jpg
2024-01-29 12:32:32,345 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型技术栈-算法与原理-幕布图片-81470-404273.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型指令对齐训练原理-幕布图片-17565-176537.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型指令对齐训练原理-幕布图片-349153-657791.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型指令对齐训练原理-幕布图片-350029-666381.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型指令对齐训练原理-幕布图片-759487-923925.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型指令对齐训练原理-幕布图片-805089-731888.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型指令对齐训练原理-幕布图片-95996-523276.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型推理优化策略-幕布图片-276446-401476.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型推理优化策略-幕布图片-380552-579242.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型推理优化策略-幕布图片-590671-36787.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型推理优化策略-幕布图片-699343-219844.jpg
2024-01-29 12:32:32,361 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型推理优化策略-幕布图片-789705-122117.jpg
2024-01-29 12:32:32,376 - utils.py[line:295] - INFO: RapidOCRLoader used for D:\gitrepos\langchain\Langchain-Chatchat\knowledge_base\samples\content\llm/img/大模型推理优化策略-幕布图片-923924-83386.jpg
2024-01-29 12:32:53,156 - main.py[line:158] - WARNING: Because the aspect ratio of the current image exceeds the limit (min_height or width_height_ratio), the program will skip the detection step.**

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：默认
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：默认
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： 默认
- 操作系统及版本 / Operating system and version: windows11
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
你可以尝试把python-magic-bin、unstructured卸载重新安装试一下。

**Comment by caoziyang1997** [comment]
> 你可以尝试把python-magic-bin、unstructured卸载重新安装试一下。

Traceback (most recent call last):
  File "/home/czy/project/lc-chat1/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/czy/project/lc-chat1/Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/home/czy/project/lc-chat1/Langchain-Chatchat/server/knowledge_base/migrate.py", line 110, in files2vs
    print(f"正在将 {kb_name}/{filename} 添加到向量库，共包含{len(docs)}条文档")
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 20-21: surrogates not allowed
 初始化知识库报错了   怎么解决啊

**Comment by BoFan-tunning** [comment]
> 你可以尝试把python-magic-bin、unstructured卸载重新安装试一下。
真可以

**Comment by shizhanhao** [comment]
同样bug 卡住了不用管等了大概半小时好了
