### ISSUE TITLE
[BUG] 知识库对话报错ERROR: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by FmKnight** [chatchat-space/Langchain-Chatchat#2834]
使用的对话模型是azure-api(gpt4-turbo)，对话过程中，有时候会报错ERROR: object of type 'NoneType' has no len()，此报错我看issue中很多人提到了，我也按照部分issue将torch版本从2.1.0降到了2.0.1，但还是报错，尤其是每次程序启动后第一次对话，后面有时候能够对话成功，不是每次必现，麻烦帮忙看看，十分感谢

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：2.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：azure-gpt4-turbo
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：milvus
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.10

相关日志信息：
2024-01-29 16:08:26,733 - base.py[line:36] - INFO: thread 431741 开始操作：('m3e-base', 'cuda')。初始化
2024-01-29 16:08:26,960 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /mnt/ai/models/moka-ai/m3e-base
2024-01-29 16:08:27,657 - base.py[line:40] - INFO: thread 431741 结束操作：('m3e-base', 'cuda')。初始化

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s]
INFO:     180.164.88.168:38332 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
2024-01-29 16:08:30 | INFO | stdout | INFO:     127.0.0.1:35018 - "POST /list_models HTTP/1.1" 200 OK
2024-01-29 16:08:30 | INFO | controller | names: ['http://127.0.0.1:21008'], queue_lens: [0.0], ret: http://127.0.0.1:21008
2024-01-29 16:08:30 | INFO | stdout | INFO:     127.0.0.1:35026 - "POST /get_worker_address HTTP/1.1" 200 OK
INFO:     127.0.0.1:48778 - "POST /worker_get_conv_template HTTP/1.1" 200 OK
INFO:     127.0.0.1:48786 - "POST /model_details HTTP/1.1" 200 OK
INFO:     127.0.0.1:48792 - "POST /count_token HTTP/1.1" 200 OK
2024-01-29 16:08:30 | INFO | stdout | INFO:     127.0.0.1:44314 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-29 16:08:30,109 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:18002/v1/chat/completions "HTTP/1.1 200 OK"
INFO:     127.0.0.1:48796 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2024-01-29 16:08:30 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21008/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-29 16:08:32,188 - utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/server/utils.py", line 22, in wrap_done
    await fn
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
![Uploading shot_01-29_16-09-48.png…]()

    raise e
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/mnt/ai/usrs/stephen/Langchain-Chatchat-mod/venv/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 477, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()

**Comment by FmKnight** [comment]
torch版本
![Uploading shot_01-29_16-09-48.png…]()

**Comment by zRzRzRzRzRzRzR** [comment]
这个根torch版本没有关系吧，我怀疑的是模型启动出现了问题，因为这个错误是模型没有正确返回内容

**Comment by FmKnight** [comment]
@zRzRzRzRzRzRzR 
启动日志没有看到报错日志，而且这个错误不是一直能复现，启动之后，有时模型对话是成功的，也有内容返回，但是有时就是报这个错，我看报错在引入的第三方包里，暂时也没有对第三方包进行处理。公司最近需要使用这个项目，如果方便，或者能否远程帮忙看下，感激不尽！
日志打印的模型参数如下(key等敏感信息已抹去)：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-60-generic-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.34


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['azure-api'] @ cuda
{'api_key': ' XXXX',
 'api_version': 'XXX',
 'deployment_name': ' XXX',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'max_tokens': 4096,
 'online_api': True,
 'port': 21008,
 'provider': 'AzureWorker',
 'resource_name': ' XXX',
 'worker_class': <class 'server.model_workers.azure.AzureWorker'>}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

**Comment by zRzRzRzRzRzRzR** [comment]
你这啥都没有打印啊，这看上去是正常的，不过azure这个接口很久没有人维护了

**Comment by zRzRzRzRzRzRzR** [comment]
这个是因为有时候没有访问到大模型，如果是不稳定的大改就是这个情况

**Comment by zyy26-zyy** [comment]
请问这个问题解决了吗？我也遇到同样的问题

**Comment by FmKnight** [comment]
> 请问这个问题解决了吗？我也遇到同样的问题

没有解决，目前只是在gpt流式结果返回那块，如果不返回，就手动指定答案

**Comment by FmKnight** [comment]
> 这个是因为有时候没有访问到大模型，如果是不稳定的大改就是这个情况

个人拙见这个问题是不是可以考虑看看，我看很多人也会遇到这个报错

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题没法修呀，这个报错是因为各种模型问题，结果就是chatchat请求不到统一报这个错

**Comment by haohuichen1981** [comment]
您好。我也遇到同样的问题。我用版本0.2.6的时候还能正常使用。但是到了0.2.7以及0.2.10出现同样错误。我发现配置Azure-api的参数改变了，是不是在这个过程中连接各个参数得到URL的过程出现问题了？
