### ISSUE TITLE
最新版v0.2.10 ES 访问知识库，添加文件到向量库报错list index out of range，辛苦大佬帮看看 DEFAULT_VS_TYPE = "es"

### ISSUE THREAD

**Issue by fengyaojieTTT** [chatchat-space/Langchain-Chatchat#2848]
INFO:     127.0.0.1:60298 - "POST /knowledge_base/search_docs HTTP/1.1" 500 Internal Server Error
2024-01-30 10:47:24,180 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 500 Internal Server Error"
2024-01-30 10:47:24.184 Uncaught app exception
Traceback (most recent call last):
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/fengyaojie/git/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/Users/fengyaojie/git/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 328, in knowledge_base_page
    data = [
           ^
  File "/Users/fengyaojie/git/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/chat-venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 41, in search_docs
    data = kb.list_docs(file_name=file_name, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengyaojie/git/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 213, in list_docs
    doc_info = self.get_doc_by_ids([x["id"]])[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by GuoJuan911** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39322886/b20b59b4-bdf8-42ad-a2a2-5eaf7ef5be8d)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39322886/4abbb34c-6fd1-4145-ada9-a62193eea231)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39322886/c2f51ae1-3350-406d-888d-fedf76ead7df)
看着是es 找不到这个方法 走了默认base里的了感觉
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39322886/13cd2056-3028-493e-9e20-6f803303a2f5)

**Comment by fengyaojieTTT** [comment]
Issue已在dev分支中解决并验证无误，因此我将其关闭。感谢您的反馈和贡献！如果您有任何其他问题或建议，请随时在新的Issue中提出。

**Comment by qianbaidu1266** [comment]
> Issue已在dev分支中解决并验证无误，因此我将其关闭。感谢您的反馈和贡献！如果您有任何其他问题或建议，请随时在新的Issue中提出。

怎么解决的呢，我看了代码和我本地的没有变化呀
