### ISSUE TITLE
可能是模型配置出问题了？

### ISSUE THREAD

**Issue by ALLENROGERDAI** [chatchat-space/Langchain-Chatchat#2882]
(lang) C:\GLM\Langchain-Chatchat>python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'C:\\GLM\\Langchain-Chatchat\\chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-01-31 15:27:09,844 - startup.py[line:655] - INFO: 正在启动服务：
2024-01-31 15:27:09,844 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 C:\GLM\Langchain-Chatchat\logs
C:\Anaconda3\envs\lang\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-01-31 15:27:14 | INFO | model_worker | Register to controller
2024-01-31 15:27:14 | ERROR | stderr | INFO:     Started server process [28876]
2024-01-31 15:27:14 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-31 15:27:14 | ERROR | stderr | INFO:     Application startup complete.
2024-01-31 15:27:14 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2024-01-31 15:27:15 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 0af88b04 ...
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:00<00:04,  1.28it/s]
Loading checkpoint shards:  29%|████████████████▎                                        | 2/7 [00:01<00:03,  1.29it/s]
Loading checkpoint shards:  43%|████████████████████████▍                                | 3/7 [00:02<00:03,  1.23it/s]
Loading checkpoint shards:  57%|████████████████████████████████▌                        | 4/7 [00:03<00:02,  1.31it/s]
Loading checkpoint shards:  71%|████████████████████████████████████████▋                | 5/7 [00:03<00:01,  1.25it/s]
Loading checkpoint shards:  86%|████████████████████████████████████████████████▊        | 6/7 [00:04<00:00,  1.24it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.41it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.32it/s]
2024-01-31 15:27:21 | ERROR | stderr |
2024-01-31 15:27:21 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-01-31 15:27:21 | ERROR | stderr | Traceback (most recent call last):
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\multiprocessing\process.py", line 314, in _bootstrap
2024-01-31 15:27:21 | ERROR | stderr |     self.run()
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\multiprocessing\process.py", line 108, in run
2024-01-31 15:27:21 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\GLM\Langchain-Chatchat\startup.py", line 389, in run_model_worker
2024-01-31 15:27:21 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-31 15:27:21 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\GLM\Langchain-Chatchat\startup.py", line 217, in create_model_worker_app
2024-01-31 15:27:21 | ERROR | stderr |     worker = ModelWorker(
2024-01-31 15:27:21 | ERROR | stderr |              ^^^^^^^^^^^^
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-01-31 15:27:21 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-01-31 15:27:21 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\fastchat\model\model_adapter.py", line 362, in load_model
2024-01-31 15:27:21 | ERROR | stderr |     model.to(device)
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\transformers\modeling_utils.py", line 2460, in to
2024-01-31 15:27:21 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-01-31 15:27:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
2024-01-31 15:27:21 | ERROR | stderr |     return self._apply(convert)
2024-01-31 15:27:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-01-31 15:27:21 | ERROR | stderr |     module._apply(fn)
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-01-31 15:27:21 | ERROR | stderr |     module._apply(fn)
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-01-31 15:27:21 | ERROR | stderr |     module._apply(fn)
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
2024-01-31 15:27:21 | ERROR | stderr |     param_applied = fn(param)
2024-01-31 15:27:21 | ERROR | stderr |                     ^^^^^^^^^
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
2024-01-31 15:27:21 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-01-31 15:27:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-31 15:27:21 | ERROR | stderr |   File "C:\Anaconda3\envs\lang\Lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
2024-01-31 15:27:21 | ERROR | stderr |     raise AssertionError("Torch not compiled with CUDA enabled")
2024-01-31 15:27:21 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled

使用streamlit启动则：
(lang) C:\GLM\Langchain-Chatchat>streamlit run webui.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.197.24.73:8501

2024-01-31 15:44:32,049 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-31 15:44:34,069 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-31 15:44:36,110 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-31 15:44:38,252 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-31 15:44:40,289 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-31 15:44:42,361 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-01-31 15:44:42.361 Uncaught app exception
Traceback (most recent call last):
  File "C:\Anaconda3\envs\lang\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\GLM\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "C:\GLM\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

之前大佬们说可能是我模型位置的问题，但是这是我的model config.py，应该不会错...吧？：
import os

# 可以指定一个绝对路径，统一存放所有的Embedding和LLM模型。
# 每个模型可以是一个单独的目录，也可以是某个目录下的二级子目录。
# 如果模型目录名称和 MODEL_PATH 中的 key 或 value 相同，程序会自动检测加载，无需修改 MODEL_PATH 中的路径。
MODEL_ROOT_PATH = ""

# 选用的 Embedding 名称
EMBEDDING_MODEL = "bge-large-zh"

# Embedding 模型运行设备。设为 "auto" 会自动检测(会有警告)，也可手动设定为 "cuda","mps","cpu","xpu" 其中之一。
EMBEDDING_DEVICE = "cuda"

# 选用的reranker模型
RERANKER_MODEL = "bge-reranker-large"
# 是否启用reranker模型
USE_RERANKER = False
RERANKER_MAX_LENGTH = 1024

# 如果需要在 EMBEDDING_MODEL 中增加自定义的关键字时配置
EMBEDDING_KEYWORD_FILE = "keywords.txt"
EMBEDDING_MODEL_OUTPUT_PATH = "output"

# 要运行的 LLM 名称，可以包括本地模型和在线模型。列表中本地模型将在启动项目时全部加载。
# 列表中第一个模型将作为 API 和 WEBUI 的默认模型。
# 在这里，我们使用目前主流的两个离线模型，其中，chatglm3-6b 为默认加载模型。
# 如果你的显存不足，可使用 Qwen-1_8B-Chat, 该模型 FP16 仅需 3.8G显存。

LLM_MODELS = ["chatglm3-6b", "zhipu-api", "openai-api"]
Agent_MODEL = "chatglm3-6b"

# LLM 模型运行设备。设为"auto"会自动检测(会有警告)，也可手动设定为 "cuda","mps","cpu","xpu" 其中之一。
LLM_DEVICE = "cuda"

HISTORY_LEN = 3

MAX_TOKENS = 2048

TEMPERATURE = 0.7

..............................................
MODEL_PATH = {
    "embed_model": {
        "bge-large-zh": "C:\GLM\Langchain-Chatchat\bge-large-zh",
..............................................
    "llm_model": {
        "chatglm3-6b": "C:\GLM\Langchain-Chatchat\chatglm3-6b",
..............................................
# 使用VLLM可能导致模型推理能力下降，无法完成Agent任务
VLLM_MODEL_DICT = {
    "chatglm2-6b": "THUDM/chatglm2-6b",
    "chatglm2-6b-32k": "THUDM/chatglm2-6b-32k",
    "chatglm3-6b": "THUDM/chatglm3-6b",
    "chatglm3-6b-32k": "THUDM/chatglm3-6b-32k",

这怎么办啊QwQ

操作系统：Windows-10-10.0.22621-SP0.
python版本：3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35
langchain-chatchat：0.2.10
没有使用 Docker 部署
ChatGLM3-6B
Embedding 模型bge-large-zh
还没到改向量库这步呢.....

**Comment by ALLENROGERDAI** [comment]
对了我这个其实pytorch是否兼容cuda显示的是true的，而且都是最新版有什么不兼容的...

**Comment by zRzRzRzRzRzRzR** [comment]
orch not compiled with CUDA enabled 这个你不是不兼容吗导致后面全部都没法执行，只要出现这个报错后面都跑不了了模型没有读取
