### ISSUE TITLE
[BUG] UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-5: surrogates not allowed

### ISSUE THREAD

**Issue by ipv6next** [chatchat-space/Langchain-Chatchat#2889]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：  faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information** 
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-5: surrogates not allowed
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by ipv6next** [comment]
Traceback (most recent call last):
  File "/opt/mydata/miniconda3/envs/int/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/opt/mydata/chatchat/Chatchat-0.2.9/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/opt/mydata/chatchat/Chatchat-0.2.9/webui_pages/knowledge_base/knowledge_base.py", line 222, in knowledge_base_page
    doc_grid = AgGrid(
               ^^^^^^^
  File "/opt/mydata/miniconda3/envs/int/lib/python3.11/site-packages/st_aggrid/__init__.py", line 356, in AgGrid
    row_data = __parse_row_data(data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mydata/miniconda3/envs/int/lib/python3.11/site-packages/st_aggrid/__init__.py", line 54, in __parse_row_data
    row_data = data_parameter.to_json(orient='records', date_format='iso')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mydata/miniconda3/envs/int/lib/python3.11/site-packages/pandas/core/generic.py", line 2532, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/opt/mydata/miniconda3/envs/int/lib/python3.11/site-packages/pandas/io/json/_json.py", line 191, in to_json
    ).write()
      ^^^^^^^
  File "/opt/mydata/miniconda3/envs/int/lib/python3.11/site-packages/pandas/io/json/_json.py", line 244, in write
    return dumps(
           ^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-5: surrogates not allowed

**Comment by zRzRzRzRzRzRzR** [comment]
编码问题，查看过往的issue
