### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by 8425334** [chatchat-space/Langchain-Chatchat#2891]
**问题描述 / Problem Description**
WebUi运行时出错：
```
Process WEBUI Server:
Traceback (most recent call last):
  File "H:\Dev\anaconda\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "H:\Dev\anaconda\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "H:\Project\llm\Langchain-Chatchat\startup.py", line 467, in run_webui
    p = subprocess.Popen(cmd)
        ^^^^^^^^^^^^^^^^^^^^^
  File "H:\Dev\anaconda\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "H:\Dev\anaconda\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

```
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 操作系统及版本 / Operating system and version: win11
- Python 版本 / Python version: 3.11.5(conda)
- 其他相关环境信息 / Other relevant environment information: Conda

**Comment by zRzRzRzRzRzRzR** [comment]
似乎没遇到过这个问题。。。

**Comment by mygcdr** [comment]
我也是webui启动不了，一样的报错
