### ISSUE TITLE
使用千文的在线模型时，llm对话可以正常使用但是，知识库也使用千文的模型，但是知识库问答的时候会报API通信遇到错误，这是什么原因啊？

### ISSUE THREAD

**Issue by jinhaowen123** [chatchat-space/Langchain-Chatchat#2898]
是配置的问题吗？
![微信截图_20240201150250](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/437a11b4-6bae-46ac-8023-0a2de08020e3)
![qqq](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/92e4ee73-db92-4393-afa5-c3e8a688ca56)
![1111](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/4bdd7914-4751-4f8e-9bc3-faecd1863d59)
![2222](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/c7c89ce6-3032-4b0a-bf8f-ae44021bb401)

**Comment by jinhaowen123** [comment]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "D:\llm\Langchain-Chatchat\Miniconda3\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "D:\llm\Langchain-Chatchat\server\chat\knowledge_base_chat.py", line 84, in knowledge_base_chat_iterator
    input_msg = History(role="user", content=prompt_template).to_msg_template(False)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for History
content
  none is not an allowed value (type=type_error.none.not_allowed)
2024-02-01 16:31:16,080 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by Gzj369** [comment]
我也遇到了这个问题，我的LangChain版本为v0.2.9，目前不知道原因，会不会是python第3方包版本的问题

**Comment by zRzRzRzRzRzRzR** [comment]
超过token上限了？

**Comment by liunux4odoo** [comment]
确保你 prompt_config.py 里知识库问答的模板存在。
