### ISSUE TITLE
[BUG] Windows使用pgvector 初始化知识库python init_database.py --recreate-vs报错

### ISSUE THREAD

**Issue by yumu7777777** [chatchat-space/Langchain-Chatchat#2902]
python版本3.11.5，该项目版本也是最新的 (报错 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 58: invalid continuation byte)
(docshub) PS E:\DocsHub\docshub-api> python init_database.py --recreate-vs
Traceback (most recent call last):
  File "E:\DocsHub\docshub-api\init_database.py", line 105, in <module>
    create_tables()
  File "E:\DocsHub\docshub-api\server\knowledge_base\migrate.py", line 22, in create_tables
    Base.metadata.create_all(bind=engine)
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\sql\schema.py", line 5792, in create_all
    bind._run_ddl_visitor(
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\engine\base.py", line 3238, in _run_ddl_visitor
    with self.begin() as conn:
  File "E:\software\miniconda\envs\docshub\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\engine\base.py", line 3228, in begin
    with self.connect() as conn:
         ^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\engine\base.py", line 3264, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\engine\base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__
    self.__connect()
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect
    with util.safe_reraise():
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\engine\create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\sqlalchemy\engine\default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\software\miniconda\envs\docshub\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 58: invalid continuation byte

**Comment by yumu7777777** [comment]
试了postgres 15和16 都是这个问题，linux下没有问题，求回复

**Comment by yumu7777777** [comment]
果然是这个问题，长记性了，我密码里面有@符号，感谢
