### ISSUE TITLE
Mac M1上执'python startup.py -a报错

### ISSUE THREAD

**Issue by wangkx0107** [chatchat-space/Langchain-Chatchat#2909]
Mac M1上执`'python startup.py -a`报错

**复现问题的步骤 / Steps to Reproduce**
1. 前面的操作都是ok的，没有报错，然后执行执行 'python startup.py -a'之后，正常加载模型，但是有CUDA编译相关的报错。

**实际结果 / Actual Result**
从日志的开头可以看到我的本地的环境信息：
操作系统：macOS-14.2.1-arm64-arm-64bit.
python版本：3.11.7 (main, Dec 15 2023, 12:09:56) [Clang 14.0.6 ]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

```
  # CPU
  芯片：	Apple M1 Pro
  核总数：	10（8性能和2能效）
  内存：	32 GB
  # GPU
  芯片组型号：	Apple M1 Pro
  类型：	GPU
  总线：	内建
  核总数：	16
  供应商：	Apple (0x106b)
  Metal支持：	Metal 3
  类型：	GPU
  总线：	内建
  核总数：	16
  供应商：	Apple (0x106b)
  Metal支持：	Metal 3
```

```
==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-14.2.1-arm64-arm-64bit.
python版本：3.11.7 (main, Dec 15 2023, 12:09:56) [Clang 14.0.6 ]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ mps
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ mps
==============================Langchain-Chatchat Configuration==============================


2024-02-02 22:12:26,542 - startup.py[line:655] - INFO: 正在启动服务：
2024-02-02 22:12:26,542 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /Users/joseph.wang/llm/Langchain-Chatchat/logs
/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-02 22:12:29 | INFO | model_worker | Register to controller
2024-02-02 22:12:29 | ERROR | stderr | INFO:     Started server process [29318]
2024-02-02 22:12:29 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-02 22:12:29 | ERROR | stderr | INFO:     Application startup complete.
2024-02-02 22:12:29 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-02-02 22:12:29 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 832fbe76 ...
Loading checkpoint shards:   0%|                                                                                   | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|██████████▋                                                                | 1/7 [00:00<00:03,  1.68it/s]
Loading checkpoint shards:  29%|█████████████████████▍                                                     | 2/7 [00:01<00:03,  1.29it/s]
Loading checkpoint shards:  43%|████████████████████████████████▏                                          | 3/7 [00:03<00:04,  1.15s/it]
Loading checkpoint shards:  57%|██████████████████████████████████████████▊                                | 4/7 [00:05<00:05,  1.80s/it]
Loading checkpoint shards:  71%|█████████████████████████████████████████████████████▌                     | 5/7 [00:07<00:03,  1.89s/it]
Loading checkpoint shards:  86%|████████████████████████████████████████████████████████████████▎          | 6/7 [00:10<00:02,  2.20s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████| 7/7 [00:11<00:00,  1.84s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████| 7/7 [00:11<00:00,  1.69s/it]
2024-02-02 22:12:41 | ERROR | stderr |
2024-02-02 22:12:41 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-02 22:12:41 | ERROR | stderr | Traceback (most recent call last):
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-02 22:12:41 | ERROR | stderr |     self.run()
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-02 22:12:41 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/llm/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-02-02 22:12:41 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-02 22:12:41 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/llm/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-02-02 22:12:41 | ERROR | stderr |     worker = ModelWorker(
2024-02-02 22:12:41 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-02 22:12:41 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-02 22:12:41 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 362, in load_model
2024-02-02 22:12:41 | ERROR | stderr |     model.to(device)
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2597, in to
2024-02-02 22:12:41 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-02-02 22:12:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
2024-02-02 22:12:41 | ERROR | stderr |     return self._apply(convert)
2024-02-02 22:12:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-02 22:12:41 | ERROR | stderr |     module._apply(fn)
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-02 22:12:41 | ERROR | stderr |     module._apply(fn)
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-02 22:12:41 | ERROR | stderr |     module._apply(fn)
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
2024-02-02 22:12:41 | ERROR | stderr |     param_applied = fn(param)
2024-02-02 22:12:41 | ERROR | stderr |                     ^^^^^^^^^
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
2024-02-02 22:12:41 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-02-02 22:12:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-02 22:12:41 | ERROR | stderr |   File "/Users/joseph.wang/miniconda3/envs/chatglm2/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
2024-02-02 22:12:41 | ERROR | stderr |     raise AssertionError("Torch not compiled with CUDA enabled")
2024-02-02 22:12:41 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled

```

**Comment by wangkx0107** [comment]
我也看了下一些资料，我的mac pro m1 确实是不支持cuda的，因为这个是英伟达显卡的标识。 如果[这里](https://github.com/THUDM/ChatGLM2-6B?tab=readme-ov-file#mac-%E9%83%A8%E7%BD%B2)的workaroud，是否也有类似的方法呢

**Comment by zRzRzRzRzRzRzR** [comment]
那你应该按照mps来设置，torch要去官网按照m1的妆

**Comment by wangkx0107** [comment]
> 那你应该按照mps来设置，torch要去官网按照m1的装

这块安装也没问题呢，通过py也验证过了呢。想求助下您这边，还可以从哪些方面看呢？

**Comment by zRzRzRzRzRzRzR** [comment]
你这没有cuda就不能装有torch的cuda，然后启动的时候model config也要改成mps
