### ISSUE TITLE
[BUG] 创建知识库失败

### ISSUE THREAD

**Issue by LeoQianQY** [chatchat-space/Langchain-Chatchat#2921]
**问题描述 / Problem Description**
创建知识库失败，但是列表里可以选择这个没创好的知识库

**预期的结果 / Expected Result**
正常创建知识库

**实际结果 / Actual Result**
创建知识库失败，但是列表里可以选择这个没创好的知识库

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456) v2.0.1
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): 否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): text2vec-large-chinese
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: python 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
2024-02-04 11:17:51,952 - faiss_cache.py[line:92] - INFO: loading vector store in '111/vector_store/text2vec' from disk.
2024-02-04 11:17:51,953 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: text2vec
2024-02-04 11:17:51,953 - SentenceTransformer.py[line:805] - WARNING: No sentence-transformers model found with name text2vec. Creating a new one with MEAN pooling.
2024-02-04 11:17:51,953 - embeddings_api.py[line:39] - ERROR: text2vec does not appear to have a file named config.json. Checkout 'https://huggingface.co/text2vec/None' for available files.
2024-02-04 11:17:51,953 - kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by JackieGLQ** [comment]
(LangChainChat) root@autodl-container-95f2448374-de230908:~/autodl-tmp/Langchain-Chatchat# python init_database.py --recreate-vs
recreating all vector stores
2024-02-04 13:48:28,296 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh-v1.5' from disk.
2024-02-04 13:48:28,519 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: bge-large-zh-v1.5
2024-02-04 13:48:29,023 - embeddings_api.py[line:39] - ERROR: Error while deserializing header: HeaderTooLarge
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/migrate.py", line 121, in folder2db
    kb.create_kb()
  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 81, in create_kb
    self.do_create_kb()
  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 102, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 60, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/LangChainChat/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/LangChainChat/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 959, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 425, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in norm
  File "/root/miniconda3/envs/LangChainChat/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 2541, in norm
    s = (x.conj() * x).real
         ^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method


也是初始化知识库错误！

**Comment by luoriusheng** [comment]
试试把faiss_cache.py里的normalize_L2=True，都改成False，有两处

**Comment by LeoQianQY** [comment]
> 试试把faiss_cache.py里的normalize_L2=True，都改成False，有两处

谢谢，但试了还是不行

**Comment by LeoQianQY** [comment]
> 试试把faiss_cache.py里的normalize_L2=True，都改成False，有两处

谢谢，但我试了还是不行···知识库/vector_store/text2vec里始终是空的，但我配置了text2vec的

**Comment by moster33** [comment]
我与你的情况类似，我使用了在线embeding模型，在线llm，本地milvus向量库，初始化数据库的时候，也报这个错误。不知道是为什么

**Comment by zRzRzRzRzRzRzR** [comment]
只要创建表格了就会显示，但是如果你知识库创建失败你后续的操作都是执行不了的

**Comment by ocpinfo** [comment]
> 试试把faiss_cache.py里的normalize_L2=True，都改成False，有两处

改成False之后虽然可以创建知识库成功，但是知识库问答总是找不到任何内容。怎么办？

**Comment by zRzRzRzRzRzRzR** [comment]
应该是要true的，不然搜不到东西的，因为有一个score得改，在kb_config中

**Comment by ocpinfo** [comment]
我查了kb_config.py中设置的就是CHUNK_SIZE = 250啊，那是要把SCORE_THRESHOLD = 1.0改成250吗？
