### ISSUE TITLE
使用在线模型通义千问,同时配置es,报错!

### ISSUE THREAD

**Issue by lvxiangjin** [chatchat-space/Langchain-Chatchat#2923]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\env\my_env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\env\my_env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\starlette\applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\env\my_env\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\env\my_env\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\env\my_env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\env\my_env\lib\site-packages\starlette\routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\starlette\routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\env\my_env\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\env\my_env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\env\my_env\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "D:\env\my_env\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "D:\env\my_env\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "D:\env\my_env\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\env\my_env\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\env\my_env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\env\my_env\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\env\my_env\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\env\my_env\py\Langchain-Chatchat-master\server\knowledge_base\kb_api.py", line 29, in create_kb
    kb = KBServiceFactory.get_service(knowledge_base_name, vector_store_type, embed_model)
  File "D:\env\my_env\py\Langchain-Chatchat-master\server\knowledge_base\kb_service\base.py", line 321, in get_service
    return ESKBService(kb_name, embed_model=embed_model)
  File "D:\env\my_env\py\Langchain-Chatchat-master\server\knowledge_base\kb_service\base.py", line 63, in __init__
    self.do_init()
  File "D:\env\my_env\py\Langchain-Chatchat-master\server\knowledge_base\kb_service\es_kb_service.py", line 25, in do_init
    self.embeddings_model = load_local_embeddings(self.embed_model, EMBEDDING_DEVICE)
  File "D:\env\my_env\py\Langchain-Chatchat-master\server\utils.py", line 669, in load_local_embeddings
    return embeddings_pool.load_embeddings(model=model, device=device)
  File "D:\env\my_env\py\Langchain-Chatchat-master\server\knowledge_base\kb_cache\base.py", line 153, in load_embeddings
    embeddings = HuggingFaceEmbeddings(model_name=get_model_path(model),
  File "D:\env\my_env\lib\site-packages\langchain_community\embeddings\huggingface.py", line 55, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_name
  none is not an allowed value (type=type_error.none.not_allowed)
  
![QQ截图20240204145612](https://github.com/chatchat-space/Langchain-Chatchat/assets/58935204/1924a19d-5007-4a04-b7a8-515d2213361e)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58935204/e48a571e-4a24-4202-92b4-b2782bd62b17)

**Comment by lvxiangjin** [comment]
求求了  作者看见了  回答一下 谢谢

**Comment by lvxiangjin** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58935204/257056a7-d04a-4525-961e-c6e043103d9e)
https://github.com/chatchat-space/Langchain-Chatchat/issues/2343
找到了过去的文档  解决了在线模型和es不能一起用的问题  886
