### ISSUE TITLE
有时候可以运行，有时候就报错：

### ISSUE THREAD

**Issue by immmor** [chatchat-space/Langchain-Chatchat#2928]
F:\Langchain-Chatchat>echo "Start VENV"
"Start VENV"

F:\Langchain-Chatchat>call Miniconda3\Scripts\activate.bat

(base) F:\Langchain-Chatchat>goto :run

(base) F:\Langchain-Chatchat>echo "Start API + WebUI"
"Start API + WebUI"

(base) F:\Langchain-Chatchat>python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9-preview
langchain版本：0.0.344. fastchat版本：0.2.33

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-1_8B-Chat-Int4'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'F:\\Langchain-Chatchat\\models\\LLM\\Qwen-1_8B-Chat-Int4',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-02-04 21:16:25,047 - startup.py[line:651] - INFO: 正在启动服务：
2024-02-04 21:16:25,048 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 F:\Langchain-Chatchat\logs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\Langchain-Chatchat\Miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "F:\Langchain-Chatchat\Miniconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "F:\Langchain-Chatchat\Miniconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "F:\Langchain-Chatchat\Miniconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "F:\Langchain-Chatchat\Miniconda3\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "F:\Langchain-Chatchat\Miniconda3\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "F:\Langchain-Chatchat\Miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Langchain-Chatchat\startup.py", line 21, in <module>
    from configs import (
  File "F:\Langchain-Chatchat\configs\__init__.py", line 1, in <module>
    from .basic_config import *
  File "F:\Langchain-Chatchat\configs\basic_config.py", line 29, in <module>
    shutil.rmtree(BASE_TEMP_DIR)
  File "F:\Langchain-Chatchat\Miniconda3\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "F:\Langchain-Chatchat\Miniconda3\lib\shutil.py", line 624, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "F:\Langchain-Chatchat\Miniconda3\lib\shutil.py", line 622, in _rmtree_unsafe
    os.rmdir(path)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\chatchat'

**Comment by immmor** [comment]
有时候可以打开webui界面。但是一回复就报错：
2024-02-04 21:21:59,922 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-02-04 21:22:02,159 - _base_client.py[line:1410] - INFO: Retrying request to /chat/completions in 0.865284 seconds
2024-02-04 21:22:05,031 - _base_client.py[line:1410] - INFO: Retrying request to /chat/completions in 1.806337 seconds
2024-02-04 21:22:08,844 - utils.py[line:24] - ERROR: Connection error.
Traceback (most recent call last):
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\anyio\_core\_sockets.py", line 167, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 1627, in connect_tcp
    await get_running_loop().create_connection(
  File "F:\Langchain-Chatchat\Miniconda3\lib\asyncio\base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "F:\Langchain-Chatchat\Miniconda3\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "F:\Langchain-Chatchat\Miniconda3\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "F:\Langchain-Chatchat\Miniconda3\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "F:\Langchain-Chatchat\Miniconda3\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "F:\Langchain-Chatchat\Miniconda3\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_backends\anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\anyio\_core\_sockets.py", line 225, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_async\connection_pool.py", line 268, in handle_async_request
    raise exc
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_async\connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_backends\anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "F:\Langchain-Chatchat\Miniconda3\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\_base_client.py", line 1332, in _request
    response = await self._client.send(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "F:\Langchain-Chatchat\Miniconda3\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Langchain-Chatchat\server\utils.py", line 22, in wrap_done
    await fn
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\chains\base.py", line 381, in acall
    raise e
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\chains\base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\chat_models\openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\chat_models\openai.py", line 472, in _astream
    async for chunk in await acompletion_with_retry(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\chat_models\openai.py", line 101, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\resources\chat\completions.py", line 1199, in create
    return await self._post(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\_base_client.py", line 1532, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\_base_client.py", line 1306, in request
    return await self._request(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\_base_client.py", line 1379, in _request
    return await self._retry_request(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\_base_client.py", line 1414, in _retry_request
    return await self._request(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\_base_client.py", line 1379, in _request
    return await self._retry_request(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\_base_client.py", line 1414, in _retry_request
    return await self._request(
  File "F:\Langchain-Chatchat\Miniconda3\lib\site-packages\openai\_base_client.py", line 1388, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
2024-02-04 21:22:09,047 - utils.py[line:27] - ERROR: APIConnectionError: Caught exception: Connection error.

**Comment by immmor** [comment]
这是完全成功的日志：
F:\Langchain-Chatchat>echo "Start VENV"
"Start VENV"

F:\Langchain-Chatchat>call Miniconda3\Scripts\activate.bat

(base) F:\Langchain-Chatchat>goto :run

(base) F:\Langchain-Chatchat>echo "Start API + WebUI"
"Start API + WebUI"

(base) F:\Langchain-Chatchat>python startup.py -a


==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9-preview
langchain版本：0.0.344. fastchat版本：0.2.33


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-1_8B-Chat-Int4'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'F:\\Langchain-Chatchat\\models\\LLM\\Qwen-1_8B-Chat-Int4',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================


2024-02-04 21:23:50,128 - startup.py[line:651] - INFO: 正在启动服务：
2024-02-04 21:23:50,129 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 F:\Langchain-Chatchat\logs
2024-02-04 21:24:06 | ERROR | stderr | INFO:     Started server process [17316]
2024-02-04 21:24:06 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-04 21:24:06 | ERROR | stderr | INFO:     Application startup complete.
2024-02-04 21:24:06 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2024-02-04 21:24:09 | INFO | model_worker | Loading the model ['Qwen-1_8B-Chat-Int4'] on worker 70bfe67b ...
Using `disable_exllama` is deprecated and will be removed in version 4.37. Use `use_exllama` instead and specify the version with `exllama_config`.The value of `use_exllama` will be overwritten by `disable_exllama` passed in `GPTQConfig` or stored in your config file.
2024-02-04 21:24:14 | WARNING | transformers_modules.Qwen-1_8B-Chat-Int4.modeling_qwen | Try importing flash-attention for faster inference...
2024-02-04 21:24:14 | WARNING | transformers_modules.Qwen-1_8B-Chat-Int4.modeling_qwen | Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
2024-02-04 21:24:14 | WARNING | transformers_modules.Qwen-1_8B-Chat-Int4.modeling_qwen | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
2024-02-04 21:24:14 | WARNING | transformers_modules.Qwen-1_8B-Chat-Int4.modeling_qwen | Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
2024-02-04 21:24:19 | INFO | model_worker | Register to controller
INFO:     Started server process [18708]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)


==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9-preview
langchain版本：0.0.344. fastchat版本：0.2.33


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-1_8B-Chat-Int4'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'F:\\Langchain-Chatchat\\models\\LLM\\Qwen-1_8B-Chat-Int4',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================



  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

2024-02-04 21:24:56,425 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52137 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-04 21:24:56,430 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-02-04 21:24:56,562 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52137 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-04 21:24:56,566 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52137 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-02-04 21:24:56,609 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-02-04 21:25:00,459 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52142 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-04 21:25:00,463 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-02-04 21:25:00,592 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52142 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-04 21:25:00,597 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52142 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-02-04 21:25:00,640 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52160 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:52160 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:52160 - "GET /swagger-ui.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52161 - "GET /swagger-ui-bundle.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52161 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:52160 - "GET /favicon.png HTTP/1.1" 200 OK

**Comment by zRzRzRzRzRzRzR** [comment]
这个报错就是没有跟大模型链接成功，找不到临时文件那个可以不管，应该是个警告

**Comment by YangFW** [comment]
> 大模型链接成功，找不到临时文件

请问你的这个问题解决了吗 ，await fn 这个问题，我现在是在调用/chat/chat请求时，如果history里带有内容会报这个错，如果没有内容是正常成功的
