### ISSUE TITLE
[BUG] 2卡4090加载本地模型时报错

### ISSUE THREAD

**Issue by zhitianzhidao** [chatchat-space/Langchain-Chatchat#2931]
**问题描述 / Problem Description**
加载本地大模型报错：
2024-02-05 13:07:32 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-05 13:07:32 | ERROR | stderr | Traceback (most recent call last):
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\multiprocessing\process.py", line 314, in _bootstrap
2024-02-05 13:07:32 | ERROR | stderr |     self.run()
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\multiprocessing\process.py", line 108, in run
2024-02-05 13:07:32 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Langchain-Chatchat\startup.py", line 389, in run_model_worker
2024-02-05 13:07:32 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-05 13:07:32 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Langchain-Chatchat\startup.py", line 217, in create_model_worker_app
2024-02-05 13:07:32 | ERROR | stderr |     worker = ModelWorker(
2024-02-05 13:07:32 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-02-05 13:07:32 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-05 13:07:32 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\fastchat\model\model_adapter.py", line 362, in load_model
2024-02-05 13:07:32 | ERROR | stderr |     model.to(device)
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\transformers\modeling_utils.py", line 2597, in to
2024-02-05 13:07:32 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-02-05 13:07:32 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
2024-02-05 13:07:32 | ERROR | stderr |     return self._apply(convert)
2024-02-05 13:07:32 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-02-05 13:07:32 | ERROR | stderr |     module._apply(fn)
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-02-05 13:07:32 | ERROR | stderr |     module._apply(fn)
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-02-05 13:07:32 | ERROR | stderr |     module._apply(fn)
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
2024-02-05 13:07:32 | ERROR | stderr |     param_applied = fn(param)
2024-02-05 13:07:32 | ERROR | stderr |                     ^^^^^^^^^
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
2024-02-05 13:07:32 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-02-05 13:07:32 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-05 13:07:32 | ERROR | stderr |   File "C:\Users\PS\anaconda3\envs\chatglm3-6b\Lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
2024-02-05 13:07:32 | ERROR | stderr |     raise AssertionError("Torch not compiled with CUDA enabled")
2024-02-05 13:07:32 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled
**复现问题的步骤 / Steps to Reproduce**
1. model_config中进行如下设定：
2. 
MODEL_ROOT_PATH = r"C:\LLM\model_db" 

LLM_DEVICE = "cuda"

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：最新版
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm3-6b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: win11
- Python 版本 / Python version:3.11

**Comment by zhitianzhidao** [comment]
我这边是已经有安装过cuda12.2了

**Comment by zRzRzRzRzRzRzR** [comment]
Torch not compiled with CUDA enabled 肯定是环境问题了，建议检查环境
另外，fscaht是单卡启动不支持多卡的
你得用vllm启动

**Comment by zhitianzhidao** [comment]
环境的话感觉应该没问题啊
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_03:10:21_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0

**Comment by zRzRzRzRzRzRzR** [comment]
这个报错都出现了只能是环境了，具体的问题你可能要根据你的系统和pytorch文档查询

**Comment by LiuZheng60** [comment]
configs/server_config.py中FSCHAT_MODEL_WORKERS的"chatglm3-6b": {
"device":"cuda" ,
},改为cpu"chatglm3-6b": {
"device":"cpu" ,
},
model_config.py中的EMBEDDING_DEVICE = "cpu"，LLM_DEVICE = "cpu"，也都改为cpu
