### ISSUE TITLE
对话时输入问题报错ERROR: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by zhifeng-ff** [chatchat-space/Langchain-Chatchat#2942]
**问题描述 / Problem Description**
对话时输入问题报错ERROR: object of type 'NoneType' has no len()

**复现问题的步骤 / Steps to Reproduce**
1. 对话框输入问题
2. chatchat回答为空
3. 后台报错ERROR: object of type 'NoneType' has no len()

**实际结果 / Actual Result**
完整log如下：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-92-generic-x86_64-with-glibc2.31.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-02-06 11:21:41,855 - startup.py[line:655] - INFO: 正在启动服务：
2024-02-06 11:21:41,855 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /home/yzrt/Langchain-Chatchat/logs
/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:116: LangChainDeprecationWarning: 模型启动功能将于 LangChatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-06 11:21:46 | ERROR | stderr | INFO:     Started server process [23082]
2024-02-06 11:21:46 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-06 11:21:46 | ERROR | stderr | INFO:     Application startup complete.
2024-02-06 11:21:46 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-02-06 11:21:46 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 1caa21f7 ...
  0%|                                                                                                                                     | 0/7 [00:00<?, 
 14%|█████████████████▊                                                                                                           | 1/7 [00:01<00:11,  1.9
 29%|███████████████████████████████████▋                                                                                         | 2/7 [00:04<00:12,  2.5
 43%|█████████████████████████████████████████████████████▌                                                                       | 3/7 [00:08<00:11,  2.8
 57%|███████████████████████████████████████████████████████████████████████▍                                                     | 4/7 [00:11<00:09,  3.0
 71%|█████████████████████████████████████████████████████████████████████████████████████████▎                                   | 5/7 [00:14<00:06,  3.1
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 6/7 [00:18<00:03,  3.2
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:21<00:00,  3.2
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:21<00:00,  3.0
2024-02-06 11:22:12 | ERROR | stderr | 
2024-02-06 11:22:12 | INFO | model_worker | Register to controller
INFO:     Started server process [23231]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-92-generic-x86_64-with-glibc2.31.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2024-02-06 11:22:21,218 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:50712 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-06 11:22:21,220 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-02-06 11:22:21,345 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:50712 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-06 11:22:21,347 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:50712 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-02-06 11:22:21,354 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-02-06 11:22:29,219 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54962 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-06 11:22:29,220 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-02-06 11:22:29,244 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54962 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-06 11:22:29,245 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54962 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-02-06 11:22:29,254 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54962 - "POST /chat/chat HTTP/1.1" 200 OK
/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:116: LangChainDeprecationWarning: The class `langchain_ity.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in thchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-02-06 11:22:29,319 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-02-06 11:22:29 | INFO | stdout | INFO:     127.0.0.1:40316 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-02-06 11:22:29,359 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-02-06 11:22:29 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-02-06 11:22:31,110 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/yzrt/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/yzrt/anaconda3/envs/ChatChat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-02-06 11:22:31,112 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B int8
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:ubuntu20.04
- Python 版本 / Python version:3.10.13
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
这个是没访问到模型

**Comment by zhifeng-ff** [comment]
> 这个是没访问到模型
请问可以int4量化吗   我看startup里只有int8   是不是需要下载int4的模型

**Comment by zRzRzRzRzRzRzR** [comment]
没有支持

**Comment by zshmbbs** [comment]
> 这个是没访问到模型

我也又同样的问题，是没访问到什么模型呢？启动的时候，已经找到模型了。
