### ISSUE TITLE
webui

### ISSUE THREAD

**Issue by yi-si-hua** [chatchat-space/Langchain-Chatchat#2951]
运行startup的时候完全没有问题，还能分别正常进入服务器网页状态和api页面。
但是streamlit run webui.py时，就会被电脑里不知道什么东西拦截。我把防火墙关了，360卸了，还是继续被拦截。
报错如下：
2024-02-06 17:35:30,002 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-06 17:35:32,035 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-06 17:35:34,053 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\langchain\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\git\Langchain-Chatchat-master\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\git\Langchain-Chatchat-master\webui_pages\dialogue\dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
TypeError: 'NoneType' object is not iterable
![winerror](https://github.com/chatchat-space/Langchain-Chatchat/assets/158030256/375f6aa8-5b7b-4e76-ac42-af7d88fd5909)
![winerror](https://github.com/chatchat-space/Langchain-Chatchat/assets/158030256/bb85f0e9-5d7d-48ec-893f-25826109f221)

**Comment by zRzRzRzRzRzRzR** [comment]
server config没有正确配置吧

**Comment by Jsonzhang20** [comment]
我也碰到上述相同问题，**python startup.py -a** 各项功能运行正常，**python startup.py -w**与**streamlit run webui.py**报相同错误，如下

(venv) PS D:\workscope\Langchain-Chatchat> streamlit run webui.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.76:8501

2024-02-07 16:42:31,884 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-07 16:42:33,938 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-07 16:42:35,956 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-07 16:42:38,121 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-07 16:42:40,131 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-07 16:42:42,157 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-07 16:42:42.158 Uncaught app exception
Traceback (most recent call last):
  File "D:\workscope\Langchain-Chatchat\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\workscope\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\workscope\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 169, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable


**configs\model_config.py**配置如下：

ODEL_ROOT_PATH = "/workscope/Langchain-Chatchat/models"   #相关模型都放在该目录下，包括 bge-large-zh，chatglm3-6b，Qwen-7B-Chat

EMBEDDING_MODEL = "bge-large-zh"  # "bge-large-zh-v1.5"
EMBEDDING_DEVICE = "cuda"

LLM_MODELS = ["chatglm3-6b", "Qwen-7B-Chat", "openai-api"]
Agent_MODEL = "chatglm3-6b" # None

MODEL_PATH = {
    "embed_model": {
        "ernie-tiny": "nghuyong/ernie-3.0-nano-zh",
        
        # "bge-large-zh": "BAAI/bge-large-zh",
        "bge-large-zh": "bge-large-zh",
        
    "llm_model": {
        "chatglm2-6b": "THUDM/chatglm2-6b",
        "chatglm2-6b-32k": "THUDM/chatglm2-6b-32k",
        # "chatglm3-6b": "THUDM/chatglm3-6b",
        "chatglm3-6b": "chatglm3-6b",
        "chatglm3-6b-32k": "THUDM/chatglm3-6b-32k",

        "Qwen-1_8B-Chat": "Qwen/Qwen-1_8B-Chat",
        # "Qwen-7B-Chat": "Qwen/Qwen-7B-Chat",
        "Qwen-7B-Chat": "Qwen-7B-Chat",

**configs\**其他配置文件没修改，都是默认配置


环境信息：python3.11.5,win11,其他按requirements.txt pip install 安装

**Comment by zRzRzRzRzRzRzR** [comment]
winsows估计是端口被锁了吧

**Comment by yi-si-hua** [comment]
我在必应上搜到一个和我们类似的。然后他的问题其实是模型提交不上去。把embedding moedl默认的bge-large-zh-v1.5改为了bge-large-zh，他就跑通了。但是我不行，我还是跑不通。你也可以试一试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月7日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] webui (Issue #2951)





 
我也碰到上述相同问题，python startup.py -a 各项功能运行正常，python startup.py -w与streamlit run webui.py报相同错误，如下
 
(venv) PS D:\workscope\Langchain-Chatchat&gt; streamlit run webui.py
 
You can now view your Streamlit app in your browser.
 
Local URL: http://localhost:8501
 Network URL: http://192.168.1.76:8501
 
2024-02-07 16:42:31,884 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 2024-02-07 16:42:33,938 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 2024-02-07 16:42:35,956 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 2024-02-07 16:42:38,121 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 2024-02-07 16:42:40,131 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 2024-02-07 16:42:42,157 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 2024-02-07 16:42:42.158 Uncaught app exception
 Traceback (most recent call last):
 File "D:\workscope\Langchain-Chatchat\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
 exec(code, module.dict)
 File "D:\workscope\Langchain-Chatchat\webui.py", line 64, in 
 pages[selected_page]["func"](api=api, is_lite=is_lite)
 File "D:\workscope\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 169, in dialogue_page
 running_models = list(api.list_running_models())
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: 'NoneType' object is not iterable
 
configs\model_config.py配置如下：
 
ODEL_ROOT_PATH = "/workscope/Langchain-Chatchat/models"   #相关模型都放在该目录下，包括 bge-large-zh，chatglm3-6b，Qwen-7B-Chat
 
EMBEDDING_MODEL = "bge-large-zh"  # "bge-large-zh-v1.5"
 EMBEDDING_DEVICE = "cuda"
 
LLM_MODELS = ["chatglm3-6b", "Qwen-7B-Chat", "openai-api"]
 Agent_MODEL = "chatglm3-6b" # None
 
MODEL_PATH = {
 "embed_model": {
 "ernie-tiny": "nghuyong/ernie-3.0-nano-zh",
     # "bge-large-zh": "BAAI/bge-large-zh",     "bge-large-zh": "bge-large-zh",      "llm_model": {     "chatglm2-6b": "THUDM/chatglm2-6b",     "chatglm2-6b-32k": "THUDM/chatglm2-6b-32k",     # "chatglm3-6b": "THUDM/chatglm3-6b",     "chatglm3-6b": "chatglm3-6b",     "chatglm3-6b-32k": "THUDM/chatglm3-6b-32k",     "Qwen-1_8B-Chat": "Qwen/Qwen-1_8B-Chat",     # "Qwen-7B-Chat": "Qwen/Qwen-7B-Chat",     "Qwen-7B-Chat": "Qwen-7B-Chat",  
**configs**其他配置文件没修改，都是默认配置
 
环境信息：python3.11.5,win11,其他按requirements.txt pip install 安装

**Comment by liunux4odoo** [comment]
webui.py 依赖于 api.py，python startup.py -a 会同时启动所有的服务，单独启动 streamlit run webui.py是不行的。
