### ISSUE TITLE
[BUG] Langchain-chatchat 一键启动项目 python startup.py -a 报错

### ISSUE THREAD

**Issue by PedroNeal** [chatchat-space/Langchain-Chatchat#2963]
**问题描述 / Problem Description**
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'model/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-02-07 17:12:32,808 - startup.py[line:655] - INFO: 正在启动服务：
2024-02-07 17:12:32,808 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /home/david/20240207/Langchain-Chatchat/logs
/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-07 17:12:42 | ERROR | stderr | INFO:     Started server process [6205]
2024-02-07 17:12:42 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-07 17:12:42 | ERROR | stderr | INFO:     Application startup complete.
2024-02-07 17:12:42 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2024-02-07 17:12:43 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker aa19f252 ...
Loading checkpoint shards:   0%|                                                                                         | 0/7 [00:00<?, ?it/s]
2024-02-07 17:12:43 | ERROR | stderr | /home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
2024-02-07 17:12:43 | ERROR | stderr |   return self.fget.__get__(instance, owner)()
Loading checkpoint shards:  14%|███████████▌                                                                     | 1/7 [00:00<00:04,  1.48it/s]
Loading checkpoint shards:  29%|███████████████████████▏                                                         | 2/7 [00:01<00:03,  1.46it/s]
Loading checkpoint shards:  43%|██████████████████████████████████▋                                              | 3/7 [00:02<00:02,  1.38it/s]
Loading checkpoint shards:  57%|██████████████████████████████████████████████▎                                  | 4/7 [00:02<00:02,  1.33it/s]
Loading checkpoint shards:  71%|█████████████████████████████████████████████████████████▊                       | 5/7 [00:03<00:01,  1.23it/s]
Loading checkpoint shards:  86%|█████████████████████████████████████████████████████████████████████▍           | 6/7 [00:04<00:00,  1.23it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.42it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.36it/s]
2024-02-07 17:12:48 | ERROR | stderr |
2024-02-07 17:12:49 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-07 17:12:49 | ERROR | stderr | Traceback (most recent call last):
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/cuda/__init__.py", line 311, in _lazy_init
2024-02-07 17:12:49 | ERROR | stderr |     queued_call()
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/cuda/__init__.py", line 180, in _check_capability
2024-02-07 17:12:49 | ERROR | stderr |     capability = get_device_capability(d)
2024-02-07 17:12:49 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/cuda/__init__.py", line 435, in get_device_capability
2024-02-07 17:12:49 | ERROR | stderr |     prop = get_device_properties(device)
2024-02-07 17:12:49 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/cuda/__init__.py", line 453, in get_device_properties
2024-02-07 17:12:49 | ERROR | stderr |     return _get_device_properties(device)  # type: ignore[name-defined]
2024-02-07 17:12:49 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr | RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=
2024-02-07 17:12:49 | ERROR | stderr |
2024-02-07 17:12:49 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-02-07 17:12:49 | ERROR | stderr |
2024-02-07 17:12:49 | ERROR | stderr | Traceback (most recent call last):
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-07 17:12:49 | ERROR | stderr |     self.run()
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-07 17:12:49 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/20240207/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-02-07 17:12:49 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-07 17:12:49 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/20240207/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-02-07 17:12:49 | ERROR | stderr |     worker = ModelWorker(
2024-02-07 17:12:49 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-07 17:12:49 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-07 17:12:49 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 362, in load_model
2024-02-07 17:12:49 | ERROR | stderr |     model.to(device)
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2595, in to
2024-02-07 17:12:49 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-02-07 17:12:49 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
2024-02-07 17:12:49 | ERROR | stderr |     return self._apply(convert)
2024-02-07 17:12:49 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-07 17:12:49 | ERROR | stderr |     module._apply(fn)
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-07 17:12:49 | ERROR | stderr |     module._apply(fn)
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-07 17:12:49 | ERROR | stderr |     module._apply(fn)
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
2024-02-07 17:12:49 | ERROR | stderr |     param_applied = fn(param)
2024-02-07 17:12:49 | ERROR | stderr |                     ^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
2024-02-07 17:12:49 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-02-07 17:12:49 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/cuda/__init__.py", line 317, in _lazy_init
2024-02-07 17:12:49 | ERROR | stderr |     raise DeferredCudaCallError(msg) from e
2024-02-07 17:12:49 | ERROR | stderr | torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=
2024-02-07 17:12:49 | ERROR | stderr |
2024-02-07 17:12:49 | ERROR | stderr | CUDA call was originally invoked at:
2024-02-07 17:12:49 | ERROR | stderr |
2024-02-07 17:12:49 | ERROR | stderr |   File "<string>", line 1, in <module>
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
2024-02-07 17:12:49 | ERROR | stderr |     exitcode = _main(fd, parent_sentinel)
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/spawn.py", line 131, in _main
2024-02-07 17:12:49 | ERROR | stderr |     prepare(preparation_data)
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/spawn.py", line 246, in prepare
2024-02-07 17:12:49 | ERROR | stderr |     _fixup_main_from_path(data['init_main_from_path'])
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
2024-02-07 17:12:49 | ERROR | stderr |     main_content = runpy.run_path(main_path,
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen runpy>", line 291, in run_path
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen runpy>", line 98, in _run_module_code
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/20240207/Langchain-Chatchat/startup.py", line 34, in <module>
2024-02-07 17:12:49 | ERROR | stderr |     from server.utils import (fschat_controller_address, fschat_model_worker_address,
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/20240207/Langchain-Chatchat/server/utils.py", line 28, in <module>
2024-02-07 17:12:49 | ERROR | stderr |     import torch
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/__init__.py", line 1332, in <module>
2024-02-07 17:12:49 | ERROR | stderr |     _C._initExtension(manager_path())
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-02-07 17:12:49 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/cuda/__init__.py", line 244, in <module>
2024-02-07 17:12:49 | ERROR | stderr |     _lazy_call(_check_capability)
2024-02-07 17:12:49 | ERROR | stderr |   File "/home/david/anaconda3/envs/chat/lib/python3.11/site-packages/torch/cuda/__init__.py", line 241, in _lazy_call
2024-02-07 17:12:49 | ERROR | stderr |     _queued_calls.append((callable, traceback.format_stack()))
2024-02-07 17:12:49 | ERROR | stderr |
^C2024-02-07 17:14:37,796 - startup.py[line:855] - WARNING: Sending SIGKILL to {}
2024-02-07 17:14:37,796 - startup.py[line:855] - WARNING: Sending SIGKILL to {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (6206)' pid=6206 parent=5971 stopped exitcode=1 daemon>}
2024-02-07 17:14:37,797 - startup.py[line:855] - WARNING: Sending SIGKILL to <Process name='controller (6117)' pid=6117 parent=5971 started daemon>
2024-02-07 17:14:37,800 - startup.py[line:855] - WARNING: Sending SIGKILL to <Process name='openai_api (6205)' pid=6205 parent=5971 started daemon>
2024-02-07 17:14:37,802 - startup.py[line:855] - WARNING: Sending SIGKILL to <Process name='API Server' parent=5971 initial daemon>
Traceback (most recent call last):
  File "/home/david/20240207/Langchain-Chatchat/startup.py", line 767, in start_main_server
    e.wait()
  File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/managers.py", line 1097, in wait
    return self._callmethod('wait', (timeout,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/managers.py", line 822, in _callmethod
    kind, result = conn.recv()
                   ^^^^^^^^^^^
  File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/connection.py", line 395, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/20240207/Langchain-Chatchat/startup.py", line 612, in f
    raise KeyboardInterrupt(f"{signalname} received")
KeyboardInterrupt: SIGINT received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/20240207/Langchain-Chatchat/startup.py", line 881, in <module>
    loop.run_until_complete(start_main_server())
  File "/home/david/anaconda3/envs/chat/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/david/20240207/Langchain-Chatchat/startup.py", line 863, in start_main_server
    p.kill()
  File "/home/david/anaconda3/envs/chat/lib/python3.11/multiprocessing/process.py", line 140, in kill
    self._popen.kill()
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'kill'

**环境信息 / Environment Information**

操作系统：Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'model/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda

**Comment by zRzRzRzRzRzRzR** [comment]
配置不够导致的进程被杀了吧

**Comment by PedroNeal** [comment]
@zRzRzRzRzRzRzR 24G显卡应该不至于吧

**Comment by zRzRzRzRzRzRzR** [comment]
内存杀了

**Comment by PedroNeal** [comment]
谢谢，我再看看

**Comment by LuoShiJun1** [comment]
遇到了相同的问题，请问这个问题现在解决了吗？

**Comment by LuoShiJun1** [comment]
> 遇到了相同的问题，请问这个问题现在解决了吗？

找到原因了，我的环境是4090*4，如果配置文件中指定所有显卡可见，可用显卡为4，服务可以启动。但是指定可见显卡为0，可用显卡数为1，启动时会报上述错误。原因是配置文件失效，需要启动时指定可见显卡：CUDA_VISIBLE_DEVICES=0,1 python startup.py -a。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/105686701/f92fb395-feb4-4c85-ae68-45162f4e2195)
