### ISSUE TITLE
[BUG] 知识库问答问题 /  utils.py[line:40] - ERROR: APIError: Caught exception: An error occurred during streaming

### ISSUE THREAD

**Issue by ocpinfo** [chatchat-space/Langchain-Chatchat#2971]
**问题描述 / Problem Description**
知识库问答突然会出现这个问题，然后没有回答

**复现问题的步骤 / Steps to Reproduce**
任意知识库问答，问到较为复杂的问题会出现

**预期的结果 / Expected Result**
如果不会回答，会反馈没有合适的信息，而不是出错

**实际结果 / Actual Result**
 utils.py[line:40] - ERROR: APIError: Caught exception: An error occurred during streaming

**环境信息 / Environment Information**
- langchain-chatchat 0.0.354 fastchat版本0.2.34
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): qwen-max
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Windows10
- Python 版本 / Python version: 3.10.10
- 其他相关环境信息 / Other relevant environment information: Dell Laptop intel chip

**附加信息 / Additional Information**
2024-02-09 06:05:45 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21006/worker_generate_stream "HTTP/1.1 200 OK"
2024-02-09 06:05:46 | ERROR | model_worker | 请求千问 API 时发生错误：{'error_code': <HTTPStatus.INTERNAL_SERVER_ERROR: 500>, 'text': 'Input data may contain inappropriate content.', 'error': {'message': 'Input data may contain inappropriate content.', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-02-09 06:05:46,649 - utils.py[line:38] - ERROR: An error occurred during streaming
Traceback (most recent call last):
  File "D:\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\chat_models\openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\chat_models\openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_streaming.py", line 136, in __stream__
    raise APIError(
openai.APIError: An error occurred during streaming
2024-02-09 06:05:46,650 - utils.py[line:40] - ERROR: APIError: Caught exception: An error occurred during streaming

**Comment by zRzRzRzRzRzRzR** [comment]
回答超时吗，这时候大概输出了多少字

**Comment by ocpinfo** [comment]
这种情况就没有字出了，一个也没有

**Comment by ocpinfo** [comment]
降级到29、30版本都试过，没啥用

**Comment by weigong1983** [comment]
知识库问答及文件对话都遇到类似问题：
Traceback (most recent call last):
  File "/Users/weigong/Desktop/gpt/hkb/server/utils.py", line 22, in wrap_done
    await fn
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 136, in __stream__
    raise APIError(
openai.APIError: An error occurred during streaming
2024-03-19 19:09:15 | ERROR | root | APIError: Caught exception: An error occurred during streaming

**Comment by cackako** [comment]
> 知识库问答及文件对话都遇到类似问题： Traceback (most recent call last): File "/Users/weigong/Desktop/gpt/hkb/server/utils.py", line 22, in wrap_done await fn File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 381, in acall raise e File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 375, in acall await self._acall(inputs, run_manager=run_manager) File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall response = await self.agenerate([inputs], run_manager=run_manager) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate return await self.llm.agenerate_prompt( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt return await self.agenerate( ^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate raise exceptions[0] File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache return await self._agenerate( ^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate return await agenerate_from_stream(stream_iter) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream async for chunk in stream: File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream async for chunk in await acompletion_with_retry( File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 116, in **aiter** async for item in self._iterator: File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 136, in **stream** raise APIError( openai.APIError: An error occurred during streaming 2024-03-19 19:09:15 | ERROR | root | APIError: Caught exception: An error occurred during streaming

您好，请问解决了吗

**Comment by ocpinfo** [comment]
> > 知识库问答及文件对话都遇到类似问题： Traceback (most recent call last): File "/Users/weigong/Desktop/gpt/hkb/server/utils.py", line 22, in wrap_done await fn File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 381, in acall raise e File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 375, in acall await self._acall(inputs, run_manager=run_manager) File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall response = await self.agenerate([inputs], run_manager=run_manager) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate return await self.llm.agenerate_prompt( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt return await self.agenerate( ^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate raise exceptions[0] File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache return await self._agenerate( ^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate return await agenerate_from_stream(stream_iter) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream async for chunk in stream: File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream async for chunk in await acompletion_with_retry( File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 116, in **aiter** async for item in self._iterator: File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 136, in **stream** raise APIError( openai.APIError: An error occurred during streaming 2024-03-19 19:09:15 | ERROR | root | APIError: Caught exception: An error occurred during streaming
> 
> 您好，请问解决了吗

没有解决，没人理我，已经放弃使用langchain了，建议使用Fastgpt，很好用。

**Comment by cackako** [comment]
> > > 知识库问答及文件对话都遇到类似问题： Traceback (most recent call last): File "/Users/weigong/Desktop/gpt/hkb/server/utils.py", line 22, in wrap_done await fn File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 381, in acall raise e File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 375, in acall await self._acall(inputs, run_manager=run_manager) File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall response = await self.agenerate([inputs], run_manager=run_manager) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate return await self.llm.agenerate_prompt( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt return await self.agenerate( ^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate raise exceptions[0] File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache return await self._agenerate( ^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate return await agenerate_from_stream(stream_iter) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream async for chunk in stream: File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream async for chunk in await acompletion_with_retry( File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 116, in **aiter** async for item in self._iterator: File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 136, in **stream** raise APIError( openai.APIError: An error occurred during streaming 2024-03-19 19:09:15 | ERROR | root | APIError: Caught exception: An error occurred during streaming
> > 
> > 
> > 您好，请问解决了吗
> 
> 没有解决，没人理我，已经放弃使用langchain了，建议使用Fastgpt，很好用。
好的好的，谢谢
