### ISSUE TITLE
Mac上运行本地的chatglm3-6b模型对话报错

### ISSUE THREAD

**Issue by mobguang** [chatchat-space/Langchain-Chatchat#2974]
**问题描述 / Problem Description**
Mac上运行本地的chatglm3-6b模型对话报错。
配置信息：
Macmini，16GB，3.2 GHz 6-Core Intel Core i7，python3.11，Langchain-chatchat版本：0.2.10

**复现问题的步骤 / Steps to Reproduce**
1. 安装官方文档，clone代码和模型到本地，初始化后执行：python startup.py -a
2. 在WebUI上选择“对话”模式，Temperature选择0.7，历史对话轮数：3
3. 在右侧的输入框中输入“你是谁”，然后回车，页面上显示“思考中”，几分钟后报错，信息如下：

2024-02-12 17:29:16,038 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-02-12 17:29:16,262 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-02-12 17:29:16 | INFO | stdout | INFO:     127.0.0.1:54124 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-02-12 17:29:16,737 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-02-12 17:29:16 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-02-12 17:30:57 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-02-12 17:30:57 | ERROR | stderr | Traceback (most recent call last):
2024-02-12 17:30:57 | ERROR | stderr |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/responses.py", line 261, in __call__
2024-02-12 17:30:57 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-02-12 17:30:57 | ERROR | stderr |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/responses.py", line 257, in wrap
2024-02-12 17:30:57 | ERROR | stderr |     await func()
2024-02-12 17:30:57 | ERROR | stderr |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/responses.py", line 234, in listen_for_disconnect
2024-02-12 17:30:57 | ERROR | stderr |     message = await receive()
2024-02-12 17:30:57 | ERROR | stderr |               ^^^^^^^^^^^^^^^
2024-02-12 17:30:57 | ERROR | stderr |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 580, in receive
2024-02-12 17:30:57 | ERROR | stderr |     await self.message_event.wait()
2024-02-12 17:30:57 | ERROR | stderr |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/asyncio/locks.py", line 213, in wait
2024-02-12 17:30:57 | ERROR | stderr |     await fut
2024-02-12 17:30:57 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 120e7d590
2024-02-12 17:30:57 | ERROR | stderr | 
2024-02-12 17:30:57 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-02-12 17:30:57 | ERROR | stderr | 
2024-02-12 17:30:57 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2024-02-12 17:30:57 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-02-12 17:30:57 | ERROR | stderr |   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     raise exc
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-02-12 17:30:57 | ERROR | stderr |   |     raise exc
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-02-12 17:30:57 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
2024-02-12 17:30:57 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-02-12 17:30:57 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-02-12 17:30:57 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-02-12 17:30:57 | ERROR | stderr |   |     raise exc
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-02-12 17:30:57 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
2024-02-12 17:30:57 | ERROR | stderr |   |     await response(scope, receive, send)
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/responses.py", line 254, in __call__
2024-02-12 17:30:57 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-02-12 17:30:57 | ERROR | stderr |   |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
2024-02-12 17:30:57 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-02-12 17:30:57 | ERROR | stderr |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-02-12 17:30:57 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-02-12 17:30:57 | ERROR | stderr |     | Traceback (most recent call last):
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
2024-02-12 17:30:57 | ERROR | stderr |     |     yield cancel_scope
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 34, in read
2024-02-12 17:30:57 | ERROR | stderr |     |     return await self._stream.receive(max_bytes=max_bytes)
2024-02-12 17:30:57 | ERROR | stderr |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1123, in receive
2024-02-12 17:30:57 | ERROR | stderr |     |     await self._protocol.read_event.wait()
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/asyncio/locks.py", line 213, in wait
2024-02-12 17:30:57 | ERROR | stderr |     |     await fut
2024-02-12 17:30:57 | ERROR | stderr |     | asyncio.exceptions.CancelledError: Cancelled by cancel scope 12056f5d0
2024-02-12 17:30:57 | ERROR | stderr |     |
2024-02-12 17:30:57 | ERROR | stderr |     | During handling of the above exception, another exception occurred:
2024-02-12 17:30:57 | ERROR | stderr |     |
2024-02-12 17:30:57 | ERROR | stderr |     | Traceback (most recent call last):
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
2024-02-12 17:30:57 | ERROR | stderr |     |     yield
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 32, in read
2024-02-12 17:30:57 | ERROR | stderr |     |     with anyio.fail_after(timeout):
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/contextlib.py", line 158, in __exit__
2024-02-12 17:30:57 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
2024-02-12 17:30:57 | ERROR | stderr |     |     raise TimeoutError
2024-02-12 17:30:57 | ERROR | stderr |     | TimeoutError
2024-02-12 17:30:57 | ERROR | stderr |     |
2024-02-12 17:30:57 | ERROR | stderr |     | The above exception was the direct cause of the following exception:
2024-02-12 17:30:57 | ERROR | stderr |     |
2024-02-12 17:30:57 | ERROR | stderr |     | Traceback (most recent call last):
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
2024-02-12 17:30:57 | ERROR | stderr |     |     yield
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 252, in __aiter__
2024-02-12 17:30:57 | ERROR | stderr |     |     async for part in self._httpcore_stream:
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
2024-02-12 17:30:57 | ERROR | stderr |     |     async for part in self._stream:
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
2024-02-12 17:30:57 | ERROR | stderr |     |     raise exc
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
2024-02-12 17:30:57 | ERROR | stderr |     |     async for chunk in self._connection._receive_response_body(**kwargs):
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
2024-02-12 17:30:57 | ERROR | stderr |     |     event = await self._receive_event(timeout=timeout)
2024-02-12 17:30:57 | ERROR | stderr |     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
2024-02-12 17:30:57 | ERROR | stderr |     |     data = await self._network_stream.read(
2024-02-12 17:30:57 | ERROR | stderr |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 31, in read
2024-02-12 17:30:57 | ERROR | stderr |     |     with map_exceptions(exc_map):
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/contextlib.py", line 158, in __exit__
2024-02-12 17:30:57 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-02-12 17:30:57 | ERROR | stderr |     |     raise to_exc(exc) from exc
2024-02-12 17:30:57 | ERROR | stderr |     | httpcore.ReadTimeout
2024-02-12 17:30:57 | ERROR | stderr |     |
2024-02-12 17:30:57 | ERROR | stderr |     | The above exception was the direct cause of the following exception:
2024-02-12 17:30:57 | ERROR | stderr |     |
2024-02-12 17:30:57 | ERROR | stderr |     | Traceback (most recent call last):
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/responses.py", line 257, in wrap
2024-02-12 17:30:57 | ERROR | stderr |     |     await func()
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/starlette/responses.py", line 246, in stream_response
2024-02-12 17:30:57 | ERROR | stderr |     |     async for chunk in self.body_iterator:
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/fastchat/serve/openai_api_server.py", line 473, in chat_completion_stream_generator
2024-02-12 17:30:57 | ERROR | stderr |     |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/fastchat/serve/openai_api_server.py", line 658, in generate_completion_stream
2024-02-12 17:30:57 | ERROR | stderr |     |     async for raw_chunk in response.aiter_raw():
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_models.py", line 991, in aiter_raw
2024-02-12 17:30:57 | ERROR | stderr |     |     async for raw_stream_bytes in self.stream:
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_client.py", line 147, in __aiter__
2024-02-12 17:30:57 | ERROR | stderr |     |     async for chunk in self._stream:
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 251, in __aiter__
2024-02-12 17:30:57 | ERROR | stderr |     |     with map_httpcore_exceptions():
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/contextlib.py", line 158, in __exit__
2024-02-12 17:30:57 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-02-12 17:30:57 | ERROR | stderr |     |   File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
2024-02-12 17:30:57 | ERROR | stderr |     |     raise mapped_exc(message) from exc
2024-02-12 17:30:57 | ERROR | stderr |     | httpx.ReadTimeout
2024-02-12 17:30:57 | ERROR | stderr |     +------------------------------------
2024-02-12 17:30:57,735 - utils.py[line:38] - ERROR: peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/h11/_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 252, in __aiter__
    async for part in self._httpcore_stream:
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
    async for part in self._stream:
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
    raise exc
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Volumes/M2SSD/Space/Workspace/llm/langchain_chatchat/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/openai/_streaming.py", line 129, in __stream__
    async for sse in iterator:
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/openai/_streaming.py", line 120, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/openai/_streaming.py", line 231, in aiter
    async for line in iterator:
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_models.py", line 967, in aiter_lines
    async for text in self.aiter_text():
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_models.py", line 954, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_models.py", line 933, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_models.py", line 991, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_client.py", line 147, in __aiter__
    async for chunk in self._stream:
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 251, in __aiter__
    with map_httpcore_exceptions():
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/workspace/anaconda3/envs/lcchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-02-12 17:30:57,914 - utils.py[line:40] - ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)

请问要如何处理，谢谢。

**Comment by mobguang** [comment]
> _🤖_
> 
> Based on the error messages you provided, it seems like the application is unable to complete its task within the expected time, hence the `TimeoutError`. This could be due to several reasons, including insufficient system resources, incorrect configuration, or issues with the model files.
> 
> Here are some steps you can take to troubleshoot and potentially resolve the issue:
> 
> 1. **Check System Resources**: The chatglm3-6b model is quite large and requires significant computational resources. Ensure that your Macmini has enough CPU, GPU, and RAM to load and run the model. If resources are insufficient, consider upgrading your hardware or using a more powerful machine.
> 2. **Verify Configuration**: Review the `model_config.py.example` file and ensure that all configurations are set correctly. Specifically, ensure that "chatglm3-6b" is included in the `LLM_MODELS` list and `LLM_DEVICE` is set to a device that your Macmini supports. You can find the configuration file [here](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example).
> 3. **Check Model Files**: Ensure that the model files for chatglm3-6b are correctly downloaded and placed in the correct directory as specified by `MODEL_ROOT_PATH`. If the model files are not found, download them from the Hugging Face model repository and place them in the correct directory.
> 
> In addition, I found two similar issues in the Langchain-Chatchat repository that might be helpful:
> 
> 1. [执行python startup.py -a 报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2937): This issue was resolved by ensuring that the model files were complete and that `streamlit` was installed and added to the system path.
> 2. [【bug】选择用chatglm3-6b 加载模型时报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/1409): This issue was closed without any comments or solution, but it might be worth checking out.
> 
> If the above suggestions do not resolve your issue, please provide more details about the error messages you're seeing. This will help me provide a more precise solution.
> 
> ## Sources
> * [执行python startup.py -a 报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2937)
> * [【bug】选择用chatglm-api 加载模型时报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/1409)
> * [configs/model_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example)
> * [startup.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/startup.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

是不是因为机器内存只有16G导致的，内存不足会引起这个问题吗。

**Comment by zRzRzRzRzRzRzR** [comment]
16G的跑不动GLM3-6B，换个小点的吧

**Comment by mobguang** [comment]
> 16G的跑不动GLM3-6B，换个小点的吧

谢谢回复。
请问有哪些可以替代的。

**Comment by zRzRzRzRzRzRzR** [comment]
Qwen 系列4B 0.5B 1.8B

**Comment by cuntoushifu** [comment]
我是三峡大学的硕士刘战

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ZhichaoOuyang** [comment]
> 16G的跑不动GLM3-6B，换个小点的吧

我是mac m2 pro 32g 换了 Qwen 0.5B 还是报楼主这个错，请问该怎么解决
