### ISSUE TITLE
[BUG] chatgpt和zhipu的api都接不进去

### ISSUE THREAD

**Issue by nanfengyishang** [chatchat-space/Langchain-Chatchat#2978]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 将model_config.py中的
LLM_MODELS

修改为["zhipu-api"]
并将zhipu的key写上

或

修改为["openai-api"]
并将openai-api的key写上

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

1.可以在页面正常切换对应的llm api选项后，成功问答。

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

1. 配置为["zhipu-api"]报错
rt ChatOpenAI`.
  warn_deprecated(
2024-02-14 20:47:17 | INFO | stdout | INFO:     127.0.0.1:52702 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-02-14 20:47:17,488 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-02-14 20:47:17 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21001/worker_generate_stream "HTTP/1.1 200 OK"
2024-02-14 20:47:17,752 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "D:\code\Langchain-Chatchat-master\server\utils.py", line 36, in wrap_done
    await fn
  File "C:\Users\97161\.conda\envs\wangru\Lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "C:\Users\97161\.conda\envs\wangru\Lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "C:\Users\97161\.conda\envs\wangru\Lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97161\.conda\envs\wangru\Lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97161\AppData\Roaming\Python\Python311\site-packages\langchain_core\language_models\chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97161\AppData\Roaming\Python\Python311\site-packages\langchain_core\language_models\chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "C:\Users\97161\AppData\Roaming\Python\Python311\site-packages\langchain_core\language_models\chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97161\AppData\Roaming\Python\Python311\site-packages\langchain_community\chat_models\openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97161\AppData\Roaming\Python\Python311\site-packages\langchain_core\language_models\chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "C:\Users\97161\AppData\Roaming\Python\Python311\site-packages\langchain_community\chat_models\openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

2.配置为["openai-api"]报错

rt ChatOpenAI`.
  warn_deprecated(
2024-02-14 21:05:59,275 - _base_client.py[line:1524] - INFO: Retrying request to /chat/completions in 0.931504 seconds
2024-02-14 21:06:21,274 - _base_client.py[line:1524] - INFO: Retrying request to /chat/completions in 1.613604 seconds
2024-02-14 21:06:43,940 - utils.py[line:38] - ERROR: Connection error.

**单独使用LLMChain（）链调用chatgpt的api可以通，相同的代码，改到项目里，就是超时，什么鬼，原地爆炸。**

**环境信息 / Environment Information**
windows和linux环境下 Langchain-Chatchat-0.2.10版本

- 是否使用 Docker 部署（是/否）：否 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatgpt和zhipu
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：默认
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：默认
- 操作系统及版本： windows和linux
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

使用模型没问题，api调用都不成功

**Comment by zRzRzRzRzRzRzR** [comment]
不是这么改的。。建议看wiki
