### ISSUE TITLE
前一天晚上配置好能跑之后，第二天重新启动就报错了，，，

### ISSUE THREAD

**Issue by Nikolahuang** [chatchat-space/Langchain-Chatchat#2985]
这是啥问题啊，拒绝访问了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/72554297/c3031a84-8439-44e5-88d3-3b5c05937923)

**Comment by AndersonHuangEDU** [comment]
2024-02-17 10:18:41,010 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-17 10:18:43,028 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-17 10:18:45,041 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-17 10:18:47,155 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-17 10:18:49,173 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-17 10:18:51,190 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-17 10:18:51.190 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\17769\.conda\envs\env\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\BaiduNetdiskDownload\langchain_chatchatv2_anderson\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\BaiduNetdiskDownload\langchain_chatchatv2_anderson\webui_pages\dialogue\dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by zRzRzRzRzRzRzR** [comment]
重启程序

**Comment by zmwstu** [comment]
> 重启程序

不行，重启也是一样，重新拉代码跑还会报错，这是什么原因，怎么解决？

**Comment by sh66666** [comment]
兄弟，解决了么，求助

**Comment by zRzRzRzRzRzRzR** [comment]
尝试选择一个本地模型进行启动

**Comment by Micla-SHL** [comment]
> 估计是全部用了API的问题，一般不会出现。尝试选择一个本地模型进行启动

我按着readme来也是出现了这错误，我还没有配置智谱API和OpenAI API 。我是直接指定了GLM3的绝对地址跟向量模型的地址，发现了这问题。看着好多人都是这问题，这会是什么原因呢？

**Comment by Micla-SHL** [comment]
> > 估计是全部用了API的问题，一般不会出现。尝试选择一个本地模型进行启动
> 
> 我按着readme来也是出现了这错误，我还没有配置智谱API和OpenAI API 。我是直接指定了GLM3的绝对地址跟向量模型的地址，发现了这问题。看着好多人都是这问题，这会是什么原因呢？

我今天在另外一台配置，操作一样，是不会出现这问题的。下面我说一下配置上的两台PC的区别，昨天失败的那台配置了梯子，采取wifi上网没有接网线，其余操作跟今天操作成功的电脑一致，希望对他人有启发。另外希望新版本不会有这问题
