### ISSUE TITLE
使用lora和glm2微调合并后，报错。

### ISSUE THREAD

**Issue by hOVOzw** [chatchat-space/Langchain-Chatchat#2988]
使用lora和glm2微调合并后，报错。
使用llama factory对模型微调后导出模型，已经在model_config.py修改了配置。

**预期的结果 /正常打开webui

**实际结果 / 
2024-02-18 01:39:12 | ERROR | stderr | Traceback (most recent call last):
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\multiprocessing\process.py", line 315, in _bootstrap
2024-02-18 01:39:12 | ERROR | stderr |     self.run()
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\multiprocessing\process.py", line 108, in run
2024-02-18 01:39:12 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\langchain_Chatchat\startup.py", line 389, in run_model_worker
2024-02-18 01:39:12 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\langchain_Chatchat\startup.py", line 217, in create_model_worker_app
2024-02-18 01:39:12 | ERROR | stderr |     worker = ModelWorker(
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-02-18 01:39:12 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\fastchat\model\model_adapter.py", line 348, in load_model
2024-02-18 01:39:12 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\fastchat\model\model_adapter.py", line 823, in load_model
2024-02-18 01:39:12 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 801, in from_pretrained
2024-02-18 01:39:12 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\transformers\tokenization_utils_base.py", line 2029, in from_pretrained
2024-02-18 01:39:12 | ERROR | stderr |     return cls._from_pretrained(
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\transformers\tokenization_utils_base.py", line 2261, in _from_pretrained
2024-02-18 01:39:12 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-02-18 01:39:12 | ERROR | stderr |   File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\chatglm2-lora\tokenization_chatglm.py", line 78, in __init__
2024-02-18 01:39:12 | ERROR | stderr |     super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces, **kwargs)
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\transformers\tokenization_utils.py", line 363, in __init__
2024-02-18 01:39:12 | ERROR | stderr |     super().__init__(**kwargs)
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\transformers\tokenization_utils_base.py", line 1603, in __init__
2024-02-18 01:39:12 | ERROR | stderr |     super().__init__(**kwargs)
2024-02-18 01:39:12 | ERROR | stderr |   File "D:\ANACONDA\envs\chatchat\lib\site-packages\transformers\tokenization_utils_base.py", line 861, in __init__
2024-02-18 01:39:12 | ERROR | stderr |     setattr(self, key, value)
2024-02-18 01:39:12 | ERROR | stderr | AttributeError: can't set attribute
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:00<00:05,  1.00it/s]
Loading checkpoint shards:  29%|████████████████▎                                        | 2/7 [00:01<00:04,  1.12it/s]
Loading checkpoint shards:  43%|████████████████████████▍                                | 3/7 [00:02<00:03,  1.30it/s]
Loading checkpoint shards:  57%|████████████████████████████████▌                        | 4/7 [00:03<00:02,  1.45it/s]
Loading checkpoint shards:  71%|████████████████████████████████████████▋                | 5/7 [00:03<00:01,  1.38it/s]
Loading checkpoint shards:  86%|████████████████████████████████████████████████▊        | 6/7 [00:04<00:00,  1.28it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.43it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.34it/s]
2024-02-18 01:39:17 | ERROR | stderr |
2024-02-18 01:39:20 | INFO | model_worker | Register to controller

**Comment by zRzRzRzRzRzRzR** [comment]
建议使用peft加载，分别挂载微调和原始的模型，wiki中有相关内容
