### ISSUE TITLE
千问14b-int4模型加载失败

### ISSUE THREAD

**Issue by leizhu1989** [chatchat-space/Langchain-Chatchat#2993]
**问题描述 / Problem Description**
CUDA_VISIBLE_DEVICES=2,3 python startup.py -a --model-name Qwen-14B-Chat-Int4   运行startup.py 报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：master分支
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): Qwen-14B-Chat-Int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:  ubuntu18.04
- Python 版本 / Python version:  3.11
- 显卡：tesla v100
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

错误信息：
2024-02-18 17:21:16 | ERROR | stderr | Process model_worker - Qwen-14B-Chat-Int4:
2024-02-18 17:21:16 | ERROR | stderr | Traceback (most recent call last):
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
2024-02-18 17:21:16 | ERROR | stderr |     return next(cls.discover(name=name))
2024-02-18 17:21:16 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr | StopIteration
2024-02-18 17:21:16 | ERROR | stderr | 
2024-02-18 17:21:16 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-02-18 17:21:16 | ERROR | stderr | 
2024-02-18 17:21:16 | ERROR | stderr | Traceback (most recent call last):
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-18 17:21:16 | ERROR | stderr |     self.run()
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-18 17:21:16 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/lei/NLP/Langchain-Chatchat-master/startup.py", line 387, in run_model_worker
2024-02-18 17:21:16 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-18 17:21:16 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/lei/NLP/Langchain-Chatchat-master/startup.py", line 215, in create_model_worker_app
2024-02-18 17:21:16 | ERROR | stderr |     worker = ModelWorker(
2024-02-18 17:21:16 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-18 17:21:16 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-18 17:21:16 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 323, in load_model
2024-02-18 17:21:16 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-02-18 17:21:16 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 1583, in load_model
2024-02-18 17:21:16 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2024-02-18 17:21:16 | ERROR | stderr |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
2024-02-18 17:21:16 | ERROR | stderr |     return model_class.from_pretrained(
2024-02-18 17:21:16 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3013, in from_pretrained
2024-02-18 17:21:16 | ERROR | stderr |     gptq_supports_cpu = version.parse(importlib.metadata.version("auto-gptq")) > version.parse("0.4.2")
2024-02-18 17:21:16 | ERROR | stderr |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
2024-02-18 17:21:16 | ERROR | stderr |     return distribution(distribution_name).version
2024-02-18 17:21:16 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
2024-02-18 17:21:16 | ERROR | stderr |     return Distribution.from_name(distribution_name)
2024-02-18 17:21:16 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18 17:21:16 | ERROR | stderr |   File "/home/anaconda3/envs/Langchain_chat/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
2024-02-18 17:21:16 | ERROR | stderr |     raise PackageNotFoundError(name)
2024-02-18 17:21:16 | ERROR | stderr | importlib.metadata.PackageNotFoundError: No package metadata was found for auto-gptq

请问大佬这是什么原因

**Comment by zRzRzRzRzRzRzR** [comment]
装对应依赖就行了

**Comment by ponponon** [comment]
> 装对应依赖就行了

是什么依赖？可以告知对应的名称吗？
