### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.bridge'

### ISSUE THREAD

**Issue by forgotriver** [chatchat-space/Langchain-Chatchat#3000]
** Problem Description**
ModuleNotFoundError: No module named 'llama_index.bridge'

**Steps to Reproduce**
python startup.py -a

**Actual Result**

2024-02-19 00:21:13 | ERROR | stderr |
2024-02-19 00:21:16 | INFO | model_worker | Register to controller
Process API Server:
Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "E:\ProgramData\anaconda3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Download\Langchain-Chatchat\startup.py", line 436, in run_api_server
    app = create_app(run_mode=run_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Download\Langchain-Chatchat\server\api.py", line 51, in create_app
    mount_app_routes(app, run_mode=run_mode)
  File "G:\Download\Langchain-Chatchat\server\api.py", line 77, in mount_app_routes
    mount_knowledge_routes(app)
  File "G:\Download\Langchain-Chatchat\server\api.py", line 140, in mount_knowledge_routes
    from server.chat.knowledge_base_chat import knowledge_base_chat
  File "G:\Download\Langchain-Chatchat\server\chat\knowledge_base_chat.py", line 24, in <module>
    from server.reranker.reranker import LangchainReranker
  File "G:\Download\Langchain-Chatchat\server\reranker\reranker.py", line 11, in <module>
    from llama_index.bridge.pydantic import Field, PrivateAttr
ModuleNotFoundError: No module named 'llama_index.bridge'

**环境信息 / Environment Information**
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base

- 操作系统及版本 / Operating system and version: Win10
- Python 版本 / Python version: 3.11

**Comment by forgotriver** [comment]
**版本问题**
导入库的时候将
from llama_index.bridge.pydantic import Field, PrivateAttr
改为
from llama_index.legacy.bridge.pydantic import Field, PrivateAttr
