### ISSUE TITLE
[BUG] 2.10 不能运行 baichuan2-13b-chat-4bits

### ISSUE THREAD

**Issue by daim6n** [chatchat-space/Langchain-Chatchat#3005]
**问题描述 / Problem Description**
我知道baichuan2-13b-chat-4bits不在支持列表中，而且也不确定这是不是bug，如果给您困扰，非常抱歉。
我使用0.2.7加载baichuan2-13b-chat-4bits很好，因为这个模型对我来说性价比是最高的。
因为要使用rerank的能力，我升级到0.2.10，发现模型能正常加载，但聊天就直接出错：

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/responses.py", line 254, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/responses.py", line 257, in wrap
    await func()
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/responses.py", line 246, in stream_response
    async for chunk in self.body_iterator:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, as_iterator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/concurrency.py", line 52, in _next
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 114, in generate_stream_gate
    for output in self.generate_stream_func(
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/fastchat/serve/inference.py", line 132, in generate_stream
    out = model(input_ids=start_ids, use_cache=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat-4bits/modeling_baichuan.py", line 688, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat-4bits/modeling_baichuan.py", line 464, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat-4bits/modeling_baichuan.py", line 241, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat-4bits/modeling_baichuan.py", line 147, in forward
    proj = self.W_pack(hidden_states)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 256, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/bitsandbytes/autograd/_functions.py", line 577, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/bitsandbytes/autograd/_functions.py", line 516, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 1017, in dequantize_4bit
    absmax = quant_state.absmax
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'absmax'
2024-02-19 17:01:38 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-02-19 17:01:38 | ERROR | stderr | Traceback (most recent call last):
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
2024-02-19 17:01:38 | ERROR | stderr |     yield
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_transports/default.py", line 252, in __aiter__
2024-02-19 17:01:38 | ERROR | stderr |     async for part in self._httpcore_stream:
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
2024-02-19 17:01:38 | ERROR | stderr |     raise exc from None
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
2024-02-19 17:01:38 | ERROR | stderr |     async for part in self._stream:
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/http11.py", line 336, in __aiter__
2024-02-19 17:01:38 | ERROR | stderr |     raise exc
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/http11.py", line 328, in __aiter__
2024-02-19 17:01:38 | ERROR | stderr |     async for chunk in self._connection._receive_response_body(**kwargs):
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/http11.py", line 197, in _receive_response_body
2024-02-19 17:01:38 | ERROR | stderr |     event = await self._receive_event(timeout=timeout)
2024-02-19 17:01:38 | ERROR | stderr |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/http11.py", line 207, in _receive_event
2024-02-19 17:01:38 | ERROR | stderr |     with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/contextlib.py", line 158, in __exit__
2024-02-19 17:01:38 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-02-19 17:01:38 | ERROR | stderr |     raise to_exc(exc) from exc
2024-02-19 17:01:38 | ERROR | stderr | httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-02-19 17:01:38 | ERROR | stderr |
2024-02-19 17:01:38 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-02-19 17:01:38 | ERROR | stderr |
2024-02-19 17:01:38 | ERROR | stderr | Traceback (most recent call last):
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-02-19 17:01:38 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-02-19 17:01:38 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     raise exc
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     await self.app(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-02-19 17:01:38 | ERROR | stderr |     raise exc
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-02-19 17:01:38 | ERROR | stderr |     await app(scope, receive, sender)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
2024-02-19 17:01:38 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-02-19 17:01:38 | ERROR | stderr |     await self.app(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-02-19 17:01:38 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-02-19 17:01:38 | ERROR | stderr |     raise exc
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-02-19 17:01:38 | ERROR | stderr |     await app(scope, receive, sender)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
2024-02-19 17:01:38 | ERROR | stderr |     await response(scope, receive, send)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/responses.py", line 254, in __call__
2024-02-19 17:01:38 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2024-02-19 17:01:38 | ERROR | stderr |     raise exceptions[0]
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/responses.py", line 257, in wrap
2024-02-19 17:01:38 | ERROR | stderr |     await func()
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/starlette/responses.py", line 246, in stream_response
2024-02-19 17:01:38 | ERROR | stderr |     async for chunk in self.body_iterator:
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/fastchat/serve/openai_api_server.py", line 473, in chat_completion_stream_generator
2024-02-19 17:01:38 | ERROR | stderr |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/fastchat/serve/openai_api_server.py", line 658, in generate_completion_stream
2024-02-19 17:01:38 | ERROR | stderr |     async for raw_chunk in response.aiter_raw():
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_models.py", line 991, in aiter_raw
2024-02-19 17:01:38 | ERROR | stderr |     async for raw_stream_bytes in self.stream:
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_client.py", line 147, in __aiter__
2024-02-19 17:01:38 | ERROR | stderr |     async for chunk in self._stream:
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_transports/default.py", line 251, in __aiter__
2024-02-19 17:01:38 | ERROR | stderr |     with map_httpcore_exceptions():
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/contextlib.py", line 158, in __exit__
2024-02-19 17:01:38 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2024-02-19 17:01:38 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
2024-02-19 17:01:38 | ERROR | stderr |     raise mapped_exc(message) from exc
2024-02-19 17:01:38 | ERROR | stderr | httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-02-19 17:01:38,270 - utils.py[line:38] - ERROR: peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_transports/default.py", line 252, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
    raise exc from None
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
    async for part in self._stream:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/http11.py", line 336, in __aiter__
    raise exc
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/http11.py", line 328, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/http11.py", line 197, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_async/http11.py", line 207, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/service/langchain/0.2.10_/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/openai/_streaming.py", line 129, in __stream__
    async for sse in iterator:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/openai/_streaming.py", line 120, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/openai/_streaming.py", line 231, in aiter
    async for line in iterator:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_models.py", line 967, in aiter_lines
    async for text in self.aiter_text():
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_models.py", line 954, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_models.py", line 933, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_models.py", line 991, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_client.py", line 147, in __aiter__
    async for chunk in self._stream:
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_transports/default.py", line 251, in __aiter__
    with map_httpcore_exceptions():
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/anaconda3/envs/lc10_311/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
```

**环境信息 / Environment Information**
- master 最新代码
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：baichuan2-13b-chat-4bits
- 操作系统及版本 / Operating system and version: ubuntu 20.0.4
- Python 版本 / Python version:
- 2.11.7

**附加信息 / Additional Information**
baichuan2-13b-chat 开启8bit量化，是正常使用的，但它消耗太多内存了。

期待您的帮助

**Comment by daim6n** [comment]
bitsandbytes==0.42.0

**Comment by zRzRzRzRzRzRzR** [comment]
4bit没有适配，你可能要去对应的模型寻找在正常huggingface中怎么接入4bit模型的
