### ISSUE TITLE
运行出错，显示CUDA内存不足，同时还有别的问题，不值得怎么解决

### ISSUE THREAD

**Issue by zh-chuan** [chatchat-space/Langchain-Chatchat#3017]
2024-02-21 10:38:46 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-02-21 10:38:46 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker d93ff0f0 ...
Loading checkpoint shards:   0%|                                                                          | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|█████████▍                                                        | 1/7 [00:00<00:05,  1.17it/s]
Loading checkpoint shards:  29%|██████████████████▊                                               | 2/7 [00:01<00:04,  1.14it/s]
Loading checkpoint shards:  43%|████████████████████████████▎                                     | 3/7 [00:02<00:03,  1.14it/s]
Loading checkpoint shards:  57%|█████████████████████████████████████▋                            | 4/7 [00:03<00:02,  1.16it/s]
Loading checkpoint shards:  71%|███████████████████████████████████████████████▏                  | 5/7 [00:04<00:01,  1.13it/s]
Loading checkpoint shards:  86%|████████████████████████████████████████████████████████▌         | 6/7 [00:05<00:00,  1.07it/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████| 7/7 [00:06<00:00,  1.07s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████| 7/7 [00:06<00:00,  1.03it/s]
2024-02-21 10:38:53 | ERROR | stderr | 
2024-02-21 10:38:54 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-21 10:38:54 | ERROR | stderr | Traceback (most recent call last):
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-21 10:38:54 | ERROR | stderr |     self.run()
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-21 10:38:54 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/Downloads/LLMA_project/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-02-21 10:38:54 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-21 10:38:54 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/Downloads/LLMA_project/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-02-21 10:38:54 | ERROR | stderr |     worker = ModelWorker(
2024-02-21 10:38:54 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-21 10:38:54 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-21 10:38:54 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 362, in load_model
2024-02-21 10:38:54 | ERROR | stderr |     model.to(device)
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2595, in to
2024-02-21 10:38:54 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-02-21 10:38:54 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
2024-02-21 10:38:54 | ERROR | stderr |     return self._apply(convert)
2024-02-21 10:38:54 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-21 10:38:54 | ERROR | stderr |     module._apply(fn)
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-21 10:38:54 | ERROR | stderr |     module._apply(fn)
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-02-21 10:38:54 | ERROR | stderr |     module._apply(fn)
2024-02-21 10:38:54 | ERROR | stderr |   [Previous line repeated 3 more times]
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
2024-02-21 10:38:54 | ERROR | stderr |     param_applied = fn(param)
2024-02-21 10:38:54 | ERROR | stderr |                     ^^^^^^^^^
2024-02-21 10:38:54 | ERROR | stderr |   File "/home/csoft/anaconda3/envs/LLMchat00/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
2024-02-21 10:38:54 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-02-21 10:38:54 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-21 10:38:54 | ERROR | stderr | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB. GPU 0 has a total capacty of 3.81 GiB of which 145.88 MiB is free. Including non-PyTorch memory, this process has 3.66 GiB memory in use. Of the allocated memory 3.61 GiB is allocated by PyTorch, and 1.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by lastrei** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB. GPU 0 has a total capacty of 3.81 GiB of which 145.88 MiB is free. Including non-PyTorch memory, this process has 3.66 GiB memory in use. 

torch设置set_max_workspace_size参数和set_per_process_memory_fraction可以试试，但你这个明显显存不足。
