### ISSUE TITLE
langchain-chatchatv0.2.9部署好之后偶尔出现异步问题

### ISSUE THREAD

**Issue by maxusheng123** [chatchat-space/Langchain-Chatchat#3022]
2024-02-21 06:34:42,733 - runners.py[line:44] - ERROR: Task exception was never retrieved
future: <Task finished name='Task-13266' coro=<AsyncClient.aclose() done, defined at /root/miniconda3/envs/xiaokaguiji/lib/python3.10/site-packages/httpx/_client.py:1967> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x7fd7c0730a30>; the handler is closed')>
Traceback (most recent call last):
  File "/root/miniconda3/envs/xiaokaguiji/lib/python3.10/site-packages/httpx/_client.py", line 1974, in aclose
    await self._transport.aclose()
  File "/root/miniconda3/envs/xiaokaguiji/lib/python3.10/site-packages/httpx/_transports/default.py", line 378, in aclose
    await self._pool.aclose()
  File "/root/miniconda3/envs/xiaokaguiji/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 324, in aclose
    await connection.aclose()
  File "/root/miniconda3/envs/xiaokaguiji/lib/python3.10/site-packages/httpcore/_async/connection.py", line 173, in aclose
    await self._connection.aclose()
  File "/root/miniconda3/envs/xiaokaguiji/lib/python3.10/site-packages/httpcore/_async/http11.py", line 253, in aclose
    await self._network_stream.aclose()
  File "/root/miniconda3/envs/xiaokaguiji/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 54, in aclose
    await self._stream.aclose()
  File "/root/miniconda3/envs/xiaokaguiji/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1257, in aclose
    self._transport.write_eof()
  File "uvloop/handles/stream.pyx", line 699, in uvloop.loop.UVStream.write_eof
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x7fd7c0730a30>; the handler is closed
在进行agent对话时偶尔会出现上面这个错，请教一下是啥原因。

**Comment by zRzRzRzRzRzRzR** [comment]
1. agent是顺发的，如果你高并发可能会冲突出现问题
2. agent中间执行失败是很正常的，这样就会无法请求

**Comment by Nancy7zt** [comment]
有人知道这个解决办法吗
