### ISSUE TITLE
[BUG] 版本0.2.10 Embedding模型使用bge-large-zh-v1.5报错

### ISSUE THREAD

**Issue by WangXusheng1225** [chatchat-space/Langchain-Chatchat#3033]
模型已完整从HF下载
执行python init_database.py --recreate-vs报错如下：

recreating all vector stores
2024-02-22 09:45:07,946 - faiss_cache.py[line:92] - INFO: loading vector store in 'fangyi/vector_store/bge-large-zh-v1.5'
from disk.
2024-02-22 09:45:08,900 - SentenceTransformer.py[line:110] - INFO: Load pretrained SentenceTransformer: D:\LLMs\bge-large-
zh-v1.5
2024-02-22 09:45:11,323 - embeddings_api.py[line:39] - ****ERROR: Repo id must use alphanumeric chars or '-', '_', '.', '--' a
nd '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\LLMs\bge-large-zh-v1.5'.
AttributeError: 'NoneType' object has no attribute 'conjugate**'**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\server\knowledge_base\migrate.py", line 121, in folder2db
    kb.create_kb()
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\server\knowledge_base\kb_service\base.py", line 80, in create_kb
    self.do_create_kb()
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\server\knowledge_base\kb_service\faiss_kb_service.py", line 51, in
do_create_kb
    self.load_vector_store()
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\server\knowledge_base\kb_service\faiss_kb_service.py", line 28, in
load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\server\knowledge_base\kb_cache\faiss_cache.py", line 102, in load_v
ector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\server\knowledge_base\kb_cache\faiss_cache.py", line 60, in new_vec
tor_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
  File "C:\soft_install\Anaconda3\envs\airllm\lib\site-packages\langchain_core\vectorstores.py", line 508, in from_documen
ts
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "C:\soft_install\Anaconda3\envs\airllm\lib\site-packages\langchain_community\vectorstores\faiss.py", line 913, in f
rom_texts
    embeddings = embedding.embed_documents(texts)
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\server\knowledge_base\kb_service\base.py", line 420, in embed_docum
ents
    return normalize(embeddings).tolist()
  File "E:\DeskTop\pythonProject\Langchain-Chatchat-v2\server\knowledge_base\kb_service\base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "C:\soft_install\Anaconda3\envs\airllm\lib\site-packages\numpy\linalg\linalg.py", line 2582, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by Hiroshi230** [comment]
解决了吗兄弟，我也是这样，重新往知识库加了文件，然后重置后报错了

**Comment by WangXusheng1225** [comment]
> 解决了吗兄弟，我也是这样，重新往知识库加了文件，然后重置后报错了

"embed_model": {
        "bge-large-zh-v1.5": "BAAI/bge-large-zh-v1.5",
    },
    用项目代码去下载就可以，用本地的模型就不行。

**Comment by WangXusheng1225** [comment]
想问怎么加载本地的bge-large-zh-v1.5，一加载本地的bge-large-zh-v1.5就报上面的错误

**Comment by zRzRzRzRzRzRzR** [comment]
这个真的不是你的配置环境的问题吗，你是cpu还是gpu，这个文件多么是文件没全，建议git下载模型

**Comment by WangXusheng1225** [comment]
> 这个真的不是你的配置环境的问题吗，你是cpu还是gpu，这个文件多么是文件没全，建议git下载模型

模型是从HF Gitclone的，是GPU，模型下载后用transformers在本地加载是可以正确加载的，r如下图
![2cd512abe0ff714b4eb9642c85b6dd9](https://github.com/chatchat-space/Langchain-Chatchat/assets/61652556/1634363d-5f1d-42e5-8438-75a81b7a2110)
而使用langchain加载就报错，如下图
![28505546ac2744c10aa21e428c86b7a](https://github.com/chatchat-space/Langchain-Chatchat/assets/61652556/b70b0e12-39b6-4124-b7aa-755ba4751f29)

**Comment by Leng-bingo** [comment]
打开翻墙VPN即可解决，亲测问题
