### ISSUE TITLE
[BUG] 简洁阐述问题 / python init_database.py --recreate-vs

### ISSUE THREAD

**Issue by cq134cq** [chatchat-space/Langchain-Chatchat#3040]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh

- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:win11
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / >python init_database.py --recreate-vs
Traceback (most recent call last):
  File "C:\soft\lc\init_database.py", line 3, in <module>
    from server.knowledge_base.migrate import (create_tables, reset_tables, import_from_db,
  File "C:\soft\lc\server\knowledge_base\migrate.py", line 6, in <module>
    from server.knowledge_base.utils import (
  File "C:\soft\lc\server\knowledge_base\utils.py", line 15, in <module>
    import langchain.document_loaders
  File "C:\soft\lc\lib\site-packages\langchain\document_loaders\__init__.py", line 18, in <module>
    from langchain_community.document_loaders.acreom import AcreomLoader
  File "C:\soft\lc\lib\site-packages\langchain_community\document_loaders\__init__.py", line 163, in <module>
    from langchain_community.document_loaders.pebblo import PebbloSafeLoader
  File "C:\soft\lc\lib\site-packages\langchain_community\document_loaders\pebblo.py", line 5, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
请问这个如何解决
我安装全部依赖
$ pip install -r requirements.txt 
$ pip install -r requirements_api.txt
$ pip install -r requirements_webui.txt

**Comment by cq134cq** [comment]
pip install langchain-community==0.0.19
使用这个命令可以了，谢谢

**Comment by cq134cq** [comment]
(c:\soft\lc) C:\soft\lc>python init_database.py --recreate-vs
recreating all vector stores
2024-02-22 13:57:09,547 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh' from disk.
2024-02-22 13:57:09,901 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI\bge-large-zh
2024-02-22 13:57:10,973 - embeddings_api.py[line:39] - ERROR: Torch not compiled with CUDA enabled
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\soft\lc\init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "C:\soft\lc\server\knowledge_base\migrate.py", line 126, in folder2db
    kb.create_kb()
  File "C:\soft\lc\server\knowledge_base\kb_service\base.py", line 80, in create_kb
    self.do_create_kb()
  File "C:\soft\lc\server\knowledge_base\kb_service\faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "C:\soft\lc\server\knowledge_base\kb_service\faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "C:\soft\lc\server\knowledge_base\kb_cache\faiss_cache.py", line 102, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "C:\soft\lc\server\knowledge_base\kb_cache\faiss_cache.py", line 60, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
  File "C:\soft\lc\lib\site-packages\langchain_core\vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "C:\soft\lc\lib\site-packages\langchain_community\vectorstores\faiss.py", line 959, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "C:\soft\lc\server\knowledge_base\kb_service\base.py", line 420, in embed_documents
    return normalize(embeddings).tolist()
  File "C:\soft\lc\server\knowledge_base\kb_service\base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "C:\soft\lc\lib\site-packages\numpy\linalg\linalg.py", line 2541, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
请问这个如何解决，我以安装了，可以还是有问题
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by Nancy-wangxixi** [comment]
> pip install langchain-community==0.0.19 使用这个命令可以了，谢谢

我还是会报loop of ufunc does not support argument 0 of type Nodetype which has no callable conjugate method的错误。。。。

**Comment by kevinchi8781** [comment]
> pip install langchain-community==0.0.19
> 使用这个命令可以了，谢谢

我也是用这个命令以后，开始报TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by cq134cq** [comment]
你们的版本是0.2.10
langchain-ChatGLM 版本/commit 号：0.2.10

**Comment by cackako** [comment]
> > pip install langchain-community==0.0.19
> > 使用这个命令可以了，谢谢
> 
> 我也是用这个命令以后，开始报TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

请问你们这个怎么解决的呀

**Comment by zRzRzRzRzRzRzR** [comment]
这个是embedding模型没全吧，我又一次遇到了这个问题后检查模型文件发现是没全，一个embed模型都是几个G，少了就是文件没全

**Comment by chunshengding** [comment]
同问
