### ISSUE TITLE
[BUG] 使用sample知识库的时候报错

### ISSUE THREAD

**Issue by haitongwan** [chatchat-space/Langchain-Chatchat#3041]
exception
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/llm_langchain_chat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/data/llm/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/data/llm/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 221, in knowledge_base_page
    doc_grid = AgGrid(
               ^^^^^^^
  File "/usr/local/anaconda3/envs/llm_langchain_chat/lib/python3.11/site-packages/st_aggrid/__init__.py", line 356, in AgGrid
    row_data = __parse_row_data(data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/llm_langchain_chat/lib/python3.11/site-packages/st_aggrid/__init__.py", line 54, in __parse_row_data
    row_data = data_parameter.to_json(orient='records', date_format='iso')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/llm_langchain_chat/lib/python3.11/site-packages/pandas/core/generic.py", line 2532, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/llm_langchain_chat/lib/python3.11/site-packages/pandas/io/json/_json.py", line 191, in to_json
    ).write()
      ^^^^^^^
  File "/usr/local/anaconda3/envs/llm_langchain_chat/lib/python3.11/site-packages/pandas/io/json/_json.py", line 244, in write
    return dumps(
           ^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-5: surrogates not allowed

**Comment by zRzRzRzRzRzRzR** [comment]
你是不是打开了，正常我们是utf8编码，你是不是改了东西变成了其他编码，或者你的运行环境非utf8
