### ISSUE TITLE
[BUG]  救救孩子吧 变成在线LLM 和 Embedding 后 Exception in ASGI application 还有超时

### ISSUE THREAD

**Issue by Bo-LiangD** [chatchat-space/Langchain-Chatchat#3047]
**问题描述 / Exception in ASGI application
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
在使用线上模型进行知识库提问的时候会时长有这个问题
**复现问题的步骤 / Steps to Reproduce**
1. EMBEDDING_MODEL 使用本地或是 qwen-api 都不行
![1708599042353](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/758f9071-a2d6-4705-add5-0d7d2692b07e)
2.使用知识库提出问题的时候
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/1930b6d1-f021-42ce-9aa2-2c134b177c27)
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.48it/s]
2024-02-22 18:31:21 | INFO | stdout | INFO:     127.0.0.1:49670 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-02-22 18:31:21,462 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-02-22 18:31:21 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21006/worker_generate_stream "HTTP/1.1 200 OK"
2024-02-22 18:33:01 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-02-22 18:33:01 | ERROR | stderr | Traceback (most recent call last):
2024-02-22 18:33:01 | ERROR | stderr |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/responses.py", line 261, in __call__
2024-02-22 18:33:01 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-02-22 18:33:01 | ERROR | stderr |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/responses.py", line 257, in wrap
2024-02-22 18:33:01 | ERROR | stderr |     await func()
2024-02-22 18:33:01 | ERROR | stderr |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/responses.py", line 234, in listen_for_disconnect
2024-02-22 18:33:01 | ERROR | stderr |     message = await receive()
2024-02-22 18:33:01 | ERROR | stderr |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 580, in receive
2024-02-22 18:33:01 | ERROR | stderr |     await self.message_event.wait()
2024-02-22 18:33:01 | ERROR | stderr |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/asyncio/locks.py", line 214, in wait
2024-02-22 18:33:01 | ERROR | stderr |     await fut
2024-02-22 18:33:01 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f5c37e94850
2024-02-22 18:33:01 | ERROR | stderr | 
2024-02-22 18:33:01 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-02-22 18:33:01 | ERROR | stderr | 
2024-02-22 18:33:01 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2024-02-22 18:33:01 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/applications.py", line 119, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     raise exc
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-02-22 18:33:01 | ERROR | stderr |   |     raise exc
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-02-22 18:33:01 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
2024-02-22 18:33:01 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-02-22 18:33:01 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-02-22 18:33:01 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-02-22 18:33:01 | ERROR | stderr |   |     raise exc
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-02-22 18:33:01 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
2024-02-22 18:33:01 | ERROR | stderr |   |     await response(scope, receive, send)
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/responses.py", line 254, in __call__
2024-02-22 18:33:01 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-02-22 18:33:01 | ERROR | stderr |   |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
2024-02-22 18:33:01 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-02-22 18:33:01 | ERROR | stderr |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-02-22 18:33:01 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-02-22 18:33:01 | ERROR | stderr |     | Traceback (most recent call last):
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
2024-02-22 18:33:01 | ERROR | stderr |     |     yield
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_transports/default.py", line 252, in __aiter__
2024-02-22 18:33:01 | ERROR | stderr |     |     async for part in self._httpcore_stream:
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
2024-02-22 18:33:01 | ERROR | stderr |     |     raise exc from None
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
2024-02-22 18:33:01 | ERROR | stderr |     |     async for part in self._stream:
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
2024-02-22 18:33:01 | ERROR | stderr |     |     raise exc
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
2024-02-22 18:33:01 | ERROR | stderr |     |     async for chunk in self._connection._receive_response_body(**kwargs):
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
2024-02-22 18:33:01 | ERROR | stderr |     |     event = await self._receive_event(timeout=timeout)
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
2024-02-22 18:33:01 | ERROR | stderr |     |     data = await self._network_stream.read(
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 31, in read
2024-02-22 18:33:01 | ERROR | stderr |     |     with map_exceptions(exc_map):
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/contextlib.py", line 153, in __exit__
2024-02-22 18:33:01 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-02-22 18:33:01 | ERROR | stderr |     |     raise to_exc(exc) from exc
2024-02-22 18:33:01 | ERROR | stderr |     | httpcore.ReadTimeout
2024-02-22 18:33:01 | ERROR | stderr |     |
2024-02-22 18:33:01 | ERROR | stderr |     | The above exception was the direct cause of the following exception:
2024-02-22 18:33:01 | ERROR | stderr |     |
2024-02-22 18:33:01 | ERROR | stderr |     | Traceback (most recent call last):
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/responses.py", line 257, in wrap
2024-02-22 18:33:01 | ERROR | stderr |     |     await func()
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/starlette/responses.py", line 246, in stream_response
2024-02-22 18:33:01 | ERROR | stderr |     |     async for chunk in self.body_iterator:
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 473, in chat_completion_stream_generator
2024-02-22 18:33:01 | ERROR | stderr |     |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 658, in generate_completion_stream
2024-02-22 18:33:01 | ERROR | stderr |     |     async for raw_chunk in response.aiter_raw():
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_models.py", line 991, in aiter_raw
2024-02-22 18:33:01 | ERROR | stderr |     |     async for raw_stream_bytes in self.stream:
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_client.py", line 147, in __aiter__
2024-02-22 18:33:01 | ERROR | stderr |     |     async for chunk in self._stream:
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_transports/default.py", line 251, in __aiter__
2024-02-22 18:33:01 | ERROR | stderr |     |     with map_httpcore_exceptions():
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/contextlib.py", line 153, in __exit__
2024-02-22 18:33:01 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-02-22 18:33:01 | ERROR | stderr |     |   File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
2024-02-22 18:33:01 | ERROR | stderr |     |     raise mapped_exc(message) from exc
2024-02-22 18:33:01 | ERROR | stderr |     | httpx.ReadTimeout
2024-02-22 18:33:01 | ERROR | stderr |     +------------------------------------
2024-02-22 18:33:01,469 - utils.py[line:38] - ERROR: peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_transports/default.py", line 252, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
    raise exc from None
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
    async for part in self._stream:
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
    raise exc
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_async/http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abs/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/openai/_streaming.py", line 129, in __stream__
    async for sse in iterator:
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/openai/_streaming.py", line 120, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/openai/_streaming.py", line 231, in aiter
    async for line in iterator:
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_models.py", line 967, in aiter_lines
    async for text in self.aiter_text():
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_models.py", line 954, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_models.py", line 933, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_models.py", line 991, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_client.py", line 147, in __aiter__
    async for chunk in self._stream:
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_transports/default.py", line 251, in __aiter__
    with map_httpcore_exceptions():
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/abs/anaconda3/envs/Lcc210/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-02-22 18:33:01,470 - utils.py[line:40] - ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)
2024-02-22 18:49:03 | ERROR | model_worker | 请求千问 API 时发生错误：{'error_code': <HTTPStatus.INTERNAL_SERVER_ERROR: 500>, 'text': 'Role must be user or assistant and Content length must be greater than 0', 'error': {'message': 'Role must be user or assistant and Content length must be greater than 0', 'type': 'invalid_request_error', 'param': None, 'code': None}}

描述应该出现的结果 / Describe the expected result.
按理说 使用在线LLM和Embedding 本地文件会向量化成功但是并没有成功，可以看到向量化的结果
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/205fb604-cd83-4ad8-99b6-561f89655437)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM 0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： 在线 qwen-api,qwen-72b-chat  
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：在线 qwen-api ，或是 bge-large-zh-v1.5  
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 : Ubuntu 22.04
- Python 版本 / conda 3.10.13:

这是  在线配置
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/8d21eaac-c07e-49fb-a98c-0dfef1629919)
这两个在切换

**Comment by zRzRzRzRzRzRzR** [comment]
这大概率是配置问题吧，啥llm啊

**Comment by Bo-LiangD** [comment]
> 这大概率是配置问题吧，啥llm啊
qwen-72B-chat 
Embedding  是在线和 bge-large-zh-v1.5 在切换着测试
还需要配置啥嘛。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/b3a82d7d-5bfa-4808-bdea-5cc0afc80c91)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/7772305b-e132-4404-9e86-dd48e2e37e33)
而且今天测试agent 发现 跟上个版本有区别 使用联网的模型后 一致在报错😂😂😂

**Comment by zRzRzRzRzRzRzR** [comment]
有一定区别，另外qwen我刚测的，不应该会有链接错误的问题

**Comment by qweqweqweasdasd** [comment]
> > 这大概率是配置问题吧，啥llm啊
> > qwen-72B-chat
> > Embedding  是在线和 bge-large-zh-v1.5 在切换着测试
> > 还需要配置啥嘛。
> > ![image](https://private-user-images.githubusercontent.com/29296518/307211285-b3a82d7d-5bfa-4808-bdea-5cc0afc80c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDU3NDAsIm5iZiI6MTcxMDkwNTQ0MCwicGF0aCI6Ii8yOTI5NjUxOC8zMDcyMTEyODUtYjNhODJkN2QtNWJmYS00ODA4LWJkZWEtNWNjMGFmYzgwYzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzY2I5NDkzMWZlMzZjOWMxNDQ5YjczZmU2YWJkMDNkNjdkOGNjZTk1ZGM2NzAwNzdhMmJjZGQ0ZDg0MWNlYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CbDJZ_SfDhm2ehKZcFsZxJdwBrCJQGAcGCYf8B1zblc)
> > ![image](https://private-user-images.githubusercontent.com/29296518/307211310-7772305b-e132-4404-9e86-dd48e2e37e33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDU3NDAsIm5iZiI6MTcxMDkwNTQ0MCwicGF0aCI6Ii8yOTI5NjUxOC8zMDcyMTEzMTAtNzc3MjMwNWItZTEzMi00NDA0LTllODYtZGQ0OGUyZTM3ZTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjUwNDk0MmMxYTNjNjQwOTVlOTk1ZWFmNmY3MmU1ZTdiMzcwZjlhNzFjNjU4MDhhM2RhMmZkNWI2MmVhM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bP6UZOT1DBDYC_Nac94K0IwtTV_LelGUvMWBSaDcrA4)
> > 而且今天测试agent 发现 跟上个版本有区别 使用联网的模型后 一致在报错😂😂😂

你好请问有解决方法了吗
