### ISSUE TITLE
[BUG] python startup.py -a执行报错卡住

### ISSUE THREAD

**Issue by kevinchi8781** [chatchat-space/Langchain-Chatchat#3062]
(chat007) C:\AI\chat007\Langchain-Chatchat>python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22631-SP0.
python版本：3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cpu
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'C:\\AI\\models\\THUDM\\chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cpu
==============================Langchain-Chatchat Configuration==============================

2024-02-23 22:50:52,275 - startup.py[line:655] - INFO: 正在启动服务：
2024-02-23 22:50:52,275 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 C:\AI\chat007\Langchain-Chatchat\logs
C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-23 22:50:57 | ERROR | stderr | INFO:     Started server process [30488]
2024-02-23 22:50:57 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-23 22:50:57 | ERROR | stderr | INFO:     Application startup complete.
2024-02-23 22:50:57 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2024-02-23 22:50:58 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker dae5dde2 ...
Could not locate the tokenization_chatglm.py inside THUDM/chatglm3-6b.
2024-02-23 22:51:00 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-23 22:51:00 | ERROR | stderr | Traceback (most recent call last):
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
2024-02-23 22:51:00 | ERROR | stderr |     sock = connection.create_connection(
2024-02-23 22:51:00 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
2024-02-23 22:51:00 | ERROR | stderr |     raise err
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
2024-02-23 22:51:00 | ERROR | stderr |     sock.connect(sa)
2024-02-23 22:51:00 | ERROR | stderr | ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-23 22:51:00 | ERROR | stderr |
2024-02-23 22:51:00 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-02-23 22:51:00 | ERROR | stderr |
2024-02-23 22:51:00 | ERROR | stderr | Traceback (most recent call last):
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\connectionpool.py", line 779, in urlopen
2024-02-23 22:51:00 | ERROR | stderr |     self._prepare_proxy(conn)
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\connectionpool.py", line 1048, in _prepare_proxy
2024-02-23 22:51:00 | ERROR | stderr |     conn.connect()
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\connection.py", line 616, in connect
2024-02-23 22:51:00 | ERROR | stderr |     self.sock = sock = self._new_conn()
2024-02-23 22:51:00 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\connection.py", line 213, in _new_conn
2024-02-23 22:51:00 | ERROR | stderr |     raise NewConnectionError(
2024-02-23 22:51:00 | ERROR | stderr | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000029FFFAC4DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-02-23 22:51:00 | ERROR | stderr |
2024-02-23 22:51:00 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-02-23 22:51:00 | ERROR | stderr |
2024-02-23 22:51:00 | ERROR | stderr | urllib3.exceptions.ProxyError: ('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029FFFAC4DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-02-23 22:51:00 | ERROR | stderr |
2024-02-23 22:51:00 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-02-23 22:51:00 | ERROR | stderr |
2024-02-23 22:51:00 | ERROR | stderr | Traceback (most recent call last):
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\requests\adapters.py", line 486, in send
2024-02-23 22:51:00 | ERROR | stderr |     resp = conn.urlopen(
2024-02-23 22:51:00 | ERROR | stderr |            ^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
2024-02-23 22:51:00 | ERROR | stderr |     retries = retries.increment(
2024-02-23 22:51:00 | ERROR | stderr |               ^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
2024-02-23 22:51:00 | ERROR | stderr |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-02-23 22:51:00 | ERROR | stderr |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/tokenization_chatglm.py (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029FFFAC4DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2024-02-23 22:51:00 | ERROR | stderr |
2024-02-23 22:51:00 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-02-23 22:51:00 | ERROR | stderr |
2024-02-23 22:51:00 | ERROR | stderr | Traceback (most recent call last):
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\multiprocessing\process.py", line 314, in _bootstrap
2024-02-23 22:51:00 | ERROR | stderr |     self.run()
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\multiprocessing\process.py", line 108, in run
2024-02-23 22:51:00 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\AI\chat007\Langchain-Chatchat\startup.py", line 389, in run_model_worker
2024-02-23 22:51:00 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-23 22:51:00 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\AI\chat007\Langchain-Chatchat\startup.py", line 217, in create_model_worker_app
2024-02-23 22:51:00 | ERROR | stderr |     worker = ModelWorker(
2024-02-23 22:51:00 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-02-23 22:51:00 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-23 22:51:00 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\fastchat\model\model_adapter.py", line 348, in load_model
2024-02-23 22:51:00 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-02-23 22:51:00 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\fastchat\model\model_adapter.py", line 816, in load_model
2024-02-23 22:51:00 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-02-23 22:51:00 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 797, in from_pretrained
2024-02-23 22:51:00 | ERROR | stderr |     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
2024-02-23 22:51:00 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\transformers\dynamic_module_utils.py", line 488, in get_class_from_dynamic_module
2024-02-23 22:51:00 | ERROR | stderr |     final_module = get_cached_module_file(
2024-02-23 22:51:00 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\transformers\dynamic_module_utils.py", line 294, in get_cached_module_file
2024-02-23 22:51:00 | ERROR | stderr |     resolved_module_file = cached_file(
2024-02-23 22:51:00 | ERROR | stderr |                            ^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\transformers\utils\hub.py", line 385, in cached_file
2024-02-23 22:51:00 | ERROR | stderr |     resolved_file = hf_hub_download(
2024-02-23 22:51:00 | ERROR | stderr |                     ^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
2024-02-23 22:51:00 | ERROR | stderr |     return fn(*args, **kwargs)
2024-02-23 22:51:00 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\huggingface_hub\file_download.py", line 1238, in hf_hub_download
2024-02-23 22:51:00 | ERROR | stderr |     metadata = get_hf_file_metadata(
2024-02-23 22:51:00 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
2024-02-23 22:51:00 | ERROR | stderr |     return fn(*args, **kwargs)
2024-02-23 22:51:00 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
2024-02-23 22:51:00 | ERROR | stderr |     r = _request_wrapper(
2024-02-23 22:51:00 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
2024-02-23 22:51:00 | ERROR | stderr |     response = _request_wrapper(
2024-02-23 22:51:00 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
2024-02-23 22:51:00 | ERROR | stderr |     response = get_session().request(method=method, url=url, **params)
2024-02-23 22:51:00 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\requests\sessions.py", line 589, in request
2024-02-23 22:51:00 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-02-23 22:51:00 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\requests\sessions.py", line 703, in send
2024-02-23 22:51:00 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-02-23 22:51:00 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
2024-02-23 22:51:00 | ERROR | stderr |     return super().send(request, *args, **kwargs)
2024-02-23 22:51:00 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 22:51:00 | ERROR | stderr |   File "C:\Users\1\anaconda3\envs\chat007\Lib\site-packages\requests\adapters.py", line 513, in send
2024-02-23 22:51:00 | ERROR | stderr |     raise ProxyError(e, request=request)
2024-02-23 22:51:00 | ERROR | stderr | requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/tokenization_chatglm.py (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029FFFAC4DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"), '(Request ID: 3e14bbac-2cd9-4a08-a187-a30d8b90f492)')

**Comment by kevinchi8781** [comment]
> _🤖_
> 
> 根据提供的上下文，您似乎遇到了多个问题。让我们一一解决它们。
> 
> 1. **缺少“tokenization_chatglm.py”文件**：此文件通常负责将输入文本标记化为模型可以理解的格式。如果缺少它，则可能是模型目录已损坏或不完整。您可以尝试从源存储库或模型的官方网站重新下载模型。有关类似问题及其解决方案，请参阅[此问题](https://github.com/chatchat-space/Langchain-Chatchat/issues/2937)。
> 2. **ConnectionRefusedError 和 MaxRetryError**：这些错误表明您的程序无法与“huggingface.co”服务器建立连接。这可能是由于网络问题、防火墙设置或服务器本身可能已关闭。您可以尝试以下几种方法：
>    
>    * 检查您的互联网连接并确保其稳定。
>    * 如果您位于防火墙后面，请确保它不会阻止您的程序访问互联网。
>    * 尝试在 Web 浏览器中访问“huggingface.co”，查看服务器是否已启动并运行。
>    * 如果您使用的是代理，请确保其配置正确。您可以参考此问题，其中通过设置代理地址解决了类似的[问题](https://github.com/chatchat-space/Langchain-Chatchat/issues/2223)。
> 
> 如果问题仍然存在，您可能需要考虑使用不需要连接到“huggingface.co”的其他模型，或者您可以下载该模型并在本地使用它。
> 
> 至于“THUDM/chatglm3-6b”模型中“tokenization_chatglm.py”文件的确切功能以及它如何与 Langchain-Chatchat 代码库的其余部分交互，我无法在存储库中找到特定信息。但是，通常，此类文件将包含用于将输入文本标记为模型可以理解的格式的逻辑。每当模型需要处理输入或输出文本时，都会使用它。
> 
> 请注意，这些都是基于所提供上下文的一般建议。对于更具体的解决方案，需要有关错误消息和系统设置的更多详细信息。
> 
> ## 来源
> * [执行python startup.py -a 报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2937)
> * [python startup.py -a执行报错卡住](https://github.com/chatchat-space/Langchain-Chatchat/issues/2580)
> * [[BUG] 模型加载失败 报错：OSError： 我们无法连接到“https://huggingface.co”来加载此文件，在缓存的文件中找不到它，看起来 THUDM/chatglm3-6b 不是包含名为 configuration_chatglm.py 的文件的目录的路径。](https://github.com/chatchat-space/Langchain-Chatchat/issues/2223)
> * [configs/model_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example)
> 
> #### 关于Dosu
> 此响应旨在有用并节省您的时间。它**并不意味着是一个精确的解决方案**，而是你自己研究的起点。
> 
> 帮助我变得更有用！如果这有帮助，👎请留下一个👍，如果它无关紧要。
> 
> 如果您想继续对话，请以 开始回复。

C:\AI\models\THUDM\chatglm3-6b     有这个文件tokenization_chatglm.py，我在model_config.py文件配置了这个，
"chatglm3-6b": "C:\\AI\\models\\THUDM\\chatglm3-6b",
