### ISSUE TITLE
[BUG] 把faiss向量库换成pgvector后初始化有问题，感觉是connection uri配置的地方不对

### ISSUE THREAD

**Issue by Ryan512527** [chatchat-space/Langchain-Chatchat#3065]
recreating all vector stores
Traceback (most recent call last):
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: FATAL:  role "postgres" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/pgvector.py", line 253, in create_vector_extension
    session.execute(statement)
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2131, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1998, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1123, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: FATAL:  role "postgres" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/migrate.py", line 119, in folder2db
    kb = KBServiceFactory.get_service(kb_name, vs_type, embed_model)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 310, in get_service
    return PGKBService(kb_name, embed_model=embed_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 64, in __init__
    self.do_init()
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/kb_service/pg_kb_service.py", line 39, in do_init
    self._load_pg_vector()
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/kb_service/pg_kb_service.py", line 23, in _load_pg_vector
    self.pg_vector = PGVector(embedding_function=EmbeddingsFunAdapter(self.embed_model),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/pgvector.py", line 212, in __init__
    self.__post_init__()
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/pgvector.py", line 218, in __post_init__
    self.create_vector_extension()
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/pgvector.py", line 256, in create_vector_extension
    raise Exception(f"Failed to create vector extension: {e}") from e
Exception: Failed to create vector extension: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: FATAL:  role "postgres" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by Ryan512527** [comment]
(chatchat) bogon:Langchain-Chatchat-master ryan$ python init_database.py --recreate-vs
recreating all vector stores
Traceback (most recent call last):
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFile: could not open extension control file "/usr/local/opt/postgresql@12/share/postgresql@12/extension/vector.control": No such file or directory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/pgvector.py", line 253, in create_vector_extension
    session.execute(statement)
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2150, in _execute_internal
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/local/opt/postgresql@12/share/postgresql@12/extension/vector.control": No such file or directory

[SQL: BEGIN;SELECT pg_advisory_xact_lock(1573678846307946496);CREATE EXTENSION IF NOT EXISTS vector;COMMIT;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/migrate.py", line 119, in folder2db
    kb = KBServiceFactory.get_service(kb_name, vs_type, embed_model)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 310, in get_service
    return PGKBService(kb_name, embed_model=embed_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 64, in __init__
    self.do_init()
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/kb_service/pg_kb_service.py", line 39, in do_init
    self._load_pg_vector()
  File "/Users/ryan/Downloads/Langchain-Chatchat-master/server/knowledge_base/kb_service/pg_kb_service.py", line 23, in _load_pg_vector
    self.pg_vector = PGVector(embedding_function=EmbeddingsFunAdapter(self.embed_model),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/pgvector.py", line 212, in __init__
    self.__post_init__()
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/pgvector.py", line 218, in __post_init__
    self.create_vector_extension()
  File "/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/pgvector.py", line 256, in create_vector_extension
    raise Exception(f"Failed to create vector extension: {e}") from e
Exception: Failed to create vector extension: (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/local/opt/postgresql@12/share/postgresql@12/extension/vector.control": No such file or directory

[SQL: BEGIN;SELECT pg_advisory_xact_lock(1573678846307946496);CREATE EXTENSION IF NOT EXISTS vector;COMMIT;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(chatchat) bogon:Langchain-Chatchat-master ryan$ 

需要创建一个新文件目录，还是把项目里的某个文件放进去
