### ISSUE TITLE
[BUG] 启动脚本文件startup.py时遇到的模型路径报错

### ISSUE THREAD

**Issue by Fripping** [chatchat-space/Langchain-Chatchat#3066]
**问题描述 / Problem Description**
在启动脚本文件startup.py加载chatglm3-6b，遇到了模型路径为空的报错

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py -a'
2. 问题出现 :
2024-02-24 13:31:46 | ERROR | stderr |    File "C:\Users\dell、\.cache\huggingface\modules\transformers_modules\chatglm3-6b\tokenization_chatglm.py", line 17, in __init__ assert os.path.isfile(model_path), model_path
2024-02-24 13:31:46 | ERROR | stderr |     AssertionError: None

是不是model.config配置文件的问题？

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本: Windows 10
- Python 版本 / Python version: 3.10.13
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

**Comment by Fripping** [comment]
@dosu-bot 补充一下具体报错：
2024-02-24 13:31:46 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-24 13:31:46 | ERROR | stderr | Traceback (most recent call last):
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Anaconda3\envs\SciAgent\lib\multiprocessing\process.py", line 314, in _bootstrap
2024-02-24 13:31:46 | ERROR | stderr |     self.run()
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Anaconda3\envs\SciAgent\lib\multiprocessing\process.py", line 108, in run
2024-02-24 13:31:46 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Pythonfiles\Langchain-Chatchat\startup.py", line 389, in run_model_worker
2024-02-24 13:31:46 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Pythonfiles\Langchain-Chatchat\startup.py", line 217, in create_model_worker_app
2024-02-24 13:31:46 | ERROR | stderr |     worker = ModelWorker(
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Anaconda3\envs\SciAgent\lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-02-24 13:31:46 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Anaconda3\envs\SciAgent\lib\site-packages\fastchat\model\model_adapter.py", line 348, in load_model
2024-02-24 13:31:46 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Anaconda3\envs\SciAgent\lib\site-packages\fastchat\model\model_adapter.py", line 816, in load_model
2024-02-24 13:31:46 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Anaconda3\envs\SciAgent\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 801, in from_pretrained
2024-02-24 13:31:46 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Anaconda3\envs\SciAgent\lib\site-packages\transformers\tokenization_utils_base.py", line 2029, in from_pretrained
2024-02-24 13:31:46 | ERROR | stderr |     return cls._from_pretrained(
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Anaconda3\envs\SciAgent\lib\site-packages\transformers\tokenization_utils_base.py", line 2261, in _from_pretrained
2024-02-24 13:31:46 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Users\dell、\.cache\huggingface\modules\transformers_modules\chatglm3-6b\tokenization_chatglm.py", line 109, in __init__
2024-02-24 13:31:46 | ERROR | stderr |     self.tokenizer = SPTokenizer(vocab_file)
2024-02-24 13:31:46 | ERROR | stderr |   File "C:\Users\dell、\.cache\huggingface\modules\transformers_modules\chatglm3-6b\tokenization_chatglm.py", line 17, in __init__
2024-02-24 13:31:46 | ERROR | stderr |     assert os.path.isfile(model_path), model_path
2024-02-24 13:31:46 | ERROR | stderr | AssertionError: None
希望能进一步推理出报错原因

**Comment by Fripping** [comment]
@dosu-bot 另外run_model_maker是哪个文件的函数？

**Comment by zRzRzRzRzRzRzR** [comment]
2024-02-24 13:31:46 | ERROR | stderr | AssertionError: None 你模型位置没对吧

**Comment by Fripping** [comment]
@zRzRzRzRzRzRzR 检查过了，配置文件上的路径是没问题的

**Comment by zRzRzRzRzRzRzR** [comment]
\dell、.cache 这不是明显有问题么
