### ISSUE TITLE
[BUG] 无法新建数据库

### ISSUE THREAD

**Issue by wusongbai139** [chatchat-space/Langchain-Chatchat#3067]
**问题描述 / Problem Description**
无法新建数据库

**复现问题的步骤 / Steps to Reproduce**
在建立数据库的时候，一直停留在建立页面上
<img width="877" alt="微信图片_20240225132833" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/69897981/3d695ffe-622f-4c91-9874-ea1c9e5084ff">
后台显示如下：
INFO:     127.0.0.1:64178 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-02-25 13:21:59,628 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-02-25 13:23:05,709 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/search_docs: timed out
  File "H:\agent\LBchat\webui_pages\knowledge_base\knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
TypeError: string indices must be integers2024-02-25 13:32:00,839 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/search_docs: timed out
2024-02-25 13:32:18,410 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/create_knowledge_base: timed out
2024-02-25 13:37:00,864 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/search_docs: timed out
2024-02-25 13:37:00.865 Uncaught app exceptionTraceback (most recent call last):  File "H:\anaconda3\envs\chatchat\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script    exec(code, module.__dict__)  File "H:\agent\LBchat\webui.py", line 64, in <module>    pages[selected_page]["func"](api=api, is_lite=is_lite)  File "H:\agent\LBchat\webui_pages\knowledge_base\knowledge_base.py", line 328, in knowledge_base_page    data = [  File "H:\agent\LBchat\webui_pages\knowledge_base\knowledge_base.py", line 329, in <listcomp>    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),TypeError: string indices must be integers2024-02-25 13:37:18,421 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/create_knowledge_base: timed out

**环境信息 / Environment Information**
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

**附加信息 / Additional Information**
执行“python init_database.py --recreate-vs”没有问题的。

**Comment by zRzRzRzRzRzRzR** [comment]
尝试一下本地行不行

**Comment by lrn201** [comment]
我也遇到这个问题了，但我用的就是本地的模型

> INFO: loading vector store in '14/vector_store/bge-large-zh-v1.5' from disk.
> 2024-03-22 11:07:07,460 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/create_knowledge_base: timed out
>

**Comment by lrn201** [comment]
> 我也遇到这个问题了，但我用的就是本地的模型
> 
> > INFO: loading vector store in '14/vector_store/bge-large-zh-v1.5' from disk.
> > 2024-03-22 11:07:07,460 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/create_knowledge_base: timed out

我重新下载了模型，重新启动了几次就好了，具体原因还不知道为什么
