### ISSUE TITLE
pgvector    POST /knowledge_base/search_docs HTTP/1.1" 500 Internal Server Error

### ISSUE THREAD

**Issue by nilin1998** [chatchat-space/Langchain-Chatchat#3073]
当向量知识库选用pgvector，查询向量数据库是报错，错误如下：

INFO:     127.0.0.1:58621 - "POST /knowledge_base/search_docs HTTP/1.1" 500 Internal Server Error
2024-02-26 09:20:10,509 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "ARRAY"
LINE 1: ...ROM langchain_pg_embedding WHERE collection_id in ARRAY['ee8...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\langchain\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Anaconda\envs\langchain\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\Anaconda\envs\langchain\lib\site-packages\fastapi\applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Anaconda\envs\langchain\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\Anaconda\envs\langchain\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\Anaconda\envs\langchain\lib\site-packages\fastapi\routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "D:\Anaconda\envs\langchain\lib\site-packages\fastapi\routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\Anaconda\envs\langchain\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\Anaconda\envs\langchain\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Anaconda\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Anaconda\envs\langchain\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\TSD_work\langchain software\Langchain-Chatchat\server\knowledge_base\kb_doc_api.py", line 41, in search_docs
    data = kb.list_docs(file_name=file_name, metadata=metadata)
  File "D:\TSD_work\langchain software\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 214, in list_docs
    doc_info = self.get_doc_by_ids([x["id"]])[0]
  File "D:\TSD_work\langchain software\Langchain-Chatchat\server\knowledge_base\kb_service\pg_kb_service.py", line 33, in get_doc_by_ids
    session.execute(stmt, {'ids': ids}).fetchall()]
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\orm\session.py", line 2308, in execute
    return self._execute_internal(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\orm\session.py", line 2199, in _execute_internal
    result = conn.execute(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "D:\Anaconda\envs\langchain\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "ARRAY"
LINE 1: ...ROM langchain_pg_embedding WHERE collection_id in ARRAY['ee8...
                                                             ^

[SQL: SELECT document, cmetadata FROM langchain_pg_embedding WHERE collection_id in %(ids)s]
[parameters: {'ids': ['ee8d832d-d211-11ee-9321-000ec654f358']}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-02-26 09:20:10.535 Uncaught app exception
Traceback (most recent call last):
  File "D:\Anaconda\envs\langchain\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\TSD_work\langchain software\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\TSD_work\langchain software\Langchain-Chatchat\webui_pages\knowledge_base\knowledge_base.py", line 328, in knowledge_base_page
    data = [
  File "D:\TSD_work\langchain software\Langchain-Chatchat\webui_pages\knowledge_base\knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
TypeError: string indices must be integers

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）Qwen-72b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：pgvector
- 操作系统及版本 / Operating system and version:windows
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:PostgreSQL 11.23 

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by ghyaauoo** [comment]
我也遇到了一样的问题，看上去这边会用元数据表file_doc的doc_id去检索向量库中的langchain_pg_embedding表的相同collection_id的数据，但这两个表的数据并不一致

**Comment by ghyaauoo** [comment]
应该换成custom_id关联，SQL调整如下
SELECT document, cmetadata FROM langchain_pg_embedding WHERE custom_id in :ids

**Comment by Adsryen** [comment]
同样遇到这个问题，我觉得知识库可能更关心数据库一些，完善向量数据库的适配，或许应该优先进行
