### ISSUE TITLE
mac 跑起来网页，但是无法输出，object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by liuhuanshuo** [chatchat-space/Langchain-Chatchat#3098]
**问题描述 / Problem Description**
使用 mac m1 经过一番折腾，终于成功启动网页，但是无法和大模型对话

**复现问题的步骤 / Steps to Reproduce**
相关日志我贴在下面的报错代码里面了。

设备是 mac m1 的，其实在配置的时候就有一堆问题，但是通过检索 issue 和相关文章，成功把服务跑起来了。

但是在和大模型对话的时候，网页没有输出，后台报错。

> 选择知识库对话的话，倒是可以检索

```
2024-02-28 11:13:06,307 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
```

我并没有检索到对我有用的相关 issue 解决方案，另外，我注意到还有如下 warning，推测是大模型没有加载成功？但是不清楚具体该如何去解决

```
2024-02-28 11:08:13 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting eos_token is not supported, use the default one.
2024-02-28 11:08:13 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting pad_token is not supported, use the default one.
2024-02-28 11:08:13 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting unk_token is not supported, use the default one.
```

**预期的结果 / Expected Result**
正常回复

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
```
==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-12.6-arm64-arm-64bit.
python版本：3.10.6 (main, Oct 24 2022, 11:04:07) [Clang 12.0.0 ]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ mps
{'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/Users/liuhuanshuo/Desktop/Langchain-Chatchat/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh @ mps
==============================Langchain-Chatchat Configuration==============================


2024-02-28 11:07:56,723 - startup.py[line:655] - INFO: 正在启动服务：
2024-02-28 11:07:56,723 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /Users/liuhuanshuo/Desktop/Langchain-Chatchat/logs
/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-28 11:08:02 | ERROR | stderr | INFO:     Started server process [14869]
2024-02-28 11:08:02 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-28 11:08:02 | ERROR | stderr | INFO:     Application startup complete.
2024-02-28 11:08:02 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-02-28 11:08:03 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 94a350ba ...
2024-02-28 11:08:13 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting eos_token is not supported, use the default one.
2024-02-28 11:08:13 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting pad_token is not supported, use the default one.
2024-02-28 11:08:13 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting unk_token is not supported, use the default one.
Loading checkpoint shards:   0%|                                                                                                                                  | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|█████████████████▍                                                                                                        | 1/7 [00:03<00:18,  3.03s/it]
Loading checkpoint shards:  29%|██████████████████████████████████▊                                                                                       | 2/7 [00:07<00:18,  3.70s/it]
Loading checkpoint shards:  43%|████████████████████████████████████████████████████▎                                                                     | 3/7 [00:10<00:14,  3.59s/it]
Loading checkpoint shards:  57%|█████████████████████████████████████████████████████████████████████▋                                                    | 4/7 [00:14<00:10,  3.61s/it]
Loading checkpoint shards:  71%|███████████████████████████████████████████████████████████████████████████████████████▏                                  | 5/7 [00:18<00:07,  3.71s/it]
Loading checkpoint shards:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 6/7 [00:23<00:04,  4.31s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:25<00:00,  3.64s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:25<00:00,  3.70s/it]
2024-02-28 11:08:39 | ERROR | stderr | 
2024-02-28 11:09:30 | INFO | model_worker | Register to controller
INFO:     Started server process [15849]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)


==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-12.6-arm64-arm-64bit.
python版本：3.10.6 (main, Oct 24 2022, 11:04:07) [Clang 12.0.0 ]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ mps
{'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/Users/liuhuanshuo/Desktop/Langchain-Chatchat/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh @ mps


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================



  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2024-02-28 11:09:56,222 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58458 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-28 11:09:56,227 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-02-28 11:09:56,355 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58458 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-28 11:09:56,359 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:58458 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-02-28 11:09:56,367 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-02-28 11:13:02,399 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59795 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-28 11:13:02,403 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-02-28 11:13:02,434 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59795 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-02-28 11:13:02,440 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59795 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-02-28 11:13:02,479 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59795 - "POST /chat/chat HTTP/1.1" 200 OK
2024-02-28 11:13:02,490 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-02-28 11:13:02 | INFO | stdout | INFO:     127.0.0.1:59801 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-02-28 11:13:02,874 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-02-28 11:13:02 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
/Users/liuhuanshuo/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py:822: UserWarning: MPS: no support for int64 for all_all_out, downcasting to a smaller data type (int32/float32). Native support for int64 has been added in macOS 13.3. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/ReduceOps.mm:1399.)
  if (attention_mask is not None and not attention_mask.all()) or (past_key_values and seq_length != 1):
2024-02-28 11:13:06,307 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/liuhuanshuo/Desktop/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-02-28 11:13:06,311 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：latest
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: macOS 12.6
- Python 版本 / Python version:3.10.6
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liuhuanshuo** [comment]
> 参数设置有问题，但是这个需要自己查一下，有可能相关内容太长，如果是直接对话很大概率就是模型运行报错了，这个项目不会执行内部模型调用的错误

有没有排查的方向？搜了很多，没找到该往哪个配置文件上查。

就一个你好都没法回答

**Comment by reid41** [comment]
同问

**Comment by reid41** [comment]
`chat/completions "HTTP/1.1 200 OK"
---------chuck--------- {'id': 'chatcmpl-4J2Jnuy7KfaALAUhuPQNqq', 'choices': [{'delta': {'content': None, 'function_call': None, 'role': 'assistant', 'tool_calls': None}, 'finish_reason': None, 'index': 0, 'logprobs': None}], 'created': None, 'model': 'chatglm3-6b', 'object': None, 'system_fingerprint': None}
2024-02-29 12:24:52 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
---------chuck--------- {'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'text': '**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n("addmm_impl_cpu_" not implemented for \'Half\')', 'error_code': 50001}
2024-02-29 12:24:52,756 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/root/src/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 523, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 494, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-02-29 12:24:52,757 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()`

**Comment by JiadiLee** [comment]
有没有排查过显存，或者系统资源的使用情况？我在其它问题里有看到过回复说是显存不够会出现这种问题，我这边是因为还跑了其它服务，24G的显存占了得快23G了，再跑大模型对话的时候，就报这个错了，不知道对你有没有帮助。
