### ISSUE TITLE
[BUG] RuntimeError: Internal: could not parse ModelProto from chatglm3-6b/tokenizer.model

### ISSUE THREAD

**Issue by ZhichaoOuyang** [chatchat-space/Langchain-Chatchat#3103]
运行 python startup.py -a 

报错：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.18.0-2.4.3.kwai.x86_64-x86_64-with-glibc2.27.
python版本：3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cpu
==============================Langchain-Chatchat Configuration==============================

2024-02-28 08:16:53,771 - startup.py[line:655] - INFO: 正在启动服务：
2024-02-28 08:16:53,771 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /home/ouyangzhichao/Langchain-Chatchat/logs
/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-28 08:17:01 | INFO | model_worker | Register to controller
2024-02-28 08:17:01 | ERROR | stderr | INFO:     Started server process [3160451]
2024-02-28 08:17:01 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-28 08:17:01 | ERROR | stderr | INFO:     Application startup complete.
2024-02-28 08:17:01 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-02-28 08:17:01 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 05c9ab76 ...
2024-02-28 08:17:02 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-28 08:17:02 | ERROR | stderr | Traceback (most recent call last):
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-28 08:17:02 | ERROR | stderr |     self.run()
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-28 08:17:02 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-02-28 08:17:02 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-28 08:17:02 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-02-28 08:17:02 | ERROR | stderr |     worker = ModelWorker(
2024-02-28 08:17:02 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-28 08:17:02 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-28 08:17:02 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 348, in load_model
2024-02-28 08:17:02 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-02-28 08:17:02 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 816, in load_model
2024-02-28 08:17:02 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-02-28 08:17:02 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 801, in from_pretrained
2024-02-28 08:17:02 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2024-02-28 08:17:02 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
2024-02-28 08:17:02 | ERROR | stderr |     return cls._from_pretrained(
2024-02-28 08:17:02 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2261, in _from_pretrained
2024-02-28 08:17:02 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-02-28 08:17:02 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/9addbe01105ca1939dd60a0e5866a1812be9daea/tokenization_chatglm.py", line 109, in __init__
2024-02-28 08:17:02 | ERROR | stderr |     self.tokenizer = SPTokenizer(vocab_file)
2024-02-28 08:17:02 | ERROR | stderr |                      ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/9addbe01105ca1939dd60a0e5866a1812be9daea/tokenization_chatglm.py", line 18, in __init__
2024-02-28 08:17:02 | ERROR | stderr |     self.sp_model = SentencePieceProcessor(model_file=model_path)
2024-02-28 08:17:02 | ERROR | stderr |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/sentencepiece/__init__.py", line 468, in Init
2024-02-28 08:17:02 | ERROR | stderr |     self.Load(model_file=model_file, model_proto=model_proto)
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/sentencepiece/__init__.py", line 961, in Load
2024-02-28 08:17:02 | ERROR | stderr |     return self.LoadFromFile(model_file)
2024-02-28 08:17:02 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr |   File "/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
2024-02-28 08:17:02 | ERROR | stderr |     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
2024-02-28 08:17:02 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-28 08:17:02 | ERROR | stderr | RuntimeError: Internal: could not parse ModelProto from chatglm3-6b/tokenizer.model

前置步骤都按照要求搞了，求大佬帮忙看看

**Comment by zRzRzRzRzRzRzR** [comment]
你模型是在hf下载的么，是不是模型没全

**Comment by ZhichaoOuyang** [comment]
> 你模型是在hf下载的么，是不是模型没全

对，是不全的问题，重新下解决了

**Comment by liyiyiya** [comment]
> 运行 python startup.py -a
> 
> 报错： ==============================Langchain-Chatchat Configuration============================== 操作系统：Linux-4.18.0-2.4.3.kwai.x86_64-x86_64-with-glibc2.27. python版本：3.11.5 （main， Sep 11 2023， 13：54：46） [GCC 11.2.0] 项目版本：v0.2.10 langchain版本：0.0.354.fastchat版本：0.2.35
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter 当前启动的LLM模型：['chatglm3-6b'， 'zhipu-api'， 'openai-api'] @ cpu {'device'： 'cuda'， 'host'： '0.0.0.0'， 'infer_turbo'： False， 'model_path'： 'chatglm3-6b'， 'model_path_exists'： True， 'port'： 20002} {'api_key'： ''， 'device'： 'auto'， 'host'： '0.0.0.0'， 'infer_turbo'： False， 'online_api'： True， 'port'： 21001， 'provider'： 'ChatGLMWorker'， 'version'： 'glm-4'， 'worker_class'： <class 'server.model_workers.zhipu.ChatGLMWorker'>} {'api_base_url'： ['https://api.openai.com/v1](https://api.openai.com/v1)'， 'api_key'： ''， 'device'： 'auto'， 'host'： '0.0.0.0'， 'infer_turbo'： False， 'model_name'： 'gpt-4'， 'online_api'： True， 'openai_proxy'： ''， 'port'： 20002} 当前Embbedings模型： bge-large-zh-v1.5 @ cpu ==============================Langchain-Chatchat Configuration==============================
> 
> 2024-02-28 08：16：53,771 - startup.py[line：655] - INFO： 正在启动服务： 2024-02-28 08：16：53,771 - startup.py[line：656] - INFO： 如需查看 llm_api 日志，请前往 /home/ouyangzhichao/langchain-chatchat/logs /home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/langchain_core/_api/deprecation.py：117： LangChainDeprecationWarning： 模型启动功能将于 Langchain-Chatchat 0.3.x重写，支持更多模式和加速启动，0.2.x中相关功能将废弃 warn_deprecated（ 2024-02-28 08：17：01 |资讯 |model_worker |注册控制器 2024-02-28 08：17：01 |错误 |斯特德尔 |信息：服务器进程已启动 [3160451] 2024-02-28 08：17：01 |错误 |斯特德尔 |信息：正在等待应用程序启动。 2024-02-28 08：17：01 |错误 |斯特德尔 |信息：应用程序启动完成。 2024-02-28 08：17：01 |错误 |斯特德尔 |信息：Uvicorn 在 http://0.0.0.0:20000 上运行（按 CTRL+C 退出） 2024-02-28 08：17：01 |资讯 |model_worker |在工作器 05c9ab76 上加载模型 ['chatglm3-6b'] ... 2024-02-28 08：17：02 |错误 |斯特德尔 |流程model_worker - chatglm3-6b： 2024-02-28 08：17：02 |错误 |斯特德尔 |回溯（最近一次调用最后）：2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/multiprocessing/process.py”，第 314 行，在 _bootstrap 2024-02-28 08：17：02 |错误 |斯特德尔 |自我运行（） 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/multiprocessing/process.py”，第 108 行，正在运行 2024-02-28 08：17：02 |错误 |斯特德尔 |self._target（*self._args， **self._kwargs） 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/langchain-chatchat/startup.py”，第 389 行，在 run_model_worker 2024-02-28 08：17：02 |错误 |斯特德尔 |app = create_model_worker_app（log_level=log_level， **kwargs） 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/langchain-chatchat/startup.py”，第 217 行，在 create_model_worker_app 2024-02-28 08：17：02 |错误 |斯特德尔 |worker = 模型工人（ 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/fastchat/serve/model_worker.py”，第 77 行，**init** 2024-02-28 08：17：02 |错误 |斯特德尔 |self.model， self.tokenizer = load_model（ 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/fastchat/model/model_adapter.py”，第 348 行，load_model 2024-02-28 08：17：02 |错误 |斯特德尔 |模型，分词器 = adapter.load_model（model_path， kwargs） 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/fastchat/model/model_adapter.py”，第 816 行，在 load_model 2024-02-28 08：17：02 |错误 |斯特德尔 |分词器 = AutoTokenizer.from_pretrained（ 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件 “/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py“，801行，在from_pretrained 2024-02-28 08：17：02 |错误 |斯特德尔 |返回 tokenizer_class.from_pretrained（pretrained_model_name_or_path， *inputs， **kwargs） 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py”，第 2029 行，在 from_pretrained 2024-02-28 08：17：02 |错误 |斯特德尔 |返回cls._from_pretrained（ 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py”，第 2261 行，_from_pretrained 2024-02-28 08：17：02 |错误 |斯特德尔 |分词器 = cls（*init_inputs， **init_kwargs） 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/9addbe01105ca1939dd60a0e5866a1812be9daea/tokenization_chatglm.py”，第 109 行，**init** 2024-02-28 08：17：02 |错误 |斯特德尔 |self.tokenizer = SPTokenizer（vocab_file） 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/9addbe01105ca1939dd60a0e5866a1812be9daea/tokenization_chatglm.py”，第 18 行，**init** 2024-02-28 08：17：02 |错误 |斯特德尔 |self.sp_model = SentencePieceProcessor（model_file=model_path） 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/sentencepiece/**init**.py”，第 468 行，在 Init 中 2024-02-28 08：17：02 |错误 |斯特德尔 |自我。负载（model_file=model_file， model_proto=model_proto） 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/sentencepiece/**init**.py”，第 961 行，加载 2024-02-28 08：17：02 |错误 |斯特德尔 |返回自我。LoadFromFile（model_file） 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |文件“/home/ouyangzhichao/anaconda3/lib/python3.11/site-packages/sentencepiece/**init**.py”，第 316 行，在 LoadFromFile 2024-02-28 08：17：02 |错误 |斯特德尔 |返回_sentencepiece。SentencePieceProcessor_LoadFromFile（self， arg） 2024-02-28 08：17：02 |错误 |斯特德尔 |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-02-28 08：17：02 |错误 |斯特德尔 |RuntimeError：内部：无法从 chatglm3-6b/tokenizer.model 解析 ModelProto
> 
> 前置步骤都按照要求搞了，求大佬帮忙看看

兄弟，你是怎么解决的呀，我也出现这个问题了

**Comment by liyiyiya** [comment]
> > 你模型是在hf下载的么，是不是模型没全
> 
> 对，是不全的问题，重新下解决了

兄弟怎么重新下呀？跟着文档重新来一遍吗？还需要初始化吗？

**Comment by liyiyiya** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/166470931/fdc6cc51-3c25-4f01-a6ba-37d6447ee9db)
我的是这样，这是全的吗。我看不缺呀

**Comment by swordqiqi** [comment]
哥们，我遇到了同样的问题，你试试重新上传一下tokenizer.model能不能解决。

**Comment by biu0924** [comment]
同问，怎么个不全法啊，我重新下了很多次了

**Comment by Stevenzwzhai** [comment]
![image](https://github.com/user-attachments/assets/edc8c437-6fe9-452c-9e96-b405b454f55b)
模型要下载，一般来说直接git clone很快结束是不会下载完10多G的模型的

**Comment by lixuancn** [comment]
本质是没有git lfs，安装一下就好了。https://git-lfs.com/  
<img width="590" alt="image" src="https://github.com/user-attachments/assets/5de3a441-040c-4e24-9f63-76ea0973ceb4">

**Comment by zejun-chen** [comment]
我也遇到了这个问题，llama3预训练，比较过tokenizer json文件的sha256sum，完全一致，说明数据完整性没问题，不需要重新下载的
现在仍然不能被parse，不知道要怎么做？
出错的log如下：
```
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/sdp/miniforge3/envs/zejun_llama_train/lib/python3.10/site-packages/sentencepiece/__init__.py", line 963, in Load
    return self.LoadFromFile(model_file)
  File "/home/sdp/miniforge3/envs/zejun_llama_train/lib/python3.10/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
**_RuntimeError: Internal: could not parse ModelProto from /mnt/frameworks.ai.pytorch.gpu-models.lfs-data/datasets/red_pajama_1T_llama3tok_sample/llama3_tokenizer/tokenizer.json_**

```

**Comment by Magic-Pony** [comment]
> 我也遇到了这个问题，llama3预训练，比较过tokenizer json文件的sha256sum，完全一致，说明数据完整性没问题，不需要重新下载的 现在仍然不能被parse，不知道要怎么做？ 出错的log如下：
> 
> ```
>     self.Load(model_file=model_file, model_proto=model_proto)
>   File "/home/sdp/miniforge3/envs/zejun_llama_train/lib/python3.10/site-packages/sentencepiece/__init__.py", line 963, in Load
>     return self.LoadFromFile(model_file)
>   File "/home/sdp/miniforge3/envs/zejun_llama_train/lib/python3.10/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
>     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
> **_RuntimeError: Internal: could not parse ModelProto from /mnt/frameworks.ai.pytorch.gpu-models.lfs-data/datasets/red_pajama_1T_llama3tok_sample/llama3_tokenizer/tokenizer.json_**
> ```

same problem. Have you found the solution?
