### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by mwang12345** [chatchat-space/Langchain-Chatchat#3109]
V0.2.9版本自定义Agent使用时，报这个异常
![异常截图](https://github.com/chatchat-space/Langchain-Chatchat/assets/14009055/1773efce-65a8-474e-ac02-a09d12d9a65f)

2024-02-28 20:43:22.638 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/langchain-env/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/opt/software/Langchain-Chatchat-0.2.9/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/opt/software/Langchain-Chatchat-0.2.9/webui_pages/dialogue/dialogue.py", line 358, in dialogue_page
    if chunk := d.get("answer"):

**Comment by zRzRzRzRzRzRzR** [comment]
不要选择defalut，选择GLM模板
