### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by zoufuxing** [chatchat-space/Langchain-Chatchat#3117]
使用python startup.py -a启动，有如下报错，网上查了很久，没找到有具体的解决办法。

/opt/software/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-29 16:23:13 | INFO | model_worker | Register to controller
Process api_worker - zhipu-api:
Traceback (most recent call last):
  File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/trendsi/Langchain-Chatchat/startup.py", line 389, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trendsi/Langchain-Chatchat/startup.py", line 100, in create_model_worker_app
    worker = worker_class(model_names=args.model_names,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trendsi/Langchain-Chatchat/server/model_workers/zhipu.py", line 53, in __init__
    super().__init__(**kwargs)
  File "/home/trendsi/Langchain-Chatchat/server/model_workers/base.py", line 124, in __init__
    self.init_heart_beat()
  File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/base_model_worker.py", line 79, in init_heart_beat
    self.register_to_controller()
  File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/base_model_worker.py", line 97, in register_to_controller
    assert r.status_code == 200
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
2024-02-29 16:23:13 | ERROR | stderr | INFO:     Started server process [38567]
2024-02-29 16:23:13 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-29 16:23:13 | ERROR | stderr | INFO:     Application startup complete.
2024-02-29 16:23:13 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-02-29 16:23:14 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 29f5d241 ...
2024-02-29 16:23:15 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting eos_token is not supported, use the default one.
2024-02-29 16:23:15 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting pad_token is not supported, use the default one.
2024-02-29 16:23:15 | WARNING | transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm | Setting unk_token is not supported, use the default one.
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:06<00:37,  6.32s/it]
Loading checkpoint shards:  29%|████████████████▎                                        | 2/7 [00:07<00:15,  3.10s/it]
Loading checkpoint shards:  43%|████████████████████████▍                                | 3/7 [00:07<00:08,  2.04s/it]
Loading checkpoint shards:  57%|████████████████████████████████▌                        | 4/7 [00:08<00:04,  1.52s/it]
Loading checkpoint shards:  71%|████████████████████████████████████████▋                | 5/7 [00:09<00:02,  1.25s/it]
Loading checkpoint shards:  86%|████████████████████████████████████████████████▊        | 6/7 [00:10<00:01,  1.09s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.07it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.55s/it]
2024-02-29 16:23:26 | ERROR | stderr | 
2024-02-29 16:23:31 | INFO | model_worker | Register to controller
2024-02-29 16:23:31 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-02-29 16:23:31 | ERROR | stderr | Traceback (most recent call last):
2024-02-29 16:23:31 | ERROR | stderr |   File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-29 16:23:31 | ERROR | stderr |     self.run()
2024-02-29 16:23:31 | ERROR | stderr |   File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-29 16:23:31 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-29 16:23:31 | ERROR | stderr |   File "/home/trendsi/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-02-29 16:23:31 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-29 16:23:31 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29 16:23:31 | ERROR | stderr |   File "/home/trendsi/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-02-29 16:23:31 | ERROR | stderr |     worker = ModelWorker(
2024-02-29 16:23:31 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-29 16:23:31 | ERROR | stderr |   File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 102, in __init__
2024-02-29 16:23:31 | ERROR | stderr |     self.init_heart_beat()
2024-02-29 16:23:31 | ERROR | stderr |   File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/base_model_worker.py", line 79, in init_heart_beat
2024-02-29 16:23:31 | ERROR | stderr |     self.register_to_controller()
2024-02-29 16:23:31 | ERROR | stderr |   File "/opt/software/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/base_model_worker.py", line 97, in register_to_controller
2024-02-29 16:23:31 | ERROR | stderr |     assert r.status_code == 200
2024-02-29 16:23:31 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-02-29 16:23:31 | ERROR | stderr | AssertionError

**Comment by zoufuxing** [comment]
运行环境如下
操作系统：Ubuntu 22.04.3 LTS
python： 3.11.5
使用miniconda3虚拟环境

**Comment by manhere** [comment]
关闭代理

**Comment by zoufuxing** [comment]
> 关闭代理

没有设置代理

**Comment by litongyun233** [comment]
同样的问题

**Comment by mxyq** [comment]
> 关闭代理

测试有效
