### ISSUE TITLE
最轻模式本地部署对接线上API对话报错

### ISSUE THREAD

**Issue by ChengRuiLiang** [chatchat-space/Langchain-Chatchat#3131]
**最轻模式本地部署对接线上API对话报错**

**已操作的步骤 **
1. EMBEDDING_MODEL = "text-embedding-v1"
2. LLM_MODELS = ["qwen-max"]
3.     # 阿里云通义千问 API，文档参考 https://help.aliyun.com/zh/dashscope/developer-reference/api-details
    "qwen-api": {
        "version": "qwen-max",
        "api_key": ".........",
        "provider": "QwenWorker",
        "embed_model": "text-embedding-v1"  # embedding 模型名称
    }
4. pip为报错，已下载qwen-api: dashscope

**报错如下：**
2024-03-01 17:02:05,559 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"                   
2024-03-01 17:02:06 | INFO | stdout | INFO:     127.0.0.1:52375 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2024-03-01 17:02:06,037 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 400 Bad Request"              
2024-03-01 17:02:06,038 - utils.py[line:38] - ERROR: Error code: 400 - {'object': 'error', 'message': 'Only  allowed now, your model qwen-max', 'code': 40301}
Traceback (most recent call last):
  File "E:\pythonProject\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain_community\chat_models\openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain_community\chat_models\openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\langchain_community\chat_models\openai.py", line 105, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\openai\resources\chat\completions.py", line 1300, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\openai\_base_client.py", line 1703, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\openai\_base_client.py", line 1406, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\Langchain-Chatchat\venv\Lib\site-packages\openai\_base_client.py", line 1497, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Only  allowed now, your model qwen-max', 'code': 40301}
2024-03-01 17:02:06,040 - utils.py[line:40] - ERROR: BadRequestError: Caught exception: Error code: 400 - {'object': 'error', 'message': 'Only  allowed now, your model qwen-max', 'code': 40301}

**Comment by ChengRuiLiang** [comment]
我这个解决了，EMBEDDING_MODEL = "text-embedding-v1" 和 LLM_MODELS = ["qwen-max"] 中的值都填qwen-api就可以了
