### ISSUE TITLE
cuda,pytorch不识别

### ISSUE THREAD

**Issue by cstkn** [chatchat-space/Langchain-Chatchat#3140]
我安装了cuda12.1
但是当我使用pip install torch torchvision torchaudio cudatoolkit==12.1 -f [https://download.pytorch.org/whl/torch_stable.html时报错ERROR](https://download.pytorch.org/whl/torch_stable.html%E6%97%B6%E6%8A%A5%E9%94%99ERROR): Could not find a version that satisfies the requirement cudatoolkit==12.1 (from versions: none)
ERROR: No matching distribution found for cudatoolkit==12.1
(.venv) PS D:\wujiaping\chatglm\langchain-chatchat>
我尝试自己安装了最新版pytorch,运行后出现以下问题
2024-03-02 00:28:50,142 - startup.py[line:655] - INFO: 正在启动服务：
2024-03-02 00:28:50,143 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 D:\wujiaping\chatglm\langchain-chatchat\logs
D:\wujiaping\chatglm.venv\Lib\site-packages\langchain_core_api\deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将弃
warn_deprecated(
2024-03-02 00:28:54 | ERROR | stderr | INFO: Started server process [12492]
2024-03-02 00:28:54 | ERROR | stderr | INFO: Waiting for application startup.
2024-03-02 00:28:54 | ERROR | stderr | INFO: Application startup complete.
2024-03-02 00:28:54 | ERROR | stderr | INFO: Uvicorn running on http://127.0.0.1:20000/ (Press CTRL+C to quit)
2024-03-02 00:28:54 | INFO | model_worker | Register to controller
2024-03-02 00:28:55 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker d15d7072 ...
2024-03-02 00:28:55 | WARNING | transformers_modules.chatglm3-6b.tokenization_chatglm | Setting eos_token is not supported, use the default one.
2024-03-02 00:28:55 | WARNING | transformers_modules.chatglm3-6b.tokenization_chatglm | Setting pad_token is not supported, use the default one.
2024-03-02 00:28:55 | WARNING | transformers_modules.chatglm3-6b.tokenization_chatglm | Setting unk_token is not supported, use the default one.
Loading checkpoint shards: 0%| | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards: 14%|███████████████████▋ | 1/7 [00:01<00:07, 1.29s/it]
Loading checkpoint shards: 29%|███████████████████████████████████████▍ | 2/7 [00:02<00:06, 1.39s/it]
Loading checkpoint shards: 43%|███████████████████████████████████████████████████████████▏ | 3/7 [00:05<00:07, 1.92s/it]
Loading checkpoint shards: 57%|██████████████████████████████████████████████████████████████████████████████▊ | 4/7 [00:08<00:06, 2.27s/it]
Loading checkpoint shards: 71%|██████████████████████████████████████████████████████████████████████████████████████████████████▌ | 5/7 [00:19<00:10, 5.38s/it]
Loading checkpoint shards: 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 6/7 [00:32<00:08, 8.06s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:43<00:00, 9.13s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:43<00:00, 6.23s/it]
2024-03-02 00:29:40 | ERROR | stderr |
2024-03-02 00:29:40 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-03-02 00:29:40 | ERROR | stderr | Traceback (most recent call last):
2024-03-02 00:29:40 | ERROR | stderr | File "C:\Users\lycor\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
2024-03-02 00:29:40 | ERROR | stderr | self.run()
2024-03-02 00:29:40 | ERROR | stderr | File "C:\Users\lycor\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
2024-03-02 00:29:40 | ERROR | stderr | self._target(*self._args, **self._kwargs)
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm\langchain-chatchat\startup.py", line 389, in run_model_worker
2024-03-02 00:29:40 | ERROR | stderr | app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-02 00:29:40 | ERROR | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm\langchain-chatchat\startup.py", line 217, in create_model_worker_app
2024-03-02 00:29:40 | ERROR | stderr | worker = ModelWorker(
2024-03-02 00:29:40 | ERROR | stderr | ^^^^^^^^^^^^
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\fastchat\serve\model_worker.py", line 77, in init
2024-03-02 00:29:40 | ERROR | stderr | self.model, self.tokenizer = load_model(
2024-03-02 00:29:40 | ERROR | stderr | ^^^^^^^^^^^
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\fastchat\model\model_adapter.py", line 362, in load_model
2024-03-02 00:29:40 | ERROR | stderr | model.to(device)
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\transformers\modeling_utils.py", line 2595, in to
2024-03-02 00:29:40 | ERROR | stderr | return super().to(*args, **kwargs)
2024-03-02 00:29:40 | ERROR | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
2024-03-02 00:29:40 | ERROR | stderr | return self._apply(convert)
2024-03-02 00:29:40 | ERROR | stderr | ^^^^^^^^^^^^^^^^^^^^
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-03-02 00:29:40 | ERROR | stderr | module._apply(fn)
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-03-02 00:29:40 | ERROR | stderr | module._apply(fn)
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-03-02 00:29:40 | ERROR | stderr | module._apply(fn)
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\torch\nn\modules\module.py", line 833, in apply
2024-03-02 00:29:40 | ERROR | stderr | param_applied = fn(param)
2024-03-02 00:29:40 | ERROR | stderr | ^^^^^^^^^
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
2024-03-02 00:29:40 | ERROR | stderr | return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-03-02 00:29:40 | ERROR | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-02 00:29:40 | ERROR | stderr | File "D:\wujiaping\chatglm.venv\Lib\site-packages\torch\cuda_init.py", line 289, in _lazy_init
2024-03-02 00:29:40 | ERROR | stderr | raise AssertionError("Torch not compiled with CUDA enabled")
2024-03-02 00:29:40 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled

**Comment by zRzRzRzRzRzRzR** [comment]
请按照pytorch上的方式安装
