### ISSUE TITLE
当我尝试向数据库添加文档出现以下错误

### ISSUE THREAD

**Issue by cstkn** [chatchat-space/Langchain-Chatchat#3143]
2024-03-02 10:40:59,781 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51231 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:40:59,782 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-02 10:41:00,032 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51231 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:41:00,034 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51231 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-02 10:41:00,046 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-02 10:41:16,824 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51244 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:41:16,826 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-02 10:41:16,990 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51244 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:41:16,992 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51244 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-02 10:41:17,002 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-02 10:41:17.003 Please replace `st.experimental_rerun` with `st.rerun`.

`st.experimental_rerun` will be removed after 2024-04-01.
2024-03-02 10:41:17,435 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51247 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:41:17,438 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-02 10:41:17,606 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51247 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:41:17,606 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51247 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-02 10:41:17,615 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-02 10:41:22,742 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51254 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:41:22,744 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-02 10:41:22.745 Please replace `st.experimental_rerun` with `st.rerun`.

`st.experimental_rerun` will be removed after 2024-04-01.
2024-03-02 10:41:23,177 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51258 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:41:23,179 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-02 10:41:23,344 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51258 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-02 10:41:23,346 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51258 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-02 10:41:23,361 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-02 10:41:32,106 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh-v1.5' from disk.
2024-03-02 10:41:32,106 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5
2024-03-02 10:41:38,327 - utils.py[line:95] - ERROR: ReadError: error when post /knowledge_base/search_docs: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-03-02 10:41:38,327 - utils.py[line:95] - ERROR: ReadError: error when post /knowledge_base/search_docs: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-03-02 10:41:38,327 - utils.py[line:95] - ERROR: ReadError: error when post /knowledge_base/search_docs: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-03-02 10:41:40,352 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:40,352 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:40,352 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:42,373 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:42,373 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:42,373 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:42.373 Uncaught app exception
Traceback (most recent call last):
  File "D:\wujiaping\chatglm\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\wujiaping\chatglm\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\wujiaping\chatglm\langchain-chatchat\webui_pages\knowledge_base\knowledge_base.py", line 328, in knowledge_base_page
    data = [
           ^
  File "D:\wujiaping\chatglm\langchain-chatchat\webui_pages\knowledge_base\knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'
2024-03-02 10:41:42.373 Uncaught app exception
Traceback (most recent call last):
  File "D:\wujiaping\chatglm\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\wujiaping\chatglm\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\wujiaping\chatglm\langchain-chatchat\webui_pages\knowledge_base\knowledge_base.py", line 328, in knowledge_base_page
    data = [
           ^
  File "D:\wujiaping\chatglm\langchain-chatchat\webui_pages\knowledge_base\knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'
2024-03-02 10:41:42.373 Uncaught app exception
Traceback (most recent call last):
  File "D:\wujiaping\chatglm\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\wujiaping\chatglm\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\wujiaping\chatglm\langchain-chatchat\webui_pages\knowledge_base\knowledge_base.py", line 328, in knowledge_base_page
    data = [
           ^
  File "D:\wujiaping\chatglm\langchain-chatchat\webui_pages\knowledge_base\knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'
2024-03-02 10:41:47,594 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:49,623 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:51,658 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-02 10:41:51.658 Uncaught app exception
Traceback (most recent call last):
  File "D:\wujiaping\chatglm\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\wujiaping\chatglm\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\wujiaping\chatglm\langchain-chatchat\webui_pages\knowledge_base\knowledge_base.py", line 328, in knowledge_base_page
    data = [
           ^
  File "D:\wujiaping\chatglm\langchain-chatchat\webui_pages\knowledge_base\knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by Leng-bingo** [comment]
打开翻墙VPN即可解决，亲测问题

**Comment by ttPrivacy** [comment]
请问解决了吗 我也是同样的问题
vpn没用
