### ISSUE TITLE
utils.py[line:95] - ERROR: InvalidURL: error when post /llm_model/list_running_models: Invalid port: ':1'

### ISSUE THREAD

**Issue by hanwsf** [chatchat-space/Langchain-Chatchat#3147]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
python startup.py -a 出现不能查询到运行的模型，提示模型已经加载

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'python startup.py -a
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
-langchain                                    0.0.354
langchain-community                          0.0.8
langchain-core                               0.1.23
langchain-experimental                       0.0.47
langchain-serve                              0.0.41

- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）："ChatGLM2-6B-int4"或"ranchlai/chatglm3-6B-gptq-4bit"
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：GanymedeNil/text2vec-base-chinese
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: ubuntu20
- Python 版本 / Python version:3.10.0
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-170-generic-x86_64-with-glibc2.31.
python版本：3.10.10 (main, May 21 2023, 08:08:59) [GCC 9.4.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6B-gptq-4bit'] @ cpu
{'device': 'cpu',
 'host': 'localhost',
 'infer_turbo': False,
 'model_path': '/media/will/ssd-h/model_cache/chatglm3-6B-gptq-4bit',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： text2vec-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2024-03-02 20:27:54,444 - startup.py[line:659] - INFO: 正在启动服务：
2024-03-02 20:27:54,444 - startup.py[line:660] - INFO: 如需查看 llm_api 日志，请前往 /media/will/ssd-h/Langchain-Chatchat/logs
/media/will/ssd-h/Langchain-Chatchat/bot/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-03-02 20:28:12 | ERROR | stderr | INFO:     Started server process [40137]
2024-03-02 20:28:12 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-02 20:28:12 | ERROR | stderr | INFO:     Application startup complete.
2024-03-02 20:28:12 | ERROR | stderr | INFO:     Uvicorn running on http://localhost:20000 (Press CTRL+C to quit)
/media/will/ssd-h/Langchain-Chatchat/bot/lib/python3.10/site-packages/torch/cuda/__init__.py:611: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2024-03-02 20:28:15 | INFO | model_worker | Loading the model ['chatglm3-6B-gptq-4bit'] on worker a0d472c4 ...
2024-03-02 20:28:17 | INFO | datasets | PyTorch version 2.1.2 available.
2024-03-02 20:28:19 | WARNING | auto_gptq.nn_modules.qlinear.qlinear_cuda | CUDA extension not installed.
2024-03-02 20:28:19 | WARNING | auto_gptq.nn_modules.qlinear.qlinear_cuda_old | CUDA extension not installed.
Using `disable_exllama` is deprecated and will be removed in version 4.37. Use `use_exllama` instead and specify the version with `exllama_config`.The value of `use_exllama` will be overwritten by `disable_exllama` passed in `GPTQConfig` or stored in your config file.
2024-03-02 20:28:19 | ERROR | stderr | /media/will/ssd-h/Langchain-Chatchat/bot/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
2024-03-02 20:28:19 | ERROR | stderr |   return self.fget.__get__(instance, owner)()
2024-03-02 20:28:41 | INFO | model_worker | Register to controller
INFO:     Started server process [40448]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:7861 (Press CTRL+C to quit)
2024-03-02 20:29:10,169 - startup.py[line:470] - INFO: cmd:['streamlit', 'run', 'webui.py', '--server.address', 'localhost', '--server.port', '8501', '--theme.base', 'light', '--theme.primaryColor', '#165dff', '--theme.secondaryBackgroundColor', '#f5f5f5', '--theme.textColor', '#000000']

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-170-generic-x86_64-with-glibc2.31.
python版本：3.10.10 (main, May 21 2023, 08:08:59) [GCC 9.4.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6B-gptq-4bit'] @ cpu
{'device': 'cpu',
 'host': 'localhost',
 'infer_turbo': False,
 'model_path': '/media/will/ssd-h/model_cache/chatglm3-6B-gptq-4bit',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： text2vec-base @ cpu

服务端运行信息：
    OpenAI API Server: http://localhost:20000/v1
    Chatchat  API  Server: http://localhost:7861
    Chatchat WEBUI Server: http://localhost:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://localhost:8501

{}
2024-03-02 20:29:34,765 - utils.py[line:95] - ERROR: InvalidURL: error when post /llm_model/list_running_models: Invalid port: ':1'
{}
2024-03-02 20:29:34,843 - utils.py[line:95] - ERROR: InvalidURL: error when post /llm_model/list_running_models: Invalid port: ':1'
{}
2024-03-02 20:29:34,919 - utils.py[line:95] - ERROR: InvalidURL: error when post /llm_model/list_running_models: Invalid port: ':1'
{}
2024-03-02 20:29:35,079 - utils.py[line:95] - ERROR: InvalidURL: error when post /llm_model/list_running_models: Invalid port: ':1'
{}
2024-03-02 20:29:35,126 - utils.py[line:95] - ERROR: InvalidURL: error when post /llm_model/list_running_models: Invalid port: ':1'
{}
2024-03-02 20:29:35,192 - utils.py[line:95] - ERROR: InvalidURL: error when post /llm_model/list_running_models: Invalid port: ':1'
2024-03-02 20:29:35.194 Uncaught app exception
Traceback (most recent call last):
  File "/media/will/ssd-h/Langchain-Chatchat/bot/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/media/will/ssd-h/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/media/will/ssd-h/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
TypeError: 'NoneType' object is not iterable

**Comment by relaxtheo** [comment]
I had the same issue, and finally I found it is caused by no_proxy setting in my case. 
If you also use proxy, you can disable the proxy, or try to unset the no_proxy environment variables.

Command:
unset no_proxy
unset NO_PROXY

Hope this can help you if you still have this problem
