### ISSUE TITLE
mac mini m2安装依赖时，xformers报错

### ISSUE THREAD

**Issue by caopengfeigit** [chatchat-space/Langchain-Chatchat#3196]
**问题描述 / Problem Description**
安装依赖时，在安装xformers时，报错：
clang: error: unsupported option '-fopenmp'
ninja: build stopped: subcommand failed.

**复现问题的步骤 / Steps to Reproduce**
1.执行 pip install -r requirements.txt
2.在安装xformers时出现报错

**预期的结果 / Expected Result**
可以将依赖安装成功

**实际结果 / Actual Result**
clang: error: unsupported option '-fopenmp'
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2108, in _run_ninja_build
          subprocess.run(
        File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/k3/2sqp55v15dg910g1kyzklscc0000gn/T/pip-install-0kr945ra/xformers_52bb6e82498742fdb74696e7745e7e54/setup.py", line 405, in <module>
          setuptools.setup(
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 89, in run
          _build_ext.run(self)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/private/var/folders/k3/2sqp55v15dg910g1kyzklscc0000gn/T/pip-install-0kr945ra/xformers_52bb6e82498742fdb74696e7745e7e54/setup.py", line 361, in build_extensions
          super().build_extensions()
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 870, in build_extensions
          build_ext.build_extensions(self)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 250, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 683, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2124, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects

**环境信息 / Environment Information**
- Langchain-Chatchat 版本号：v0.2.10
- 是否使用 Docker 部署：否
- 使用的模型：无
- 使用的 Embedding 模型：无
- 使用的向量库类型：无
- 操作系统及版本 : macOS Sonoma 14.2.1
- Python 版本: 3.11.8
- 其他相关环境信息 : mac mini m2芯片

**Comment by caopengfeigit** [comment]
并没有起作用

**Comment by caopengfeigit** [comment]
机器人可以的，问题解决了

**Comment by yu1ec** [comment]
机器人给的不能解决所有情况，这是我的解决方法
```shell
# 安装特殊
brew install llvm libomp

# 在项目环境中执行以下
export CC=/opt/homebrew/opt/llvm/bin/clang 
export CXX=/opt/homebrew/opt/llvm/bin/clang++
export LDFLAGS="-L/opt/homebrew/opt/libomp/lib" 
export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
````
这时候再执行就不会报错了。

[参考资料 ](https://stackoverflow.com/questions/60005176/how-to-deal-with-clang-error-unsupported-option-fopenmp-on-travis)

**Comment by caopengfeigit** [comment]
这个方案网上可以搜到，我试过，对我来说是不可行的。
机器人提供的这个方案我试了之后是可以的。

**Comment by yu1ec** [comment]
主要是想多提供点方案，给后来人。我的是M1 PRO

**Comment by caopengfeigit** [comment]
好的，为后来人感谢你的方案 : )

**Comment by Gavinnell** [comment]
xFormers主要针对NVIDIA GPU和CUDA环境进行的优化，mac 上似乎不需要安装这个。xFormers原生并不直接支持Apple的M系列芯片的电脑。我到这一步现在也卡住了

**Comment by Gavinnell** [comment]
> 机器人可以解决的问题

按照机器人给的操作步骤解决问题了吗？

**Comment by BeEdward** [comment]
```bash
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install xformers
```
worked for me, based on the discussion here https://github.com/facebookresearch/xformers/issues/157

**Comment by zhu344742542** [comment]
docker-compose up -d 运行报错，Error response from daemon: unknown or invalid runtime name: nvidia， 我机器是mac m3 pro

**Comment by icbd** [comment]
`> brew install libomp llvm`

export CC=/usr/local/opt/llvm/bin/clang
export CXX=/usr/local/opt/llvm/bin/clang++
