### ISSUE TITLE
[BUG] milvus向量库上传文档报错

### ISSUE THREAD

**Issue by jiyang2024** [chatchat-space/Langchain-Chatchat#3197]
milvus可以进行知识库文档，但是向milvus上传新的文档报错信息如下：

INFO:     127.0.0.1:57820 - "POST /knowledge_base/search_docs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/encoders.py", line 322, in jsonable_encoder
    data = dict(obj)
TypeError: 'numpy.float32' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/encoders.py", line 327, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/routing.py", line 315, in app
    content = await serialize_response(
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/routing.py", line 170, in serialize_response
    return jsonable_encoder(
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/encoders.py", line 301, in jsonable_encoder
    jsonable_encoder(
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/encoders.py", line 235, in jsonable_encoder
    return jsonable_encoder(
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/encoders.py", line 301, in jsonable_encoder
    jsonable_encoder(
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/fastapi/encoders.py", line 330, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'numpy.float32' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2024-03-06 05:35:13,656 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 500 Internal Server Error"
2024-03-06 05:35:13.658 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/env_rag/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/root/jgy/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/root/jgy/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 328, in knowledge_base_page
    data = [
  File "/root/jgy/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
TypeError: string indices must be integers

**Comment by HuntZhaozq** [comment]
请问这个问题解决了吗，我也遇到了同样的问题

**Comment by zcs007** [comment]
@dosu-bot
