### ISSUE TITLE
模型chatglm3-6b server_config开启vllm，报错AttributeError: 'Namespace' object has no attribute 'max_parallel_loading_workers'

### ISSUE THREAD

**Issue by Andy1018** [chatchat-space/Langchain-Chatchat#3200]
和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-03-06 14:01:55 | ERROR | stderr | INFO:     Started server process [215129]
2024-03-06 14:01:55 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-06 14:01:55 | ERROR | stderr | INFO:     Application startup complete.
2024-03-06 14:01:55 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-03-06 14:01:56 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-03-06 14:01:56 | ERROR | stderr | Traceback (most recent call last):
2024-03-06 14:01:56 | ERROR | stderr |   File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-03-06 14:01:56 | ERROR | stderr |     self.run()
2024-03-06 14:01:56 | ERROR | stderr |   File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-03-06 14:01:56 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-03-06 14:01:56 | ERROR | stderr |   File "/home/chatglm3/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-03-06 14:01:56 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-06 14:01:56 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-06 14:01:56 | ERROR | stderr |   File "/home/chatglm3/Langchain-Chatchat/startup.py", line 155, in create_model_worker_app
2024-03-06 14:01:56 | ERROR | stderr |     engine_args = AsyncEngineArgs.from_cli_args(args)
2024-03-06 14:01:56 | ERROR | stderr |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-06 14:01:56 | ERROR | stderr |   File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 212, in from_cli_args
2024-03-06 14:01:56 | ERROR | stderr |     engine_args = cls(**{attr: getattr(args, attr) for attr in attrs})
2024-03-06 14:01:56 | ERROR | stderr |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-06 14:01:56 | ERROR | stderr |   File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 212, in <dictcomp>
2024-03-06 14:01:56 | ERROR | stderr |     engine_args = cls(**{attr: getattr(args, attr) for attr in attrs})
2024-03-06 14:01:56 | ERROR | stderr |                                ^^^^^^^^^^^^^^^^^^^
2024-03-06 14:01:56 | ERROR | stderr | AttributeError: 'Namespace' object has no attribute 'max_parallel_loading_workers'

**Comment by zRzRzRzRzRzRzR** [comment]
请选择支持VLLM的模型，同时严格按照配置安装
