### ISSUE TITLE
使用Qwen-72B-Chat，启动服务，问答的时候发生：API通信遇到错误

### ISSUE THREAD

**Issue by cc8476** [chatchat-space/Langchain-Chatchat#3201]
项目版本是0.2.9
加载本地模型：Qwen-72B-Chat
配置使用多卡A800,最大显存48G

加载正常，问答的时候，会如下报错，麻烦看一下：
`
INFO:     127.0.0.1:54730 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-06 13:28:09,183 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:8003/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54730 - "GET /knowledge_base/list_knowledge_bases HTTP/1.1" 200 OK
2024-03-06 13:28:09,192 - _client.py[line:1013] - INFO: HTTP Request: GET http://127.0.0.1:8003/knowledge_base/list_knowledge_bases "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54730 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
2024-03-06 13:28:09,264 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-03-06 13:28:09,319 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:8003/chat/knowledge_base_chat "HTTP/1.1 200 OK"
2024-03-06 13:28:09,321 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-03-06 13:28:09,321 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /home/cc/bge-large-zh
2024-03-06 13:28:10,483 - embeddings_api.py[line:40] - ERROR: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 587, in receive
    await self.message_event.wait()
  File "/root/anaconda3/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f8c1a51df50

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
  |     raise exc
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
  |     await route.handle(scope, receive, send)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
  |     raise exc
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
  |     await response(scope, receive, send)
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/home/cc/linxi/Langchain-Chatchat-master/server/chat/knowledge_base_chat.py", line 81, in knowledge_base_chat_iterator
    |     docs = await run_in_threadpool(search_docs,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/home/cc/linxi/Langchain-Chatchat-master/langchain/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/cc/linxi/Langchain-Chatchat-master/server/knowledge_base/kb_doc_api.py", line 38, in search_docs
    |     docs = kb.search_docs(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/cc/linxi/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 181, in search_docs
    |     docs = self.do_search(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/cc/linxi/Langchain-Chatchat-master/server/knowledge_base/kb_service/faiss_kb_service.py", line 66, in do_search
    |     embeddings = embed_func.embed_query(query)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/cc/linxi/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 425, in embed_query
    |     query_embed = embeddings[0]
    |                   ~~~~~~~~~~^^^
    | TypeError: 'NoneType' object is not subscriptable
    +------------------------------------
2024-03-06 13:28:10,493 - utils.py[line:196] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
^C  Stopping...
2024-03-06 13:28:24,522 - startup.py[line:856] - WARNING: Sending SIGKILL to {'qianfan-api': <Process name='api_worker - qianfan-api (1617546)' pid=1617546 parent=1617054 started daemon>}
2024-03-06 13:28:24,524 - startup.py[line:856] - WARNING: Sending SIGKILL to {'Qwen-72B-Chat': <Process name='model_worker - Qwen-72B-Chat (1617545)' pid=1617545 parent=1617054 started daemon>}
2024-03-06 13:28:24,526 - startup.py[line:856] - WARNING: Sending SIGKILL to <Process name='controller (1617343)' pid=1617343 parent=1617054 started daemon>
2024-03-06 13:28:24,529 - startup.py[line:856] - WARNING: Sending SIGKILL to <Process name='openai_api (1617544)' pid=1617544 parent=1617054 started daemon>
2024-03-06 13:28:24,530 - startup.py[line:856] - WARNING: Sending SIGKILL to <Process name='API Server (1618225)' pid=1618225 parent=1617054 started daemon>
2024-03-06 13:28:24,532 - startup.py[line:856] - WARNING: Sending SIGKILL to <Process name='WEBUI Server (1618490)' pid=1618490 parent=1617054 started daemon>
2024-03-06 13:28:24,533 - startup.py[line:867] - INFO: Process status: {'qianfan-api': <Process name='api_worker - qianfan-api (1617546)' pid=1617546 parent=1617054 started daemon>}
2024-03-06 13:28:24,533 - startup.py[line:867] - INFO: Process status: {'Qwen-72B-Chat': <Process name='model_worker - Qwen-72B-Chat (1617545)' pid=1617545 parent=1617054 started daemon>}
2024-03-06 13:28:24,534 - startup.py[line:867] - INFO: Process status: <Process name='controller (1617343)' pid=1617343 parent=1617054 started daemon>
2024-03-06 13:28:24,534 - startup.py[line:867] - INFO: Process status: <Process name='openai_api (1617544)' pid=1617544 parent=1617054 started daemon>
2024-03-06 13:28:24,534 - startup.py[line:867] - INFO: Process status: <Process name='API Server (1618225)' pid=1618225 parent=1617054 started daemon>
2024-03-06 13:28:24,535 - startup.py[line:867] - INFO: Process status: <Process name='WEBUI Server (1618490)' pid=1618490 parent=1617054 started daemon>

`

**Comment by zRzRzRzRzRzRzR** [comment]
你这种适合用vllm，fschat是单卡的，你多少张卡都是单卡读入
