### ISSUE TITLE
执行python init_database.py --recreate-vs 命令报错，ERROR: init() got an unexpected keyword argument '_name_or_path' AttributeError: 'NoneType' object has no attribute 'conjugate'

### ISSUE THREAD

**Issue by zcs007** [chatchat-space/Langchain-Chatchat#3208]
2024-03-06 17:28:41,134 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: embeddings
2024-03-06 17:28:41,469 - embeddings_api.py[line:40] - ERROR: __init__() got an unexpected keyword argument '_name_or_path'
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hduser/langchainchatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/hduser/langchainchatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/home/hduser/langchainchatchat/server/knowledge_base/migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "/home/hduser/langchainchatchat/server/knowledge_base/kb_service/base.py", line 130, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
  File "/home/hduser/langchainchatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 81, in do_add_doc
    ids = self.milvus.add_documents(docs)
  File "/home/hduser/miniconda3/envs/chatglm3/lib/python3.9/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/home/hduser/miniconda3/envs/chatglm3/lib/python3.9/site-packages/langchain_community/vectorstores/milvus.py", line 531, in add_texts
    embeddings = self.embedding_func.embed_documents(texts)
  File "/home/hduser/langchainchatchat/server/knowledge_base/kb_service/base.py", line 420, in embed_documents
    return normalize(embeddings).tolist()
  File "/home/hduser/langchainchatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "/home/hduser/miniconda3/envs/chatglm3/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 2541, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

 执行python init_database.py --recreate-vs 命令报错

**复现问题的步骤 / Steps to Reproduce**
python init_database.py --recreate-vs 

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus
- 操作系统及版本 / Operating system and version: Linux algo 5.4.0-171-generic #189-Ubuntu SMP Fri Jan 5 14:23:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Python 版本 / Python version:3.9.18
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zcs007** [comment]
@dosu-bot

**Comment by chunshengding** [comment]
同样的问题
