### ISSUE TITLE
浏览器访问http://0.0.0.0:8501，立马报错ModuleNotFoundError: No module named 'httpx_sse'

### ISSUE THREAD

**Issue by zcs007** [chatchat-space/Langchain-Chatchat#3210]
**问题描述 / ==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2024-03-06 20:13:31.898 Uncaught app exception
Traceback (most recent call last):
  File "/home/hduser/.local/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/hduser/Langchat/Langchain-Chatchat/webui.py", line 2, in <module>
    from webui_pages.utils import *
  File "/home/hduser/Langchat/Langchain-Chatchat/webui_pages/utils.py", line 31, in <module>
    set_httpx_config()
  File "/home/hduser/Langchat/Langchain-Chatchat/server/utils.py", line 497, in set_httpx_config
    fschat_model_worker_address(),
  File "/home/hduser/Langchat/Langchain-Chatchat/server/utils.py", line 406, in fschat_model_worker_address
    if model := get_model_worker_config(model_name):
  File "/home/hduser/Langchat/Langchain-Chatchat/server/utils.py", line 361, in get_model_worker_config
    from server import model_workers
  File "/home/hduser/Langchat/Langchain-Chatchat/server/model_workers/__init__.py", line 2, in <module>
    from .zhipu import ChatGLMWorker
  File "/home/hduser/Langchat/Langchain-Chatchat/server/model_workers/zhipu.py", line 5, in <module>
    from httpx_sse import EventSource
ModuleNotFoundError: No module named 'httpx_sse'

用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
执行python3 startup.py -a命令运行起来，用浏览器访问就会报找不到httpx_sse，实际上httpx_sse已经安装 版本号也是对的
**复现问题的步骤 / Steps to Reproduce**
1. 执行 '执行python3 startup.py -a
2. 点击 用浏览器访问

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
网页正常访问

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
网页无法访问

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus
- 操作系统及版本 / Operating system and version:Linux algo 5.4.0-171-generic #189-Ubuntu SMP Fri Jan 5 14:23:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Python 版本 / Python version:3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
httpx_sse 装一下试试 pip装
