### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by fireflywwj** [chatchat-space/Langchain-Chatchat#3219]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda\envs\LangChainChatChat\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "E:\01_Code\GitCode\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "E:\01_Code\GitCode\Langchain-Chatchat\webui_pages\dialogue\dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by LazyCatLee** [comment]
/server/utils.py 中 get_httpx_client() 方法中or host in os.environ.get("no_proxy", "").split(",") 代码中如下改能够解决该问题，我本地因为改过网络参数以及更新过依赖包出现该问题


    for host in os.environ.get("no_proxy", "").split(","):
        # print(host)
        #TODO:  Local BUG 
        if (host:= host.strip() )!='::1':
            default_proxies.update({'all://' +host: None})
