### ISSUE TITLE
成功打开页面后，无法进行问答

### ISSUE THREAD

**Issue by amberccR** [chatchat-space/Langchain-Chatchat#3241]
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/root/autodl-tmp/model/THUDM/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2024-03-09 15:19:20,172 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51406 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-09 15:19:20,177 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-09 15:19:20,295 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51406 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-09 15:19:20,298 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51406 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-09 15:19:20,309 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-09 15:19:27,676 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:50886 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-09 15:19:27,680 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-09 15:19:27,696 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:50886 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-09 15:19:27,702 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:50886 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-09 15:19:27,717 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:50886 - "POST /chat/chat HTTP/1.1" 200 OK
/root/miniconda3/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-03-09 15:19:27,800 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-03-09 15:19:27 | INFO | stdout | INFO:     127.0.0.1:37634 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-03-09 15:19:27,854 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-03-09 15:19:27 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 261, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 257, in wrap
    await func()
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 234, in listen_for_disconnect
    message = await receive()
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 580, in receive
    await self.message_event.wait()
  File "/root/miniconda3/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f292d3ab520

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 254, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 257, in wrap
    |     await func()
    |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 246, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    |     yield await anyio.to_thread.run_sync(_next, as_iterator)
    |   File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    |     return await future
    |   File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/concurrency.py", line 52, in _next
    |     return next(iterator)
    |   File "/root/miniconda3/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 114, in generate_stream_gate
    |     for output in self.generate_stream_func(
    |   File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    |     response = gen.send(None)
    |   File "/root/miniconda3/lib/python3.10/site-packages/fastchat/model/model_chatglm.py", line 88, in generate_stream_chatglm
    |     inputs = tokenizer.build_chat_input(
    | AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_chat_input'
    +------------------------------------
2024-03-09 15:19:27 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-03-09 15:19:27 | ERROR | stderr | Traceback (most recent call last):
2024-03-09 15:19:27 | ERROR | stderr |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 261, in __call__
2024-03-09 15:19:27 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-03-09 15:19:27 | ERROR | stderr |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 257, in wrap
2024-03-09 15:19:27 | ERROR | stderr |     await func()
2024-03-09 15:19:27 | ERROR | stderr |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 234, in listen_for_disconnect
2024-03-09 15:19:27 | ERROR | stderr |     message = await receive()
2024-03-09 15:19:27 | ERROR | stderr |   File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 580, in receive
2024-03-09 15:19:27 | ERROR | stderr |     await self.message_event.wait()
2024-03-09 15:19:27 | ERROR | stderr |   File "/root/miniconda3/lib/python3.10/asyncio/locks.py", line 214, in wait
2024-03-09 15:19:27 | ERROR | stderr |     await fut
2024-03-09 15:19:27 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f450144dc90
2024-03-09 15:19:27 | ERROR | stderr | 
2024-03-09 15:19:27 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-03-09 15:19:27 | ERROR | stderr | 
2024-03-09 15:19:27 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2024-03-09 15:19:27 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 119, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     raise exc
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-03-09 15:19:27 | ERROR | stderr |   |     raise exc
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-03-09 15:19:27 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
2024-03-09 15:19:27 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-03-09 15:19:27 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-03-09 15:19:27 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-03-09 15:19:27 | ERROR | stderr |   |     raise exc
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-03-09 15:19:27 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
2024-03-09 15:19:27 | ERROR | stderr |   |     await response(scope, receive, send)
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 254, in __call__
2024-03-09 15:19:27 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-03-09 15:19:27 | ERROR | stderr |   |   File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
2024-03-09 15:19:27 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-03-09 15:19:27 | ERROR | stderr |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-03-09 15:19:27 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-03-09 15:19:27 | ERROR | stderr |     | Traceback (most recent call last):
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
2024-03-09 15:19:27 | ERROR | stderr |     |     yield
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 252, in __aiter__
2024-03-09 15:19:27 | ERROR | stderr |     |     async for part in self._httpcore_stream:
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
2024-03-09 15:19:27 | ERROR | stderr |     |     raise exc from None
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
2024-03-09 15:19:27 | ERROR | stderr |     |     async for part in self._stream:
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
2024-03-09 15:19:27 | ERROR | stderr |     |     raise exc
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
2024-03-09 15:19:27 | ERROR | stderr |     |     async for chunk in self._connection._receive_response_body(**kwargs):
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
2024-03-09 15:19:27 | ERROR | stderr |     |     event = await self._receive_event(timeout=timeout)
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/http11.py", line 220, in _receive_event
2024-03-09 15:19:27 | ERROR | stderr |     |     with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/contextlib.py", line 153, in __exit__
2024-03-09 15:19:27 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-03-09 15:19:27 | ERROR | stderr |     |     raise to_exc(exc) from exc
2024-03-09 15:19:27 | ERROR | stderr |     | httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-03-09 15:19:27 | ERROR | stderr |     |
2024-03-09 15:19:27 | ERROR | stderr |     | The above exception was the direct cause of the following exception:
2024-03-09 15:19:27 | ERROR | stderr |     |
2024-03-09 15:19:27 | ERROR | stderr |     | Traceback (most recent call last):
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 257, in wrap
2024-03-09 15:19:27 | ERROR | stderr |     |     await func()
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/starlette/responses.py", line 246, in stream_response
2024-03-09 15:19:27 | ERROR | stderr |     |     async for chunk in self.body_iterator:
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 473, in chat_completion_stream_generator
2024-03-09 15:19:27 | ERROR | stderr |     |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/fastchat/serve/openai_api_server.py", line 658, in generate_completion_stream
2024-03-09 15:19:27 | ERROR | stderr |     |     async for raw_chunk in response.aiter_raw():
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpx/_models.py", line 991, in aiter_raw
2024-03-09 15:19:27 | ERROR | stderr |     |     async for raw_stream_bytes in self.stream:
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpx/_client.py", line 147, in __aiter__
2024-03-09 15:19:27 | ERROR | stderr |     |     async for chunk in self._stream:
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 251, in __aiter__
2024-03-09 15:19:27 | ERROR | stderr |     |     with map_httpcore_exceptions():
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/contextlib.py", line 153, in __exit__
2024-03-09 15:19:27 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-03-09 15:19:27 | ERROR | stderr |     |   File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
2024-03-09 15:19:27 | ERROR | stderr |     |     raise mapped_exc(message) from exc
2024-03-09 15:19:27 | ERROR | stderr |     | httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-03-09 15:19:27 | ERROR | stderr |     +------------------------------------
2024-03-09 15:19:27,887 - utils.py[line:38] - ERROR: peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 252, in __aiter__
    async for part in self._httpcore_stream:
  File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
    raise exc from None
  File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
    async for part in self._stream:
  File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_async/http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/root/miniconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/chat/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/root/miniconda3/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/root/miniconda3/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/root/miniconda3/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/root/miniconda3/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/root/miniconda3/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/root/miniconda3/lib/python3.10/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/root/miniconda3/lib/python3.10/site-packages/openai/_streaming.py", line 129, in __stream__
    async for sse in iterator:
  File "/root/miniconda3/lib/python3.10/site-packages/openai/_streaming.py", line 120, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/root/miniconda3/lib/python3.10/site-packages/openai/_streaming.py", line 231, in aiter
    async for line in iterator:
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_models.py", line 967, in aiter_lines
    async for text in self.aiter_text():
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_models.py", line 954, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_models.py", line 933, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_models.py", line 991, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_client.py", line 147, in __aiter__
    async for chunk in self._stream:
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 251, in __aiter__
    with map_httpcore_exceptions():
  File "/root/miniconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-03-09 15:19:27,890 - utils.py[line:40] - ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)

成功启动weibu之后，进行提问出现以上问题，请问是哪里出错了呢？该如何解决啊？

**Comment by litongyun233** [comment]
同样的问题

**Comment by shili1902** [comment]
同样的问题
