### ISSUE TITLE
webui启动成功，但有报错

### ISSUE THREAD

**Issue by wjh-fire** [chatchat-space/Langchain-Chatchat#325]
**问题描述 / Problem Description**
webui启动成功，可以正常打开页面，但是日志有报错，所有日志如下：
(virtual_env) E:\langchain-ChatGLM>python webui.py
INFO  2023-05-12 09:16:17,576-1d:
loading model config
llm device: cpu
embedding device: cpu
dir: E:\langchain-ChatGLM
flagging username: a654353fd8d14a8cbf74954f5701ee4a

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels_parallel.c -shared -o C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels_parallel.so
d:/mingw/install/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels.c -shared -o C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels.so
Load default cpu kernel failed:
Traceback (most recent call last):
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization.py", line 178, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "D:\python3.8\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "D:\python3.8\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

Failed to load kernel.
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
INFO  2023-05-12 09:16:31,102-1d: Load pretrained SentenceTransformer: E:\text2vec-large-chinese
WARNING 2023-05-12 09:16:31,102-1d: No sentence-transformers model found with name E:\text2vec-large-chinese. Creating a new one with MEAN pooling.
INFO  2023-05-12 09:16:35,365-1d: 模型已成功加载，可以开始对话，或从右侧选择模式后开始对话
Running on local URL:  http://0.0.0.0:7860

**复现问题的步骤 / Steps to Reproduce**
执行python webui.py

**预期的结果 / Expected Result**
正常启动无报错

**实际结果 / Actual Result**
可以正常启动但日志有报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：最新版
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B-int8
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：text2vec-large-chinese
- 操作系统及版本 / Operating system and version: win10 专业版 19045.2965
- Python 版本 / Python version: 3.8.10
- 其他相关环境信息 / Other relevant environment information:  使用`py -3.8 -m venv myenv`命令创建虚拟环境来运行

**附加信息 / Additional Information**
无

**Comment by wjh-fire** [comment]
并且启动起来之后聊天框问个`你好`都报错，报错信息只显示空指针，具体报错信息如下：

To create a public link, set `share=True` in `launch()`.
INFO  2023-05-12 09:22:57,450-1d: Loading faiss with AVX2 support.
INFO  2023-05-12 09:22:57,451-1d: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
INFO  2023-05-12 09:22:57,451-1d: Loading faiss.
INFO  2023-05-12 09:22:57,546-1d: Successfully loaded faiss.
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.54it/s]
Traceback (most recent call last):
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\gradio\blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "webui.py", line 34, in get_answer
    for resp, history in local_doc_qa.get_knowledge_based_answer(
  File "E:\langchain-ChatGLM\chains\local_doc_qa.py", line 223, in get_knowledge_based_answer
    for result, history in self.llm._call(prompt=prompt,
  File "E:\langchain-ChatGLM\models\chatglm_llm.py", line 65, in _call
    for inum, (stream_resp, _) in enumerate(self.model.stream_chat(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\modeling_chatglm.py", line 1311, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\modeling_chatglm.py", line 1388, in stream_generate
    outputs = self(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\modeling_chatglm.py", line 445, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization.py", line 388, in forward
    output = W8A16LinearCPU.apply(input, self.weight, self.weight_scale, self.weight_bit_width,
  File "E:\langchain-ChatGLM\virtual_env\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization.py", line 80, in forward
    weight = extract_weight_to_float(quant_w, scale_w, weight_bit_width, quantization_cache=quantization_cache)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization.py", line 316, in extract_weight_to_float
    func(
TypeError: 'NoneType' object is not callable

**Comment by wangbochao** [comment]
我也报同样的错误，好尴尬，还没解决

**Comment by wjh-fire** [comment]
本座已收到

**Comment by wangbochao** [comment]
您已经解决该问题了吗？

**Comment by wjh-fire** [comment]
> 我也报同样的错误，好尴尬，还没解决

不好意思，忘记回复了。我在服务器上面装了个pycharm来跑就成功了。。

**Comment by luocj** [comment]
认真的吗

**Comment by luocj** [comment]
> > 我也报同样的错误，好尴尬，还没解决
> 
> 不好意思，忘记回复了。我在服务器上面装了个pycharm来跑就成功了。。

认真的吗

**Comment by wjh-fire** [comment]
本座已收到
