### ISSUE TITLE
[问题] 启动报错，requests.exceptions.ProxyError

### ISSUE THREAD

**Issue by randian666** [chatchat-space/Langchain-Chatchat#3258]
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.14.188-x86_64-with-glibc2.27.
python版本：3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/flightdap/MODEL_ROOT_PATH/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-03-11 14:13:49,990 - startup.py[line:655] - INFO: 正在启动服务：
2024-03-11 14:13:49,990 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /home/flightdap/Langchain-Chatchat/logs
no_proxy ['http://127.0.0.1', 'http://localhost']
/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
no_proxy ['http://127.0.0.1', 'http://localhost']
2024-03-11 14:13:55 | ERROR | stderr | INFO:     Started server process [53969]
2024-03-11 14:13:55 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-11 14:13:55 | ERROR | stderr | INFO:     Application startup complete.
2024-03-11 14:13:55 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
no_proxy ['http://127.0.0.1', 'http://localhost']
kwargs {'device': 'cuda', 'infer_turbo': False, 'model_path': '/home/flightdap/MODEL_ROOT_PATH/chatglm3-6b', 'model_path_exists': True, 'model_names': ['chatglm3-6b'], 'controller_address': 'http://127.0.0.1:20001', 'worker_address': 'http://127.0.0.1:20002'}
2024-03-11 14:13:55 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 0debd57a ...
Loading checkpoint shards:   0%|                                                                  | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████▎                                                 | 1/7 [00:00<00:02,  2.77it/s]
Loading checkpoint shards:  29%|████████████████▌                                         | 2/7 [00:00<00:01,  2.66it/s]
Loading checkpoint shards:  43%|████████████████████████▊                                 | 3/7 [00:01<00:01,  2.59it/s]
Loading checkpoint shards:  57%|█████████████████████████████████▏                        | 4/7 [00:01<00:01,  2.61it/s]
Loading checkpoint shards:  71%|█████████████████████████████████████████▍                | 5/7 [00:01<00:00,  2.56it/s]
Loading checkpoint shards:  86%|█████████████████████████████████████████████████▋        | 6/7 [00:02<00:00,  2.54it/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.03it/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.77it/s]
2024-03-11 14:13:58 | ERROR | stderr | 
2024-03-11 14:14:01 | INFO | model_worker | Register to controller
2024-03-11 14:14:03 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-03-11 14:14:03 | ERROR | stderr | Traceback (most recent call last):
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
2024-03-11 14:14:03 | ERROR | stderr |     response = self._make_request(
2024-03-11 14:14:03 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/urllib3/connectionpool.py", line 537, in _make_request
2024-03-11 14:14:03 | ERROR | stderr |     response = conn.getresponse()
2024-03-11 14:14:03 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/urllib3/connection.py", line 466, in getresponse
2024-03-11 14:14:03 | ERROR | stderr |     httplib_response = super().getresponse()
2024-03-11 14:14:03 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/http/client.py", line 1390, in getresponse
2024-03-11 14:14:03 | ERROR | stderr |     response.begin()
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/http/client.py", line 325, in begin
2024-03-11 14:14:03 | ERROR | stderr |     version, status, reason = self._read_status()
2024-03-11 14:14:03 | ERROR | stderr |                               ^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/http/client.py", line 294, in _read_status
2024-03-11 14:14:03 | ERROR | stderr |     raise RemoteDisconnected("Remote end closed connection without"
2024-03-11 14:14:03 | ERROR | stderr | http.client.RemoteDisconnected: Remote end closed connection without response
2024-03-11 14:14:03 | ERROR | stderr | 
2024-03-11 14:14:03 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-03-11 14:14:03 | ERROR | stderr | 
2024-03-11 14:14:03 | ERROR | stderr | urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))
2024-03-11 14:14:03 | ERROR | stderr | 
2024-03-11 14:14:03 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-03-11 14:14:03 | ERROR | stderr | 
2024-03-11 14:14:03 | ERROR | stderr | Traceback (most recent call last):
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
2024-03-11 14:14:03 | ERROR | stderr |     resp = conn.urlopen(
2024-03-11 14:14:03 | ERROR | stderr |            ^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
2024-03-11 14:14:03 | ERROR | stderr |     retries = retries.increment(
2024-03-11 14:14:03 | ERROR | stderr |               ^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
2024-03-11 14:14:03 | ERROR | stderr |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-03-11 14:14:03 | ERROR | stderr |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.25.239.45', port=33080): Max retries exceeded with url: http://127.0.0.1:20001/register_worker (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-03-11 14:14:03 | ERROR | stderr | 
2024-03-11 14:14:03 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-03-11 14:14:03 | ERROR | stderr | 
2024-03-11 14:14:03 | ERROR | stderr | Traceback (most recent call last):
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-03-11 14:14:03 | ERROR | stderr |     self.run()
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-03-11 14:14:03 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-03-11 14:14:03 | ERROR | stderr |   File "/home/flightdap/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-03-11 14:14:03 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-11 14:14:03 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/home/flightdap/Langchain-Chatchat/startup.py", line 216, in create_model_worker_app
2024-03-11 14:14:03 | ERROR | stderr |     worker = ModelWorker(
2024-03-11 14:14:03 | ERROR | stderr |              ^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 102, in __init__
2024-03-11 14:14:03 | ERROR | stderr |     self.init_heart_beat()
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/fastchat/serve/base_model_worker.py", line 79, in init_heart_beat
2024-03-11 14:14:03 | ERROR | stderr |     self.register_to_controller()
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/fastchat/serve/base_model_worker.py", line 96, in register_to_controller
2024-03-11 14:14:03 | ERROR | stderr |     r = requests.post(url, json=data)
2024-03-11 14:14:03 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/requests/api.py", line 115, in post
2024-03-11 14:14:03 | ERROR | stderr |     return request("post", url, data=data, json=json, **kwargs)
2024-03-11 14:14:03 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/requests/api.py", line 59, in request
2024-03-11 14:14:03 | ERROR | stderr |     return session.request(method=method, url=url, **kwargs)
2024-03-11 14:14:03 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-03-11 14:14:03 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-03-11 14:14:03 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-03-11 14:14:03 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-03-11 14:14:03 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-11 14:14:03 | ERROR | stderr |   File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/requests/adapters.py", line 513, in send
2024-03-11 14:14:03 | ERROR | stderr |     raise ProxyError(e, request=request)
2024-03-11 14:14:03 | ERROR | stderr | requests.exceptions.ProxyError: HTTPConnectionPool(host='172.25.239.45', port=33080): Max retries exceeded with url: http://127.0.0.1:20001/register_worker (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

**Comment by zRzRzRzRzRzRzR** [comment]
这是没有请求到数据库的感觉
