### ISSUE TITLE
无法使用第三方接口的 gpt-3.5？

### ISSUE THREAD

**Issue by liuhuanshuo** [chatchat-space/Langchain-Chatchat#3263]
**问题描述 / Problem Description**

因为自己的 openai 账号被 ban，尝试使用第三方服务商提供的 openai 接口和 key，但是无法调用

设备是 mac，用的clash端口是 7890，测试 openai 官网是可以访问使用的（不论是否开全局）

我想似乎应该是我哪里没有设置对，求指导

**复现问题的步骤 / Steps to Reproduce**

修改`model_config.py` 如下部分，也就是第三方提供的接口地址（在其他 gpt 项目（例如ChatGPT-Next-Web等）中可以调用）
```
LLM_MODELS = ["openai-api"]


ONLINE_LLM_MODEL = {
    "openai-api": {
        "model_name": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai-proxy.org",
        "api_key": "sk-",
        "openai_proxy": "http://127.0.0.1:7890",
    },
··· ···
```

启动后，对话空白，并且立刻报错 404
```
2024-03-11 17:00:01,377 - _client.py[line:1758] - INFO: HTTP Request: POST https://api.closeai-proxy.xyz/chat/completions "HTTP/1.1 404 Not Found"
2024-03-11 17:00:01,380 - utils.py[line:38] - ERROR: 404 page not found
Traceback (most recent call last):
  File "/Users/liuhuanshuo/Desktop/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 105, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1300, in create
    return await self._post(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1703, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1406, in request
    return await self._request(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1497, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found
2024-03-11 17:00:01,382 - utils.py[line:40] - ERROR: NotFoundError: Caught exception: 404 page not found
```

如果使用默认的 openai 接口地址，也就是如下修改

```
LLM_MODELS = ["openai-api"]


ONLINE_LLM_MODEL = {
    "openai-api": {
        "model_name": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "sk-",
        "openai_proxy": "http://127.0.0.1:7890",
    },
··· ···
```

会一直提示正在思考，出现如下报错

```
Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(

```

过一会打印了完整的报错
```
2024-03-11 17:12:33,005 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-03-11 17:13:48,102 - _base_client.py[line:1524] - INFO: Retrying request to /chat/completions in 0.876169 seconds
2024-03-11 17:15:04,011 - _base_client.py[line:1524] - INFO: Retrying request to /chat/completions in 1.995247 seconds
2024-03-11 17:16:21,073 - utils.py[line:38] - ERROR: Connection error.
Traceback (most recent call last):
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1435, in _request
    response = await self._client.send(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpx/_transports/default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/liuhuanshuo/Desktop/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 105, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1300, in create
    return await self._post(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1703, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1406, in request
    return await self._request(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1459, in _request
    return await self._retry_request(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1528, in _retry_request
    return await self._request(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1459, in _request
    return await self._retry_request(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1528, in _retry_request
    return await self._request(
  File "/Users/liuhuanshuo/miniforge3/envs/llm-chat/lib/python3.10/site-packages/openai/_base_client.py", line 1469, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
2024-03-11 17:16:21,090 - utils.py[line:40] - ERROR: APIConnectionError: Caught exception: Connection error.
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：latest

**Comment by litterGuy** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2154539/e31f4e12-5a2e-45dd-885d-1d2798e9bfc4)
这个地址填错了吧
