### ISSUE TITLE
[FEATURE] 访问web界面控制台报错

### ISSUE THREAD

**Issue by randian666** [chatchat-space/Langchain-Chatchat#3265]
执行命令后streamlit run webui.py访问web界面控制台报错：

2024-03-11 20:02:51,533 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('172.25.239.45:33080')
2024-03-11 20:02:51,533 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('172.25.239.45:33080')
2024-03-11 20:02:51,533 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('172.25.239.45:33080')
2024-03-11 20:02:51,635 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('172.25.239.45:33080')
2024-03-11 20:02:51,636 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('172.25.239.45:33080')
2024-03-11 20:02:51,636 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('172.25.239.45:33080')
2024-03-11 20:02:51.636 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/envs/langchain-chatchat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/flightdap/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/flightdap/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by zRzRzRzRzRzRzR** [comment]
模型没有配置或者正确运行导致的无法识别到运行的模型报错，检查模型是否正常运行

**Comment by litongyun233** [comment]
你好，请问应该如何检查呢？
