### ISSUE TITLE
对数据库 提问有问题，找到数据但不回答或数据库没有的什么都不回答

### ISSUE THREAD

**Issue by cstkn** [chatchat-space/Langchain-Chatchat#3288]
2024-03-12 18:34:25,072 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "D:\wujiaping\chat\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain_community\chat_models\openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "D:\wujiaping\chat\Langchain-Chatchat\.venv\Lib\site-packages\langchain_community\chat_models\openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^

**Comment by zRzRzRzRzRzRzR** [comment]
这个是大模型端有问题吧，你估计LLM对话也是不通的，检查大模型是否正常

**Comment by jinyilun718** [comment]
我LLM对话是通的，但是还是遇到了这个问题是为什么呢
