### ISSUE TITLE
[BUG] 简洁阐述问题 / 使用命令 python startup.py -a启动时出错

### ISSUE THREAD

**Issue by lzh2016zzz** [chatchat-space/Langchain-Chatchat#3289]
操作系统：macOS-14.3.1-arm64-arm-64bit.
python版本：3.11.5 (main, Oct  4 2023, 10:56:25) [Clang 15.0.0 (clang-1500.0.40.1)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ mps
{'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ mps

报错信息 : 

Process API Server:
Traceback (most recent call last):
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mac/code/Langchain-Chatchat/startup.py", line 438, in run_api_server
    app = create_app(run_mode=run_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/code/Langchain-Chatchat/server/api.py", line 51, in create_app
    mount_app_routes(app, run_mode=run_mode)
  File "/Users/mac/code/Langchain-Chatchat/server/api.py", line 77, in mount_app_routes
    mount_knowledge_routes(app)
  File "/Users/mac/code/Langchain-Chatchat/server/api.py", line 140, in mount_knowledge_routes
    from server.chat.knowledge_base_chat import knowledge_base_chat
  File "/Users/mac/code/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 24, in <module>
    from server.reranker.reranker import LangchainReranker
  File "/Users/mac/code/Langchain-Chatchat/server/reranker/reranker.py", line 11, in <module>
    from llama_index.bridge.pydantic import Field, PrivateAttr
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/__init__.py", line 13, in <module>
    from llama_index.callbacks.global_handlers import set_global_handler
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/callbacks/__init__.py", line 7, in <module>
    from .token_counting import TokenCountingHandler
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/callbacks/token_counting.py", line 6, in <module>
    from llama_index.utilities.token_counting import TokenCounter
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/utilities/token_counting.py", line 6, in <module>
    from llama_index.llms import ChatMessage, MessageRole
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/llms/__init__.py", line 1, in <module>
    from llama_index.core.llms.types import (
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 31, in <module>
    from llama_index.core.ingestion.api_utils import get_client
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/ingestion/api_utils.py", line 20, in <module>
    from llama_index.core.ingestion.data_sources import (
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/ingestion/data_sources.py", line 340, in <module>
    ConfigurableDataSources = build_configurable_data_source_enum()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/ingestion/data_sources.py", line 117, in build_configurable_data_source_enum
    DataSource(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)

**Comment by lzh2016zzz** [comment]
> 你好，@lzh2016zzz！很高兴再次看到你的反馈。
> 
> 根据您提供的错误信息，问题出在 `llama_index.core.ingestion.data_sources.py` 文件的 `build_configurable_data_source_enum` 函数中。这个函数试图创建一个 `DataSource` 对象，但在验证过程中出现了错误。错误信息显示，`component_type` 需要是 `BaseComponent` 的子类，但实际上并不是。
> 
> 这可能是由于 `llama_index` 库的版本问题，或者是 `Langchain-Chatchat` 项目中某些部分与 `llama_index` 库的使用方式不兼容。以下是一些可能的解决方案：
> 
> 1. **检查 `llama_index` 库的版本**：确保您使用的 `llama_index` 库的版本与 `Langchain-Chatchat` 项目兼容。您可以在项目的 `requirements.txt` 文件或者 `Pipfile` 文件中查看推荐的 `llama_index` 版本。
> 2. **更新 `Langchain-Chatchat` 项目**：项目的最新版本可能已经解决了这个问题。您可以尝试更新到最新版本，看看问题是否得到解决。
> 3. **检查 Python 版本**：`Langchain-Chatchat` 项目可能不支持 Python 3.11.5。您可以尝试使用 Python 3.10 或者 3.9，看看问题是否得到解决。
> 4. **联系开发者**：如果以上方法都不能解决问题，您可以尝试联系 `Langchain-Chatchat` 或者 `llama_index` 的开发者，看看他们是否有解决这个问题的建议。
> 
> 希望以上建议能对您有所帮助。如果问题仍然存在，或者有其他问题，欢迎继续提问。
> 
> ## Sources
> * [[BUG] Langchain-chatchat 一键启动项目 python startup.py -a 报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2963)
> * [startup.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/startup.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

降级llama-index以后问题解决了
```
pip uninstall llama-index
pip install llama-index==0.9.35
```
