### ISSUE TITLE
server_config.py 开启"infer_turbo": 'vllm'模式加载chatglm3-6b启动报错

### ISSUE THREAD

**Issue by Andy1018** [chatchat-space/Langchain-Chatchat#3293]
2024-03-13 09:51:31,055 - startup.py[line:655] - INFO: 正在启动服务：
2024-03-13 09:51:31,055 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /home/chatglm3/Langchain-Chatchat/logs

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1160.108.1.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'gpus': '0,1',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'limit_worker_concurrency': 20,
 'max_gpu_memory': '22GiB',
 'model_path': '/home/chatglm3/Langchain-Chatchat/chatglm3-6b',
 'model_path_exists': True,
 'num_gpus': 2,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
==============================Langchain-Chatchat Configuration==============================

/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-03-13 09:51:36 | ERROR | stderr | INFO:     Started server process [810671]
2024-03-13 09:51:36 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-13 09:51:36 | ERROR | stderr | INFO:     Application startup complete.
2024-03-13 09:51:36 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
Process model_worker - chatglm3-6b:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chatglm3/Langchain-Chatchat/startup.py", line 389, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chatglm3/Langchain-Chatchat/startup.py", line 109, in create_model_worker_app
    import fastchat.serve.vllm_worker
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/fastchat/serve/vllm_worker.py", line 15, in <module>
    from vllm import AsyncLLMEngine
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 6, in <module>
    from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/config.py", line 9, in <module>
    from vllm.utils import get_cpu_memory, is_hip
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/utils.py", line 11, in <module>
    from vllm._C import cuda_utils
ImportError: /home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/_C.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE

**Comment by Andy1018** [comment]
此问题为解决，请提供解决方案

**Comment by Andy1018** [comment]
@dosu-bot 此解决方案不对

**Comment by Andy1018** [comment]
@dosu-bot 问题就是server_config.py 开启"infer_turbo": 'vllm'设置，加载的模型是chatglm3-6b， startup.py -a启动报错，ImportError: /home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/_C.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE以下是打印的详细日志


24-03-13 09:51:31,055 - startup.py[line:655] - INFO: 正在启动服务：
2024-03-13 09:51:31,055 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /home/chatglm3/Langchain-Chatchat/logs

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1160.108.1.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
'gpus': '0,1',
'host': '0.0.0.0',
'infer_turbo': 'vllm',
'limit_worker_concurrency': 20,
'max_gpu_memory': '22GiB',
'model_path': '/home/chatglm3/Langchain-Chatchat/chatglm3-6b',
'model_path_exists': True,
'num_gpus': 2,
'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
==============================Langchain-Chatchat Configuration==============================

/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
warn_deprecated(
2024-03-13 09:51:36 | ERROR | stderr | INFO: Started server process [810671]
2024-03-13 09:51:36 | ERROR | stderr | INFO: Waiting for application startup.
2024-03-13 09:51:36 | ERROR | stderr | INFO: Application startup complete.
2024-03-13 09:51:36 | ERROR | stderr | INFO: Uvicorn running on http://0.0.0.0:20000/ (Press CTRL+C to quit)
Process model_worker - chatglm3-6b:
Traceback (most recent call last):
File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/home/chatglm3/Langchain-Chatchat/startup.py", line 389, in run_model_worker
app = create_model_worker_app(log_level=log_level, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/chatglm3/Langchain-Chatchat/startup.py", line 109, in create_model_worker_app
import fastchat.serve.vllm_worker
File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/fastchat/serve/vllm_worker.py", line 15, in
from vllm import AsyncLLMEngine
File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/init.py", line 3, in
from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 6, in
from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/config.py", line 9, in
from vllm.utils import get_cpu_memory, is_hip
File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/utils.py", line 11, in
from vllm._C import cuda_utils
ImportError: /home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/vllm/_C.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE
