### ISSUE TITLE
chatglm3-6b模型llm模式，正常对话突然报错TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Andy1018** [chatchat-space/Langchain-Chatchat#3305]
24-03-13 17:02:32,422 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/chatglm3/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-03-13 17:02:32,426 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
2024-03-13 17:02:34,294 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/chatglm3/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-03-13 17:02:34,296 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
2024-03-13 17:02:41,976 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/chatglm3/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-03-13 17:02:41,978 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by zRzRzRzRzRzRzR** [comment]
估计是说一半模型异常了，你单独跑chatglm3的示例能正常回答完整的流程吗

**Comment by Donovan-Ye** [comment]
是不是显存不够了。。我们这边爆显存的时候会出现这个错误

**Comment by LaoK263** [comment]
我使用智谱的在线API，本地没有大模型，也遇到了相同的错误，每次出现该错误时，chat都没有返回，应该是对超时未返回或者返回异常的处理问题，一般情况下重试就行了。

**Comment by sevenandseven** [comment]
> 估计是说一半模型异常了，你单独跑chatglm3的示例能正常回答完整的流程吗

你好，我在hf上下载了128k的长文本模型，但是他在langchain工程中使用时，出现了utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()  问题，并且该模型无法进行正常对话，请问怎么处理？

**Comment by xuzhigong** [comment]
windows无独立显卡跑本地模型（千问）会遇到这个问题，切换为在线模型后可正常使用

**Comment by Buezw** [comment]
torch 版本

**Comment by Andy1018** [comment]
@Buezw torch版本不对还能正常使用？是在正常对话的过程中出现了问题

**Comment by Andy1018** [comment]
> > 估计是说一半模型异常了，你单独跑chatglm3的示例能正常回答完整的流程吗
> 
> 你好，我在hf上下载了128k的长文本模型，但是他在langchain工程中使用时，出现了utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len() 问题，并且该模型无法进行正常对话，请问怎么处理？

我觉得这个是正解
