### ISSUE TITLE
[FEATURE] 启动时发生错误

### ISSUE THREAD

**Issue by huangbz2007** [chatchat-space/Langchain-Chatchat#3334]
python3 startup.py -a

Traceback (most recent call last):
  File "/Users/hbz/git/Langchain-Chatchat/startup.py", line 35, in <module>
    from server.utils import (fschat_controller_address, fschat_model_worker_address,
  File "/Users/hbz/git/Langchain-Chatchat/server/utils.py", line 4, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'

is:issue is:open  No module named 'fastapi'

**Comment by huangbz2007** [comment]
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import OpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/document_loaders/__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.document_loaders import JSONLoader`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_cffi_backend.cpython-312-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_cffi_backend.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_cffi_backend.cpython-312-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_cffi_backend.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/err/mod.rs:788:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/hbz/git/Langchain-Chatchat/startup.py", line 38, in <module>
    from server.knowledge_base.migrate import create_tables
  File "/Users/hbz/git/Langchain-Chatchat/server/knowledge_base/migrate.py", line 11, in <module>
    from server.knowledge_base.kb_service.base import KBServiceFactory
  File "/Users/hbz/git/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 29, in <module>
    from server.embeddings_api import embed_texts, aembed_texts, embed_documents
  File "/Users/hbz/git/Langchain-Chatchat/server/embeddings_api.py", line 3, in <module>
    from server.model_workers.base import ApiEmbeddingsParams
  File "/Users/hbz/git/Langchain-Chatchat/server/model_workers/__init__.py", line 2, in <module>
    from .zhipu import ChatGLMWorker
  File "/Users/hbz/git/Langchain-Chatchat/server/model_workers/zhipu.py", line 11, in <module>
    import jwt
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jwt/__init__.py", line 17, in <module>
    from .jwa import std_hash_by_alg
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jwt/jwa.py", line 26, in <module>
    from cryptography.hazmat.primitives.asymmetric import padding
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cryptography/hazmat/primitives/asymmetric/padding.py", line 9, in <module>
    from cryptography.hazmat.primitives import hashes
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cryptography/hazmat/primitives/hashes.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
pyo3_runtime.PanicException: Python API call failed  还有如上错误

**Comment by huangbz2007** [comment]
@imClumsyPanda 麻烦看下哦

**Comment by imClumsyPanda** [comment]
目前3.12还没有进行测试，建议按照项目readme和wiki中的版本要求及依赖包安装完成后再启动项目
