### ISSUE TITLE
LLM对话没问题，知识库对话报错peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by GamePlayerScript** [chatchat-space/Langchain-Chatchat#3342]
LLM对话没问题，知识库对话报错

2024-03-15 09:31:42,966 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:41506 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-15 09:31:42,967 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-15 09:31:43,090 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:41506 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-15 09:31:43,091 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:41506 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-15 09:31:43,094 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-15 09:31:48,448 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52666 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-15 09:31:48,449 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-15 09:31:48,474 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52666 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-15 09:31:48,476 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52666 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-15 09:31:48,478 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52666 - "POST /chat/chat HTTP/1.1" 200 OK
2024-03-15 09:31:48,529 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-03-15 09:31:48 | INFO | stdout | INFO:     127.0.0.1:36524 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-03-15 09:31:48,555 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-03-15 09:31:48 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-03-15 09:31:57,468 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52680 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-15 09:31:57,468 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-15 09:31:57,487 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52680 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-15 09:31:57,488 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52680 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-15 09:31:57,490 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:52680 - "GET /knowledge_base/list_knowledge_bases HTTP/1.1" 200 OK
2024-03-15 09:31:57,493 - _client.py[line:1027] - INFO: HTTP Request: GET http://127.0.0.1:7861/knowledge_base/list_knowledge_bases "HTTP/1.1 200 OK"
2024-03-15 09:32:01,124 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51750 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-15 09:32:01,125 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-15 09:32:01,144 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51750 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-15 09:32:01,145 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51750 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-15 09:32:01,148 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51750 - "GET /knowledge_base/list_knowledge_bases HTTP/1.1" 200 OK
2024-03-15 09:32:01,152 - _client.py[line:1027] - INFO: HTTP Request: GET http://127.0.0.1:7861/knowledge_base/list_knowledge_bases "HTTP/1.1 200 OK"
INFO:     127.0.0.1:51750 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
2024-03-15 09:32:01,251 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 587, in receive
    await self.message_event.wait()
  File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f17d9a8c850

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/home/zwy/workspace/chat_glm/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 81, in knowledge_base_chat_iterator
    |     docs = await run_in_threadpool(search_docs,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/home/zwy/anaconda3/envs/langchain/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/zwy/workspace/chat_glm/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 38, in search_docs
    |     docs = kb.search_docs(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/zwy/workspace/chat_glm/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 181, in search_docs
    |     docs = self.do_search(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/zwy/workspace/chat_glm/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 66, in do_search
    |     embeddings = embed_func.embed_query(query)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/zwy/workspace/chat_glm/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 424, in embed_query
    |     query_embed = embeddings[0]
    |                   ~~~~~~~~~~^^^
    | TypeError: 'NoneType' object is not subscriptable
    +------------------------------------
2024-03-15 09:32:01,255 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by GamePlayerScript** [comment]
![lQDPJw-J-m5Ty5HNAzPNBpGwPQQ7lCmpidIF4Y4zz9ZxAA_1681_819](https://github.com/chatchat-space/Langchain-Chatchat/assets/52642167/3b6dfce0-601e-4a87-9bb1-eed8d1fb456d)

**Comment by zRzRzRzRzRzRzR** [comment]
超过长度了，修改maxtoken变大就行

**Comment by zmwstu** [comment]
> 超过长度了，修改maxtoken变大就行

请问在哪修改maxtoken？
