### ISSUE TITLE
执行python init_database.py --recreate-vs

### ISSUE THREAD

**Issue by jimmywangzhiping** [chatchat-space/Langchain-Chatchat#3346]
(base) PS H:\Private\Langchain-Chatchat>  python init_database.py --recreate-vs
Traceback (most recent call last):
  File "H:\Private\Langchain-Chatchat\init_database.py", line 3, in <module>
    from server.knowledge_base.migrate import (create_tables, reset_tables, import_from_db,
  File "H:\Private\Langchain-Chatchat\server\knowledge_base\migrate.py", line 6, in <module>
    from server.knowledge_base.utils import (
  File "H:\Private\Langchain-Chatchat\server\knowledge_base\utils.py", line 15, in <module>
    import langchain.document_loaders
  File "D:\Users\dddd\AppData\Local\anaconda3\Lib\site-packages\langchain\document_loaders\__init__.py", line 18, in <module>
    from langchain_community.document_loaders.acreom import AcreomLoader
  File "D:\Users\dddd\AppData\Local\anaconda3\Lib\site-packages\langchain_community\document_loaders\__init__.py", line 163, in <module>
    from langchain_community.document_loaders.pebblo import PebbloSafeLoader
  File "D:\Users\dddd\AppData\Local\anaconda3\Lib\site-packages\langchain_community\document_loaders\pebblo.py", line 5, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

**Comment by jimmywangzhiping** [comment]
pip install langchain-community==0.0.19

**Comment by 1992leiting** [comment]
> pip install langchain-community==0.0.19

Really works!

**Comment by Belonger** [comment]
Really works!！！！！！
