### ISSUE TITLE
通过webui客户端交互，报错IndexError: list index out of range

### ISSUE THREAD

**Issue by Andy1018** [chatchat-space/Langchain-Chatchat#3347]
2024-03-15 11:12:59.932 Uncaught app exception
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/chatglm3/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/chatglm3/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 325, in dialogue_page
    chat_box.show_feedback(**feedback_kwargs,
  File "/home/user/anaconda3/envs/langchai-chat/lib/python3.11/site-packages/streamlit_chatbox/messages.py", line 307, in show_feedback
    with self._chat_containers[history_index]:
         ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by lhtpluto** [comment]
也遇到这个问题了

2024-04-10 22:47:37.539 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/Langchain-Chatchat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/llm/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/llm/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 324, in dialogue_page
    chat_box.show_feedback(**feedback_kwargs,
  File "/root/anaconda3/envs/Langchain-Chatchat/lib/python3.11/site-packages/streamlit_chatbox/messages.py", line 307, in show_feedback
    with self._chat_containers[history_index]:
         ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range
