### ISSUE TITLE
初始化向量库报错

### ISSUE THREAD

**Issue by why3z** [chatchat-space/Langchain-Chatchat#3358]
**问题描述 / Problem Description**
执行 python init_database.py --recreate-vs报错 
**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
PS D:\Langchain-Chatchat> python init_database.py --recreate-vs
recreating all vector stores
2024-03-15 15:09:39,006 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh-v1.5' from disk.
2024-03-15 15:09:39,408 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5
2024-03-15 15:09:39,421 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5 (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_
ssl.c:997)'))))"), '(Request ID: 1a31db15-d6b1-4e51-ad79-14612266d491)')
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Langchain-Chatchat\init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "D:\Langchain-Chatchat\server\knowledge_base\migrate.py", line 121, in folder2db
    kb.create_kb()
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 81, in create_kb
    self.do_create_kb()
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_cache\faiss_cache.py", line 102, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_cache\faiss_cache.py", line 60, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
  File "D:\Langchain-Chatchat\venv\lib\site-packages\langchain_core\vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "D:\Langchain-Chatchat\venv\lib\site-packages\langchain_community\vectorstores\faiss.py", line 965, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 425, in embed_documents
    return normalize(embeddings).tolist()
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "D:\Langchain-Chatchat\venv\lib\site-packages\numpy\linalg\linalg.py", line 2541, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by Panchat001** [comment]
@why3z 我也遇到这个问题，目前已经解决了 
1. 确定 model_config.py 文件中的 EMBEDDING_MODEL 路径是否正确
2. 1_Pooling 文件里面的 config.json 不知道为什么下载的名字是 1_Pooling_config.json ，重命名为 config.json
这样就解决了

**Comment by masterDXP** [comment]
@Panchat001 我MODEL_ROOT_PATH，EMBEDDING_MODEL，MODEL_PATH里面和bge-large-zh相关的路径全改了，还是没用

**Comment by Sololololo** [comment]
> @why3z 我也遇到这个问题，目前已经解决了
> 
>     1. 确定 model_config.py 文件中的 EMBEDDING_MODEL 路径是否正确
> 
>     2. 1_Pooling 文件里面的 config.json 不知道为什么下载的名字是 1_Pooling_config.json ，重命名为 config.json
>        这样就解决了

成功了，感谢朋友。智源的bge-m3也可以通过这个问题解决。
