### ISSUE TITLE
[BUG] python startup.py -a 不能正常启动服务

### ISSUE THREAD

**Issue by huan0808** [chatchat-space/Langchain-Chatchat#3362]
**问题描述 / Problem Description**
python startup.py -a 运行后报：
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /register_worker

**复现问题的步骤 / Steps to Reproduce**
python startup.py -a 

**预期的结果 / Expected Result**
HTTPConnection成功

**实际结果 / Actual Result**
HTTPConnection失败

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： d879e86
- 应该为通用问题

**附加信息 / Additional Information**
详细log:
2024-03-15 17:04:58 | ERROR | stderr | /home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
2024-03-15 17:04:58 | ERROR | stderr |   return self.fget.__get__(instance, owner)()
2024-03-15 17:05:04 | INFO | model_worker | Register to controller
2024-03-15 17:05:04 | ERROR | stderr | Process model_worker - baichuan2-7b-chat:
2024-03-15 17:05:04 | ERROR | stderr | Traceback (most recent call last):
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
2024-03-15 17:05:04 | ERROR | stderr |     sock = connection.create_connection(
2024-03-15 17:05:04 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
2024-03-15 17:05:04 | ERROR | stderr |     raise err
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
2024-03-15 17:05:04 | ERROR | stderr |     sock.connect(sa)
2024-03-15 17:05:04 | ERROR | stderr | ConnectionRefusedError: [Errno 111] Connection refused
2024-03-15 17:05:04 | ERROR | stderr | 
2024-03-15 17:05:04 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-03-15 17:05:04 | ERROR | stderr | 
2024-03-15 17:05:04 | ERROR | stderr | Traceback (most recent call last):
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
2024-03-15 17:05:04 | ERROR | stderr |     response = self._make_request(
2024-03-15 17:05:04 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
2024-03-15 17:05:04 | ERROR | stderr |     conn.request(
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/connection.py", line 400, in request
2024-03-15 17:05:04 | ERROR | stderr |     self.endheaders()
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/http/client.py", line 1293, in endheaders
2024-03-15 17:05:04 | ERROR | stderr |     self._send_output(message_body, encode_chunked=encode_chunked)
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/http/client.py", line 1052, in _send_output
2024-03-15 17:05:04 | ERROR | stderr |     self.send(msg)
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/http/client.py", line 990, in send
2024-03-15 17:05:04 | ERROR | stderr |     self.connect()
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/connection.py", line 238, in connect
2024-03-15 17:05:04 | ERROR | stderr |     self.sock = self._new_conn()
2024-03-15 17:05:04 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/connection.py", line 213, in _new_conn
2024-03-15 17:05:04 | ERROR | stderr |     raise NewConnectionError(
2024-03-15 17:05:04 | ERROR | stderr | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f117da2e610>: Failed to establish a new connection: [Errno 111] Connection refused
2024-03-15 17:05:04 | ERROR | stderr | 
2024-03-15 17:05:04 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-03-15 17:05:04 | ERROR | stderr | 
2024-03-15 17:05:04 | ERROR | stderr | Traceback (most recent call last):
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
2024-03-15 17:05:04 | ERROR | stderr |     resp = conn.urlopen(
2024-03-15 17:05:04 | ERROR | stderr |            ^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
2024-03-15 17:05:04 | ERROR | stderr |     retries = retries.increment(
2024-03-15 17:05:04 | ERROR | stderr |               ^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
2024-03-15 17:05:04 | ERROR | stderr |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-03-15 17:05:04 | ERROR | stderr |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117da2e610>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-03-15 17:05:04 | ERROR | stderr | 
2024-03-15 17:05:04 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-03-15 17:05:04 | ERROR | stderr | 
2024-03-15 17:05:04 | ERROR | stderr | Traceback (most recent call last):
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-03-15 17:05:04 | ERROR | stderr |     self.run()
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-03-15 17:05:04 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/Desktop/project/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-03-15 17:05:04 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-15 17:05:04 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/Desktop/project/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-03-15 17:05:04 | ERROR | stderr |     worker = ModelWorker(
2024-03-15 17:05:04 | ERROR | stderr |              ^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 102, in __init__
2024-03-15 17:05:04 | ERROR | stderr |     self.init_heart_beat()
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/base_model_worker.py", line 79, in init_heart_beat
2024-03-15 17:05:04 | ERROR | stderr |     self.register_to_controller()
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/fastchat/serve/base_model_worker.py", line 96, in register_to_controller
2024-03-15 17:05:04 | ERROR | stderr |     r = requests.post(url, json=data)
2024-03-15 17:05:04 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/requests/api.py", line 115, in post
2024-03-15 17:05:04 | ERROR | stderr |     return request("post", url, data=data, json=json, **kwargs)
2024-03-15 17:05:04 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/requests/api.py", line 59, in request
2024-03-15 17:05:04 | ERROR | stderr |     return session.request(method=method, url=url, **kwargs)
2024-03-15 17:05:04 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-03-15 17:05:04 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-03-15 17:05:04 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-03-15 17:05:04 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-03-15 17:05:04 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15 17:05:04 | ERROR | stderr |   File "/home/link/miniconda3/envs/chatchat/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
2024-03-15 17:05:04 | ERROR | stderr |     raise ConnectionError(e, request=request)
2024-03-15 17:05:04 | ERROR | stderr | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117da2e610>: Failed to establish a new connection: [Errno 111] Connection refused'))
^C2024-03-15 17:10:15,831 - startup.py[line:855] - WARNING: Sending SIGKILL to {}
2024-03-15 17:10:15,834 - startup.py[line:855] - WARNING: Sending SIGKILL to {'baichuan2-7b-chat': <Process name='model_worker - baichuan2-7b-chat (13345)' pid=13345 parent=13250 stopped exitcode=1 daemon>}
2024-03-15 17:10:15,834 - startup.py[line:855] - WARNING: Sending SIGKILL to <Process name='WEBUI Server' parent=13250 initial daemon>

**Comment by huan0808** [comment]
root cause:将openai_api 改成了False，没有启动model_controller
![YDcuMk4DgU](https://github.com/chatchat-space/Langchain-Chatchat/assets/49682558/4058fa7b-5d6e-4c62-bbc2-d70e8ece571a)
counter measure:  改回True,正常启动服务
