### ISSUE TITLE
添加文件到知识库报错 ：AssertionError: daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by wenzhaoabc** [chatchat-space/Langchain-Chatchat#3375]
**问题描述 / Problem Description**
对于新建的知识库，在添加文件时报错。前端显示`未返回正确JSON`，后端报错日志如下

```txt
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lang/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 153, in upload_docs
    result = update_docs(
             ^^^^^^^^^^^^
  File "/root/lang/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 261, in update_docs
    for status, result in files2docs_in_thread(kb_files,
  File "/root/lang/Langchain-Chatchat/server/knowledge_base/utils.py", line 404, in files2docs_in_thread
    for result in run_in_process_pool(func=files2docs_in_thread_file2docs, params=kwargs_list):
  File "/root/lang/Langchain-Chatchat/server/utils.py", line 599, in run_in_process_pool
    tasks.append(pool.submit(func, **kwargs))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/langchat/lib/python3.11/concurrent/futures/process.py", line 808, in submit
    self._adjust_process_count()
  File "/root/miniconda3/envs/langchat/lib/python3.11/concurrent/futures/process.py", line 767, in _adjust_process_count
    self._spawn_process()
  File "/root/miniconda3/envs/langchat/lib/python3.11/concurrent/futures/process.py", line 785, in _spawn_process
    p.start()
  File "/root/miniconda3/envs/langchat/lib/python3.11/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
2024-03-17 16:16:54.111 ComponentRequestHandler: GET /root/miniconda3/envs/langchat/lib/python3.11/site-packages/st_aggrid/frontend/build/bootstrap.min.css.map read error
Traceback (most recent call last):
  File "/root/miniconda3/envs/langchat/lib/python3.11/site-packages/streamlit/web/server/component_request_handler.py", line 51, in get
    with open(abspath, "rb") as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/miniconda3/envs/langchat/lib/python3.11/site-packages/st_aggrid/frontend/build/bootstrap.min.css.map'
```

**复现问题的步骤 / Steps to Reproduce**
1. 点击Browse files选择文件
2. 点击添加文件到知识库
3. 前端提示 未返回正确JSON，后端报错日志信息如上。

**预期的结果 / Expected Result**
正确添加文件，文件向量化后添加到知识库，并且`源文件`，`向量库`两列为对勾

**实际结果 / Actual Result**
前端报错，后端报错，`源文件`，`向量库`两列仍为`×`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：commit 4bdb69b
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：openai/gpt-4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：openai/text-embedding-3-large
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 22.04
- Python 版本 / Python version: python 3.11
- 其他相关环境信息 / Other relevant environment information: conda 24.1.2，系统配置2核4G，无GPU

**附加信息 / Additional Information**
使用dev分支操作。启动步骤如下
```bash
bash update_requirements.sh

python startup.py -a --lite
```

与LLM对话无异常，但是无法正确获取文档内的知识，向量库添加失败。

**Comment by litongyun233** [comment]
遇到同样的问题，请问作者如何解决的

**Comment by wenzhaoabc** [comment]
没有找到有效的解决方法，改成了fastGPT
