### ISSUE TITLE
添加文件到知识库报错: ERROR: ReadError: error when post /knowledge_base/upload_docs: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by ttPrivacy** [chatchat-space/Langchain-Chatchat#3376]
**问题描述 / Problem Description**
添加文件到知识库报错

```
2024-03-17 17:20:59,815 - utils.py[line:295] - INFO: RapidOCRDocLoader used for E:\WorkSpace\zhishiku\Langchain-Chatchat\knowledge_base\tt1\content\三国.docx
RapidOCRDocLoader  block index: 2: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 98.34it/s]
2024-03-17 17:21:01,478 - utils.py[line:95] - ERROR: ReadError: error when post /knowledge_base/upload_docs: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-03-17 17:21:03,534 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/upload_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:05,574 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/upload_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:07,980 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:10,023 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:12,061 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

```
**环境信息 / Environment Information**
windows11
python3.11
显卡4070tisuper
显存16g 内存32g

**Comment by ttPrivacy** [comment]
点击添加文件到知识库或者依据源文件重建向量库就会发生这种情况，看这情况是server里的api.py的fastapi直接挂了，为什么会发生这个情况呢？
全部输出如下
```
服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================



  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

2024-03-17 17:20:05,645 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54980 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-17 17:20:05,646 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-17 17:20:05,851 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54980 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-17 17:20:05,852 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54980 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-17 17:20:05,864 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54983 - "POST /knowledge_base/search_docs HTTP/1.1" 200 OK
2024-03-17 17:20:06,795 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54988 - "POST /knowledge_base/search_docs HTTP/1.1" 200 OK
2024-03-17 17:20:20,073 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 200 OK"
INFO:     127.0.0.1:54991 - "POST /knowledge_base/search_docs HTTP/1.1" 200 OK
2024-03-17 17:20:22,004 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 200 OK"
2024-03-17 17:20:25,400 - faiss_cache.py[line:92] - INFO: loading vector store in 'tt1/vector_store/bge-large-zh-v1.5' from disk.
2024-03-17 17:20:25,401 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5
2024-03-17 17:20:26,724 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2024-03-17 17:20:26,724 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2024-03-17 17:20:26,724 - loader.py[line:64] - INFO: Loading faiss.
2024-03-17 17:20:26,777 - loader.py[line:66] - INFO: Successfully loaded faiss.
E:\Anaconda3\Lib\site-packages\langchain_community\vectorstores\faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(
2024-03-17 17:20:26,787 - faiss_cache.py[line:38] - INFO: 已将向量库 ('tt1', 'bge-large-zh-v1.5') 保存到磁盘
INFO:     127.0.0.1:54992 - "POST /knowledge_base/delete_docs HTTP/1.1" 200 OK
2024-03-17 17:20:26,787 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/delete_docs "HTTP/1.1 200 OK"
2024-03-17 17:20:59,815 - utils.py[line:295] - INFO: RapidOCRDocLoader used for E:\WorkSpace\zhishiku\Langchain-Chatchat\knowledge_base\tt1\content\三国.docx
RapidOCRDocLoader  block index: 2: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 98.34it/s]
2024-03-17 17:21:01,478 - utils.py[line:95] - ERROR: ReadError: error when post /knowledge_base/upload_docs: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-03-17 17:21:03,534 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/upload_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:05,574 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/upload_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:07,980 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:10,023 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:12,061 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-03-17 17:21:12.062 Uncaught app exception
Traceback (most recent call last):
  File "E:\Anaconda3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "E:\WorkSpace\zhishiku\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "E:\WorkSpace\zhishiku\Langchain-Chatchat\webui_pages\knowledge_base\knowledge_base.py", line 328, in knowledge_base_page
    data = [
           ^
  File "E:\WorkSpace\zhishiku\Langchain-Chatchat\webui_pages\knowledge_base\knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by ttPrivacy** [comment]
另外有大佬可以帮忙拉我进微信群吗 官方的二维码进不去。

**Comment by ttPrivacy** [comment]
有人可以帮忙解答吗

**Comment by lujingyu** [comment]
同样的情况，防火墙关闭了也不行，Admin运行也不行，还有救吗？

**Comment by blackwhites** [comment]
我用milvus 也出现了同样的错误，数据进入Milvus，点击文档就报一样的错

**Comment by Lj4040** [comment]
解决了吗？我也遇到同样的错误了
