### ISSUE TITLE
[BUG] RuntimeError: Task <Task pending name='Task-1329' coro=<RequestResponseCycle.run_asgi() running at /data/soft ware/anaconda3/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py:419> cb=[set.discard()]> got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by SolarKnight1** [chatchat-space/Langchain-Chatchat#3394]
**问题描述 / Problem Description**
在api调用的时候，出现了上述error报错，且问的问题回复为空

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...' python startup.py -a 
2. 点击 '...' / Click '...'  调用/chat/file-chat
3. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
详细报错信息：INFO:     115.236.165.162:5584 - "POST /chat/file_chat HTTP/1.1" 200 OK
Batches: 100%|██████████████████████████████████████████████���██████████████████| 1/1 [00:00<00:00, 49.73it/s]

> Entering new LLMChain chain...
Prompt after formatting:
user: <指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，不
允许在答案中添加编造成分，答案请使用中文。 </指令>
<已知信息>度对应日的 24 时止为一个保单月度。
【保险金受益人】：是指合同中约定的有权申请领取保险金的人。
【不可抗力】：是指不能预见、不可避免且无法克服的客观情况。
。。。
2024-03-18 14:42:09 | INFO | stdout | INFO:     127.0.0.1:54584 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-03-18 14:42:09,316 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/com
pletions "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line
419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/software/anaconda3/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, i
n __call__
    return await self.app(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call_
_
    await self.middleware_stack(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __
call__
    raise exc
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __
call__
    await self.app(scope, receive, _send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in
 __call__
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wr
apped_app
    raise exc
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wr
apped_app
    await app(scope, receive, sender)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wr
apped_app
    raise exc
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wr
apped_app
    await app(scope, receive, sender)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_f
unction
    return await dependant.call(**values)
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastchat/serve/base_model_worker.py", line 196,
in api_generate_stream
    await acquire_worker_semaphore()
  File "/data/software/anaconda3/lib/python3.9/asyncio/locks.py", line 417, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-1314' coro=<RequestResponseCycle.run_asgi() running at /data/soft
ware/anaconda3/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py:419> cb=[set.discard()]>
got Future <Future pending> attached to a different loop
2024-03-18 14:42:09 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21001/worker_generate_stream "HTTP/1
.1 500 Internal Server Error"

> Finished chain.
INFO:     115.236.165.162:5585 - "POST /chat/file_chat HTTP/1.1" 200 OK

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by SwordHG** [comment]
@SolarKnight1 这个问题有解决吗，我也遇到的相同的问题，并发大于5后，就出现了一样的问题
