### ISSUE TITLE
[BUG] 长上下文模型输入较长时显示显存不足，显存分配在单卡上。

### ISSUE THREAD

**Issue by XHANYAO** [chatchat-space/Langchain-Chatchat#3412]
**问题描述 / Problem Description**
长上下文模型尝试，这里尝试了internlm2-chat-7b和Orion-14b-longchat,在单机8卡4090运行，启动没有问题，8张卡都正常分配了显存。对话模式问较短的问题也没问题，但输入较长时（38k）显示显存不足，并且显存分配在单卡上。

**复现问题的步骤 / Steps to Reproduce**
同问题描述。

**预期的结果 / Expected Result**
正常回答问题

**实际结果 / Actual Result**
```2024-03-18 11:36:32,347 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-03-18 11:36:32 | INFO | stdout | INFO:     127.0.0.1:56178 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-03-18 11:36:32,617 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
这是一个check的log:
{'id': 'chatcmpl-nm4f2A28DjnUnQarGA29Nx', 'choices': [{'delta': {'content': None, 'function_call': None, 'role': 'assistant', 'tool_calls': None}, 'finish_reason': None, 'index': 0, 'logprobs': None}], 'created': None, 'model': 'internlm2-chat-7b', 'object': None, 'system_fingerprint': None}
2024-03-18 11:36:32 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
这是一个check的log:
{'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'text': '**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(CUDA out of memory. Tried to allocate 60.64 GiB. GPU 0 has a total capacty of 23.65 GiB of which 16.64 GiB is free. Process 3804868 has 7.00 GiB memory in use. Of the allocated memory 5.10 GiB is allocated by PyTorch, and 1.45 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF)', 'error_code': 50002}
2024-03-18 11:36:33,339 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/workspace/xhy/langchain-chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/chat_models/openai.py", line 524, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/chat_models/openai.py", line 495, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否（本地部署，但运行是在docker上运行） 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：internlm2-chat-7b\Orion-14b-longchat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: ubuntu
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information: torch2.1 cuda 12.1

**附加信息 / Additional Information**
报错
```
if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
```
感觉是很多人遇到的问题，打印的log借鉴了类似问题中一位老哥的方法。
在server.config中，我的修改如下：
```
FSCHAT_MODEL_WORKERS = {
    # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
    "default": {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
        # vllm对一些模型支持还不成熟，暂时默认关闭
        "infer_turbo": False,

        # model_worker多卡加载需要配置的参数
        "gpus": "0,1,2,3,4,5,6,7", # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        "num_gpus": 8, # 使用GPU的数量
        "max_gpu_memory": "20GiB", # 每个GPU占用的最大显存
 ```
 在model.config中，我的修改如下：
 ```
 # 选用的 Embedding 名称
EMBEDDING_MODEL = "bge-large-zh-v1.5"

# Embedding 模型运行设备。设为 "auto" 会自动检测(会有警告)，也可手动设定为 "cuda","mps","cpu","xpu" 其中之一。
EMBEDDING_DEVICE = "auto"

# 选用的reranker模型
RERANKER_MODEL = "bge-reranker-large"
# 是否启用reranker模型
USE_RERANKER = False
RERANKER_MAX_LENGTH = 1024

# 如果需要在 EMBEDDING_MODEL 中增加自定义的关键字时配置
EMBEDDING_KEYWORD_FILE = "keywords.txt"
EMBEDDING_MODEL_OUTPUT_PATH = "output"

# 要运行的 LLM 名称，可以包括本地模型和在线模型。列表中本地模型将在启动项目时全部加载。
# 列表中第一个模型将作为 API 和 WEBUI 的默认模型。
# 在这里，我们使用目前主流的两个离线模型，其中，chatglm3-6b 为默认加载模型。
# 如果你的显存不足，可使用 Qwen-1_8B-Chat, 该模型 FP16 仅需 3.8G显存。

LLM_MODELS = ["internlm2-chat-7b"]
Agent_MODEL = None

# LLM 模型运行设备。设为"auto"会自动检测(会有警告)，也可手动设定为 "cuda","mps","cpu","xpu" 其中之一。
LLM_DEVICE = "auto"

HISTORY_LEN = 3

MAX_TOKENS = 65536

TEMPERATURE = 0.7
```

**Comment by XHANYAO** [comment]
> 在server.config中，我的修改如下：
> 
> FSCHAT_MODEL_WORKERS = {
>     # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
>     "default": {
>         "host": DEFAULT_BIND_HOST,
>         "port": 20002,
>         "device": LLM_DEVICE,
>         # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
>         # vllm对一些模型支持还不成熟，暂时默认关闭
>         "infer_turbo": False,
> 
>         # model_worker多卡加载需要配置的参数
>         "gpus": "0,1,2,3,4,5,6,7", # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
>         "num_gpus": 8, # 使用GPU的数量
>         "max_gpu_memory": "20GiB", # 每个GPU占用的最大显存
我已经指定使用8张gpu,并且可以回答简短的问题。但在输出超长文本时会报错，首先超长文本输入后提示显存不足，但8张4090的显存是足够的，导致不足的原因似乎是因为输入张量被分配到了一个Gpu上，我想知道如何解决这个问题。

**Comment by HitFjn** [comment]
老哥解决了吗

**Comment by XHANYAO** [comment]
> 老哥解决了吗

没有啊，暂时先用32k的模型顶着。而且我感觉chatchat这个框架本身对超长文本模型支持可能也不是特别好，Orion-14b-longchat我得改好几个地方的代码才能启动。

**Comment by GuuHeng** [comment]
我也遇到这种问题，只有大模型是平均分配到2张显卡上，但知识库问答时，向量模型、包含了query和docs等的prompt却只在一张显卡上，导致稍大点的模型就不能推理回复了，只能改用小点模型。还没找到解决办法。

**Comment by zRzRzRzRzRzRzR** [comment]
一开始就要分配到两张卡，用VLLM

**Comment by azhe1234** [comment]
> 一开始就要分配到两张卡，用VLLM

![Image](https://github.com/user-attachments/assets/f3ee22d3-13be-4095-bc45-6ce3707e217f)

![Image](https://github.com/user-attachments/assets/17f10d84-625c-4f68-9a25-160341d75e48)

您好，请问在进行知识库问答时，随着提问的轮次增多，显存越来越大，使用的是deepseek-r1-32b的模型，怎样配置可以实现llm分配到多张卡上呢，是需要在model_settings.yaml里配置吗？谢谢！
