### ISSUE TITLE
[BUG] 调用智谱在线向量库Embedding-2出错，报错为'zhipu-api' is not in list，是否使用api作为llm就不能使用它作为向量模型？

### ISSUE THREAD

**Issue by 871052165** [chatchat-space/Langchain-Chatchat#3450]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
官方未给出在线向量库如何接入，目前我的配置如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/53ccc521-7076-4ba3-bb9b-28b6b1d257cb)

**预期的结果 / Expected Result**
正常调用

**实际结果 / Actual Result**
2024-03-20 17:24:38,769 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62587 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-20 17:24:38,772 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-20 17:24:39,129 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62587 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-20 17:24:39,133 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62587 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-20 17:24:39,181 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-20 17:24:53,145 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62596 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-20 17:24:53,147 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-20 17:24:53,503 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62596 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-20 17:24:53,504 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62596 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-20 17:24:53,551 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-20 17:25:12,803 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62607 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-20 17:25:12,805 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-20 17:25:13,070 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62607 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-20 17:25:13,073 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62607 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-20 17:25:13,119 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:62607 - "POST /chat/chat HTTP/1.1" 200 OK
2024-03-20 17:25:13,128 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
D:\ProgramData\anaconda3\envs\langchain0.2.10\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-03-20 17:25:13 | INFO | stdout | INFO:     127.0.0.1:62610 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-03-20 17:25:13,825 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
{'choices': [{'finish_reason': 'stop', 'index': 0, 'message': {'content': '你好👋！我是人工智能助手智谱清言，可以叫我小 智🤖，很高兴见到你，欢迎问我任何问题。', 'role': 'assistant'}}], 'created': 1710926716, 'id': '8494924967707734063', 'model': 'glm-4', 'request_id': '8494924967707734063', 'usage': {'completion_tokens': 32, 'prompt_tokens': 6, 'total_tokens': 38}}
2024-03-20 17:25:21.472 Uncaught app exception
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\langchain0.2.10\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\AI\Langchain-Chatchat-master\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "D:\AI\Langchain-Chatchat-master\webui_pages\knowledge_base\knowledge_base.py", line 117, in knowledge_base_page
    index=embed_models.index(EMBEDDING_MODEL),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'zhipu-api' is not in list

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/871c92be-00e0-48a1-ab99-308cb0bfcf91)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：zhipu-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：Embedding-2
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:windos
- Python 版本 / Python version:3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
建议官方给一个调用规范

**Comment by devilmoom** [comment]
实际上目前代码并不支持智谱AI的在线嵌入模型，可以看下server/model_workers的相关代码，建议你换成百度千帆或者通义千问

**Comment by xiangjieli96** [comment]
我也用embedding-2，其他设置都确认没有错误，但是报错404，看了官方文档给出的解释是未开通服务

**Comment by JiXia830** [comment]
> 我也用embedding-2，其他设置都确认没有错误，但是报错404，看了官方文档给出的解释是未开通服务

我的报错是1113，账户欠费，但是我的token明明还剩很多
