### ISSUE TITLE
[BUG] 两个知识库问同一个问题，一个能回答，一个报错ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without 

### ISSUE THREAD

**Issue by 15927566740** [chatchat-space/Langchain-Chatchat#3462]
**问题描述 / Problem Description**
两个知识库问同一个问题，一个能回答，一个报错ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

![29ba59c742777620d4bca3fb087cfac](https://github.com/chatchat-space/Langchain-Chatchat/assets/48681680/5c12de8e-e949-409e-9c77-a92392262f61)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：是
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B / Qwen-14B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:Linux-5.15.0-71-generic-x86_64-with-glibc2.31.
- Python 版本 / Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

**Comment by 15927566740** [comment]
忘了贴报错了，以下是报错内容：


2024-03-21 16:29:14,407 - faiss_cache.py[line:92] - INFO: loading vector store in '331节点知识库/vector_store/bge-large-zh-v1.5' from disk.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
    async for data in self.body_iterator:
  File "/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 81, in knowledge_base_chat_iterator
    docs = await run_in_threadpool(search_docs,
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 38, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 182, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 67, in do_search
    with self.load_vector_store().acquire() as vs:
  File "/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 97, in load_vector_store
    vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
  File "/root/miniconda3/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 1116, in load_local
    docstore, index_to_docstore_id = pickle.load(f)
EOFError: Ran out of input
2024-03-21 16:29:15,321 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by 15927566740** [comment]
> 你好，@15927566740！很高兴再次见到你。希望你今天过得不错。
> 
> 根据您提供的信息，这个错误 "RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)" 通常表示在客户端和服务器之间的HTTP通信中存在问题，可能是由于服务器过早地关闭了连接，或者在处理分块传输编码时存在配置错误。这可能与Langchain-Chatchat的特定设置、Docker环境，或者与使用的模型和嵌入的交互有关。
> 
> 在Langchain-Chatchat的代码库中，处理API通信的具体函数或方法可能会抛出这个错误，但在提供的上下文中并没有直接提到这个特定错误或其直接原因。因此，很难确定错误的确切原因。
> 
> 解决此类错误的一般方法是查看服务器日志以获取更详细的错误消息，检查正在使用的软件版本是否存在已知问题，确保HTTP服务器和客户端在分块传输编码方面的正确配置，并可能根据发现更新或调整设置。然而，如果没有具体的信息将错误链接到提供的上下文中的已知问题或配置细节，就无法提供精确的解决方案。
> 
> 在Langchain-Chatchat的问题跟踪中，我找到了一些类似的问题，但没有一个直接提到这个特定错误或其直接原因。这些问题的建议解决方案包括检查网络连接，确保服务器可以正确访问OpenAI API，验证OpenAI API密钥是否正确，以及是否有足够的请求配额。如果在接收消息体时连接被关闭，尝试重新建立连接并重新发送请求。如果问题仍然存在，可能是OpenAI API服务器的问题，可能需要联系OpenAI的技术支持。
> 
> 然而，后来澄清说用户并未使用OpenAI的模型，实际的解决方案与代理问题有关。用户没有提供关于如何解决代理问题的具体细节。
> 
> 在Langchain-Chatchat的问题跟踪中，我还找到了一些类似的已关闭问题。这些问题的建议解决方案包括更新到版本0.2.7或开发分支以解决此问题，因为它在开发环境中正常运行。另一个建议的解决方案是直接拉取最新版本0.2.4的，重新部署就没有这个问题。还有一个建议的解决方案是检查是否安装了duckduckgo的包，通过pip install duckduckgo-search解决。
> 
> 以上信息是根据我在Langchain-Chatchat的问题跟踪中找到的信息得出的。如果您需要更多的帮助，或者如果您有更多的信息可以提供，那么我将很乐意提供更多的帮助。
> 
> ## Sources
> * [ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)](https://github.com/chatchat-space/Langchain-Chatchat/issues/3329)
> * [[BUG] 用通义千问API模式，LLM对话，返回错误：API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)](https://github.com/chatchat-space/Langchain-Chatchat/issues/1986)
> * [分开启动api服务时，在基于知识库问答时返回空答案，且后端有报错：httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)](https://github.com/chatchat-space/Langchain-Chatchat/issues/1279)
> * [使用搜索引擎问答，选择duckduckgo，开启科学上网，报错如下](https://github.com/chatchat-space/Langchain-Chatchat/issues/1072)
> * [knowledge_base/samples/content/test_files/langchain-ChatGLM_open.jsonl](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.jsonl)
> * [server/chat/chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/chat.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

忘了贴报错了，以下是报错内容：

2024-03-21 16:29:14,407 - faiss_cache.py[line:92] - INFO: loading vector store in '331节点知识库/vector_store/bge-large-zh-v1.5' from disk.
ERROR: Exception in ASGI application
Traceback (most recent call last):
File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 412, in run_asgi
result = await app( # type: ignore[func-returns-value]
File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in call
return await self.app(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in call
await super().call(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 119, in call
await self.middleware_stack(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in call
raise exc
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in call
await self.app(scope, receive, _send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in call
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
raise exc
File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 762, in call
await self.middleware_stack(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
await route.handle(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
await self.app(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
raise exc
File "/root/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
await response(scope, receive, send)
File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in call
async with anyio.create_task_group() as task_group:
File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in aexit
raise exceptions[0]
File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
await func()
File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
async for data in self.body_iterator:
File "/Langchain-Chatchat/server/chat/knowledge_base_chat.py", line 81, in knowledge_base_chat_iterator
docs = await run_in_threadpool(search_docs,
File "/root/miniconda3/lib/python3.10/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
return await anyio.to_thread.run_sync(func, *args)
File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
return await future
File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
result = context.run(func, *args)
File "/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 38, in search_docs
docs = kb.search_docs(query, top_k, score_threshold)
File "/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 182, in search_docs
docs = self.do_search(query, top_k, score_threshold)
File "/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 67, in do_search
with self.load_vector_store().acquire() as vs:
File "/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
File "/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 97, in load_vector_store
vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
File "/root/miniconda3/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 1116, in load_local
docstore, index_to_docstore_id = pickle.load(f)
EOFError: Ran out of input
2024-03-21 16:29:15,321 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
