### ISSUE TITLE
[BUG] v0.1.12打包镜像后启动webui.py失败 / Concise description of the issue

### ISSUE THREAD

**Issue by biiigwang** [chatchat-space/Langchain-Chatchat#347]
**问题描述 / Problem Description**
使用项目中`Dockerfile-cu`打包`v0.1.12`镜像后报错，详细日志如下
``` bash
INFO  2023-05-13 05:44:49,792-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /chatGLM
flagging username: 1625a58fa2cd423aaf241c227ca27514

2023-05-13 13:23:14 Traceback (most recent call last):
2023-05-13 13:23:14   File "webui.py", line 4, in <module>
2023-05-13 13:23:14     from chains.local_doc_qa import LocalDocQA
2023-05-13 13:23:14   File "/chatGLM/chains/local_doc_qa.py", line 13, in <module>
2023-05-13 13:23:14     from loader import UnstructuredPaddleImageLoader
2023-05-13 13:23:14   File "/chatGLM/loader/__init__.py", line 1, in <module>
2023-05-13 13:23:14     from .image_loader import UnstructuredPaddleImageLoader
2023-05-13 13:23:14   File "/chatGLM/loader/image_loader.py", line 5, in <module>
2023-05-13 13:23:14     from paddleocr import PaddleOCR
2023-05-13 13:23:14   File "/usr/local/lib/python3.8/dist-packages/paddleocr/__init__.py", line 14, in <module>
2023-05-13 13:23:14     from .paddleocr import *
2023-05-13 13:23:14   File "/usr/local/lib/python3.8/dist-packages/paddleocr/paddleocr.py", line 25, in <module>
2023-05-13 13:23:14     import cv2
2023-05-13 13:23:14   File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
2023-05-13 13:23:14     bootstrap()
2023-05-13 13:23:14   File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 153, in bootstrap
2023-05-13 13:23:14     native_module = importlib.import_module("cv2")
2023-05-13 13:23:14   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2023-05-13 13:23:14     return _bootstrap._gcd_import(name[level:], package, level)
2023-05-13 13:23:14 ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
解决上述以来后会出下如下错误
```bash
Traceback (most recent call last):
  File "webui.py", line 4, in <module>
    from chains.local_doc_qa import LocalDocQA
  File "/chatGLM/chains/local_doc_qa.py", line 13, in <module>
    from loader import UnstructuredPaddleImageLoader
  File "/chatGLM/loader/__init__.py", line 1, in <module>
    from .image_loader import UnstructuredPaddleImageLoader
  File "/chatGLM/loader/image_loader.py", line 5, in <module>
    from paddleocr import PaddleOCR
  File "/usr/local/lib/python3.8/dist-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/usr/local/lib/python3.8/dist-packages/paddleocr/paddleocr.py", line 25, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.1.12
- 是否使用 Docker 部署（是/否）：yes
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
执行以下命令后正常启动，不知道是否有更好的办法：
```bash
apt install libgl1-mesa-glx
apt install libglib2.0-dev 
```

**Comment by ray-008** [comment]
1. ImportError: libGL.so.1: cannot open shared object file: No such file or directory
使用 `apt-get update && apt-get install libgl1` 命令解决

2. ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
使用 `apt-get update && apt-get install libglib2.0-dev` 命令解决
