### ISSUE TITLE
init_database.py --recreate-vs 本地知识库启动失败

### ISSUE THREAD

**Issue by xiaoma444** [chatchat-space/Langchain-Chatchat#3472]
报错：recreating all vector stores
2024-03-22 10:54:26,440 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh' from disk.
2024-03-22 10:54:27,739 - embeddings_api.py[line:39] - ERROR: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/server/knowledge_base/migrate.py", line 121, in folder2db
    kb.create_kb()
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 81, in create_kb
    self.do_create_kb()
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/server/knowledge_base/kb_service/faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/server/knowledge_base/kb_cache/faiss_cache.py", line 102, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/server/knowledge_base/kb_cache/faiss_cache.py", line 60, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/scx6mbr/.conda/envs/py311_torch_cu118/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/scx6mbr/.conda/envs/py311_torch_cu118/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 965, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 439, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/scx6mbr/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in norm
  File "/home/bingxing2/home/scx6mbr/.conda/envs/py311_torch_cu118/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 2541, in norm
    s = (x.conj() * x).real
         ^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

环境：Python 3.11.8   torch 2.1.2+cu118
操作流程：更新代码->pip install -r requirement.txt ->pip install -r requirements_webui.txt  -> 下载模型->修改model_config.py.example中的EMBEDDING_MODEL = "bge-large-zh"   "bge-large-zh": "/home/bingxing2/home/scx6mbr/Telechat/bge-large-zh",  "chatglm3-6b": "/home/bingxing2/home/scx6mbr/chatglm3-6b",->python copy_config_example.py ->python init_database.py --recreate-vs

已经尝试：pip install sentence_transformers升降级都试了，更新了代码，对比了huggingface我的模型文件没问题，删掉了info_db,重新尝试过，按照issue里别人的方法都尝试过，使用资源为单块A100

**Comment by Autism-al** [comment]
我卸载了sentence-transformer后用conda重新安装就行了，pip安装的一直报错。

**Comment by buchidonggua** [comment]
我遇到同样的问题，兄弟怎么解决的。

**Comment by Autism-al** [comment]
> 我遇到同样的问题，兄弟怎么解决的。

你试试卸载sentence-transformer，用conda安装，别用pip。。我是这么解决的，不知道是啥原因，装环境很玄学呢。
