### ISSUE TITLE
能否实现完全本地化？

### ISSUE THREAD

**Issue by xx59469xx** [chatchat-space/Langchain-Chatchat#3493]
我使用了chatglm3-6和bge-large-zh两个模型，并且已经将模型保存到了本地，但是当我使用vpn执行python startup.py -a时就会报错：==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-67-generic-x86_64-with-glibc2.31.
python版本：3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/ai/chatglm/Langchain-Chatchat/Models/THUDM/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-03-23 20:03:24,412 - startup.py[line:658] - INFO: 正在启动服务：
2024-03-23 20:03:24,412 - startup.py[line:659] - INFO: 如需查看 llm_api 日志，请前往 /ai/chatglm/Langchain-Chatchat/logs
/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 30001): address already in use
2024-03-23 20:03:30 | ERROR | stderr | INFO:     Started server process [112584]
2024-03-23 20:03:30 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-23 20:03:30 | ERROR | stderr | INFO:     Application startup complete.
2024-03-23 20:03:30 | ERROR | stderr | ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 30000): address already in use
2024-03-23 20:03:30 | ERROR | stderr | INFO:     Waiting for application shutdown.
2024-03-23 20:03:30 | ERROR | stderr | INFO:     Application shutdown complete.
2024-03-23 20:03:30 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker ad0a3964 ...
Could not locate the tokenization_chatglm.py inside THUDM/chatglm3-6b.
2024-03-23 20:03:40 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-03-23 20:03:40 | ERROR | stderr | Traceback (most recent call last):
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
2024-03-23 20:03:40 | ERROR | stderr |     sock = connection.create_connection(
2024-03-23 20:03:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
2024-03-23 20:03:40 | ERROR | stderr |     raise err
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
2024-03-23 20:03:40 | ERROR | stderr |     sock.connect(sa)
2024-03-23 20:03:40 | ERROR | stderr | TimeoutError: timed out
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | Traceback (most recent call last):
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
2024-03-23 20:03:40 | ERROR | stderr |     response = self._make_request(
2024-03-23 20:03:40 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
2024-03-23 20:03:40 | ERROR | stderr |     raise new_e
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
2024-03-23 20:03:40 | ERROR | stderr |     self._validate_conn(conn)
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
2024-03-23 20:03:40 | ERROR | stderr |     conn.connect()
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/connection.py", line 616, in connect
2024-03-23 20:03:40 | ERROR | stderr |     self.sock = sock = self._new_conn()
2024-03-23 20:03:40 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/connection.py", line 207, in _new_conn
2024-03-23 20:03:40 | ERROR | stderr |     raise ConnectTimeoutError(
2024-03-23 20:03:40 | ERROR | stderr | urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fe045635ad0>, 'Connection to huggingface.co timed out. (connect timeout=10)')
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | Traceback (most recent call last):
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
2024-03-23 20:03:40 | ERROR | stderr |     resp = conn.urlopen(
2024-03-23 20:03:40 | ERROR | stderr |            ^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
2024-03-23 20:03:40 | ERROR | stderr |     retries = retries.increment(
2024-03-23 20:03:40 | ERROR | stderr |               ^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
2024-03-23 20:03:40 | ERROR | stderr |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-03-23 20:03:40 | ERROR | stderr |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/tokenization_chatglm.py (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe045635ad0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | Traceback (most recent call last):
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
2024-03-23 20:03:40 | ERROR | stderr |     metadata = get_hf_file_metadata(
2024-03-23 20:03:40 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2024-03-23 20:03:40 | ERROR | stderr |     return fn(*args, **kwargs)
2024-03-23 20:03:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1667, in get_hf_file_metadata
2024-03-23 20:03:40 | ERROR | stderr |     r = _request_wrapper(
2024-03-23 20:03:40 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
2024-03-23 20:03:40 | ERROR | stderr |     response = _request_wrapper(
2024-03-23 20:03:40 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
2024-03-23 20:03:40 | ERROR | stderr |     response = get_session().request(method=method, url=url, **params)
2024-03-23 20:03:40 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-03-23 20:03:40 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-03-23 20:03:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-03-23 20:03:40 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-03-23 20:03:40 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 67, in send
2024-03-23 20:03:40 | ERROR | stderr |     return super().send(request, *args, **kwargs)
2024-03-23 20:03:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
2024-03-23 20:03:40 | ERROR | stderr |     raise ConnectTimeout(e, request=request)
2024-03-23 20:03:40 | ERROR | stderr | requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/tokenization_chatglm.py (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe045635ad0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: acc36d3a-02f3-4c9b-b41f-9d556750f06b)')
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | Traceback (most recent call last):
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/transformers/utils/hub.py", line 385, in cached_file
2024-03-23 20:03:40 | ERROR | stderr |     resolved_file = hf_hub_download(
2024-03-23 20:03:40 | ERROR | stderr |                     ^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2024-03-23 20:03:40 | ERROR | stderr |     return fn(*args, **kwargs)
2024-03-23 20:03:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1406, in hf_hub_download
2024-03-23 20:03:40 | ERROR | stderr |     raise LocalEntryNotFoundError(
2024-03-23 20:03:40 | ERROR | stderr | huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-03-23 20:03:40 | ERROR | stderr | 
2024-03-23 20:03:40 | ERROR | stderr | Traceback (most recent call last):
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-03-23 20:03:40 | ERROR | stderr |     self.run()
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-03-23 20:03:40 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-03-23 20:03:40 | ERROR | stderr |   File "/ai/chatglm/Langchain-Chatchat/startup.py", line 392, in run_model_worker
2024-03-23 20:03:40 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-23 20:03:40 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/ai/chatglm/Langchain-Chatchat/startup.py", line 220, in create_model_worker_app
2024-03-23 20:03:40 | ERROR | stderr |     worker = ModelWorker(
2024-03-23 20:03:40 | ERROR | stderr |              ^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-03-23 20:03:40 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-03-23 20:03:40 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 348, in load_model
2024-03-23 20:03:40 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-03-23 20:03:40 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 816, in load_model
2024-03-23 20:03:40 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-03-23 20:03:40 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 797, in from_pretrained
2024-03-23 20:03:40 | ERROR | stderr |     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
2024-03-23 20:03:40 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 488, in get_class_from_dynamic_module
2024-03-23 20:03:40 | ERROR | stderr |     final_module = get_cached_module_file(
2024-03-23 20:03:40 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 294, in get_cached_module_file
2024-03-23 20:03:40 | ERROR | stderr |     resolved_module_file = cached_file(
2024-03-23 20:03:40 | ERROR | stderr |                            ^^^^^^^^^^^^
2024-03-23 20:03:40 | ERROR | stderr |   File "/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/transformers/utils/hub.py", line 425, in cached_file
2024-03-23 20:03:40 | ERROR | stderr |     raise EnvironmentError(
2024-03-23 20:03:40 | ERROR | stderr | OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named tokenization_chatglm.py.
2024-03-23 20:03:40 | ERROR | stderr | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
这是为什么呢

**Comment by xx59469xx** [comment]
> Hey @xx59469xx, great to see you back here! Hope you've been doing well since our last chat.
> 
> Based on the error messages you provided and the similar issues I found in the Langchain-Chatchat repository, here are some potential solutions:
> 
> 1. **Address Already in Use Error**: This error occurs when the port specified for your application is already occupied by another process. You can resolve this by either changing the port in your configuration or by finding and stopping the process that's currently using the port. To change the port, look for the `port` variable in your configuration (`FSCHAT_CONTROLLER["port"]` for the controller and similarly for other components) and assign a different port number. If you prefer to find and stop the process using the port, you can use the following commands:
>    
>    * On Linux: `lsof -i :<port_number>` to find the process and `kill -9 <PID>` to stop it.
>    * On Windows: `netstat -ano | findstr :<port_number>` to find the process and `taskkill /PID <PID> /F` to stop it.
> 2. **Cannot Locate the tokenization_chatglm.py File**: This issue indicates that the Python interpreter cannot find the specified file in its search path. Ensure that the file `tokenization_chatglm.py` exists and is located in a directory that's included in your Python path. If the file is part of a package you've developed or downloaded, make sure that package's directory is correctly added to the Python path. You can add a directory to the Python path at runtime with `sys.path.append('/path/to/directory')`.
> 3. **Connection Timeouts to huggingface.co**: This issue might be related to network problems, especially when using a VPN that might restrict or slow down your connection to certain websites. To resolve this, you can try the following:
>    
>    * Ensure your VPN is configured correctly and allows connections to huggingface.co.
>    * Temporarily disable the VPN to check if the issue persists without it. If the problem goes away, the issue is likely with the VPN's configuration.
>    * Increase the timeout setting in your HTTP client configuration. Look for the `HTTPX_DEFAULT_TIMEOUT` variable in your code and increase its value to allow more time for connections to complete.
> 
> Remember to check the logs for more detailed error messages that can provide additional clues on how to resolve these issues.
> 
> For more information, you can refer to the following issues in the Langchain-Chatchat repository that discuss similar problems:
> 
> * [启动失败](https://github.com/chatchat-space/Langchain-Chatchat/issues/3117)
> * [[BUG] 生成在python startup.py -a 之后](https://github.com/chatchat-space/Langchain-Chatchat/issues/3129)
> * [[BUG] python startup.py -a执行报错卡住--模型是本地的C:\AI\models\THUDM\chatglm3-6b](https://github.com/chatchat-space/Langchain-Chatchat/issues/3062)
> * [[BUG] 模型加载失败 报错：OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named configuration_chatglm.py.](https://github.com/chatchat-space/Langchain-Chatchat/issues/2223)
> * [[BUG] 简洁阐述问题 / Concise description of the issue](https://github.com/chatchat-space/Langchain-Chatchat/issues/3074)
> * [执行python startup.py -a 报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2937)
> 
> If these solutions do not resolve your issue, please provide more detailed information about your setup and the full error messages you are encountering.
> 
> ## Sources
> * [启动失败](https://github.com/chatchat-space/Langchain-Chatchat/issues/3117)
> * [[BUG] 生成在python startup.py -a 之后](https://github.com/chatchat-space/Langchain-Chatchat/issues/3129)
> * [[BUG] python startup.py -a执行报错卡住--模型是本地的C:\AI\models\THUDM\chatglm3-6b](https://github.com/chatchat-space/Langchain-Chatchat/issues/3062)
> * [[BUG] 模型加载失败 报错：OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named configuration_chatglm.py.](https://github.com/chatchat-space/Langchain-Chatchat/issues/2223)
> * [[BUG] 简洁阐述问题 / Concise description of the issue](https://github.com/chatchat-space/Langchain-Chatchat/issues/3074)
> * [执行python startup.py -a 报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2937)
> * [startup.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/startup.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

没用啊

**Comment by xx59469xx** [comment]
> Based on the issues you've described and the solutions you've tried, it seems like there are a few different things going on. Let's address each one:
> 
> 1. **Address Binding Error**: This error typically occurs when the port you're trying to bind to is already in use or you don't have permission to bind to it. Since you've tried changing the port without success, ensure that the new port is not in use by running `netstat -an | grep <port_number>` on Unix/Linux or `netstat -an | findstr <port_number>` on Windows. If the port is in use, choose another one. Additionally, ensure you're running your application with sufficient privileges to bind to the desired port.
> 2. **Inability to Locate the `tokenization_chatglm.py` File**: This issue suggests a problem with your project's directory structure or how Python's import system is locating your modules. Ensure that the `tokenization_chatglm.py` file is in a directory that is part of Python's search path. You can add a directory to Python's search path by appending it to the `sys.path` list:
>    ```python
>    import sys
>    sys.path.append('/path/to/directory/containing/tokenization_chatglm')
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Replace `'/path/to/directory/containing/tokenization_chatglm'` with the actual path to the directory containing the `tokenization_chatglm.py` file. This should be done before attempting to import the module.
> 3. **Connection Timeouts**: Connection timeouts can be caused by network issues, server unavailability, or misconfigurations in your VPN or HTTP client. Since you've already adjusted your VPN and HTTP client configurations, verify that the server you're trying to connect to is available and that there are no network issues between your client and the server. For HTTP client configurations, ensure that you've set appropriate timeout values. In the provided code, you're using `httpx.Client` without explicitly setting timeout values. You can set a timeout value as follows:
>    ```python
>    from httpx import Timeout
>    
>    timeout = Timeout(10.0, connect=5.0)
>    with httpx.Client(headers=headers, timeout=timeout) as client:
>        response = client.post(url, json=data)
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    This sets a total timeout of 10 seconds for the request, with a 5-second timeout for establishing a connection. Adjust these values based on your requirements and network conditions.
> 
> If these solutions do not resolve your issues, please provide additional details about the errors (e.g., error messages, stack traces) for further assistance.
> 
> Regarding your question about how Langchain-Chatchat handles port binding, I wasn't able to find specific information within the repository. However, typically, applications can bind to any available port within the valid range (0-65535), with ports below 1024 being reserved for privileged services and designated as well-known ports. It's generally recommended to use ports in the dynamic or private range (49152-65535) for custom applications to avoid conflicts with reserved ports.
> 
> For the issue related to the `tokenizer_config.json` file for the `chatglm3-6b` model, a solution suggested in a similar issue in the Langchain-Chatchat repository is to modify the `auto_map` section of the `tokenizer_config.json` file from:
> 
> ```json
>   "auto_map": {
>     "AutoTokenizer": [
>       "THUDM/chatglm3-6b--tokenization_chatglm.ChatGLMTokenizer",
>       null
>     ]
>   },
> ```
> 
> to:
> 
> ```json
>   "auto_map": {
>     "AutoTokenizer": [
>       "tokenization_chatglm.ChatGLMTokenizer",
>       null
>     ]
>   },
> ```
> 
> This change has been confirmed to be helpful by users in the discussion. You can find more details in the [issue #3074](https://github.com/chatchat-space/Langchain-Chatchat/issues/3074) in the Langchain-Chatchat repository.
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [[BUG] python startup.py -a执行报错卡住--模型是本地的C:\AI\models\THUDM\chatglm3-6b](https://github.com/chatchat-space/Langchain-Chatchat/issues/3062)
> * [[BUG] 模型加载失败 报错：OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named configuration_chatglm.py.](https://github.com/chatchat-space/Langchain-Chatchat/issues/2223)
> * [[BUG] 简洁阐述问题 / Concise description of the issue](https://github.com/chatchat-space/Langchain-Chatchat/issues/3074)
> * [server/model_workers/zhipu.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/zhipu.py)
> 
> #### About Dosu

谢谢你啊小机器人，修改tokenizer_config.json的AutoTokenizer确实起效了！
