### ISSUE TITLE
报错：API通信遇到错误

### ISSUE THREAD

**Issue by Gaki1993** [chatchat-space/Langchain-Chatchat#3515]
![peer closed connection without sending complete message body (incomplete chunked read)](https://github.com/chatchat-space/Langchain-Chatchat/assets/164276898/b721509b-b347-42aa-8960-bd4623cb394d)

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\sse_starlette\sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    await func()
  File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\sse_starlette\sse.py", line 215, in listen_for_disconnect
    message = await receive()
  File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 542, in receive
    await self.message_event.wait()
  File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1ae85161780

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 412, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\starlette\routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\sse_starlette\sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\langchain_core\prompts\string.py", line 76, in _get_jinja2_variables_from_template
    |     from jinja2 import Environment, meta
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\jinja2\__init__.py", line 8, in <module>
    |     from .environment import Environment as Environment
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\jinja2\environment.py", line 14, in <module>
    |     from markupsafe import Markup
    | ModuleNotFoundError: No module named 'markupsafe'
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    |     await func()
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\sse_starlette\sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "D:\Program Files (x86)\AI\AIG5\Langchain-Chatchat\server\chat\chat.py", line 76, in chat_iterator
    |     input_msg = History(role="user", content=prompt_template).to_msg_template(False)
    |   File "D:\Program Files (x86)\AI\AIG5\Langchain-Chatchat\server\chat\utils.py", line 32, in to_msg_template
    |     return ChatMessagePromptTemplate.from_template(
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\langchain_core\prompts\chat.py", line 196, in from_template
    |     prompt = PromptTemplate.from_template(
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\langchain_core\prompts\prompt.py", line 247, in from_template
    |     input_variables = get_template_variables(template, template_format)
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\langchain_core\prompts\string.py", line 143, in get_template_variables
    |     input_variables = _get_jinja2_variables_from_template(template)
    |   File "C:\Users\Administrator\MiniConda3\envs\py3.10.11\lib\site-packages\langchain_core\prompts\string.py", line 78, in _get_jinja2_variables_from_template
    |     raise ImportError(
    | ImportError: jinja2 not installed, which is needed to use the jinja2_formatter. Please install it with `pip install jinja2`.
    +------------------------------------
2024-03-25 20:32:35,171 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by lihengsss** [comment]
不是提示你jinja2没装吗

**Comment by Gaki1993** [comment]
> 不是提示你jinja2没装吗

感谢，已解决

**Comment by sliontc** [comment]
> > 不是提示你jinja2没装吗
> 
> 感谢，已解决

你好，你是怎么解决的？

**Comment by Gaki1993** [comment]
> > > 不是提示你jinja2没安装吗
> > 
> > 
> > 谢谢，已解决
> 
> 你好，你是怎么解决的？

装一下jinja2就行了
