### ISSUE TITLE
运行langchain-chatchat 0.2.10版本的官方demo错误

### ISSUE THREAD

**Issue by MakeWater** [chatchat-space/Langchain-Chatchat#3520]
**报错信息：**
File "/home/ftsadmin/miniconda3/envs/Langchain/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/media/ftsadmin/E/Maolongchun/LLMs/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
File "/media/ftsadmin/E/Maolongchun/LLMs/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**复现问题的步骤 / Steps to Reproduce**
1. 按照官方的操作步骤进行操作：
2. python --version, 3.11.8
3. `# 拉取仓库
$ git clone https://github.com/chatchat-space/Langchain-Chatchat.git

# 进入目录
$ cd Langchain-Chatchat

# 安装全部依赖
$ pip install -r requirements.txt 
$ pip install -r requirements_api.txt
$ pip install -r requirements_webui.txt  `

4. Langchain 版本： pip list 信息：
 `langchain                     0.0.354
langchain-community           0.0.20
langchain-core                0.1.23
langchain-experimental        0.0.47
langchain-text-splitters      0.0.1
langchainhub                  0.1.15
`
5. `$ git lfs install
$ git clone https://huggingface.co/THUDM/chatglm3-6b
$ git clone https://huggingface.co/BAAI/bge-large-zh
`
6. $ python copy_config_example.py
$ python init_database.py --recreate-vs
7. $ python startup.py -a

8.  问题出现 / Problem occurs：File "/home/ftsadmin/miniconda3/envs/Langchain/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/media/ftsadmin/E/Maolongchun/LLMs/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
File "/media/ftsadmin/E/Maolongchun/LLMs/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**预期的结果 / Expected Result**
预期可以按官方demo出现正常的界面

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/6929407/22a94bc7-e23c-4e2f-ae6f-ca2c5829db21)

**环境信息 / Environment Information**
-系统信息：Ubuntu22.04
- langchain-ChatGLM 版本/commit 号：v0.2.10 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
(Langchain) ftsadmin@ftsadmin:/media/ftsadmin/E/Maolongchun/LLMs/Langchain-Chatchat$ python startup.py -a --model-name "chatglm3-6b"

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.5.0-25-generic-x86_64-with-glibc2.35.
python版本：3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-03-26 10:44:08,990 - startup.py[line:655] - INFO: 正在启动服务：
2024-03-26 10:44:08,990 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /media/ftsadmin/E/Maolongchun/LLMs/Langchain-Chatchat/logs
/home/ftsadmin/miniconda3/envs/Langchain/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-03-26 10:44:15 | ERROR | stderr | INFO:     Started server process [46175]
2024-03-26 10:44:15 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-26 10:44:15 | ERROR | stderr | INFO:     Application startup complete.
2024-03-26 10:44:15 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20003 (Press CTRL+C to quit)
2024-03-26 10:44:16 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 8621e101 ...
Loading checkpoint shards:   0%|                                                                                                                                                                     | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|██████████████████████▍                                                                                                                                      | 1/7 [00:20<02:00, 20.07s/it]
Loading checkpoint shards:  29%|████████████████████████████████████████████▊                                                                                                                | 2/7 [00:31<01:15, 15.05s/it]
Loading checkpoint shards:  43%|███████████████████████████████████████████████████████████████████▎                                                                                         | 3/7 [00:48<01:02, 15.74s/it]
Loading checkpoint shards:  57%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                   | 4/7 [01:06<00:50, 16.90s/it]
Loading checkpoint shards:  71%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 5/7 [01:27<00:36, 18.19s/it]
Loading checkpoint shards:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 6/7 [01:27<00:12, 12.18s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:28<00:00,  8.29s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:28<00:00, 12.59s/it]
2024-03-26 10:45:44 | ERROR | stderr | 
2024-03-26 10:45:47 | INFO | model_worker | Register to controller
INFO:     Started server process [46330]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.5.0-25-generic-x86_64-with-glibc2.35.
python版本：3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20003/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2024-03-26 10:46:16,386 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('socks://127.0.0.1:7890/')
2024-03-26 10:46:16,387 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('socks://127.0.0.1:7890/')
2024-03-26 10:46:16,387 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('socks://127.0.0.1:7890/')
2024-03-26 10:46:16,490 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('socks://127.0.0.1:7890/')
2024-03-26 10:46:16,491 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('socks://127.0.0.1:7890/')
2024-03-26 10:46:16,492 - utils.py[line:95] - ERROR: ValueError: error when post /llm_model/list_running_models: Unknown scheme for proxy URL URL('socks://127.0.0.1:7890/')
2024-03-26 10:46:16.493 Uncaught app exception
Traceback (most recent call last):
  File "/home/ftsadmin/miniconda3/envs/Langchain/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/media/ftsadmin/E/Maolongchun/LLMs/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/media/ftsadmin/E/Maolongchun/LLMs/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by MakeWater** [comment]
通过关闭网络代理后，重启计算机可以成功！
