### ISSUE TITLE
非流式请求的模型，如何对接langchain-chatchat，例如qwen-vl-chat

### ISSUE THREAD

**Issue by wlllearn** [chatchat-space/Langchain-Chatchat#3525]
模型不支持流式请求，需要修改哪些参数文件
以下是报错服务信息
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.47it/s]
2024-03-26 15:45:56,893 - faiss_cache.py[line:92] - INFO: loading vector store in '分类编码树/vector_store/bge-large-zh-v1.5' from disk.
/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(
2024-03-26 15:45:56,905 - _client.py[line:1758] - INFO: HTTP Request: POST http://192.168.2.49:5002/v1/chat/completions "HTTP/1.1 400 Bad Request"
2024-03-26 15:45:56,906 - utils.py[line:38] - ERROR: Error code: 400 - {'detail': 'Stream request is not supported currently.'}
Traceback (most recent call last):
  File "/home/liupin/workspace/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 105, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1300, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/openai/_base_client.py", line 1703, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/openai/_base_client.py", line 1406, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/liupin/miniconda3/envs/langchain/lib/python3.11/site-packages/openai/_base_client.py", line 1497, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'detail': 'Stream request is not supported currently.'}
2024-03-26 15:45:56,907 - utils.py[line:40] - ERROR: BadRequestError: Caught exception: Error code: 400 - {'detail': 'Stream request is not supported currently.'}

**Comment by glide-the** [comment]
目前3.0在多模态业务处于设计阶段，您的需求已加入开发计划，您可以在dev分支查看目前的成果
https://github.com/chatchat-space/Langchain-Chatchat/issues/2661
