### ISSUE TITLE
[BUG] 使用/upload_temp_docs上传pdf时，报错numpy.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by SolarKnight1** [chatchat-space/Langchain-Chatchat#3527]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

使用/upload_temp_docs上传pdf时，报错numpy.AxisError: axis 1 is out of bounds for array of dimension 1
且请求报错500

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'： python startup.py -a
2. 点击 '...' / Click '...':    使用/upload_temp_docs上传pdf文件，出现Upload failed with status code 500: Internal Server Error
3. 滚动到 '...' / Scroll to '...' ：   在服务上报错numpy.AxisError: axis 1 is out of bounds for array of dimension 1

且我在issue看到了之前的别人的问题，我看说要安装libglib2.0-0 libgl1-mesa-glx
但我确实已经装了
libgl1-mesa-glx is already the newest version (18.0.5-0ubuntu0~16.04.1).
libglib2.0-0 is already the newest version (2.48.2-0ubuntu4.8).

完整报错

2024-03-26 17:25:41,645 - utils.py[line:295] - INFO: RapidOCRPDFLoader used for /tmp/chatchat/tmpkszfuhhv/渤
海人寿 安康 e 生 B 款 重大疾病保险.pdf
2024-03-26 17:25:42,163 - faiss_cache.py[line:127] - INFO: loading vector store in 'tmpkszfuhhv' to memory.
Batches: 100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.95it/s]
Batches: 0it [00:00, ?it/s]
INFO:     115.236.165.162:6708 - "POST /knowledge_base/upload_temp_docs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line
419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/software/anaconda3/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, i
n __call__
    return await self.app(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call_
_
    await self.middleware_stack(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __
call__
    raise exc
File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __
call__
    await self.app(scope, receive, _send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in
 __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wr
apped_app
    raise exc
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wr
apped_app
    await app(scope, receive, sender)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wr
apped_app
    raise exc
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wr
apped_app
    await app(scope, receive, sender)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_f
unction
    return await run_in_threadpool(dependant.call, **values)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_th
readpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/data/software/anaconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/software/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_s
ync_in_worker_thread
return await future
  File "/data/software/anaconda3/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/data/software/anaconda3/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/data/software/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/data/software/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/chat/file_chat.py", line 88, in upload_temp_docs
    vs.add_documents(documents)
  File "/data/software/anaconda3/lib/python3.9/site-packages/langchain_core/vectorstores.py", line 119, in ad
d_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/data/software/anaconda3/lib/python3.9/site-packages/langchain_community/vectorstores/faiss.py", line
 225, in add_texts
    embeddings = self._embed_documents(texts)
  File "/data/software/anaconda3/lib/python3.9/site-packages/langchain_community/vectorstores/faiss.py", line
 137, in _embed_documents
    return self.embedding_function.embed_documents(texts)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 439, in e
mbed_documents
    return normalize(embeddings).tolist()
File "/home/wyxx/warBackup/ner/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in no
rmalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "/data/software/anaconda3/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 2542, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by Chrosea** [comment]
这个问题根本没解决啊，我这边也复现了，为什么关闭了呢？
