### ISSUE TITLE
[BUG] 在对接milvus初始化向量数据库时出错

### ISSUE THREAD

**Issue by MuuuShin** [chatchat-space/Langchain-Chatchat#3532]
**问题描述 / Problem Description**
在对接milvus初始化向量数据库时出错.首先是报了AssertionError: A list of valid ids are required when auto_id is False.

尝试寻找issue( https://github.com/chatchat-space/Langchain-Chatchat/issues/3180 , https://github.com/chatchat-space/Langchain-Chatchat/issues/2999 等) 发现可以添加一行`auto_id=True`在`server/knowledge_base/kb_service/milvus_kb_service.py` 去避免这个报错

但是会报另一个错,报错信息如下:
<details>
<summary>
报错详情
</summary>
(前略)
2024-03-26 19:18:34,229 - tokenization_chatglm.py[line:164] - WARNING: Setting eos_token is not supported, use the default one.
2024-03-26 19:18:34,229 - tokenization_chatglm.py[line:160] - WARNING: Setting pad_token is not supported, use the default one.
2024-03-26 19:18:34,229 - tokenization_chatglm.py[line:156] - WARNING: Setting unk_token is not supported, use the default one.
文档切分示例：page_content='ChatGPT是OpenAI开发的一个大型语言模型，可以提供各种主题的信息，\n# 如何向 ChatGPT 提问以获得高质量答案：提示技巧工程完全指南\n## 介绍\n我很高兴欢迎您阅读我的最新书籍《The Art of Asking ChatGPT for High-Quality Answers: A complete Guide to Prompt Engineering Techniques》。本书是一本全面指南，介绍了各种提示技术，用于从ChatGPT中生成高质量的答案。\n我们将探讨如何使用不同的提示工程技术来实现不同的目标。ChatGPT是一款最先进的语言模型，能够生成类似人类的文本。然而，理解如何正确地向ChatGPT提问以获得我们所需的高质量输出非常重要。而这正是本书的目的。' metadata={'source': '/data/bch/LLM/Langchain-Chatchat/knowledge_base/samples/content/test_files/test.txt'}
2024-03-26 19:18:34,833 - tokenization_chatglm.py[line:164] - WARNING: Setting eos_token is not supported, use the default one.
2024-03-26 19:18:34,834 - tokenization_chatglm.py[line:160] - WARNING: Setting pad_token is not supported, use the default one.
2024-03-26 19:18:34,834 - tokenization_chatglm.py[line:156] - WARNING: Setting unk_token is not supported, use the default one.
文档切分示例：page_content='See discussions, stats, and author profiles for this publication at: https://www.researchgate.net/publication/372669736\nCreating Large Language Model Applications Utilizing LangChain: A Primer on\nDeveloping LLM Apps Fast\nArticle\xa0\xa0in\xa0\xa0International Conference on Applied Engineering and Natural Sciences · July 2023\nDOI: 10.59287/icaens.1127\nCITATIONS\n0\nREADS\n47\n2 authors:\nSome of the authors of this publication are also working on these related projects:\nTHALIA: Test Harness for the Assessment of Legacy Information Integration Approaches View project\nAnalysis of Feroresonance with Signal Processing Technique View project\nOguzhan Topsakal' metadata={'source': '/data/bch/LLM/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain.pdf'}
2024-03-26 19:18:35,221 - tokenization_chatglm.py[line:164] - WARNING: Setting eos_token is not supported, use the default one.
2024-03-26 19:18:35,222 - tokenization_chatglm.py[line:160] - WARNING: Setting pad_token is not supported, use the default one.
2024-03-26 19:18:35,222 - tokenization_chatglm.py[line:156] - WARNING: Setting unk_token is not supported, use the default one.
文档切分示例：page_content='BoolQ\nPIQA\nSIQA\nHella-Swag\nARC-e\nARC-c\nNQ\nTQA\nMMLU\nGSM8K\nHuman-Eval\nMHA\n71.0\n79.3\n48.2\n75.1\n71.2\n43.0\n12.4\n44.7\n28.0\n4.9\n7.9\nMQA\n70.6' metadata={'source': '/data/bch/LLM/Langchain-Chatchat/knowledge_base/samples/content/llm/img/大模型推理优化策略-幕布图片-930255-616209.jpg'}
Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.50it/s]
2024-03-26 19:18:38,421 - decorators.py[line:139] - ERROR: RPC error: [create_index], <MilvusException: (code=65535, message=efConstruction out of range: [1, 2147483647])>, <Time:{'RPC start': '2024-03-26 19:18:38.416343', 'RPC error': '2024-03-26 19:18:38.421167'}>
Traceback (most recent call last):
  File "/data/bch/LLM/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 131, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 84, in do_add_doc
    ids = self.milvus.add_documents(docs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 586, in add_texts
    insert_list = [insert_dict[x][i:end] for x in self.fields]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 586, in <listcomp>
    insert_list = [insert_dict[x][i:end] for x in self.fields]
                   ~~~~~~~~~~~^^^
KeyError: 'pk'
</details>


**复现问题的步骤 / Steps to Reproduce**
1.修改对应配置
2.执行`python init_database.py --recreate-vs`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署：否
- 使用的模型：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM3-6B
- 使用的 Embedding 模型: bge-large-zh
- 使用的向量库类型 : milvus
- 操作系统及版本 / Operating system and version: 20.04.1-Ubuntu
- Python 版本 / Python version: 3.11.7

**Comment by MuuuShin** [comment]
@dosu-bot 可是不加auto_id 的话 报错AssertionError: A list of valid ids are required when auto_id is False.

**Comment by MuuuShin** [comment]
@dosu-bot 不加auto_id 的报错

<details>
<summary>
报错详情
</summary>

```
2024-03-26 21:05:38,246 - tokenization_chatglm.py[line:164] - WARNING: Setting eos_token is not supported, use the default one.
2024-03-26 21:05:38,246 - tokenization_chatglm.py[line:160] - WARNING: Setting pad_token is not supported, use the default one.
2024-03-26 21:05:38,246 - tokenization_chatglm.py[line:156] - WARNING: Setting unk_token is not supported, use the default one.
文档切分示例：page_content='See discussions, stats, and author profiles for this publication at: https://www.researchgate.net/publication/372669736\nCreating Large Language Model Applications Utilizing LangChain: A Primer on\nDeveloping LLM Apps Fast\nArticle\xa0\xa0in\xa0\xa0International Conference on Applied Engineering and Natural Sciences · July 2023\nDOI: 10.59287/icaens.1127\nCITATIONS\n0\nREADS\n47\n2 authors:\nSome of the authors of this publication are also working on these related projects:\nTHALIA: Test Harness for the Assessment of Legacy Information Integration Approaches View project\nAnalysis of Feroresonance with Signal Processing Technique View project\nOguzhan Topsakal' metadata={'source': '/data/bch/LLM/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain.pdf'}
Traceback (most recent call last):
  File "/data/bch/LLM/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 131, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 83, in do_add_doc
    ids = self.milvus.add_documents(docs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 520, in add_texts
    assert isinstance(
AssertionError: A list of valid ids are required when auto_id is False.
```

</details>

**Comment by MuuuShin** [comment]
@dosu-bot 根据你给我的回复进行修改后的代码报错



Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.63it/s]
2024-03-26 21:21:06,995 - decorators.py[line:139] - ERROR: RPC error: [create_index], <MilvusException: (code=65535, message=efConstruction out of range: [1, 2147483647])>, <Time:{'RPC start': '2024-03-26 21:21:06.989450', 'RPC error': '2024-03-26 21:21:06.995058'}>
2024-03-26 21:21:10,056 - decorators.py[line:139] - ERROR: RPC error: [batch_insert], <ParamError: (code=1, message=('Field data size misaligned for field [text] ', 'got size=[1000] ', 'alignment size=[969]'))>, <Time:{'RPC start': '2024-03-26 21:21:10.054082', 'RPC error': '2024-03-26 21:21:10.056043'}>
2024-03-26 21:21:10,056 - milvus.py[line:593] - ERROR: Failed to insert batch starting at entity: 0/1292
Traceback (most recent call last):
  File "/data/bch/LLM/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 131, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/LLM/Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 92, in do_add_doc
    ids = self.milvus.add_documents(docs, ids=doc_ids)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 596, in add_texts
    raise e
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 590, in add_texts
    res = self.col.insert(insert_list, timeout=timeout, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 497, in insert
    res = conn.batch_insert(
          ^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/decorators.py", line 140, in handler
    raise e from e
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/decorators.py", line 136, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/decorators.py", line 175, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/decorators.py", line 115, in handler
    raise e from e
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 575, in batch_insert
    raise err from err
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 558, in batch_insert
    request = self._prepare_batch_insert_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 542, in _prepare_batch_insert_request
    else Prepare.batch_insert_param(collection_name, entities, partition_name, fields_info)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 528, in batch_insert_param
    return cls._parse_batch_request(request, entities, fields_info, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bch/miniconda3/envs/LLMEnv/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 496, in _parse_batch_request
    raise ParamError(
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=('Field data size misaligned for field [text] ', 'got size=[1000] ', 'alignment size=[969]'))>

**Comment by MuuuShin** [comment]
另外需要加上auto_id=True

**Comment by Wangzhongxi** [comment]
> 尝试调了一下,主要涉及到的包langchain, langchain_core和langchain_community 都重装一下试一试各个版本,我这边全部卸了又重装了几次莫名好了,希望能帮到后面的人

每一个版本是多少哇，可以告知一下嘛

**Comment by MuuuShin** [comment]
> > 尝试调了一下,主要涉及到的包langchain, langchain_core和langchain_community 都重装一下试一试各个版本,我这边全部卸了又重装了几次莫名好了,希望能帮到后面的人
> 
> 每一个版本是多少哇，可以告知一下嘛

langchain                     0.0.354
langchain-community           0.0.20
langchain-core                0.1.23

**Comment by 1986smalltiger** [comment]
langchain 0.0.354
langchain-community 0.0.20
langchain-core 0.1.23
确实是版本的原因，不过也需要添加auto_id=True的配置

**Comment by 1431551850** [comment]
> langchain 0.0.354 langchain-community 0.0.20 langchain-core 0.1.23 确实是版本的原因，不过也需要添加auto_id=True的配置

ModuleNotFoundError: No module named 'pwd'0.0.20会报错

**Comment by MuuuShin** [comment]
> > langchain 0.0.354 langchain-community 0.0.20 langchain-core 0.1.23 确实是版本的原因，不过也需要添加auto_id=True的配置
> ModuleNotFoundError: No module named 'pwd'0.0.20会报错

搜一搜其他issue哦，我印象里好像看到过这个错

**Comment by utopia2077** [comment]
解决方法：langchain-community降级到0.0.16
参考：https://github.com/langchain-ai/langchain/issues/17172

**Comment by zfishbone01** [comment]
langchain-community 由0.0.19升级到0.0.20，修复了bug，insert_list = [insert_dict[x][i:end] for x in self.fields] ->             insert_list = [
                insert_dict[x][i:end] for x in self.fields if x in insert_dict
            ]
