### ISSUE TITLE
[BUG] 启动项目时报错

### ISSUE THREAD

**Issue by ganhy1218** [chatchat-space/Langchain-Chatchat#3533]
报错内容是这个样子

 'api_key': 'EMPTY',
 'local_model_path': '../model/basic'}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-03-26 20:34:09 | ERROR | stderr | INFO:     Started server process [31267]
2024-03-26 20:34:09 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-26 20:34:09 | ERROR | stderr | INFO:     Application startup complete.
2024-03-26 20:34:09 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
The repository for ../model/basic contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/../model/basic.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] Process model_worker - 电信导览大模型:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 599, in resolve_trust_remote_code
    answer = input(
EOFError: EOF when reading a line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/data/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    worker = ModelWorker(
  File "/root/anaconda3/envs/pytorch/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 213, in __init__
    self.model, self.tokenizer = load_model(
  File "/root/anaconda3/envs/pytorch/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 279, in load_model
    model, tokenizer = adapter.load_model(model_path, kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 74, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1141, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/root/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 612, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for ../model/basic contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/../model/basic.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.

**Comment by zRzRzRzRzRzRzR** [comment]
trust_remote_code=True 模型没有成功读入，检查模型或者检查你的权限

**Comment by TC10127** [comment]
请问楼主问题解决了吗
