### ISSUE TITLE
启动时出现报错： AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

### ISSUE THREAD

**Issue by ysyx2008** [chatchat-space/Langchain-Chatchat#3556]
**问题描述 / Problem Description**
启动时出现报错：
AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

**复现问题的步骤 / Steps to Reproduce**
1. 按要求部署环境，并配置ChatGLM2-6B模型绝对地址
2. 执行python startup.py -a 出现以下报错信息：
(langchain) yushen@YuShen-Work:~/ai/Langchain-Chatchat$ python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/yushen/ai/chatglm2-6b-model',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-03-28 14:26:33,565 - startup.py[line:655] - INFO: 正在启动服务：
2024-03-28 14:26:33,565 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /home/yushen/ai/Langchain-Chatchat/logs
/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-03-28 14:26:37 | ERROR | stderr | INFO:     Started server process [57299]
2024-03-28 14:26:37 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-28 14:26:37 | ERROR | stderr | INFO:     Application startup complete.
2024-03-28 14:26:37 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-03-28 14:26:38 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker b8516093 ...
2024-03-28 14:26:38 | ERROR | stderr | Process model_worker - chatglm2-6b:
2024-03-28 14:26:38 | ERROR | stderr | Traceback (most recent call last):
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-03-28 14:26:38 | ERROR | stderr |     self.run()
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-03-28 14:26:38 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/ai/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-03-28 14:26:38 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-28 14:26:38 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/ai/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-03-28 14:26:38 | ERROR | stderr |     worker = ModelWorker(
2024-03-28 14:26:38 | ERROR | stderr |              ^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-03-28 14:26:38 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-03-28 14:26:38 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 348, in load_model
2024-03-28 14:26:38 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-03-28 14:26:38 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 823, in load_model
2024-03-28 14:26:38 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-03-28 14:26:38 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 822, in from_pretrained
2024-03-28 14:26:38 | ERROR | stderr |     return tokenizer_class.from_pretrained(
2024-03-28 14:26:38 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2086, in from_pretrained
2024-03-28 14:26:38 | ERROR | stderr |     return cls._from_pretrained(
2024-03-28 14:26:38 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2325, in _from_pretrained
2024-03-28 14:26:38 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-03-28 14:26:38 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/.cache/huggingface/modules/transformers_modules/chatglm2-6b-model/tokenization_chatglm.py", line 69, in __init__
2024-03-28 14:26:38 | ERROR | stderr |     super().__init__(padding_side=padding_side, **kwargs)
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 367, in __init__
2024-03-28 14:26:38 | ERROR | stderr |     self._add_tokens(
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/micromamba/envs/langchain/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
2024-03-28 14:26:38 | ERROR | stderr |     current_vocab = self.get_vocab().copy()
2024-03-28 14:26:38 | ERROR | stderr |                     ^^^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/.cache/huggingface/modules/transformers_modules/chatglm2-6b-model/tokenization_chatglm.py", line 99, in get_vocab
2024-03-28 14:26:38 | ERROR | stderr |     vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
2024-03-28 14:26:38 | ERROR | stderr |                                                             ^^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr |   File "/home/yushen/.cache/huggingface/modules/transformers_modules/chatglm2-6b-model/tokenization_chatglm.py", line 95, in vocab_size
2024-03-28 14:26:38 | ERROR | stderr |     return self.tokenizer.n_words
2024-03-28 14:26:38 | ERROR | stderr |            ^^^^^^^^^^^^^^
2024-03-28 14:26:38 | ERROR | stderr | AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 操作系统及版本 / Operating system and version: Wsl2 Ubuntu
- Python 版本 / Python version:3.11

**Comment by zRzRzRzRzRzRzR** [comment]
更新最新的chatglm3-6b huggingface仓库的代码

**Comment by ysyx2008** [comment]
改为调用ollama的API了，相当丝滑~ 感谢。

**Comment by Elon1997** [comment]
多谢
