### ISSUE TITLE
知识库无法回答

### ISSUE THREAD

**Issue by LuYaoMarvh** [chatchat-space/Langchain-Chatchat#3567]
<img width="936" alt="Snipaste_2024-03-29_10-49-10" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/140768469/848d74fe-5015-41b4-a83d-e1d5273d0b37">
使用知识库问答时
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/140768469/4ae9b46a-3698-4d09-a80b-7a44827aab92)

**Comment by LuYaoMarvh** [comment]
错误是NotFound错误： 无法在“节点”上执行“removeChild”：要删除的节点不是该节点的子节点。
at Ss (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:2248546)
at Cl (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:2260336)
at t.unstable_runWithPriority (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:3040959)
at Ho (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:2203377)
at kl (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:2258294)
at gl (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:2254380)
at http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:2203600
at t.unstable_runWithPriority (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:3040959)
at Ho (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:2203377)
at Ko (http://127.0.0.1:8501/static/js/main.3ab8e8d9.js:2:2203545)
