### ISSUE TITLE
在使用API添加文件到向量库时出错

### ISSUE THREAD

**Issue by SSTato** [chatchat-space/Langchain-Chatchat#3590]
使用的是gpu版本的rapidocr_paddle，报错如下：

RapidOCRPDFLoader context page index: 5:  10%|█         | 5/50 [00:15<01:44,  2.32s/it][A[A[A[A[A[A[A
RapidOCRPDFLoader context page index: 8: 100%|██████████| 9/9 [00:53<00:00,  5.92s/it]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   mupdf::FzDocument::~FzDocument()
1   mupdf::ll_fz_drop_document(fz_document*)
2   fz_drop_document
3   pdf_drop_obj

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1711952055 (unix time) try "date -d @1711952055" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x5c002b00) received by PID 128213 (TID 0x7f64b3eff700) from PID 1543514880 ***]

2024-04-01 14:17:04,769 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 14:17:04,769 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 14:17:04,770 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 14:17:04,875 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 14:17:04,876 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 14:17:04,878 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 14:17:04.878 Uncaught app exception
Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/chat-0.2.10/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/llm/Chatchat-0.2.10/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/llm/Chatchat-0.2.10/webui_pages/dialogue/dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by SSTato** [comment]
RapidOCRPDFLoader在多线程的情况下会出现上面的问题，单线程没有问题(max_workers=1)，但是速度降低了，这个该怎么解决
```
def run_in_thread_pool(
        func: Callable,
        params: List[Dict] = [],
) -> Generator:
’ ‘ ’
    在线程池中批量运行任务，并将运行结果以生成器的形式返回。
    请确保任务中的所有操作是线程安全的，任务函数请全部使用关键字参数。
    '''
    tasks = []
    with ThreadPoolExecutor(max_workers=1) as pool:
        for kwargs in params:
            thread = pool.submit(func, **kwargs)
            tasks.append(thread)

        for obj in as_completed(tasks):
            yield obj.result()
```
