### ISSUE TITLE
如何加载本地微调后的模型运行startup.py

### ISSUE THREAD

**Issue by WSC741606** [chatchat-space/Langchain-Chatchat#3599]
我在本地训练了一个基于yi-6b-chat的模型，运行python3 startup.py -a -n "/path/yi-SFTModel0-chat/"报错如下
```
2024-04-01 16:53:30 | ERROR | stderr | INFO:     Started server process [29967]
2024-04-01 16:53:30 | ERROR | stderr | INFO:     Waiting for application startup.
2024-04-01 16:53:30 | ERROR | stderr | INFO:     Application startup complete.
2024-04-01 16:53:30 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-04-01 16:53:31 | INFO | model_worker | Loading the model ['/data/home/user/Test/SwiftLog/yi-SFTModel0-chat/'] on worker e8278bc0 ...
2024-04-01 16:53:31 | ERROR | stderr | Process model_worker - /data/home/user/Test/SwiftLog/yi-SFTModel0-chat/:
2024-04-01 16:53:31 | ERROR | stderr | Traceback (most recent call last):
2024-04-01 16:53:31 | ERROR | stderr |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-04-01 16:53:31 | ERROR | stderr |     self.run()
2024-04-01 16:53:31 | ERROR | stderr |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-04-01 16:53:31 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-04-01 16:53:31 | ERROR | stderr |   File "/data/home/user/Test/GitLibrary/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-04-01 16:53:31 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-04-01 16:53:31 | ERROR | stderr |   File "/data/home/user/Test/GitLibrary/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-04-01 16:53:31 | ERROR | stderr |     worker = ModelWorker(
2024-04-01 16:53:31 | ERROR | stderr |   File "/data/home/user/Test/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-04-01 16:53:31 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-04-01 16:53:31 | ERROR | stderr |   File "/data/home/user/Test/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 261, in load_model
2024-04-01 16:53:31 | ERROR | stderr |     raise ValueError(f"Invalid device: {device}")
2024-04-01 16:53:31 | ERROR | stderr | ValueError: Invalid device: auto
```
我希望像加载yi-6b-chat一样加载她，并且支持自动的device_map以实现单机多卡推理
我应该怎么用startup.py？

**Comment by WSC741606** [comment]
应该是环境问题，我新建虚拟环境重装了项目解决了

**Comment by WSC741606** [comment]
python3 startup.py -a --model-name Yi-SFTModel0-Chat
