### ISSUE TITLE
[BUG] 向量数据库，选择pg的话，需要设置哪些地方

### ISSUE THREAD

**Issue by gz-simon** [chatchat-space/Langchain-Chatchat#3602]
**问题描述 / Problem Description**
kbs_config设置了使用的向量数据库，目前可以选择

faiss: 使用faiss数据库，需要安装faiss-gpu
milvus: 使用milvus数据库，需要安装milvus并进行端口配置
pg: 使用pg数据库，需要配置connection_uri

**复现问题的步骤 / Steps to Reproduce**

# 默认使用的知识库
DEFAULT_KNOWLEDGE_BASE = "samples"

# 默认向量库/全文检索引擎类型。可选：faiss, milvus(离线) & zilliz(在线), pgvector, chromadb 全文检索引擎es
DEFAULT_VS_TYPE = "pgvector"

# 缓存向量库数量（针对FAISS）
CACHED_VS_NUM = 1

# 缓存临时向量库数量（针对FAISS），用于文件对话
CACHED_MEMO_VS_NUM = 10

**实际结果 / Actual Result**
recreating all vector stores
Traceback (most recent call last):
  File "/mnt/workspace/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/migrate.py", line 119, in folder2db
    kb = KBServiceFactory.get_service(kb_name, vs_type, embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 304, in get_service
    vector_store_type = getattr(SupportedVSType, vector_store_type.upper())
AttributeError: type object 'SupportedVSType' has no attribute 'PGVECTOR'
(base) root@dsw-338768-98b58b74c-vs88t:/mnt/workspace/Langchain-Chatchat#

**Comment by gz-simon** [comment]
Traceback (most recent call last):
  File "/mnt/workspace/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/migrate.py", line 119, in folder2db
    kb = KBServiceFactory.get_service(kb_name, vs_type, embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 310, in get_service
    return PGKBService(kb_name, embed_model=embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 64, in __init__
    self.do_init()
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 39, in do_init
    self._load_pg_vector()
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 23, in _load_pg_vector
    self.pg_vector = PGVector(embedding_function=EmbeddingsFunAdapter(self.embed_model),
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 212, in __init__
    self.__post_init__()
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 218, in __post_init__
    self.create_vector_extension()
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 256, in create_vector_extension
    raise Exception(f"Failed to create vector extension: {e}") from e
Exception: Failed to create vector extension: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

**Comment by gz-simon** [comment]
> 嘿@gz-simon，很高兴再次在这里见到你！希望您已准备好带着这个问题回到数字领域。 🚀
> 
> 根据您提供的错误消息，问题似乎与`SupportedVSType`没有属性“PGVECTOR”的对象有关。 Langchain-Chachat 代码库中的对象`SupportedVSType`用于指定支持或正在使用的向量存储类型。它不包括“PGVECTOR”作为属性。这是它的结构：
> 
> ```python
> class SupportedVSType:
>     FAISS = 'faiss'
>     MILVUS = 'milvus'
>     DEFAULT = 'default'
>     ZILLIZ = 'zilliz'
>     PG = 'pg'
>     ES = 'es'
>     CHROMADB = 'chromadb'
> ```
> 
> （来源：[server/knowledge_base/kb_service/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py)）
> 
> 要正确配置 Langchain-Chachat 以使用 PostgreSQL 数据库作为向量存储并解决错误“AttributeError: type object 'SupportedVSType' has no attribute 'PGVECTOR'”，您应该在配置文件中将`DEFAULT_VS_TYPE`from更改`"faiss"`为。`"pg"`此更改是必要的，因为 PostgreSQL 的配置位于字典`"pg"`中的键下`kbs_config`，而不是`"pgvector"`从错误消息中推断出的。
> 
> 这是您需要更改的具体行：
> 
> ```python
> DEFAULT_VS_TYPE = "pg"
> ```
> 
> （来源：[configs/kb_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/kb_config.py.example)）
> 
> `DEFAULT_VS_TYPE`此调整将与字典中的可用键对齐`kbs_config`，特别针对您在 下设置的 PostgreSQL 配置`"pg"`。
> 
> 如果进行此更改后仍然遇到问题，请提供有关 PostgreSQL 配置以及迄今为止所采取的步骤的更多详细信息。这将有助于进一步诊断问题。
> 
> ## 来源
> * [PG数据库配置后创建提供库报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2554)
> * [[BUG] 创建知识库-提供类型除了 faiss 都报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/1336)
> * [配置/kb_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/kb_config.py.example)
> * [服务器/knowledge_base/kb_service/pg_kb_service.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/pg_kb_service.py)
> * [服务器/knowledge_base/kb_service/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py)
> 
> #### 关于多苏

Traceback (most recent call last):
  File "/mnt/workspace/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/migrate.py", line 119, in folder2db
    kb = KBServiceFactory.get_service(kb_name, vs_type, embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 310, in get_service
    return PGKBService(kb_name, embed_model=embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 64, in __init__
    self.do_init()
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 39, in do_init
    self._load_pg_vector()
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 23, in _load_pg_vector
    self.pg_vector = PGVector(embedding_function=EmbeddingsFunAdapter(self.embed_model),
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 212, in __init__
    self.__post_init__()
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 218, in __post_init__
    self.create_vector_extension()
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 256, in create_vector_extension
    raise Exception(f"Failed to create vector extension: {e}") from e
Exception: Failed to create vector extension: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

**Comment by gz-simon** [comment]
@dosu-bot (base) root@dsw-338768-98b58b74c-vs88t:/mnt/workspace/Langchain-Chatchat# python init_database.py --recreate-vs
recreating all vector stores
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/conda/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 253, in create_vector_extension
    session.execute(statement)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2431, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/conda/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/workspace/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/migrate.py", line 119, in folder2db
    kb = KBServiceFactory.get_service(kb_name, vs_type, embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 310, in get_service
    return PGKBService(kb_name, embed_model=embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 64, in __init__
    self.do_init()
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 39, in do_init
    self._load_pg_vector()
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 23, in _load_pg_vector
    self.pg_vector = PGVector(embedding_function=EmbeddingsFunAdapter(self.embed_model),
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 212, in __init__
    self.__post_init__()
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 218, in __post_init__
    self.create_vector_extension()
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 256, in create_vector_extension
    raise Exception(f"Failed to create vector extension: {e}") from e
Exception: Failed to create vector extension: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

**Comment by gz-simon** [comment]
@dosu-bot  (base) root@dsw-338768-98b58b74c-vs88t:/mnt/workspace/Langchain-Chatchat# python init_database.py --recreate-vs
recreating all vector stores
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/conda/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 253, in create_vector_extension
    session.execute(statement)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2431, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/conda/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/workspace/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/migrate.py", line 119, in folder2db
    kb = KBServiceFactory.get_service(kb_name, vs_type, embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 310, in get_service
    return PGKBService(kb_name, embed_model=embed_model)
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 64, in __init__
    self.do_init()
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 39, in do_init
    self._load_pg_vector()
  File "/mnt/workspace/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 23, in _load_pg_vector
    self.pg_vector = PGVector(embedding_function=EmbeddingsFunAdapter(self.embed_model),
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 212, in __init__
    self.__post_init__()
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 218, in __post_init__
    self.create_vector_extension()
  File "/opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/pgvector.py", line 256, in create_vector_extension
    raise Exception(f"Failed to create vector extension: {e}") from e
Exception: Failed to create vector extension: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?  @dosu-bot
