### ISSUE TITLE
webui 启动报错，对话界面报错

### ISSUE THREAD

**Issue by huitao2018** [chatchat-space/Langchain-Chatchat#3603]
操作系统：Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
python版本：3.9.10 (main, Mar 28 2024, 11:41:54) 
项目版本：v0.2.10
langchain版本：0.1.5. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/numax/langchain-Chatchat/Langchain-Chatchat/model/chatglm3-6b-int4',
 'model_path_exists': True,
 'port': 20002}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda

服务端运行信息：
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  Git integration is disabled.

  Streamlit requires Git 2.7.0 or later, but you have 1.8.3.1.
  Git is used by Streamlit Cloud (https://streamlit.io/cloud).
  To enable this feature, please update Git.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

打开界面，报错如下：

/usr/local/python3/lib/python3.9/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/usr/local/python3/lib/python3.9/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import OpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/usr/local/python3/lib/python3.9/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
/usr/local/python3/lib/python3.9/site-packages/langchain/document_loaders/__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.document_loaders import JSONLoader`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
2024-04-01 17:55:44,829 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 17:55:44,830 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 17:55:44,830 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 17:55:44,937 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 17:55:44,938 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 17:55:44,940 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-04-01 17:55:44.940 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/numax/langchain-Chatchat/Langchain-Chatchat/webui.py", line 61, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/numax/langchain-Chatchat/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
TypeError: 'NoneType' object is not iterable
2024-04-01 17:56:29,561 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-04-01 17:56:29,561 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-04-01 17:56:29,561 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-04-01 17:56:29.561 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/numax/langchain-Chatchat/Langchain-Chatchat/webui.py", line 61, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/numax/langchain-Chatchat/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 328, in knowledge_base_page
    data = [
  File "/home/numax/langchain-Chatchat/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
TypeError: string indices must be integers

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/165660614/5b90fa4b-b7e2-4fba-8350-82fd2ac55961)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/165660614/ca58f16d-4a4d-4b14-ab66-3edbad26bfb4)

**Comment by zRzRzRzRzRzRzR** [comment]
依赖对吗，感觉依赖没装对
