### ISSUE TITLE
[BUG] 运行python init_database.py --recreate-vs报错

### ISSUE THREAD

**Issue by bluefish-08** [chatchat-space/Langchain-Chatchat#3612]
**实际结果 / Actual Result**
oot@hdkj-B760M-AORUS-ELITE-AX-DDR4:/opt/Langchain-Chatchat# python3 init_database.py --recreate-vs
recreating all vector stores
2024-04-02 14:18:05,863 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh-v1.5' from disk.
2024-04-02 14:18:05,960 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5
2024-04-02 14:18:06,227 - embeddings_api.py[line:39] - ERROR: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: 2063036c-dcb6-429c-8b26-53e3038b1640)')
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/opt/Langchain-Chatchat/server/knowledge_base/migrate.py", line 121, in folder2db
    kb.create_kb()
  File "/opt/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 81, in create_kb
    self.do_create_kb()
  File "/opt/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "/opt/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "/opt/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 102, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "/opt/Langchain-Chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 60, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/vectorstores/faiss.py", line 965, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "/opt/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 439, in embed_documents
    return normalize(embeddings).tolist()
  File "/opt/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "/usr/local/lib/python3.10/dist-packages/numpy/linalg/linalg.py", line 2541, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by bluefish-08** [comment]
没有效果

**Comment by bluefish-08** [comment]
> 换python版本为311，我是这样解决的

难蚌 我现在连不上huggingface.co

**Comment by Lu0Key** [comment]
> > 换python版本为311，我是这样解决的
> 
> 难蚌 我现在连不上huggingface.co

这个网站现在被墙了捏

**Comment by mmyhs** [comment]
Is there a better way? I tried that. It didn't work

**Comment by SupremeJulyan** [comment]
> 换python版本为311，我是这样解决的

我用的3.11.7报的这个错，请问你用的是3.11.几？

**Comment by zRzRzRzRzRzRzR** [comment]
这个是模型没下全啊，embedding模型没找到

**Comment by buchidonggua** [comment]
我刚刚解决了，困扰了我半小时，以至于现在快1点了都没睡。
configs/model_config.py中的llm模型和Embedding模型地址要指派正确。
1. EMBEDDING_MODEL = "bge-large-zh" （填你使用的Embedding模型名字）
2. LLM_MODELS = ["chatglm3-6b", "zhipu-api", "openai-api"] （填你使用的llm模型名字，我是chatglm3-6b）
3. MODEL_PATH中，找到bge-large-zh、chatglm3-6b，填你下载的模型的绝对地址。

**Comment by buchidonggua** [comment]
新的问题了，不知道初始化数据库要多久，我困死了……
