### ISSUE TITLE
[BUG] 启动时报错

### ISSUE THREAD

**Issue by chinesecalvin8282** [chatchat-space/Langchain-Chatchat#3617]
之前一切正常，直到……
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:11<00:00,  1.60s/it]
2024-04-02 18:30:33 | ERROR | stderr |
2024-04-02 18:30:33 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-04-02 18:30:33 | ERROR | stderr | Traceback (most recent call last):
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
2024-04-02 18:30:33 | ERROR | stderr |     self.run()
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
2024-04-02 18:30:33 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-04-02 18:30:33 | ERROR | stderr |   File "D:\download\Langchain-Chatchat\startup.py", line 389, in run_model_worker
2024-04-02 18:30:33 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-04-02 18:30:33 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 18:30:33 | ERROR | stderr |   File "D:\download\Langchain-Chatchat\startup.py", line 217, in create_model_worker_app
2024-04-02 18:30:33 | ERROR | stderr |     worker = ModelWorker(
2024-04-02 18:30:33 | ERROR | stderr |              ^^^^^^^^^^^^
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-04-02 18:30:33 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-04-02 18:30:33 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastchat\model\model_adapter.py", line 362, in load_model
2024-04-02 18:30:33 | ERROR | stderr |     model.to(device)
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\modeling_utils.py", line 2595, in to
2024-04-02 18:30:33 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-04-02 18:30:33 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
2024-04-02 18:30:33 | ERROR | stderr |     return self._apply(convert)
2024-04-02 18:30:33 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-04-02 18:30:33 | ERROR | stderr |     module._apply(fn)
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-04-02 18:30:33 | ERROR | stderr |     module._apply(fn)
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-04-02 18:30:33 | ERROR | stderr |     module._apply(fn)
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
2024-04-02 18:30:33 | ERROR | stderr |     param_applied = fn(param)
2024-04-02 18:30:33 | ERROR | stderr |                     ^^^^^^^^^
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
2024-04-02 18:30:33 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-04-02 18:30:33 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 18:30:33 | ERROR | stderr |   File "C:\Users\calvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
2024-04-02 18:30:33 | ERROR | stderr |     raise AssertionError("Torch not compiled with CUDA enabled")
2024-04-02 18:30:33 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled

**Comment by chinesecalvin8282** [comment]
我的CUDA是12.4，只有这个和安装要求不一样。

**Comment by Lu0Key** [comment]
> 我的CUDA是12.4，只有这个和安装要求不一样。
> 
> D:\download\Langchain-Chatchat>nvcc -V nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2024 NVIDIA Corporation Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024 Cuda compilation tools, release 12.4, V12.4.99 Build cuda_12.4.r12.4/compiler.33961263_0

你导出你的环境看看

**Comment by Curlyfuu** [comment]
建议用conda管理，不受系统的cuda版本影响

**Comment by A-Corner** [comment]
2个解决方法：
1.直接修改  startup.py，直接写死配置，如果是macbook 就修改配置使用“mps”

`def create_model_worker_app(log_level: str = "INFO", **kwargs) -> FastAPI:
    # ... 其他代码 ...

    # 本地模型
    else:
        # ... 其他代码 ...
        worker = ModelWorker(
            # ... 其他参数 ...
            # device=args.device,  # 这是原来的
            device="mps",  # 使用 MPS 设备
            # ... 其他参数 ...
        )
        # ... 其他代码 ...`

第二个方法，按照 [Jas0nxlee](https://github.com/Jas0nxlee) 提供的方法也可以
`修改configs/server_config.py相关内容
    "chatglm3-6b": { "device": "cuda", }, "Qwen1.5-0.5B-Chat": { "device": "cuda", },
改为：
    "chatglm3-6b": { "device": "mps", }, "Qwen1.5-0.5B-Chat": { "device": "mps", },`

我自己才用的是第一种
