### ISSUE TITLE
使用pg向量数据库报错，端口未占用的前提下无法连接数据库

### ISSUE THREAD

**Issue by WSC741606** [chatchat-space/Langchain-Chatchat#3619]
新建知识库选择pg向量数据库报错，是需要我先怎么操作启动pg数据库吗？
防火墙已关闭，5432端口经检查无占用
Python startup.py -a 启动的

报错如下：
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/data/home/user/Test/GitLibrary/Langchain-Chatchat/server/knowledge_base/kb_api.py", line 29, in create_kb
    kb = KBServiceFactory.get_service(knowledge_base_name, vector_store_type, embed_model)
  File "/data/home/user/Test/GitLibrary/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 324, in get_service
    return PGKBService(kb_name, embed_model=embed_model)
  File "/data/home/user/Test/GitLibrary/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 64, in __init__
    self.do_init()
  File "/data/home/user/Test/GitLibrary/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 39, in do_init
    self._load_pg_vector()
  File "/data/home/user/Test/GitLibrary/Langchain-Chatchat/server/knowledge_base/kb_service/pg_kb_service.py", line 23, in _load_pg_vector
    self.pg_vector = PGVector(embedding_function=EmbeddingsFunAdapter(self.embed_model),
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/langchain_community/vectorstores/pgvector.py", line 212, in __init__
    self.__post_init__()
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/langchain_community/vectorstores/pgvector.py", line 218, in __post_init__
    self.create_vector_extension()
  File "/data/home/user/Test/Langchain-Chatchat-Env/lib/python3.9/site-packages/langchain_community/vectorstores/pgvector.py", line 256, in create_vector_extension
    raise Exception(f"Failed to create vector extension: {e}") from e
Exception: Failed to create vector extension: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
（蹲机器人的自动回复）

**Comment by WSC741606** [comment]
> Hey there, @WSC741606! 😄 Long time no see in the digital realm of issues and code. How's the tech wizardry going on your end?
> 
> Based on the error message you provided, it seems like the application is unable to connect to the PostgreSQL database. This could be due to several reasons, including incorrect connection details, the database not running, or network issues. Here are some steps you can take to troubleshoot this issue:
> 
> 1. **Correct Connection URI**: Verify that the `connection_uri` provided in your `kbs_config` is correct. The URI should follow the format: `postgresql://user:password@host:port/dbname`. Ensure that the `user`, `password`, `host`, `port`, and `dbname` are correctly specified and match the credentials of your PostgreSQL database.
> 2. **Database Running and Accessible**: Ensure that your PostgreSQL database is running and accessible from the machine where you're trying to set up the knowledge base. You can test this by trying to connect to your database using a PostgreSQL client with the same credentials and connection details.
> 3. **Permissions and Roles**: Check if the database user specified in the `connection_uri` has the necessary permissions to create tables, insert data, and perform other required operations in the specified database.
> 4. **Network Issues**: Although you mentioned having the firewall disabled and port 5432 open, it's still worth double-checking any network configurations, including any intermediate firewalls, network ACLs, or security groups that might be blocking the connection.
> 5. **PostgreSQL Configuration**: Ensure that your PostgreSQL server is configured to listen on the correct network interface (`listen_addresses` in `postgresql.conf`) and that the `pg_hba.conf` file is configured to allow connections from your application's host.
> 6. **Dependencies and Libraries**: Make sure all required Python libraries and dependencies for Langchain-Chatchat and PG vector database integration are correctly installed and up to date. This includes libraries such as `psycopg2` or `SQLAlchemy` for interacting with PostgreSQL from Python, and the `pgvector` extension for efficient vector search in PostgreSQL.
> 
> If after checking these points the issue persists, consider enabling detailed logging for both your application and the PostgreSQL server to get more insights into what might be causing the connection refusal. You can set the `log_level` variable to `"INFO"` or `"DEBUG"` for more detailed output in Langchain-Chatchat.
> 
> For more information, you can refer to similar issues in the Langchain-Chatchat issue tracker, such as [启动失败](https://github.com/chatchat-space/Langchain-Chatchat/issues/3117), [[BUG] python startup.py -a后无法启动](https://github.com/chatchat-space/Langchain-Chatchat/issues/3187), and [[BUG] 创建向量库报connection refused 500 错误](https://github.com/chatchat-space/Langchain-Chatchat/issues/2645).
> 
> If the issue still persists, please provide more environment configuration information, such as the operating system version, Python version, and whether the program is running in a virtual environment. If any modifications have been made to the code, please provide that information as well.
> 
> ## Sources
> * [启动失败](https://github.com/chatchat-space/Langchain-Chatchat/issues/3117)
> * [[BUG] python startup.py -a后无法启动](https://github.com/chatchat-space/Langchain-Chatchat/issues/3187)
> * [[BUG] 创建向量库报connection refused 500 错误](https://github.com/chatchat-space/Langchain-Chatchat/issues/2645)
> * [[BUG]  重建知识库失败](https://github.com/chatchat-space/Langchain-Chatchat/issues/3284)
> * [PG数据库配置后创建向量库报错](https://github.com/chatchat-space/Langchain-Chatchat/issues/2554)
> * [[BUG] 无法配置知识库](https://github.com/chatchat-space/Langchain-Chatchat/issues/413)
> * [server/knowledge_base/kb_service/pg_kb_service.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/pg_kb_service.py)
> * [configs/kb_config.py.example](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/kb_config.py.example)
> 
> #### About Dosu

pg向量数据库到底是个啥 需要我自己先配置什么数据库后端吗？@dosubot

**Comment by WSC741606** [comment]
我需要自己维护一个PostgreSQL数据库是吗@dosubot

**Comment by WSC741606** [comment]
我自己没先搭PostgreSQL Service导致的
还是faiss方便
