### ISSUE TITLE
批量重新向量化报错

### ISSUE THREAD

**Issue by summerfeel** [chatchat-space/Langchain-Chatchat#3633]
用api批量向量化的时候，，py这边突然就报错了，，，但是api那边没报错 显示在正常向量化，，这是咋回事啊有人遇到过吗 是在运行了几个小时后出现的。这样一报错 分词和已经向量化的 又没用了，又得重来了

Traceback (most recent call last):
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/urllib3/response.py", line 1040, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/urllib3/response.py", line 1184, in read_chunked
    self._update_chunk_length()
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/urllib3/response.py", line 1119, in _update_chunk_length
    raise ProtocolError("Response ended prematurely") from None
urllib3.exceptions.ProtocolError: Response ended prematurely

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/Langchain-Chatchat/t.py", line 17, in <module>
    response = requests.post(url, json=data, headers=headers) # 发送POST请求并获取响应结果
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chat/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: Response ended prematurely

**Comment by summerfeel** [comment]
好像是api端挂掉了，不知道为啥 运行了十多个小时突然挂掉了，，查询端口占用 显示该端口已经没被使用了，连接也连不上，，然后向量化白做了···

**Comment by zRzRzRzRzRzRzR** [comment]
大文件 多文件直接放在本地来做，别用API
