### ISSUE TITLE
科学上网，用DuckDuckGo搜索，提示API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by bjev-xie** [chatchat-space/Langchain-Chatchat#3643]
1、问题描述：
用DuckDuckGo搜索，提示API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
2、复现问题的步骤 
① 选择DuckDuckGo
②输入需要内容点击发送
③问题出现。
3、环境信息
① langchain-ChatGLM 版本v2.0.10 
② 是否使用 Docker 部署（是/否）：否
③使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
④使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
⑤ 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
⑥操作系统及版本 / Operating system and version: win10 专业版
⑦ Python 版本 / Python version:3.11
- 其他相关环境信息 / Other relevant environment information:

4、错误具体信息如下：
INFO:     127.0.0.1:57606 - "POST /chat/search_engine_chat HTTP/1.1" 200 OK
2024-04-06 19:42:49,720 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/search_engine_chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    await func()
  File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "C:\Users\xiemingwei\.conda\envs\chat\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1a900074910

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    |     yield
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    |     resp = self._pool.handle_request(req)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    |     raise exc from None
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    |     response = connection.handle_request(
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    |     raise exc
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    |     stream = self._connect(request)
    |              ^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpcore\_sync\connection.py", line 154, in _connect
    |     stream = stream.start_tls(**kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
    |     with map_exceptions(exc_map):
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    |     raise to_exc(exc) from exc
    | httpcore.ConnectError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 44, in _get_url
    |     resp = self._client.request(method, url, follow_redirects=True, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_client.py", line 828, in request
    |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_client.py", line 915, in send
    |     response = self._send_handling_auth(
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_client.py", line 943, in _send_handling_auth
    |     response = self._send_handling_redirects(
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_client.py", line 980, in _send_handling_redirects
    |     response = self._send_single_request(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    |     response = transport.handle_request(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_transports\default.py", line 230, in handle_request
    |     with map_httpcore_exceptions():
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    |     raise mapped_exc(message) from exc
    | httpx.ConnectError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    |     await func()
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "H:\xiemignwei\01GPT\03Langchain_Chatchat\server\chat\search_engine_chat.py", line 164, in search_engine_chat_iterator
    |     docs = await lookup_search_engine(query, search_engine_name, top_k, split_result=split_result)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "H:\xiemignwei\01GPT\03Langchain_Chatchat\server\chat\search_engine_chat.py", line 112, in lookup_search_engine
    |     results = await run_in_threadpool(search_engine, query, result_len=top_k, split_result=split_result)
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "H:\xiemignwei\01GPT\03Langchain_Chatchat\server\chat\search_engine_chat.py", line 37, in duckduckgo_search
    |     return search.results(text, result_len)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\langchain_community\utilities\duckduckgo_search.py", line 111, in results
    |     for r in self._ddgs_text(query, max_results=max_results)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\langchain_community\utilities\duckduckgo_search.py", line 57, in _ddgs_text
    |     return [r for r in ddgs_gen]
    |            ^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\langchain_community\utilities\duckduckgo_search.py", line 57, in <listcomp>
    |     return [r for r in ddgs_gen]
    |            ^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 105, in text
    |     for i, result in enumerate(results, start=1):
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 133, in _text_api
    |     vqd = self._get_vqd(keywords)
    |           ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 63, in _get_vqd
    |     resp = self._get_url("POST", "https://duckduckgo.com", data={"q": keywords})
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\xiemingwei\.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 57, in _get_url
    |     raise HTTPException(f"_get_url() {url} HttpError: {ex}")
    | duckduckgo_search.exceptions.HTTPException: _get_url() https://duckduckgo.com HttpError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
    +------------------------------------
2024-04-06 19:42:51,960 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by zixiaotan21** [comment]
科学上网后，使用duckduckgo搜索，同样遇到这个错误，想问问楼主解决了吗

**Comment by bjev-xie** [comment]
> 科学上网后，使用duckduckgo搜索，同样遇到这个错误，想问问楼主解决了吗

没有解决，不知道[dosubot]回答的什么，完全看不懂。希望有大神指教下。

**Comment by zRzRzRzRzRzRzR** [comment]
系统代理，建议检查你这个程序是否走了代理

**Comment by Tiandishihua** [comment]
> 1、问题描述： 用DuckDuckGo搜索，提示API通信遇到错误：peer closed connection without sending complete message body （incomplete chunked read） 2、复现问题的步骤 （1） 选择DuckDuckGo （2）输入需要内容点击发送 （3）问题出现。 3、环境信息 （1） langchain-ChatGLM 版本v2.0.10 （2） 是否使用 Docker 部署（是/否）：否 （3）使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B （4）使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base （5） 使用的向量库类型 （faiss / milvus / pg_vector 等）： faiss （6）操作系统及版本 / Operating system and version： win10 专业版 （7） Python 版本 / Python version：3.11
> 
> * 其他相关环境信息 / Other related environment information：
> 
> 4、错误具体信息如下： INFO： 127.0.0.1：57606 - “POST /chat/search_engine_chat HTTP/1.1” 200 OK 2024-04-06 19：42：49,720 - _client.py[line：1027] - INFO： HTTP 请求： POST http://127.0.0.1:7861/chat/search_engine_chat “HTTP/1.1 200 OK” 错误：ASGI 应用程序中出现异常 回溯（最近一次调用）：文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py”，第 269 行，**在调用**中await wrap（partial（self.listen_for_disconnect， receive）） 文件 “C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py”，第 258 行，换行 await func（） 文件 “C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py”，第 215 行，在 listen_for_disconnect message = await receive（） ^^^^^^^^^^^^^^^文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\uvicorn\protocols\http\h11_impl.py”，第 535 行，在接收中等待 self.message_event.wait（） 文件“C：\Users\xiemingwei.conda\envs\chat\Lib\asyncio\locks.py”，第 213 行，在等待中等待 fut asyncio.exceptions.CancelledError：取消范围 1a900074910
> 
> 在处理上述异常时，发生了另一个异常：
> 
> * 异常组回溯（最近一次调用最后一次）： |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\uvicorn\protocols\http\h11_impl.py”，第 407 行，在 run_asgi |result = await app（ # type： ignore[func-returns-value] | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\uvicorn\middleware\proxy_headers.py”，第 69 行，**正在调用**中 |返回 await self.app（范围、接收、发送） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\fastapi\applications.py”，第 1054 行，**正在调用** |等待 super（）。**调用**（范围、接收、发送） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\applications.py”，第 119 行，**正在调用**中 |等待self.middleware_stack（范围、接收、发送） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\middleware\errors.py”，第 186 行，**正在调用**中 |提高 EXC |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\middleware\errors.py”，第 164 行，**正在调用**中 |等待 self.app（范围、接收、_send） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\middleware\exceptions.py”，第 62 行，**正在调用**中 |等待 wrap_app_handling_exceptions（self.app， conn）（范围、接收、发送） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette_exception_handler.py”，第 64 行，wrapped_app |提高 EXC |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette_exception_handler.py”，第 53 行，wrapped_app |await app（scope， receive， sender） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\routing.py”，第 762 行，**正在调用**中 |等待self.middleware_stack（范围、接收、发送） |应用程序中的文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\routing.py”，第 782 行 |await route.handle（范围、接收、发送） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\routing.py”，第 297 行，在句柄中 |等待 self.app（范围、接收、发送） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\routing.py”，第 77 行，在应用程序中 |等待 wrap_app_handling_exceptions（应用、请求）（范围、接收、发送） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette_exception_handler.py”，第 64 行，wrapped_app |提高 EXC |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette_exception_handler.py”，第 53 行，wrapped_app |await app（scope， receive， sender） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\routing.py”，第 75 行，在应用程序中 |等待响应（范围、接收、发送） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py”，第 255 行，**正在调用**中 |与 anyio.create_task_group（） 异步，如 task_group： |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\anyio_backends_asyncio.py”，第 678 行，**在 aexit** |raise BaseExceptionGroup（|ExceptionGroup：任务组中未处理的错误（1 个子异常）+-+---------------- 1 个---------------- |回溯（最近一次调用最后一次）： |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_transports\default.py”，第 67 行，在 map_httpcore_exceptions |屈服 |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_transports\default.py”，第 231 行，handle_request |resp = self._pool.handle_request（req） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpcore_sync\connection_pool.py”，第 216 行，在 handle_request |从无中提高 exc |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpcore_sync\connection_pool.py”，第 196 行，handle_request |响应 = connection.handle_request（ | ^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpcore_sync\connection.py”，第 99 行，handle_request |提高 EXC |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpcore_sync\connection.py”，第 76 行，在 handle_request |stream = self._connect（请求） |^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpcore_sync\connection.py”，第 154 行，_connect |流 = stream.start_tls（**kwargs） |^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpcore_backends\sync.py”，第 152 行，在 start_tls |与 map_exceptions（exc_map）： |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\contextlib.py”，第 158 行，**在退出** |self.gen.throw（典型值、值、回溯） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpcore_exceptions.py”，第 14 行，在 map_exceptions |从 EXC 提高 to_exc（exc） |httpcore。ConnectError： [WinError 10054] 远程主机强迫关闭了一个现有的连接。 | |上述例外是以下异常的直接原因： | |回溯（最近一次调用最后一次）： |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py”，第 44 行，_get_url |resp = self._client.request（方法， url， follow_redirects=True， **kwargs） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_client.py”，第 828 行，请求中 |返回 self.send（request， auth=auth， follow_redirects=follow_redirects） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_client.py”，第 915 行，发送中 |响应 = self._send_handling_auth（ | ^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_client.py”，第 943 行，_send_handling_auth |响应 = self._send_handling_redirects（ | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_client.py”，第 980 行，_send_handling_redirects |响应 = self._send_single_request（请求） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_client.py”，第 1016 行，_send_single_request |响应 = transport.handle_request（请求） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_transports\default.py”，第 230 行，handle_request |使用 map_httpcore_exceptions（）： |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\contextlib.py”，第 158 行，**在退出** |self.gen.throw（典型值、值、回溯） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\httpx_transports\default.py”，第 84 行，map_httpcore_exceptions |从 EXC 提出mapped_exc（消息） |httpx的。ConnectError： [WinError 10054] 远程主机强迫关闭了一个现有的连接。 | |在处理上述异常期间，发生了另一个异常：| |回溯（最近一次调用最后一次）： |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py”，第 258 行，换行 |等待函数（） |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\sse_starlette\sse.py”，第 245 行，stream_response |self.body_iterator中数据的异步：|文件“H：\xiemignwei\01GPT\03Langchain_Chatchat\server\chat\search_engine_chat.py”，第 164 行，search_engine_chat_iterator |docs = await lookup_search_engine（query， search_engine_name， top_k， split_result=split_result） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“H：\xiemignwei\01GPT\03Langchain_Chatchat\server\chat\search_engine_chat.py”，第 112 行，lookup_search_engine |结果 = await run_in_threadpool（search_engine， query， result_len=top_k， split_result=split_result） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\starlette\concurrency.py”，第 40 行，run_in_threadpool |返回 await anyio.to_thread.run_sync（func， *args） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\anyio\to_thread.py”，第 56 行，run_sync |返回 await get_async_backend（）.run_sync_in_worker_thread（ | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\anyio_backends_asyncio.py”，第 2144 行，在 run_sync_in_worker_thread |返回等待未来 |^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\anyio_backends_asyncio.py”，第 851 行，正在运行 |结果 = context.run（func， *args） |^^^^^^^^^^^^^^^^^^^^^^^^ |文件“H：\xiemignwei\01GPT\03Langchain_Chatchat\server\chat\search_engine_chat.py”，第 37 行，duckduckgo_search |返回 search.results（text， result_len） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\langchain_community\utilities\duckduckgo_search.py”，第 111 行，在结果中 |for r in self._ddgs_text（query， max_results=max_results） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\langchain_community\utilities\duckduckgo_search.py”，第 57 行，在 _ddgs_text |返回 [R for R in ddgs_gen] |^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\langchain_community\utilities\duckduckgo_search.py”，第 57 行，在  |返回 [R for R in ddgs_gen] |^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py”，第 105 行，文本 |对于 i，结果为 enumerate（results， start=1）： |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py”，第 133 行，_text_api |vqd = self._get_vqd（关键字） |^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py”，第 63 行，_get_vqd |resp = self._get_url（“POST”， “https://duckduckgo.com”， data={“q”： 关键字}） |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |文件“C：\Users\xiemingwei.conda\envs\chat\Lib\site-packages\duckduckgo_search\duckduckgo_search.py”，第 57 行，_get_url |引发 HTTPException（f“_get_url（） {url} HttpError： {ex}”） |duckduckgo_search.exceptions.HTTPException： _get_url（） https://duckduckgo.com HttpError： [WinError 10054] 远程主机强迫关闭了一个现有的连接。 +------------------------------------ 2024-04-06 19：42：51,960 - utils.py[line：197] - ERROR： RemoteProtocolError： API通信遇到错误：peer closed connection without send complete message body （incomplete chunked read）

您好！请问您解决了吗？谢谢
