### ISSUE TITLE
执行python init_database.py --recreate-vs错误

### ISSUE THREAD

**Issue by 1431551850** [chatchat-space/Langchain-Chatchat#3694]
使用的milvus，langchain_community使用0.0.19
```
Traceback (most recent call last):
  File "D:\pythonproject\Chatchat0.2.10\init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "D:\pythonproject\Chatchat0.2.10\server\knowledge_base\migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "D:\pythonproject\Chatchat0.2.10\server\knowledge_base\migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "D:\pythonproject\Chatchat0.2.10\server\knowledge_base\kb_service\base.py", line 131, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
  File "D:\pythonproject\Chatchat0.2.10\server\knowledge_base\kb_service\milvus_kb_service.py", line 83, in do_add_doc
    ids = self.milvus.add_documents(docs)
  File "D:\pythonproject\Chatchat0.2.10\venv\lib\site-packages\langchain_core\vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "D:\pythonproject\Chatchat0.2.10\venv\lib\site-packages\langchain_community\vectorstores\milvus.py", line 520, in add_texts
    assert isinstance(
AssertionError: A list of valid ids are required when auto_id is False.

```

**Comment by 1431551850** [comment]
KeyError: 'pk',降级到langchain-community-0.0.19

**Comment by SuperTangW** [comment]
报错KeyError: 'pk，langchain-community-0.0.19 本身就是这个0.0.19 版本，降级到langchain-community-0.0.19是什么意思呢，您是不是写错了

**Comment by danny-zhu** [comment]
server.knowledge_base.kb_service.milvus_kb_service.MilvusKBService._load_milvus函数中初始化milvus的时候指定参数auto_id=True，如下：

def _load_milvus(self):
self.milvus = Milvus(embedding_function=EmbeddingsFunAdapter(self.embed_model),
collection_name=self.kb_name,
connection_args=kbs_config.get("milvus"),
index_params=kbs_config.get("milvus_kwargs")["index_params"],
search_params=kbs_config.get("milvus_kwargs")["search_params"],
auto_id=True
)
