### ISSUE TITLE
调用azure-api时使用llm对话正常没问题，但是使用知识库问答时会报错，请问有什么原因以及如何修改

### ISSUE THREAD

**Issue by liaoqingjian** [chatchat-space/Langchain-Chatchat#3716]
2024-04-11 11:20:59 | ERROR | model_worker | 请求 Azure API 时发生错误：{'choices': [], 'created': 0, 'id': '', 'model': '', 'object': '', 'prompt_filter_results':
 [{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {
'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}]}

2024-04-11 11:11:51,483 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/root/opt/Langchain-Chatchat-0.2.10-pdf/server/utils.py", line 36, in wrap_done
    await fn
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/root/anaconda3/envs/vt/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-04-11 11:11:51,485 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by zRzRzRzRzRzRzR** [comment]
超出长度限制，减少知识库召回的K
