### ISSUE TITLE
通过docs页面请求启动的API报错

### ISSUE THREAD

**Issue by Autism-al** [chatchat-space/Langchain-Chatchat#3728]
![er1](https://github.com/chatchat-space/Langchain-Chatchat/assets/70809894/94f66ad9-83d9-4271-a4dd-1d73a41f0110)
![er2](https://github.com/chatchat-space/Langchain-Chatchat/assets/70809894/8581ee8d-fabb-4951-8601-ab41dbc2ef7a)
如图所示，在成功启动模型后，通过fastAPI的docs页面调用接口后产生错误：
INFO:     127.0.0.1:43100 - "POST /chat/chat HTTP/1.1" 200 OK
2024-04-12 00:22:32 | INFO | stdout | INFO:     127.0.0.1:59048 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2024-04-12 00:22:32,428 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 400 Bad Request"
2024-04-12 00:22:32,429 - utils.py[line:25] - ERROR: Error code: 400 - {'object': 'error', 'message': 'Only  allowed now, your model local_chatglm3-6b', 'code': 40301}
Traceback (most recent call last):
  File "/public/home/robertchen/hj20215227065/Langchain-Chatchat-master/server/utils.py", line 23, in wrap_done
    await fn
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 105, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1300, in create
    return await self._post(
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1703, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1406, in request
    return await self._request(
  File "/public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1497, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Only  allowed now, your model local_chatglm3-6b', 'code': 40301}
2024-04-12 00:22:32,433 - utils.py[line:28] - ERROR: BadRequestError: Caught exception: Error code: 400 - {'object': 'error', 'message': 'Only  allowed now, your model local_chatglm3-6b', 'code': 40301}

这里的ERROR: BadRequestError: Caught exception: Error code: 400 - {'object': 'error', 'message': 'Only  allowed now, your model local_chatglm3-6b', 'code': 40301}是什么意思，是否是我配置的本地模型local_chatglm3-6b有问题导致的?

我的启动日志如下：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['local_chatglm3-6b'] @ cpu
{'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'load_kwargs': {'pre_seq_len': 16},
 'model_path': '/public/home/robertchen/hj20215227065/model_llm/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： local_bge @ cpu
==============================Langchain-Chatchat Configuration==============================

2024-04-12 00:08:57,874 - startup.py[line:636] - INFO: 正在启动服务：
2024-04-12 00:08:57,875 - startup.py[line:637] - INFO: 如需查看 llm_api 日志，请前往 /public/home/robertchen/hj20215227065/Langchain-Chatchat-master/logs
2024-04-12 00:09:21 | ERROR | stderr | INFO:     Started server process [250797]
2024-04-12 00:09:21 | ERROR | stderr | INFO:     Waiting for application startup.
2024-04-12 00:09:21 | ERROR | stderr | INFO:     Application startup complete.
2024-04-12 00:09:21 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-04-12 00:09:25 | INFO | model_worker | Loading the model ['local_chatglm3-6b'] on worker 4c9b0594 ...
Loading checkpoint shards:   0%|                                                                                                         | 0/7 [00:00<?, ?it/s]
2024-04-12 00:09:28 | ERROR | stderr | /public/home/robertchen/anaconda3/envs/lmfchatchat/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
2024-04-12 00:09:28 | ERROR | stderr |   return self.fget.__get__(instance, owner)()
Loading checkpoint shards:  14%|█████████████▊                                                                                   | 1/7 [00:03<00:23,  3.98s/it]
Loading checkpoint shards:  29%|███████████████████████████▋                                                                     | 2/7 [00:08<00:21,  4.32s/it]
Loading checkpoint shards:  43%|█████████████████████████████████████████▌                                                       | 3/7 [00:13<00:18,  4.52s/it]
Loading checkpoint shards:  57%|███████████████████████████████████████████████████████▍                                         | 4/7 [00:18<00:13,  4.64s/it]
Loading checkpoint shards:  71%|█████████████████████████████████████████████████████████████████████▎                           | 5/7 [00:22<00:09,  4.66s/it]
Loading checkpoint shards:  86%|███████████████████████████████████████████████████████████████████████████████████▏             | 6/7 [00:27<00:04,  4.60s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:29<00:00,  3.83s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:29<00:00,  4.22s/it]
2024-04-12 00:09:57 | ERROR | stderr |
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /public/home/robertchen/hj20215227065/model_llm/chatglm3-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2024-04-12 00:09:57 | INFO | stdout | ********************************************************************************************************************************************************************************************************
2024-04-12 00:09:57 | INFO | stdout | self.generate_stream_func<function generate_stream_chatglm at 0x7f625c1d52d0>
2024-04-12 00:09:57 | INFO | stdout | ****************************************************************************************************
2024-04-12 00:09:57 | INFO | model_worker | Register to controller
INFO:     Started server process [268749]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['local_chatglm3-6b'] @ cpu
{'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'load_kwargs': {'pre_seq_len': 16},
 'model_path': '/public/home/robertchen/hj20215227065/model_llm/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： local_bge @ cpu

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

**Comment by caaaattt** [comment]
解决了吗？我也出现了这个问题

**Comment by caaaattt** [comment]
解决了，换一个启动就行了，startup.py --all-api
