### ISSUE TITLE
[BUG] 简洁ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by A-runaaaa** [chatchat-space/Langchain-Chatchat#3750]
一键运行之后 使用LLM对话都没有问题  但是使用知识库问答 和文件对话时都会报一个“创建History对象时content属性的值为None而引起的错误。根据错误信息，似乎content属性不允许为None。可能需要检查代码中创建History对象的地方，并确保在创建对象时提供了有效的content值，下面是具体的报错信息。具体应该修改哪些地方的内容
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/home/guanjr/miniconda3/envs/KQAP/lib/python3.11/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/home/guanjr/Langchain-Chatchat-master_2024_2/server/chat/file_chat.py", line 138, in knowledge_base_chat_iterator
    |     input_msg = History(role="user", content=prompt_template).to_msg_template(False)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    | pydantic.error_wrappers.ValidationError: 1 validation error for History
    | content
    |   none is not an allowed value (type=type_error.none.not_allowed)

**Comment by zRzRzRzRzRzRzR** [comment]
这是没输入内容吧

**Comment by danny-zhu** [comment]
机器人dosubot回答解决我的问题，改了prompt模板的名称后，代码中忘记改了
