### ISSUE TITLE
Docker启动后，回答乱码

### ISSUE THREAD

**Issue by fxcvv** [chatchat-space/Langchain-Chatchat#3762]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
使用了官方的docker镜像，0.2.10
操作系统：ubuntu22.04
Driver Version: 545.29.06  
CUDA Version: 12.3
Docker version 26.0.1, build d260a54

在webui中提问，回答都是乱码
使用docker logs命令查看，发现以下报错

2024-04-16 02:24:34,294 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
2024-04-16 02:24:36,402 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:55856 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-04-16 02:24:36,404 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-04-16 02:24:36,468 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:55856 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-04-16 02:24:36,469 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:55856 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-04-16 02:24:36,483 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:55856 - "POST /chat/chat HTTP/1.1" 200 OK
2024-04-16 02:24:36,648 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-04-16 02:24:36 | INFO | stdout | INFO:     127.0.0.1:60554 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-04-16 02:24:36,731 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-04-16 02:24:36 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-04-16 02:24:36,762 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/data/model/langchain-chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/usr/local/lib/python3.11/dist-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/usr/local/lib/python3.11/dist-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.11/dist-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/usr/local/lib/python3.11/dist-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-04-16 02:24:36,762 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by Zephyr69** [comment]
你是多卡加载的模型吗？我用官方docker单卡没问题，fschat多卡加载就乱码。而wsl里多卡加载则正常。

**Comment by fxcvv** [comment]
> 你是多卡加载的模型吗？我用官方docker单卡没问题，fschat多卡加载就乱码。而wsl里多卡加载则正常。

我有两台服务器，使用相同的docker镜像

**Comment by Zephyr69** [comment]
> > 你是多卡加载的模型吗？我用官方docker单卡没问题，fschat多卡加载就乱码。而wsl里多卡加载则正常。
> 
> 我有两台服务器，使用相同的docker镜像，都是多卡环境，一台正常，一台乱码， 我怀疑是宿主机的环境导致的，但又不知道哪里出了问题

应该是宿主机有什么问题，在有多卡问题的机器上用宿主机和docker容器都会乱码，报错是一连串的../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [30,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
宿主上试过切换cuda118、cuda121、py310、py311、bios关闭ACS，均同样报错，而只用单卡就没问题。不知道是哪里有问题，其他多卡应用就完全正常。
