### ISSUE TITLE
[BUG] chat/chat方法，偶发内部调用openai的acompletion_with_retry超过120s没有任何响应

### ISSUE THREAD

**Issue by zhoufurong2022** [chatchat-space/Langchain-Chatchat#3765]
**问题描述 / Problem Description**
/chat/chat方法调用的时候我设置了asyncio.create_task(wrap_done)中超时时间为120s——asyncio.wait_for(fn, timeout=120)，调用前没有任何并发，还没有调用到get_worker_address之前就出现了超时

**复现问题的步骤 / Steps to Reproduce**
有敏感信息暂时无法给到，请自行编造

**预期的结果 / Expected Result**
Post请求到/get_worker_address之后打印日志

**实际结果 / Actual Result**

response = await self._send_handling_auth(
stream = await self._network_backend.connect_tcp(**kwargs)
response = await transport.handle_async_request(request)
response = await self._client.send(
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 484, in _astream
return await self._post(
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
stream = await self._connect(request)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1646, in send
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
raise exc
raise exc from None
return await self._request(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1748, in _send_single_request
response = await self._send_single_request(request)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
resp = await self._pool.handle_async_request(req)
async for chunk in await acompletion_with_retry(
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
return await llm.async_client.create(**kwargs)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
response = await connection.handle_async_request(
File "/usr/local/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 104, in acompletion_with_retry
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1406, in request
response = await self._send_handling_redirects(
return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1703, in post
ERROR:root:
async for chunk in stream:
File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1435, in _request
File "/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1300, in create
asyncio.exceptions.CancelledError

return await _wait(fs, timeout, return_when, loop)
asyncio.exceptions.CancelledError
File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
Traceback (most recent call last):
File "/root/KnowledgeChat/server/utils.py", line 48, in wrap_done
asyncio.exceptions.TimeoutError
await asyncio.wait_for(fn, timeout=120)
The above exception was the direct cause of the following exception:

File "/usr/local/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
response = await self.agenerate([inputs], run_manager=run_manager)
File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
During handling of the above exception, another exception occurred:

File "/usr/local/lib/python3.10/asyncio/tasks.py", line 491, in _wait
File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 481, in agenerate
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate

raise e
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
File "/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 219, in connect_tcp
File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 668, in __aexit__
async with create_task_group() as tg:
return await self.llm.agenerate_prompt(
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 384, in wait
File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
await self._acall(inputs, run_manager=run_manager)
asyncio.exceptions.CancelledError
stream: anyio.abc.ByteStream = await anyio.connect_tcp(
return fut.result()

raise exceptions.TimeoutError() from exc
File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 688, in __aexit__
results = await asyncio.gather(
raise cancelled_exc_while_waiting_tasks

File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
Traceback (most recent call last):
await asyncio.wait(self._tasks)
File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
return await self._backend.connect_tcp(
return await self.agenerate(
await waiter
async for chunk in await acompletion_with_retry(
File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 385, in acall
File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1703, in post
File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 688, in __aexit__
File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1646, in send
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
await asyncio.wait_for(fn, timeout=120)
File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1435, in _request
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
async for chunk in stream:
raise e
return fut.result()
response = await connection.handle_async_request(
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 491, in _wait
File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 379, in acall
File "/root/KnowledgeChat/server/utils.py", line 48, in wrap_done
return await llm.async_client.create(**kwargs)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
raise cancelled_exc_while_waiting_tasks
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1748, in _send_single_request
return await self._post(
await waiter
File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
response = await self._send_handling_redirects(
File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 481, in agenerate
results = await asyncio.gather(
raise exc
return await self._backend.connect_tcp(
Traceback (most recent call last):
return await self._request(
raise exceptions.TimeoutError() from exc
response = await transport.handle_async_request(request)
return await _wait(fs, timeout, return_when, loop)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
await self._acall(inputs, run_manager=run_manager)
asyncio.exceptions.CancelledError

File "/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 219, in connect_tcp
File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1406, in request
response = await self.agenerate([inputs], run_manager=run_manager)
File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
resp = await self._pool.handle_async_request(req)
stream: anyio.abc.ByteStream = await anyio.connect_tcp(
stream = await self._connect(request)
async with create_task_group() as tg:
File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 668, in __aexit__
File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request

stream = await self._network_backend.connect_tcp(**kwargs)
raise exc from None
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
The above exception was the direct cause of the following exception:
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
response = await self._send_single_request(request)
response = await self._client.send(
File "/usr/local/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 484, in _astream
2024-04-15 07:35:00,931 832 ERROR TimeoutError: Wrap Done Timeout error:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 384, in wait

File "/usr/local/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 104, in acompletion_with_retry

asyncio.exceptions.TimeoutError
return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
File "/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1300, in create
File "/usr/local/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
response = await self._send_handling_auth(
return await self.agenerate(
return await self.llm.agenerate_prompt(
await asyncio.wait(self._tasks)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：是
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：glm-4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：milvus
- 操作系统及版本 / Operating system and version: Linux xxxxxxxxxx 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 GNU/Linux
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

**Comment by manchiy** [comment]
同样遇到类似问题 ，我设置了server_config 的HTTPX_DEFAULT_TIMEOUT = 30 后。偶发出现 超时卡住的时候，其他所有接口都会卡住无法调用， 类似前端查询有什么模型。 所有接口都会被卡主

**Comment by zRzRzRzRzRzRzR** [comment]
是的，以为这是完全顺发的系统

**Comment by manchiy** [comment]
> 是的，以为这是完全顺发的系统

大佬 , 这个要改的话,是从哪里入手呢. 是因为fastchat的问题吗

**Comment by zRzRzRzRzRzRzR** [comment]
是框架设计的时候就是顺发的，这个修改的部分挺多，at @glide-the
