### ISSUE TITLE
macos M1 安装不上xformers包，报错信息如下

### ISSUE THREAD

**Issue by wbcz** [chatchat-space/Langchain-Chatchat#3771]
python3.11

error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/alsc/Documents/eleme/Langchain-Chatchat/vChat/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/alsc/Documents/eleme/Langchain-Chatchat/vChat/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/alsc/Documents/eleme/Langchain-Chatchat/vChat/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rr/pcbq6qt94bb38608w7njjrzh0000gn/T/pip-build-env-8m047qh9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rr/pcbq6qt94bb38608w7njjrzh0000gn/T/pip-build-env-8m047qh9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/rr/pcbq6qt94bb38608w7njjrzh0000gn/T/pip-build-env-8m047qh9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/rr/pcbq6qt94bb38608w7njjrzh0000gn/T/pip-build-env-8m047qh9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

**Comment by bluetree2009** [comment]
不支持mac

**Comment by 100ZZ** [comment]
我是M2Max
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2
然后再：pip install -r requirements.txt
是可以成功的，conda python是推荐的3.11.7

但start的时候报错了，还在看；不知道后面的CUDA用MPS能不能搞定
