### ISSUE TITLE
运行python startup.py -a时报错

### ISSUE THREAD

**Issue by Fdioa** [chatchat-space/Langchain-Chatchat#3776]
报错信息如下：
OSError: Incorrect path_or_model_id: ''. Please provide either the path to a local folder or the repo_id of a model on the Hub.
是否为模型位置配置不当？应该如何修改？

**Comment by Fdioa** [comment]
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-100-generic-x86_64-with-glibc2.35.
python版本：3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：chatglm2-6b @ cuda
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
{'device': 'cuda', 'host': '127.0.0.1', 'infer_turbo': False, 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================


2024-04-17 01:58:58,471 - startup.py[line:655] - INFO: 正在启动服务：
2024-04-17 01:58:58,471 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /root/Langchain/Langchain-Chatchat/logs
/root/miniconda3/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-04-17 01:59:09 | INFO | model_worker | Loading the model ['6'] on worker b2c8a1fd ...
2024-04-17 01:59:09 | ERROR | stderr | Process model_worker - 6:
2024-04-17 01:59:09 | ERROR | stderr | Traceback (most recent call last):
2024-04-17 01:59:09 | ERROR | stderr |   File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 385, in cached_file
2024-04-17 01:59:09 | ERROR | stderr |     resolved_file = hf_hub_download(
2024-04-17 01:59:09 | ERROR | stderr |   File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 111, in _inner_fn
2024-04-17 01:59:09 | ERROR | stderr |     validate_repo_id(arg_value)
2024-04-17 01:59:09 | ERROR | stderr |   File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 165, in validate_repo_id
2024-04-17 01:59:09 | ERROR | stderr |     raise HFValidationError(
2024-04-17 01:59:09 | ERROR | stderr | huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''.
