### ISSUE TITLE
初始化数据库的时候报错

### ISSUE THREAD

**Issue by qyf661** [chatchat-space/Langchain-Chatchat#3781]
Traceback (most recent call last):
  File "/home/abc/git/Langchain-Chatchat-master/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/abc/git/Langchain-Chatchat-master/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/home/abc/git/Langchain-Chatchat-master/server/knowledge_base/migrate.py", line 110, in files2vs
    print(f"正在将 {kb_name}/{filename} 添加到向量库，共包含{len(docs)}条文档")
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 16-17: surrogates not allowed

**Comment by zRzRzRzRzRzRzR** [comment]
这应该就是编码不兼容的问题
