### ISSUE TITLE
milvus向量数据库 We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like None is not the path to a directory containing a file named config.json.

### ISSUE THREAD

**Issue by supergangchao** [chatchat-space/Langchain-Chatchat#3783]
问题

We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like None is not the path to a directory containing a file named config.json.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/129723199/871797a7-4711-4862-b996-5260950faf97)

环境
①有milvus向量数据库
②系统使用faiss 向量数据库正常使用上传文件解析功能
③milvus 用官方demo测试正常

配置milvus知识库，上传文件的是时候报一下错误
`2024-04-17 11:43:16,616 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 200 OK"
2024-04-17 11:43:19,825 - utils.py[line:295] - INFO: UnstructuredExcelLoader used for /mnt/sdc/Langchain-Chatchat/knowledge_base/test111/content/1.xlsx
We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like None is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
文档切分示例：page_content='2\n电子发票和纸质发票的区别在哪里?' metadata={'source': '/mnt/sdc/Langchain-Chatchat/knowledge_base/test111/content/1.xlsx'}
INFO:     127.0.0.1:33286 - "POST /knowledge_base/upload_docs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 170, in upload_docs
    result = update_docs(
             ^^^^^^^^^^^^
  File "/mnt/sdc/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 287, in update_docs
    kb.update_doc(kb_file, not_refresh_vs_cache=True)
  File "/mnt/sdc/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 165, in update_doc
    return self.add_doc(kb_file, docs=docs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 131, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 83, in do_add_doc
    ids = self.milvus.add_documents(docs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdc/soft/anaconda3/envs/Langchain_Chatchat_env/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 520, in add_texts
    assert isinstance(
`

**Comment by supergangchao** [comment]
> The error you're encountering indicates an issue with loading a model from Hugging Face's model repository, likely due to connectivity issues or the model not being cached locally. Here's how to address this:您遇到的错误表示从 Hugging Face 的模型存储库加载模型时出现问题，可能是由于连接问题或模型未在本地缓存。解决此问题的方法如下：
> 
> 1. **Verify Model Configuration**: Ensure the model specified (via `EMBEDDING_MODEL` or similar) is correct and intended for use.验证模型配置：确保指定的模型（通过 `EMBEDDING_MODEL` 或类似）正确且可供使用。
> 2. **Internet Access**: Check if your environment has access to `https://huggingface.co`. If internet access is restricted, you'll need to manually download and cache the model.Internet 访问：检查您的环境是否有权访问 `https://huggingface.co` .如果 Internet 访问受到限制，则需要手动下载和缓存模型。
> 3. **Local Model Cache**: Pre-download the model on a machine with internet access and transfer it to your environment. Set the `TRANSFORMERS_CACHE` environment variable to the local cache directory.本地模型缓存：在可以访问 Internet 的计算机上预下载模型，并将其传输到您的环境。将 `TRANSFORMERS_CACHE` 环境变量设置为本地缓存目录。
> 4. **Adjust for Offline Use**: Modify your application to load models from a local directory if intended to run offline.针对脱机使用进行调整：如果打算脱机运行，请修改应用程序以从本地目录加载模型。
> 5. **Test with a Simple Model**: Use a basic model for testing to isolate the issue.使用简单模型进行测试：使用基本模型进行测试以隔离问题。
> 6. **Review Logs**: Check the error message and ensure the `config.json` file path is correct.查看日志：检查错误消息并确保 `config.json` 文件路径正确。
> 
> For further assistance, consider looking into similar issues discussed in the Langchain-Chatchat repository, which might provide additional insights or solutions specific to your setup.如需进一步的帮助，请考虑查看 Langchain-Chatchat 存储库中讨论的类似问题，这可能会提供特定于您的设置的其他见解或解决方案。
> 
> ## Sources 来源
> * [关于文件上传到知识库并向量化的问题](https://github.com/chatchat-space/Langchain-Chatchat/issues/3308)
> * [关于上传文件到知识库出现We couldn't connect to 'https://huggingface.co' to load this file](https://github.com/chatchat-space/Langchain-Chatchat/issues/3416)
> * [[BUG] 在知识库中上传文件时遇到访问https://huggingface.co/None/resolve/main/tokenizer_config.json](https://github.com/chatchat-space/Langchain-Chatchat/issues/2325)
> * [server/knowledge_base/kb_service/base.py服务器/knowledge_base/kb_service/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py)
> 
> #### About Dosu 关于Dosu

![cb81bbb5d0a860619aab838ead16312](https://github.com/chatchat-space/Langchain-Chatchat/assets/129723199/a4324dbb-5387-4a5a-b61b-2e6c9a3585c7)
![8c06660df3014b919b4d226542c28dd](https://github.com/chatchat-space/Langchain-Chatchat/assets/129723199/2579623e-903f-407b-b6ba-dd7ba5b98560)

用miluvs 向量数据库后就出现报错，使用faiss就正常。
