### ISSUE TITLE
调用zhipu官方api接口，不能流式输出

### ISSUE THREAD

**Issue by GLY-123** [chatchat-space/Langchain-Chatchat#3793]
调用zhipu官方api接口，不能流式输出

**实际结果 / Actual Result**
data中设置stream为false时能正常问答，不能流式；data中stream设置为true时报错如下：连接成功*********
2024-04-17 07:57:58 | INFO | httpx | HTTP Request: POST https://open.bigmodel.cn/api/paas/v4/chat/completions "HTTP/1.1 200 "
请求成功*************: <Response [200 ]>
response*************: <Response [200 ]>
2024-04-17 07:58:01,034 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/guo/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain_core/language_models/chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain_core/language_models/chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain_core/language_models/chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain_core/language_models/chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "/data/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()

**环境信息 / Environment Information**
langchian-chatchat-2.10
源码部署

**Comment by zRzRzRzRzRzRzR** [comment]
是的，没有做，有bug，在0.2.x不会做了
