### ISSUE TITLE
将文件添加至向量库时报错：TypeError: string indices must be integers

### ISSUE THREAD

**Issue by zhifeng-ff** [chatchat-space/Langchain-Chatchat#3812]
RapidOCRPDFLoader context page index: 0:   0%|                                                                                            | 0/1 [00:00<?, ?it/s]*** stack smashing detected ***: terminated
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.
----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1713510824 (unix time) try "date -d @1713510824" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80002d0ad) received by PID 184493 (TID 0x7f63a61c6700) from PID 184493 ***]

2024-04-19 15:13:44,796 - utils.py[line:95] - ERROR: RemoteProtocolError: error when post /knowledge_base/upload_docs: Server disconnected without sending a response.
2024-04-19 15:13:44,797 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/upload_docs: [Errno 111] Connection refused
2024-04-19 15:13:44,798 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/upload_docs: [Errno 111] Connection refused
2024-04-19 15:13:45,153 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-04-19 15:13:45,153 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-04-19 15:13:45,154 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-04-19 15:13:45.154 Uncaught app exception
Traceback (most recent call last):
  File "/home/yzrt/anaconda3/envs/chat/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/yzrt/AI/Chatchat/webui.py", line 65, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/yzrt/AI/Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 328, in knowledge_base_page
    data = [
  File "/home/yzrt/AI/Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
TypeError: string indices must be integers

**Comment by fivegg** [comment]
我也遇到了，实际是RapidOCRDocLoader解析文档出错，另外可能导致api接口down掉了，后续代码访问nowledge_base接口返回空数据，导致代码报类型错。

**Comment by nikelius** [comment]
类似问题，如何解决？——"id": x["id"], TypeError: string indices must be integers

2024-08-08 17:49:58.330 | ERROR    | chatchat.webui_pages.utils:post:87 - ConnectError: error when post /knowledge_base/update_docs: [Errno 111] Connection refused
2024-08-08 17:49:58.332 | ERROR    | chatchat.webui_pages.utils:post:87 - ConnectError: error when post /knowledge_base/update_docs: [Errno 111] Connection refused
2024-08-08 17:49:58.334 | ERROR    | chatchat.webui_pages.utils:post:87 - ConnectError: error when post /knowledge_base/update_docs: [Errno 111] Connection refused
2024-08-08 17:49:58.336 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-08-08 17:49:58.651 | ERROR    | chatchat.webui_pages.utils:post:87 - ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-08-08 17:49:58.655 | ERROR    | chatchat.webui_pages.utils:post:87 - ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-08-08 17:49:58.657 | ERROR    | chatchat.webui_pages.utils:post:87 - ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-08-08 17:49:58.659 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-08-08 17:49:58.661 Uncaught app exception
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/py310/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/xxx/miniconda3/envs/py310/lib/python3.10/site-packages/chatchat/webui.py", line 69, in <module>
    knowledge_base_page(api=api, is_lite=is_lite)
  File "/home/xxx/miniconda3/envs/py310/lib/python3.10/site-packages/chatchat/webui_pages/knowledge_base/knowledge_base.py", line 374, in knowledge_base_page
    data = [
  File "/home/xxx/miniconda3/envs/py310/lib/python3.10/site-packages/chatchat/webui_pages/knowledge_base/knowledge_base.py", line 377, in <listcomp>
    "id": x["id"],
TypeError: string indices must be integers

**Comment by nikelius** [comment]
> 类似问题，如何解决？——"id": x["id"], TypeError: string indices must be integers

重启有时候就好了
