### ISSUE TITLE
配置Azure Openai时，只能使用GPT模型，不能使用embedding模型

### ISSUE THREAD

**Issue by mydreamworldpolly** [chatchat-space/Langchain-Chatchat#3827]
**问题描述 / Problem Description**
配置Azure Openai时，只能使用GPT模型，不能使用embedding模型。只有OpenAI原版embedding模型的配置，没有Azure Openai的。

**复现问题的步骤 / Steps to Reproduce**
1. 进入配置文件，notepad model_config.py，添加Azure Openai key，  EMBEDDING_MODEL = "text-embedding-ada-002"
 "text-embedding-ada-002": Azure Openai key
2. 执行 python init_database.py --recreate-vs
3. 问题出现 / Problem occurs
2024-04-21 17:02:41,700 - _base_client.py[line:986] - INFO: Retrying request to /embeddings in 0.989405 seconds
2024-04-21 17:03:24,783 - _base_client.py[line:986] - INFO: Retrying request to /embeddings in 1.698303 seconds
2024-04-21 17:04:08,597 - embeddings_api.py[line:39] - ERROR: Request timed out.
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\polly\Langchain-Chatchat\init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "C:\Users\polly\Langchain-Chatchat\server\knowledge_base\migrate.py", line 121, in folder2db
    kb.create_kb()
  File "C:\Users\polly\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 81, in create_kb
    self.do_create_kb()
  File "C:\Users\polly\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "C:\Users\polly\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\polly\Langchain-Chatchat\server\knowledge_base\kb_cache\faiss_cache.py", line 102, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\polly\Langchain-Chatchat\server\knowledge_base\kb_cache\faiss_cache.py", line 60, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\polly\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\langchain_core\vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\polly\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 959, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\polly\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 439, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\polly\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\polly\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\numpy\linalg\linalg.py", line 2582, in norm
    s = (x.conj() * x).real
         ^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by mydreamworldpolly** [comment]
@dosu 实际上，Azure Openai支持这个模型，而且我在别的程序中使用很正常。但我没有在配置文件中发现输入模型名称、endpoint的地方。

**Comment by zRzRzRzRzRzRzR** [comment]
是的，因为没有这个API的接入
