### ISSUE TITLE
[BUG] 执行python api.py 报错

### ISSUE THREAD

**Issue by kanalmighty** [chatchat-space/Langchain-Chatchat#383]
错误信息
(chatglm_langchain) kan@kan-MS-TZZ-H510M-H:~/chatglm_langchain/langchain-ChatGLM$ python api.py 
INFO  2023-05-16 18:31:31,521-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /home/kan/chatglm_langchain/langchain-ChatGLM
flagging username: d8342782bc274004afa14748cd45680c

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "api.py", line 357, in <module>
    api_start(args.host, args.port)
  File "api.py", line 342, in api_start
    local_doc_qa.init_cfg(
  File "/home/kan/chatglm_langchain/langchain-ChatGLM/chains/local_doc_qa.py", line 158, in init_cfg
    self.llm.load_model(model_name_or_path=llm_model_dict[llm_model],
  File "/home/kan/chatglm_langchain/langchain-ChatGLM/models/chatglm_llm.py", line 121, in load_model
    self.tokenizer = AutoTokenizer.from_pretrained(
  File "/home/kan/miniconda3/envs/chatglm_langchain/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 679, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/kan/miniconda3/envs/chatglm_langchain/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "/home/kan/miniconda3/envs/chatglm_langchain/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1958, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/kan/.cache/huggingface/modules/transformers_modules/ChatGLM-6B/tokenization_chatglm.py", line 209, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
  File "/home/kan/.cache/huggingface/modules/transformers_modules/ChatGLM-6B/tokenization_chatglm.py", line 55, in __init__
    assert vocab_file is not None
AssertionError

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码尝试是否解决问题，如果问题仍然存在，可以重新提issue
