### ISSUE TITLE
当我启用api时，送入文本过长时程序会报错，返回空值。

### ISSUE THREAD

**Issue by renllll** [chatchat-space/Langchain-Chatchat#3853]
当我启用api时，送入文本过长终端报以下错误，返回空值，如何解决这个报错
以上代码运行是报以下错误，如何解决
response返回为空，在终端显示报错如下
Traceback (most recent call last):
  File "/media/remotesense/c076bdaf-88b9-4573-88f1-b4bdb3af31834/jack/Langchain-Chatchat-master/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-04-23 15:13:58,995 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by renllll** [comment]
api设置最大长度是在哪设置的，调用api总报以下错误
2024-04-24 17:06:58 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-04-24 17:06:59,665 - utils.py[line:38] - ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/media/remotesense/c076bdaf-88b9-4573-88f1-b4bdb3af31834/jack/Langchain-Chatchat-master/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/remotesense/anaconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 495, in _astream
    choice = chunk["choices"][0]
             ~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-04-24 17:06:59,665 - utils.py[line:40] - ERROR: TypeError: Caught exception: 'NoneType' object is not subscriptable

**Comment by zRzRzRzRzRzRzR** [comment]
因为超过了4096 token，你要在model config或者对应请求api调整max token， 比如zhipu只有4096 如果你上传的内容和提问超过4096就无法回答
