### ISSUE TITLE
[BUG] 基于baichuan2-7b-chat的Lora微调模型加载时报错：TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by BlingDan** [chatchat-space/Langchain-Chatchat#3876]
**问题描述 / Problem Description**
使用Lora微调后的baichuan2-7b-chat自定义模型，启动web服务`python startup.py -a`报错：TypeError: argument of type 'NoneType' is not iterable

**复现问题的步骤 / Steps to Reproduce**

1. 根据[微调模型加载实操](https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5#%E5%BE%AE%E8%B0%83%E6%A8%A1%E5%9E%8B%E5%8A%A0%E8%BD%BD%E5%AE%9E%E6%93%8D)修改相关配置
2. 设置`PEFT_SHARE_BASE_WEIGHTS=true`环境变量后运行`python startup.py -a`
3. model_worker部分开始出错

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**

+ 控制台运行截图

  ![image-20240425135039771](https://raw.githubusercontent.com/BlingDan/ImageHosting/main/img/image-20240425135039771.png)

+ Langchain-Chatchat/logs/model_worker.log中的报错信息如下

```log
2024-04-25 13:25:44 | ERROR | stderr | Process model_worker - qlora_baichuan2-7b-chat:
2024-04-25 13:25:44 | ERROR | stderr | Traceback (most recent call last):
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-04-25 13:25:44 | ERROR | stderr |     self.run()
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-04-25 13:25:44 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-04-25 13:25:44 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-04-25 13:25:44 | ERROR | stderr |     worker = ModelWorker(
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 66, in __init__
2024-04-25 13:25:44 | ERROR | stderr |     super().__init__(
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/fastchat/serve/base_model_worker.py", line 47, in __init__
2024-04-25 13:25:44 | ERROR | stderr |     self.conv = self.make_conv_template(conv_template, model_path)
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/fastchat/serve/base_model_worker.py", line 75, in make_conv_template
2024-04-25 13:25:44 | ERROR | stderr |     conv = get_conversation_template(model_path)
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 376, in get_conversation_template
2024-04-25 13:25:44 | ERROR | stderr |     return adapter.get_default_conv_template(model_path)
2024-04-25 13:25:44 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 655, in get_default_conv_template
2024-04-25 13:25:44 | ERROR | stderr |     if "peft" in config.base_model_name_or_path:
2024-04-25 13:25:44 | ERROR | stderr | TypeError: argument of type 'NoneType' is not iterable

```

**环境信息 / Environment Information**

- langchain-Chatchat版本号：[autodl镜像](https://github.com/chatchat-space/Langchain-Chatchat)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：[baichuan-inc/Baichuan2-7B-Chat](https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat)
- 操作系统及版本 ：Linux
- Python 版本：Python 3.10.9
- 其他相关环境信息：PyTorch: 12.0+CUDA:12.2

**附加信息 / Additional Information**
无

**Comment by BlingDan** [comment]
修改了adapter_config.json文件中`base_model_name_or_path`属性

```json
{
  "_from_model_config": true,
  "base_model_name_or_path": "/root/autodl-tmp/baichuan-inc/Baichuan2-7B-Chat",
  "architectures": [
    "BaichuanForCausalLM"
  ],
  "auto_map": {
    "AutoConfig": "configuration_baichuan.BaichuanConfig",
    "AutoModelForCausalLM": "modeling_baichuan.BaichuanForCausalLM"
  },
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "model_max_length": 4096,
  "model_type": "baichuan",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.36.2",
  "use_cache": true,
  "vocab_size": 125696,
  "z_loss_weight": 0
}

```

运行程序后报错

```shell
2024-04-25 14:28:43 | ERROR | stderr | 
2024-04-25 14:28:43 | ERROR | stderr | Process model_worker - qlora_baichuan2-7b-chat:
2024-04-25 14:28:43 | ERROR | stderr | Traceback (most recent call last):
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-04-25 14:28:43 | ERROR | stderr |     self.run()
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-04-25 14:28:43 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-04-25 14:28:43 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-04-25 14:28:43 | ERROR | stderr |     worker = ModelWorker(
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-04-25 14:28:43 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 348, in load_model
2024-04-25 14:28:43 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 647, in load_model
2024-04-25 14:28:43 | ERROR | stderr |     model = PeftModel.from_pretrained(base_model, model_path)
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/peft/peft_model.py", line 244, in from_pretrained
2024-04-25 14:28:43 | ERROR | stderr |     PeftConfig._get_peft_type(
2024-04-25 14:28:43 | ERROR | stderr |   File "/root/pyenv/lib/python3.10/site-packages/peft/utils/config.py", line 186, in _get_peft_type
2024-04-25 14:28:43 | ERROR | stderr |     return loaded_attributes["peft_type"]
2024-04-25 14:28:43 | ERROR | stderr | KeyError: 'peft_type'
```

**Comment by zRzRzRzRzRzRzR** [comment]
查看wiki如何调用微调模型
