### ISSUE TITLE
[BUG] 使用milvus,初始化时报错attempt to write a readonly database

### ISSUE THREAD

**Issue by sweetautumn** [chatchat-space/Langchain-Chatchat#3931]
**问题描述 / Problem Description**
使用milvus,输入命令python init_database.py --recreate-vs初始化时报错attempt to write a readonly database

具体报错信息：
recreating all vector stores
2024-04-29 14:36:07,106 - utils.py[line:145] - INFO: Note: detected 112 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-04-29 14:36:07,107 - utils.py[line:148] - INFO: Note: NumExpr detected 112 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-04-29 14:36:07,107 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
2024-04-29 14:36:07,282 - milvus.py[line:264] - DEBUG: Created new connection using: d36ea3981fe2476bb07cf8a61ae4311d
Traceback (most recent call last):
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/algo/workproject/Langchain-Chatchat-gen-v1.0.2/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/algo/workproject/Langchain-Chatchat-gen-v1.0.2/server/knowledge_base/migrate.py", line 125, in folder2db
    kb.clear_vs()
  File "/home/algo/workproject/Langchain-Chatchat-gen-v1.0.2/server/knowledge_base/kb_service/base.py", line 90, in clear_vs
    status = delete_files_from_db(self.kb_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algo/workproject/Langchain-Chatchat-gen-v1.0.2/server/db/session.py", line 26, in wrapper
    result = f(session, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algo/workproject/Langchain-Chatchat-gen-v1.0.2/server/db/repository/knowledge_file_repository.py", line 156, in delete_files_from_db
    session.query(KnowledgeFileModel).filter(KnowledgeFileModel.kb_name.ilike(knowledge_base_name)).delete(
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 3182, in delete
    self.session.execute(
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1936, in orm_execute_statement
    return super().orm_execute_statement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/algo/anaconda3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: DELETE FROM knowledge_file WHERE lower(knowledge_file.kb_name) LIKE lower(?)]
[parameters: ('ktxxfz_ess0h',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-m3
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus
- 操作系统及版本 / Operating system and version:ubuntu
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by hanwsf** [comment]
milvus建议使用2.4版本， 用sh启动。
用miluvs对ids支持不够好，删除向量等目前还有问题。
