### ISSUE TITLE
[BUG必现] 并发请求知识库api服务出现报错：ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by SupremeJulyan** [chatchat-space/Langchain-Chatchat#3935]
**问题描述 / Problem Description**
800个线程去post http://0.0.0.0:7861/chat/knowledge_base_chat 开始结果正常，后续结果持续报错：
```
2024-04-30 22:25:02 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-04-30 22:25:02 | ERROR | stderr | Traceback (most recent call last):
2024-04-30 22:25:02 | ERROR | stderr |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/responses.py", line 261, in __call__
2024-04-30 22:25:02 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-04-30 22:25:02 | ERROR | stderr |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/responses.py", line 257, in wrap
2024-04-30 22:25:02 | ERROR | stderr |     await func()
2024-04-30 22:25:02 | ERROR | stderr |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/responses.py", line 234, in listen_for_disconnect
2024-04-30 22:25:02 | ERROR | stderr |     message = await receive()
2024-04-30 22:25:02 | ERROR | stderr |               ^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 568, in receive
2024-04-30 22:25:02 | ERROR | stderr |     await self.message_event.wait()
2024-04-30 22:25:02 | ERROR | stderr |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/asyncio/locks.py", line 213, in wait
2024-04-30 22:25:02 | ERROR | stderr |     await fut
2024-04-30 22:25:02 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f9a0164b9d0
2024-04-30 22:25:02 | ERROR | stderr | 
2024-04-30 22:25:02 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-04-30 22:25:02 | ERROR | stderr | 
2024-04-30 22:25:02 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
2024-04-30 22:25:02 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-04-30 22:25:02 | ERROR | stderr |   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     raise exc
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-30 22:25:02 | ERROR | stderr |   |     raise exc
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-30 22:25:02 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
2024-04-30 22:25:02 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-04-30 22:25:02 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-04-30 22:25:02 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-30 22:25:02 | ERROR | stderr |   |     raise exc
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-30 22:25:02 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
2024-04-30 22:25:02 | ERROR | stderr |   |     await response(scope, receive, send)
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/responses.py", line 254, in __call__
2024-04-30 22:25:02 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-04-30 22:25:02 | ERROR | stderr |   |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
2024-04-30 22:25:02 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-04-30 22:25:02 | ERROR | stderr |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-04-30 22:25:02 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-04-30 22:25:02 | ERROR | stderr |     | Traceback (most recent call last):
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
2024-04-30 22:25:02 | ERROR | stderr |     |     yield
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
2024-04-30 22:25:02 | ERROR | stderr |     |     resp = await self._pool.handle_async_request(req)
2024-04-30 22:25:02 | ERROR | stderr |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
2024-04-30 22:25:02 | ERROR | stderr |     |     raise exc from None
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
2024-04-30 22:25:02 | ERROR | stderr |     |     response = await connection.handle_async_request(
2024-04-30 22:25:02 | ERROR | stderr |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
2024-04-30 22:25:02 | ERROR | stderr |     |     return await self._connection.handle_async_request(request)
2024-04-30 22:25:02 | ERROR | stderr |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
2024-04-30 22:25:02 | ERROR | stderr |     |     raise exc
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
2024-04-30 22:25:02 | ERROR | stderr |     |     ) = await self._receive_response_headers(**kwargs)
2024-04-30 22:25:02 | ERROR | stderr |     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
2024-04-30 22:25:02 | ERROR | stderr |     |     event = await self._receive_event(timeout=timeout)
2024-04-30 22:25:02 | ERROR | stderr |     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
2024-04-30 22:25:02 | ERROR | stderr |     |     data = await self._network_stream.read(
2024-04-30 22:25:02 | ERROR | stderr |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 31, in read
2024-04-30 22:25:02 | ERROR | stderr |     |     with map_exceptions(exc_map):
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/contextlib.py", line 158, in __exit__
2024-04-30 22:25:02 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-04-30 22:25:02 | ERROR | stderr |     |     raise to_exc(exc) from exc
2024-04-30 22:25:02 | ERROR | stderr |     | httpcore.ReadTimeout
2024-04-30 22:25:02 | ERROR | stderr |     |
2024-04-30 22:25:02 | ERROR | stderr |     | The above exception was the direct cause of the following exception:
2024-04-30 22:25:02 | ERROR | stderr |     |
2024-04-30 22:25:02 | ERROR | stderr |     | Traceback (most recent call last):
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/responses.py", line 257, in wrap
2024-04-30 22:25:02 | ERROR | stderr |     |     await func()
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/starlette/responses.py", line 246, in stream_response
2024-04-30 22:25:02 | ERROR | stderr |     |     async for chunk in self.body_iterator:
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/fastchat/serve/openai_api_server.py", line 473, in chat_completion_stream_generator
2024-04-30 22:25:02 | ERROR | stderr |     |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/fastchat/serve/openai_api_server.py", line 649, in generate_completion_stream
2024-04-30 22:25:02 | ERROR | stderr |     |     async with client.stream(
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/contextlib.py", line 210, in __aenter__
2024-04-30 22:25:02 | ERROR | stderr |     |     return await anext(self.gen)
2024-04-30 22:25:02 | ERROR | stderr |     |            ^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_client.py", line 1602, in stream
2024-04-30 22:25:02 | ERROR | stderr |     |     response = await self.send(
2024-04-30 22:25:02 | ERROR | stderr |     |                ^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_client.py", line 1646, in send
2024-04-30 22:25:02 | ERROR | stderr |     |     response = await self._send_handling_auth(
2024-04-30 22:25:02 | ERROR | stderr |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
2024-04-30 22:25:02 | ERROR | stderr |     |     response = await self._send_handling_redirects(
2024-04-30 22:25:02 | ERROR | stderr |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
2024-04-30 22:25:02 | ERROR | stderr |     |     response = await self._send_single_request(request)
2024-04-30 22:25:02 | ERROR | stderr |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_client.py", line 1748, in _send_single_request
2024-04-30 22:25:02 | ERROR | stderr |     |     response = await transport.handle_async_request(request)
2024-04-30 22:25:02 | ERROR | stderr |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_transports/default.py", line 370, in handle_async_request
2024-04-30 22:25:02 | ERROR | stderr |     |     with map_httpcore_exceptions():
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/contextlib.py", line 158, in __exit__
2024-04-30 22:25:02 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-04-30 22:25:02 | ERROR | stderr |     |   File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
2024-04-30 22:25:02 | ERROR | stderr |     |     raise mapped_exc(message) from exc
2024-04-30 22:25:02 | ERROR | stderr |     | httpx.ReadTimeout
2024-04-30 22:25:02 | ERROR | stderr |     +------------------------------------
2024-04-30 22:25:02,790 - utils.py[line:38] - ERROR: peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_transports/default.py", line 252, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
    raise exc from None
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
    async for part in self._stream:
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
    raise exc
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_async/http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xx/chatglm3_lab/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/openai/_streaming.py", line 116, in __aiter__
    async for item in self._iterator:
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/openai/_streaming.py", line 129, in __stream__
    async for sse in iterator:
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/openai/_streaming.py", line 120, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/openai/_streaming.py", line 231, in aiter
    async for line in iterator:
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_models.py", line 967, in aiter_lines
    async for text in self.aiter_text():
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_models.py", line 954, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_models.py", line 933, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_models.py", line 991, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_client.py", line 147, in __aiter__
    async for chunk in self._stream:
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_transports/default.py", line 251, in __aiter__
    with map_httpcore_exceptions():
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/xx/anaconda3/envs/RAG/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-04-30 22:25:02,790 - utils.py[line:40] - ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)
```

**复现问题的步骤 / Steps to Reproduce**
测试代码如下：
```
# -- coding:utf-8 --
import threading
import time
import requests

url = "http://0.0.0.0:7861/chat/knowledge_base_chat"  # 与知识库对话接口
model_name = 'chatglm3-6b'
headers={'Connection':'close'}


Request_Body = {
  "query": "",
  "knowledge_base_name": "samples",
  "top_k": 20,
  "score_threshold": 1,
  "history": [
    {
      "role": "user",
      "content": `"我们来玩成语接龙，我先来，生龙活虎"`
    },
    {
      "role": "assistant",
      "content": "虎头虎脑"
    }
  ],
  "stream": False,
  "model_name": model_name,
  "temperature": 0.7,
  "max_tokens": 0,
  "prompt_name": "default",
}


class post_routine(threading.Thread):
    count_200 = 0
    count_else = 0

    def __init__(self, threadID, name, question):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.name = name
        self.question = question

    def run(self):
        time.sleep(2)
        #设置重连次数
        requests.adapters.DEFAULT_RETRIES = 5
        s = requests.session()
        # 设置连接活跃状态为False
        s.keep_alive = False
        Request_Body.update({"query":self.question})
        with requests.post(url, json=Request_Body,headers=headers) as response:
          if response.status_code == 200:
              post_routine.count_200 += 1
          else:
              post_routine.count_else += 1


if __name__ == '__main__':
    questions = ['李华是谁？',‘小红是谁?’]
    # 请求总数
    TOTAL_REQUEST = 800
    # 问题总数
    TOTAL_QUESTION = len(questions)
    post_threads = []
    for i in range(TOTAL_REQUEST):
        thread = post_routine(i, f'Thread-{i}', questions[i % TOTAL_QUESTION])
        post_threads.append(thread)
          
    for i in post_threads:
        i.start()
        time.sleep(0.005)

    for i in post_threads:
        i.join()
```
 
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:linux 6.2.0-39-generic
- Python 版本 / Python version: 3.11.7

**Comment by zRzRzRzRzRzRzR** [comment]
这个仓库没有设计并发
