### ISSUE TITLE
往向量库上传文件报错：TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by b2383355038** [chatchat-space/Langchain-Chatchat#3952]
**问题描述 / Problem Description**
在知识库上传csv文件时发生报错

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup -a'
2. 点击 '知识库管理'
3. 滚动到 '上传文件.'
4. 问题出现 /报错
**预期的结果 / Expected Result**
成功的传入到faiss向量库中

**实际结果 / Actual Result**
报错信息：：
2024-05-07 09:45:16,936 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-05-07 09:45:16,936 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-05-07 09:45:16,937 - utils.py[line:95] - ERROR: ConnectError: error when post /knowledge_base/search_docs: [Errno 111] Connection refused
2024-05-07 09:45:16.937 Uncaught app exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/lc/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/mnt/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/mnt/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 330, in knowledge_base_page
    data = [
           ^
  File "/mnt/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 331, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.10
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：文心一言4.0
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: 阿里云服务器 
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
使用sample数据库能成功吗

**Comment by b2383355038** [comment]
> 使用sample数据库能成功吗

我没有试，这个好像是接口直接就断开啦

**Comment by zRzRzRzRzRzRzR** [comment]
你试试本地 命令行跑一下

**Comment by b2383355038** [comment]
> 你试试本地 命令行跑一下

我试过了不行一直报这个错

**Comment by zRzRzRzRzRzRzR** [comment]
你的内容是什么格式的

**Comment by b2383355038** [comment]
csv格式的

**Comment by zRzRzRzRzRzRzR** [comment]
csv是qa两列吗，一般是两列

**Comment by b2383355038** [comment]
不是 就一列5万行，都是一些公司名称

**Comment by zRzRzRzRzRzRzR** [comment]
那应该户出现这个问题，一列没发做embed

**Comment by b2383355038** [comment]
但是我之前可以穿进去现在也是穿进去了几十个但现在一直传不进去

**Comment by aben1900** [comment]
搞了一个开源，连基本的运行都做不到，唉，这些错误都是直接就能发现的呀，真是看不懂，我也是出了这个问题。
一个128k的模型无限自问自答只能弃用，一个langchain加载个人库报这个错，感觉也完全用不起来

2024-05-27 16:32:22,181 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/create_knowledge_base: timed out
2024-05-27 16:36:43,277 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/search_docs: timed out
2024-05-27 16:36:43.277 Uncaught app exception
Traceback (most recent call last):
  File "/root/langchain_pip/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/sdb/chatgpt/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/sdb/chatgpt/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 330, in knowledge_base_page
    data = [
           ^
  File "/sdb/chatgpt/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 331, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by liwei413519** [comment]
解决了，需要把知识阈值修改为1.0默认就是这个不能改！！！！！！！

**Comment by liwei413519** [comment]
SCORE_THRESHOLD = 1.0  不能修改否则就会报错！！！！！

**Comment by aben1900** [comment]
在哪个文件修改？

**Comment by rookie0w0** [comment]
> 在哪个文件修改？

在configs下的kb_config.py

**Comment by HappyJimmyBoy** [comment]
2024-07-18 拉取main分支同样有这个问题,拉取dev分支一切正常了.
