### ISSUE TITLE
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=invalid input, length of string exceeds max length. length: 68919, max length: 65535)>

### ISSUE THREAD

**Issue by zmwstu** [chatchat-space/Langchain-Chatchat#3981]
2024-05-09 13:37:57,767 - decorators.py[line:146] - ERROR: RPC error: [batch_insert], <ParamError: (code=1, message=invalid input, length of string exceeds max length. length: 68919, max length: 65535)>, <Time:{'RPC start': '2024-05-09 13:37:57.766483', 'RPC error': '2024-05-09 13:37:57.767291'}>
2024-05-09 13:37:57,767 - milvus.py[line:595] - ERROR: Failed to insert batch starting at entity: 2000/37433
Traceback (most recent call last):
  File "/home/zwm/Code_Program/Chatchat/milvus-Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/zwm/Code_Program/Chatchat/milvus-Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/home/zwm/Code_Program/Chatchat/milvus-Langchain-Chatchat/server/knowledge_base/migrate.py", line 113, in files2vs
    kb.add_doc(kb_file=kb_file, not_refresh_vs_cache=True)
  File "/home/zwm/Code_Program/Chatchat/milvus-Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 131, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/Code_Program/Chatchat/milvus-Langchain-Chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 83, in do_add_doc
    ids = self.milvus.add_documents(docs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 598, in add_texts
    raise e
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 592, in add_texts
    res = self.col.insert(insert_list, timeout=timeout, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 500, in insert
    return conn.batch_insert(
           ^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 575, in batch_insert
    raise err from err
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 558, in batch_insert
    request = self._prepare_batch_insert_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 542, in _prepare_batch_insert_request
    else Prepare.batch_insert_param(collection_name, entities, partition_name, fields_info)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 531, in batch_insert_param
    return cls._parse_batch_request(request, entities, fields_info, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 507, in _parse_batch_request
    field_data = entity_helper.entity_to_field_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/entity_helper.py", line 374, in entity_to_field_data
    entity_to_str_arr(entity, field_info, CHECK_STR_ARRAY)
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/entity_helper.py", line 236, in entity_to_str_arr
    return convert_to_str_array(entity.get("values", []), field_info, check=check)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/entity_helper.py", line 231, in convert_to_str_array
    check_str_arr(arr, max_len)
  File "/home/zwm/miniconda3/envs/Langchain-Chatchat2/lib/python3.11/site-packages/pymilvus/client/entity_helper.py", line 216, in check_str_arr
    raise ParamError(
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=invalid input, length of string exceeds max length. length: 68919, max length: 65535)>
在执行初始化数据库之后，就出bug了

**Comment by hengxing9072** [comment]
Have you solved this problem? Is there no way for milvus to store text longer than max length: 65535?
