### ISSUE TITLE
[BUG] vllm0.3.3加速Qwen1.5系列模型，报ImportError: cannot import name 'model_schema' from 'pydantic.schema'

### ISSUE THREAD

**Issue by xqxls** [chatchat-space/Langchain-Chatchat#3985]
2024-05-10 15:14:44 | INFO | stdout | 本地vllm加速模型
/home/xqxls/git/Langchain-Chatchat/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
/home/xqxls/git/Langchain-Chatchat/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Process API Server:
Traceback (most recent call last):
  File "/home/xqxls/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/xqxls/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xqxls/git/Langchain-Chatchat/startup.py", line 456, in run_api_server
    app = create_app(run_mode=run_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xqxls/git/Langchain-Chatchat/server/api.py", line 51, in create_app
    mount_app_routes(app, run_mode=run_mode)
  File "/home/xqxls/git/Langchain-Chatchat/server/api.py", line 77, in mount_app_routes
    mount_knowledge_routes(app)
  File "/home/xqxls/git/Langchain-Chatchat/server/api.py", line 142, in mount_knowledge_routes
    from server.chat.agent_chat import agent_chat
  File "/home/xqxls/git/Langchain-Chatchat/server/chat/agent_chat.py", line 15, in <module>
    from server.agent.custom_agent.ChatGLM3Agent import initialize_glm3_agent
  File "/home/xqxls/git/Langchain-Chatchat/server/agent/custom_agent/ChatGLM3Agent.py", line 9, in <module>
    from pydantic.schema import model_schema
ImportError: cannot import name 'model_schema' from 'pydantic.schema' (/home/xqxls/git/Langchain-Chatchat/venv/lib/python3.11/site-packages/pydantic/schema.py)

**Comment by KrisWongz** [comment]
@xqxls  请问这个问题解决了吗
