### ISSUE TITLE
知识库问答报错API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by Liwan-Chen** [chatchat-space/Langchain-Chatchat#4077]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LiWanChen\Downloads\docker-talentai-python-chat-test\webui_pages\utils.py", line 167, in ret_sync
    for chunk in r.iter_text(None):
  File "C:\Users\LiWanChen\Prefix\envs\chatchat\Lib\site-packages\httpx\_models.py", line 849, in iter_text
    for byte_content in self.iter_bytes():
  File "C:\Users\LiWanChen\Prefix\envs\chatchat\Lib\site-packages\httpx\_models.py", line 828, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "C:\Users\LiWanChen\Prefix\envs\chatchat\Lib\site-packages\httpx\_models.py", line 886, in iter_raw
    for raw_stream_bytes in self.stream:
  File "C:\Users\LiWanChen\Prefix\envs\chatchat\Lib\site-packages\httpx\_client.py", line 123, in __iter__
    for chunk in self._stream:
  File "C:\Users\LiWanChen\Prefix\envs\chatchat\Lib\site-packages\httpx\_transports\default.py", line 109, in __iter__
    with map_httpcore_exceptions():
  File "C:\Users\LiWanChen\Prefix\envs\chatchat\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\LiWanChen\Prefix\envs\chatchat\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**Comment by danny-zhu** [comment]
python是什么版本？我也遇到了这个问题，我把python从3.11版本换成3.10以后问题这个问题没有出现过。

**Comment by danny-zhu** [comment]
可以试试把model_config中用的模型路径写完整就可以解决了。MODEL_ROOT_PATH这参数可能是有的地方没有自动拼接上，我还没来得及去逐行排查代码，你们遇到可以试试看。

**Comment by liwei413519** [comment]
解决了吗
