### ISSUE TITLE
Tesla M40不支持吗?

### ISSUE THREAD

**Issue by a442509097** [chatchat-space/Langchain-Chatchat#4078]
Maxwell架构的, 环境部署应该是没问题的(Windows), 因为我用P106(Pascal架构)运行是没问题, 是跟xformers有关, 还是跟模型有关(Qwen1.5-1.8B-Chat-GPTQ-Int4), 还是工具本身不支持? 

```
2024-05-24 16:25:04,333 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "I:\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 553, in agenerate_prompt
    return await self.agenerate(
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 513, in agenerate
    raise exceptions[0]
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 616, in _agenerate_with_cache
    return await self._agenerate(
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\chat_models\openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 86, in agenerate_from_stream
    async for chunk in stream:
  File "I:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\chat_models\openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-05-24 16:25:04,339 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
```

**Comment by a442509097** [comment]
哦, 好了, 应该是Qwen1.5-1.8B-Chat-GPTQ-Int4模型不支持, 我用chatglm3-6b模型就可以了. chatglm3-6b大概会占到12G的显存

**Comment by a442509097** [comment]
有人试过llama3-8b的模型, 我试了双卡总共18g都不够, 没找到多显卡每张显卡的分配比例设置, 因为我看到一张显卡显存直接满了, 而另一张显卡显存动都没动.  总是会先跑在固定的那张显卡, 显卡编号顺序调换或调换物理显卡插槽都没用, 没搞懂显存自动分配机制, 要是能像text-generation-webui那样设置载入指定层到显卡和设置每张卡分配比例就好了.
