### ISSUE TITLE
启动startup.py,即便显卡不存在运行进程，依然显示报错：torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB. GPU 0 has a total capacty of 21.99 GiB of which 119.06 MiB is free

### ISSUE THREAD

**Issue by a898569012** [chatchat-space/Langchain-Chatchat#4136]
尝试了accelerate config ,CUDA_VISIBLE_DEVICES=1,2 或在startup.py的176行修改gpu编号均出现以下问题

`~/Langchain-Chatchat$ python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-167-generic-x86_64-with-glibc2.31.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-14B', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/wangzhixiang/Qwen-14B',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-06-05 09:56:28,557 - startup.py[line:655] - INFO: 正在启动服务：
2024-06-05 09:56:28,557 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /home/wangzhixiang/Langchain-Chatchat/logs
/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-06-05 09:56:33 | ERROR | stderr | INFO:     Started server process [2293753]
2024-06-05 09:56:33 | ERROR | stderr | INFO:     Waiting for application startup.
2024-06-05 09:56:33 | ERROR | stderr | INFO:     Application startup complete.
2024-06-05 09:56:33 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-06-05 09:56:34 | INFO | model_worker | Register to controller
2024-06-05 09:56:34 | INFO | model_worker | Loading the model ['Qwen-14B'] on worker 07c851a3 ...
2024-06-05 09:56:34 | WARNING | transformers_modules.Qwen-14B.modeling_qwen | Try importing flash-attention for faster inference...
2024-06-05 09:56:34 | WARNING | transformers_modules.Qwen-14B.modeling_qwen | Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
2024-06-05 09:56:34 | WARNING | transformers_modules.Qwen-14B.modeling_qwen | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
2024-06-05 09:56:34 | WARNING | transformers_modules.Qwen-14B.modeling_qwen | Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards:   0%|                                                                                             | 0/15 [00:00<?, ?it/s]
Loading checkpoint shards:   7%|█████▋                                                                               | 1/15 [00:00<00:03,  3.72it/s]
Loading checkpoint shards:  13%|███████████▎                                                                         | 2/15 [00:00<00:03,  3.85it/s]
Loading checkpoint shards:  20%|█████████████████                                                                    | 3/15 [00:00<00:03,  3.95it/s]
Loading checkpoint shards:  27%|██████████████████████▋                                                              | 4/15 [00:01<00:02,  4.00it/s]
Loading checkpoint shards:  33%|████████████████████████████▎                                                        | 5/15 [00:01<00:02,  4.04it/s]
Loading checkpoint shards:  40%|██████████████████████████████████                                                   | 6/15 [00:01<00:02,  4.05it/s]
Loading checkpoint shards:  47%|███████████████████████████████████████▋                                             | 7/15 [00:01<00:01,  4.08it/s]
Loading checkpoint shards:  53%|█████████████████████████████████████████████▎                                       | 8/15 [00:01<00:01,  4.09it/s]
Loading checkpoint shards:  60%|███████████████████████████████████████████████████                                  | 9/15 [00:02<00:01,  4.09it/s]
Loading checkpoint shards:  67%|████████████████████████████████████████████████████████                            | 10/15 [00:02<00:01,  3.87it/s]
Loading checkpoint shards:  73%|█████████████████████████████████████████████████████████████▌                      | 11/15 [00:02<00:01,  3.77it/s]
Loading checkpoint shards:  80%|███████████████████████████████████████████████████████████████████▏                | 12/15 [00:03<00:00,  3.71it/s]
Loading checkpoint shards:  87%|████████████████████████████████████████████████████████████████████████▊           | 13/15 [00:03<00:00,  3.66it/s]
Loading checkpoint shards:  93%|██████████████████████████████████████████████████████████████████████████████▍     | 14/15 [00:03<00:00,  3.64it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.69it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.84it/s]
2024-06-05 09:56:39 | ERROR | stderr | 
2024-06-05 09:56:43 | ERROR | stderr | Process model_worker - Qwen-14B:
2024-06-05 09:56:43 | ERROR | stderr | Traceback (most recent call last):
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-06-05 09:56:43 | ERROR | stderr |     self.run()
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-06-05 09:56:43 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-06-05 09:56:43 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-06-05 09:56:43 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-06-05 09:56:43 | ERROR | stderr |     worker = ModelWorker(
2024-06-05 09:56:43 | ERROR | stderr |              ^^^^^^^^^^^^
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-06-05 09:56:43 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-06-05 09:56:43 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 362, in load_model
2024-06-05 09:56:43 | ERROR | stderr |     model.to(device)
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2595, in to
2024-06-05 09:56:43 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-06-05 09:56:43 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
2024-06-05 09:56:43 | ERROR | stderr |     return self._apply(convert)
2024-06-05 09:56:43 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-06-05 09:56:43 | ERROR | stderr |     module._apply(fn)
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-06-05 09:56:43 | ERROR | stderr |     module._apply(fn)
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-06-05 09:56:43 | ERROR | stderr |     module._apply(fn)
2024-06-05 09:56:43 | ERROR | stderr |   [Previous line repeated 2 more times]
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
2024-06-05 09:56:43 | ERROR | stderr |     param_applied = fn(param)
2024-06-05 09:56:43 | ERROR | stderr |                     ^^^^^^^^^
2024-06-05 09:56:43 | ERROR | stderr |   File "/home/wangzhixiang/anaconda3/envs/chat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
2024-06-05 09:56:43 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-06-05 09:56:43 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 09:56:43 | ERROR | stderr | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB. GPU 0 has a total capacty of 21.99 GiB of which 119.06 MiB is free. Including non-PyTorch memory, this process has 21.86 GiB memory in use. Of the allocated memory 21.64 GiB is allocated by PyTorch, and 88.00 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

显卡状态：

![微信图片_20240605180932](https://github.com/chatchat-space/Langchain-Chatchat/assets/148635916/1bcdf732-49d5-4609-b747-4e01e650d299)

- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-14B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- Python 版本 / Python version: 3.11.7

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by a898569012** [comment]
在进行其他任务的时候不存在这种情况 CUDA_VISIBLE_DEVICES指定显卡是有效的  应该可以排除环境造成的问题

**Comment by ilovesouthpark** [comment]
#3764 
参考一下我这里的设置？用两块gpu就行，3块会更慢。
