### ISSUE TITLE
[BUG] 使用qwen-api在线模型报错ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by fengzengfly** [chatchat-space/Langchain-Chatchat#4149]
**问题描述 / Problem Description**
使用qwen-api在线模型报错ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read).

**复现问题的步骤 / Steps to Reproduce**
1. 执行 ‘python startup.py -a’
2. 执行命令: ``` curl -X 'POST' \
  'http://127.0.0.1:7861/chat/chat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "恼羞成怒",
  "conversation_id": "123456",
  "history_len": -1,
  "history": [
    {
      "role": "user",
      "content": "我们来玩成语接龙，我先来，生龙活虎"
    },
    {
      "role": "assistant",
      "content": "虎头虎脑"
    }
  ],
  "stream": true,
  "model_name": "qwen-api",
  "temperature": 0.7,
  "max_tokens": 8000,
  "prompt_name": "default"
}' ```
3. 终端log显示：``` - INFO: HTTP Request: POST http://127.0.0.1:58002/v1/chat/completions "HTTP/1.1 200 OK"
```
4. 问题出现 /  Exception in ASGI application

**预期的结果 / Expected Result**
正常响应.

**实际结果 / Actual Result**
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/workspace/Langchain-Chatchat/server/chat/chat.py", line 103, in chat_iterator
    {"text": answer, "message_id": message_id},


**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.8
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- Python 版本 / Python version: 3.10

**Comment by liunux4odoo** [comment]
更新到 0.2.x 的最新版再试试。
