### ISSUE TITLE
0.2.10版本无法与Qwen2正常对话

### ISSUE THREAD

**Issue by zhongzhubailong** [chatchat-space/Langchain-Chatchat#4152]
能与Qwen1.5正常对话，但Qwen2不行

`  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

D:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\chat_models\__init__.py:32: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
D:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\llms\__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import OpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
D:\Langchain-Chatchat\Miniconda3\lib\site-packages\langchain\_api\module_import.py:92: LangChainDeprecationWarning: Importing JSONLoader from langchain.document_loaders is deprecated. Please replace deprecated imports:

>> from langchain.document_loaders import JSONLoader

with new imports of:

>> from langchain_community.document_loaders import JSONLoader
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here https://python.langchain.com/v0.2/docs/versions/v0_2/
  warn_deprecated(
2024-06-08 12:34:36,049 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49323 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-06-08 12:34:36,052 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-06-08 12:34:36,171 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49323 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-06-08 12:34:36,173 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49323 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-06-08 12:34:36,198 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-06-08 12:34:51,896 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49338 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-06-08 12:34:51,898 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-06-08 12:34:51,913 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49338 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-06-08 12:34:51,915 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49338 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-06-08 12:34:51,941 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49338 - "POST /chat/chat HTTP/1.1" 200 OK
2024-06-08 12:34:51,948 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\_api\deprecation.py:119: LangChainDeprecationWarning: The class `ChatOpenAI` was deprecated in LangChain 0.0.10 and will be removed in 0.3.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\_api\deprecation.py:119: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 0.3.0. Use RunnableSequence, e.g., `prompt | llm` instead.
  warn_deprecated(
D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\_api\deprecation.py:119: LangChainDeprecationWarning: The method `Chain.acall` was deprecated in langchain 0.1.0 and will be removed in 0.3.0. Use ainvoke instead.
  warn_deprecated(
2024-06-08 12:34:52 | INFO | stdout | INFO:     127.0.0.1:49341 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-06-08 12:34:52,074 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-06-08 12:34:52 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-06-08 12:34:52,989 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "D:\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\_api\deprecation.py", line 157, in awarning_emitting_wrapper
    return await wrapped(*args, **kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\base.py", line 433, in acall
    return await self.ainvoke(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\base.py", line 217, in ainvoke
    raise e
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\base.py", line 208, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\llm.py", line 298, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\chains\llm.py", line 165, in agenerate
    return await self.llm.agenerate_prompt(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 609, in agenerate_prompt
    return await self.agenerate(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 569, in agenerate
    raise exceptions[0]
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 754, in _agenerate_with_cache
    result = await self._agenerate(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\chat_models\openai.py", line 527, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 101, in agenerate_from_stream
    async for chunk in stream:
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\chat_models\openai.py", line 496, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-06-08 12:34:52,991 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()`

**Comment by zRzRzRzRzRzRzR** [comment]
要等0.3.0了
GLM-4 Qwen2都不支持
