### ISSUE TITLE
【问题】model_config.py 文件里面配置了 LLM_MODELS = ["Qwen-1_8B-Chat"]，但是启动后，在WEB发送chat到本地，会走 openai 的代码

### ISSUE THREAD

**Issue by Zyred9** [chatchat-space/Langchain-Chatchat#4165]
[修改的配置项]
model_config.py
LLM_MODELS = ["Qwen-1_8B-Chat"]
LLM_DEVICE = "cpu"
MODEL_PATH = {
    "embed_model": {
         # 此处省略未改动部分
        "bge-large-zh-v1.5": "D:\\workspces\\llm_space\\bge-large-zh-v1.5\\"
     },
     "llm_model": {
        "Qwen-1_8B-Chat": "D:\\workspaces\\llm_space\\Qwen-1_8B-Chat\\",
     }
}

按照官方教程一步步实现，启动完成后访问 http://127.0.0.1:8501/ 地址：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39330403/633cb48f-8ff9-4904-9b2d-fa2f9718b27d)

向后端发送信息  “hi”，后端报错如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39330403/4f78b0fc-3008-456d-8f51-d086e2aa073d)

完整的报错信息：

2024-06-11 15:23:01,615 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-06-11 15:23:04 | INFO | stdout | INFO:     127.0.0.1:55927 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-06-11 15:23:04,405 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-06-11 15:23:04 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-06-11 15:23:06,070 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "D:\workspaces\ai_space\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain_community\chat_models\openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "D:\workspaces\ai_space\Langchain-Chatchat\.venv\Lib\site-packages\langchain_community\chat_models\openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-06-11 15:23:06,071 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

请问一下各位大佬，如何解决呀，拜托

**Comment by Zyred9** [comment]
补充一下，langchain-chatchat 代码是今天下载的 main 分支

**Comment by urev** [comment]
我也遇到了.

**Comment by urev** [comment]
我按照这个做了修改，问题解决了：https://github.com/chatchat-space/Langchain-Chatchat/issues/4032#issuecomment-2132539611

**Comment by git-quanxin** [comment]
@Zyred9 同样问题，请问解决了吗
