### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by TJSL0715** [chatchat-space/Langchain-Chatchat#4178]
使用python startup.py -a命令运行代码可以正常使用聊天以及加载知识库

使用 streamlit run webui.py命令运行代码时出现bug
2024-06-13 00:24:37,967 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-06-13 00:24:37,967 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-06-13 00:24:37,968 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-06-13 00:24:38,070 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-06-13 00:24:38,070 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-06-13 00:24:38,070 - utils.py[line:95] - ERROR: ConnectError: error when post /llm_model/list_running_models: [Errno 111] Connection refused
2024-06-13 00:24:38.070 Uncaught app exception
Traceback (most recent call last):
File "anaconda3/envs/py39/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
File "Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 163, in dialogue_page
    running_models = list(api.list_running_models())
TypeError: 'NoneType' object is not iterable

**Comment by wowkie83** [comment]
同样的问题，请问解决了吗

**Comment by blankspark** [comment]
同求，问题解决了吗

**Comment by liunux4odoo** [comment]
webui 不能单独运行，他需要 api 提供服务
