### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。  hp, ht, pid, tid = _winapi.CreateProcess(executable, args,                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by Hotlat6077** [chatchat-space/Langchain-Chatchat#4225]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\langChain\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Anaconda3\envs\langChain\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Langchain-Chatchat\startup.py", line 467, in run_webui
    p = subprocess.Popen(cmd)
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\langChain\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda3\envs\langChain\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Hotlat6077** [comment]
我好像解决了，安装了pip install streamlit
