### ISSUE TITLE
[BUG] pre-release 版本在最后初始化知识库时报错AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by binxuan98** [chatchat-space/Langchain-Chatchat#4232]
**问题描述 / Problem Description**
pre-release 版本在最后初始化知识库时报错AttributeError: 'NoneType' object has no attribute 'get'

(chatchat) user@a100:~/chatchat-data$ chatchat-kb -r
Process Model providers Server:
Traceback (most recent call last):
  File "/env/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/env/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/env/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/init_database.py", line 29, in run_init_model_provider
    init_server(model_platforms_shard=model_platforms_shard,
  File "/env/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/init_server.py", line 42, in init_server
    .build()
  File "/env/anaconda3/envs/chatchat/lib/python3.10/site-packages/model_providers/__init__.py", line 88, in build
    ) = _to_custom_provide_configuration(cfg)
  File "/env/anaconda3/envs/chatchat/lib/python3.10/site-packages/model_providers/__init__.py", line 39, in _to_custom_provide_configuration
    model_credential = item.get("model_credential")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
