### ISSUE TITLE
V0.3版本_core_config.py报错AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by zting111** [chatchat-space/Langchain-Chatchat#4261]
运行python startup.py 和 chatchat -config指令时都会报错

(chatchat3) [root@localhost Langchain-Chatchat-0.3.0]# chatchat-config --help
Traceback (most recent call last):
  File "/home/opt/anaconda3/envs/chatchat3/bin/chatchat-config", line 5, in <module>
    from chatchat.config_work_space import main
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/config_work_space.py", line 3, in <module>
    from chatchat.configs import (
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/configs/__init__.py", line 91, in <module>
    "_basic_config.py": _import_config_mod_load("_basic_config"),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/configs/__init__.py", line 79, in _import_config_mod_load
    spec.loader.exec_module(module)
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/configs/_basic_config.py", line 166, in <module>
    config_basic_workspace: ConfigBasicWorkSpace = ConfigBasicWorkSpace()
                                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/configs/_basic_config.py", line 131, in __init__
    super().__init__()
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/configs/_core_config.py", line 71, in __init__
    config_type_json = self.get_config_by_type(self.get_type())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/configs/_core_config.py", line 115, in get_config_by_type
    return get_lambda(cfg_type)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/configs/_core_config.py", line 114, in <lambda>
    get_lambda = lambda store_cfg_type: store_cfg[self._get_store_cfg_index_by_type(store_cfg, store_cfg_type)]
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opt/anaconda3/envs/chatchat3/lib/python3.11/site-packages/chatchat/configs/_core_config.py", line 104, in _get_store_cfg_index_by_type
    if cfg.get("type") == store_cfg_type:
       ^^^^^^^
AttributeError: 'str' object has no attribute 'get'

**Comment by zting111** [comment]
原来是pre-release和正式版本冲突了，需要把主目录下面的.data文件夹删掉
