### ISSUE TITLE
[BUG]0.3.0 用openai embedding创建知识库导入文件失败 “IndexError: list index out of range”

### ISSUE THREAD

**Issue by lzt9746** [chatchat-space/Langchain-Chatchat#4262]
model_providers.yaml
```json
openai:
  model_credential:
    - model: 'text-embedding-ada-002'
      model_type: 'text-embedding'
      model_credentials:
        openai_api_key: 'sk-xxxx'
        openai_organization: ''
        openai_api_base: 'xxxx'


  provider_credential:
    openai_api_key: 'sk-xxxx'
    openai_organization: ''
    openai_api_base: 'xxx'

xinference:
  model_credential:
    - model: 'qwen2-7b-instruct'
      model_type: 'llm'
      model_credentials:
        server_url: 'http://127.0.0.1:9997/'
        model_uid: 'qwen2-7b-instruct'
    - model: 'bge-large-zh-v1.5'
      model_type: 'text-embedding'
      model_credentials:
        server_url: 'http://127.0.0.1:9997/'
        model_uid: 'bge-large-custom'
```
用本地部署的bge-large可以正常导入，用openai的模型就报错。

报错信息

2024-06-21 14:31:38,935 httpx        1598995 INFO     HTTP Request: POST https://api.gptsapi.net/v1/embeddings "HTTP/1.1 200 OK"
2024-06-21 14:31:38,940 uvicorn.access 1598995 INFO     127.0.0.1:50120 - "POST /openai/v1/embeddings HTTP/1.1" 200
2024-06-21 14:31:38,941 httpx        1599038 INFO     HTTP Request: POST http://127.0.0.1:20000/openai/v1/embeddings "HTTP/1.1 200 OK"
2024-06-21 14:31:38,949 httpx        1599084 INFO     HTTP Request: POST http://127.0.0.1:7861/knowledge_base/upload_docs "HTTP/1.1 500 Internal Server Error"
INFO:     127.0.0.1:34708 - "POST /knowledge_base/upload_docs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/Langchain-Chatchat/libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py", line 156, in upload_docs
    result = update_docs(
  File "/home/Langchain-Chatchat/libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py", line 273, in update_docs
    kb.update_doc(kb_file, not_refresh_vs_cache=True)
  File "/home/Langchain-Chatchat/libs/chatchat-server/chatchat/server/knowledge_base/kb_service/base.py", line 162, in update_doc
    return self.add_doc(kb_file, docs=docs, **kwargs)
  File "/home/Langchain-Chatchat/libs/chatchat-server/chatchat/server/knowledge_base/kb_service/base.py", line 125, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
  File "/home/Langchain-Chatchat/libs/chatchat-server/chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 82, in do_add_doc
    embeddings = vs.embeddings.embed_documents(texts)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/langchain_openai/embeddings/base.py", line 480, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
  File "/home/Langchain-Chatchat/libs/chatchat-server/.venv/lib/python3.10/site-packages/langchain_openai/embeddings/base.py", line 335, in _get_len_safe_embeddings
    results[indices[i]].append(batched_embeddings[i])
IndexError: list index out of range

**Comment by lzt9746** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/blob/aadf3ef99077dc964d40ecbb82b1f35ba006b799/libs/chatchat-server/chatchat/server/utils.py#L235-L236
这段代码改为
```python

        if model_info.get("platform_type") == "openai":
            params.update(chunk_size=1)
            return OpenAIEmbeddings(**params)
可以导入，但是每个文档切片要发送一次请求，速度很慢

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，不再使用 model_provider，在线 API 建议使用 oneapi 接入。
