### ISSUE TITLE
[BUG] zhipuai无法使用，openai.InternalServerError: Internal Server Error

### ISSUE THREAD

**Issue by li1553770945** [chatchat-space/Langchain-Chatchat#4264]
**问题描述 / Problem Description**

按照“快速上手”部分，安装chatchat后，使用zhipuai模型时，报错`openai.InternalServerError: Internal Server Error`。

**复现问题的步骤 / Steps to Reproduce**
1. 新建一个conda环境
2. 使用`pip install langchain-chatchat[xinference] -U`安装chatchat
3. 编辑`model-providers.yaml`
注释掉其他内容，只保留
```yaml
zhipuai:
 provider_credential:
   api_key: 'xxxxx'
```

4. 使用`chatchat -a`启动，随便问个问题

**预期的结果 / Expected Result**

模型正常回答

**实际结果 / Actual Result**

报错`openai.InternalServerError: Internal Server Error`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： 0.3.0.20240621.3    
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：zhipuai
- 使用的 Embedding 模型（moka-ai/m3e-base 等）： bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： 无
- 操作系统及版本 / Operating system and version: Windows-10-10.0.22631-SP0.
- Python 版本 / Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
- 其他相关环境信息 / Other relevant environment information:

完整报错信息：
```
INFO:     127.0.0.1:13427 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-06-21 16:06:10,840 httpx        12920 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\anaconda\envs\chain\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\anaconda\envs\chain\Lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "D:\anaconda\envs\chain\Lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\chatchat\server\api_server\chat_routes.py", line 51, in chat_completions
    client = get_OpenAIClient(model_name=body.model, is_async=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\chatchat\server\utils.py", line 271, in get_OpenAIClient
    assert platform_info, f"cannot find configured platform: {platform_name}"
           ^^^^^^^^^^^^^
AssertionError: cannot find configured platform: None
2024-06-21 16:06:10.852 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda\envs\chain\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "D:\anaconda\envs\chain\Lib\site-packages\chatchat\webui.py", line 71, in <module>
    dialogue_page(api=api, is_lite=is_lite)
  File "D:\anaconda\envs\chain\Lib\site-packages\chatchat\webui_pages\dialogue\dialogue.py", line 304, in dialogue_page
    for d in client.chat.completions.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\resources\chat\completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\_base_client.py", line 897, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\_base_client.py", line 973, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\_base_client.py", line 973, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chain\Lib\site-packages\openai\_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Internal Server Error

```

**Comment by li1553770945** [comment]
好像我把DEFAULT_MODEL_NAME错误的设置成了`zhipuai`。

 但是我发现了另外一个问题，yml文件里面已经改了zhipuai（如我的第一个comment所示），在请求/chat/chat/completions的API的时候，代码逻辑会根据当前model_name获取请求API的地址，但是以下逻辑会遍历所有的platform，如果当前模型存在则直用这个platform，获取API地址的时候只考虑model_name，没有platform_name。

虽然yml里面配置的是zhipuai，但是获取到的是xinterface的API地址，从而导致了连接错误。

```python
 for m_type in model_types:
            for m_name in m.get(m_type, []):
                if model_name is None or model_name == m_name:
                    result[m_name] = {
                        "platform_name": m.get("platform_name"),
                        "platform_type": m.get("platform_type"),
                        "model_type": m_type.split("_")[0],
                        "model_name": m_name,
                        "api_base_url": m.get("api_base_url"),
                        "api_key": m.get("api_key"),
                        "api_proxy": m.get("api_proxy"),
```

**Comment by xuelang001** [comment]
您好，请问应该如何在线使用智谱的API呢？具体需要改哪里啊0.3

**Comment by liunux4odoo** [comment]
智谱清言等在线 API 建议使用 oneapi 接入，0.3.1 版已经发布，详见文档。
