### ISSUE TITLE
请求api http://127.0.0.1:7861/chat/chat报错

### ISSUE THREAD

**Issue by fwx0815** [chatchat-space/Langchain-Chatchat#4273]
复现描述：
1、源码运行python startup.py -a
2、Xinference的llm
qwen2-instruct-custom 7B
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/24691319/8b94ccb6-7256-43d6-892a-6e476af0ac56)

3、请求api接口
curl -X 'POST' \
  'http://127.0.0.1:7861/chat/chat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "恼羞成怒",
  "metadata": {},
  "conversation_id": "123",
  "message_id": "123",
  "history_len": -1,
  "history": [
    {
      "content": "我们来玩成语接龙，我先来，生龙活虎",
      "role": "user"
    },
    {
      "content": "虎头虎脑",
      "role": "assistant"
    }
  ],
  "stream": true,
  "chat_model_config": {},
  "tool_config": {}
}'

错误堆栈：
INFO:     127.0.0.1:63636 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:63832 - "POST /chat/chat HTTP/1.1" 200 OK
2024-06-22 13:42:29,310 model_providers.bootstrap_web.openai_bootstrap_web 19656 INFO     Received chat completion request: {'function_call': None,
 'functions': None,
 'max_tokens': 4096,
 'messages': [{'content': 'Answer the following questions as best you can. You '
                          'have access to the following APIs:\n'
                          '\n'
                          '\n'
                          '\n'
                          'Use the following format:\n'
                          '\n'
                          'Question: the input question you must answer\n'
                          'Thought: you should always think about what to do\n'
                          'Action: the action to take, should be one of []\n'
                          'Action Input: the input to the action\n'
                          'Observation: the result of the action\n'
                          '... (this Thought/Action/Action Input/Observation '
                          'can be repeated zero or more times)\n'
                          'Thought: I now know the final answer\n'
                          'Final Answer: the final answer to the original '
                          'input question\n'
                          '\n'
                          'Format the Action Input as a JSON object.\n'
                          '\n'
                          'Begin!\n'
                          '\n'
                          'Question: 恼羞成怒\n'
                          '\n'
                          '\n'
                          '\n',
               'role': <Role.USER: 'user'>}],
 'model': 'qwen2-instruct-custom',
 'n': 1,
 'stop': ['<|endoftext|>', '<|im_start|>', '<|im_end|>', '\nObservation:'],
 'stream': False,
 'temperature': 0.9,
 'tools': None,
 'top_k': None,
 'top_p': 0.75}
2024-06-22 13:42:29,312 model_providers.bootstrap_web.openai_bootstrap_web 19656 ERROR    Error while creating chat completion: Model Parameter max_tokens should be less than or equal to 2048.0.
2024-06-22 13:42:29,313 uvicorn.access 19656 INFO     127.0.0.1:63834 - "POST /xinference/v1/chat/completions HTTP/1.1" 400
2024-06-22 13:42:29,314 httpx        10236 INFO     HTTP Request: POST http://127.0.0.1:20000/xinference/v1/chat/completions "HTTP/1.1 400 Bad Request"
2024-06-22 13:42:29,316 root         10236 ERROR    failed when request to ('qwen2-instruct-custom', 'xinference')
Traceback (most recent call last):
  File "E:\AI\Langchain-Chatchat-master\libs\chatchat-server\chatchat\server\api_server\openai_routes.py", line 56, in get_model_client
    yield get_OpenAIClient(platform_name=selected_platform, is_async=True)
  File "E:\AI\Langchain-Chatchat-master\libs\chatchat-server\chatchat\server\api_server\openai_routes.py", line 136, in create_chat_completions
    result = await openai_request(client.chat.completions.create, body)
  File "E:\AI\Langchain-Chatchat-master\libs\chatchat-server\chatchat\server\api_server\openai_routes.py", line 100, in openai_request
    result = await method(**params)
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\openai\resources\chat\completions.py", line 1334, in create
    return await self._post(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\openai\_base_client.py", line 1738, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\openai\_base_client.py", line 1441, in request
    return await self._request(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\openai\_base_client.py", line 1532, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'detail': 'Model Parameter max_tokens should be less than or equal to 2048.0.'}
2024-06-22 13:42:29,318 httpx        10236 INFO     HTTP Request: POST http://127.0.0.1:7861/v1/chat/completions "HTTP/1.1 200 OK"
2024-06-22 13:42:29,321 root         10236 ERROR    'NoneType' object has no attribute 'dict'
Traceback (most recent call last):
  File "E:\AI\Langchain-Chatchat-master\libs\chatchat-server\chatchat\server\utils.py", line 41, in wrap_done
    await fn
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_core\runnables\base.py", line 2536, in ainvoke
    input = await step.ainvoke(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain\chains\base.py", line 212, in ainvoke
    raise e
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain\chains\base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain\agents\agent.py", line 1481, in _acall
    next_step_output = await self._atake_next_step(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain\agents\agent.py", line 1275, in _atake_next_step
    [
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain\agents\agent.py", line 1275, in <listcomp>
    [
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain\agents\agent.py", line 1303, in _aiter_next_step
    output = await self.agent.aplan(
  File "E:\AI\Langchain-Chatchat-master\libs\chatchat-server\chatchat\server\agent\agent_factory\qwen_agent.py", line 44, in _aplan_without_stream
    return await self.runnable.ainvoke(inputs, config={"callbacks": callbacks})
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_core\runnables\base.py", line 2536, in ainvoke
    input = await step.ainvoke(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_core\runnables\base.py", line 4537, in ainvoke
    return await self.bound.ainvoke(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_core\language_models\chat_models.py", line 179, in ainvoke
    llm_result = await self.agenerate_prompt(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_core\language_models\chat_models.py", line 570, in agenerate_prompt
    return await self.agenerate(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_core\language_models\chat_models.py", line 530, in agenerate
    raise exceptions[0]
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_core\language_models\chat_models.py", line 715, in _agenerate_with_cache
    result = await self._agenerate(
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_openai\chat_models\base.py", line 534, in _agenerate
    return self._create_chat_result(response)
  File "E:\AI\Langchain-Chatchat-master\venv\lib\site-packages\langchain_openai\chat_models\base.py", line 455, in _create_chat_result
    response = response.dict()
AttributeError: 'NoneType' object has no attribute 'dict'
2024-06-22 13:42:29,323 root         10236 ERROR    AttributeError: Caught exception: 'NoneType' object has no attribute 'dict'

**Comment by yhfgyyf** [comment]
Langchain-Chatchat/libs/model-providers/model_providers/core/model_runtime/model_providers/xinference/llm/llm.py 中默认配置了模型max tokens为2048，可以修改这个参数，也可以在Langchain-Chatchat/libs/model-providers/model_providers/core/model_runtime/model_providers/xinference/llm目录下增加你使用的模型qwen2-instruct-custom.yaml配置文件：
`  - name: max_tokens
    use_template: max_tokens
    default: 4096`

**Comment by fwx0815** [comment]
> Langchain-Chatchat/libs/model-providers/model_providers/core/model_runtime/model_providers/xinference/llm/llm.py 中默认配置了模型max tokens为2048，可以修改这个参数，也可以在Langchain-Chatchat/libs/model-providers/model_providers/core/model_runtime/model_providers/xinference/llm目录下增加你使用的模型qwen2-instruct-custom.yaml配置文件： ` - name: max_tokens use_template: max_tokens default: 4096`

非常感谢回答，but 配置了，但不好使
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/24691319/c786b1c7-d0c7-4a4d-88f1-3da01d3717d6)

**Comment by fwx0815** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/24691319/411919b3-593b-4982-88fe-df66bda97108)

**Comment by yhfgyyf** [comment]
你出错的是xinference上的本地模型
2024-06-22 13:42:29,316 root 10236 ERROR failed when request to ('qwen2-instruct-custom', 'xinference')
修改的是tongyi的在线模型
