### ISSUE TITLE
本地知识库对话出现Internal Server Error

### ISSUE THREAD

**Issue by zhongzhubailong** [chatchat-space/Langchain-Chatchat#4284]
LLM和embedding模型均用Xinference接入，普通对话和新建知识库、添加文件到知识库和向量化都没问题，但用知识库对话的时候报错。

`  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

INFO:     127.0.0.1:49922 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:49:07,541 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49926 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:49:16,567 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49927 - "POST /chat/chat/completions HTTP/1.1" 200 OK
2024-06-23 14:49:16,642 httpx        12988 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 200 OK"
2024-06-23 14:49:16,675 model_providers.bootstrap_web.openai_bootstrap_web 10280 INFO     Received chat completion request: {'function_call': None,
 'functions': None,
 'max_tokens': 256,
 'messages': [{'content': '你好', 'role': <Role.USER: 'user'>}],
 'model': 'qwen1.5-chat',
 'n': 1,
 'stop': None,
 'stream': True,
 'temperature': 0.75,
 'tool_choice': None,
 'tools': None,
 'top_k': None,
 'top_p': 0.75}
2024-06-23 14:49:16,736 httpx        10280 INFO     HTTP Request: POST http://127.0.0.1:52855/v1/chat/completions "HTTP/1.1 200 OK"
2024-06-23 14:49:16,741 uvicorn.access 10280 INFO     127.0.0.1:49928 - "POST /xinference/v1/chat/completions HTTP/1.1" 200
2024-06-23 14:49:16,742 httpx        5552 INFO     HTTP Request: POST http://127.0.0.1:20000/xinference/v1/chat/completions "HTTP/1.1 200 OK"
D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain\_api\module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
  warnings.warn(
2024-06-23 14:49:37,253 root         5552 INFO     loading vector store in 'test/vector_store/bce-embedding-base_v1' from disk.
2024-06-23 14:49:37,293 model_providers.bootstrap_web.openai_bootstrap_web 10280 INFO     Received create_embeddings request: {'encoding_format': 'base64',
 'input': ['init'],
 'model': 'bce-embedding-base_v1'}
2024-06-23 14:49:37,294 model_providers.bootstrap_web.openai_bootstrap_web 10280 WARNING  Warning: model not found. Using cl100k_base encoding.
2024-06-23 14:49:37,646 uvicorn.access 10280 INFO     127.0.0.1:49949 - "POST /xinference/v1/embeddings HTTP/1.1" 200
2024-06-23 14:49:37,647 httpx        5552 INFO     HTTP Request: POST http://127.0.0.1:20000/xinference/v1/embeddings "HTTP/1.1 200 OK"
2024-06-23 14:49:37,658 faiss.loader 5552 INFO     Loading faiss with AVX2 support.
2024-06-23 14:49:37,911 faiss.loader 5552 INFO     Successfully loaded faiss with AVX2 support.
INFO:     127.0.0.1:49948 - "POST /knowledge_base/create_knowledge_base HTTP/1.1" 200 OK
2024-06-23 14:49:37,919 httpx        12988 INFO     HTTP Request: POST http://127.0.0.1:7861/knowledge_base/create_knowledge_base "HTTP/1.1 200 OK"
2024-06-23 14:49:58,765 root         5552 INFO     RapidOCRDocLoader used for D:\Langchain-Chatchat\miniconda3\Lib\site-packages\chatchat\data\knowledge_base\test\content\黑暗森林.docx
2024-06-23 14:49:58,930 root         5552 ERROR    ModuleNotFoundError: 从文件 test/黑暗森林.docx 加载文档时出错：No module named 'exceptions'
2024-06-23 14:49:58,931 root         5552 INFO     已将向量库 ('test', 'bce-embedding-base_v1') 保存到磁盘
INFO:     127.0.0.1:49969 - "POST /knowledge_base/upload_docs HTTP/1.1" 200 OK
2024-06-23 14:49:58,933 httpx        12988 INFO     HTTP Request: POST http://127.0.0.1:7861/knowledge_base/upload_docs "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49973 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:50:02,213 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49974 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:50:02,370 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49976 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:50:04,223 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49977 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:50:04,393 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49979 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:50:07,888 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49983 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:50:10,443 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49985 - "GET /tools HTTP/1.1" 200 OK
2024-06-23 14:50:15,764 httpx        12988 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
2024-06-23 14:50:15,847 model_providers.bootstrap_web.openai_bootstrap_web 10280 INFO     Received create_embeddings request: {'encoding_format': 'base64',
 'input': ['this is a test'],
 'model': 'bce-embedding-base_v1'}
2024-06-23 14:50:15,848 model_providers.bootstrap_web.openai_bootstrap_web 10280 WARNING  Warning: model not found. Using cl100k_base encoding.
2024-06-23 14:50:15,912 uvicorn.access 10280 INFO     127.0.0.1:49987 - "POST /xinference/v1/embeddings HTTP/1.1" 200
2024-06-23 14:50:15,913 httpx        5552 INFO     HTTP Request: POST http://127.0.0.1:20000/xinference/v1/embeddings "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49986 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-06-23 14:50:16,202 httpx        12988 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
2024-06-23 14:50:16,203 openai._base_client 12988 INFO     Retrying request to /chat/completions in 0.873646 seconds
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\api_server\chat_routes.py", line 96, in chat_completions
    tool_result = await tool.ainvoke(tool_input)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 723, in ainvoke
    return await run_in_executor(config, self.invoke, input, config, **kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\runnables\config.py", line 514, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "D:\Langchain-Chatchat\miniconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 260, in invoke
    return self.run(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 452, in run
    raise e
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 409, in run
    context.run(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 750, in _run
    else self.func(*args, **kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\agent\tools_factory\search_local_knowledgebase.py", line 51, in search_local_knowledgebase
    ret = search_knowledgebase(query=query, database=database, config=tool_config)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\agent\tools_factory\search_local_knowledgebase.py", line 36, in search_knowledgebase
    docs = search_docs(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_doc_api.py", line 39, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_service\base.py", line 181, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 66, in do_search
    retriever = get_Retriever("ensemble").from_vectorstore(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\file_rag\retrievers\ensemble.py", line 37, in from_vectorstore
    bm25_retriever = BM25Retriever.from_documents(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\retrievers\bm25.py", line 90, in from_documents
    texts, metadatas = zip(*((d.page_content, d.metadata) for d in documents))
ValueError: not enough values to unpack (expected 2, got 0)
2024-06-23 14:50:17,140 model_providers.bootstrap_web.openai_bootstrap_web 10280 INFO     Received create_embeddings request: {'encoding_format': 'base64',
 'input': ['this is a test'],
 'model': 'bce-embedding-base_v1'}
2024-06-23 14:50:17,141 model_providers.bootstrap_web.openai_bootstrap_web 10280 WARNING  Warning: model not found. Using cl100k_base encoding.
2024-06-23 14:50:17,195 uvicorn.access 10280 INFO     127.0.0.1:49992 - "POST /xinference/v1/embeddings HTTP/1.1" 200
2024-06-23 14:50:17,197 httpx        5552 INFO     HTTP Request: POST http://127.0.0.1:20000/xinference/v1/embeddings "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49991 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-06-23 14:50:17,205 httpx        12988 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\api_server\chat_routes.py", line 96, in chat_completions
    tool_result = await tool.ainvoke(tool_input)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 723, in ainvoke
    return await run_in_executor(config, self.invoke, input, config, **kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\runnables\config.py", line 514, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "D:\Langchain-Chatchat\miniconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 260, in invoke
    return self.run(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 452, in run
    raise e
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 409, in run
    context.run(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 750, in _run
    else self.func(*args, **kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\agent\tools_factory\search_local_knowledgebase.py", line 51, in search_local_knowledgebase
    ret = search_knowledgebase(query=query, database=database, config=tool_config)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\agent\tools_factory\search_local_knowledgebase.py", line 36, in search_knowledgebase
    docs = search_docs(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_doc_api.py", line 39, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_service\base.py", line 181, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 66, in do_search
    retriever = get_Retriever("ensemble").from_vectorstore(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\file_rag\retrievers\ensemble.py", line 37, in from_vectorstore
    bm25_retriever = BM25Retriever.from_documents(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\retrievers\bm25.py", line 90, in from_documents
    texts, metadatas = zip(*((d.page_content, d.metadata) for d in documents))
ValueError: not enough values to unpack (expected 2, got 0)
2024-06-23 14:50:17,207 openai._base_client 12988 INFO     Retrying request to /chat/completions in 1.902221 seconds
2024-06-23 14:50:19,171 model_providers.bootstrap_web.openai_bootstrap_web 10280 INFO     Received create_embeddings request: {'encoding_format': 'base64',
 'input': ['this is a test'],
 'model': 'bce-embedding-base_v1'}
2024-06-23 14:50:19,172 model_providers.bootstrap_web.openai_bootstrap_web 10280 WARNING  Warning: model not found. Using cl100k_base encoding.
2024-06-23 14:50:19,226 uvicorn.access 10280 INFO     127.0.0.1:50000 - "POST /xinference/v1/embeddings HTTP/1.1" 200
2024-06-23 14:50:19,227 httpx        5552 INFO     HTTP Request: POST http://127.0.0.1:20000/xinference/v1/embeddings "HTTP/1.1 200 OK"
INFO:     127.0.0.1:49999 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-06-23 14:50:19,237 httpx        12988 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\api_server\chat_routes.py", line 96, in chat_completions
    tool_result = await tool.ainvoke(tool_input)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 723, in ainvoke
    return await run_in_executor(config, self.invoke, input, config, **kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\runnables\config.py", line 514, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "D:\Langchain-Chatchat\miniconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 260, in invoke
    return self.run(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 452, in run
    raise e
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 409, in run
    context.run(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_core\tools.py", line 750, in _run
    else self.func(*args, **kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\agent\tools_factory\search_local_knowledgebase.py", line 51, in search_local_knowledgebase
    ret = search_knowledgebase(query=query, database=database, config=tool_config)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\agent\tools_factory\search_local_knowledgebase.py", line 36, in search_knowledgebase
    docs = search_docs(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_doc_api.py", line 39, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_service\base.py", line 181, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 66, in do_search
    retriever = get_Retriever("ensemble").from_vectorstore(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\server\file_rag\retrievers\ensemble.py", line 37, in from_vectorstore
    bm25_retriever = BM25Retriever.from_documents(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\langchain_community\retrievers\bm25.py", line 90, in from_documents
    texts, metadatas = zip(*((d.page_content, d.metadata) for d in documents))
ValueError: not enough values to unpack (expected 2, got 0)
2024-06-23 14:50:19.239 Uncaught app exception
Traceback (most recent call last):
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "D:\Langchain-Chatchat\miniconda3\Lib\site-packages\chatchat\webui.py", line 71, in <module>
    dialogue_page(api=api, is_lite=is_lite)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\chatchat\webui_pages\dialogue\dialogue.py", line 304, in dialogue_page
    for d in client.chat.completions.create(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\resources\chat\completions.py", line 667, in create
    return self._post(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_base_client.py", line 897, in request
    return self._request(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_base_client.py", line 973, in _request
    return self._retry_request(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_base_client.py", line 973, in _request
    return self._retry_request(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
  File "D:\Langchain-Chatchat\miniconda3\lib\site-packages\openai\_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Internal Server Error`

**Comment by cristiano-xw** [comment]
解决了吗请问

**Comment by RucLee** [comment]
同样的问题 Internal Server Error

**Comment by zhongzhubailong** [comment]
根据No module named ''的报错提示，安装了以下包之后，顺利跑通：
`pip install python-docx rapidocr_onnxruntime rank_bm25`

**Comment by zhongzhubailong** [comment]
> 解决了吗请问



> 解决了吗请问

已解决

**Comment by zhongzhubailong** [comment]
已解决。根据No module named ''的报错提示，安装了以下包之后，顺利跑通：
pip install python-docx rapidocr_onnxruntime rank_bm25
