### ISSUE TITLE
[BUG]运行chatchat -a 页面报错

### ISSUE THREAD

**Issue by wll0307** [chatchat-space/Langchain-Chatchat#4291]
2024-06-24 09:40:06.723 Uncaught app exception
Traceback (most recent call last):
  File "/root/autodl-tmp/conda/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/root/autodl-tmp/conda/envs/chatchat/lib/python3.11/site-packages/chatchat/webui.py", line 71, in <module>
    dialogue_page(api=api, is_lite=is_lite)
  File "/root/autodl-tmp/conda/envs/chatchat/lib/python3.11/site-packages/chatchat/webui_pages/dialogue/dialogue.py", line 120, in dialogue_page
    ctx = chat_box.context
          ^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/conda/envs/chatchat/lib/python3.11/site-packages/streamlit_chatbox/messages.py", line 121, in context
    self.init_session()
  File "/root/autodl-tmp/conda/envs/chatchat/lib/python3.11/site-packages/streamlit_chatbox/messages.py", line 72, in init_session
    self.reset_history(self._chat_name)
  File "/root/autodl-tmp/conda/envs/chatchat/lib/python3.11/site-packages/streamlit_chatbox/messages.py", line 80, in reset_history
    st.session_state[self._session_key][name]["history"] = []
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'default'

**Comment by HhhBbWw** [comment]
我当时好像是升级了streamlit_chatbox解决的，pip install -U streamlit_chatbox

**Comment by wll0307** [comment]
> 我当时好像升级了streamlit_chatbox解决的，pip install -U streamlit_chatbox
是在chatchat环境下吗
