### ISSUE TITLE
[BUG] 在macbook M3设备上运行启动chatchat 之后页面报错

### ISSUE THREAD

**Issue by Pan06da** [chatchat-space/Langchain-Chatchat#4298]
**问题描述 / Problem Description**
在macbook M3设备上运行启动chatchat 之后页面报错

**实际结果 / Actual Result**
Traceback (most recent call last):
  File "/Users/leioupan/anaconda3/bin/chatchat-kb", line 5, in <module>
    from chatchat.init_database import main
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/chatchat/init_database.py", line 6, in <module>
    from chatchat.server.knowledge_base.migrate import (create_tables, reset_tables, import_from_db,
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/chatchat/server/knowledge_base/migrate.py", line 10, in <module>
    from chatchat.server.knowledge_base.utils import (
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/chatchat/server/knowledge_base/utils.py", line 18, in <module>
    from chatchat.server.utils import run_in_thread_pool, run_in_process_pool
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/chatchat/server/utils.py", line 11, in <module>
    from langchain_openai.chat_models import ChatOpenAI
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/langchain_openai/__init__.py", line 1, in <module>
    from langchain_openai.chat_models import (
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/langchain_openai/chat_models/__init__.py", line 1, in <module>
    from langchain_openai.chat_models.azure import AzureChatOpenAI
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/langchain_openai/chat_models/azure.py", line 8, in <module>
    import openai
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/openai/types/__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/openai/types/batch.py", line 7, in <module>
    from .._models import BaseModel
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/openai/_models.py", line 21, in <module>
    import pydantic.generics
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/pydantic/generics.py", line 2, in <module>
    from ._migration import getattr_migration
  File "/Users/leioupan/anaconda3/lib/python3.11/site-packages/pydantic/_migration.py", line 4, in <module>
    from .version import version_short
ImportError: cannot import name 'version_short' from 'pydantic.version' (/Users/leioupan/anaconda3/lib/python3.11/site-packages/pydantic/version.cpython-311-darwin.so)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： langchain-chatchat (0.3.0.20240621.3)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Ollama加载
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：Ollama加载
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：Ollama加载
- 操作系统及版本 / Operating system and version: MacOS 14.5
- Python 版本 / Python version: 3.11

**Comment by Pan06da** [comment]
通过拉取最新的版本已经成功启动
