### ISSUE TITLE
langchain-chatchat 工具调用有返回结果，但是会出现错误    docs = d.tool_output.get("docs") 中没有docs的键值

### ISSUE THREAD

**Issue by cqray1990** [chatchat-space/Langchain-Chatchat#4300]
2024-06-24 16:08:07,796 model_providers.bootstrap_web.openai_bootstrap_web 2528736 INFO     Received chat completion request: {'function_call': None,
 'functions': None,
 'max_tokens': 256,
 'messages': [{'content': '帮我查询北京今天的天气怎么样', 'role': <Role.USER: 'user'>},
              {'content': '', 'role': <Role.ASSISTANT: 'assistant'>},
              {'content': '帮我查询深圳的天气怎么样', 'role': <Role.USER: 'user'>},
              {'content': '', 'role': <Role.ASSISTANT: 'assistant'>},
              {'content': '【指令】根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 '
                          '“根据已知信息无法回答该问题”，不允许在答案中添加编造成分，答案请使用中文。\n'
                          '\n'
                          '【已知信息】4\n'
                          '\n'
                          '【问题】帮我计算1+3等于多少',
               'role': <Role.USER: 'user'>}],
 'model': 'glm4-chat',
 'n': 1,
 'stop': None,
 'stream': True,
 'temperature': 0.75,
 'tools': None,
 'top_k': None,
 'top_p': 0.75}
===== 4
2024-06-24 16:08:07.800 Uncaught app exception
Traceback (most recent call last):
  File "anaconda3/envs/llama_factory/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "anaconda3/envs/llama_factory/lib/python3.10/site-packages/chatchat/webui.py", line 71, in <module>
    dialogue_page(api=api, is_lite=is_lite)
  File "anaconda3/envs/llama_factory/lib/python3.10/site-packages/chatchat/webui_pages/dialogue/dialogue.py", line 362, in dialogue_page
    docs = d.tool_output.get("docs")
AttributeError: 'str' object has no attribute 'get'
2024-06-24 16:08:07,838 httpx        2528736 INFO     HTTP Request: POST http://127.0.0.1:9997/v1/chat/completions "HTTP/1.1 200 OK"
2024-06-24 16:08:07,839 uvicorn.access 2528736 INFO     127.0.0.1:46452 - "POST /xinference/v1/chat/completions HTTP/1.1" 200

**Comment by liunux4odoo** [comment]
dev 已修复。
