### ISSUE TITLE
[BUG] 通过api文档,调用/chat/chat接口报错

### ISSUE THREAD

**Issue by yangjun19950118** [chatchat-space/Langchain-Chatchat#4311]
直接用api文档进行调用:
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/30163938/eba6e4b9-ef17-45a7-a92f-55e3e0958301)

报错内容:
`Traceback (most recent call last):
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 254, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
    raise exc from None
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
    async for part in self._stream:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
    raise exc
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpcore/_async/http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/home/anaconda3/envs/langchat/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/chatchat/server/utils.py", line 41, in wrap_done
    await fn
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2536, in ainvoke
    input = await step.ainvoke(
            ^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain/chains/base.py", line 212, in ainvoke
    raise e
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain/chains/base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1481, in _acall
    next_step_output = await self._atake_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1275, in _atake_next_step
    [
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1275, in <listcomp>
    [
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1303, in _aiter_next_step
    output = await self.agent.aplan(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 436, in aplan
    async for chunk in self.runnable.astream(
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2900, in astream
    async for chunk in self.atransform(input_aiter(), config, **kwargs):
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2883, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1980, in _atransform_stream_with_config
    chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2853, in _atransform
    async for output in final_pipeline:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1316, in atransform
    async for ichunk in input:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 4748, in atransform
    async for item in self.bound.atransform(
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1334, in atransform
    async for output in self.astream(final, config, **kwargs):
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 319, in astream
    raise e
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 297, in astream
    async for chunk in self._astream(
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 485, in _astream
    async for chunk in await self.async_client.create(
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/openai/_streaming.py", line 131, in __aiter__
    async for item in self._iterator:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/openai/_streaming.py", line 148, in __stream__
    async for sse in iterator:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/openai/_streaming.py", line 139, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/openai/_streaming.py", line 257, in aiter
    async for line in iterator:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_models.py", line 963, in aiter_lines
    async for text in self.aiter_text():
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_models.py", line 950, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_models.py", line 929, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_models.py", line 987, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_client.py", line 149, in __aiter__
    async for chunk in self._stream:
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 253, in __aiter__
    with map_httpcore_exceptions():
  File "/home/anaconda3/envs/langchat/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/anaconda3/envs/langchat/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)`

**Comment by imClumsyPanda** [comment]
请参考 API 调用说明

https://github.com/chatchat-space/Langchain-Chatchat/blob/dev/docs/contributing/api.md
