### ISSUE TITLE
0.3.0 初始化知识库报错

### ISSUE THREAD

**Issue by tf18536** [chatchat-space/Langchain-Chatchat#4322]
一、执行初始化知识库报错：
chatchat-kb -r --embed-model=bge-large-zh-v1.5

2024-06-25 03:54:14,567 uvicorn.error 20946 INFO     Started server process [20946]
2024-06-25 03:54:14,567 uvicorn.error 20946 INFO     Waiting for application startup.
2024-06-25 03:54:14,568 uvicorn.error 20946 INFO     Application startup complete.
2024-06-25 03:54:14,568 uvicorn.error 20946 INFO     Uvicorn running on http://127.0.0.1:2001 (Press CTRL+C to quit)
recreating all vector stores
/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
  warnings.warn(
2024-06-25 03:56:09,931 - before_sleep.py[line:65] - WARNING: Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 8.0 seconds as it raised APIConnectionError: Connection error..
2024-06-25 03:56:42,764 - before_sleep.py[line:65] - WARNING: Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 10.0 seconds as it raised APIConnectionError: Connection error..
2024-06-25 03:57:20,752 - utils.py[line:614] - ERROR: error in sub thread: Connection error.

二、初始化之前使用xinference启动llm和embedding，配置如下：chatchat-config model --show
{
    "DEFAULT_LLM_MODEL": "glm4-chat",
    "DEFAULT_EMBEDDING_MODEL": "bge-large-zh-v1.5",
    ],
    "MODEL_PLATFORMS": [
        {
            "platform_name": "xinference",
            "platform_type": "xinference",
            "api_base_url": "http://127.0.0.1:9997/v1",
            "api_key": "EMPT",
            "api_concurrencies": 5,
            "llm_models": [
                "glm4-chat"
            ],
            "embed_models": [
                "bge-large-zh-v1.5"
            ],
        }
    ],
}

**Comment by imClumsyPanda** [comment]
请问xinference框架是否已启动，以及对应embedding模型是否已启动？

**Comment by tf18536** [comment]
> 请问xinference框架是否已启动，以及对应embedding模型是否已启动？

xinference成功启动，对应的llm和embedding也都启动了，
如果没启动llm或者识别出对应的llm，初始化会有专门的报错，

但是不知道是否识别出embedding

**Comment by tf18536** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101076770/a6560e3a-ec0f-488f-8abb-49b92a220f0f)

**Comment by tf18536** [comment]
完整报错如下：
$ chatchat-kb -r
2024-06-27 10:30:13,846 uvicorn.error 22057 INFO     Started server process [22057]
2024-06-27 10:30:13,846 uvicorn.error 22057 INFO     Waiting for application startup.
2024-06-27 10:30:13,847 uvicorn.error 22057 INFO     Application startup complete.
2024-06-27 10:30:13,848 uvicorn.error 22057 INFO     Uvicorn running on http://127.0.0.1:2001 (Press CTRL+C to quit)
recreating all vector stores
/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
  warnings.warn(
2024-06-27 10:30:41,850 - before_sleep.py[line:65] - WARNING: Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised APIConnectionError: Connection error..
2024-06-27 10:31:12,395 - before_sleep.py[line:65] - WARNING: Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised APIConnectionError: Connection error..
2024-06-27 10:31:44,128 - before_sleep.py[line:65] - WARNING: Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised APIConnectionError: Connection error..
2024-06-27 10:32:17,346 - before_sleep.py[line:65] - WARNING: Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 8.0 seconds as it raised APIConnectionError: Connection error..
2024-06-27 10:32:50,913 - before_sleep.py[line:65] - WARNING: Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 10.0 seconds as it raised APIConnectionError: Connection error..
2024-06-27 10:33:27,307 - utils.py[line:614] - ERROR: error in sub thread: Connection error.
Traceback (most recent call last):
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 926, in _request
    response = self._client.send(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/utils.py", line 612, in run_in_thread_pool
    yield obj.result()
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/localai_embeddings.py", line 323, in task
    return (seq, self._embedding_func(text, engine=self.deployment))
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/localai_embeddings.py", line 287, in _embedding_func
    return embed_with_retry(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/localai_embeddings.py", line 108, in embed_with_retry
    return _embed_with_retry(**kwargs)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/tenacity/__init__.py", line 332, in wrapped_f
    return self(f, *args, **kw)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/tenacity/__init__.py", line 469, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/tenacity/__init__.py", line 370, in iter
    result = action(retry_state)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/tenacity/__init__.py", line 412, in exc_check
    raise retry_exc.reraise()
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/tenacity/__init__.py", line 472, in __call__
    result = fn(*args, **kwargs)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/localai_embeddings.py", line 105, in _embed_with_retry
    response = embeddings.client.create(**kwargs)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/resources/embeddings.py", line 113, in create
    return self._post(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 897, in request
    return self._request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 950, in _request
    return self._retry_request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 950, in _request
    return self._retry_request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 950, in _request
    return self._retry_request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 950, in _request
    return self._retry_request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 950, in _request
    return self._retry_request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 950, in _request
    return self._retry_request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/openai/_base_client.py", line 960, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
2024-06-27 10:33:27,796 - faiss_cache.py[line:131] - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 119, in load_vector_store
    vector_store = self.new_vector_store(kb_name=kb_name, embed_model=embed_model)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 61, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 550, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 931, in from_texts
    return cls.__from(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 888, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
IndexError: list index out of range
2024-06-27 10:33:27,796 - init_database.py[line:171] - ERROR: 向量库 samples 加载失败。
Traceback (most recent call last):
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 119, in load_vector_store
    vector_store = self.new_vector_store(kb_name=kb_name, embed_model=embed_model)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 61, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 550, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 931, in from_texts
    return cls.__from(
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 888, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/init_database.py", line 156, in main
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/migrate.py", line 130, in folder2db
    kb.create_kb()
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_service/base.py", line 80, in create_kb
    self.do_create_kb()
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "/home/tws/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_cache/faiss_cache.py", line 132, in load_vector_store
    raise RuntimeError(f"向量库 {kb_name} 加载失败。")
RuntimeError: 向量库 samples 加载失败。
2024-06-27 10:33:27,797 - init_database.py[line:172] - WARNING: Caught KeyboardInterrupt! Setting stop event...
2024-06-27 10:33:27,797 - init_database.py[line:176] - WARNING: Sending SIGKILL to <Process name='Model providers Server (22057)' pid=22057 parent=21969 started daemon>

**Comment by Chrosea** [comment]
一样的问题

**Comment by Friman04** [comment]
same

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
