### ISSUE TITLE
[BUG] 网络搜索报错

### ISSUE THREAD

**Issue by vincentyan2023** [chatchat-space/Langchain-Chatchat#4337]
搜索引擎:bing

配置了bing_key
选择互联网搜索选项，运行报错：

Traceback (most recent call last):
  File "/home/anaconda3/envs/Chat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/anaconda3/envs/Chat/lib/python3.11/site-packages/chatchat/webui.py", line 69, in <module>
    dialogue_page(api=api, is_lite=is_lite)
  File "/home/anaconda3/envs/Chat/lib/python3.11/site-packages/chatchat/webui_pages/dialogue/dialogue.py", line 422, in dialogue_page
    docs = d.tool_output.get("docs")
           ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

**Comment by Taol777** [comment]
系统命令工具问题相同

**Comment by liunux4odoo** [comment]
dev 分支做了修复，可以再测试一下。

**Comment by Blasy77777** [comment]
测试已经解决
