### ISSUE TITLE
使用milvus向量库报错, NotImplementedError

### ISSUE THREAD

**Issue by liaolinchun-AI** [chatchat-space/Langchain-Chatchat#4338]
**使用milvus向量库报错, self._similarity_search_with_relevance_scores中的self._select_relevance_score_fn()报错：NotImplementedError**
版本：
langchain：0.1.17
langchain-community： 0.0.36
langchain-core：0.1.52
langchain-chatchat：0.3.0.20240625.1
pymilvus：2.4.4

```python
2024-06-27 09:46:58,338 httpx        12940 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/chatchat/server/api_server/chat_routes.py", line 108, in chat_completions
    tool_result = await tool.ainvoke(tool_input)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/tools.py", line 723, in ainvoke
    return await run_in_executor(config, self.invoke, input, config, **kwargs)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 514, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/tools.py", line 260, in invoke
    return self.run(
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/tools.py", line 452, in run
    raise e
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/tools.py", line 409, in run
    context.run(
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/tools.py", line 750, in _run
    else self.func(*args, **kwargs)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/chatchat/server/agent/tools_factory/search_local_knowledgebase.py", line 60, in search_local_knowledgebase
    ret = search_knowledgebase(query=query, database=database, config=tool_config)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/chatchat/server/agent/tools_factory/search_local_knowledgebase.py", line 41, in search_knowledgebase
    docs = search_docs(
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_doc_api.py", line 64, in search_docs
    docs = kb.search_docs(query, top_k, score_threshold)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_service/base.py", line 219, in search_docs
    docs = self.do_search(query, top_k, score_threshold)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/chatchat/server/knowledge_base/kb_service/milvus_kb_service.py", line 86, in do_search
    docs = retriever.get_relevant_documents(query)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/chatchat/server/file_rag/retrievers/vectorstore.py", line 30, in get_relevant_documents
    return self.retriever.get_relevant_documents(query)[: self.top_k]
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 148, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/retrievers.py", line 323, in get_relevant_documents
    raise e
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/retrievers.py", line 316, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 699, in _get_relevant_documents
    self.vectorstore.similarity_search_with_relevance_scores(
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 323, in similarity_search_with_relevance_scores
    docs_and_similarities = self._similarity_search_with_relevance_scores(
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 270, in _similarity_search_with_relevance_scores
    relevance_score_fn = self._select_relevance_score_fn()
  File "/home/liaolinchun/anaconda3/envs/lang_chatglm_env4/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 227, in _select_relevance_score_fn
    raise NotImplementedError
NotImplementedError
```

**Comment by theafromhua** [comment]
same error

**Comment by JiadiLee** [comment]
相同的问题，不知是否有解决方案？

**Comment by jiusi9** [comment]
> 相同的问题，不知是否有解决方案？ 在langchain 的issue 里面可以查找到相关的BUG：[langchain-ai/langchain#19106](https://github.com/langchain-ai/langchain/issues/19106) 这个问题是在0.1.17版本发布之后fix 的，我不太确定langchain 是否可以升级，可以先手动解决下试试

我新部署的版本是0.0.17， 也同样有这个问题

**Comment by jiusi9** [comment]
langchain 已经发布0.1.17以后的版本了，langchain-chatchat指定了0.1.17版本，这等langchain-chatchat修复吗
![Uploading image.png…]()
