### ISSUE TITLE
[BUG] poetry源码启动，报无法导入DOC的错误

### ISSUE THREAD

**Issue by morego123** [chatchat-space/Langchain-Chatchat#4340]
(xx3) root@5478f1695181:/DDD/LLm/lang4/libs/chatchat-server# poetry run chatchat -a
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/xx3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/DDD/LLm/lang4/libs/chatchat-server/chatchat/startup.py", line 25, in <module>
    from fastapi import FastAPI
  File "/opt/conda/envs/xx3/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/opt/conda/envs/xx3/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/opt/conda/envs/xx3/lib/python3.10/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/opt/conda/envs/xx3/lib/python3.10/site-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/opt/conda/envs/xx3/lib/python3.10/site-packages/fastapi/openapi/models.py", line 4, in <module>
    from fastapi._compat import (
  File "/opt/conda/envs/xx3/lib/python3.10/site-packages/fastapi/_compat.py", line 20, in <module>
    from fastapi.exceptions import RequestErrorModel
  File "/opt/conda/envs/xx3/lib/python3.10/site-packages/fastapi/exceptions.py", line 6, in <module>
    from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
ImportError: cannot import name 'Doc' from 'typing_extensions' (/opt/conda/envs/xx3/lib/python3.10/site-packages/typing_extensions.py)
(xx3) root@5478f1695181:/DDD/LLm/lang4/libs/chatchat-server#

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
