### ISSUE TITLE
[BUG] Chatchat-config kb --set_search_engine_top_k 设置报错

### ISSUE THREAD

**Issue by vincentyan2023** [chatchat-space/Langchain-Chatchat#4353]
执行如下命令报错：
   chatchat-config kb --set_search_engine_top_k 10

Traceback (most recent call last):
  File "/home/anaconda3/envs/chat/bin/chatchat-config", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/anaconda3/envs/chat/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/chat/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/chat/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/chat/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/chat/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/chat/lib/python3.11/site-packages/chatchat/config_work_space.py", line 213, in kb
    config_model_workspace.set_search_engine_top_k(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigModelWorkSpace' object has no attribute 'set_search_engine_top_k'

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
