### ISSUE TITLE
0.3版网络搜索报错

### ISSUE THREAD

**Issue by yang9366** [chatchat-space/Langchain-Chatchat#4359]
已经配置好bing_key
```{'status': 3, 'text': 'Thought: 我需要搜索相关信息。\nAction: search_internet\nAction Input: {"query": {"title": "大模型最新消息", "description": "关于大模型的最新进展和研究动态", "type": "string"}}'}
{'status': 4, 'tool_name': 'search_internet', 'tool_input': {'query': {'title': '大模型最新消息', 'description': '关于大模型的最新进展和研究动态', 'type': 'string'}}, 'text': 'Thought: 我需要搜索相关信息。\nAction: search_internet\nAction Input: {"query": {"title": "大模型最新消息", "description": "关于大模型的最新进展和研究动态", "type": "string"}}'}
<class 'pydantic.v1.main.search_internetSchema'>
{'run_id': 'bc9ddd1b-a7a0-451f-97fb-2def62f9630b', 'status': 6, 'tool': 'search_internet', 'tool_input': "{'query': {'title': '大模型最新消息', 'description': '关于大模型的最新进展和研究动态', 'type': 'string'}}"}
2024-06-28 16:23:39,575 root         674266 ERROR    1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)
Traceback (most recent call last):
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/chatchat/server/utils.py", line 46, in wrap_done
    await fn
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2536, in ainvoke
    input = await step.ainvoke(
            ^^^^^^^^^^^^^^^^^^^
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/base.py", line 212, in ainvoke
    raise e
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain/chains/base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1481, in _acall
    next_step_output = await self._atake_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1275, in _atake_next_step
    [
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1275, in <listcomp>
    [
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1359, in _aiter_next_step
    result = await asyncio.gather(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain/agents/agent.py", line 1392, in _aperform_agent_action
    observation = await tool.arun(
                  ^^^^^^^^^^^^^^^^
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/tools.py", line 520, in arun
    raise e
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_core/tools.py", line 497, in arun
    parsed_input = self._parse_input(tool_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/chatchat/server/agent/tools_factory/tools_registry.py", line 38, in _new_parse_input
    result = input_args.parse_obj(tool_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/etc/miniconda3/envs/chatchat/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)
2024-06-28 16:23:39,577 root         674266 ERROR    ValidationError: Caught exception: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)```

```
def _new_parse_input(
    self,
    tool_input: Union[str, Dict],
) -> Union[str, Dict[str, Any]]:
    """Convert tool input to pydantic model."""
    input_args = self.args_schema
    print('bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb')
    print(input_args) #<class 'pydantic.v1.main.search_internetSchema'> 但是这个类根本没找到从哪来的
    print(tool_input) #{'query': {'title': '大模型最新消息', 'description': '大模型最近的新闻和发展', 'type': 'string'}}
    if isinstance(tool_input, str):
        if input_args is not None:
            key_ = next(iter(input_args.__fields__.keys()))
            input_args.validate({key_: tool_input})
        return tool_input
    else:
        if input_args is not None:
            result = input_args.parse_obj(tool_input)  #报错的地方
            return result.dict()
```

**Comment by yang9366** [comment]
大佬们请指教

**Comment by Modas-Li** [comment]
same issue:


Traceback (most recent call last):
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/utils.py", line 46, in wrap_done
    await fn
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2536, in ainvoke
    input = await step.ainvoke(
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 212, in ainvoke
    raise e
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1481, in _acall
    next_step_output = await self._atake_next_step(
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in _atake_next_step
    [
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in <listcomp>
    [
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1359, in _aiter_next_step
    result = await asyncio.gather(
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1392, in _aperform_agent_action
    observation = await tool.arun(
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 520, in arun
    raise e
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 497, in arun
    parsed_input = self._parse_input(tool_input)
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/agent/tools_factory/tools_registry.py", line 36, in _new_parse_input
    result = input_args.parse_obj(tool_input)
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)
2024-06-28 23:43:43,914 root         81303 ERROR    ValidationError: Caught exception: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)

**Comment by yang9366** [comment]
> same issue:
> 
> Traceback (most recent call last): File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/utils.py", line 46, in wrap_done await fn File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2536, in ainvoke input = await step.ainvoke( File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 212, in ainvoke raise e File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 203, in ainvoke await self._acall(inputs, run_manager=run_manager) File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1481, in _acall next_step_output = await self._atake_next_step( File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in _atake_next_step [ File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in [ File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1359, in _aiter_next_step result = await asyncio.gather( File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1392, in _aperform_agent_action observation = await tool.arun( File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 520, in arun raise e File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 497, in arun parsed_input = self._parse_input(tool_input) File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/agent/tools_factory/tools_registry.py", line 36, in _new_parse_input result = input_args.parse_obj(tool_input) File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 526, in parse_obj return cls(**obj) File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in **init** raise validation_error pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema query str type expected (type=type_error.str) 2024-06-28 23:43:43,914 root 81303 ERROR ValidationError: Caught exception: 1 validation error for search_internetSchema query str type expected (type=type_error.str)

    if isinstance(tool_input, str):
        if input_args is not None:
            key_ = next(iter(input_args.__fields__.keys()))
            input_args.validate({key_: tool_input})
        return tool_input
    else:
        if input_args is not None:
            # result = input_args.parse_obj(tool_input)  # I commented out these two lines and then the code started working
            # return result.dict()
            return tool_input['query']['title'] #replace with this code

**Comment by yhfgyyf** [comment]
使用的llm是哪个？看日志应该是传参错误，这里的tool封装，容易把description当做参数传递，就会抱错。

**Comment by yang9366** [comment]
> 使用的llm是哪个？看日志应该是传参错误，这里的tool封装，容易把description当做参数传递，就会抱错。

用的qwen-chat  我明天换qwen2试试

**Comment by panda4444ssdfs** [comment]
> > 使用的llm是哪个？看日志应该是传参错误，这里的tool封装，容易把description当做参数传递，就会抱错。
> 
> 用的qwen-chat 我明天换qwen2试试

请问你这个报错解决了没，我现在遇到的也是这个报错，一直解决不掉

**Comment by Modas-Li** [comment]
> > same issue:
> > Traceback (most recent call last): File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/utils.py", line 46, in wrap_done await fn File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2536, in ainvoke input = await step.ainvoke( File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 212, in ainvoke raise e File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 203, in ainvoke await self._acall(inputs, run_manager=run_manager) File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1481, in _acall next_step_output = await self._atake_next_step( File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in _atake_next_step [ File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in [ File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1359, in _aiter_next_step result = await asyncio.gather( File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1392, in _aperform_agent_action observation = await tool.arun( File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 520, in arun raise e File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 497, in arun parsed_input = self._parse_input(tool_input) File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/agent/tools_factory/tools_registry.py", line 36, in _new_parse_input result = input_args.parse_obj(tool_input) File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 526, in parse_obj return cls(**obj) File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in **init** raise validation_error pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema query str type expected (type=type_error.str) 2024-06-28 23:43:43,914 root 81303 ERROR ValidationError: Caught exception: 1 validation error for search_internetSchema query str type expected (type=type_error.str)
> 
> server--agent--tools_factory--tools_registry.py _new_parse_input
> 
> ```
> if isinstance(tool_input, str):
>     if input_args is not None:
>         key_ = next(iter(input_args.__fields__.keys()))
>         input_args.validate({key_: tool_input})
>     return tool_input
> else:
>     if input_args is not None:
>         # result = input_args.parse_obj(tool_input)  # I commented out these two lines and then the code started working
>         # return result.dict()
>         return tool_input['query']['title'] #replace with this code
> ```

big brother, could you explain why, thx

**Comment by panda4444ssdfs** [comment]
我解决掉了，可以正常进行网络搜索了

**Comment by jdx2099** [comment]
> 我解决掉了，可以正常进行网络搜索了

方便讲讲怎么配置网络搜索吗

**Comment by panda4444ssdfs** [comment]
> > 我解决掉了，可以正常进行网络搜索了
> 
> 方便讲讲怎么配置网络搜索吗

我给你一个地址，我发布到csdn上去了，你自己试试。https://blog.csdn.net/weixin_57635535/article/details/140325854?spm=1001.2014.3001.5502

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，可以更新尝试。

**Comment by Modas-Li** [comment]
glm4-chat还是报同样的错
