### ISSUE TITLE
不启用agent，单独使用网络搜索时报错

### ISSUE THREAD

**Issue by lingyezhixing** [chatchat-space/Langchain-Chatchat#4369]
win11，python版本：3.10.10

Traceback (most recent call last):
  File "D:\LLM\Langchain-Chatchat\runtime\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\LLM\Langchain-Chatchat\runtime\Lib\site-packages\chatchat\webui.py", line 69, in <module>
    dialogue_page(api=api, is_lite=is_lite)
  File "D:\LLM\Langchain-Chatchat\runtime\lib\site-packages\chatchat\webui_pages\dialogue\dialogue.py", line 422, in dialogue_page
    docs = d.tool_output.get("docs")
AttributeError: 'str' object has no attribute 'get'

**Comment by liunux4odoo** [comment]
如果是源码部署的，可以更新下 dev 分支，里面已经修复：https://github.com/chatchat-space/Langchain-Chatchat/pull/4344
