### ISSUE TITLE
[BUG] TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by zhngs** [chatchat-space/Langchain-Chatchat#440]
**问题描述**
TypeError: issubclass() arg 1 must be a class

**复现问题的步骤**
1. 执行 python loader/image_loader.py 
2. 出现错误
<img width="873" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/71338383/c899030a-d291-429d-8867-c52f18702064">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.1.13
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: centos8
- Python 版本 / Python version: 3.8.13
- 其他相关环境信息 / Other relevant environment information:

Traceback (most recent call last):
  File "loader/image_loader.py", line 4, in <module>
    from langchain.document_loaders.unstructured import UnstructuredFileLoader
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/tools/__init__.py", line 42, in <module>
    from langchain.tools.vectorstore.tool import (
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/tools/vectorstore/tool.py", line 13, in <module>
    from langchain.chains import RetrievalQA, RetrievalQAWithSourcesChain
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/chains/api/base.py", line 13, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/memory/__init__.py", line 28, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/vectorstores/analyticdb.py", line 16, in <module>
    from langchain.embeddings.base import Embeddings
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/embeddings/__init__.py", line 19, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/langchain/embeddings/openai.py", line 67, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by DeemoZen** [comment]
这似乎是 langchain 的问题，从那边的issue中找到了解决方案，https://github.com/hwchase17/langchain/issues/5113 ，安装一下特定版本库就好：pip install typing-inspect==0.8.0 typing_extensions==4.5.0

**Comment by zhngs** [comment]
非常感谢

**Comment by juanprida** [comment]
Facing the same issue

**Comment by prerit714** [comment]
It broke moments ago

**Comment by cmuro27** [comment]
It worked well yesterday, now I'm facing this issue

**Comment by imClumsyPanda** [comment]
> It worked well yesterday, now I'm facing this issue

pip install typing-inspect==0.8.0 typing_extensions==4.5.0

This should work as mentioned in langchain issue

**Comment by cmuro27** [comment]
Thank you very much, bro,
Now it works well.
Best regards,
Cesar

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Holden-Lin** [comment]
I'm still having while the package versions are typing-inspect==0.8.0 typing_extensions==4.5.0...
