### ISSUE TITLE
2.10版本异步问题

### ISSUE THREAD

**Issue by Nancy7zt** [chatchat-space/Langchain-Chatchat#4420]
调用agent_chat的时候报异步处理的错误，请问如何解决
INFO:     58.208.85.140:59574 - "POST /chat/agent_chat HTTP/1.0" 200 OK
2024-07-05 08:58:55,195 - runners.py[line:118] - ERROR: Task exception was never retrieved
future: <Task finished name='Task-63257' coro=<AsyncClient.aclose() done, defined at /data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/httpx/_client.py:1996> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x7f1ba45b0e90>; the handler is closed')>
Traceback (most recent call last):
  File "/data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/httpx/_client.py", line 2003, in aclose
    await self._transport.aclose()
  File "/data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/httpx/_transports/default.py", line 383, in aclose
    await self._pool.aclose()
  File "/data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 313, in aclose
    await self._close_connections(closing_connections)
  File "/data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 305, in _close_connections
    await connection.aclose()
  File "/data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/httpcore/_async/connection.py", line 171, in aclose
    await self._connection.aclose()
  File "/data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/httpcore/_async/http11.py", line 265, in aclose
    await self._network_stream.aclose()
  File "/data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 55, in aclose
    await self._stream.aclose()
  File "/data/anaconda3/envs/langchainv3.0/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1198, in aclose
    self._transport.write_eof()
  File "uvloop/handles/stream.pyx", line 699, in uvloop.loop.UVStream.write_eof
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x7f1ba45b0e90>; the handler is closed

**Comment by liunux4odoo** [comment]
0.2.x 版本已经停止维护。
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。0.2.x 版本已经停止维护。
