### ISSUE TITLE
【求助】cannot import name 'model_validator' from 'pydantic'

### ISSUE THREAD

**Issue by LillyChen** [chatchat-space/Langchain-Chatchat#4440]
cannot import name 'model_validator' from 'pydantic'

langchain-chatchat==0.2.final， pydantic==1.10.13

启动的时候报错
Process API Server:
Traceback (most recent call last):
  File "D:\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\program\llm\Langchain-Chatchat-0.2.final\startup.py", line 438, in run_api_server
    app = create_app(run_mode=run_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\program\llm\Langchain-Chatchat-0.2.final\server\api.py", line 51, in create_app
    mount_app_routes(app, run_mode=run_mode)
  File "E:\program\llm\Langchain-Chatchat-0.2.final\server\api.py", line 77, in mount_app_routes
    mount_knowledge_routes(app)
  File "E:\program\llm\Langchain-Chatchat-0.2.final\server\api.py", line 140, in mount_knowledge_routes
    from server.chat.knowledge_base_chat import knowledge_base_chat
  File "E:\program\llm\Langchain-Chatchat-0.2.final\server\chat\knowledge_base_chat.py", line 22, in <module>
    from server.reranker.reranker import LangchainReranker
  File "E:\program\llm\Langchain-Chatchat-0.2.final\server\reranker\reranker.py", line 11, in <module>
    from llama_index.bridge.pydantic import Field, PrivateAttr
  File "D:\Python\Python311\Lib\site-packages\llama_index\__init__.py", line 13, in <module>
    from llama_index.callbacks.global_handlers import set_global_handler
  File "D:\Python\Python311\Lib\site-packages\llama_index\callbacks\__init__.py", line 7, in <module>
    from .token_counting import TokenCountingHandler
  File "D:\Python\Python311\Lib\site-packages\llama_index\callbacks\token_counting.py", line 6, in <module>
    from llama_index.utilities.token_counting import TokenCounter
  File "D:\Python\Python311\Lib\site-packages\llama_index\utilities\token_counting.py", line 6, in <module>
    from llama_index.llms import ChatMessage, MessageRole
  File "D:\Python\Python311\Lib\site-packages\llama_index\llms\__init__.py", line 26, in <module>
    from llama_index.llms.litellm import LiteLLM
  File "D:\Python\Python311\Lib\site-packages\llama_index\llms\litellm.py", line 27, in <module>
    from llama_index.llms.litellm_utils import (
  File "D:\Python\Python311\Lib\site-packages\llama_index\llms\litellm_utils.py", line 25, in <module>
    from litellm.utils import Message
  File "D:\Python\Python311\Lib\site-packages\litellm\__init__.py", line 20, in <module>
    from litellm.proxy._types import (
  File "D:\Python\Python311\Lib\site-packages\litellm\proxy\_types.py", line 10, in <module>
    from pydantic import BaseModel, ConfigDict, Extra, Field, Json, model_validator
ImportError: cannot import name 'model_validator' from 'pydantic' (D:\Python\Python311\Lib\site-packages\pydantic\__init__.cp311-win_amd64.pyd)

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
