### ISSUE TITLE
[BUG] 知识库管理-上传txt格式文件报ModuleNotFoundError: No module named 'unstructured_inference.inference.ordering'

### ISSUE THREAD

**Issue by mk1990** [chatchat-space/Langchain-Chatchat#4449]
**问题描述 / Problem Description**
知识库管理功能添加txt格式知识库报错，chatchat后台报错ModuleNotFoundError: No module named 'unstructured_inference.inference.ordering'。

**复现问题的步骤 / Steps to Reproduce**
1.  在知识库管理页面，点击“上传知识文件”，然后选择txt格式文件；
2.  点击“添加文件到知识库”；
3. 知识库中已有文件列表中“文档加载器”和“分词器”选项显示为空，"文档数量"显示为0，“向量库”选项显示为X；
4. chatchat后台报错ModuleNotFoundError: No module named 'unstructured_inference.inference.ordering'。

**预期的结果 / Expected Result**
 1. 知识库已有文件列表正确显示文档加载器和分词器；
 2. chatchat后台不报错

**实际结果 / Actual Result**
1. 知识库中已有文件列表中“文档加载器”和“分词器”选项显示为空，"文档数量"显示为0，“向量库”选项显示为X；
2. chatchat后台报错ModuleNotFoundError: No module named 'unstructured_inference.inference.ordering'。

**环境信息 / Environment Information**
- langchain-ChatChat docker镜像版本：chatimage/chatchat:0.3.0-2024-0624
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu22.04

**附加信息 / Additional Information**
无

**Comment by mk1990** [comment]
报错详情：
2024-07-09 14:36:44,946 root         63 INFO     UnstructuredFileLoader used for /usr/local/lib/python3.11/site-packages/chatchat/data/knowledge_base/tt/content/三国.txt
2024-07-09 14:36:44,949 root         63 ERROR    ModuleNotFoundError: 从文件 tt/三国.txt 加载文档时出错：No module named 'unstructured_inference.inference.ordering'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/chatchat/server/knowledge_base/utils.py", line 424, in files2docs_in_thread_file2docs
    return True, (file.kb_name, file.filename, file.file2text(**kwargs))
                                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatchat/server/knowledge_base/utils.py", line 399, in file2text
    docs = self.file2docs()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatchat/server/knowledge_base/utils.py", line 354, in file2docs
    self.docs = loader.load()
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/document_loaders/base.py", line 29, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/document_loaders/unstructured.py", line 88, in lazy_load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/document_loaders/unstructured.py", line 168, in _get_elements
    from unstructured.partition.auto import partition
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/auto.py", line 81, in <module>
    from unstructured.partition.pdf import partition_pdf
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 81, in <module>
    from unstructured.partition.pdf_image.pdfminer_processing import (
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/pdf_image/pdfminer_processing.py", line 12, in <module>
    from unstructured_inference.inference.ordering import order_layout
ModuleNotFoundError: No module named 'unstructured_inference.inference.ordering'

**Comment by hcxss** [comment]
+1
No module named 'unstructured_inference.inference.ordering'

**Comment by lelofraser** [comment]
+1
没有名为“unstructured_inference.inference.ordering”的模块

**Comment by hcxss** [comment]
你们都是docker部署吗

**Comment by hcxss** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37952998/993c5b4b-12da-42a4-9a60-13e98999dabd)

**Comment by hcxss** [comment]
有没有可能是版本太新了！

**Comment by hcxss** [comment]
ordering这个文件没有，去历史版本找个ordering文件

**Comment by QJBX-DJN** [comment]
pip install unstructured==0.11.0

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
