### ISSUE TITLE
pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema

### ISSUE THREAD

**Issue by Modas-Li** [chatchat-space/Langchain-Chatchat#4455]
模型：glm-4-9b-chat
agent功能：知识库、网络检索
报错详情：
```2024-07-09 17:38:50,778 root         82445 ERROR    1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)
Traceback (most recent call last):
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/utils.py", line 46, in wrap_done
    await fn
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2536, in ainvoke
    input = await step.ainvoke(
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 212, in ainvoke
    raise e
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1481, in _acall
    next_step_output = await self._atake_next_step(
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in _atake_next_step
    [
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in <listcomp>
    [
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1359, in _aiter_next_step
    result = await asyncio.gather(
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1392, in _aperform_agent_action
    observation = await tool.arun(
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 520, in arun
    raise e
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 497, in arun
    parsed_input = self._parse_input(tool_input)
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/agent/tools_factory/tools_registry.py", line 36, in _new_parse_input
    result = input_args.parse_obj(tool_input)
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)
2024-07-09 17:38:50,780 root         82445 ERROR    ValidationError: Caught exception: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

**Comment by Modas-Li** [comment]
> 0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
glm4-chat还是报错：
pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema
