### ISSUE TITLE
[BUG] 互联网搜索功能报错

### ISSUE THREAD

**Issue by ganwumeng** [chatchat-space/Langchain-Chatchat#4457]
**问题描述 / Problem Description**
无法使用互联网搜索功能。

**复现问题的步骤 / Steps to Reproduce**
1. 填写完workspace_config.json中的bing_key
2. 使用互联网搜索工具
3. 输入prompt

**预期的结果 / Expected Result**
返回互联网搜索的结果

**实际结果 / Actual Result**
2024-07-11 09:59:11.651 Uncaught app exception
Traceback (most recent call last):
  File "/Users/ganwumeng/Ganwumeng/Connection/Project/ChatChatUI/.venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/Users/ganwumeng/Ganwumeng/Connection/Project/ChatChatUI/.venv/lib/python3.9/site-packages/chatchat/webui.py", line 69, in <module>
    dialogue_page(api=api, is_lite=is_lite)
  File "/Users/ganwumeng/Ganwumeng/Connection/Project/ChatChatUI/.venv/lib/python3.9/site-packages/chatchat/webui_pages/dialogue/dialogue.py", line 422, in dialogue_page
    # docs = d.tool_output.get("docs")
AttributeError: 'str' object has no attribute 'get'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.3.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Phi-3-mini-4k-instruct-q4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：jina-embeddings-v2-base-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: macOS
- Python 版本 / Python version:3.9
- 其他相关环境信息 / Other relevant environment information:/

**附加信息 / Additional Information**

**Comment by ganwumeng** [comment]
#4336 已解决该问题。

**Comment by jdx2099** [comment]
可以讲讲怎么配置bing key吗

**Comment by ganwumeng** [comment]
> 可以讲讲怎么配置bing key吗

@jdx2099 在azure后台搜BingSearch，可以用免费的那个计划
