### ISSUE TITLE
本地知识库对话报错：failed to create Embeddings for model: bge-large-zh-v1.5.

### ISSUE THREAD

**Issue by hzk866** [chatchat-space/Langchain-Chatchat#4512]
**问题描述 / Problem Description**
使用ollama quentinz/bge-large-zh-v1.5，本地知识库对话后报错failed to create Embeddings for model: bge-large-zh-v1.5。

**配置信息**
 ~/.chatchat 下面的 json 文件
```shell
[
    {
        "type": "ConfigBasic",
        "config": {
            "log_verbose": false,
            "CHATCHAT_ROOT": "E:\\Langchain-Chatchat2\\Langchain-Chatchat\\Chatchat\\env\\Lib\\site-packages\\chatchat",
            "DATA_PATH": "E:\\Langchain-Chatchat2\\Langchain-Chatchat\\Chatchat\\env\\Lib\\site-packages\\chatchat\\data",
            "IMG_DIR": "E:\\Langchain-Chatchat2\\Langchain-Chatchat\\Chatchat\\env\\Lib\\site-packages\\chatchat\\img",
            "NLTK_DATA_PATH": "E:\\Langchain-Chatchat2\\Langchain-Chatchat\\Chatchat\\env\\Lib\\site-packages\\chatchat\\data\\nltk_data",
            "LOG_FORMAT": "%(asctime)s - %(filename)s[line:%(lineno)d] - %(levelname)s: %(message)s",
            "LOG_PATH": "E:\\Langchain-Chatchat2\\Langchain-Chatchat\\Chatchat\\env\\Lib\\site-packages\\chatchat\\data\\logs",
            "MEDIA_PATH": "E:\\Langchain-Chatchat2\\Langchain-Chatchat\\Chatchat\\env\\Lib\\site-packages\\chatchat\\data\\media",
            "BASE_TEMP_DIR": "E:\\Langchain-Chatchat2\\Langchain-Chatchat\\Chatchat\\env\\Lib\\site-packages\\chatchat\\data\\temp",
            "class_name": "ConfigBasic"
        }
    },
    {
        "type": "ConfigModel",
        "config": {
            "DEFAULT_LLM_MODEL": "qwen2:7b",
            "DEFAULT_EMBEDDING_MODEL": "quentinz/bge-large-zh-v1.5",
            "Agent_MODEL": null,
            "HISTORY_LEN": 3,
            "MAX_TOKENS": null,
            "TEMPERATURE": 0.7,
            "SUPPORT_AGENT_MODELS": [
                "qwen2:7b"
            ],
            "LLM_MODEL_CONFIG": {
                "preprocess_model": {
                    "qwen2:7b": {
                        "temperature": 0.05,
                        "max_tokens": 4096,
                        "history_len": 100,
                        "prompt_name": "default",
                        "callbacks": false
                    }
                },
                "llm_model": {
                    "qwen2:7b": {
                        "temperature": 0.9,
                        "max_tokens": 4096,
                        "history_len": 10,
                        "prompt_name": "default",
                        "callbacks": true
                    }
                },
                "action_model": {
                    "qwen2:7b": {
                        "temperature": 0.01,
                        "max_tokens": 4096,
                        "prompt_name": "ChatGLM3",
                        "callbacks": true
                    }
                },
                "postprocess_model": {
                    "qwen2:7b": {
                        "temperature": 0.01,
                        "max_tokens": 4096,
                        "prompt_name": "default",
                        "callbacks": true
                    }
                },
                "image_model": {
                    "sd-turbo": {
                        "size": "256*256"
                    }
                }
            },
            "MODEL_PLATFORMS": [
                {
                    "platform_name": "ollama",
                    "platform_type": "ollama",
                    "api_base_url": "http://127.0.0.1:11434/v1",
                    "api_key": "EMPT",
                    "api_concurrencies": 5,
                    "llm_models": [
                        "qwen2:7b"
                    ],
                    "embed_models": [
                        "quentinz/bge-large-zh-v1.5"
                    ],
                    "image_models": [],
                    "reranking_models": [],
                    "speech2text_models": [],
                    "tts_models": []
                }
            ],
            "TOOL_CONFIG": {
                "search_local_knowledgebase": {
                    "use": false,
                    "top_k": 3,
                    "score_threshold": 1.0,
                    "conclude_prompt": {
                        "with_result": "<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 \"根据已知信息无法回答该问题\"，不允许在答案中添加编造成分，答案请使用中文。 </指令>\n<已知信息>{{ context }}</已知信息>\n<问题>{{ question }}</问题>\n",
                        "without_result": "请你根据我的提问回答我的问题:\n{{ question }}\n请注意，你必须在回答结束后强调，你的回答是根据你的经验回答而不是参考资料回答的。\n"
                    }
                },
                "search_internet": {
                    "use": false,
                    "search_engine_name": "bing",
                    "search_engine_config": {
                        "bing": {
                            "result_len": 3,
                            "bing_search_url": "https://api.bing.microsoft.com/v7.0/search",
                            "bing_key": ""
                        },
                        "metaphor": {
                            "result_len": 3,
                            "metaphor_api_key": "",
                            "split_result": false,
                            "chunk_size": 500,
                            "chunk_overlap": 0
                        },
                        "duckduckgo": {
                            "result_len": 3
                        }
                    },
                    "top_k": 10,
                    "verbose": "Origin",
                    "conclude_prompt": "<指令>这是搜索到的互联网信息，请你根据这些信息进行提取并有调理，简洁的回答问题。如果无法从中得到答案，请说 “无法搜索到能回答问题的内容”。 </指令>\n<已知信息>{{ context }}</已知信息>\n<问题>\n{{ question }}\n</问题>\n"
                },
                "arxiv": {
                    "use": true
                },
                "shell": {
                    "use": true
                },
                "weather_check": {
                    "use": true,
                    "api_key": "SUdWyvDuoxNN5Zp5W"
                },
                "search_youtube": {
                    "use": false
                },
                "wolfram": {
                    "use": false,
                    "appid": ""
                },
                "calculate": {
                    "use": true
                },
                "vqa_processor": {
                    "use": false,
                    "model_path": "your model path",
                    "tokenizer_path": "your tokenizer path",
                    "device": "cuda:1"
                },
                "aqa_processor": {
                    "use": false,
                    "model_path": "your model path",
                    "tokenizer_path": "yout tokenizer path",
                    "device": "cuda:2"
                },
                "text2images": {
                    "use": false,
                    "model": "sd-turbo",
                    "size": "256*256"
                },
                "text2sql": {
                    "use": false,
                    "sqlalchemy_connect_str": "mysql+pymysql://用户名:密码@主机地址/数据库名称e",
                    "read_only": false,
                    "top_k": 50,
                    "return_intermediate_steps": true,
                    "table_names": [],
                    "table_comments": {}
                }
            },
            "class_name": "ConfigModel"
        }
    }
]
``` 

**环境信息 / Environment Information**
-langchain-ChatGLM 版本/commit 号: v0.3.0
-是否使用 Docker 部署（是/否）：否
-使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen2:7b
-使用的 Embedding 模型（moka-ai/m3e-base 等）：Qwen-7B
-操作系统及版本 / Operating system and version:Windows 10 专业版

**完整报错信息**
```shell
2024-07-15 11:04:14,604 root         11960 ERROR    failed to create Embeddings for model: bge-large-zh-v1.5.
Traceback (most recent call last):
  File "E:\Langchain-Chatchat2\Langchain-Chatchat\Chatchat\env\Lib\site-packages\chatchat\server\utils.py", line 258, in get_Embeddings
    return LocalAIEmbeddings(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Langchain-Chatchat2\Langchain-Chatchat\Chatchat\env\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for LocalAIEmbeddings
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
2024-07-15 11:04:14,606 root         11960 ERROR    failed to access embed model 'bge-large-zh-v1.5': 'NoneType' object has no attribute 'embed_query'
Traceback (most recent call last):
  File "E:\Langchain-Chatchat2\Langchain-Chatchat\Chatchat\env\Lib\site-packages\chatchat\server\utils.py", line 268, in check_embed_model
    embeddings.embed_query("this is a test")
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'embed_query'
2024-07-15 11:04:14,607 root         11960 ERROR    could not search docs because failed to access embed model.
NoneType: None
```

**Comment by DanzelHe** [comment]
Langchain-Chatchat readme提到，能調用ollama的模型，不包括embedding model
現在ollama 0.2.x 已經支持同時調用embedding和LLM model
不知道，未來Langchain-Chatchat項目是否可以全面支持ollama的LLM以及embedding model？

**Comment by yhfgyyf** [comment]
ollama list看下是否启用了embedding模型

**Comment by hzk866** [comment]
> ollama list看下是否启用了embedding模型

![image](https://github.com/user-attachments/assets/8eace677-1d5c-4bea-8811-01b6731dda1e)

**Comment by yhfgyyf** [comment]
我测试下ollama embedding

**Comment by hzk866** [comment]
万分感谢！

**Comment by yhfgyyf** [comment]
测试下来可行，使用ollama list下显示的全称，我使用的是DEFAULT_EMBEDDING_MODEL: chatfire/bge-m3:q8_0，ollama的 platform下 embed_models增加 chatfire/bge-m3:q8_0，你这个应该需要带上:latest

**Comment by hzk866** [comment]
好的，我再试一下。

**Comment by yhfgyyf** [comment]
ollama的embedding速度远比xinference慢，你可以试下

**Comment by hzk866** [comment]
xinference测试都没有问题，但是同样的语言模型对话时比ollama慢很多，所以想试下ollama。

**Comment by hzk866** [comment]
我也修改了embedding为chatfire/bge-m3:q8_0，但是还是报没有找到bge-large-zh-v1.5的错，是配置信息没有生效吗？
```shell
            "DEFAULT_LLM_MODEL": "qwen2:7b",
            "DEFAULT_EMBEDDING_MODEL": "chatfire/bge-m3:q8_0",
            "Agent_MODEL": null,
            "HISTORY_LEN": 3,
            "MAX_TOKENS": null,
            "TEMPERATURE": 0.7,
            "SUPPORT_AGENT_MODELS": [
                "qwen2:7b"
            ],
            "LLM_MODEL_CONFIG": {
                "preprocess_model": {
                    "qwen2:7b": {
                        "temperature": 0.05,
                        "max_tokens": 4096,
                        "history_len": 100,
                        "prompt_name": "default",
                        "callbacks": false
                    }
                },
                "llm_model": {
                    "qwen2:7b": {
                        "temperature": 0.9,
                        "max_tokens": 4096,
                        "history_len": 10,
                        "prompt_name": "default",
                        "callbacks": true
                    }
                },
                "action_model": {
                    "qwen2:7b": {
                        "temperature": 0.01,
                        "max_tokens": 4096,
                        "prompt_name": "ChatGLM3",
                        "callbacks": true
                    }
                },
                "postprocess_model": {
                    "qwen2:7b": {
                        "temperature": 0.01,
                        "max_tokens": 4096,
                        "prompt_name": "default",
                        "callbacks": true
                    }
                },
                "image_model": {
                    "sd-turbo": {
                        "size": "256*256"
                    }
                }
            },
            "MODEL_PLATFORMS": [
                {
                    "platform_name": "ollama",
                    "platform_type": "ollama",
                    "api_base_url": "http://127.0.0.1:11434/v1",
                    "api_key": "sk",
                    "api_concurrencies": 5,
                    "llm_models": [
                        "qwen2:7b"
                    ],
                    "embed_models": [
                        "chatfire/bge-m3:q8_0"
                    ],
                    "image_models": [],
                    "reranking_models": [],
                    "speech2text_models": [],
                    "tts_models": []
                }
            ],
``` 
![image](https://github.com/user-attachments/assets/d8cfff1b-571c-43d0-86b4-866df7ab8a2c)

**报错信息**
```shell
2024-07-15 17:22:39,314 root         11472 ERROR    failed to create Embeddings for model: bge-large-zh-v1.5.
Traceback (most recent call last):
  File "E:\Langchain-Chatchat2\Langchain-Chatchat\Chatchat\env\Lib\site-packages\chatchat\server\utils.py", line 258, in get_Embeddings
    return LocalAIEmbeddings(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Langchain-Chatchat2\Langchain-Chatchat\Chatchat\env\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for LocalAIEmbeddings
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
2024-07-15 17:22:39,317 root         11472 ERROR    failed to access embed model 'bge-large-zh-v1.5': 'NoneType' object has no attribute 'embed_query'
Traceback (most recent call last):
  File "E:\Langchain-Chatchat2\Langchain-Chatchat\Chatchat\env\Lib\site-packages\chatchat\server\utils.py", line 268, in check_embed_model
    embeddings.embed_query("this is a test")
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'embed_query'
2024-07-15 17:22:39,318 root         11472 ERROR    could not search docs because failed to access embed model.
NoneType: None
```

**Comment by liunux4odoo** [comment]
模型配置错误。
如果是 0.3.0，要修改 ~/.chatchat 下的 json 文件，如果是 0.3.1，要修改 CHATCHAT_ROOT 下的 yaml 文件。
建议升级 0.3.1。
另外，你可以配置 xinference 使用 LLM，同时配置 ollama 使用 embedding，可以任意组合。

**Comment by hzk866** [comment]
更新0.3.1后，问题已解决~

**Comment by Panda-Panda-new** [comment]
> 更新0.3.1后，问题已解决~

我现在也遇到 #/
2025-02-09 14:36:18.282 | ERROR    | chatchat.server.utils:get_Embeddings:341 - failed to create Embeddings for model: bge-large-zh-v1.5.
2025-02-09 14:36:18.285 | ERROR    | chatchat.server.utils:check_embed_model:355 - failed to access embed model 'bge-large-zh-v1.5': 'NoneType' object has no attribute 'embed_query'
2025-02-09 14:36:18.285 | ERROR    | chatchat.server.chat.kb_chat:knowledge_base_chat_iterator:221 - error in knowledge chat: failed to access embed model 'bge-large-zh-v1.5': 'NoneType' object has no attribute 'embed_query'
这个报错请问您这边怎么解决呢

**Comment by Lihwnlp** [comment]
修改之后需要init一下
