### ISSUE TITLE
pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema

### ISSUE THREAD

**Issue by Modas-Li** [chatchat-space/Langchain-Chatchat#4519]
模型：glm4-chat
系统：linux
版本：V0.3.1
报错：
Thought: The user is asking for the current weather condition. I need to use the search_internet tool to find the weather information for today.
Action:
```json
{
  "action": "search_internet",
  "action_input": {
    "query": {
      "title": "Today's weather",
      "description": "current weather condition",
      "type": "string"
    }
  }
}
```2024-07-15 14:37:16.286 | ERROR    | chatchat.server.utils:wrap_done:45 - ValidationError: Caught exception: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 20
               └ <function _main at 0x7f5d242c76d0>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f5d243f9f30>
           └ <Process name='API Server' parent=5483 started>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f5d243f95a0>
    └ <Process name='API Server' parent=5483 started>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'started_event': <EventProxy object, typeid 'Event' at 0x7f5d242f6320>, 'run_mode': None}
    │    │        │    │        └ <Process name='API Server' parent=5483 started>
    │    │        │    └ ()
    │    │        └ <Process name='API Server' parent=5483 started>
    │    └ <function run_api_server at 0x7f5c5118ec20>
    └ <Process name='API Server' parent=5483 started>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/startup.py", line 70, in run_api_server
    uvicorn.run(app, host=host, port=port)
    │       │   │         │          └ 7860
    │       │   │         └ '0.0.0.0'
    │       │   └ <fastapi.applications.FastAPI object at 0x7f5c4cb91f00>
    │       └ <function run at 0x7f5c4e500550>
    └ <module 'uvicorn' from '/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/uvicorn/__init__.py'>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
    │      └ <function Server.run at 0x7f5c4e4c7d90>
    └ <uvicorn.server.Server object at 0x7f5c4c75cf40>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f5c4e4c7e20>
           │       │   └ <uvicorn.server.Server object at 0x7f5c4c75cf40>
           │       └ <function run at 0x7f5d238025f0>
           └ <module 'asyncio' from '/data/anaconda3/envs/chatchat/lib/python3.10/asyncio/__init__.py'>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f5c4c8c28f0>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f5d2380c040>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f5d23803f40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f5d2380dab0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f5d237c4e50>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
> File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/utils.py", line 42, in wrap_done
    await fn
          └ <coroutine object RunnableSequence.ainvoke at 0x7f5c43d3e570>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2536, in ainvoke
    input = await step.ainvoke(
                  │    └ <function Chain.ainvoke at 0x7f5c4e2bf130>
                  └ AgentExecutor(callbacks=[<chatchat.server.callback_handler.agent_callback_handler.AgentExecutorAsyncIteratorCallbackHandler o...
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 212, in ainvoke
    raise e
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
          │    │      │                   └ <langchain_core.callbacks.manager.AsyncCallbackManagerForChainRun object at 0x7f5c4db83310>
          │    │      └ {'input': '今天天气咋样'}
          │    └ <function AgentExecutor._acall at 0x7f5c4dedbb50>
          └ AgentExecutor(callbacks=[<chatchat.server.callback_handler.agent_callback_handler.AgentExecutorAsyncIteratorCallbackHandler o...
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1481, in _acall
    next_step_output = await self._atake_next_step(
                             │    └ <function AgentExecutor._atake_next_step at 0x7f5c4dedb910>
                             └ AgentExecutor(callbacks=[<chatchat.server.callback_handler.agent_callback_handler.AgentExecutorAsyncIteratorCallbackHandler o...
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in _atake_next_step
    [
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in <listcomp>
    [
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1359, in _aiter_next_step
    result = await asyncio.gather(
                   │       └ <function gather at 0x7f5d237f3370>
                   └ <module 'asyncio' from '/data/anaconda3/envs/chatchat/lib/python3.10/asyncio/__init__.py'>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain/agents/agent.py", line 1392, in _aperform_agent_action
    observation = await tool.arun(
                        │    └ <function BaseTool.arun at 0x7f5c4eb0ba30>
                        └ StructuredTool(name='search_internet', description='Use this tool to use bing search engine to search the internet and get in...
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 520, in arun
    raise e
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/langchain_core/tools.py", line 497, in arun
    parsed_input = self._parse_input(tool_input)
                   │    │            └ {'query': {'title': "Today's weather", 'description': 'current weather condition', 'type': 'string'}}
                   │    └ <function _new_parse_input at 0x7f5c4d87eb00>
                   └ StructuredTool(name='search_internet', description='Use this tool to use bing search engine to search the internet and get in...
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/chatchat/server/agent/tools_factory/tools_registry.py", line 40, in _new_parse_input
    result = input_args.parse_obj(tool_input)
             │          │         └ {'query': {'title': "Today's weather", 'description': 'current weather condition', 'type': 'string'}}
             │          └ <classmethod(<function BaseModel.parse_obj at 0x7f5c4fd916c0>)>
             └ <class 'pydantic.v1.main.search_internetSchema'>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
           │     └ {'query': {'title': "Today's weather", 'description': 'current weather condition', 'type': 'string'}}
           └ <class 'pydantic.v1.main.search_internetSchema'>
  File "/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
          └ ValidationError(model='search_internetSchema', errors=[{'loc': ('query',), 'msg': 'str type expected', 'type': 'type_error.st...

pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)

**Comment by liunux4odoo** [comment]
这明显是 LLM 返回的 action_input 有问题。开源模型的 Agent 能力不稳定，Agent 出错是挺常见的。 Qwen1.5、Qwen2的能力相对稳定一些，可以试试。

**Comment by Modas-Li** [comment]
> 这明显是 LLM 返回的 action_input 有问题。开源模型的 Agent 能力不稳定，Agent 出错是挺常见的。 Qwen1.5、Qwen2的能力相对稳定一些，可以试试。

那为什么Agent使用本地知识库可以稳定输出，使用搜索引擎就百分百异常呢

**Comment by liunux4odoo** [comment]
> ```json
> {
>   "action": "search_internet",
>   "action_input": {
>     "query": {
>       "title": "Today's weather",
>       "description": "current weather condition",
>       "type": "string"
>     }
>   }
> }
> ```

那是有点奇怪。我用qwen2 两者都是稳定的。
要说差别，知识库的tool使用了结构化参数，搜索引擎只有一个 query 参数，可能模型对这两种情况的输出不一样。这个得需要多对比测试一下。

**Comment by Modas-Li** [comment]
> > ```json
> > {
> >   "action": "search_internet",
> >   "action_input": {
> >     "query": {
> >       "title": "Today's weather",
> >       "description": "current weather condition",
> >       "type": "string"
> >     }
> >   }
> > }
> > ```
> 
> 那是有点奇怪。我用qwen2 两者都是稳定的。 要说差别，知识库的tool使用了结构化参数，搜索引擎只有一个 query 参数，可能模型对这两种情况的输出不一样。这个得需要多对比测试一下。

我用qwen报错这个，麻烦帮忙看一下，谢谢~
ValueError: Tag "<|endoftext|>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)

**Comment by liushaoqian** [comment]
> > 这明显是 LLM 返回的 action_input 有问题。开源模型的 Agent 能力不稳定，Agent 出错是挺常见的。 Qwen1.5、Qwen2的能力相对稳定一些，可以试试。
> 
> 那为什么Agent使用本地知识库可以稳定输出，使用搜索引擎就百分百异常呢

我调用agent就没有正确调用过，反正总是给我报错
