### ISSUE TITLE
创建新知识库，上传与其他知识库中同名文件，其他知识库的向量化数据会被删除

### ISSUE THREAD

**Issue by lrw-lee** [chatchat-space/Langchain-Chatchat#4544]
INFO:     127.0.0.1:33864 - "POST /knowledge_base/search_docs HTTP/1.1" 500 Internal Server Error
2024-07-16 17:25:59,309 httpx        345 INFO     HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatchat/server/knowledge_base/kb_doc_api.py", line 74, in search_docs
    data = kb.list_docs(file_name=file_name, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatchat/server/knowledge_base/kb_service/base.py", line 260, in list_docs
    doc_info = self.get_doc_by_ids([x["id"]])[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-07-16 17:25:59.309 | ERROR    | chatchat.webui_pages.utils:to_json:233 - JSONDecodeError: API未能返回正确的JSON。Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):

  File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f8b83d04900>
    └ <Thread(ScriptRunner.scriptThread, started 140233567893184)>
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f8b83d045e0>
    └ <Thread(ScriptRunner.scriptThread, started 140233567893184)>
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ScriptRunner.scriptThread, started 140233567893184)>
    │    │        │    └ ()
    │    │        └ <Thread(ScriptRunner.scriptThread, started 140233567893184)>
    │    └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='1e714182-b988-420f-9984-03b8a4221d80', _main_scrip...
    └ <Thread(ScriptRunner.scriptThread, started 140233567893184)>
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 307, in _run_script_thread
    self._run_script(request.rerun_data)
    │    │           │       └ <property object at 0x7f8abd538040>
    │    │           └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
    │    │               id: "$$WIDGET_ID-c630d...
    │    └ <function ScriptRunner._run_script at 0x7f8abd53ea20>
    └ ScriptRunner(_session_id='1e714182-b988-420f-9984-03b8a4221d80', _main_script_path='/usr/local/lib/python3.11/site-packages/c...
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
         │     │      └ <member '__dict__' of 'module' objects>
         │     └ <module '__main__' from '/usr/local/lib/python3.11/site-packages/chatchat/webui.py'>
         └ <code object <module> at 0x7f8ab800d5f0, file "/usr/local/lib/python3.11/site-packages/chatchat/webui.py", line 1>
  File "/usr/local/lib/python3.11/site-packages/chatchat/webui.py", line 69, in <module>
    knowledge_base_page(api=api, is_lite=is_lite)
    │                       │            └ False
    │                       └ <chatchat.webui_pages.utils.ApiRequest object at 0x7f8aab780b10>
    └ <function knowledge_base_page at 0x7f8ab09b2200>
  File "/usr/local/lib/python3.11/site-packages/chatchat/webui_pages/knowledge_base/knowledge_base.py", line 370, in knowledge_base_page
    docs = api.search_kb_docs(
           │   └ <function ApiRequest.search_kb_docs at 0x7f8abc1cd3a0>
           └ <chatchat.webui_pages.utils.ApiRequest object at 0x7f8aab780b10>
  File "/usr/local/lib/python3.11/site-packages/chatchat/webui_pages/utils.py", line 464, in search_kb_docs
    return self._get_response_value(response, as_json=True)
           │    │                   └ <Response [500 Internal Server Error]>
           │    └ <function ApiRequest._get_response_value at 0x7f8abc1ccd60>
           └ <chatchat.webui_pages.utils.ApiRequest object at 0x7f8aab780b10>
  File "/usr/local/lib/python3.11/site-packages/chatchat/webui_pages/utils.py", line 249, in _get_response_value
    return value_func(to_json(response))
           │          │       └ <Response [500 Internal Server Error]>
           │          └ <function ApiRequest._get_response_value.<locals>.to_json at 0x7f8ab07a8220>
           └ <function ApiRequest._get_response_value.<locals>.<lambda> at 0x7f8abc21efc0>
> File "/usr/local/lib/python3.11/site-packages/chatchat/webui_pages/utils.py", line 230, in to_json
    return r.json()
           │ └ <function Response.json at 0x7f8abe878ae0>
           └ <Response [500 Internal Server Error]>
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
           │       │     │    │          └ {}
           │       │     │    └ <property object at 0x7f8abe871760>
           │       │     └ <Response [500 Internal Server Error]>
           │       └ <function loads at 0x7f8b82fd71a0>
           └ <module 'json' from '/usr/local/lib/python3.11/json/__init__.py'>
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ 'Internal Server Error'
           │                └ <function JSONDecoder.decode at 0x7f8b82fd6ac0>
           └ <json.decoder.JSONDecoder object at 0x7f8b82fe8c50>
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ 'Internal Server Error'
               │    │          │      └ <built-in method match of re.Pattern object at 0x7f8b82fe46c0>
               │    │          └ 'Internal Server Error'
               │    └ <function JSONDecoder.raw_decode at 0x7f8b82fd6b60>
               └ <json.decoder.JSONDecoder object at 0x7f8b82fe8c50>
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ 'Internal Server Error'
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-07-16 17:26:00.454 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/usr/local/lib/python3.11/site-packages/chatchat/webui.py", line 69, in <module>
    knowledge_base_page(api=api, is_lite=is_lite)
  File "/usr/local/lib/python3.11/site-packages/chatchat/webui_pages/knowledge_base/knowledge_base.py", line 374, in knowledge_base_page
    data = [
           ^
  File "/usr/local/lib/python3.11/site-packages/chatchat/webui_pages/knowledge_base/knowledge_base.py", line 377, in <listcomp>
    "id": x["id"],
          ~^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by lrw-lee** [comment]
@liunux4odoo 
metadata["source"] 存储的是相对路径，使用pg作为向量库，pg的do_delete_doc()方法会将所有同名的数据都删除，之前的向量库就会没有数据
<img width="776" alt="image" src="https://github.com/user-attachments/assets/48d77c6b-b6a0-4485-a175-c7fa0a11c6a0">
<img width="928" alt="image" src="https://github.com/user-attachments/assets/d6c930e7-9020-423e-8497-8acb11c97fe1">

**Comment by liunux4odoo** [comment]
PG我不熟，这里似乎应该加上知识库名称的条件？欢迎PR
