### ISSUE TITLE
[BUG] 使用chatchat kb -r命令时出现错误：TypeError: expected str, got OperationalError

### ISSUE THREAD

**Issue by colorfulandcjy0806** [chatchat-space/Langchain-Chatchat#4568]
**问题描述 / Problem Description**
使用chatchat kb -r命令时出现错误：TypeError: expected str, got OperationalError

An error occurred while using the chatchat kb - r command: TypeError: expected str, got OperationalError

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'chatchat kb -r'

1. Execute 'chatchat kb-r'

**预期的结果 / Expected Result**
知识库加载完成

Knowledge base loading completed

**实际结果 / Actual Result**

```
Traceback (most recent call last):
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\chatchat\init_database.py", line 38, in worker
    create_tables()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\chatchat\server\knowledge_base\migrate.py", line 39, in create_tables
    Base.metadata.create_all(bind=engine)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\sql\schema.py", line 5871, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 3250, in _run_ddl_visitor
    with self.begin() as conn:
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 3240, in begin
    with self.connect() as conn:
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 3276, in connect
    return self._connection_cls(self)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 2440, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\sqlalchemy\engine\default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\chatchat\init_database.py", line 61, in worker
    logger.error(e, exc_info=True)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\loguru\_logger.py", line 2056, in error
    __self._log("ERROR", False, __self._options, __message, args, kwargs)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\loguru\_logger.py", line 2015, in _log
    colored_message = Colorizer.prepare_message(message, args, kwargs)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\loguru\_colorizer.py", line 362, in prepare_message
    tokens = Colorizer._parse_with_formatting(string, args, kwargs)
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\site-packages\loguru\_colorizer.py", line 391, in _parse_with_formatting
    for literal_text, field_name, format_spec, conversion in formatter.parse(string):
  File "C:\Users\windows\miniconda3\envs\llm-universe\lib\string.py", line 259, in parse
    return _string.formatter_parser(format_string)
TypeError: expected str, got OperationalError
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.3.1 / langchain-ChatGLM version/commit number: 0.3.1
- 是否使用 Docker 部署（是/否）：no / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM4 / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5 / Embedding model used (moka-ai/m3e-base, etc.): bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Windows11
- Python 版本 / Python version: 3.10

**Comment by colorfulandcjy0806** [comment]
抱歉，问题已经解决，原因在于Chatchat 存储配置文件和数据文件的根目录位置发生了变动，重新执行

```
set CHATCHAT_ROOT=/path/to/chatchat_data
chatchat init
```
就可以解决

Sorry, the issue has been resolved. The reason is that the root directory location where Chatchat stores configuration files and data files has changed. Please execute it again

```
set CHATCHAT_ROOT=/path/to/chatchat_data
chatchat init
```
It can be solved
