### ISSUE TITLE
[BUG] 0.3.1支持高并发吗？

### ISSUE THREAD

**Issue by LULU-LULULA** [chatchat-space/Langchain-Chatchat#4594]
**两人同时访问webui进行提问出现报错**
0.3.1源码部署成功后两人同时访问web进行提问，出现以下报错

**实际结果 / Actual Result**
ERROR: Exception in ASGI application
Traceback (most recent call last):
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/sse_starlette/sse.py", line 269, in call
await wrap(partial(self.listen_for_disconnect, receive))
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
await func()
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
message = await receive()
^^^^^^^^^^^^^^^
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 524, in receive
await self.message_event.wait()
File "/home/test/.conda/envs/langchain31/lib/python3.11/asyncio/locks.py", line 213, in wait
await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f0b9a71f450

During handling of the above exception, another exception occurred:

Exception Group Traceback (most recent call last):
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
| result = await app( # type: ignore[func-returns-value]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in call
| return await self.app(scope, receive, send)
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in call
| await super().call(scope, receive, send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/applications.py", line 123, in call
| await self.middleware_stack(scope, receive, send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in call
| raise exc
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in call
| await self.app(scope, receive, _send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in call
| await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
| raise exc
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
| await app(scope, receive, sender)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/routing.py", line 758, in call
| await self.middleware_stack(scope, receive, send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
| await route.handle(scope, receive, send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
| await self.app(scope, receive, send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
| await wrap_app_handling_exceptions(app, request)(scope, receive, send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
| raise exc
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
| await app(scope, receive, sender)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
| await response(scope, receive, send)
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/sse_starlette/sse.py", line 255, in call
| async with anyio.create_task_group() as task_group:
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in aexit
| raise BaseExceptionGroup(
| ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
+-+---------------- 1 ----------------
| Traceback (most recent call last):
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
| await func()
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/sse_starlette/sse.py", line 245, in stream_response
| async for data in self.body_iterator:
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/chatchat/server/api_server/openai_routes.py", line 87, in generator
| async for chunk in await method(**params):
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/openai/_streaming.py", line 147, in aiter
| async for item in self._iterator:
| File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/openai/_streaming.py", line 174, in stream
| raise APIError(
| openai.APIError: An error occurred during streaming
+------------------------------------
2024-07-23 16:12:16.403 Uncaught app exception
Traceback (most recent call last):
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
yield
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpx/_transports/default.py", line 113, in iter
for part in self._httpcore_stream:
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 367, in iter
raise exc from None
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 363, in iter
for part in self._stream:
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 349, in iter
raise exc
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 341, in iter
for chunk in self._connection._receive_response_body(**kwargs):
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 210, in _receive_response_body
event = self._receive_event(timeout=timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 220, in _receive_event
with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
File "/home/test/.conda/envs/langchain31/lib/python3.11/contextlib.py", line 155, in exit
self.gen.throw(typ, value, traceback)
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
exec(code, module.dict)
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/chatchat/webui.py", line 73, in <module>
dialogue_page(api=api, is_lite=is_lite)
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/chatchat/webui_pages/dialogue/dialogue.py", line 426, in dialogue_page
for d in client.chat.completions.create(
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/openai/_streaming.py", line 46, in iter
for item in self._iterator:
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/openai/_streaming.py", line 58, in stream
for sse in iterator:
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/openai/_streaming.py", line 50, in _iter_events
yield from self._decoder.iter_bytes(self.response.iter_bytes())
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/openai/_streaming.py", line 280, in iter_bytes
for chunk in self._iter_chunks(iterator):
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/openai/_streaming.py", line 291, in _iter_chunks
for chunk in iterator:
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpx/_models.py", line 829, in iter_bytes
for raw_bytes in self.iter_raw():
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpx/_models.py", line 883, in iter_raw
for raw_stream_bytes in self.stream:
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpx/_client.py", line 126, in iter
for chunk in self._stream:
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpx/_transports/default.py", line 112, in iter
with map_httpcore_exceptions():
File "/home/test/.conda/envs/langchain31/lib/python3.11/contextlib.py", line 155, in exit
self.gen.throw(typ, value, traceback)
File "/home/test/.conda/envs/langchain31/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3.1
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：glm4-chat
- 使用的 Embedding 模型：bge-large-zh-v1.5
- 使用的向量库类型 ：faiss 
- 操作系统及版本 / Operating system and version: Centos7 
- Python 版本 / Python version: python3.11
![image](https://github.com/user-attachments/assets/79f07e39-7b61-4294-be8c-300a00833236)

**Comment by liunux4odoo** [comment]
你模型加载用的什么框架？我这里用 xinference 加载 qwen2，分别测试了用 Thread Pool 10 并发访问 /chat/chat/completions 接口，开两个 WEBUI 同时提问，均无错误，除了响应速度变慢了。

**Comment by zqt996** [comment]
在改了

**Comment by LULU-LULULA** [comment]
> * 使用的模型：glm4-chat
> * 使用的 Embedding 模型：bge-large-zh-v1.5
硬件：rtx3090  24g显存，2t硬盘，我估计是我硬件不行。

**Comment by zqt996** [comment]
对话是可以多人的，我以为又是向量化哪

**Comment by LULU-LULULA** [comment]
> 对话是可以多人的，我以为又是向量化哪



> 对话是可以多人的，我以为又是向量化哪

我两人同时对话就有一人的不到答案直接报错，另外一人回答一半就卡住了。重新刷新后才能再问，我估计是我的服务器性能不行，3090，24G显存，6核cpu跑这个glm4有点为难

**Comment by njzfw1024** [comment]
> 在改了

蹲一个

**Comment by Silenceang** [comment]
> > 对话是可以多人的，我以为又是向量化哪
> 
> > 对话是可以多人的，我以为又是向量化哪
> 
> 我两人同时对话就有一人的不到答案直接报错，另外一人回答一半就卡住了。重新刷新后才能再问，我估计是我的服务器性能不行，3090，24G显存，6核cpu跑这个glm4有点为难

我也遇到了同样的问题

**Comment by liunux4odoo** [comment]
参考 #4809 ，可能是 streamlit webui 的问题。开发组无法复现。

**Comment by mailtobshen** [comment]
我用的是0.2.10版本，开20个线程同时提问，提问量超过20个以上，平均每个线程1.x个就开始报上述错误。

**Comment by mailtobshen** [comment]
我的类似问题已经得到解决，方法是startup.py模块里create_model_worker_app（）中，将模型worker并发上限参数args.limit_worker_concurrency = 10  #  原来是5 增大，并发线程数与worker的比例大概在4:1，基本上就不报错。随着worker数量的增加，GPU资源爆缸的概率也增大了，对于穷人来说又会报一系列显存不够等错误，需要识别和捕获，我的方法是：找到site-packages/langchain_community/chat_models/openai.py 里 async def _astream(）函数，将下述代码做修改：

**Comment by mailtobshen** [comment]
if not isinstance(chunk, dict):
        chunk = chunk.dict()              
 else:
       choice = chunk["choices"][0]
       
修改为：
if not isinstance(chunk, dict):
       chunk = chunk.dict()
       if chunk["choices"] is None or len(chunk["choices"]) == 0:
                print("========Tokens大小 超出显存极限!========")
                choice = {'delta': {'content': 'Tokens大小 超出显存极限!', 'function_call': None, 'role': 'assistant', 'tool_calls': None}, 'finish_reason': None, 'index': 0, 'logprobs': None}
            else:
                choice = chunk["choices"][0]

**Comment by mailtobshen** [comment]
更正下，经过反复测试，并发线程数与worker的比例大概在1:1.5左右会比较稳定，算力利用率高，设置参数数值越高，GPU显存消耗越大。

**Comment by wz96cj** [comment]
> 更正下，经过反复测试，并发线程数与worker的比例大概在1:1.5左右会比较稳定，算力利用率高，设置参数数值越高，GPU显存消耗越大。

3.0版本 已经移除这个limit_worker_concurrency参数了   openai_routes文件有个DEFAULT_API_CONCURRENCIES参数  不知道是不是类似的作用 参考你的例子改了之后 还是会出现Bad 'setIn' index异常

**Comment by xziyh** [comment]
> 更正下，经过反复测试，并发线程数与worker的比例大概在1:1.5左右会比较稳定，算力利用率高，设置参数数值越高，GPU显存消耗越大。

请教一下，worker数量可以在框架内设置吗
