### ISSUE TITLE
知识库中调用Agent,例如高德搜索，提供高德API后，选择启动高德地图POI搜索Agent,并搜索城市坐标，发生报错

### ISSUE THREAD

**Issue by fengchezhendexiatian** [chatchat-space/Langchain-Chatchat#4609]
![image](https://github.com/user-attachments/assets/88c2c9b0-ab76-45a1-aef0-ce4385c2eb99)

报错日志如下：
2024-07-25 17:19:34.710 | ERROR    | chatchat.server.utils:wrap_done:45 - ValidationError: Caught exception: 1 validation error for amap_poi_searchSchema
types
  field required (type=value_error.missing)
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 284
               │     └ 3
               └ <function _main at 0x00000156203BEAC0>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 284
           │    └ <function BaseProcess._bootstrap at 0x00000156200BD1C0>
           └ <Process name='API Server' parent=20704 started>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x00000156200BC720>
    └ <Process name='API Server' parent=20704 started>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'started_event': <EventProxy object, typeid 'Event' at 0x1564bdab790>, 'run_mode': None}
    │    │        │    │        └ <Process name='API Server' parent=20704 started>
    │    │        │    └ ()
    │    │        └ <Process name='API Server' parent=20704 started>
    │    └ <function run_api_server at 0x000001564BE82F20>
    └ <Process name='API Server' parent=20704 started>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\chatchat\startup.py", line 70, in run_api_server
    uvicorn.run(app, host=host, port=port)
    │       │   │         │          └ 7861
    │       │   │         └ '127.0.0.1'
    │       │   └ <fastapi.applications.FastAPI object at 0x00000156511B8F50>
    │       └ <function run at 0x000001564BF76700>
    └ <module 'uvicorn' from 'D:\\ProgramData\\miniconda3\\envs\\chat-chat-2.x\\Lib\\site-packages\\uvicorn\\__init__.py'>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
    │      └ <function Server.run at 0x000001564BF76AC0>
    └ <uvicorn.server.Server object at 0x000001564BF7A790>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000001564BF76B60>
           │       │   └ <uvicorn.server.Server object at 0x000001564BF7A790>
           │       └ <function run at 0x0000015621D428E0>
           └ <module 'asyncio' from 'D:\\ProgramData\\miniconda3\\envs\\chat-chat-2.x\\Lib\\asyncio\\__init__.py'>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x00000156515555D0>
           │      └ <function Runner.run at 0x0000015621E05580>
           └ <asyncio.runners.Runner object at 0x0000015650FC5750>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\uv...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000015621E031A0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000015650FC5750>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000015621EE6D40>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000015621E04F40>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000015621D43240>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
> File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\chatchat\server\utils.py", line 42, in wrap_done
    await fn
          └ <coroutine object RunnableSequence.ainvoke at 0x0000015650E60CA0>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain_core\runnables\base.py", line 2536, in ainvoke
    input = await step.ainvoke(
                  │    └ <function Chain.ainvoke at 0x000001564E911A80>
                  └ AgentExecutor(callbacks=[<chatchat.server.callback_handler.agent_callback_handler.AgentExecutorAsyncIteratorCallbackHandler o...
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain\chains\base.py", line 212, in ainvoke
    raise e
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain\chains\base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
          │    │      │                   └ <langchain_core.callbacks.manager.AsyncCallbackManagerForChainRun object at 0x00000156D9977D50>
          │    │      └ {'input': '提供南京坐标'}
          │    └ <function AgentExecutor._acall at 0x000001564F364180>
          └ AgentExecutor(callbacks=[<chatchat.server.callback_handler.agent_callback_handler.AgentExecutorAsyncIteratorCallbackHandler o...
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain\agents\agent.py", line 1481, in _acall
    next_step_output = await self._atake_next_step(
                             │    └ <function AgentExecutor._atake_next_step at 0x000001564F353EC0>
                             └ AgentExecutor(callbacks=[<chatchat.server.callback_handler.agent_callback_handler.AgentExecutorAsyncIteratorCallbackHandler o...
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain\agents\agent.py", line 1275, in _atake_next_step
    [
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain\agents\agent.py", line 1275, in <listcomp>
    [
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain\agents\agent.py", line 1359, in _aiter_next_step
    result = await asyncio.gather(
                   │       └ <function gather at 0x0000015621DDE480>
                   └ <module 'asyncio' from 'D:\\ProgramData\\miniconda3\\envs\\chat-chat-2.x\\Lib\\asyncio\\__init__.py'>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain\agents\agent.py", line 1392, in _aperform_agent_action
    observation = await tool.arun(
                        │    └ <function BaseTool.arun at 0x000001564E5F6700>
                        └ StructuredTool(name='amap_poi_search', description=' A wrapper that uses Amap to search.', args_schema=<class 'pydantic.v1.ma...
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain_core\tools.py", line 520, in arun
    raise e
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\langchain_core\tools.py", line 497, in arun
    parsed_input = self._parse_input(tool_input)
                   │    │            └ {'location': '南京'}
                   │    └ <function _new_parse_input at 0x0000015650DDD620>
                   └ StructuredTool(name='amap_poi_search', description=' A wrapper that uses Amap to search.', args_schema=<class 'pydantic.v1.ma...
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\chatchat\server\agent\tools_factory\tools_registry.py", line 40, in _new_parse_input
    result = input_args.parse_obj(tool_input)
             │          │         └ {'location': '南京'}
             │          └ <classmethod(<function BaseModel.parse_obj at 0x000001564C3022A0>)>
             └ <class 'pydantic.v1.main.amap_poi_searchSchema'>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\pydantic\v1\main.py", line 526, in parse_obj
    return cls(**obj)
           │     └ {'location': '南京'}
           └ <class 'pydantic.v1.main.amap_poi_searchSchema'>
  File "D:\ProgramData\miniconda3\envs\chat-chat-2.x\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
          └ ValidationError(model='amap_poi_searchSchema', errors=[{'loc': ('types',), 'msg': 'field required', 'type': 'value_error.miss...

pydantic.v1.error_wrappers.ValidationError: 1 validation error for amap_poi_searchSchema

**Comment by yhfgyyf** [comment]
这个tool的作用是搜索某个地面边上的兴趣点，不如可以搜索南京紫峰大厦边上有哪些旅游景点
