### ISSUE TITLE
[BUG] xinference启动gpt4-chat失败

### ISSUE THREAD

**Issue by wcw1996119** [chatchat-space/Langchain-Chatchat#4668]
参数有这些：
![image](https://github.com/user-attachments/assets/9611f37c-eeb0-4bbf-ada2-6b3768c49c24)

报错如下，总是分配到内存上，然后因为空间不够报错。我应该怎么调整参数？
2024-08-02 09:25:13,047 xinference.model.llm.llm_family 119852 INFO     Caching from Modelscope: LLM-Research/glm-4-9b-chat-GGUF
llama_model_loader: loaded meta data with 24 key-value pairs and 283 tensors from C:\Users\PC\.xinference\cache\glm4-chat-ggufv2-9b\glm-4-9b-chat.FP16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = chatglm
llama_model_loader: - kv   1:                               general.name str              = glm-4-9b-chat
llama_model_loader: - kv   2:                     chatglm.context_length u32              = 131072
llama_model_loader: - kv   3:                   chatglm.embedding_length u32              = 4096
llama_model_loader: - kv   4:                chatglm.feed_forward_length u32              = 13696
llama_model_loader: - kv   5:                        chatglm.block_count u32              = 40
llama_model_loader: - kv   6:               chatglm.attention.head_count u32              = 32
llama_model_loader: - kv   7:            chatglm.attention.head_count_kv u32              = 2
llama_model_loader: - kv   8:   chatglm.attention.layer_norm_rms_epsilon f32              = 0.000000
llama_model_loader: - kv   9:                          general.file_type u32              = 1
llama_model_loader: - kv  10:               chatglm.rope.dimension_count u32              = 64
llama_model_loader: - kv  11:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  13:                         tokenizer.ggml.pre str              = chatglm-bpe
llama_model_loader: - kv  14:                      tokenizer.ggml.tokens arr[str,151552]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,151552]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  16:                      tokenizer.ggml.merges arr[str,151073]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32              = 151329
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 151329
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 151329
llama_model_loader: - kv  20:                tokenizer.ggml.eot_token_id u32              = 151336
llama_model_loader: - kv  21:            tokenizer.ggml.unknown_token_id u32              = 151329
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = ChatGLM4
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type  f16:  162 tensors
llm_load_vocab: special tokens cache size = 223
llm_load_vocab: token to piece cache size = 0.9732 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = chatglm
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 151552
llm_load_print_meta: n_merges         = 151073
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 2
llm_load_print_meta: n_rot            = 64
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 16
llm_load_print_meta: n_embd_k_gqa     = 256
llm_load_print_meta: n_embd_v_gqa     = 256
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.6e-07
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 13696
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 131072
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 9B
llm_load_print_meta: model ftype      = F16
llm_load_print_meta: model params     = 9.40 B
llm_load_print_meta: model size       = 17.51 GiB (16.00 BPW)
llm_load_print_meta: general.name     = glm-4-9b-chat
llm_load_print_meta: BOS token        = 151329 '<|endoftext|>'
llm_load_print_meta: EOS token        = 151329 '<|endoftext|>'
llm_load_print_meta: UNK token        = 151329 '<|endoftext|>'
llm_load_print_meta: PAD token        = 151329 '<|endoftext|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 151336 '<|user|>'
llm_load_print_meta: max token length = 1024
llm_load_tensors: ggml ctx size =    0.14 MiB
Exception ignored on calling ctypes callback function: <function llama_log_callback at 0x00000277B0D41A80>
Traceback (most recent call last):
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\llama_cpp\_logger.py", line 30, in llama_log_callback
    print(text.decode("utf-8"), end="", flush=True, file=sys.stderr)
          ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 91: invalid continuation byte
llm_load_tensors:        CPU buffer size = 17929.97 MiB
.................................................................................
llama_new_context_with_model: n_ctx      = 131072
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =  5120.00 MiB
llama_new_context_with_model: KV self size  = 5120.00 MiB, K (f16): 2560.00 MiB, V (f16): 2560.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.58 MiB
llama_new_context_with_model:        CPU compute buffer size =  8481.01 MiB
llama_new_context_with_model: graph nodes  = 1606
llama_new_context_with_model: graph splits = 1
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 |
2024-08-02 09:25:24,420 xinference.core.worker 119852 ERROR    Failed to load model glm4-chat-1-0
Traceback (most recent call last):
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\core\worker.py", line 841, in launch_builtin_model
    await model_ref.load()
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\core\model.py", line 295, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\model\llm\ggml\llamacpp.py", line 172, in load
    self._llm = Llama(
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\llama_cpp\llama.py", line 452, in __init__
    self.scores: npt.NDArray[np.single] = np.ndarray(
    ^^^^^^^^^^^^^^^^^
numpy.core._exceptions.MemoryError: [address=127.0.0.1:59313, pid=134332] Unable to allocate 74.0 GiB for an array with shape (131072, 151552) and data type float32
2024-08-02 09:25:25,735 xinference.api.restful_api 124192 ERROR    [address=127.0.0.1:59313, pid=134332] Unable to allocate 74.0 GiB for an array with shape (131072, 151552) and data type float32
Traceback (most recent call last):
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\api\restful_api.py", line 847, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\core\supervisor.py", line 988, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\core\supervisor.py", line 952, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\core\supervisor.py", line 932, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\core\utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\core\worker.py", line 841, in launch_builtin_model
    await model_ref.load()
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\core\model.py", line 295, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\xinference\model\llm\ggml\llamacpp.py", line 172, in load
    self._llm = Llama(
    ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Anaconda\envs\xinference\Lib\site-packages\llama_cpp\llama.py", line 452, in __init__
    self.scores: npt.NDArray[np.single] = np.ndarray(
    ^^^^^^^^^^^^^^^^^
numpy.core._exceptions.MemoryError: [address=127.0.0.1:59313, pid=134332] Unable to allocate 74.0 GiB for an array with shape (131072, 151552) and data type float32

**Comment by yhfgyyf** [comment]
建议还是把模型全部放在gpu上跑。
这里应该是因为kv cache和计算缓存都放在cpu和内存上跑导致内存不够。
 看下gpu显存多大，n_gpu_layer 设置-1或者大于41，kv cache 128k是5g，32k是1.25g，fp16模型权重是18g，q8_0是9.4g，q4_0大概是5-6g，compute buffer size放cuda上跑不会占用多少显存的。
 当前剩余的显存大于kv cache +模型权重+1g，就差不多了，如果有embedding模型，要把这部分显存也去掉。

**Comment by wcw1996119** [comment]
> 建议还是把模型全部放在gpu上跑。 这里应该是因为kv cache和计算缓存都放在cpu和内存上跑导致内存不够。 看下gpu显存多大，n_gpu_layer 设置-1或者大于41，kv cache 128k是5g，32k是1.25g，fp16模型权重是18g，q8_0是9.4g，q4_0大概是5-6g，compute buffer size放cuda上跑不会占用多少显存的。 当前剩余的显存大于kv cache +模型权重+1g，就差不多了，如果有embedding模型，要把这部分显存也去掉。

可是好像n_gpu_layer 设置-1，选了Q4_K也不会调用到GPU，还是报一样的错numpy.core._exceptions.MemoryError: [address=127.0.0.1:57677, pid=137148] Unable to allocate 74.0 GiB for an array with shape (131072, 151552) and data type float32。我的GPU是一块4090，该怎么才能用到它呢

**Comment by yhfgyyf** [comment]
pip show llama-cpp-python 看下

**Comment by wcw1996119** [comment]
> pip show llama-cpp-python 看下

谢谢大佬！
Name: llama_cpp_python
Version: 0.2.84
Summary: Python bindings for the llama.cpp library
Home-page:
Author:
Author-email: Andrei Betlen <abetlen@gmail.com>
License: MIT
Location: D:\Program Files\Anaconda\envs\xinference\Lib\site-packages
Requires: diskcache, jinja2, numpy, typing-extensions
Required-by:

**Comment by yhfgyyf** [comment]
xinference官方应该没有更新llama-cpp-python的最新版本，最大可能是没有安装cuda编译的llama-cpp-python
`CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1  --force-reinstall  --no-cache-dir llama-cpp-python`

**Comment by wcw1996119** [comment]
> xinference官方应该没有更新llama-cpp-python的最新版本，最大可能是没有安装cuda编译的llama-cpp-python `CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 --force-reinstall --no-cache-dir llama-cpp-python`

重装了之后依然无法调用GPU（但我测试torch.cuda.is_available()是可以通过的），用llama.cpp或者transformers装都不行

**Comment by wcw1996119** [comment]
> xinference官方应该没有更新llama-cpp-python的最新版本，最大可能是没有安装cuda编译的llama-cpp-python `CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 --force-reinstall --no-cache-dir llama-cpp-python`

重新配置了pytorch之后可以调用了，感谢！

**Comment by geneives233** [comment]
> > xinference官方应该没有更新llama-cpp-python的最新版本，最大可能是没有安装cuda编译的llama-cpp-python `CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 --force-reinstall --no-cache-dir llama-cpp-python`
> 
> 重新配置了pytorch之后可以调用了，感谢！

怎样重新配置 pytorch 呢
