### ISSUE TITLE
glm-4v-9b 调用agent  url阅读工具报错

### ISSUE THREAD

**Issue by sy960923** [chatchat-space/Langchain-Chatchat#4696]
INFO:     127.0.0.1:63427 - "GET /tools HTTP/1.1" 200 OK
2024-08-08 10:29:15,320 httpx        15108 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:63428 - "GET /tools HTTP/1.1" 200 OK
2024-08-08 10:29:15,328 httpx        15108 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:63539 - "GET /tools HTTP/1.1" 200 OK
2024-08-08 10:30:10,010 httpx        15108 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:63556 - "GET /tools HTTP/1.1" 200 OK
2024-08-08 10:30:22,482 httpx        15108 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:63557 - "GET /tools HTTP/1.1" 200 OK
2024-08-08 10:30:22,587 httpx        15108 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:63578 - "GET /tools HTTP/1.1" 200 OK
2024-08-08 10:30:28,145 httpx        15108 INFO     HTTP Request: GET http://127.0.0.1:7861/tools "HTTP/1.1 200 OK"
INFO:     127.0.0.1:63579 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-08-08 10:30:28,657 httpx        15108 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
2024-08-08 10:30:28,658 openai._base_client 15108 INFO     Retrying request to /chat/completions in 0.778431 seconds
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "d:\python11\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "d:\python11\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "d:\python11\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\chatchat\server\api_server\chat_routes.py", line 122, in chat_completions
    tool_result = await tool.ainvoke(tool_input)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 723, in ainvoke
    return await run_in_executor(config, self.invoke, input, config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\runnables\config.py", line 514, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 260, in invoke
    return self.run(
           ^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 452, in run
    raise e
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 409, in run
    context.run(
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 750, in _run
    else self.func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\chatchat\server\agent\tools_factory\url_reader.py", line 36, in url_reader
    response = requests.get(reader_url, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\adapters.py", line 483, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\urllib3\util\timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\urllib3\util\timeout.py", line 165, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was 10000, but it must be an int, float or None.
INFO:     127.0.0.1:63581 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-08-08 10:30:29,659 httpx        15108 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
2024-08-08 10:30:29,660 openai._base_client 15108 INFO     Retrying request to /chat/completions in 1.729763 seconds
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "d:\python11\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "d:\python11\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "d:\python11\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\chatchat\server\api_server\chat_routes.py", line 122, in chat_completions
    tool_result = await tool.ainvoke(tool_input)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 723, in ainvoke
    return await run_in_executor(config, self.invoke, input, config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\runnables\config.py", line 514, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 260, in invoke
    return self.run(
           ^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 452, in run
    raise e
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 409, in run
    context.run(
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 750, in _run
    else self.func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\chatchat\server\agent\tools_factory\url_reader.py", line 36, in url_reader
    response = requests.get(reader_url, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\adapters.py", line 483, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\urllib3\util\timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\urllib3\util\timeout.py", line 165, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was 10000, but it must be an int, float or None.
INFO:     127.0.0.1:63584 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-08-08 10:30:31,623 httpx        15108 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "d:\python11\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "d:\python11\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "d:\python11\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "d:\python11\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "d:\python11\Lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\chatchat\server\api_server\chat_routes.py", line 122, in chat_completions
    tool_result = await tool.ainvoke(tool_input)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 723, in ainvoke
    return await run_in_executor(config, self.invoke, input, config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\runnables\config.py", line 514, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 260, in invoke
    return self.run(
           ^^^^^^^^^
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 452, in run
    raise e
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 409, in run
    context.run(
  File "d:\python11\Lib\site-packages\langchain_core\tools.py", line 750, in _run
    else self.func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\chatchat\server\agent\tools_factory\url_reader.py", line 36, in url_reader
    response = requests.get(reader_url, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\requests\adapters.py", line 483, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\urllib3\util\timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python11\Lib\site-packages\urllib3\util\timeout.py", line 165, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was 10000, but it must be an int, float or None.

**Comment by IUYSY** [comment]
同问

**Comment by sy960923** [comment]
glm-4v不支持自定义agent
