### ISSUE TITLE
v2.10版本调用在线embedding api  好像不支持多并发

### ISSUE THREAD

**Issue by Nancy7zt** [chatchat-space/Langchain-Chatchat#4699]
2024-08-08 00:28:32,146 - faiss_cache.py[line:92] - INFO: loading vector store in '20240806/vector_store/text-embedding-ada-002' from disk.
2024-08-08 00:28:32,147 - base.py[line:36] - INFO: thread 40446 开始操作：('text-embedding-ada-002', 'cpu')。初始化
2024-08-08 00:28:32,339 - base.py[line:40] - INFO: thread 40446 结束操作：('text-embedding-ada-002', 'cpu')。初始化
2024-08-08 00:28:32,341 - loader.py[line:64] - INFO: Loading faiss.
2024-08-08 00:28:32,358 - loader.py[line:66] - INFO: Successfully loaded faiss.
2024-08-08 00:28:32,364 - base.py[line:40] - INFO: thread 40446 结束操作：('20240806', 'text-embedding-ada-002')。初始化
2024-08-08 00:28:32,364 - base.py[line:36] - INFO: thread 40446 开始操作：('20240806', 'text-embedding-ada-002')。
2024-08-08 00:28:32,364 - base.py[line:40] - INFO: thread 40446 结束操作：('20240806', 'text-embedding-ada-002')。
2024-08-08 00:28:32,369 - base.py[line:36] - INFO: thread 40446 开始操作：('20240806', 'text-embedding-ada-002')。
2024-08-08 00:28:32,370 - base.py[line:40] - INFO: thread 40446 结束操作：('20240806', 'text-embedding-ada-002')。
2024-08-08 00:28:33,961 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:8000/v1/embeddings "HTTP/1.1 400 Bad Request"
2024-08-08 00:28:33,964 - embeddings_api.py[line:39] - ERROR: Error code: 400 - {'object': 'error', 'message': '**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(The expanded size of the tensor (513) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [4, 513].  Tensor sizes: [1, 512])', 'code': 50001}
2024-08-08 00:28:33,966 - base.py[line:36] - INFO: thread 40446 开始操作：('20240806', 'text-embedding-ada-002')。
2024-08-08 00:28:33,966 - base.py[line:40] - INFO: thread 40446 结束操作：('20240806', 'text-embedding-ada-002')。
INFO:     58.213.224.244:3297 - "POST /knowledge_base/upload_docs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/data/workcode/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 173, in upload_docs
    result = update_docs(
  File "/data/workcode/Langchain-Chatchat/server/knowledge_base/kb_doc_api.py", line 290, in update_docs
    kb.update_doc(kb_file, not_refresh_vs_cache=True)
  File "/data/workcode/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 166, in update_doc
    return self.add_doc(kb_file, docs=docs, **kwargs)
  File "/data/workcode/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 132, in add_doc
    doc_infos = self.do_add_doc(docs, **kwargs)
  File "/data/workcode/Langchain-Chatchat/server/knowledge_base/kb_service/faiss_kb_service.py", line 78, in do_add_doc
    ids = vs.add_embeddings(text_embeddings=zip(data["texts"], data["embeddings"]),
TypeError: 'NoneType' object is not subscriptable

我在api接口测试embedd_texts 他是OK的 ，返回结果如下：
2024-08-08 00:41:32,839 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:8000/v1/embeddings "HTTP/1.1 200 OK"
INFO:     58.213.224.244:3298 - "POST /other/embed_texts HTTP/1.1" 200 OK
2024-08-08 00:56:20,117 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:8000/v1/embeddings "HTTP/1.1 200 OK"
INFO:     58.213.224.244:3299 - "POST /other/embed_texts HTTP/1.1" 200 OK

能帮我看看这个错误如何解决吗

**Comment by Nancy7zt** [comment]
...为啥关啦  看看有没有人解决了这个啊
