### ISSUE TITLE
Xinference 部署glm-4-9b-chat 运行报错 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

### ISSUE THREAD

**Issue by tyler326** [chatchat-space/Langchain-Chatchat#4829]
2024-08-16 16:05:43,985 xinference.api.restful_api 20844 ERROR    Chat completion stream got an error: [address=127.0.0.1:57433, pid=17372] 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'
Traceback (most recent call last):
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\api\restful_api.py", line 1678, in stream_results
    iterator = await model.chat(
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\core\utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\core\model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xoscar\api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\core\model.py", line 523, in chat
    response = await self._call_wrapper_json(
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\core\model.py", line 393, in _call_wrapper_json
    return await self._call_wrapper("json", fn, *args, **kwargs)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\core\model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\core\model.py", line 404, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "D:\Software\Anaconda\envs\xinference\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "D:\Software\Anaconda\envs\xinference\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\model\llm\pytorch\chatglm.py", line 481, in chat
    stream_chat = self._model.stream_chat
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: [address=127.0.0.1:57433, pid=17372] 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'
Traceback (most recent call last):
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\utils.py", line 583, in async_iteration
    return await iterator.__anext__()
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\utils.py", line 709, in asyncgen_wrapper
    response = await iterator.__anext__()
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\chat_interface.py", line 545, in _stream_fn
    first_response = await async_iteration(generator)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\utils.py", line 583, in async_iteration
    return await iterator.__anext__()
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\gradio\utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\core\chat_interface.py", line 124, in generate_wrapper
    for chunk in model.chat(
  File "D:\Software\Anaconda\envs\xinference\lib\site-packages\xinference\client\common.py", line 51, in streaming_response_iterator
    raise Exception(str(error))
Exception: [address=127.0.0.1:57433, pid=17372] 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

**Comment by liunux4odoo** [comment]
与chatchat无关的问题，建议到xinference讨论区看看。
