### ISSUE TITLE
[BUG] 用openAI接口方式访问Fastchat封装的qwen2-57Bint4时遇到问题,utils.py[line:38] - ERROR: Connection error.

### ISSUE THREAD

**Issue by pdwfree** [chatchat-space/Langchain-Chatchat#4842]
Use Fastchat to make the qwen2-57Bint4 to an openai service
use opanai api to ask the LLM
It's ok  when use qwen2-7bint model
but if use qwen2-57bint4
Can not get any answear in chatbox
to see the console:
服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
==============================Langchain-Chatchat Configuration==============================

2024-08-20 23:24:50,764 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53968 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-08-20 23:24:50,877 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53968 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
INFO:     127.0.0.1:53968 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-08-20 23:25:10,337 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53976 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-08-20 23:25:10,349 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:53976 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
INFO:     127.0.0.1:53976 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
INFO:     127.0.0.1:53976 - "POST /chat/chat HTTP/1.1" 200 OK
L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-08-20 23:25:21,398 - _base_client.py[line:1524] - INFO: Retrying request to /chat/completions in 0.869553 seconds
2024-08-20 23:25:33,399 - _base_client.py[line:1524] - INFO: Retrying request to /chat/completions in 1.943461 seconds
2024-08-20 23:25:46,400 - utils.py[line:38] - ERROR: Connection error.
Traceback (most recent call last):
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    yield
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpx\_transports\default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpcore\_async\http11.py", line 143, in handle_async_request
    raise exc
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpcore\_async\http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpcore\_async\http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\_base_client.py", line 1435, in _request
    response = await self._client.send(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpx\_client.py", line 1646, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpx\_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpx\_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpx\_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpx\_transports\default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain_core\language_models\chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain_core\language_models\chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain_core\language_models\chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain_community\chat_models\openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain_core\language_models\chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain_community\chat_models\openai.py", line 488, in _astream
    async for chunk in await acompletion_with_retry(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain_community\chat_models\openai.py", line 105, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\resources\chat\completions.py", line 1300, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\_base_client.py", line 1703, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\_base_client.py", line 1406, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\_base_client.py", line 1459, in _request
    return await self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\_base_client.py", line 1528, in _retry_request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\_base_client.py", line 1459, in _request
    return await self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\_base_client.py", line 1528, in _retry_request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "L:\Langchain-Chatchat\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\openai\_base_client.py", line 1469, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
2024-08-20 23:25:46,412 - utils.py[line:40] - ERROR: APIConnectionError: Caught exception: Connection error. 

I run python in windows10, gpu is 4080 16G( use 18.5G system memory,Fastchat Report No error, seems to load success )
any one can help me?
thanks!

**Comment by liunux4odoo** [comment]
0.2.x 版本已经停止维护。
