### ISSUE TITLE
[BUG] 不能进行图文对话

### ISSUE THREAD

**Issue by Qacket** [chatchat-space/Langchain-Chatchat#4888]
问题描述 / Problem Description
确定在xinference中已经启动了qwen-vl-chat模型或者glm-4v-9b，在webui的模型配置中也能够选择qwen-vl-chat，可以进行正常的文本对话，但是图文问答时，报错。

报错信息：
xinference
{'platform_name': 'xinference', 'platform_type': 'xinference', 'api_base_url': 'http://172.16.10.125:9997/v1', 'api_key': 'EMPTY', 'api_proxy': '', 'api_concurrencies': 5, 'auto_detect_model': True, 'llm_models': [], 'embed_models': [], 'text2image_models': [], 'image2text_models': [], 'rerank_models': [], 'speech2text_models': [], 'text2speech_models': []}
-------------------------- {'messages': [{'content': SerializationIterator(index=0, iterator=ValidatorIterator(index=0, schema=Some(Union(UnionValidator { mode: Smart, choices: [(DefinitionRef(DefinitionRefValidator { definition: "typed-dict" }), None), (TypedDict(TypedDictValidator { fields: [TypedDictField { name: "image_url", lookup_key: Simple { key: "image_url", py_key: Py(0x1d9ebf1f5f0), path: LookupPath([S("image_url", Py(0x1d9ebf1f5b0))]) }, name_py: Py(0x1d9ea4456b0), required: true, validator: TypedDict(TypedDictValidator { fields: [TypedDictField { name: "url", lookup_key: Simple { key: "url", py_key: Py(0x1d9ebf1f570), path: LookupPath([S("url", Py(0x1d9ebf1f6b0))]) }, name_py: Py(0x1d9d5a03730), required: true, validator: Str(StrValidator { strict: false, coerce_numbers_to_str: false }) }, TypedDictField { name: "detail", lookup_key: Simple { key: "detail", py_key: Py(0x1d9ebf1f4f0), path: LookupPath([S("detail", Py(0x1d9ebf1f530))]) }, name_py: Py(0x1d9e4622270), required: false, validator: Literal(LiteralValidator { lookup: LiteralLookup { expected_bool: None, expected_int: None, expected_str: Some({"auto": 0, "low": 1, "high": 2}), expected_py_dict: None, expected_py_list: None, values: [Py(0x1d9d3d92730), Py(0x1d9d5be2df0), Py(0x1d9d5be2db0)] }, expected_repr: "'auto', 'low' or 'high'", name: "literal['auto','low','high']" }) }], extra_behavior: Allow, extras_validator: None, strict: false, loc_by_alias: true }) }, TypedDictField { name: "type", lookup_key: Simple { key: "type", py_key: Py(0x1d9ebf1f470), path: LookupPath([S("type", Py(0x1d9ebf1f4b0))]) }, name_py: Py(0x1d9d3635bb0), required: true, validator: Literal(LiteralValidator { lookup: LiteralLookup { expected_bool: None, expected_int: None, expected_str: Some({"image_url": 0}), expected_py_dict: None, expected_py_list: None, values: [Py(0x1d9ea4456b0)] }, expected_repr: "'image_url'", name: "literal['image_url']" }) }], extra_behavior: Allow, extras_validator: None, strict: false, loc_by_alias: true }), None)], custom_error: None, strict: false, name: "union[typed-dict,typed-dict]" })))), 'role': 'user'}], 'model': 'glm-4v-9b-model', 'max_tokens': None, 'stream': False}
<bound method AsyncCompletions.create of <openai.resources.chat.completions.AsyncCompletions object at 0x000001D9ED35ADF0>> 333333333333333333333333
2024-08-29 11:38:01,143 httpx        6636 INFO     HTTP Request: POST http://172.16.10.125:9997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
2024-08-29 11:38:01,144 openai._base_client 6636 INFO     Retrying request to /chat/completions in 0.871416 seconds
2024-08-29 11:38:02,041 httpx        6636 INFO     HTTP Request: POST http://172.16.10.125:9997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
2024-08-29 11:38:02,044 openai._base_client 6636 INFO     Retrying request to /chat/completions in 1.526123 seconds
2024-08-29 11:38:03,605 httpx        6636 INFO     HTTP Request: POST http://172.16.10.125:9997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:     127.0.0.1:63694 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-08-29 11:38:03,607 httpx        19764 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 398, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\pujian\Desktop\Langchain-Chatchat\libs\chatchat-server\chatchat\server\api_server\chat_routes.py", line 213, in chat_completions
    return await openai_request(
  File "C:\Users\pujian\Desktop\Langchain-Chatchat\libs\chatchat-server\chatchat\server\api_server\openai_routes.py", line 117, in openai_request
    result = await method(**params)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\resources\chat\completions.py", line 1305, in create
    return await self._post(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_base_client.py", line 1815, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_base_client.py", line 1509, in request
    return await self._request(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_base_client.py", line 1595, in _request
    return await self._retry_request(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_base_client.py", line 1642, in _retry_request
    return await self._request(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_base_client.py", line 1595, in _request
    return await self._retry_request(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_base_client.py", line 1642, in _retry_request
    return await self._request(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_base_client.py", line 1610, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'detail': '[address=0.0.0.0:44199, pid=5615] None: Max retries exceeded with url: /v1/files/YXNzaXN0YW50cy8yMDI0LTA4LTI5LzAwMDAwMDAwNzgxNi5wbmc=/content (Caused by None)'}
2024-08-29 11:38:03,609 openai._base_client 19764 INFO     Retrying request to /chat/completions in 1.686473 seconds

**Comment by wpcwpcwpc** [comment]
我也遇到了同样的问题，
```
if stream:
            try:
                for d in client.chat.completions.create(**params):`
```
这一步之前messages中的content仍然是正常的字典组，进入到
```
@chat_router.post("/chat/completions", summary="兼容 openai 的统一 chat 接口")
async def chat_completions(
    request: Request,
    body: OpenAIChatInput,
) -> Dict: 
```
这个接口后，body中对应的messages里的content变成了
```
[{'content': ValidatorIterator(index=0, schema=Some(Union(UnionValidator { mode: Smart, choices: [... name: "union[typed-dict,typed-dict]" }))), 'role': 'user'}]
```
问了某大模型后给出的可能原因如下：但我自己目前还是找不到解决方法。

自定义验证器或钩子：项目中可能有自定义的 Pydantic 验证器或模型钩子（如 validator 装饰器或 pre_save/post_save 钩子），这些在数据被处理时修改了 content 字段。
序列化/反序列化问题：在将数据发送到 OpenAI API 之前或之后，可能进行了某种形式的序列化或反序列化，这可能导致数据类型的变化。
中间件或代理：如果请求是通过某种中间件或代理发送的，这些组件可能会修改请求体。
错误的调试输出：有时，调试工具或日志记录可能会以非预期的方式显示对象，特别是当对象具有复杂的内部结构或自定义的 __repr__ 方法时。

**Comment by wpcwpcwpc** [comment]
已有解决方案：我是用的 ollama 平台，llava多模态模型进行的图文对话。然而Ollama官网给出的openai的多模态接口（https://github.com/ollama/ollama/blob/main/docs/openai.md）与Openai的官方接口（https://platform.openai.com/docs/guides/vision）有出入，仅需参考openai官方提供的图文messages的格式，并修改{PathToProject}\libs\chatchat-server\chatchat\webui_pages\dialogue\dialogue.py的行号403开始的VisonChat部分的代码

**Comment by Qacket** [comment]
> 我也遇到了同样的问题，
> 
> ```
> if stream:
>             try:
>                 for d in client.chat.completions.create(**params):`
> ```
> 
> 这一步之前messages中的content仍然是正常的字典组，进入到
> 
> ```
> @chat_router.post("/chat/completions", summary="兼容 openai 的统一 chat 接口")
> async def chat_completions(
>     request: Request,
>     body: OpenAIChatInput,
> ) -> Dict: 
> ```
> 
> 这个接口后，body中对应的messages里的content变成了
> 
> ```
> [{'content': ValidatorIterator(index=0, schema=Some(Union(UnionValidator { mode: Smart, choices: [... name: "union[typed-dict,typed-dict]" }))), 'role': 'user'}]
> ```
> 
> 问了某大模型后给出的可能原因如下：但我自己目前还是找不到解决方法。
> 
> 自定义验证器或钩子：项目中可能有自定义的 Pydantic 验证器或模型钩子（如 validator 装饰器或 pre_save/post_save 钩子），这些在数据被处理时修改了 content 字段。 序列化/反序列化问题：在将数据发送到 OpenAI API 之前或之后，可能进行了某种形式的序列化或反序列化，这可能导致数据类型的变化。 中间件或代理：如果请求是通过某种中间件或代理发送的，这些组件可能会修改请求体。 错误的调试输出：有时，调试工具或日志记录可能会以非预期的方式显示对象，特别是当对象具有复杂的内部结构或自定义的 **repr** 方法时。



> 已有解决方案：我是用的ollama平台，llava多模态模型进行的图文对话。然而Ollama官网给出的openai的[多模态接口](https://github.com/ollama/ollama/blob/main/docs/openai.md),与openai的[官方接口](https://platform.openai.com/docs/guides/vision)有出入，仅需参考openai官方提供的图文messages的格式，并修改{PathToProject}\libs\chatchat-server\chatchat\webui_pages\dialogue\dialogue.py的行号403开始的VisonChat部分的代码))

感谢提供的参考信息，我用的xinference平台，多模态模型用的是glm-4v-9b，将403行的url修改为image_url可以正常图文对话。

**Comment by Qacket** [comment]
还有个问题是，您的文本对话模型和多模态模使用同一个模型吗？我将get_default_llm()的model_type改成image2text，支持文本对话，但图文对话时，出现了新的错误。



xinference
{'platform_name': 'xinference', 'platform_type': 'xinference', 'api_base_url': 'http://172.16.10.125:9997/v1', 'api_key': 'EMPTY', 'api_proxy': '', 'api_concurrencies': 5, 'auto_detect_model': True, 'llm_models': [], 'embed_models': [], 'text2image_models': [], 'image2text_models': [], 'rerank_models': [], 'speech2text_models': [], 'text2speech_models': []}
-------------------------- {'messages': [{'content': SerializationIterator(index=0, iterator=ValidatorIterator(index=0, schema=Some(Union(UnionValidator { mode: Smart, choices: [(DefinitionRef(DefinitionRefValidator { definition: "typed-dict" }), None), (TypedDict(TypedDictValidator { fields: [TypedDictField { name: "image_url", lookup_key: Simple { key: "image_url", py_key: Py(0x124ee4a02b0), path: LookupPath([S("image_url", Py(0x124ee4b52b0))]) }, name_py: Py(0x124eca253b0), required: true, validator: TypedDict(TypedDictValidator { fields: [TypedDictField { name: "url", lookup_key: Simple { key: "url", py_key: Py(0x124ee4b3230), path: LookupPath([S("url", Py(0x124ee4b3e30))]) }, name_py: Py(0x124d7ff3930), required: true, validator: Str(StrValidator { strict: false, coerce_numbers_to_str: false }) }, TypedDictField { name: "detail", lookup_key: Simple { key: "detail", py_key: Py(0x124ee4928b0), path: LookupPath([S("detail", Py(0x124ee4a0370))]) }, name_py: Py(0x124e6c123b0), required: false, validator: Literal(LiteralValidator { lookup: LiteralLookup { expected_bool: None, expected_int: None, expected_str: Some({"auto": 0, "low": 1, "high": 2}), expected_py_dict: None, expected_py_list: None, values: [Py(0x124d63a2670), Py(0x124d81d2eb0), Py(0x124d81d2e70)] }, expected_repr: "'auto', 'low' or 'high'", name: "literal['auto','low','high']" }) }], extra_behavior: Allow, extras_validator: None, strict: false, loc_by_alias: true }) }, TypedDictField { name: "type", lookup_key: Simple { key: "type", py_key: Py(0x124ee4b5670), path: LookupPath([S("type", Py(0x124ee4f8f30))]) }, name_py: Py(0x124d5fb5bb0), required: true, validator: Literal(LiteralValidator { lookup: LiteralLookup { expected_bool: None, expected_int: None, expected_str: Some({"image_url": 0}), expected_py_dict: None, expected_py_list: None, values: [Py(0x124eca253b0)] }, expected_repr: "'image_url'", name: "literal['image_url']" }) }], extra_behavior: Allow, extras_validator: None, strict: false, loc_by_alias: true }), None)], custom_error: None, strict: false, name: "union[typed-dict,typed-dict]" })))), 'role': 'user'}], 'model': 'glm-4v-9b-model', 'max_tokens': None, 'stream': False}
<bound method AsyncCompletions.create of <openai.resources.chat.completions.AsyncCompletions object at 0x00000124EF91E9D0>> 333333333333333333333333
INFO:     127.0.0.1:58068 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
2024-09-02 14:48:10,608 httpx        6684 INFO     HTTP Request: POST http://127.0.0.1:7861/chat/chat/completions "HTTP/1.1 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 398, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\pujian\Desktop\Langchain-Chatchat\libs\chatchat-server\chatchat\server\api_server\chat_routes.py", line 213, in chat_completions
    return await openai_request(
  File "C:\Users\pujian\Desktop\Langchain-Chatchat\libs\chatchat-server\chatchat\server\api_server\openai_routes.py", line 117, in openai_request
    result = await method(**params)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\resources\chat\completions.py", line 1307, in create
    body=await async_maybe_transform(
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 257, in async_maybe_transform
    return await async_transform(data, expected_type)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 279, in async_transform
    transformed = await _async_transform_recursive(data, annotation=cast(type, expected_type))
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 323, in _async_transform_recursive
    data = await _async_transform_recursive(data, annotation=annotation, inner_type=subtype)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 306, in _async_transform_recursive
    return await _async_transform_typeddict(data, stripped_type)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 381, in _async_transform_typeddict
    result[_maybe_transform_key(key, type_)] = await _async_transform_recursive(value, annotation=type_)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 315, in _async_transform_recursive
    return [await _async_transform_recursive(d, annotation=annotation, inner_type=inner_type) for d in data]
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 315, in <listcomp>
    return [await _async_transform_recursive(d, annotation=annotation, inner_type=inner_type) for d in data]
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 323, in _async_transform_recursive
    data = await _async_transform_recursive(data, annotation=annotation, inner_type=subtype)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 306, in _async_transform_recursive
    return await _async_transform_typeddict(data, stripped_type)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 381, in _async_transform_typeddict
    result[_maybe_transform_key(key, type_)] = await _async_transform_recursive(value, annotation=type_)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 323, in _async_transform_recursive
    data = await _async_transform_recursive(data, annotation=annotation, inner_type=subtype)
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 315, in _async_transform_recursive
    return [await _async_transform_recursive(d, annotation=annotation, inner_type=inner_type) for d in data]
  File "F:\anaconda3\envs\chatchat_dev\lib\site-packages\openai\_utils\_transform.py", line 315, in <listcomp>
    return [await _async_transform_recursive(d, annotation=annotation, inner_type=inner_type) for d in data]
pydantic_core._pydantic_core.ValidationError: 3 validation errors for ValidatorIterator
1.typed-dict.text
  Field required [type=missing, input_value={'type': 'image_url', 'im...wNzgxNi5wbmc=/content'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
1.typed-dict.type
  Input should be 'text' [type=literal_error, input_value='image_url', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/literal_error
1.typed-dict.image_url.url
  Field required [type=missing, input_value={'image_url': 'http://127...AwNzgxNi5wbmc=/content'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

**Comment by wpcwpcwpc** [comment]
我这里chat model用到 llama3.1, image2text用的llava,仅编辑了yarm配置文件，如果有上传图片，按照代码逻辑，会调用多模态模型的，你遇到的错误我不太清楚，在我看来，get_default_llm() 方法并没有问题，如果是希望调用多模态模型，应该在model_settings.yarm里修改配置就可以了。

**Comment by jiusi9** [comment]
> 如果是希望调用多模态模型，应该在model_settings.yaml里修改配置就可以了。



> > 我也遇到了同样的问题，
> > ```
> > if stream:
> >             try:
> >                 for d in client.chat.completions.create(**params):`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这一步之前messages中的content仍然是正常的字典组，进入到
> > ```
> > @chat_router.post("/chat/completions", summary="兼容 openai 的统一 chat 接口")
> > async def chat_completions(
> >     request: Request,
> >     body: OpenAIChatInput,
> > ) -> Dict: 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个接口后，body中对应的messages里的content变成了
> > ```
> > [{'content': ValidatorIterator(index=0, schema=Some(Union(UnionValidator { mode: Smart, choices: [... name: "union[typed-dict,typed-dict]" }))), 'role': 'user'}]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 问了某大模型后给出的可能原因如下：但我自己目前还是找不到解决方法。
> > 自定义验证器或钩子：项目中可能有自定义的 Pydantic 验证器或模型钩子（如 validator 装饰器或 pre_save/post_save 钩子），这些在数据被处理时修改了 content 字段。 序列化/反序列化问题：在将数据发送到 OpenAI API 之前或之后，可能进行了某种形式的序列化或反序列化，这可能导致数据类型的变化。 中间件或代理：如果请求是通过某种中间件或代理发送的，这些组件可能会修改请求体。 错误的调试输出：有时，调试工具或日志记录可能会以非预期的方式显示对象，特别是当对象具有复杂的内部结构或自定义的 **repr** 方法时。
> 
> > 已有解决方案：我是用的ollama平台，llava多模态模型进行的图文对话。然而Ollama官网给出的openai的[多模态接口](https://github.com/ollama/ollama/blob/main/docs/openai.md),与openai的[官方接口](https://platform.openai.com/docs/guides/vision)有出入，仅需参考openai官方提供的图文messages的格式，并修改{PathToProject}\libs\chatchat-server\chatchat\webui_pages\dialogue\dialogue.py的行号403开始的VisonChat部分的代码))
> 
> 感谢提供的参考信息，我用的xinference平台，多模态模型用的是glm-4v-9b，将403行的url修改为image_url可以正常图文对话。

请问是怎么修改的url这部分呀，可以share一下吗
![image](https://github.com/user-attachments/assets/9896110c-6ded-4c84-9c4f-6c8f2bfb5e6c)

**Comment by wpcwpcwpc** [comment]
```
def get_image_64encode(image_url:str) -> str:
    response = requests.get(image_url)  
    image_data = response.content  
    return f"data:image/jpeg;base64,{base64.b64encode(image_data).decode('utf-8')}" 
###############################################################
client = openai.Client(base_url=f"{api_address()}/chat", api_key="NONE")
        if is_vision_chat: # multimodal chat
            content = [
                {"type": "text", "text": prompt},
                {"type": "image_url", "image_url": {"url": get_image_64encode(get_image_file_url(upload_image))}}
            ]
            messages = [{"role": "user", "content": content}]
        else:
            messages = history + [{"role": "user", "content": prompt}]
```

**Comment by Alan-zhong** [comment]
为什么我使用qwen-vl-chat必须先上传图片才能进行对话，不能直接进行文本对话？
