### ISSUE TITLE
[BUG] qwen2.5在WEBUI中可以正常调用，通过api调用返回不支持tools call / It works in WEBUI when using the model 'qwen2.5', but an error occurred in api call, it return "only [xxx] support tool calls"

### ISSUE THREAD

**Issue by mttbyte** [chatchat-space/Langchain-Chatchat#5006]
**问题描述**
在xinference里我切换了模型为qwen2.5-instruct的7b模型，在WEBUI中可以正常使用，但是通过api访问时返回{'detail': "Only ['qwen1.5-chat', 'qwen1.5-moe-chat', 'qwen2-instruct', 'qwen2-moe-instruct', 'glm4-chat', 'glm4-chat-1m'] support tool calls"}

**复现问题的步骤**
1. 在xinference里用vllm加载qwen2.5-instruct-7b
2. 相同代码调用api中的/chat/chat/completions
3.无返回，查看窗口提示
openai.BadRequestError: Error code: 400 - {'detail': "Only ['qwen1.5-chat', 'qwen1.5-moe-chat', 'qwen2-instruct', 'qwen2-moe-instruct', 'glm4-chat', 'glm4-chat-1m'] support tool calls"}

**预期的结果**
和前端一样正确返回

**实际结果**
INFO:     127.0.0.1:59766 - "POST /chat/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/chatchat/server/api_server/chat_routes.py", line 208, in chat_completions
    return await openai_request(
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/chatchat/server/api_server/openai_routes.py", line 115, in openai_request
    result = await method(**params)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1295, in create
    return await self._post(
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/openai/_base_client.py", line 1826, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/openai/_base_client.py", line 1519, in request
    return await self._request(
  File "/home/sutai/miniconda3/envs/langchain/lib/python3.10/site-packages/openai/_base_client.py", line 1620, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'detail': "Only ['qwen1.5-chat', 'qwen1.5-moe-chat', 'qwen2-instruct', 'qwen2-moe-instruct', 'glm4-chat', 'glm4-chat-1m'] support tool calls"}

**环境信息**
- Langchain-Chatchat 版本 / commit 号：0.3.1.3
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：pypi安装
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference 
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：qwen2.5-instruct-7b
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu22.04
- Python 版本 / Python version: 3.10.14
- 推理使用的硬件（GPU / CPU / MPS / NPU 等）:GPU (Nvidia RTX 4090)

**附加信息**
1.发送的json内容：
Id: 0
User: Euler
Timeout: 600
MaxTokens: 4096
Messages: [{你是人工智能助手 system system} {测试 user Euler}]
Stream: false
Model: qwen2.5-instruct
Temperature: 0.7
TopP: 0.8
RepetitionPenalty: 1.05
Flag: 0
Tools: []

2.曾经代码正确执行过，原因未知

**Comment by wangsiyu666** [comment]
更新xinference，并重新启动xinference。

**Comment by mttbyte** [comment]
> 更新xinference，并重新启动xinference。

成功了，多谢，为何问题居然是出现在xinference里……

**Comment by zx0406** [comment]
> 我在配置文件中均调用的qwen2.5，但是实际weibu中却提示condaERROR chatchat.server.api server.openai routes:generator:105 openal request error:Connection error. 有大佬知道啥情况吗

请问这个问题解决了吗？我现在也出现这个问题了，出现的情况是在图片问答的时候，我的模型是Qwen2.5-7B-instruct

**Comment by zx0406** [comment]
> 我在配置文件中均调用的qwen2.5，但是实际weibu中却提示condaERROR chatchat.server.api server.openai routes:generator:105 openal request error:Connection error. 有大佬知道啥情况吗

请问这个问题解决了吗？我现在也出现这个问题了，出现的情况是在图片问答的时候，我的模型是Qwen2.5-7B-instruct

**Comment by zx0406** [comment]
> 我在配置文件中均调用的qwen2.5，但是实际weibu中却提示condaERROR chatchat.server.api server.openai routes:generator:105 openal request error:Connection error. 有大佬知道啥情况吗

请问这个问题解决了吗？我现在也出现这个问题了，出现的情况是在图片问答的时候，我的模型是Qwen2-VL

**Comment by zx0406** [comment]
> 我在配置文件中均调用的qwen2.5，但是实际weibu中却提示condaERROR chatchat.server.api server.openai routes:generator:105 openal request error:Connection error. 有大佬知道啥情况吗

请问这个问题解决了吗？我现在也出现这个问题了，出现的情况是在图片问答的时候，我的模型是Qwen2-VL
