### ISSUE TITLE
[BUG] 0.2版本初始化知识库和配置文件 报错 python init_database.py --recreate-vs

### ISSUE THREAD

**Issue by wxy-1121** [chatchat-space/Langchain-Chatchat#5077]
下载到本地的embedding模型和llm模型都配置model_config里面修改了路径和配置项，但是在初始化知识库的时候报错，
其中的sentence_transformers包也下载过了，还是报错
![20241114153229](https://github.com/user-attachments/assets/cf993e8c-54ac-40b4-b9ee-0b65214dae87)
![20241114153240](https://github.com/user-attachments/assets/4012553e-304f-421f-b3ba-f0cb429a265a)
![20241114153325](https://github.com/user-attachments/assets/9bdb7017-aae8-4566-8b90-5528f64f4450)

2024-11-14 15:31:08,245 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
recreating all vector stores
2024-11-14 15:31:08,695 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh-v1.5' from disk.
2024-11-14 15:31:08,876 - embeddings_api.py[line:39] - ERROR: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\workarea\pycharm_projects\0.2final\init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "D:\workarea\pycharm_projects\0.2final\server\knowledge_base\migrate.py", line 121, in folder2db
    kb.create_kb()
  File "D:\workarea\pycharm_projects\0.2final\server\knowledge_base\kb_service\base.py", line 82, in create_kb
    self.do_create_kb()
  File "D:\workarea\pycharm_projects\0.2final\server\knowledge_base\kb_service\faiss_kb_service.py", line 51, in do_create_kb
    self.load_vector_store()
  File "D:\workarea\pycharm_projects\0.2final\server\knowledge_base\kb_service\faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workarea\pycharm_projects\0.2final\server\knowledge_base\kb_cache\faiss_cache.py", line 102, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workarea\pycharm_projects\0.2final\server\knowledge_base\kb_cache\faiss_cache.py", line 60, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, distance_strategy="METRIC_INNER_PRODUCT")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\langchain_core\vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 959, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workarea\pycharm_projects\0.2final\server\knowledge_base\kb_service\base.py", line 443, in embed_documents
    return normalize(embeddings).tolist()
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\workarea\pycharm_projects\0.2final\server\knowledge_base\kb_service\base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in norm
  File "D:\python\Lib\site-packages\numpy\linalg\linalg.py", line 2541, in norm
    s = (x.conj() * x).real
         ^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by Yuhao-Luo** [comment]
你先看看这个，https://github.com/chatchat-space/Langchain-Chatchat/issues/3472
另外，我遇到的问题是，我从我自己的pip requirements里导入的 torch 不支持cuda，而我写死了device==cuda
