### ISSUE TITLE
[BUG] 知识库上传时发生ERROR (could not open xxx for reading: No such file or directory)

### ISSUE THREAD

**Issue by czs1993** [chatchat-space/Langchain-Chatchat#510]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
知识库上传文件--》上传文件--》上传文件并加载知识库
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs
Traceback (most recent call last):
  File "C:\Users\Sundy\anaconda3\envs\lcglm39\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Sundy\anaconda3\envs\lcglm39\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\Sundy\anaconda3\envs\lcglm39\lib\site-packages\gradio\blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Sundy\anaconda3\envs\lcglm39\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Sundy\anaconda3\envs\lcglm39\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Sundy\anaconda3\envs\lcglm39\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\codeai\langchainChatGLMdev\webui.py", line 152, in get_vector_store
    vs_path, loaded_files = local_doc_qa.init_knowledge_vector_store(filelist, vs_path, sentence_size)
  File "c:\codeai\langchainChatGLMdev\chains\local_doc_qa.py", line 241, in init_knowledge_vector_store
    vector_store = FAISS.load_local(vs_path, self.embeddings)
  File "C:\Users\Sundy\anaconda3\envs\lcglm39\lib\site-packages\langchain\vectorstores\faiss.py", line 502, in load_local
    index = faiss.read_index(
  File "C:\Users\Sundy\anaconda3\envs\lcglm39\lib\site-packages\faiss\swigfaiss.py", line 9795, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open c:\codeai\langchainChatGLMdev\vector_store\test03\index.faiss for reading: No such file or directory

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
知识库文件上传成功，并可用于后续会话
**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
知识库文件上传失败！
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 最新版
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): 否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.9
- 其他相关环境信息 / Other relevant environment information:
上传文件名： sec01.txt

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by tangerys** [comment]
我也出现这个问题。不知道怎么解决

**Comment by TimX914** [comment]
同问

**Comment by czs1993** [comment]
我后面更新到最新版本就没有这个问题了[langchain-ChatGLM v0.1.14]

**Comment by qq7286590** [comment]
怎么更新到V0.1.14

**Comment by czs1993** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/tree/v0.1.14
