### ISSUE TITLE
[BUG] 简洁阐述问题 多功能对话正常但RAG对话和知识库管理报错

### ISSUE THREAD

**Issue by liu697** [chatchat-space/Langchain-Chatchat#5118]
cwd:/data/user20300129/Langchain-Chatchat

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.5.0-44-generic-x86_64-with-glibc2.35.
python版本：3.11.10 (main, Oct  3 2024, 07:29:13) [GCC 11.2.0]
项目版本：0.3.1.3
langchain版本：0.1.17
数据目录：/data/user20300129/Langchain-Chatchat

当前使用的分词器：ChineseRecursiveTextSplitter
默认选用的 Embedding 名称： bge_large_zh_v1.5
==============================Langchain-Chatchat Configuration==============================

2024-11-29 21:28:06.229 | INFO     | chatchat.startup:start_main_server:257 - 正在启动服务：
2024-11-29 21:28:06.230 | INFO     | chatchat.startup:start_main_server:258 - 如需查看 llm_api 日志，请前往 /data/user20300129/Langchain-Chatchat/data/logs
/data/user20300129/.conda/envs/Langchain_LJL/lib/python3.11/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
  warnings.warn(
/data/user20300129/.conda/envs/Langchain_LJL/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
2024-11-29 21:28:08.720 | INFO     | chatchat.startup:run_api_server:55 - Api MODEL_PLATFORMS: [PlatformConfig(platform_name='xinference', platform_type='xinference', api_base_url='http://127.0.0.1:9997/v1', api_key='EMPTY', api_proxy='', api_concurrencies=5, auto_detect_model=True, llm_models=['Qwen2.5_14B_Instruct'], embed_models=['bge_large_zh_v1.5'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[])]
INFO:     Started server process [2929051]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
2024-11-29 21:28:10.295 | INFO     | chatchat.startup:run_webui:80 - Webui MODEL_PLATFORMS: [PlatformConfig(platform_name='xinference', platform_type='xinference', api_base_url='http://127.0.0.1:9997/v1', api_key='EMPTY', api_proxy='', api_concurrencies=5, auto_detect_model=True, llm_models=['Qwen2.5_14B_Instruct'], embed_models=['bge_large_zh_v1.5'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[])]

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2024-11-29 21:28:17.413 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /tools: Client.__init__() got an unexpected keyword argument 'proxies'
2024-11-29 21:28:17.416 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /tools: Client.__init__() got an unexpected keyword argument 'proxies'
2024-11-29 21:28:17.416 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /tools: Client.__init__() got an unexpected keyword argument 'proxies'
2024-11-29 21:28:17.416 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-11-29 21:28:22.193 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2024-11-29 21:28:22.196 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2024-11-29 21:28:22.196 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2024-11-29 21:28:22.197 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-11-29 21:28:22.197 Uncaught app exception
Traceback (most recent call last):
  File "/data/user20300129/.conda/envs/Langchain_LJL/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/data/user20300129/.conda/envs/Langchain_LJL/lib/python3.11/site-packages/chatchat/webui.py", line 71, in <module>
    kb_chat(api=api)
  File "/data/user20300129/.conda/envs/Langchain_LJL/lib/python3.11/site-packages/chatchat/webui_pages/kb_chat.py", line 118, in kb_chat
    kb_list = [x["kb_name"] for x in api.list_knowledge_bases()]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

I ran the chatchat kb -r command to initialize the knowledge base, and everything worked fine. However, when I run chatchat start -a, I encounter the issue mentioned above. How can I solve this?

**Comment by liu697** [comment]
我运行chatchat kb -r命令初始化知识库一切正常，但是chatchat start -a就会遇到上述问题，请问要如何解决。

**Comment by caoyao11** [comment]
我这里依旧是报错的
2025-02-05 14:38:01.662 Uncaught app exception
Traceback (most recent call last):
  File "/data/software/miniforge3/envs/langchain/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/data/software/miniforge3/envs/langchain/lib/python3.10/site-packages/chatchat/webui.py", line 71, in <module>
    kb_chat(api=api)
  File "/data/software/miniforge3/envs/langchain/lib/python3.10/site-packages/chatchat/webui_pages/kb_chat.py", line 118, in kb_chat
    kb_list = [x["kb_name"] for x in api.list_knowledge_bases()]
TypeError: 'NoneType' object is not iterable
2025-02-05 14:38:01.966 | ERROR    | chatchat.webui_pages.utils:get:64 - ValueError: error when get /knowledge_base/list_knowledge_bases: Unknown scheme for proxy URL URL(

**Comment by wo2ow** [comment]
我也是报错的，请问你们解决了吗
2025-02-26 17:01:54.490 | WARNING  | chatchat.server.utils:get_default_llm:205 - default llm model glm4-chat is not found in available llms, using deepseek-r1:1.5b instead
2025-02-26 17:01:54.495 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2025-02-26 17:01:54.498 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2025-02-26 17:01:54.498 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2025-02-26 17:01:54.499 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2025-02-26 17:01:54.499 Uncaught app exception
Traceback (most recent call last):
  File "/Users/anaconda3/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/Users/Langchain-Chatchat/libs/chatchat-server/chatchat/webui.py", line 71, in <module>
    kb_chat(api=api)
  File "/Users/Langchain-Chatchat/libs/chatchat-server/chatchat/webui_pages/kb_chat.py", line 118, in kb_chat
    kb_list = [x["kb_name"] for x in api.list_knowledge_bases()]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by whatattitude** [comment]
我这里ubuntu的环境，也一样报错,并且httpx版本已经降配后还是一样

![Image](https://github.com/user-attachments/assets/195ac485-8fcc-41e0-bd65-df36cccc4035)

2025-03-30 01:56:26.756 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2025-03-30 01:56:26.759 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2025-03-30 01:56:26.759 | ERROR    | chatchat.webui_pages.utils:get:64 - TypeError: error when get /knowledge_base/list_knowledge_bases: Client.__init__() got an unexpected keyword argument 'proxies'
2025-03-30 01:56:26.759 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2025-03-30 01:56:26.760 Uncaught app exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chatchat/webui.py", line 71, in <module>
    kb_chat(api=api)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chatchat/webui_pages/kb_chat.py", line 118, in kb_chat
    kb_list = [x["kb_name"] for x in api.list_knowledge_bases()]
TypeError: 'NoneType' object is not iterable
/home/ubuntu/.local/lib/python3.10/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
  warnings.warn(
2025-03-30 01:56:37.300 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/upload_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2025-03-30 01:56:37.304 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/upload_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2025-03-30 01:56:37.305 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/upload_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2025-03-30 01:56:37.305 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
^C  Stopping...
2025-03-30 01:57:28.306 | WARNING  | chatchat.startup:start_main_server:315 - Sending SIGKILL to %s
2025-03-30 01:57:28.307 | WARNING  | chatchat.startup:start_main_server:315 - Sending SIGKILL to %s
2025-03-30 01:57:28.308 | INFO     | chatchat.startup:start_main_server:326 - Process status: %s
2025-03-30 01:57:28.308 | INFO     | chatchat.startup:start_main_server:326 - Process status: %s

Aborted!
(myenv) ubuntu@VM-100-5-ubuntu:~/app/Langchain-Chatchat/libs/chatchat-server$ pip list |grep httpx
httpx                       0.27.2
