### ISSUE TITLE
新建支持库报错API未能返回正确的JSON。'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by futureflsl** [chatchat-space/Langchain-Chatchat#5120]
测试环境：
windows x64 
python3.10
langchain-chatchat==0.3.1.3
查看了相关issue都没解决方案，这么明显bug不修复吗，至少报错时候给个明显提示啊
新建知识库时候报错
TypeError: string indices must be integers
2024-12-02 07:30:13.942 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:13.944 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:13.945 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:13.948 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:14.000 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:14.002 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:14.004 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:14.006 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:14.007 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda3\envs\lc\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\anaconda3\envs\lc\Lib\site-packages\chatchat\webui.py", line 69, in <module>
    knowledge_base_page(api=api, is_lite=is_lite)
  File "D:\anaconda3\envs\lc\lib\site-packages\chatchat\webui_pages\knowledge_base\knowledge_base.py", line 374, in knowledge_base_page
    data = [
  File "D:\anaconda3\envs\lc\lib\site-packages\chatchat\webui_pages\knowledge_base\knowledge_base.py", line 377, in <listcomp>
    "id": x["id"],
TypeError: string indices must be integers
2024-12-02 07:30:17.567 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.568 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.570 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.572 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:17.628 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/delete_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.630 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/delete_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.631 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/delete_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.632 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:17.726 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.727 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.728 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.731 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:17.785 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.786 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.788 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:17.791 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:17.792 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda3\envs\lc\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\anaconda3\envs\lc\Lib\site-packages\chatchat\webui.py", line 69, in <module>
    knowledge_base_page(api=api, is_lite=is_lite)
  File "D:\anaconda3\envs\lc\lib\site-packages\chatchat\webui_pages\knowledge_base\knowledge_base.py", line 374, in knowledge_base_page
    data = [
  File "D:\anaconda3\envs\lc\lib\site-packages\chatchat\webui_pages\knowledge_base\knowledge_base.py", line 377, in <listcomp>
    "id": x["id"],
TypeError: string indices must be integers
2024-12-02 07:30:18.454 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.456 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.458 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.459 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:18.512 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/delete_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.513 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/delete_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.515 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/delete_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.517 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:18.605 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.607 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.613 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/update_info: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.613 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:18.683 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.685 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.686 | ERROR    | chatchat.webui_pages.utils:post:87 - TypeError: error when post /knowledge_base/search_docs: Client.__init__() got an unexpected keyword argument 'proxies'
2024-12-02 07:30:18.687 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
2024-12-02 07:30:18.689 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda3\envs\lc\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\anaconda3\envs\lc\Lib\site-packages\chatchat\webui.py", line 69, in <module>
    knowledge_base_page(api=api, is_lite=is_lite)
  File "D:\anaconda3\envs\lc\lib\site-packages\chatchat\webui_pages\knowledge_base\knowledge_base.py", line 374, in knowledge_base_page
    data = [
  File "D:\anaconda3\envs\lc\lib\site-packages\chatchat\webui_pages\knowledge_base\knowledge_base.py", line 377, in <listcomp>
    "id": x["id"],
TypeError: string indices must be integers

**Comment by refkxh** [comment]
可以参见 Issue #5115
