### ISSUE TITLE
[BUG] WEBUI删除知识库文档，会导致知识库问答失败

### ISSUE THREAD

**Issue by Helenailse1** [chatchat-space/Langchain-Chatchat#632]
如题，从知识库已有文件中选择要删除的文件，点击删除后，在问答框输入内容回车报错
Traceback (most recent call last):
  File "/home/miniconda/envs/langchain-ChatGLM/lib/python3.8/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/miniconda/envs/langchain-ChatGLM/lib/python3.8/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/home/miniconda/envs/langchain-ChatGLM/lib/python3.8/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/miniconda/envs/langchain-ChatGLM/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/miniconda/envs/langchain-ChatGLM/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/miniconda/envs/langchain-ChatGLM/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/miniconda/envs/langchain-ChatGLM/lib/python3.8/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "webui.py", line 54, in get_answer
    for resp, history in local_doc_qa.get_knowledge_based_answer(
  File "/home/langchain-ChatGLM/chains/local_doc_qa.py", line 228, in get_knowledge_based_answer
    related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
  File "/home/miniconda/envs/langchain-ChatGLM/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 221, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(embedding, k)
  File "/home/langchain-ChatGLM/vectorstores/MyFAISS.py", line 55, in similarity_search_with_score_by_vector
    _id = self.index_to_docstore_id[i]
KeyError: 421

**Comment by galen2** [comment]
同上

**Comment by dangzheng0430** [comment]
同问

**Comment by mxzgn** [comment]
同问问题出现self.index_to_docstore_id[i]索引位置不对问题

**Comment by Mingxiangyu** [comment]
相同问题！
