### ISSUE TITLE
安装 requirements 报错

### ISSUE THREAD

**Issue by fghhaha** [chatchat-space/Langchain-Chatchat#656]
(langchainchatglm) D:\github\langchain-ChatGLM>pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
ERROR: Exception:
Traceback (most recent call last):
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\commands\install.py", line 342, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\cli\req_command.py", line 433, in get_requirements
    for parsed_req in parse_requirements(
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\req\req_file.py", line 148, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\req\req_file.py", line 335, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\req\req_file.py", line 340, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\req\req_file.py", line 371, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\req\req_file.py", line 549, in get_file_content
    content = auto_decode(f.read())
  File "D:\anaconda3\envs\langchainchatglm\lib\site-packages\pip\_internal\utils\encoding.py", line 34, in auto_decode
    return data.decode(
### UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 780: illegal multibyte sequence**

**Comment by hzg0601** [comment]
这是编码格式不对，最简单的解决方法是你用txt打开，然后另存的时候选择保存为utf-8格式

**Comment by margox** [comment]
如果保存为uft-8不行，试试保存为uft-8 with bom格式

**Comment by li-xunhuan** [comment]
简单粗暴，删掉倒数第二行的那个中文，再来，我就是这么干的，笑死

**Comment by radarfyh** [comment]
草，删除倒数第二行之后真的可以！！！
