### ISSUE TITLE
cpu上运行webui，step3 asking时报错

### ISSUE THREAD

**Issue by wangchao-sh** [chatchat-space/Langchain-Chatchat#66]
web运行，文件加载都正常，asking时报错

README.txt 已成功加载
Traceback (most recent call last):
  File "/home/chwang/.local/lib/python3.8/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/chwang/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/chwang/.local/lib/python3.8/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/chwang/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/chwang/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/chwang/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "webui.py", line 31, in get_answer
    resp, history = kb.get_knowledge_based_answer(
  File "/repo/chaowang/AI/langchain-ChatGLM/knowledge_based_chatglm.py", line 98, in get_knowledge_based_answer
    retriever=vector_store.as_retriever(search_kwargs={"k": VECTOR_SEARCH_TOP_K}),
AttributeError: 'NoneType' object has no attribute 'as_retriever'

**Comment by imClumsyPanda** [comment]
按照报错来说应该是文档已完成load，但还未完成vector_store的生成，完成vector_store生成后前端会有回复。

**Comment by wangchao-sh** [comment]
重新尝试，多等了一会，前端有文档已完成加载的提示了，asking一直是...的等待状态。

![image](https://user-images.githubusercontent.com/127324559/231622058-06beed4c-1ceb-4ebc-ae12-0ee4bee29f07.png)

后端程序还在运行，但是有如下报错：
The dtype of attention mask (torch.int64) is not bool

**Comment by imClumsyPanda** [comment]
cpu 上运行单次回复可能耗时比较长，建议可以先考虑使用命令行 demo 进行测试，目前 Web UI 还在持续完善中。

**Comment by imClumsyPanda** [comment]
目前已更新v 0.1.0新版本，建议更新至最新版代码后再测试看看

**Comment by imClumsyPanda** [comment]
请检查一下protobuf版本或重新pip install -r requirements.txt

wangchao ***@***.***>于2023年4月19日 周三18:02写道：
