### ISSUE TITLE
[BUG] 目前的FAISS删除方法会有BUG / BUG in FAISS delete file method

### ISSUE THREAD

**Issue by silencesoup** [chatchat-space/Langchain-Chatchat#782]
**问题描述 / Problem Description**
当删除文件后，再次检索，可能会出现这样的BUG / When you delete file in gradio, this bug may exist.

Traceback (most recent call last):
  File "/home/<user_name>/.conda/envs/openai_env/lib/python3.10/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/<user_name>/.conda/envs/openai_env/lib/python3.10/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/home/<user_name>/.conda/envs/openai_env/lib/python3.10/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/<user_name>/.conda/envs/openai_env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/<user_name>/.conda/envs/openai_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/<user_name>/.conda/envs/openai_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/<user_name>/.conda/envs/openai_env/lib/python3.10/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/home/<user_name>/langchain-ChatGLM/webui.py", line 53, in get_answer
    for resp, history in local_doc_qa.get_knowledge_based_answer(
  File "/home/<user_name>/langchain-ChatGLM/chains/local_doc_qa.py", line 231, in get_knowledge_based_answer
    related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
  File "/home/<user_name>/.conda/envs/openai_env/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 221, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(embedding, k)
  File "/home/<user_name>/langchain-ChatGLM/vectorstores/MyFAISS.py", line 86, in similarity_search_with_score_by_vector
    _id0 = self.index_to_docstore_id[l]
KeyError: 41589

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python webui.py'，新建知识库，上传若干文件 / Run 'python webui.py', create a new knowledge base, upload files.
2. 询问其中某个文件的问题 / Make a query about a file from the ones you uploaded.
3. 点击 '删除文件'，并删除该文件 / Click '删除文件', delete that file.
4. 再次询问该问题 / Make the same query.
5. 问题可能出现，并非一定会出现，测试中意外发现的 / Problem probably occurs. It doesn‘t always happen.

**环境信息 / Environment Information**
- langchain-ChatGLM [v0.1.16]
- Docker: No
- Model : ChatGLM2-6B
- Embedding: GanymedeNil/text2vec-large-chinese
- System: Linux vm-jupyterhub-server Ubuntu x86_64 GNU/Linux
- Python version: 3.10

**Comment by zfanswer** [comment]
+1， 删除后，问题报错

**Comment by codeAndxv** [comment]
看起来是判断的问题。把 ` if l not in id_set and 0 <= l < len(self.index_to_docstore_id): `改成`if l not in id_set and  l in self.index_to_docstore_id:`

**Comment by Helenailse1** [comment]
+1

**Comment by ArtPei** [comment]
> <img alt="image" width="945" src="https://user-images.githubusercontent.com/38110029/252924432-80452bbd-e58d-4d28-9f44-613bbe0db739.png"> 这是不是意味着，知识文件删除之后，知识删除了文件的相关信息，但是真正的索引数据还在？那再搜索的时候，这些数据还会被搜索到吗？

会...非常蛋疼

**Comment by tomFoxxxx** [comment]
@imClumsyPanda 请问这个问题是不是已经修复了呀

**Comment by imClumsyPanda** [comment]
> <img width="945" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38110029/80452bbd-e58d-4d28-9f44-613bbe0db739">
> 
> 这是不是意味着，知识文件删除之后，知识删除了文件的相关信息，但是真正的索引数据还在？那再搜索的时候，这些数据还会被搜索到吗？

是的，需要从索引建立上解决这个问题，不然不好反向追溯

**Comment by imClumsyPanda** [comment]
> @imClumsyPanda 请问这个问题是不是已经修复了呀

目前能删除，但不是最佳解决方案

**Comment by lqhLoveSmy** [comment]
这种核心的问题要优先处理，其他鸡肋的功能可加可不加
