### ISSUE TITLE
运行web_ui.py, 本地知识库只能问一个问题，问第二个就出现：torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by finyone** [chatchat-space/Langchain-Chatchat#784]
**问题描述 / Problem Description**
运行web_ui.py, 本地知识库只能问一个问题，问第二个就出现：torch.cuda.OutOfMemoryError: CUDA out of memory
 具体错误为：
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 126.00 MiB (GPU 0; 14.76 GiB total capacity; 13.93 GiB already allocated; 113.75 MiB free; 13.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
^CKeyboard interruption in main thread... closing server.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：80ecc08044a1b4d21ea91fe4c83b3c423fa40294
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）： GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:  centos7.9
- Python 版本 / Python version: python3.8.2
 
 16G显存，跑起webui.py后，本地知识库导入了20k的txt文件，结果就问了一个问题，再问第二个，就报错了，错误详细信息如下：

Traceback (most recent call last):
  File "/usr/local/python38/lib/python3.8/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/python38/lib/python3.8/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/python38/lib/python3.8/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/python38/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/python38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/python38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/python38/lib/python3.8/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "webui.py", line 53, in get_answer
    for resp, history in local_doc_qa.get_knowledge_based_answer(
  File "/usr/local/src/langchain-ChatGLM/chains/local_doc_qa.py", line 238, in get_knowledge_based_answer
    for answer_result in self.llm.generatorAnswer(prompt=prompt, history=chat_history,
  File "/usr/local/src/langchain-ChatGLM/models/chatglm_llm.py", line 55, in generatorAnswer
    for inum, (stream_resp, _) in enumerate(self.checkPoint.model.stream_chat(
  File "/usr/local/python38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1311, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "/usr/local/python38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1388, in stream_generate
    outputs = self(
  File "/usr/local/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "/usr/local/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "/usr/local/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 474, in forward
    context_layer, present, attention_probs = attention_fn(
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 313, in attention_fn
    attention_probs = attention_probs.type(dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 126.00 MiB (GPU 0; 14.76 GiB total capacity; 13.93 GiB already allocated; 113.75 MiB free; 13.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
^CKeyboard interruption in main thread... closing server.

**Comment by ywm12345** [comment]
同问，我是多卡部署，当我增加CHUNK_SIZE后，prompt的内容也随之增多，也会把其中一个卡GPU用完，不是多卡部署吗，难道不是使用多个卡的GPU

**Comment by finyone** [comment]
> 同问，我是多卡部署，当我增加CHUNK_SIZE后，prompt的内容也随之增多，也会把其中一个卡GPU用完，不是多卡部署吗，难道不是使用多个卡的GPU

我这只有单卡，单卡也不至于第二个问题就内存不够了。

**Comment by illusions-LYY** [comment]
> > 同问，我是多卡部署，当我增加CHUNK_SIZE后，prompt的内容也随之增多，也会把其中一个卡GPU用完，不是多卡部署吗，难道不是使用多个卡的GPU
> 
> 我这只有单卡，单卡也不至于第二个问题就内存不够了。

我猜是和你`LLM_HISTORY_LEN`设置有关？如果设置不是1，那自然会累积的越来越多。此外Langchain的向量检索也是要用GPU的，有个地方可以设置让Langchain是用GPU还是CPU

**Comment by zfanswer** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/637#issuecomment-1594218771

我的经验是适当调整参数减少history里传给LLM的文本长度

**Comment by finyone** [comment]
> > > 同问，我是多卡部署，当我增加CHUNK_SIZE后，prompt的内容也随之增多，也会把其中一个卡GPU用完，不是多卡部署吗，难道不是使用多个卡的GPU
> > 
> > 
> > 我这只有单卡，单卡也不至于第二个问题就内存不够了。
> 
> 我猜是和你`LLM_HISTORY_LEN`设置有关？如果设置不是1，那自然会累积的越来越多。此外Langchain的向量检索也是要用GPU的，有个地方可以设置让Langchain是用GPU还是CPU

在哪里设置langchain使用cpu呢？

**Comment by finyone** [comment]
> [#637 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/637#issuecomment-1594218771)
> 
> 我的经验是适当调整参数减少history里传给LLM的文本长度

的确是减少了history，但是这样还有意义吗？减少history，多轮对话就跟说胡话是的，完全不对。

**Comment by zfanswer** [comment]
> > [#637 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/637#issuecomment-1594218771)
> > 我的经验是适当调整参数减少history里传给LLM的文本长度
> 
> 的确是减少了history，但是这样还有意义吗？减少history，多轮对话就跟说胡话是的，完全不对。

说了这是显存不够的情况下的测试方案，我也不确定history长了显存就爆是不是所谓的BUG。
现在想解决要么改参数，要么就加显存。

**Comment by finyone** [comment]
> > > [#637 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/637#issuecomment-1594218771)
> > > 我的经验是适当调整参数减少history里传给LLM的文本长度
> > 
> > 
> > 的确是减少了history，但是这样还有意义吗？减少history，多轮对话就跟说胡话是的，完全不对。
> 
> 说了这是显存不够的情况下的测试方案，我也不确定history长了显存就爆是不是所谓的BUG。 现在想解决要么改参数，要么就加显存。

谢谢大佬

**Comment by zfanswer** [comment]
> > > > [#637 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/637#issuecomment-1594218771)
> > > > 我的经验是适当调整参数减少history里传给LLM的文本长度
> > > 
> > > 
> > > 的确是减少了history，但是这样还有意义吗？减少history，多轮对话就跟说胡话是的，完全不对。
> > 
> > 
> > 说了这是显存不够的情况下的测试方案，我也不确定history长了显存就爆是不是所谓的BUG。 现在想解决要么改参数，要么就加显存。
> 
> 谢谢大佬

客气了。
