### ISSUE TITLE
启动异常ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by hy928302776** [chatchat-space/Langchain-Chatchat#786]
启动出现以下问题，怎么回事
Traceback (most recent call last):
  File "/Users/huangying/PycharmProjects/aifin/api.py", line 9, in <module>
    import pydantic
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
    # + Value   | Meaning                                 |
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后重试
