### ISSUE TITLE
[BUG]加载本地知识库之后，无法再与GLM2-6B进行交互

### ISSUE THREAD

**Issue by yaxiyeye** [chatchat-space/Langchain-Chatchat#787]
**问题描述 / Problem Description**
在成功运行webui之后，在加载本地库的时候出现了报错

**复现问题的步骤 / Steps to Reproduce**
在点击加载的本地库之后，就会出现报错，输入栏变成error

**预期的结果 / Expected Result**
预期出现是正常执行
**实际结果 / Actual Result**
实际发生了报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：
- 加载了GLM2-68，在windows下环境部署

- 在加载 Embedding 模型的时候出现了
- WARNING 2023-07-05 22:26:47,410-1d: No sentence-transformers model found with name C:\Users\pc\.cache\torch\sentence_transformers\GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
这样的warning
- 操作系统及版本 / Operating system and version:
- WIN10
- Python 版本 / Python version:
- 3.10.9

**附加信息 / Additional Information**
`Traceback (most recent call last):
  File "C:\Users\pc\AppData\Roaming\Python\Python310\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\pc\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\pc\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\pc\AppData\Roaming\Python\Python310\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\pc\AppData\Roaming\Python\Python310\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\ProgramData\anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "D:\ProgramData\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "C:\Users\pc\AppData\Roaming\Python\Python310\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "d:\ChatGLM2-6B\langchain-ChatGLM-master\webui.py", line 54, in get_answer
    for resp, history in local_doc_qa.get_knowledge_based_answer(
  File "d:\ChatGLM2-6B\langchain-ChatGLM-master\chains\local_doc_qa.py", line 231, in get_knowledge_based_answer
    related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
  File "C:\Users\pc\AppData\Roaming\Python\Python310\site-packages\langchain\vectorstores\faiss.py", line 259, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(
TypeError: MyFAISS.similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'`
以上是报错信息

**Comment by ANHDY** [comment]
请问你解决了吗？我也遇到了跟你一样的问题

**Comment by wmwinner** [comment]
> 请问你解决了吗？我也遇到了跟你一样的问题

有可能是版本问题，我修改了版本，就可以运行了
![图片](https://github.com/chatchat-space/langchain-ChatGLM/assets/38877864/57cb4c19-ab2f-4d8e-9c49-fc539ae2547f)

**Comment by zRzRzRzRzRzRzR** [comment]
使用最新版本可以解决这个问题。由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起
