### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'langchain.schema.document'; 'langchain.schema' is not a package

### ISSUE THREAD

**Issue by BoFan-tunning** [chatchat-space/Langchain-Chatchat#816]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 /加载知识库报错

ModuleNotFoundError: No module named 'langchain.schema.document'; 'langchain.schema' is not a package

**Comment by fufeng01** [comment]
Traceback (most recent call last):
  File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\glm\langchain-ChatGLM\webui.py", line 176, in change_vs_name_input
    gr.update(choices=local_doc_qa.list_file_from_vector_store(vs_path), value=[]), \
  File "D:\glm\langchain-ChatGLM\chains\local_doc_qa.py", line 306, in list_file_from_vector_store
    vector_store = load_vector_store(vs_path, self.embeddings)
  File "D:\glm\langchain-ChatGLM\chains\local_doc_qa.py", line 34, in load_vector_store
    return MyFAISS.load_local(vs_path, embeddings)
  File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\faiss.py", line 508, in load_local
    docstore, index_to_docstore_id = pickle.load(f)
ModuleNotFoundError: No module named 'langchain.schema.document'; 'langchain.schema' is not a package

**Comment by Z-yq** [comment]
你这是用了A版本的langchain制作了知识库，然后利用B版本的langchain来加载，统一制作、加载知识库时的langchain版本

**Comment by MrDaoyuan** [comment]
Have you saved this problem? I have the same issue.

**Comment by MrDaoyuan** [comment]
> 你这是用了A版本的langchain制作了知识库，然后利用B版本的langchain来加载，统一制作、加载知识库时的langchain版本

你知道怎么解决这个问题吗？我也有同样的问题，我已经安装了requirements.txt里要求的0.0.174版本。

**Comment by gechengze** [comment]
是不是新建一个知识库就行了？不要用自带的那个samples

**Comment by HelixPark** [comment]
> 

是的，每次都需要新建知识库，不要用老的
