### ISSUE TITLE
[BUG] 使用webui.py能正常启动，界面正常加载，点按钮就显示ERROR

### ISSUE THREAD

**Issue by yyg547436708** [chatchat-space/Langchain-Chatchat#841]
使用webui.py能正常启动，但在新建知识库，点击添加至知识库选项就直接显示ERROR
然后跟踪了一下原因是gradio在使用
demo
 .queue(concurrency_count=3)
 .launch(server_name='localhost',
         server_port=17860,
         show_api=False,
         share=False,
         inbrowser=False)
中的queue造成，会调用一个ws://localhost:17860/queue/join，然后有{"msg": "process_completed", "output": {"error": ""}, "success": false}，不知道为什么，一直无法解决，应该是gradio的原因

**Comment by MrDaoyuan** [comment]
I have the same problem.

**Comment by galen2027** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "webui.py", line 53, in get_answer
    for resp, history in local_doc_qa.get_knowledge_based_answer(
  File "/langchain-ChatGLM/chains/local_doc_qa.py", line 228, in get_knowledge_based_answer
    related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
  File "/usr/local/lib/python3.8/dist-packages/langchain/vectorstores/faiss.py", line 221, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(embedding, k)
  File "/langchain-ChatGLM/vectorstores/MyFAISS.py", line 82, in similarity_search_with_score_by_vector
    _id0 = self.index_to_docstore_id[l]
KeyError: 11
我也有类似的问题，这是通过docker logs看到的问题。

**Comment by ilovesouthpark** [comment]
webui.py里面webui的端口从7860换成其他试试。

**Comment by galen2027** [comment]
我用的不是默认端口，自己修改为8090，并且自己训练服务器上没有其它服务占用端口。
