### ISSUE TITLE
NameError: name 'chatglm' is not defined

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#90]
This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
langchain-ChatGLM README.md 已成功加载
Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/autodl-tmp/chatglm/langchain-ChatGLM-master/webui.py", line 118, in <lambda>
    kb.init_knowledge_vector_store(
  File "/root/autodl-tmp/chatglm/langchain-ChatGLM-master/knowledge_based_chatglm.py", line 73, in init_knowledge_vector_store
    vector_store = FAISS.from_documents(docs, embeddings)
NameError: name 'embeddings' is not defined
langchain-ChatGLM README.md 已成功加载
Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/autodl-tmp/chatglm/langchain-ChatGLM-master/webui.py", line 118, in <lambda>
    kb.init_knowledge_vector_store(
  File "/root/autodl-tmp/chatglm/langchain-ChatGLM-master/knowledge_based_chatglm.py", line 73, in init_knowledge_vector_store
    vector_store = FAISS.from_documents(docs, embeddings)
NameError: name 'embeddings' is not defined
Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/autodl-tmp/chatglm/langchain-ChatGLM-master/webui.py", line 31, in get_answer
    resp, history = kb.get_knowledge_based_answer(
  File "/root/autodl-tmp/chatglm/langchain-ChatGLM-master/knowledge_based_chatglm.py", line 92, in get_knowledge_based_answer
    chatglm.history = chat_history
NameError: name 'chatglm' is not defined

**Comment by imClumsyPanda** [comment]
在之前版本中模型未完成加载时就开始文件加载会出现这个报错，请尝试今天新发布的v 0.1.0版本，已修改为启动时直接加载模型，且具备相关报错信息的消息提醒
