### ISSUE TITLE
报错：RuntimeError: expected scalar type Double but found Float

### ISSUE THREAD

**Issue by wangcong607** [chatchat-space/Langchain-Chatchat#923]
**问题描述 / Problem Description**
报错信息：
Traceback (most recent call last):
  File "D:\GPT\langchain-ChatGLM\models\base\base.py", line 114, in gen
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "D:\GPT\langchain-ChatGLM\models\base\base.py", line 163, in generate_with_callback
    self._generate_answer(**kwargs)
  File "D:\GPT\langchain-ChatGLM\models\chatglm_llm.py", line 82, in _generate_answer
    for inum, (stream_resp, _) in enumerate(self.checkPoint.model.stream_chat(
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 1058, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 1143, in stream_generate
    outputs = self(
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 932, in forward
    transformer_outputs = self.transformer(
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 828, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 638, in forward
    layer_ret = layer(
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 542, in forward
    attention_output, kv_cache = self.self_attention(
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 374, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 504, in forward
    output = W8A16LinearCPU.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "D:\GPT\langchain-ChatGLM\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 248, in forward
    output = inp.mm(weight.t())
RuntimeError: expected scalar type Double but found Float

Process finished with exit code 0

**复现问题的步骤 / Steps to Reproduce**
使用chatglm2-6b-int4模型

**环境信息 / Environment Information**
我是在cpu上跑的测试，因为内存不够运行的是int4版本，之前在服务器上使用非量化模型好像没有这个问题

**Comment by kryst5l** [comment]
一样的碰到了这个问题。

**Comment by danny-zhu** [comment]
使用量化后的模型chatglm2-6b-int4启动项目后，报错：expected scalar type Double but found Float。
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/12292357/e59db7d7-6fa5-4908-9bed-a479a45abce2)

这是因为models\loader\loader.py加载模型时给的参数精度不对，默认用torch.float，改成torch.float32即可。
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/12292357/6636050c-2bd1-4fd2-81fc-1ab2d2078b32)

**Comment by kryst5l** [comment]
> 使用量化后的模型chatglm2-6b-int4启动项目后，报错：expected scalar type Double but found Float。 ![image](https://user-images.githubusercontent.com/12292357/258270870-e59db7d7-6fa5-4908-9bed-a479a45abce2.png)
> 
> 这是因为models\loader\loader.py加载模型时给的参数精度不对，默认用torch.float，改成torch.float32即可。 ![image](https://user-images.githubusercontent.com/12292357/258270895-6636050c-2bd1-4fd2-81fc-1ab2d2078b32.png)

这是哪个文件夹下面的啊 ，models\loader\loader.py             loader下面好像没有这个文件

**Comment by kryst5l** [comment]
> 使用量化后的模型chatglm2-6b-int4启动项目后，报错：expected scalar type Double but found Float。 ![image](https://user-images.githubusercontent.com/12292357/258270870-e59db7d7-6fa5-4908-9bed-a479a45abce2.png)
> 
> 这是因为models\loader\loader.py加载模型时给的参数精度不对，默认用torch.float，改成torch.float32即可。 ![image](https://user-images.githubusercontent.com/12292357/258270895-6636050c-2bd1-4fd2-81fc-1ab2d2078b32.png)

好的 看到了，langchain-ChatGLM/models/loader 这个下面 我试试看

**Comment by kryst5l** [comment]
> 使用量化后的模型chatglm2-6b-int4启动项目后，报错：expected scalar type Double but found Float。 ![image](https://user-images.githubusercontent.com/12292357/258270870-e59db7d7-6fa5-4908-9bed-a479a45abce2.png)
> 
> 这是因为models\loader\loader.py加载模型时给的参数精度不对，默认用torch.float，改成torch.float32即可。 ![image](https://user-images.githubusercontent.com/12292357/258270895-6636050c-2bd1-4fd2-81fc-1ab2d2078b32.png)

好的 看到了，langchain-ChatGLM/models/loader 这个下面 我试试看

**Comment by danny-zhu** [comment]
torch.float在gpu里面跑，默认是32位的，所以加载int4模型没事，到了cpu里运行的时候，torch.float默认是64位的，也就是double类型的所以报类型不匹配的错。cpu跑的话，推理速度非常慢，大约要慢一个数量级。

**Comment by kryst5l** [comment]
> 

我改了还是一样的报错~  你改了之后成功了不~~  知道很慢，就是试试想解决一下这个问题~
