### ISSUE TITLE
pip install -r requirements.txt报错

### ISSUE THREAD

**Issue by zppvae** [chatchat-space/Langchain-Chatchat#932]
ERROR: Exception:                                                                                                                            
Traceback (most recent call last):                                                                                                           
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\commands\install.py", line 342, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\cli\req_command.py", line 433, in get_requirements
    for parsed_req in parse_requirements(
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\req\req_file.py", line 148, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\req\req_file.py", line 335, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\req\req_file.py", line 340, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\req\req_file.py", line 371, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\req\req_file.py", line 549, in get_file_content
    content = auto_decode(f.read())
  File "e:\pythonproject\langchain-chatglm-master\pyqt\lib\site-packages\pip\_internal\utils\encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 454: illegal multibyte sequence

**Comment by liunux4odoo** [comment]
把requirements.txt里的中文注释全删掉再安装。

**Comment by rchlz** [comment]
我在windows也遇到类似问题，你需要设置PYTHONUTF8=1为环境变量；
linux下不存在这个问题

**Comment by huyang19881115** [comment]
paddlepaddle==2.4.2
paddleocr~=2.6.1.3
我的是安装这2个包一直报错，python是3.10的版本，不知道咋解决

**Comment by liunux4odoo** [comment]
@huyang19881115 你可以把这2包注释掉不安装，运行最新版程序试试。新版里把pdf和image加载器变成了动态引入，只要不上传pdf和图片知识文件，应该就没问题。
