### ISSUE TITLE
模型调用api之后无法返回结果.

### ISSUE THREAD

**Issue by daxian-lh** [chatchat-space/Langchain-Chatchat#962]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / 模型调用api之后无法返回结果.
报错如下：
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:/langchain-ChatGLM/api.py", line 333, in local_doc_chat
    for resp, history in local_doc_qa.get_knowledge_based_answer(
  File "D:\langchain-ChatGLM\chains\local_doc_qa.py", line 237, in get_knowledge_based_answer
    related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\langchain\vectorstores\faiss.py", line 221, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(embedding, k)
  File "D:\langchain-ChatGLM\vectorstores\MyFAISS.py", line 51, in similarity_search_with_score_by_vector
    scores, indices = self.index.search(vector, k)
  File "D:\Program Files\Conda\envs\glm2\lib\site-packages\faiss\class_wrappers.py", line 329, in replacement_search
    assert d == self.d
AssertionError

**Comment by developservertwo** [comment]
同样出现这个问题，embedding_model_dict中使用text2vec则不报错，改为text2vec-base、text2vec-base-chinese-paraphrase等，使用就会报这个错误
