### ISSUE TITLE
模型加载失败

### ISSUE THREAD

**Issue by renllll** [chatchat-space/Langchain-Chatchat#964]
Traceback (most recent call last):
  File "cli_demo.py", line 88, in <module>
    main()
  File "cli_demo.py", line 16, in main
    llm_model_ins = shared.loaderLLM()
  File "C:\Users\renyi\Downloads\langchain-ChatGLM-master\models\shared.py", line 39, in loaderLLM
    loaderCheckPoint.reload_model()
  File "C:\Users\renyi\Downloads\langchain-ChatGLM-master\models\loader\loader.py", line 453, in reload_model
    self.model, self.tokenizer = self._load_model()
  File "C:\Users\renyi\Downloads\langchain-ChatGLM-master\models\loader\loader.py", line 252, in _load_model
    model = LoaderClass.from_pretrained(checkpoint, **params).to(self.llm_device, dtype=float)
  File "D:\anaconda\envs\py385\lib\site-packages\transformers\models\auto\auto_factory.py", line 462, in from_pretrained
    return model_class.from_pretrained(
  File "D:\anaconda\envs\py385\lib\site-packages\transformers\modeling_utils.py", line 2542, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\anaconda\envs\py385\lib\site-packages\transformers\modeling_utils.py", line 462, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\renyi\Downloads\langchain-ChatGLM-master\models\chatglm-6b-int4\pytorch_model.bin' at 'C:\Users\renyi\Downloads\langchain-ChatGLM-master\models\chatglm-6b-int4\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
运行cli_demo时为啥会报以上错误

**Comment by super-tian** [comment]
内存溢出导致的吧，我碰到过类似的
