### ISSUE TITLE
下载模型失败

### ISSUE THREAD

**Issue by laksg2009** [chatchat-space/Langchain-Chatchat#971]
**问题描述 / Problem Description**
运行python webui.py后进入下载阶段，到61就报错了。

**实际结果 / Actual Result**
PS D:\VS Code Project\langchain-ChatGLM-master> python webui.py
INFO  2023-07-31 08:28:18,679-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: D:\VS Code Project\langchain-ChatGLM-master
flagging username: 59c4cfbb981f4e318fe313ac45c353ed

load_model_config THUDM/chatglm2-6b...
Loading THUDM/chatglm2-6b...
Downloading shards:   0%|                                                                                                                                                                               | 0/7 [01:11<?, ?it/s]
Traceback (most recent call last):n:  61%|███████████████████████████████████████████████████████████████████████████████████████▊                                                       | 1.12G/1.83G [01:10<00:39, 17.7MB/s] 
  File "D:\VS Code Project\langchain-ChatGLM-master\webui.py", line 334, in <module>
    model_status = init_model()
  File "D:\VS Code Project\langchain-ChatGLM-master\webui.py", line 106, in init_model
    llm_model_ins = shared.loaderLLM()
  File "D:\VS Code Project\langchain-ChatGLM-master\models\shared.py", line 39, in loaderLLM
    loaderCheckPoint.reload_model()
  File "D:\VS Code Project\langchain-ChatGLM-master\models\loader\loader.py", line 453, in reload_model
    self.model, self.tokenizer = self._load_model()
  File "D:\VS Code Project\langchain-ChatGLM-master\models\loader\loader.py", line 129, in _load_model
    LoaderClass.from_pretrained(checkpoint,
  File "D:\Program Files\Python 310\lib\site-packages\transformers\models\auto\auto_factory.py", line 462, in from_pretrained
    return model_class.from_pretrained(
  File "D:\Program Files\Python 310\lib\site-packages\transformers\modeling_utils.py", line 2523, in from_pretrained
    resolved_archive_file, sharded_metadata = get_checkpoint_shard_files(
  File "D:\Program Files\Python 310\lib\site-packages\transformers\utils\hub.py", line 934, in get_checkpoint_shard_files
    cached_filename = cached_file(
  File "D:\Program Files\Python 310\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "D:\Program Files\Python 310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Program Files\Python 310\lib\site-packages\huggingface_hub\file_download.py", line 1364, in hf_hub_download
    http_get(
  File "D:\Program Files\Python 310\lib\site-packages\huggingface_hub\file_download.py", line 547, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 1827780615 but has size 1123310804 ((…)l-00001-of-00007.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
Downloading (…)l-00001-of-00007.bin:  61%|███████████████████████████████████████████████████████████████████████████████████████▉ 

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：# LLM 名称
LLM_MODEL = "chatglm2-6b"
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：chatglm2-6b
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：不懂
- 操作系统及版本 / Operating system and version:Windows 11 专业版
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by honglyua** [comment]
看样子是网络问题，从huggingface下载模型失败。可以参考这个，先从清华镜像离线下载好。https://github.com/THUDM/ChatGLM2-6B#%E4%BB%8E%E6%9C%AC%E5%9C%B0%E5%8A%A0%E8%BD%BD%E6%A8%A1%E5%9E%8B

**Comment by favouriter** [comment]
https://github.com/favouriter/but4.git
我从huggingface下载模型非常慢，我在上面项目里写了一个脚本fast_host.py，可以检测优质的IP地址
