### ISSUE TITLE
启动webui.py后报错，模型可以加载

### ISSUE THREAD

**Issue by zppvae** [chatchat-space/Langchain-Chatchat#995]
Traceback (most recent call last):                                                                         
  File "E:\pythonProject\langchain-ChatGLM-master\models\base\base.py", line 114, in gen                   
    ret = self.mfunc(callback=_callback, **self.kwargs)                                                    
  File "E:\pythonProject\langchain-ChatGLM-master\models\base\base.py", line 163, in generate_with_callback
    self._generate_answer(**kwargs)
  File "E:\pythonProject\langchain-ChatGLM-master\models\chatglm_llm.py", line 82, in _generate_answer
    for inum, (stream_resp, _) in enumerate(self.checkPoint.model.stream_chat(
  File "E:\Python\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 1311, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "E:\Python\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 1388, in stream_generate
    outputs = self(
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 445, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 388, in forward
    output = W8A16LinearCPU.apply(input, self.weight, self.weight_scale, self.weight_bit_width,
  File "E:\Python\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 80, in forward
    weight = extract_weight_to_float(quant_w, scale_w, weight_bit_width, quantization_cache=quantization_cache)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 316, in extract_weight_to_float
    func(
TypeError: 'NoneType' object is not callable

python版本：3.10
开发环境：windows10，pycharm，cpu

**Comment by zRzRzRzRzRzRzR** [comment]
尝试使用最新代码看是否解决问题
