### ISSUE TITLE
[BUG] 多卡部署chatglm2-6b-32k报错

### ISSUE THREAD

**Issue by gumanchang** [chatchat-space/Langchain-Chatchat#999]
Traceback (most recent call last):
  File "/data/gumanchang/langchain-ChatGLM/models/base/base.py", line 114, in gen
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/data/gumanchang/langchain-ChatGLM/models/base/base.py", line 163, in generate_with_callback
    self._generate_answer(**kwargs)
  File "/data/gumanchang/langchain-ChatGLM/models/chatglm_llm.py", line 100, in _generate_answer
    response, _ = self.checkPoint.model.chat(
  File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-32k/455746d4706479a1cbbd07179db39eb2741dc692/modeling_chatglm.py", line 1042, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-32k/455746d4706479a1cbbd07179db39eb2741dc692/modeling_chatglm.py", line 946,in forward
    transformer_outputs = self.transformer(
  File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-32k/455746d4706479a1cbbd07179db39eb2741dc692/modeling_chatglm.py", line 836,in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-32k/455746d4706479a1cbbd07179db39eb2741dc692/modeling_chatglm.py", line 655,in forward
    presents = torch.cat((presents, kv_cache), dim=0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensorsin method wrapper_CUDA_cat)

有人遇见过吗？

**Comment by deku0818** [comment]
同问

**Comment by forcemeter** [comment]
同问

**Comment by forcemeter** [comment]
我遇到了这个问题，通过手动指定GPU 解决了。

代码是 master 最新，chatglm-cuda:latest 由 `Dockerfile-cuda` 构建

```shell
docker rm -f langchain-glm-cuda
docker run --gpus 0,1 -it --name langchain-glm-cuda -p 8080:7860 \
-v ./configs/model_config_docker.py:/chatGLM/configs/model_config.py \
-v ./webui.py:/chatGLM/webui.py \
-v ./knowledge_base:/chatGLM/knowledge_base \
-v ./data/root:/root \
-v /files/huggingface:/files/huggingface \
chatglm-cuda:latest
```

**Comment by deku0818** [comment]
> @gumanchang @deku0818
> 
> 我也遇到了这个问题，通过手动指定GPU 解决了，你们试试这个问题能不能解决。
> 
> 代码是 master 最新，chatglm-cuda:latest 由 构建`Dockerfile-cuda`
> 
> ```shell
> docker rm -f langchain-glm-cuda
> docker run --gpus 0,1 -it --name langchain-glm-cuda -p 8080:7860 \
> -v ./configs/model_config_docker.py:/chatGLM/configs/model_config.py \
> -v ./webui.py:/chatGLM/webui.py \
> -v ./knowledge_base:/chatGLM/knowledge_base \
> -v ./data/root:/root \
> -v /files/huggingface:/files/huggingface \
> chatglm-cuda:latest
> ```

我是conda部署的，该如何修改呢

**Comment by g-pigstar** [comment]
尝试下 loader.py文件中  num_gpus = torch.cuda.device_count() 修改为1， 试试？(不保证有效果)

**Comment by bk007lz** [comment]
如何解决的？

**Comment by janesunflower** [comment]
> 尝试下 loader.py文件中 num_gpus = torch.cuda.device_count() 修改为1， 试试？(不保证有效果)

亲测有效

**Comment by wj1017090777** [comment]
能正常启动了，但是为什么多卡会报错呢

**Comment by Peri-albert** [comment]
CUDA_VISIBLE_DEVICES=0 python webui.py

**Comment by Peri-albert** [comment]
求作者大大调整一下多卡策略，这个问题我也遇到了，并且想知道为啥更新了最新版本的多卡“负载均衡"还是会出现这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
最新代码中的多卡负载确实是均衡的，如果最新代码还有问题，可以重新提出issue
